### PR TITLE
Public library: Add Adedanha, others

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library
- Adedanha. New game by RaphaelAlvez.  Similar to Scattergories.
- Liar's Dice. New game by RaphaelAlvez.
- Blue. Updated after DevGameNight. Added automation to arrows.
- Flora. Updated after DevGameNight. Added 2 automation buttons, discard holders, changed one card color, updated Unicode to images, removed grid from bottom row, and changed onLeave flip behavior.

Public Tutorials:
- changeRoutine.  New. Uses the concept of sliders to illustrate changeRoutine.
- Timer. New. Has basic variant and variant demonstrating how to made a card dealing animation.
- Button appearance. Revised to reflect changes to button color properties from PR #461. Add a basic appearance intro and revised the text only appearance variant.
- Hexagonal cards. Updated “find width” functions to properly limit decimal places to 3.
- Random.  Removed as it is no longer a stand-alone function.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3483/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Changed files successfully loaded from new library.json file.

**Comment by 96LawDawg** [comment]
Although I am deleting RANDOM as a tutorial, I will incorporate some of that into a new Math (using dynamic expressions) tutorial I'm working on.

**Review by ArnoldSmith86 — APPROVED** [review]
Adedanha on mobile with word suggesting keyboards is kinda pointless. 😁  But I guess you still want unique words.

I'm not a big fan of its library image but it's not like most of mine are any better.

Hexagonal basics: one button should be `find height`, right?

**Pull request merged**
