### PR TITLE
added commands to align and distribute widgets

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
As far as I'm concerned this is the biggest feature gap to Ghetto Editor.

Multi-select a few widgets, put the cursor to `x` or `y`, press `align`, select options, press `Go`. All selected widgets will get the same left/top/center/right/bottom coordinate. Even works across different parents.

Multi-select a few widgets, put the cursor to `x` or `y`, press `distribute`. The spacing between all selected widgets is equalized. Even works across different parents.

Because `align` uses it, this also introduces `select` as an `INPUT` type. Something like this:
```
      { label: 'Coordinate', type: 'select', options: [ { value: 0.5, text: 'Center' }, { value: 0, text: 'Top/Left' }, { value: 1, text: 'Bottom/Right'  } ] },
      { label: 'Reference',  type: 'select', options: [ { value: 'First' }, { value: 'Last' }, { value: 'Center of all' } ] }
```
Please test if this also works (well enough) when using `INPUT` in a routine.

And because @rogerl50 reminded me that macOS can't use `CTRL`+`SHIFT`-click, multi-selection can now also be triggered by `CTRL`-rightclick.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3634/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
Is multi-selection still done with Ctrl-Shift? Because that still doesn't work for me in MacOS/Firefox.

**Comment by ArnoldSmith86** [comment]
Yes. `Shift`+`F1` should also work while hovering widgets.

**Comment by rogerl50** [comment]
> Yes. `Shift`+`F1` should also work while hovering widgets.

It does. Thanks.

**Comment by ArnoldSmith86** [comment]
`CTRL`-clicking to edit a widget works though, right?

**Comment by rogerl50** [comment]
> `CTRL`-clicking to edit a widget works though, right?

Yes. It's just Ctrl-Shift that is picked up by the OS to create a right-click.

**Comment by rogerl50** [comment]
Note that if there are lots of widgets under your cursor, the only way to multi-select one is using Shift-Fn, and depending on the ordering, the widget may not be assign a function key, or its assignment may not be visible on-screen.

**Comment by ArnoldSmith86** [comment]
Yes. That's a problem for another time though. :smile:

**Comment by ArnoldSmith86** [comment]
> Is multi-selection still done with Ctrl-Shift? Because that still doesn't work for me in MacOS/Firefox.

Please test if `CTRL`-rightclicking works for you.

**Comment by rogerl50** [comment]
> > Is multi-selection still done with Ctrl-Shift? Because that still doesn't work for me in MacOS/Firefox.
> 
> Please test if `CTRL`-rightclicking works for you.

It does. Of course, only for widgets that aren't stacked.

**Comment by ArnoldSmith86** [comment]
Yes. For the others you should use the function keys. Of course that only works for up to 12 widgets...

**Comment by ArnoldSmith86** [comment]
True. Unrelated to the PR though.

**Comment by 96LawDawg** [comment]
I tested everything, including setting up the `INPUT` using the `select` type.  I didn't do anything with the values, just made sure the mode worked.  Not sure why I would ever want that.

Everything worked, but one thing is not intuitive.  The align feature asks about first and last.  That literally means the widget you selected first and last.  I initially thought it meant lowest and highest value.  I see more value in having something like smallest/largest than I do in which order I selected the widgets.  I'd like to see an option to align to the widget that is farthest to the left or has the biggest y or whatever.  That would be more like Ghetto and more useful.

**Comment by ArnoldSmith86** [comment]
I think the `First` option is very useful. But that doesn't mean we can't add yours.

**Comment by ArnoldSmith86** [comment]
Is this what you had in mind, @96LawDawg?

**Review by 96LawDawg — APPROVED** [review]
Yes.  Thank you.  Approved through test.

**Pull request merged**
