### PR TITLE
allow 0 as `INPUT` number `min` or `max`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The expression `field.min || 1` would always fallback to `1` if you use a `0`.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3671/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
Maybe I don't see the change.  Before you could manually set an INPUT number to zero, but you couldn't scroll down to zero.  Also, a variable could set it to any number.  Now it appears to be the same.

**Comment by ArnoldSmith86** [comment]
Look at http://212.47.248.129:3670/TeamII (different PR). The `Predict` button uses the `min` property. I had to set it to `"0"` instead of `0` because of this bug.

**Review by bjalder26 — APPROVED** [review]
> Look at http://212.47.248.129:3670/TeamII (different PR). The `Predict` button uses the `min` property. I had to set it to `"0"` instead of `0` because of this bug.

I see.  I didn't change the default (of 1).  Now you can scroll down to any set min rather than it stopping at 1.  Approved through testing.

**Pull request merged**
