### PR TITLE
Adds Tarocchi Siciliani

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
As requested by A.C.GiocoTarocchiSicilia on discord

Still need revisions

https://discord.com/channels/770758631146782780/789103957938012171/1130859175241596938

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1798/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1798-pr-test`.

**Comment by 96LawDawg** [comment]
I cleaned up the metadata some so that it is "good enough" for the public library.  Formatting and readability enhancements could still be made, but I'm not going to do those.

I also deleted something in the deck that linked to a pcio playing card back (that was actually hidden by the custom back used in each variant).

**Comment by RaphaelAlvez** [comment]
Looks good to me. @96LawDawg feel free to review

**Review by 96LawDawg — APPROVED** [review]
Approved.  Did not test the room, but this has gotten lots of play testing by the designer.

**Pull request merged**
