### PR TITLE
fixed card order when dropping a pile into a hand

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The code is really not pretty but it seems to fix the issue for me. I really hope one day somebody comes along with a perfect solution for all that pile+holder mess.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3655/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Hmm, shouldn't the order be reversed?

**Comment by robartsd** [comment]
What is the `+ i/100` part for?

**Comment by ArnoldSmith86** [comment]
It adds the cards to the holder at the position where the pile was dropped. It adds a hundredth of a pixel to each card coordinate so that they are in the correct (?) order for when the next step assigns new z values based on the card positions and rearranges them according to `stackOffsetX` etc.

**Review by 96LawDawg — APPROVED** [review]
It fixes the problem in the new implementation of The Team.  Doesn't seem to hurt anything else I tested.  Approved through test.

**Comment by ArnoldSmith86** [comment]
But do you think the order should be reversed? Right now the topmost card in the pile will become the leftmost card in the hand. When they overlap it will then be the bottommost card.

**Comment by 96LawDawg** [comment]
I just realized what you are doing in The Team.  You sorted while it was in a pile waiting to be dragged to the hand.  For some reason (I'm slow) I thought this was a sorting problem in the hand.  But instead it was a pile distribution problem once it got to the hand.  Again, I'm slow.

I honestly don't think it matters.  99% of the time in games I'm dragging a pile face down and I don't know what cards are in there.  If the order of the cards is important to the game then we still need better overall implementation for how cards are moved around behind the scenes (aka #77)

**Comment by robartsd** [comment]
> But do you think the order should be reversed? Right now the topmost card in the pile will become the leftmost card in the hand. When they overlap it will then be the bottommost card.

Reversing would match PCIO.

**Comment by Ingegneus** [comment]
i think the bottom card of a pile should be the leftmost card in a hand. rn it does the opposite. @96LawDawg i agree that in the majority of games implemented in vtt rn the order of a pile dragged in a holder doesn't matter but in smash up (a game i play regularly) it is quite essential since there are cases where you can order your draw and/or discard pile. a card placed at the bottom of the deck should stay there until i say otherwise XD

**Pull request merged**
