### PR TITLE
new compute function: shuffle

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Shuffle takes a string or array as argument and returns a string or array with its components shuffled (randomly permutated). The source is not altered.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1772/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1772-pr-test`.

**Comment by 96LawDawg** [comment]
I have wanted this for a LONG, LONG time.  Thank you.  I haven't had a chance to test it yet, but I will soon.  Could have used it twice today already.

**Review by 96LawDawg — APPROVED** [review]
Approved through test and code review.  Let me update the tutorial before you merge it.

**Comment by 96LawDawg** [comment]
Ready to merge.

**Pull request merged**
