### PR TITLE
Clear erroneous audio element when invalid audio

### PR DESCRIPTION
**Pull request by bjalder26**
When an invalid src is input for the AUDIO function it creates an audio element that will not be cleared from the DOM tree.  The reason why it will not be cleared is because currently unless a length is set in the JSON the JavaScript will remove the element once it has finished playing.  Since an invalid audio won't play, the element won't be cleared.

The point of this PR is to clear it immediately.  If there is an error with the AUDIO, then the audio element will be removed.

An invalid src should quickly be cleared from the developer tools.  A valid one should be cleared after the set period (default, when the audio ends).
image

To see it "work", just open these two rooms.  Open the developer tools to the elements tab, and start clicking the button.
PR: http://212.47.248.129:4039/pr-test 
Production: https://virtualtabletop.io/9t6e

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4039/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
Hey how can I test this?

**Comment by bjalder26** [comment]
> Hey how can I test this?

These two rooms have buttons with invalid URLs.  The 
PR: http://212.47.248.129:4039/pr-test
Production: https://virtualtabletop.io/9t6e

If you open the developer's tools and click on the elements tab, then you'll see an audio element pop up for both.  On the production server it won't go away, because the interval for its deletion is set based on the length or input in the JSON.  With no JSON input and no valid audio to get the length from it will just stay there doing nothing on the production server.  If you keep clicking the button you'll wind up with a whole bunch of them.

On the PR server, you should see the element disappear almost immediately, because if there is an error (an invalid audio file), then it will remove it right away.
image

**Review by 96LawDawg — APPROVED** [review]
Great instructions for the test.  Approved through test.

**Pull request merged**
