### PR TITLE
adds mode to CLICK

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
modes are:
- 'respect' (default) : respects clickable false and executes ClickRoutine if available when clickable is true
- 'ignoreClickable' : ignores clickable false and executes ClickRoutine if available
- 'ignoreClickRoutine' : respects clickable false and ignores ClickRoutine and executes original click function
- 'ignoreAll' : ignores clickable false and ignores ClickRoutine and executes original click function

note that ignoreClickRoutine and ignoreAll make CLICKing a button pointless

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3448/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
Added examples in /pr-test

**Comment by rogerl50** [comment]
Why do you have 'ignoreClickRoutine' and 'ignoreAll' if they result in nothing happening when the `CLICK` is executed?

**Comment by RaphaelAlvez** [comment]
> Why do you have 'ignoreClickRoutine' and 'ignoreAll' if they result in nothing happening when the `CLICK` is executed?

Click on the buttons related to the spinners. The results are different.

For buttons I wanted to show that they don't have anything else other than the clickRoutine

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  I don't understand the use case for this, but you obviously think it is needed.  I tested a few public library games just to make sure nothing else seemed out of place.  The default keeps things they way they should be in other games.

**Comment by RaphaelAlvez** [comment]
> Approved through test. I don't understand the use case for this, but you obviously think it is needed. I tested a few public library games just to make sure nothing else seemed out of place. The default keeps things they way they should be in other games.

My main uses cases are:
- having something that is not clickable by the users but that you can still click with buttons
- having a click routine in a spinner and still be able to click itself in the end ignoring the click routine

**Pull request merged**
