### PR TITLE
fixed wrong logo height on oldish Android

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
My wife's phone uses Android 9 and its WebView 85.0.4183.101 somehow displays the logo in the wide toolbar really tall (the `img` but not the image), making lower buttons inaccessible.

This PR simply sets a fixed height on the `img`.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1584/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1584-pr-test`.

**Comment by ArnoldSmith86** [comment]
Just tested with the test server and it works fine on her phone. Weird bugs are weird.

**Comment by robartsd** [comment]
My Android 7 uses Chrome and Brave which do not experience this issue. Dev Tools reports intrinsic size of  i/branding/logo.svg is 1058:340, I'm guessing that for some reason that Android browser is using the intrinsic height even though the width is limited.

**Review by robartsd — APPROVED** [review]

**Review by RaphaelAlvez — APPROVED** [review]
code review. giving second approval since you already tested it on her phone

**Pull request merged**
