### PR TITLE
Update JSON editor

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
- [x] Adds default collections and default variables
- [x] Adds some frequent properties to "property "in various functions
- [x] Adds multiplication by -1 to numbers
- [x] Adds "operations" to COMPUTE and "relations" to SET
- [x] Adds "relations" to IF
- [x] Adds "angle" to ROTATE
- [x] Adds CSS variables to "css" and other properties
- [x] ~~Adds properties to grid~~ created issue #452 

I also didn't know how to make the last item as it would require a new function
Please check line 477. It is functional but maybe I did it too ugly, I can't use [A-Z]+ because not all functions should be included

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3451/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
> Please check line 477. It is functional but maybe I did it too ugly, I can't use [A-Z]+ because not all functions should be included

I think your regular expression on line 478 is fine.

**Comment by robartsd** [comment]
> * [ ]  Adds properties to grid
> 
> I also didn't know how to make the last item as it would require a new function

While it would be nice, I don't see a reason it couldn't be a future PR.

**Comment by RaphaelAlvez** [comment]
I messed up when cleaning it up but this PR is finished. Please review. All content is in the description.

**Comment by rogerl50** [comment]
Do you want to wait on this, since when #307 is merged much of this will have to change anyway, or will be altered by #307?

**Comment by 96LawDawg** [comment]
Some basic CSS defaults is a nice touch, especially the --wcxxx things you did.  However, you have --wcImageOH: url() in there.  Remember, that does not work.  Go back to the discussion in the #help channel on 4/17/2021.  Recommend removing that from this update until that is fixed.

**Comment by RaphaelAlvez** [comment]
> Some basic CSS defaults is a nice touch, especially the --wcxxx things you did. However, you have --wcImageOH: url() in there. Remember, that does not work. Go back to the discussion in the #help channel on 4/17/2021. Recommend removing that from this update until that is fixed.

I did in fact forgot about that. I mindless took all variables from the code

**Comment by 96LawDawg** [comment]
Also, it's a very small thing and you don't have to change if you don't want to.  For me, the more natural settings for rotation angles would be 45, 90, 135, 180 (instead of 60, 90, 120, 180).  But I don't really care that much either way.

**Review by 96LawDawg — APPROVED** [review]
Approved through test and code review.

**Comment by RaphaelAlvez** [comment]
changes done. I did keep 60 as this is is for hexagonal cards

**Pull request merged**
