### PR TITLE
Remove Ctrl key actions for buttons in JSON editor

### PR DESCRIPTION
**Pull request by larkob**
This PR removes the Ctrl key actions (other than Ctrl+J) in the JSON editor because they aren't working in most browsers anyhow. Only the commands on the right side are removed. This allows users to again use hotkeys like Ctrl+f to find something and Ctrl+r to reload the page.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3616/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Okay, so I just noticed that it is a draft.  But I still like it and would approve it if it were not in draft.

**Comment by rogerl50** [comment]
DO IT! I can't wait to get my ctrl-key functionality back so that Ctrl-D will delete a character like it should instead of adding a `DELETE` at some random location in my routine :)

**Review by ArnoldSmith86 — APPROVED** [review]
Code looks fine. Let's see if I ever add them back with a different modifier. :smile:

**Review by RaphaelAlvez — CHANGES_REQUESTED** [review]
Wait is CTRL + F1 a inbuilt hotkey?

I don't really want to loose the id selection feature

**Comment by ArnoldSmith86** [comment]
> Wait is CTRL + F1 a inbuilt hotkey?

That still works for me.

**Comment by ArnoldSmith86** [comment]
Any particular reason why this is still a draft? Seems like people can't wait...

**Comment by rogerl50** [comment]
The Ctrl-F1/F2/etc keys still work after this change. It is only the Ctrl- shortcuts for the commands on the right-hand side that have been removed.

**Pull request merged**
