### PR TITLE
CSV support for decks

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
currently, the line break is "* "

"NULL", "TRUE" and "FALSE" should return the boolean, and number strings are converted to float

context is '^deck ↦ cardTypes'

- [x] Add export button
- [x] Add set mode
- [x] Fix line break
     - [x] change to a file upload button
- [x] Add card count header ("cardTypeCount")
- [x] Change type ID header ("cardTypeID")
- [x] fix bug in cardTypeCount

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1411/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1411-pr-test`.

**Comment by 96LawDawg** [comment]
Your PR made a lot of (unintentional) changes to the public library.

**Comment by RaphaelAlvez** [comment]
> Your PR made a lot of (unintentional) changes to the public library.

Oh that's why you were added as a reviewer.... Ok should be an easy fix

**Comment by 96LawDawg** [comment]
Tested with a couple of my bird cards.  Worked great to import the first one just as expected.  But I couldn't add a second one.  It showed up in the JSON, but as soon as you click out of the deck and come back to it, the new addition was gone.

**Comment by rogerl50** [comment]
There are several JS-based CSV parsers in the public domain, including https://www.npmjs.com/package/csv-parser in node.js. That *might* (or might not) be easier than trying to get your own correct.

**Comment by 96LawDawg** [comment]
Mostly works.  I tested using Excel.  Imports fine, but it adds an additional blank cardType on at the end with a random 4 letter name.  If you delete the card before doing anything else, it works, but if you don't delete that card, the additions are lost.

Also, I don't understand the difference between set and add modes.

**Comment by RaphaelAlvez** [comment]
> Mostly works.  I tested using Excel.  Imports fine, but it adds an additional blank cardType on at the end with a random 4 letter name.  If you delete the card before doing anything else, it works, but if you don't delete that card, the additions are lost.
> 
> Also, I don't understand the difference between set and add modes.

Can you share that csv? Maybe excel is adding one line at the end. I did not see this using Google sheets.

Set cleans the cardTypes before adding and add just append the cardTypes to the end.

Add won't work very well if you are using random IDs

I should probably change the default to set

**Comment by 96LawDawg** [comment]
Here it is.

[demo.csv](https://github.com/ArnoldSmith86/virtualtabletop/files/10071857/demo.csv)

**Review by ArnoldSmith86 — APPROVED** [review]
Gonna approve this because you can't.

I would be very surprised if this breaks anything as all changes are confined to new JSON editor commands.

**Pull request merged**
