### PR TITLE
set window size in create game test

### LINKED ISSUE #1585: Some TestCafe tests fail on some window sizes
The Edit Button and Add Widget button are hidden with `display: none` at certain window sizes:

- height <= 420px
- height <= 520px (.wideToolbar)
- width <=760px (.aspectTooGood)
- 760px <= width <= 960px (.horzontalToolbar)

This causes the Create Game in Edit Mode test to fail waiting for the Add Widget button to appear.

### PR DESCRIPTION
**Pull request by robartsd**
Fixes #1585 by setting the window size in the editor test.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1586/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1586-pr-test`.

**Comment by robartsd** [comment]
I discovered this issue when switching the gitpod image to [gitpod/workspace-full-vnc](https://hub.docker.com/r/gitpod/workspace-full-vnc) in the [codespaces](https://github.com/ArnoldSmith86/virtualtabletop/tree/codespaces) branch. I was surprised that the image already included Chrome. When I tried running the tests in Chrome, the editor test failed because the add button never appeared. The default window size for Chrome in that image triggers the bug.

To see this in action:
- Create a [Gitpod workspace from the codespaces branch](https://gitpod.com/#https://github.com/ArnoldSmith86/virtualtabletop/tree/codespaces)
- Open a browser window to port 6080 to see the workspace graphical desktop
- run `npm run testcafe tests/testcafe/editor.js` in the Gitpod terminal and watch it fail
- switch to this branch with `get checkout robartsd/some-testcafe-tests-fail-1585`
- run `npm run testcafe tests/testcafe/editor.js` to see how this PR fixes it

**Review by 96LawDawg — APPROVED** [review]
Well, that is an odd choice for size, but as long as it works...  Approved through code review.

**Comment by robartsd** [comment]
> Well, that is an odd choice for size, but as long as it works... Approved through code review.

The size is a bit arbitrary. I'm not 100% sure, but I believe it is the inner dimensions of the viewport. I wanted to test the size and only change it if needed (height <= 520 || width <=960) , but I don't know how to get the window size within the test.

**Comment by robartsd** [comment]
Now it only changes the size if it might be too small to show the buttons and restores the original size for the window after the test.

**Pull request merged**
