### PR TITLE
Add Speedy Fruits and Whisky Cat

### PR DESCRIPTION
**Pull request by 96LawDawg**
Add Whisky Cat (similar to Brändi Dog) by Ingegneus.  Add Speedy Fruits (similar to Halli Galli) by Ingegneus.  Update Bhukhar to fix issues (revert to previous style) involving buttons and discard pile functions.  Also changed player number style from 4-6-8 to 4,6,8.

Add new Master Button tutorial by Interitus.  Updated Get tutorial to remove language regarding get working with first widget of a collection.

Updated library.json to reflect above changes.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3325/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
All changed files successfully uploaded from library.

**Review by ArnoldSmith86 — APPROVED** [review]
Looks good.

In Whisky Cat the arrow on the right looks like a button that slides in settings or something. On mobile I tried clicking it at least 50 times and nothing happened. I literally went into edit mode to find out what it's supposed to do and stumbled over the `enlarge`.

**Comment by GroggyLion** [comment]
Oops, I didn't get a chance to check the pr-test server for this yesterday. The bhukhar version is the correct one, but I saved it when it was on the play screen and not the startup menu page with the instructions. So now loading it from the library means it starts with the play screen.
The current players will not mind as they know how to get back to the main menu page. I don't know how involved changing an approved PR is so please merge this and I will ensure the next release does not have this issue. If however it is easy enough, I can resend the file via the Discord channel with the correct first screen. Thanks!

**Pull request merged**
