### PR TITLE
fix adding composite widgets

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Missed at least one `await` in #917.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3992/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
That indeed fixes the problem I noticed.

**Comment by ArnoldSmith86** [comment]
Please approve it then. :smile:

**Review by robartsd — APPROVED** [review]
Code change looks fine to me. Did not test.

**Pull request merged**
