### PR TITLE
show label text when enlarged

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This PR copies any textarea value of the original widgets to the enlarged widgets.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1765/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1765-pr-test`.

**Comment by 96LawDawg** [comment]
Testing shows something really strange.  A label with enlarge is sticky.  It remains on the screen until the mouse is near another enlargeable widget (or maybe it is some other criteria--hard to tell).  But even stranger, it only seems to be the last/most recently created label with enlarge that does that.  Other, older labels with enlarge in the room don't have that problem.

**Comment by ArnoldSmith86** [comment]
I have the problem of stuck enlarged widgets all the time. I'll probably overhaul the enlarge code soon.

How sure are you that this PR is worse in that regard? :D

**Comment by 96LawDawg** [comment]
> I have the problem of stuck enlarged widgets all the time. I'll probably overhaul the enlarge code soon.
> 
> How sure are you that this PR is worse in that regard? :D

I just went back in to test and opened the room brand new.  No problems.  So it is probably something leftover from edit mode.  Which isn't really a problem.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  This works as expected and existing behavior for other widgets seems to be unchanged.

**Pull request merged**
