### PR TITLE
Allow inheriting of a subset of properties.

### PR DESCRIPTION
**Pull request by rogerl50**
This adds a new text box below the "use inheritFrom checkbox" to allow the user to enter a set of properties to be inherited. Leaving it blank will result in all properties being inherited (as before).

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1337/pr-test (or any other room on that server)

After merging, a backup will be available at https://beta.virtualtabletop.io/editor/PR1337-pr-test.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Works like it should.

This also changes the format from `"inheritFrom": "abcd"` for the default (all properties) to `"inheritFrom": {
    "test1": "*"
  }`

I think that is a good idea as this more clearly shows what is happening and it is easier to change if you want to later because you don't have to create the object form.  Good idea.

**Comment by 96LawDawg** [comment]
When pressing the `inheritFrom` button you get: `"inheritFrom": {
    "": []
  }`.  Should that be `"inheritFrom": { "": [ "" ] }`?

Also, for css, what about adding a "background-image" button?  I use that quite a bit and always have to go and cut and paste it from somewhere else.  But maybe that is just me.  If it is included, it would be most useful if it also included several other related settings.  To be clear, I'm only asking for the 1 button, but pressing the button gives you this:

`"background-image": "url(' ')",
 "background-size": "contain",
 "background-repeat": "no-repeat",
 "background-position": "center"`

**Comment by rogerl50** [comment]
> When pressing the `inheritFrom` button you get: `"inheritFrom": { "": [] }`. Should that be `"inheritFrom": { "": [ "" ] }`?

Perhaps that would be better. There are no really good alternatives, though. The caret is being placed in the widget name in any case.

> Also, for css, what about adding a "background-image" button? I use that quite a bit and always have to go and cut and paste it from somewhere else. But maybe that is just me. If it is included, it would be most useful if it also included several other related settings. To be clear, I'm only asking for the 1 button, but pressing the button gives you this:
> 
> `"background-image": "url(' ')", "background-size": "contain", "background-repeat": "no-repeat", "background-position": "center"`
I assume you mean for buttons? Or for everything? Should it be in `default`, `:hover`, or somewhere else? Also, are those other properties (from `background-size` on) used in other contexts than with images?

**Comment by 96LawDawg** [comment]
> > Also, for css, what about adding a "background-image" button? I use that quite a bit and always have to go and cut and paste it from somewhere else. But maybe that is just me. If it is included, it would be most useful if it also included several other related settings. To be clear, I'm only asking for the 1 button, but pressing the button gives you this:
> > `"background-image": "url(' ')", "background-size": "contain", "background-repeat": "no-repeat", "background-position": "center"`
> > I assume you mean for buttons? Or for everything? Should it be in `default`, `:hover`, or somewhere else? Also, are those other properties (from `background-size` on) used in other contexts than with images?
> 
> BTW, I think you meant this comment to be associated with #1335, not this one...

Yes, the whole thing was for #1335.  I had them both open and posted in the wrong place.  I will make my response to your questions there.

**Review by ArnoldSmith86 — APPROVED** [review]
Code looks good to me. Didn't do any testing.

**Pull request merged**
