### PR TITLE
show and tell: added game categories to library

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This is one of the remaining features I want to add to #1223.

You define in which categories a game should be displayed:

image

And then those categories are available in the filter dropdown:

image

The UI is not final but it seems to be functional. So this PR is a demo so we can discuss the feature.

For the category transformation, I used this function:

```Javascript
  function getCategories(inputString) {
    const categories = new Set();

    const lines = inputString.split('\n');
    lines.forEach(line => {
      const category = line.split(' > ');

      let current = [];
      category.forEach(cat => {
        current.push(cat);
        const path = current.join(' > ');
        categories.add(path);
      });
    });

    return [...categories];
  }
```

It was written entirely by ChatGPT and you can see how unbelievably simple it was to tell the AI what to create: https://is.gd/E7i5Vt

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1435/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1435-pr-test`.

**Comment by RaphaelAlvez** [comment]
Maybe the option to add an icon there would be nice.

What are the >>>>?

**Comment by ArnoldSmith86** [comment]
Indentation for sub categories.

If you use `Games > Card Games > Coop Games` in a game, it will also show the parent categories:

```
Games
Games > Card Games
Games > Card Games > Coop Games
```

But because that is way too long, it shortens it to:

```
Games
> Card Games
> > Coop Games
```

I'm very open to suggestions.

**Comment by RaphaelAlvez** [comment]
also maybe "official art" should be a tag

**Comment by 96LawDawg** [comment]
> Why not just give a tag property to games?
> 
> ["Coop","card game","spiel des jahre"]

That seems like a good idea.  Simple.  No need for the hierarchy and >> indentations.

**Comment by ArnoldSmith86** [comment]
Hmm, I don't disagree, but that requires everything to be completely different. I guess I don't add anything in #1223 then..

**Comment by ArnoldSmith86** [comment]
In the meantime we might want to use this PR to gather every tag we would want to use? That would probably help to come up with a UI.

My general idea for this was to be able to better filter the games. Card vs board vs dice games; only show Spiel des Jahres; we're also missing age restrictions. Complexity, mechanisms, ...

**Comment by robartsd** [comment]
I agree that tags would be more flexible as a user. For instance, I might want to filter to all coop games (not just card coop OR board coop).

**Pull request closed without merging**
