### PR TITLE
Update library - Add Bhukhar, Blue, Splendid, Array Tutorial

### PR DESCRIPTION
**Pull request by 96LawDawg**
Bhukhar by GroggyLion

Blue (similar to Azul) by ArnoldSmith86 adapted from and with CC BY-NC permission from reddit user jaojins

Splendid (similar to Splendor) by Shaun

Array tutorial by Shaun (with edits by LawDawg and an example contribution from ArnoldSmith86)

Minor updates:  Add image attribution to meta data in Undercover and Undercover Duo.  Add wastebasket icon to Assets - UN Unicode.  Update library.json with new files.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3170/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
All files in PR test room loaded from public library json file successfully.

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
Splendid has `"css": "margin-left: 18px"` on the red gem cards. That only does something since yesterday so probably not intended?

**Comment by shaunhillier** [comment]
I don't know Bhukhar, but it doesn't look right that the similar game is also called Bhukhar and is a link to Rummy, should the similar game be rummy or is the link wrong?

**Comment by shaunhillier** [comment]
> Splendid has `"css": "margin-left: 18px"` on the red gem cards. That only does something since yesterday so probably not intended?

Yes this can be removed, this was left in from me trying something and doesn't work with the new update.

**Comment by ArnoldSmith86** [comment]
> I don't know Bhukhar, but it doesn't look right that the similar game is also called Bhukhar and is a link to Rummy, should the similar game be rummy or is the link wrong?

I think Bhukhar is similar to Rummy but not actually listed on BGG? Don't know how to handle it. If it's the case, it's probably fine the way it is.

**Comment by ArnoldSmith86** [comment]
Also: the random word tutorial clearly uses part of the word list from Undercover but doesn't list the source in attributions (and I don't mean Undercover as a source but the web link).

**Comment by GroggyLion** [comment]
> I don't know Bhukhar, but it doesn't look right that the similar game is also called Bhukhar and is a link to Rummy, should the similar game be rummy or is the link wrong?

Maybe we can change the link to https://www.notion.so/Playing-Bhukhar-ad26b1e5effb494ab1658a7a466e2316 where we've put up some basic rules about the game, and hope to add some more information later.

I guess it is based on the Rummy family of card games where you build sets and sequences but has evolved into its own now.

**Comment by ArnoldSmith86** [comment]
Maybe just create a BGG entry? I'm not sure if anyone can just do that but for example Duel 52 has its own entry.

**Comment by GroggyLion** [comment]
Ok, it looks like anyone can add a game to BGG (https://boardgamegeek.com/wiki/page/How_To_Add_Content) but it can take some time to be approved. I'll be able to work on this in a few days so maybe leave the similar to text as 'Bhukhar' and link to the BGG rummy page for now, and we can update the link here after the BGG page goes live?

**Comment by 96LawDawg** [comment]
Automatic checks are not completing.  Any ideas how to force that to happen?

**Comment by ArnoldSmith86** [comment]
No idea. Maybe they're waiting for my "requested changes".

**Comment by 96LawDawg** [comment]
The auto checks update has been a problem since last night.  Usually that happens in the first few minutes after a PR.  But when I triggered that latest commit, it seemed to start the process so everything is fine now.

Splendid is updated to fix the css error in the red gems.  The word list is the random array is changed to the U.S. phonetic alphabet.  Will leave Bhukhar similar to link the same until GroggyLion gets BGG updated because it is a version of rummy, just not one that BGG has.

**Review by ArnoldSmith86 — APPROVED** [review]

**Pull request merged**
