### PR TITLE
switch composed canvas button side

### PR DESCRIPTION
**Pull request by robartsd**

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3511/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Okay, but what about this?
Screenshot 2021-06-02 213054

**Comment by robartsd** [comment]
> Okay, but what about this?

Fixed now.

**Review by 96LawDawg — APPROVED** [review]
I have no problem with this either way.

**Pull request merged**
