### PR TITLE
added line numbers to JSON editor

### LINKED ISSUE #2165: Option to display line numbers in json editor
Feature request for the option to display line numbers in the JSON editor, same as you would find in most ide's and text editors.

Two scenarios in which this would be useful:

1) syntax errors specify the line in which the error is thrown, however, without line numbers displayed, this does not help in locating the error. (unless you want to count 200 lines from the top)

2) When talking about code or asking for help, line numbers can be used to refer to a specific line of code. Atm, the point of interest must be described in a roundabout way. (Example from a recent help issue: "the third-from-last object in the second faceTemplate")

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This is still WIP but as long as no lines wrap, it should already be pretty nice. Ran out of time for now but wanted to show the current state. Fixes #2165 when done.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2230/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
This now looks and works as intended. At least in the limited testing I did.

Now the question is: do we just always display the line numbers or do we make it a toggle somewhere?

**Comment by 96LawDawg** [comment]
This is great.  I thought before seeing it I was going to suggest a toggle.  But it is not needed.  They are unobtrusive.  I converted this to ready for review so I could approve it.

**Review by 96LawDawg — APPROVED** [review]
Approved.  Looks and works great.

**Comment by ArnoldSmith86** [comment]
Now with even less wasted space and correct color in light mode.

**Comment by 96LawDawg** [comment]
Looks good.

**Comment by RaphaelAlvez** [comment]
Looks very good. It was indeed a good suggestion.

Now I want collapsible functions/properties 😂

Like you click on the number and the property becomes "clickRoutine": [...]

**Review by RaphaelAlvez — APPROVED** [review]
Looks good. Great feature

**Pull request merged**
