### PR TITLE
new property: `dragging`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This PR introduces a new property `dragging` that is usually `null` but contains the player name of the player currently dragging the widget.

It also adds CSS classes `dragging` and `draggingSelf` (on clients with the same player name).

I did not think about this a lot.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1145/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
This is going to be helpful.  BUT, it is more limited than what I had hoped for.  This is listening for "moveStart" and "moveEnd" which means it only activates if the widget actually moves.  It would be more useful for it to listen for click and click release (or whatever those things are actually called).  Then it would be able to help #929 and #930. 

Maybe those could or should be separate solutions: one for dragging and one for clicking.  I don't really know.  But I do know that I've had a need for both things and had to work around them.  I've never had a need to distinguish between the two situations.  In other words, I have needed to know who was clicking on a widget (either to start a routine or to start a drag).

**Comment by robartsd** [comment]
Perhaps a similar `clicking` property added on mousedown/touchstart and removed on mouseup/touchend with comparable css classes. It is possible that the target of clicking and the target of dragging are not the same (if the target of clicking is not movable itself, a movable parent widget would become the target of dragging).

**Comment by 96LawDawg** [comment]
One thing I don't really like about the way this currently works ...  I added a `draggingChangeRoutine` onto cards.  If dragging, then the `owner` is set to the dragging player.  This continues to hide the card.  This is one feature that I wanted to be able to use this for and that works fine.  When I start dragging from the hand, however, it doesn't work.  The `dragging` property is set immediately as it should.  But `owner` doesn't change until the card is part way out of the hand (I don't think this will be any different after #1144 is merged).  There are a couple of work arounds I can think of.  And this probably isn't something that can be incorporated.  Just noting the behavior.

**Comment by 96LawDawg** [comment]
I tested this with hands and `draggingGlobalUpdate`.  I used iPhone Safari and Windows Chrome and Edge.  I tested using multiple simultaneous drags.  I don't see any issues with this at all.  I will approve it whenever, but I would like to see if mousedown and mouseup events can be added as a `clicking` property.

**Comment by robartsd** [comment]
> But a `clicking` property would also work here without the need for workarounds.

I don't see how `clicking` would help your use case. The code that removes owner during the drag would still fire.

**Comment by 96LawDawg** [comment]
> > But a `clicking` property would also work here without the need for workarounds.
> 
> I don't see how `clicking` would help your use case. The code that removes owner during the drag would still fire.

Yeah, I guess you are right.

**Comment by ArnoldSmith86** [comment]
I'm not sure any of the proposed stuff will help you with #929 and #930. My solution for those would be to check `clickable` again on mouseup and maybe introduce something that makes it easier to prevent double presses.

When checking `clickable` on mouseup, you can probably make a foolproof button that can't be clicked by two clients by setting `clickable: false` and another property somewhere to something random (so it will trigger a conflict).

But it might be a good idea to have a `noSimultaneousClick` property (probably with a different name) that does something like that behind the scenes so you don't have to construct weird stuff.

I don't think I read any comment on this PR that doesn't like what the PR implements. All I read was "I would like to have _more_". Which is totally fine but I didn't read anything that would like to change the implemented feature. So we can just add more features with another PR.

Or did I miss any suggestions?

**Comment by 96LawDawg** [comment]
I don't think you missed anything.  This is great.  I was just hoping for more.

Your suggestions for preventing simultaneous mouse clicks is what I was thinking.  I would have to do something hackyish to get it to work, but the `clicking` property is what I would need to do that.  A behind the scenes property would be even better.  But I would still like to have a property for `mousedown` and `mouseup` or whatever they are called just like we are now getting a property for `movestart` and `moveend`.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Comment by ArnoldSmith86** [comment]
> But I would still like to have a property for `mousedown` and `mouseup` or whatever they are called just like we are now getting a property for `movestart` and `moveend`.

I'm not quite sure how useful that would be. For `mousedown` and `mouseup` we have `clickRoutine`. The time difference between the down and the up is usually so small that network latency is probably longer. So I'm not quite sure what you would want to build with those that wouldn't have the same issues #929 is having.

**Comment by robartsd** [comment]
> > But I would still like to have a property for `mousedown` and `mouseup` or whatever they are called just like we are now getting a property for `movestart` and `moveend`.
> 
> I'm not quite sure how useful that would be. For `mousedown` and `mouseup` we have `clickRoutine`. The time difference between the down and the up is usually so small that network latency is probably longer. So I'm not quite sure what you would want to build with those that wouldn't have the same issues #929 is having.

But if mousedown event sets the `clicking` property it could be broadcast to the server before the results of the clickroutine (which does not start running until mouseup event). It might provide an earlier opportunity for conflict detection. I agree that a `clickingChangeRoutine` would not likely be useful.

**Comment by 96LawDawg** [comment]
> But if mousedown event sets the `clicking` property it could be broadcast to the server before the results of the clickroutine (which does not start running until mouseup event). It might provide an earlier opportunity for conflict detection.

Yes.  That.  When I was debugging a room that got wrecked because of simultaneous button clicks, what I found was that somebody had pressed a button and held it down for just a little too long.  When it was down but not up, somebody else clicked and released the button.  Because there was no conflict on the button to resolve, the routine ran twice.

So what I thought I would do is set "clickable:false" on mousedown.  Then there would be no way for that to happen.  But I'm open to other ideas of how to solve the problem.  That was just what I came up with.

**Comment by robartsd** [comment]
On second thought, `clicking` property I suggested also has the potential for unneeded conflict (two players click the same button that only affects the clicking player's widgets at the same time). I'm going to recommend `dragging` be implemented as is here, but we should probably continue the discussion of doing something on mousedown/mouseup in #930

**Comment by RaphaelAlvez** [comment]
>  property dragging that is usually null

This feels familiar....

**Comment by 96LawDawg** [comment]
Proposed wiki update.

The Using CSS entry at https://github.com/ArnoldSmith86/virtualtabletop/wiki/Using-CSS has a paragraph in the middleish of the page that should be changed to the following (or something like it):

If `css` is a compound object, a style sheet for the widget is generated by using the outer keys to create selectors and the nested object to create the style rules. Special keys _default_, _inline_, _dragging_, and _draggingSefl are provided. _default_ creates an ID selector for the widget. _inline_ places the defined style rules in the element's style attributes instead of the style sheet. _dragging_ is active when the widget starts movement (but not just clicking) by a player's action. _draggingSelf_ is the same except that the style rules will only be effective for the player doing the dragging. Any other value is appended after the widget id so rules like `#widgetID:hover` or `#widgetID::after` can be created. The below example moves the styles to a stylesheet and adds a yellow background glow on hover to the above example.

**Comment by robartsd** [comment]
Perhaps `dragging` property should be an object instead. The object could provide the player name as well as where the drag started (parent, x, y, z, rotation).

I think it would be good if clients were also aware of connections in addition to players. If the dragging property recorded the connection and the connection has been dropped, the information saved in the dragging property could be used to undo the drag instead of dropping the widget on the floor at the point of disconnect.

**Comment by 96LawDawg** [comment]
> I don't see special keys for dragging and draggingSelf and they would not be needed. A basic class selector key `".dragging":{}` would work just fine. A comma hack key could be used to target all widgets being dragged `"_, .dragging":{}`.

I have no idea of the difference between a special key, a class selector key, and the key to my house.  I was just trying to make sure that what has been included in the PR gets adopted somewhere in the wiki.

**Review by RaphaelAlvez — APPROVED** [review]
code reviewed and tested

**Comment by 96LawDawg** [comment]
I resolved the conflict.  Just for the record, it looked like the screenshot below before I touched it.  All I did is remove the <<<<feature-dragging, =========, and >>>>>>> stuff from lines 294, 299, and 302.  This was caused by the JSON Editor tree PR.  I tested this on my local machine before committing and both the new `dragging` features and the new tree/highlight stuff works.  Ready for merge.

**Comment by RaphaelAlvez** [comment]
> I resolved the conflict.

Seems correct

**Pull request merged**
