### PR TITLE
added option "Use inheritFrom" to duplicate command

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The duplicate command can now create minimal new widgets that use `inheritFrom` to receive nearly all their contents from the source.

This is pretty much the last feature of PR #479. Only a similar command that syncs children to inheriting widgets is still missing but I am not sure what I will do with that one.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3648/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Works as expected, to including overwriting an existing `inheritFrom` property if one is already in the widget being copied.

**Comment by bjalder26** [comment]
If you delete the x offset, then the duplicate will appear at x:0 y:0.  Selecting the duplicate in the JSON editor can then cause it to move to the original's original y (the y value it will have set) and the original's current x (the x value it will inherit).  

A similar thing happens when you delete the y offset or both offsets.

I view the fact that deleting the x or y offset will cause it to inherit the x or y property as a feature.  However, it seems like making it so the other value will be immediately applied would be an improvement.

It seems like the issue is that the engine is having trouble dealing with a NaN value, so it puts that widget at 0,0, even though it has a y value of 775.
image

That is until the inheritFrom 'kicks in' and it receives an x value equal the original widget.
image

**Review by bjalder26 — APPROVED** [review]
Making 10K copies (100x100) seems to be a room breaker (at least for buttons), so I would probably limit the copies to 50x50 (2,500), which seems to not be a problem.  Technically that's not a change in this PR though.

Personally, I would rather have NaN set to null rather than zero, so probably something like below (but for both x and y).

In jsonedits.js
      if(Number.isNaN(options[option.label]))
        options[option.label] = null;

in editmode.js
    if(xOffset || !newParent && inheritFrom) {
      if(xOffset == null) {
		  currentWidget.x = null;
	  } else {
		  currentWidget.x = widget.get('x') + xOffset;
	  }

Then when someone deletes the x offset (or y offset) it would produce a duplicate with no x (or y) value, which would inherit the x (or y) value from the original widget.  Zero offset would still give the widget the original widget's x (or y) value.

However, since everything appears to be working, my 1st point is technically outside of this PR, and my 2nd point is a personal preference that is debatable, I'm going to go ahead and approve based on testing.

**Pull request merged**
