### PR TITLE
new editor layout

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
https://test.virtualtabletop.io/PR-1627/pr-test

The new editor layout. This should replace the old edit mode (with the blue outlines) and incorporate the JSON editor.

I want to add a lot of awesome stuff to the editor but we should try to keep this PR as small as possible. It probably shouldn't take too many features away that we currently have.

Goals before merging:
- [ ] Move the Add Widget button from the JSON editor module to the main toolbar. This should become its own module with a lot more stuff but let's use what we have for now.
- [ ] Improve the Properties module at least a bit so it's actually useful. More complex stuff can wait for later.
- [ ] Highlighting the selected widget needs to be improved.
- [x] Increase the minimum size of the modules.
- [x] Improve the media queries so every viewport size gets a sensible layout.
- [ ] The yellow in the light debug is too bright.
- [ ] Undoing stuff sometimes creates empty piles. I think the problem is that widgets are created locally before sending its delta. Creating the undo and redo deltas needs to recognize that. (I also had a dropShadow widget staying behind after playing with carrots in the hand of `Animal Race` and undoing.)

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1627/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1627-pr-test`.

**Comment by robartsd** [comment]
I like the new blank room option. In my development room, I have a saved state just for this purpose.

**Comment by robartsd** [comment]
I notice the save button, are change not live in the editor with this?

**Comment by ArnoldSmith86** [comment]
They are. It's supposed to become a shortcut for opening the library, finding the active game, clicking edit, clicking edit on the variant, clicking "update variant with room content" and clicking save...

**Comment by ArnoldSmith86** [comment]
Alright, the general editor layout should work on any screen now although I'll probably tweak the transitions a bit.

This shows where my vision with the editor is heading. The room will not keep its "edit mode" look though and all the features are still missing.. The current JSON editor will be one of those sidebar options as will a different version of the Add Widget overlay.

**Comment by RaphaelAlvez** [comment]
First of all I miss clicked again

**Comment by RaphaelAlvez** [comment]
This zoom should be able to open edit mode



Using the desktop mode I get this

**Comment by ArnoldSmith86** [comment]
> First of all I miss clicked again

What?

**Comment by ArnoldSmith86** [comment]
Now with nearly the full power of the JSON editor on mobile.

**Comment by mousewax** [comment]
Looking fantastic. 

Question: Can the properties editor use the same form elements that are used in the input modal?

**Comment by ArnoldSmith86** [comment]
So far it only uses vanilla inputs. I'll make it use the appropriate inputs for each property.

I'll take a look to see if it makes sense to use the INPUT thingies. Probably a good idea.

**Comment by 96LawDawg** [comment]
Pretty amazing stuff.  A few thoughts:
 - Start in dark mode.  JSON looks awful on the white.
 - When returning (using X) from dark mode, the whole interface stays dark
 - For debug, I think this narrow view is going to be a problem for looking at nested routines.
 - I don't really like the "click selected widget as if in play mode" interface.  Is there a reason we need this (mobile?)  I would prefer that to be the default and have it sticky.  If mobile who whoever needs it, then they can click it to set it how it works now.

**Comment by RaphaelAlvez** [comment]
> Pretty amazing stuff.  A few thoughts:
>  - Start in dark mode.  JSON looks awful on the white.
Agree

>  - When returning (using X) from dark mode, the whole interface stays dark
Yeah both dark modes are not really the same thing. Dark mode is editor is not even full dark

>  - I don't really like the "click selected widget as if in play mode" interface.  Is there a reason we need this (mobile?)  I would prefer that to be the default and have it sticky.  If mobile who whoever needs it, then they can click it to set it how it works now.
Still pretty weird to use in mobile. I don't think mobile should have a full support. It should be targeted to minor fixes (and code review/help for us from discord)


My opinion so far
- In general I like the layout for mobile.
- Changing the modes is still a bit wierd.
- Play mode and undo places should be swapped.
- JSON editor + widget tree + basic editor layout is pretty much as I expect it to be in the end. Just the tool bar is missing.
- It's a bit hard to identify which widget is selected and which kind of interaction you are having with it (click or selection)

**Comment by mousewax** [comment]
Re: Dark mode, ideally the site will mimic the mode the operating system is in and change accordingly.

**Comment by robartsd** [comment]
I'll echo LawDawg on the "click selected widget as if in play mode", though I'd be okay with the current behavior as default as long as it can be changed back to the old mode and the setting is remembered and applied server wide for the client.

The palette buttons [Properties, Undo, JSON, Tree, Debug] take up too much width. Would be nice to be able to iconify (even better to be able to iconify into the top tool bar).

I think debug should continue to be over the room area (unless a new routine editor is going there). Debug can often use the width, and seeing the debug output while editing a routine is often very helpful.

I don't use the F-key shortcuts much, but I am surprised that no one has mentioned that they are missing (or is this smart enough to know that my Chromebook keyboard doesn't have F-keys)

**Comment by 96LawDawg** [comment]
> I don't use the F-key shortcuts much, but I am surprised that no one has mentioned that they are missing (or is this smart enough to know that my Chromebook keyboard doesn't have F-keys)

Good catch.  Definitely need those back I think.  I used them a lot.

Also, I just noticed you cannot ctrl-click in tree mode onto widgets that are in a pile.

**Comment by ArnoldSmith86** [comment]
Thanks for all the feedback! Most of that I was aware of, but I'm trying to share my plans about how to address them so we can have a discussion in the meantime.

---

> * JSON looks awful on the white.

What looks aweful? We can change the colors...

> When returning (using X) from dark mode, the whole interface stays dark

Yeah. Like Raphael said, they are different kinds of dark mode. If they were the same kind, it could probably be the same setting.

> For debug, I think this narrow view is going to be a problem for looking at nested routines.

I'm pretty sure I want to let the user increase the size of the sidebar somehow.

> * I don't really like the "click selected widget as if in play mode" interface.

Me neither. It might stay the way it is but I'll add a lot of shortcuts for mouse+keyboard. I want everything to work on mobile but there's no reason not to use right-clicking or whatever.

> * Deck indicators look weird and don't play well with game widgets.  I get why you include them here, but maybe an option to turn them off?

Yeah, I couldn't just remove them entirely. I want to add a "Filter" sidebar or whatever where you can select what widgets types to show or lock (not selectable/movable) or maybe even an opacity slider. I would hide decks by default then.

> * ctrl-click a widget is less friendly that it used to be.  If I'm ctrl-clicking, I'm not on mobile, so it should default to showing the JSON view.

Yeah, ctrl-clicking is a remnant. Now you can just click. But like I said, there will be shortcuts for mouse+keyboard.

> * Not a fan of switching back and forth between tree and widget view.

My plan would be to make it possible to open two of those sidebar modules at the same time (by shift-clicking maybe?).

> Still pretty weird to use in mobile.

Can you be more specific? Also please note that for some viewports it still does the wrong thing (too narrow sidebar or fullscreen for no reason or not using all available space for the sidebar if the room can't be bigger anyway etc.).

> I don't think mobile should have a full support. It should be targeted to minor fixes (and code review/help for us from discord)

Why?

> * Changing the modes is still a bit wierd.

What modes and what's "weird"?

> Play mode and undo places should be swapped.

I'm not sure what you mean. "Play mode" is clicking the widget like in play mode? "Undo" is the undo button in the sidebar?

> * Just the tool bar is missing.

What toolbar? You mean turning the "old" JSON editor toolbar at the top of the commands into the new toolbar that stretches across the screen? They'll move one by one. Some of them (like Add Widget, Duplicate or Macro) will probably be their own sidebar modules. Others (like Delete, Zoom) will be toolbar buttons.

> It's a bit hard to identify which widget is selected and which kind of interaction you are having with it (click or selection)

Yeah. Highlighting the selected widget needs to be consistent. As a first version I'll probably use the JSON editor highlighting we currently have to always highlight the selected widget (not as it is now in the PR where it is only highlighted if the JSON editor module is open).

> Dark mode, ideally the site will mimic the mode the operating system is in and change accordingly.

Yeah. Not the "Lights Off" mode though that also dims the toolbar in play mode..

> The palette buttons [Properties, Undo, JSON, Tree, Debug] take up too much width. Would be nice to be able to iconify (even better to be able to iconify into the top tool bar).

They do iconify for narrower viewports. I would probably make it smaller when pressing a button that makes the sidebar bigger  (or even fullscreen).

> I think debug should continue to be over the room area (unless a new routine editor is going there). Debug can often use the width, and seeing the debug output while editing a routine is often very helpful.

Same solution as with the tree. Allowing to open two modules and allowing to make them bigger. "to be over the room area" is something this can't do anymore by default because that's what it does for smaller viewports anyway. And I really like that all modules behave the same now. Just needs a way to open two and make them bigger IMO.

> Good catch. Definitely need [the F-key shortcuts] back I think. I used them a lot.

We definitely need a way to select occluded widgets. I'm thinking about changing it to something that shows you all the widgets so you can click the one you want. The F-keys don't work on mobile, they are kinda ugly and I feel like I have to look too much at them until I find what I need. I would like to wait until we have a way to hide certain widget types though so we can see how much that helps already.

**Comment by mousewax** [comment]
I would like to offer up the rejiggerator interface again. It's an old prototype so it's not at all finished, but it's more or less how I envisioned the main part of the editor. There's even a code icon at the top of the widget view (it does not work, but would work identically to Arnold's UI). Swap the side and make it wider.

https://mousewax.com/rejiggerator/
You have to put a room id from any room on the main site in the box at the top to see it "working".

Works well on desktop and mobile and has a consistent/familiar navigation for normies with visual cues that show what's happening. 

I'm sure these are all things that are coming, but I just wanted to throw this out there.

**Comment by ArnoldSmith86** [comment]
That undo stuff is pretty cool. I still want to:
- make it prettier
- combine multiple deltas when dragging into one delta
- limit it to something
- add player name and - if applicable - routine name

**Comment by robartsd** [comment]
> * combine multiple deltas when dragging into one delta

This will become difficult when multiple players drag at the same time.

**Comment by ArnoldSmith86** [comment]
> This will become difficult when multiple players drag at the same time.

True. Doesn't have to be perfect. :man_shrugging: It's mainly meant for editing anyway and people tend to do that alone.

**Comment by ArnoldSmith86** [comment]
Everybody, please think about what your minimum requirements are to merge this first PR. I updated the PR description.

If we don't have clear goals, I'll probably add way too much half-baked stuff.

Let's try to get to a point where everybody is happy-ish with the new editor and then we can have simpler PRs that add functionality over time.

**Comment by 96LawDawg** [comment]
> > * JSON looks awful on the white.
> 
> What looks aweful? We can change the colors...

All of it.  But really the greens and oranges and yellows.

Colors

**Comment by 96LawDawg** [comment]
And speaking of colors, dark mode debug is not visible after you click on one of the debug rows.

Debug

**Comment by robartsd** [comment]
Minimum for undo - provide some sort of limit so that it doesn't eat up unlimited memory

Minimum for panels - on 1080p monitor must be able to see 2 panels (particularly JSON + Tree and JSON + debug) at the same time with each panel at least 300px wide

**Comment by 96LawDawg** [comment]
> Minimum for undo - provide some sort of limit so that it doesn't eat up unlimited memory (could just be something like 1000 levels)
> 
> Minimum for panels - on 1080p monitor must be able to see 2 panels (particularly JSON + Tree and JSON + debug) at the same time with each panel at least 300px wide

I agree with both of those and add:

Minimum for interface- return ctrl-click to something like what it was before or what Dave said "current behavior as default as long as it can be changed back to the old mode and the setting is remembered and applied server wide for the client."

Minimum for selecting occluded widgets- F-keys or filters.  But let me make an additional comment about this.  Filters work most of the time.  But if you have a bunch of cards stacked or nearly stacked in a hand (for example) and you want to see which cards are directly under the mouse, filter won't work.  The F-keys have been really useful for debugging by showing me the names of the widgets my mouse if over.  So eve if we don't do F-keys, showing the id and type of the widgets my mouse is currently over I think is also a minimum for me.

**Comment by robartsd** [comment]
One idea for multiple widget under the pointer, would be a right click menu that lists all the widgets under the pointer (sorted by stacking order).

**Comment by robartsd** [comment]
Eventually:

- JSON context buttons are separate panel
- Properties panel groups properties by category (labeled) and groups can be collapsed
- Properties panel provides representation of complex properties (start with JSON in adjustable multiline text box)
- JSON and properties panel use the same grouping and sorting of properties (but JSON does not label the groups or collapse by group)
- JSON adds support for collapsing objects/arrays

**Comment by robartsd** [comment]
Once we have something that we think is the minimum for merging, we should make a general announcement about testing it in the discord Game Developer Discussion section to get feedback from any stakeholders that do not participate in developer discussion.

**Comment by ArnoldSmith86** [comment]
> JSON context buttons are separate panel

Hmm, are you sure? Would you want to edit the JSON without them?

**Comment by robartsd** [comment]
> > JSON context buttons are separate panel
> 
> Hmm, are you sure? Would you want to edit the JSON without them?

Mostly I'm thinking they aren't needed when debugging routines.

**Comment by ArnoldSmith86** [comment]
You can now open up to four sidebar modules at the same time. They form a 2x2 grid in the sidebar with the left column and top row taking up 2/3 of the width and height respectively.

- Left-clicking on the sidebar button changes the top left module.
- Right-clicking on the sidebar button changes the top right module.
- CTRL-Left-clicking on the sidebar button changes the bottom left module.
- CTRL-Right-clicking on the sidebar button changes the bottom right module.

If two modules display side by side it also increases the width of the sidebar modules by 50%.

image

It still needs some kind of border between the sections so it doesn't look like a complete mess but I wanted to ask for feedback before continuing.

What like about this is that it gives a lot of flexible layouts for PC power users while hiding it from newbies and mobile users while still making everything accessible to everyone.

Thoughts?

**Comment by 96LawDawg** [comment]
> What like about this is that it gives a lot of flexible layouts for PC power users while hiding it from newbies and mobile users while still making everything accessible to everyone.
> 
> Thoughts?

What I like: flexibility of seeing more than one thing and choosing where it goes.

What I don't like: I still think the debugger needs an option to overlay the room like we have it now.  There will come a time when the expansion window is not wide enough.  And I don't love the vertical limitation of having to look at the debug in the top and the JSON on the bottom.  I preferred side-by-side. Also, this is not very intuitive.  I played around a lot with left and right click, and control click.  I just couldn't get it to feel natural and more often than not, I didn't get the layout I was expecting and had to make a few more clicks.  If it is possible to get 4 things on there at once, I couldn't do it. If it is possible to have 2 complete vertical columns (instead of stacking), I couldn't do it.

**Comment by ArnoldSmith86** [comment]
The modules can now be arranged by dragging their button into a module area:

[cinnamon-2023-02-25T125834+0100.webm](https://user-images.githubusercontent.com/73538315/221355628-e851f9a3-7b3e-466b-843f-591d6a1e82c5.webm)

---

@flackr: This works as intended in Chromium but on Firefox I can only initiate the drag when clicking on the text ("Undo" for example) or the tooltip (by moving the mouse to it quickly). Clicking on the icon (which is a `::before`) or on the padding doesn't work. Do you have an idea why this would be happening? I already tried adding a wrapper `div` around the button and putting `ondragstart` on that one but it didn't change anything.

**Comment by 96LawDawg** [comment]
The drag and drop is great.  I was even going to suggest something like that but figured it was too much work.  Very nice.  But, now debug doesn't work at all.

**Comment by ArnoldSmith86** [comment]
> But, now debug doesn't work at all.

Works for me. Did you remember to click by using the toolbar button?

**Comment by 96LawDawg** [comment]
I couldn't get back here fast enough to say that I forgot to click the toolbar button.  You are going to fix that, right?

**Comment by ArnoldSmith86** [comment]
> You are going to fix that, right?

In some shape or form.

**Comment by RaphaelAlvez** [comment]
Ok this is nice. Very nice!

My only concern is that the UI is just getting more complex and we discussed about improving edit mode for new users.
I feel this complexity may scare some just like the JSON editor do at the moment.

But if the goal is to make the UI better and simple, I agree we are going in the general right direction.

**Comment by ArnoldSmith86** [comment]
Well, they don't have to open multiple things at once. And I'm planning to have a welcome module with some explanations and a mode selector where the "beginner" setting would hide JSON stuff and some others..

**Comment by 96LawDawg** [comment]
Maybe it would be nice to be able to set a default configuration in config.json so that no matter what room I go into, the JSON, the tree, and the debugger (my 3 most used things) are always in the same spot to start with.

**Comment by mousewax** [comment]
> Maybe it would be nice to be able to set a default configuration in config.json so that no matter what room I go into, the JSON, the tree, and the debugger (my 3 most used things) are always in the same spot to start with.

That sounds like a job for cookies.

**Comment by robartsd** [comment]
> > Maybe it would be nice to be able to set a default configuration in config.json so that no matter what room I go into, the JSON, the tree, and the debugger (my 3 most used things) are always in the same spot to start with.
> 
> That sounds like a job for cookies.

Yes, these types of preferences should be stored locally on the client.

**Comment by ArnoldSmith86** [comment]
We can also make CTRL+J load a certain layout.

**Comment by RaphaelAlvez** [comment]
> We can also make CTRL+J load a certain layout.

Yes I think we should have two levels. That might solve that problem I had in mind. Maybe have a button in the normal editor that also triggers the JSON editor and other advanced stuff.

**Comment by RaphaelAlvez** [comment]
Ok I figured out what is the bare minimum I expect from this PR.

# better basic editor
- visual input for all basic properties. Ideally taking those from the INPUT function so there's a synergy in development.
- list of properties that can be added. Again making it compatible with an already available system, the JSON editor list.
- support for custom properties. Some regex check that would choose a input type. (Maybe option to show JSON in case the regex fails (see bellow))
- if not supported, show a JSON text box. Maybe consider a option to hide all not supported inputs. With time we can work on adding support to the more complex ones.

# editor layout
- tools from JSON editor available to both basic and advanced versions
- "new" tools from the legacy editor.
- **important** expandable but simple layout. This includes menus and toolbars support. This does not mean this PR should fill the toolbar with stuff (I've been studying this on different UIs (because that's how I can help) and would like to discuss this)
- better and more clear saving and backup

**Comment by robartsd** [comment]
> Ok I figured out what is the bare minimum I expect from this PR.

The minimum requirement for this PR is that using the editor features does not become more difficult than the status quo for any use case. We need to collect a list of these use cases so that we know what to test to approve this PR. Your list includes a lot of enhancements over the status quo. It certainly is good to express where you think this should go, but I think these are unreasonable as requirements for this PR.

**Comment by robartsd** [comment]
We need to consider the basic editor's dialog for each widget type. The properties pane as currently stands is probably good enough replacement for some, but not for others (particularly decks).

**Comment by ArnoldSmith86** [comment]
I would like to improve the new property editor a lot in this PR. With descriptions and tutorial links for each property.

I think that's something _many_ people will find very useful and that way they might be less frustrated by features that were in the old editor but are still missing from the old one. Same with undo.

**Comment by RaphaelAlvez** [comment]
> I would like to improve the new property editor a lot in this PR. With descriptions and tutorial links for each property.

I agree that some sort of guide system would be useful. even for us. maybe hovering on a "?" next to the property or a on hover for tools.
we could add links to the wiki or just comments.

> I think that's something _many_ people will find very useful and that way they might be less frustrated by features that were in the old editor but are still missing from the old one. Same with undo.

what feature do you plan on removing?

About the undo: I think its on the right track but it needs to be triggered less often. maybe take a look on how photopea deals with history. each action type gets one backup in the history. so draging should only save the state before draging and dropping. not sure if there is any other situation with multiple triggers

**Comment by RaphaelAlvez** [comment]
first of all, I'm not demanding anything but I feel it came out as if I was. sorry if anyone felt like I was

> > Ok I figured out what is the bare minimum I expect from this PR.
> 
> The minimum requirement for this PR is that using the editor features does not become more difficult than the status quo for any use case. We need to collect a list of these use cases so that we know what to test to approve this PR. Your list includes a lot of enhancements over the status quo. It certainly is good to express where you think this should go, but I think these are unreasonable as requirements for this PR.

I agree that the concept of keeping it at least as good as it is now is key but that should be expected to any PR.

As requested I was just trying to come up with a list of items we should target in a short-term window so we can have direct improvement to both new and old users but at the same time set us in the direction of polishing the UI for good.

My understanding the changes are done so far were just initial stuff to get an idea of the frame of the new UI but at the same time, I believe it was discussed the goal was to make editing games easier for new users.

So my "requirements" were trying to figure out the bare minimum to make the basic UI useful and make the layout future-proof for new improvements.

**Comment by ArnoldSmith86** [comment]
> what feature do you plan on removing?

Well, the old edit mode with its overlays per type is gone. Most of it - and 10x more - will be covered by my goal to make a nice properties module. I'm not sure about the deck stuff though.

I'm pretty sure you'll love my ideas for editing decks but I'm not sure if this PR should wait for that.

**Comment by RaphaelAlvez** [comment]
> > what feature do you plan on removing?
> 
> Well, the old edit mode with its overlays per type is gone. Most of it - and 10x more - will be covered by my goal to make a nice properties module. I'm not sure about the deck stuff though.
> 
> I'm pretty sure you'll love my ideas for editing decks but I'm not sure if this PR should wait for that.

Oh I see. yeah there are some minor features that would be lost like the presets but that should be ok.

For decks how about we keep (for now) it for the cardTypes property? A button on that property in the basic editor could open that window over the play area. this might need some small changes like a close button and the removal of the "advanced settings" button.

**Comment by robartsd** [comment]
> I would like to improve the new property editor a lot in this PR. With descriptions and tutorial links for each property.

While I agree that this will likely be an improvement for most widget types, deck editing will need special attention. `classes` property should also get special treatment for adding classes that have meaning defined by the engine (transparent holders, font classes).

Eventually I see the properties pane becoming the most frequently used editor even for advanced game designers.

**Comment by robartsd** [comment]
Deck editor probably should become a special purpose pane of its own.

**Comment by 96LawDawg** [comment]
I had an idea for a really useful capability.  Doesn't have to be in this PR.

If possible, we could add a "multiple widget send to other room" feature.  When making a new room, if you want to reuse a bunch a widgets, you can start with that game then delete the stuff you don't want.  But if you also want to reuse a bunch a widgets from another game, there is no easy way to do that.  What would be nice is to make a blank room.  Then go to another room that has a game with stuff you want to copy from.  Multi-select the widgets, then push a button "send to room."  Put the URL there and boom!  Load up the other game that has stuff you want, multi-select, push the button.  Boom.  New game in no time.

Something like this would be very useful for the kinds of things Shobu is working on.

**Comment by ArnoldSmith86** [comment]
So something like https://github.com/ArnoldSmith86/virtualtabletop/pull/694 ?

**Comment by mousewax** [comment]
[this would be for a rev2 of the editor and it's only a thought]
Rather than copying widgets from one state or another, maybe we could set up a kind of collection system where if you have a widget selected it would create a kind of room with only that widget and its subwidgets (using the meta as the collection name and whatever). Recalling that collection just copies all of the widgets from that "room" to this one. I would even love it if I could update a widget with a new collection to easily old games with more usable versions of those same widgets.

Granted, that would really only be useful on servers such as mine, but that would save me a CRAP TON of time. This would replace my need to edit the add widget overlay with my own.

**Comment by ArnoldSmith86** [comment]
Does that do anything that copy-pasting doesn't? Load a game, copy a few widgets, load a different room, paste.

**Comment by rogerl50** [comment]
When the JSON editor is open, why not put the command icons in the top row of the editor?

**Comment by 96LawDawg** [comment]
> So something like #694 ?

Yes.  But I don't feel bad about not remembering an 18-month-old draft PR.

**Comment by mousewax** [comment]
It creates a library of [re]usable widgets that users have access to without having to look for them in whatever game they may have seen them in. It's a minor frustration to have to dig through all of my games where I may have done [cool thing] but can't remember which one it was so I dig through them in another window looking for it only to just ask about it in #help and discover it was actually in one of the tutorials (svgReplace on card faces).

Every game I create gets better and better generic and reusable basic widgets. I'd love to bookmark the dice roller bit that LawDawg updated and add it to my collections.

Sometimes I would go back and find an older version of something I did but it's not the latest one and now I've accidentally forked a good feature (player seats with color pickers and name detection).

**Comment by robartsd** [comment]
> It creates a library of [re]usable widgets that users have access to without having to look for them in whatever game they may have seen them in. It's a minor frustration to have to dig through all of my games where I may have done [cool thing] but can't remember which one it was so I dig through them in another window looking for it only to just ask about it in #help and discover it was actually in one of the tutorials (svgReplace on card faces).
> 
> Every game I create gets better and better generic and reusable basic widgets. I'd love to bookmark the dice roller bit that LawDawg updated and add it to my collections.
> 
> Sometimes I would go back and find an older version of something I did but it's not the latest one and now I've accidentally forked a good feature (player seats with color pickers and name detection).

I think the eventual idea is that the assets section of the public library becomes an enhanced add widget interface. It wouldn't allow every user on the server to add to a customized library, but it would meet a lot of the needs you are indicating here.

**Comment by ArnoldSmith86** [comment]
Yeah. But we could totally let the user add widgets to that list and store them in `localStorage`.

**Comment by ArnoldSmith86** [comment]
FYI for everybody: I got some nice feedback from mouse about the new layout in general.

It mostly boils down to: I'm making the same mistake as with the JSON editor again by jumbling different types of features into the same places. There are modules for "which widgets to edit", "how to edit them" and "debugging feedback" that are thrown into the sidebar.

He made a quick sketch:

Debug

The layout there isn't as flexible and similar stuff is grouped into the same place. I'm pretty sure I'll want to adopt most of the suggestions in one form or another. But for now I'll focus on the properties module and the undo module; we'll need those either way.

**Comment by ArnoldSmith86** [comment]
New concept of a "drag toolbar":

[cinnamon-2023-03-08T180836+0100.webm](https://user-images.githubusercontent.com/73538315/223850180-d161e9e4-7a50-4c0c-80ac-7d8f1f169ec1.webm)
[cinnamon-2023-03-08T181250+0100.webm](https://user-images.githubusercontent.com/73538315/223850185-bf82f638-ad97-4124-9309-1f0f416c45b1.webm)

I'm pushing the changes now so you can play around with them but some key things are missing:

1. A way to toggle "modes" between selection mode (click or rectangle to select - shift for adding/removing, only interact with drag toolbar), edit mode (click to select, drag to move) and play mode (just like normal playing).
2. Modifier keys (toolbar toggles for mobile) for some snapping behavior (only adjust spacing in one direction etc.).
3. Showing the changes with numbers somehow so you can hit your pixels better. (So a popup somewhere that says "Moving by 5px to the left, 2px to the top" or whatever.)
4. I intend for the cloning thingy to create inheriting clones where you can mirror the layout of the children. We'll see how that turns out.

If you have more ideas for the "drag toolbar", I'm all ears.

- I'll probably remove rotation once there is an easy slider in the properties panel.
- Resizing would be a simple one I should probably add.
- Other than that I thought about a "arch" one that you can drag and it will arrange widgets on an ever more curved arch until it is a circle. Feels a bit too specific though.

**Comment by RaphaelAlvez** [comment]
> New concept of a "drag toolbar":
> 
> meeple stash example holder grid example
> 
> I'm pushing the changes now so you can play around with them but some key things are missing:
> 
> 1. A way to toggle "modes" between selection mode (click or rectangle to select - shift for adding/removing, only interact with drag toolbar), edit mode (click to select, drag to move) and play mode (just like normal playing).
> 2. Modifier keys (toolbar toggles for mobile) for some snapping behavior (only adjust spacing in one direction etc.).
> 3. Showing the changes with numbers somehow so you can hit your pixels better. (So a popup somewhere that says "Moving by 5px to the left, 2px to the top" or whatever.)
> 4. I intend for the cloning thingy to create inheriting clones where you can mirror the layout of the children. We'll see how that turns out.
> 
> If you have more ideas for the "drag toolbar", I'm all ears.
> 
> * I'll probably remove rotation once there is an easy slider in the properties panel.
> * Resizing would be a simple one I should probably add.
> * Other than that I thought about a "arch" one that you can drag and it will arrange widgets on an ever more curved arch until it is a circle. Feels a bit too specific though.

image

**Comment by RaphaelAlvez** [comment]
I just realized there is one tool that we need:
Select an area of widgets, click a button select one of those widgets, then the editor uses inheritFrom in the remaining widgets and clean the properties that are equal to the source widget

**Comment by rogerl50** [comment]
There are various kinds of buttons to control function. Currently there is a small set of global buttons in the top left, the old JSON editor global command buttons in the appropriate pane, and the pane management buttons in the right column. These should all be in the top row, and should appear when appropriate. In particular, moving the pane management buttons to the top would improve the amount of available real estate for the editor itself.

I'd also like to see resizable panes, which should be relatively easy using grids or flexboxes.

**Comment by ArnoldSmith86** [comment]
Added an early prototype of `faceTemplates` editing. Select a card and Properties:

image

The changes have to be saved by clicking `Apply changes` at the bottom. Applying them live with every change for potentially hundreds or thousands of cards, is probably not the best idea.

**Comment by ArnoldSmith86** [comment]
I don't see us merging #1482 independently from this (especially because this one will be tested way more).

So I merged this one into #1482 and we'll continue there. Makes it way easier to me to keep up with the changes in `main`.

**Comment by 96LawDawg** [comment]
Just a random GitHub question.  In the past, I think every time I saw "merged" it meant it was merged into production.  This was merged into another (draft) PR.  Is that the normal way this happens.  Slightly confusing to me in the sense that when I look at a list of closed PR's I would initially think that this one got incorporated into production.

**Comment by ArnoldSmith86** [comment]
I created #1482 first - basically like any other PR. And because I wanted to base this PR on that one, I didn't branch from `main` but instead I branched from `feature-splitEdit2`. That way I created this as a PR to the other PR and now I merged it into the other PR.

If #1482 had been merged first, this one would have been merged to `main` because it then included the changes this is based on.

**Pull request merged**
