### PR TITLE
added `fixedParent`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This adds `fixedParent` which makes the engine not touch the parent when the user moves it manually. Very useful for building composite widgets.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3521/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
I did some `fixedParent` testing (though some of it is really just `parent` testing).  These are the results.

Deleting/removing parent deletes child (per usual).  HOWEVER, if you create a new widget with the same id as the parent, then the child widget will "come back" as a child of the new widget of the same id.  I suspect this just reveals an ongoing issue of widgets nor 'really' being deleted when their parent is deleted, but in the past they would lose their parent, thus not 'show up' again. 

Unexpected parent behavior.
Children NOT flipped with parent
odd results with card as a parent (the children exist in the 'window' of the card).
image

Unrelated unexpected behavior:
If you change a holder's drop target from cards to all then the shuffle button will change its own z and won't shuffle cards anymore (will still shuffle other widgets).

Probably as expected:
One of the things I have noticed is that if movable is set to true it will not move its fixed-parent and if it is set to false it WILL still move (if its parent is set to movable), but it will also move its parent.  I assume this is as intended.

Tested (seems to work as expected):
Chaining parents together
Breaking chain in editor & w/ SET
Moving child/parent with editor/SET 
Fixed parent GETable & SETable
Rotation rotates children with parent (not to the same rotation)
Children stick to parent while shuffled
Move/moveXY on fixed parent
Recall fixed parent
Shuffle/sort fixed parent cards (shuffled and sorted according to parent)
Setting parent/fixed parent with clone (of course still odd for cards as parents)

**Comment by robartsd** [comment]
> Unexpected parent behavior:
> Children NOT flipped with parent (e.g. if you flip a checker piece, children checker pieces won't flip).

This is expected behavior, flip does not affect children.

> odd results with card as a parent (the children exist in the 'window' of the card).

This is expected behavior. Cards have overflow:hidden in their CSS.


> Unrelated unexpected behavior:
> If you change a holder's drop target from cards to all then the shuffle button will change its own z and won't shuffle cards anymore (will still shuffle other widgets).

Anything matching the drop target should shuffle. While the shuffle button should change its own z in this case, the cards should still also shuffle.

**Comment by bjalder26** [comment]
> > odd results with card as a parent (the children exist in the 'window' of the card).
> 
> This is expected behavior. Cards have overflow:hidden in their CSS.


Thanks, I meant it was not what I expected, so thanks for clarifying what is working correctly and what may not be.  So it seems like the only issues are:
1) Changing the dropTarget to {} (all) will cause a button to fail to shuffle cards.  On a bit more testing (lower right corner), it does change the z, but it essentially SORTS the deck, and it stops flipping the deck as well.
2) Widgets that "disappear" because their parent are deleted (through a button click) will reappear when a new widget is given the name of their parent.
The first is unrelated, and I suspect the second is an issue with `DELETE` but wasn't really noticed until `fixedParent` brought the widgets 'back'.  In fact, I think this is related to issue #477.

**Comment by bjalder26** [comment]
How is `fixedZ` supposed to 'work' with widgets dropped into holders?  Because that is the only way I can get them to change once they are fixed.

**Comment by robartsd** [comment]
The code looks fine to me, but I haven't tested the edge cases @bjalder26 mentioned having issues.

**Comment by bjalder26** [comment]
> The code looks fine to me, but I haven't tested the edge cases @bjalder26 mentioned having issues.

> Changing the dropTarget to {} (all) will cause a button to fail to shuffle cards. On a bit more testing (lower right corner), it does change the z, but it essentially SORTS the deck, and it stops flipping the deck as well.

This happens on the production server as well, so it is probably not a reason to hold up this PR.  I will make an issue for it.

> Widgets that "disappear" because their parent are deleted (through a button click) will reappear when a new widget is given the name of their parent.

There is already a PR to fix this, and it is not very related.

> How is fixedZ supposed to 'work' with widgets dropped into holders? Because that is the only way I can get them to change once they are fixed.

I simply don't know if widgets should change their Z value if they have fixedZ and are dropped in a holder.  The current behavior in this PR is that their Z value will change to a new Z, but then will become fixed at that new Z until dropped into a holder (other parent changes do not affect the Z value).  If that is how it is supposed to work, then everything is working fine as far as I can see.

**Review by rogerl50 — CHANGES_REQUESTED** [review]
Please add a comment containing draft language to update the Wiki when this PR is merged, so we can keep the Wiki up to date.

**Comment by ArnoldSmith86** [comment]
# Global properties for every widget

| Property  | Default value       | Description           | Tutorial              |
| --------  | ------------------- | --------------------- | --------------------- |
| fixedParent |  false  | When set to `true` the `parent` of this widget will not change when it is being dragged by a player (or editor). Automation can still change it though. |
| fixedZ |  false  | When set to `true` the `z` of this widget will not change when it is being dragged by a player (or editor). Automation can still change it though. |

**Comment by ArnoldSmith86** [comment]
Is that enough and in a format that's helpful?

**Comment by rogerl50** [comment]
> Is that enough and in a format that's helpful?

That's great. Thanks. I just want people to get into the habit of doing this. The Wiki is already pretty out of date and getting worse.

**Comment by robartsd** [comment]
> I simply don't know if widgets should change their Z value if they have fixedZ and are dropped in a holder. The current behavior in this PR is that their Z value will change to a new Z, but then will become fixed at that new Z until dropped into a holder (other parent changes do not affect the Z value). If that is how it is supposed to work, then everything is working fine as far as I can see.

This sounds like it probably only happens with holders with `alignChildren:true`. Not sure if it should or not. If this is the expected behavior then the wiki documentation should explicitly state this as I would tend to interpreted "Automation can still change it though" to mean that routines can set z, but that by default the game engine will not change it.

**Comment by bjalder26** [comment]
> This sounds like it probably only happens with holders with `alignChildren:true`. Not sure if it should or not. If this is the expected behavior then the wiki documentation should explicitly state this as I would tend to interpreted "Automation can still change it though" to mean that routines can set z, but that by default the game engine will not change it.

Even if `alignChildren` is set to false it changes the z value.

**Comment by ArnoldSmith86** [comment]
I removed `fixedZ`. It looked like an easy addition at the time but your comments made me look closer at the code. I don't think there's a way to implement it that makes sense. Because if stuff like flipping a pile (using the UI) doesn't update the `z` value, it completely breaks.

And I always tell people that `z` pretty much shouldn't be touched because it changes all the time. Only `layer` should be used to change the stacking and that is fixed anyway.

I didn't have a use case for `fixedZ` anyway. At this point it shouldn't delay the merging of `fixedParent`. We can always revisit it when we want to have it.

**Review by RaphaelAlvez — APPROVED** [review]
I tested the feature and it works. really good feature.
The documentation on PRs idea turned out to be very useful.
I would also like an approval from @bjalder26 but you already got mine

**Review by bjalder26 — APPROVED** [review]
fixedParent seems to work great to me without any unexpected behavior.  I didn't particularly have a problem with fixedZ, but was reporting on behavior that might or might not be expected.  I'm not sure if fixedZ would even be desired for the same things as you would want to put in piles or holders, so I don't know if that would even be an issue.  If pilesWith or something similar become implemented, then maybe it would negate fixedZ.  Or if a clear use for fixedZ becomes apparent, then it will become clear how it should behave with piles and holders.  I would love to see fixedParent be implemented though.  I have a few uses right now.

**Pull request merged**
