### PR TITLE
tools for creating recurring widget groups

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
# Separate PRs

This is becoming too big and hard to review. I want to have a branch with all those features though for playing around with them locally. And I'll push them to this PR so you can play around with them as well.

I'll split off finished features into their own PRs for easier reviewing. So far #519, #520, #521, #522, #523, #528, #529, #530.

# Preamble

I created some games in the past weeks and two of them got stuck because I didn't have proper tools to create something like this:

Screenshot from 2021-05-22 00-18-14

Many many games need something similar: a region per player (or something similar) that is basically the same except for - well - the player. The current workflow is something like this:

1. Create the different tokens needed for the game.
2. Copy-paste tokens that are needed more than once per player.
3. Go into Ghetto and align the tokens.
4. Add counters and buttons with custom seat logic or whatever.
5. Go into Ghetto and align everything for the first player.
6. In Ghetto select everything, copy-paste and align it for every other player.
7. Fix all the copy errors Ghetto introduces (like misaligned counter buttons).
8. Go through all widgets and give them ids using the player number.
9. Update all automation per player so it actually interacts with that player.
10. For every little tweak from here on out modify every player one by one.

So for every game where I reached the necessity to start this process, I basically rage-quitted for now.

# Finding the right question

I thought a lot about how to improve this process. Others have as well. There are issues by at least @96LawDawg and @RaphaelAlvez that address parts of the problem. A much requested feature is duplication including children.

I tried to forget most of these requests and tried to focus on "what would I _actually_ want".

I want to be able to work on _one_ instance of the player area and have all the others updated automatically. So I started working on the player area of Cities (similar to Carcassonne) and every time I need a feature to make this as little work as possible (on the game creation side), I added it.

That process is far from over but I feel like now is the first time it makes sense to share my progress.

# New features

## inheritFrom

The most important new property is `inheritFrom`. It basically says "if a property is not defined in this widget, look at that other widget instead".

The simple form looks like this:

`"inheritFrom": "otherWidgetID"`

You can also use an object to specify which properties to inherit:

```
  "inheritFrom": {
    "otherWidgetID": [ "image", "svgReplaces" ]
  }
```

And you can even provide multiple widgets (and use `"*"` for the simple "inherit all"):

```
  "inheritFrom": {
    "otherWidgetID": [ "image", "svgReplaces" ],
    "thirdWidgetID": "*"
  }
```

## fixedParent

This has been requested many times.

If I want the different player areas to `inheritFrom` a template, I have to have a parent widget for the whole area. I don't really think a `holder` is the right tool for the job (I don't know, maybe it is). I simply want a common parent so I chose a `BasicWidget`.

Editing children of a `BasicWidget` is a real PITA though because every move removes the current `parent`.

So setting `fixedParent` to `true` lets you move the widget without unsetting its `parent`.

## fixedZ

When implementing `fixedParent` I noticed that moving a widget only updated `x`, `y` and `z` now and I think `z` should also be "fixable". So I just added this without really needing it.

## moving widgets in JSON editor

This is kinda unrelated. But it's a real pain to move `movable: false` widgets in JSON editor. You either change `movable` or you have to toggle edit mode but you don't really get a nice feel for the layout in edit mode IMHO.

So now you can move those widgets with activated JSON editor while holding `CTRL`. It still honours `movableInEdit: false` though.

## JSON editor command for inheriting widgets

The next big part: if you have the parent widget per player that inherits something from the template, you still have to add the children (tokens, counters, labels, buttons) to each of them and have them `inheritFrom` their source widget.

So I added a command. If you edit a widget that other widgets `inheritFrom`, you get a new command `sync children to inheriting widgets` which creates a copy of each child (actually using `inheritFrom`) in each inheriting widget.

# Epilogue

I'll add my current example to the test room but please keep in mind that this is only the first part. I just want you to be able to play with this so I can get some early feedback.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3479/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
This looks great so far. One other feature that would be extremely useful here is the ability to customize child groups, so that the groups for player 1 manipulate player 1's data etc. That would likely take the form of some special property that could be used in each copy. Note that the existing concept of variables probably wouldn't work, as you want to be able to specify widget IDs that refer to the player number/id. So it would likely have to be some concept outside the normal property mechanism.

**Comment by RaphaelAlvez** [comment]
Something I had in mind was proper support for a composed widget. 
a composed widget would be defined by having the same "object" property and each component would have a different "part" property. then we would be able to use something like ${part:label} in automation as a direct link to a collection containing the correct part.
Also, something similar to the inherited property would be a shared property that would be outputted to the whole object.

**Comment by bjalder26** [comment]
I am not sure if this would be a good idea, but it did occur to me that if `inheritFrom` could use any property instead of just id, then the widget they inheritFrom would become `SET`able.  However, I suppose something similar could be accomplished by setting all the `inheritFrom` objects as well.

**Comment by ArnoldSmith86** [comment]
I'm not sure I understand what you're saying. You can just `SET` `inheritFrom` to any widget ID.

Can you give an example?

**Comment by bjalder26** [comment]
> I'm not sure I understand what you're saying. You can just `SET` `inheritFrom` to any widget ID.
> 
> Can you give an example?

That is because it is kind of a crazy thought.  Basically, what you're doing right now might become something like this (though there may be a better way to do the naming.
  "inheritFrom_id": {
    "otherWidgetID": [ "image", "svgReplaces" ],
    "thirdWidgetID": "*"
  }

Then if someone wanted to use a different property other than id, they could do something like this.  In this case "source" is a made-up property that they're using instead of id.  

  "inheritFrom_source": {
    "xyparent": [ "x", "y" ],
    "colorparent": "color"
  "miscparent": ["css", "height", "width"]
  }

Then on the widget you wanted the x & y to be inherited from it could have this property.
"source": "xyparent"

Same for color and other misc properties.
"source": "colorparent"
"source": "miscparent"

Of course, all of this could be accomplished using id (if you know the id ahead of time).  However, where it becomes different is the "source" property would be `SET`able, so it could change during play.  You could get the same effect by `SET`ting the `inheritFrom`s for all the widgets inheriting properties, but getting there would be different.  Say you wanted to change where 40 different widgets were inheriting their color.  If (for the sake of argument) they all need to inherit color from the same new widget, then you would have to change the `inheritFrom` on all 40 widgets, or if it was inherited by a made-up property instead of id, you could just change which single widget has that property (2 string property `SET`s vs 40 object `SET`s).

This is, of course, a cherry-picked example to illustrate what I was talking about.  I can't say it would ever be important, worthwhile, or even a good idea. 

Where I think it MIGHT be most beneficial is if for some reason you can't know the id of the widget you will eventually want to inherit from of for some reason you want to frequently change where a large group of widgets are inheriting properties.

Right now you can't predict the id of piles and clones, but piles might go away, and clones might become predictable.  I can't give you a specific use, so if you can't think of one either, then the smart thing might be to wait and see if anyone winds up needing something like that.  Also, it could be a horrible idea if there are unexpected side-effects that haven't occurred to me.

The idea kind of came from trying to use this on piles for another crazy idea I had about a way to get cards to spread out nicely when a pile is dropped on the tabletop - like in Gin Rummy (an invisible holder that "follows" the pile and spreads them out when they are dropped), and it mostly worked, except it was hard to `SET` since I couldn't know the id ahead of time.  The real problem though was I couldn't think of a good way to 'pick up' a group of cards from a hand and form them into a pile so I gave up on the idea anyway.

**Comment by ArnoldSmith86** [comment]
Interesting but sounds a bit too theoretical for me. Apart from that, I would rather fix `SET`ting IDs.

Your last paragraph sounds like the newest PCIO features. We'll support those eventually (it'll be a lot of work though).

**Comment by ArnoldSmith86** [comment]
Most of the changes are already merged or in other PRs. I will open new PRs for the rest. I don't feel this needs to be kept open.

**Pull request closed without merging**
