### PR TITLE
added Steam Power to public library

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
A game by Wallace Designs, implemented by Jonathan Cox.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2032/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR2032-pr-test`.

**Comment by 96LawDawg** [comment]
The label "supply_contract_count" has an unnecessary toolbar (at least it does on Edge).  Increase the size of the label or change to a basic widget to fix.

Screenshot 2024-02-05 084708

Also, the history table starts out with "Dave's Turn."

**Comment by JonGetsGames** [comment]
> The label "supply_contract_count" has an unnecessary toolbar (at least it does on Edge). Increase the size of the label or change to a basic widget to fix.
> 
> Screenshot 2024-02-05 084708
> 
> Also, the history table starts out with "Dave's Turn."

I tried to change the label, it didn't work, so I clicked undo, and now the label appears to have been deleted? I think you may need to refresh that room back to what it was when I submitted it.  Regarding "Dave's Turn", yeah that is wiped and the first turn is printed when setup is clicked, so I can fix that for the Public Library by manually deleting the text value in that version.

**Review by 96LawDawg — APPROVED** [review]
Requested changes made.  Approved.

**Pull request merged**
