### PR TITLE
Adds spinner options

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
Still has a bug on the spinner layout on the editor

image

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2269/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
I also did some work on dice

image

**Comment by 96LawDawg** [comment]
How does this work?  I don't understand how to see the options.

**Comment by RaphaelAlvez** [comment]
> How does this work? I don't understand how to see the options.

select a dice or spinner and click on properties

image


image
S

**Comment by robartsd** [comment]
I'd change the preview of the top right dice type to show face 0 to make it more clear what the difference between it and the bottom left dice type is (0-9 vs 1-10).

**Review by ArnoldSmith86 — APPROVED** [review]
Like we talked about, this probably won't be the final UI, but it is clearly a big improvements over the current UI.

**Review by 96LawDawg — APPROVED** [review]
Approved.  Looks good to me.

**Pull request merged**
