### PR TITLE
fix scrolling issue in iOS Safari

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
I have no device to test this but according to @mousewax this should fix the issue that Safari on iOS sometimes scrolls the entire page instead of moving the desired widget when in fullscreen mode.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:1122/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Hmm, this messes things up. Selecting widgets in the JSON editor doesn't seem to work at all.

**Comment by RaphaelAlvez** [comment]
@96LawDawg you do have IOS right? can you test this?

**Comment by rogerl50** [comment]
Not knowing exactly what the problem is, I tested the pr-test room by moving several widgets around in Safari. I also changed some to be movable without ctrl. The widgets moved and nothing else did.

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
This does not fix the problem.  It is most noticeable with piles.  I tested it using the piles in the Functions: MOVE tutorial on production and in the test-server.  Most times, but not every time, the whole screen would try to close on an iPad using Safari when trying to drag one of those piles.

**Pull request closed without merging**
