### PR TITLE
reversed the order of MOVE (fixes #77)

### LINKED ISSUE #77: Count parameter of MOVE deals from bottom of deck
While updating COUNT, consider the following. When dealing more than 1 card using count, the function seems to take a pack of say, 5 cards, and then deal from the bottom of the pack rather than the type. This is the opposite of expected behavior and should be changed. I noticed this when working with the SORT tutorial. Screenshot of dealing 1 card (first image) at a time and dealing 5 at a time (second image) from the same sort function attached.
1card

5cards

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The question is: if a button moves 5 cards from one holder to another, should it move one card at a time (effectively reversing the order) or all 5 as one pile?

The former behavior should be what happens right now. @96LawDawg would prefer the latter and I think I agree.

In this PR I changed the behavior for `MOVE` and `MOVEXY`. Please test and discuss. It's entirely possible that this breaks other `MOVE`-related stuff.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3084/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
I will run some tests and let you know.  But just as an initial comment, if you want to move all 5 as a single pile, that is what SPLIT is for.  If you want to deal 5 cards, you deal one at a time from the top until you reach 5 cards, so I agree with this change (if it works).

**Comment by 96LawDawg** [comment]
I tested this and found things worked as expected for MOVE and MOVEXY except when using MOVE on the entire pile.  When using MOVE on all 52 cards in a standard deck, the status quo and the test serve had the same (the pile was picked up in current order and moved as a unit rather than dealing 1 card at a time which would reverse the order of the cards).  Interestingly MOVEXY did not have the same problem.

**Comment by larkob** [comment]
> The question is: if a button moves 5 cards from one holder to another, should it move one card at a time (effectively reversing the order) or all 5 as one pile?

I think both approaches are equally valid, so we should offer a `mode` parameter. We could have the one-by-one as a default, though.

**Comment by larkob** [comment]
Instead of a _mode_ parameter, the MOVE/MOVEXY function should ideally have a _split_ parameter (defaulting to 0 = "all"). So, by default, if you move multiple cards, you move them in one go, but if you changed _split_ to 1, it would move it one by one. 

This is almost the same as with a _mode_ parameter, however, it allows us to specify any number for splitting, not just one-by-one vs. all-at-once. It may seem trivial, but this will become really useful at a later stage (just giving a hint, because it deserves its own issue: being able to distribute cards amongs several target holders when there's no even distribution).

**Comment by pwinckles** [comment]
I like @larkob's suggestion, though I'm not sure that's the right default. My assumption was that the cards were being dealt singly.

Supporting both behaviors would be fantastic because it allows you model games such as [Solo Whist](https://www.pagat.com/boston/solowhist.html) where cards are _not_ shuffled between every hand and are dealt in packets to increase the likelyhood of interesting hands.

**Comment by RaphaelAlvez** [comment]
This PR should be revisited as PCIO added this feature and it would improve compability

**Comment by larkob** [comment]
This will be revisited in the context of achieving full compatibility with MOVE options in PCIO

**Pull request closed without merging**
