### PR TITLE
Adds color to all widgets

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
Addresses #859 

Moved code from basicWidget.js to widgets.js

This code is very important as it allows designers to use the CSS var in any widget they want.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3900/pr-test (or any other room on that server)

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
This should also require a matching change in `cssProperties`.

**Comment by bjalder26** [comment]
I placed this JSON in a bunch of widgets, and it appears to work just fine.  I believe the point being that the color will be much easier to get and set for all widgets now.

```JSON
  "color": "red",
  "css": "background: var(--color);",
```

**Comment by RaphaelAlvez** [comment]
> I placed this JSON in a bunch of widgets, and it appears to work just fine. I believe the point being that the color will be much easier to get and set for all widgets now.
> 
> ```json
>   "color": "red",
>   "css": "background: var(--color);",
> ```

well then can you approve by test?

**Comment by bjalder26** [comment]
> well then can you approve by test?

Sure, but do you want to throw `color: null,` into widget.js so that color comes up as an option in the JSON editor?

**Comment by ArnoldSmith86** [comment]
I don't think `color:null` makes sense. Should be black or something. Which it is for BasicWidget, I think. So just move that..

**Comment by RaphaelAlvez** [comment]
> I don't think `color:null` makes sense. Should be black or something. Which it is for BasicWidget, I think. So just move that..

done

**Review by bjalder26 — APPROVED** [review]
Approved based on testing.

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
This breaks card colors in `Foreign Affairs`.

**Comment by bjalder26** [comment]
It looks like with the default color being black, it will append the color to the css when none is set.
image

**Comment by ArnoldSmith86** [comment]
Hmm, then maybe a default of `null` _would_ be the better solution? Basic widget would still need `"black"` though for compatibility.

**Comment by 96LawDawg** [comment]
As it currently is, this also breaks the reset button for Chinese Checkers.  Made a LONG time ago when I didn't know what I was doing.  I created custom properties for color:red, color:black, etc.  Not trying to change the colors, just labeling the marbles.  Not that big a deal to change, but this could mean there are even more games with breaking changes.

**Comment by bjalder26** [comment]
I suspect this will still affect the cosmetics appearance of some games that used color as a property.  I also suspect that doing a file update to fix the issue would be convoluted and probably not worthwhile.  With the color defaulting to null I don't think it will affect the function of any games.  However, if someone wants to weigh in on that issue, then please do.  I could be wrong.

**Comment by 96LawDawg** [comment]
> I suspect this will still affect the cosmetics appearance of some games that used color as a property. I also suspect that doing a file update to fix the issue would be convoluted and probably not worthwhile. With the color defaulting to null I don't think it will affect the function of any games. However, if someone wants to weigh in on that issue, then please do. I could be wrong.

Well, as I said, this breaks the reset button for Chinese Checkers.  So that is at least one known broken game.

**Comment by 96LawDawg** [comment]
Nevermind.

**Comment by ArnoldSmith86** [comment]
Hmm, I actually think this is superseded by #951 as well. With `${PROPERTY color}` engine support is no longer necessary for this. And it's not unlikely that this PR could cause some issues.

**Pull request closed without merging**
