### PR TITLE
Public Library - Add Guan Dan

### PR DESCRIPTION
**Pull request by littlemissinuka**
Chinese climbing game. VTT Implementation by jade-alarm, Shobu and anewcar. 

---

PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2326/pr-test (or any other room on that server)

### CODE REVIEW

**Review by 96LawDawg — APPROVED** [review]
Approved.

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
The game contains 67 assets and the Attribution only mentions 2 of them (and the poker hands icon is missing "Lorc" as the author).

- Most of them are the cards themselves and their back face (2 back faces actually AFAICT). Looks like an unused deck though.
- One is the player aid which is probably created from scratch but it also contains a bomb icon (https://www.vecteezy.com/vector-art/551918-bomb) and a spades symbol (https://vectorified.com/download-image#spade-icon-15.png).
- https://game-icons.net/1x1/delapouite/checkered-flag.html
- https://game-icons.net/1x1/delapouite/round-star.html
- https://game-icons.net/1x1/delapouite/card-exchange.html
- The timer image: https://pixabay.com/gifs/stopwatch-clock-time-time-tracks-7503/
- ~~The rewind icon. Not sure if that is also game-icons.net?~~ https://game-icons.net/1x1/delapouite/fast-backward-button.html
- Some sort of stone texture. Is that even visible anywhere? (It's behind the "NULL" buttons left of the screen.)
- The image saying `PASS`. Couldn't that just be text on the widget instead?

**Comment by ArnoldSmith86** [comment]
Is deck `movingMeldD` even used for anything? Removing it would probably get rid of the card assets. And some of those game-icons.net assets are only offscreen, aren't they? Can't they be removed?

**Comment by ArnoldSmith86** [comment]
The free license of https://www.vecteezy.com/vector-art/551918-bomb seems to be limited to "10,000 views". No idea what that means for us...

**Comment by littlemissinuka** [comment]
I have got the number of assets down to 5 now and all of them have attributions (apart from the player aid which is created by hollow_universe (Bryce) and now uses the bomb and spade from the symbol picker.

**Comment by ArnoldSmith86** [comment]
I cropped and compressed the card back image from ~2.7MB to ~2.5kB. But afterwards I noticed that the pattern generator actually generates SVGs. Doing this looks similar but IMO a little worse. Maybe I didn't use the exact colors you did. Play with it if you want but the JPG is also fine:

```JSON
        {
          "type": "image",
          "width": 65,
          "height": 34,
          "color": " ",
          "value": "data:image/svg+xml,<svg id='patternId' width='100%' height='100%' xmlns='http://www.w3.org/2000/svg'><defs><pattern id='a' patternUnits='userSpaceOnUse' width='23.07' height='40' patternTransform='scale(0.71) rotate(0)'><rect x='0' y='0' width='100%' height='200%' fill='%236d4176ff'/><path d='M17.62 0l-6.07 10.5m2.74 4.76L8.22 4.75m-5.48 0h12.13M.01 0h23.07M6.07 20L0 9.5m2.74-4.75l-6.07 10.5m-5.48 0H3.33m8.2 4.75L0 .02-11.54 20m40.68 0L23.07 9.5m2.74-4.75l-6.06 10.5m-5.49 0H26.4M34.6 20L23.08.02 11.53 20m-5.46 0L0 30.51m2.74 4.75l-6.07-10.5m-5.48 0H3.33m8.2-4.75L0 40l-11.54-19.98zM17.6 40l-6.06-10.5m2.74-4.76L8.2 35.25m-5.48 0h12.13M0 40h23.07L11.54 20.01m17.6 0l-6.07 10.5m2.74 4.75l-6.06-10.5m-5.49 0H26.4M11.53 20h23.08L23.07 40' stroke-linecap='square' stroke-width='1.5' stroke='%23b7aabc' fill='none'/></pattern></defs><rect width='800%' height='800%' transform='translate(0,0)' fill='url(%23a)'/></svg>",
          "css": {
            "border": "3px solid white",
            "border-radius": "8px"
          }
        }
```

**Review by ArnoldSmith86 — APPROVED** [review]
Attribution looks good now. I don't know much about the game itself but I know that you playtested it a bunch.

**Pull request merged**
