### PR TITLE
Use gitpod/workspace-full-vnc

### PR DESCRIPTION
**Pull request by robartsd**
This switches Gitpod workspaces created from this repository to use the gitpod/workspace-full-vnc image instead of the default gitpod/workspace-full image. Starting up a Gitpod workspace takes about the same time, but the image comes with a visual desktop served to noVNC on port 6080 and Chrome built in. This means that testcafe can run visually (or headless) in Chrome in the workspace with no additional setup.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1594/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1594-pr-test`.

**Comment by robartsd** [comment]
I also named the ports and changed their order (so the ports that we are most likely to want to access directly are at the top of the list).

**Review by ArnoldSmith86 — APPROVED** [review]
Changes look fine to me. I didn't test it though.

**Comment by robartsd** [comment]
> Changes look fine to me. I didn't test it though.

To work on other branches, I've been opening Gitpod from this branch and checking out the branch I want to work on within Gitpod so that I can work in this container.

**Pull request merged**
