### PR TITLE
TestCafe Compute test in legacy modes

### PR DESCRIPTION
**Pull request by robartsd**
For testing #571 only: Adds legacy compute modes to TestCafe Compute tests, runs the tests, then removes the line setting the mode before comparing the hashes.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3606/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
That's awesome... :smile:

**Comment by robartsd** [comment]
> That's awesome...

Yes, I was glad to see that all the tests matched (not really surprised). Now just need to compute the new hashes for every operation.

**Comment by robartsd** [comment]
This latest commit calculates the new hash for all the fixed operations, but does not accurately calculate hashes for random operations since they are test apparatus pseudo random number generator state dependent (first random operation appears to pass, but second random operation fails since the test apparatus pseudo random number generator state is not what it should be when the test starts).

**Pull request closed without merging**
