### PR TITLE
Add Bulls, The Team II, other updates

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:
- Bulls.  New game by ArnoldSmith86.  Similar to 6 nimmt!
- The Team II.  New game by ArnoldSmith86.  Similar to The Crew Deep Sea.
- Reward.  Fixed clone deletion problem.
- Iago. Fixed a widget that should not be movable.

Public Tutorials:
- Functions – SORT. Updates poker hands variant to allow sorting by any combination of 1-5 cards.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3689/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Changed files loaded from public library.

**Comment by bjalder26** [comment]
Reward seems to work well.  SORT seems to work well too, but you might consider having the "Deal X cards" clear out the hand type, and might consider making "The Array" widget look less like a button.

**Comment by ArnoldSmith86** [comment]
You can also use the version of `Team II` with the integrated mission objectives. There will be a new version this or next week anyway though. So you can also just do it then.

**Comment by 96LawDawg** [comment]
> SORT seems to work well too, but you might consider having the "Deal X cards" clear out the hand type, and might consider making "The Array" widget look less like a button.

Done, but I put the clearing out hand types code into the recall and shuffle button.  That is the button that needs to be pressed first in the cycle.

> You can also use the version of Team II with the integrated mission objectives. There will be a new version this or next week anyway though. So you can also just do it then.

Done.  Sorry about that version control problem.

**Comment by bjalder26** [comment]
I feel pretty confident signing off on Reward, Sort, and Iago, but I don't know how to play Bulls or The Team II.

**Comment by RaphaelAlvez** [comment]
> I feel pretty confident signing off on Reward, Sort, and Iago, but I don't know how to play Bulls or The Team II.
> 

It's been play tested and then upgraded. I feel ok about approving this pr

**Review by bjalder26 — APPROVED** [review]
Seems like everything is tested and ready to go.

**Pull request merged**
