### PR TITLE
Fix problem from setting card text layers to black by default

### PR DESCRIPTION
**Pull request by 96LawDawg**
Fixes a problem created by #1874.

If a text layer use something like ` "css": "color:darkgray",` but did not just directly specify `'color": "darkgray"` as was the case in Shattered Dominions, the card text was being set to black and the css was being ignored.  This PR adds a check to see if a css color has already been set and then will not apply the default black.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1880/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1880-pr-test`.

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
That condition would also trigger for something like `border-color` or `background-color`. Can be checked with a regular expression. I'll do that when I have some time.

Also: The applied CSS is already in variable `css`. Should probably check that one instead.

The easiest solution is probably to read the current `objectDiv.style.color`. Its value should probably be `inherit` if nothing is set explicitly? Gotta check.

**Review by ArnoldSmith86 — APPROVED** [review]
I changed the logic. Please have another look. :)

**Comment by 96LawDawg** [comment]
That's a lot cleaner and easier to understand.  And it works.  Ready to merge.

**Comment by robartsd** [comment]
It probabaly would have been better to just set the default color in a stylesheet instead of as an inline style; perhaps implemented with a new class for face object text divs. Might not be worth changing at this point though.

**Comment by ArnoldSmith86** [comment]
Yeah, that sounds like the right idea.

**Pull request merged**
