### PR TITLE
extends various css properties to take simple object form

### LINKED ISSUE #1191: extend simple object CSS to all css properties
It should be simple enough to allow all places where css strings are allowed to take a simple object that creates the css string from key: value pairs by wrapping the cssValue with `cssAsText(cssValue, true)`. 
- card face `css`
- card face object `css`
- pile `handleCSS`
- spinner `backgroundCSS`
- spinner `spinnerCSS`
- spinner `valueCSS`

I don't think these need to support stylesheets or dynamic css using `${PROPERTY propName}` syntax. If dynamic css is required the use the widget css property to set a css variable (or just write a widget stylesheet in the widget css property that targets the widget's child element requiring the dynamic css).

### LINKED ISSUE #1201: add `classes` property to face and face objects
With widget stylesheets it is possible to write styles addressing any sub-element of a widget, but for card faces and face objects, in many cases this currently requires cumbersome `:nth-child()` pseudo class selectors. While these elements can also be given inline styles directly, only a stylesheet can give them dynamic styles (`:hover` pseudo class) or generated content (`::before` pseudo element). To make it easier for designers to target specific faces or face objects, we should allow the game designer to assign classes to these elements.

### PR DESCRIPTION
**Pull request by robartsd**
This extends all css properties to take the simple object form in addition to the string form. Closes #1191.

Also adds `classes` property to card faces and card face objects to make targeting a specific face or object in a widget stylesheet easier. Closes #1201.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1196/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
I tested for card, pile, and the various spinner values.  Worked fine and fixes the question I had in the help channel at https://discord.com/channels/770758631146782780/793626590848352306/964955579640590446.

**Comment by 96LawDawg** [comment]
I also just double checked the other widget types that accept CSS (pretty much everything except for canvas).  They all work fine, but that made me think maybe we should also change the JSON Editor prompt for css from `""` to `{}`.  I don't know about other people, but I much prefer to use the object form now.  Much easier to read.

But if we do that, we would also have to tweak the way the JSON Editor suggests a few common CSS properties (background, border-radius, border, color, and font-size).  We should probably get rig of border-radius as a suggested CSS property since `borderRadius` is now a default widget property and the wiki says it is the preferred format.

**Comment by robartsd** [comment]
> I also just double checked the other widget types that accept CSS (pretty much everything except for canvas). They all work fine, but that made me think maybe we should also change the JSON Editor prompt for css from `""` to `{}`. I don't know about other people, but I much prefer to use the object form now. Much easier to read.
> 
> But if we do that, we would also have to tweak the way the JSON Editor suggests a few common CSS properties (background, border-radius, border, color, and font-size). We should probably get rig of border-radius as a suggested CSS property since `borderRadius` is now a default widget property and the wiki says it is the preferred format.

Not opposed to this idea, but I've done very little with the JSON Editor code - I'm not sure if I'll make an attempt to do that with this PR.

**Review by ArnoldSmith86 — APPROVED** [review]
The code looks fine to me and the test room looks like it was tested a bunch.

**Comment by robartsd** [comment]
> The code looks fine to me and the test room looks like it was tested a bunch.

96LawDawg did quite a bit of testing, but fell short of approval due to recommended tweaks to the JSON editor. I'll merge and open an issue for the editor tweaks.

**Pull request merged**
