### PR TITLE
added property `sticksTo`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This was unbelievably easy. I only tested a simple `sticksTo: { type: card }` on the freeze tokens in Duel 52.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2250/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Adding `sticksTo: { type: card }` to the `cardDefaults` of a normal deck results in infinite recursion crashes. Will investigate at some point.. :grinning:

**Comment by 96LawDawg** [comment]
> Adding `sticksTo: { type: card }` to the `cardDefaults` of a normal deck results in infinite recursion crashes. Will investigate at some point.. 😀

I was just about to test that, because that is another common use case.

**Comment by 96LawDawg** [comment]
Bug in https://test.virtualtabletop.io/PR-2250/lawdawg.  I put sticksTo on several poker chips.  You can move one a time or two, but then the room freezes (max call stack, which I think is recursion).

**Comment by ArnoldSmith86** [comment]
> Bug in https://test.virtualtabletop.io/PR-2250/lawdawg. I put sticksTo on several poker chips. You can move one a time or two, but then the room freezes (max call stack, which I think is recursion).

Yeah, probably the same thing..

**Comment by ArnoldSmith86** [comment]
You can make `dropOffsetX` work yourself:

```JSON

  "enterRoutine": [
    {
      "func": "SET",
      "collection": "child",
      "property": "x",
      "value": "${PROPERTY dropOffsetX}"
    },
    {
      "func": "SET",
      "collection": "child",
      "property": "y",
      "value": "${PROPERTY dropOffsetY}"
    }
  ]
```

**Comment by ArnoldSmith86** [comment]
I don't feel like working on this when `dropTarget` simply works on cards. We can re-open it if we feel like it.

**Pull request closed without merging**
