### PR TITLE
Public Library: Add Wall Street Bets

### PR DESCRIPTION
**Pull request by andypymont**
Add the new public library game Wall Street Bets (similar to Owner's Choice)

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1885/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1885-pr-test`.

**Comment by 96LawDawg** [comment]
Looks good.  Two comments:

In the how to use implementation, there is a graphics glitch where you say "50 → FUND."  The arrow shows up as an error on my screen:
Screenshot 2023-10-28 171642

And what do the 3 small circle buttons below each buy and sell do?  If I knew the rules, I could probably figure it out.  But maybe put that in the how to use explanation.

**Comment by andypymont** [comment]
> In the how to use implementation, there is a graphics glitch where you say "50 → FUND." The arrow shows up as an error on my screen: Screenshot 2023-10-28 171642

That's weird. It's a standard unicode character so that shouldn't be happening. Is it only in the usage instruction or on the actual buttons in the player areas on the table too?

> And what do the 3 small circle buttons below each buy and sell do? If I knew the rules, I could probably figure it out. But maybe put that in the how to use explanation.

They're for when Swap Stock is rolled on the event spinner. I have added this to the usage instructions. Good spot, thanks!

**Comment by 96LawDawg** [comment]
Unicode is working in the game itself.  Just not in the instructions.

**Review by 96LawDawg — APPROVED** [review]
Approved.

You have en-US as the language, but also this: "click the button with the colour/suit of the share you want to receive." Hahaha.  Of course, you don't have to change it.  Just saying ...

**Pull request merged**
