### PR TITLE
enforce `id` to be a string

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
It currently just crashes if it is anything else and it really is not worth it to allow it.

---

PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2313/pr-test (or any other room on that server)

### CODE REVIEW

**Review by 96LawDawg — APPROVED** [review]
Can't do a proper test on this because the current production server does not allow a routine to SET an id.  But approved through code review.

**Comment by ArnoldSmith86** [comment]
Wanna do some more tests now that #1538 is merged?

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
There are a few unexpected things.

If you directly SET an `id` to "null," you get a standard 4-character random id.  But if you SET it to a variable that evaluates to "null," nothing happens.  That seems strange.  I would think in both cases, nothing should change.

If you SET an `id` to the value of an array (or even an array of arrays), the array gets stringified. If you SET an `id` to an object, the `id` becomes "object Object".  And then if you SET another `id` to another object, really strange things happen (because both have the same `id`, but not really the same??).  But if you SET the `id` to the key of an object then the value of that key works. Maybe we should actively ignore anything that is an object?  And we should probably ignore anything that is an array because almost certainly that was not what the designer intended, but I could go either way on that.

Also, if you SET an `id` to an empty array, the room freezes.  An empty object still gives you "object Object."

**Review by 96LawDawg — APPROVED** [review]
Approved through test

**Comment by 96LawDawg** [comment]
> `SET` should now refuse to use anything that is not a string as an `id`. Does that address all your findings?

Yes.  That is the best solution.

**Pull request merged**
