### PR TITLE
listen for touchcancel

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This problem is similar to #1144 but has a different origin.

The hand holder is usually at the bottom of the room. Phones nowadays trigger system gestures when swiping from the bottom. When dragging a card from the hand, you could trigger the system gesture to switch apps or go to the home screen and the card being dragged would just stop in mid air causing the same issues as described in #1072 (the parent is set to null but the owner is not).

This PR listens for the `touchcancel` event which is triggered in situations like this and handles it like it handles a normal `touchend` event. So it will pretend that the player let go of the card in that place.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1146/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
A similar issue could also happen if a client gets disconnected in the middle of a drag preventing mouseup/touchend/touchcancel from being processed (or processed locally on the client but never reaching the server). Ideally we could handle touchcancel or disconnected during drag by moving the dragged widget back o the state it started in.

**Comment by 96LawDawg** [comment]
I tried to test this on an iPhone and an iPad.  I can't test on the phone because the bottom of the VTT window is too far up the screen.  When in landscape mode, there are no system gestures.  On the iPad, same thing in portrait.  In landscape mode, there are system gestures, but you can't seem to do both.  Either you do a system gesture or you interact with the game room.  So I can't test this on Apple devices.  I don't have other devices.

**Review by robartsd — APPROVED** [review]
I can't recreate the issue on my devices either, but the code looks fine.

**Pull request merged**
