### PR TITLE
added `html` to basic widget

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Allows arbitrary HTML inside a basic widget. It gets filtered through DOMPurify though.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1889/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1889-pr-test`.

**Comment by ArnoldSmith86** [comment]
Hmm, this needs to support `PROPERTY` syntax, right?

**Comment by 96LawDawg** [comment]
I put a bunch of stuff into the room.  Works like it should.  But I didn't try anything really complicated.  External URLs work and open in a new tab by default (probably could change that?).  I tried a simple script that did not work.

How else should I test this to try and break it or check for vulnerabilities?

**Comment by mousewax** [comment]
image

**Comment by ArnoldSmith86** [comment]
Not sure but everything that is supported here can already be used in the metadata help texts.

**Comment by 96LawDawg** [comment]
> Not sure but everything that is supported here can already be used in the metadata help texts.

Yes, but it somehow seems more dangerous in the game than on an overlay showing the metadata.  If you don't know, then I certainly don't.  So I will approve after I make a tutorial.

**Comment by 96LawDawg** [comment]
Doesn't work with `svgReplaces`.  And it probably shouldn't.  But I just tried this and could not recolor the meeple:

`"html": "<p>You can put text here and then more after.'"`

Just reporting that.  Not asking for a change.

**Review by 96LawDawg — APPROVED** [review]
Approved through testing and development of a tutorial.

**Comment by ArnoldSmith86** [comment]
Oh, I forgot to say that I changed `PROPERTY` replacement in `css`. Should probably test that a bit. @mousewax, you probably used that a bunch, right? Can you test existing games?

**Pull request merged**
