### PR TITLE
new game: Chronology (similar to Timeline)

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Powered by AI. I went through the list and checked the dates manually. It's not exactly black and white though.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1768/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1768-pr-test`.

**Comment by 96LawDawg** [comment]
Another amazing game.  I know how much you leveraged ChatGPT and Midjourney for this one.  Just awesome.

Mechanics in the room work great but maybe you should make the cards not clickable in the" hands"?  Too easy to accidentally turn them over there.

Also recommend you add the awards from BGG.

And one other question.  The text has line breaks in strange places.  This is especially noticeable when cards are on their back.  Without manually editing 160 cards for spacing and font-size, is there any way to fix that you can think of?

**Comment by ArnoldSmith86** [comment]
I'll check. Might be easy-ish to add hyphenation points.

**Comment by ArnoldSmith86** [comment]
Any more comments? 🙃

**Review by 96LawDawg — APPROVED** [review]
Appred through test.  How did you add soft hypens?

**Comment by ArnoldSmith86** [comment]
1. Checked https://www.hyphenator.net/en/word/Pythagorean
2. Copy-pasted https://unicode-explorer.com/c/00AD

**Pull request merged**
