### PR TITLE
Fix INPUT crash on Cancel

### LINKED ISSUE #1010: INPUT crashes client
While trying to write a routine that would disable a button in preparation for input (so that only one person could click it), I wrote the following:
```JSON
"clickRoutine": [
    {
      "func": "CALL",
      "routine": "disableClickRoutine"
    },
    {
      "func": "CALL",
      "routine": "getNameRoutine"
    },
    {
      "func": "SET",
      "collection": "thisButton",
      "property": "clickable",
      "value": true
    }
  ],
  "disableClickRoutine": [
    {
      "func": "SET",
      "collection": "thisButton",
      "property": "clickable",
      "value": false
    }
  ],
  "getNameRoutine": [
    {
      "func": "INPUT",
      "fields": [
        {
          "type": "title",
          "text": "Please sit down",
          "css": "background-color:var(--VTTblue);color:white;"
        },
        {
          "type": "string",
          "label": "Name",
          "variable": "name",
          "css": "color:black",
          "value": ""
        }
      ],
      "cancelButtonIcon": "thumbs_down",
      "cancelButtonText": "Cancel",
      "confirmButtonIcon": "thumbs_up",
      "confirmButtonText": "OK"
    }
  ],
```
When I click Cancel, the client crashes at the line `variables[a.variable] = result.variable;` in the code for 'CALL' with the error `Uncaught (in promise) TypeError: result is undefined`.

Clicking Cancel on a simple INPUT that is part of the `clickRoutine` directly does not cause a crash; the issue seems to be around the return `result` variable from the `CALL`.

### PR DESCRIPTION
**Pull request by rogerl50**
Fixes #1010. Note that this creates some change in the CALL code as well, so should be well-tested and examined.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4015/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
To me this part looks perfect.  It kind of seems 'right' for it to return an empty collection, and a null variable.
image

`Exception: [object Object]` doesn't seem right though.  Could you possibly want `problems.push(`Exception: ${e.result.toString()}`);` ? (just guessing)
image

**Comment by rogerl50** [comment]
> 
> Also I noticed that the 'applied operation' is recorded before the operation runs, so I suppose changing that would be difficult, and probably either not worthwhile, or not appropriate since the operation isn't really being changed, it is just being aborted.

I made the change you suggested; a cancelled INPUT will no longer create a `problems` report. Assuming that this is the only reason for an exception in that call, this should work fine - the INPUT will just say "INPUT cancelled".

With respect to your "applied operation" comment, the difference between original and applied is just variable substitution. So I think it's correct to post this in any event, since the computation of the applied operation is necessary to even invoke the INPUT statement.

**Comment by bjalder26** [comment]
> > Also I noticed that the 'applied operation' is recorded before the operation runs, so I suppose changing that would be difficult, and probably either not worthwhile, or not appropriate since the operation isn't really being changed, it is just being aborted.
> 
> I made the change you suggested; a cancelled INPUT will no longer create a `problems` report. Assuming that this is the only reason for an exception in that call, this should work fine - the INPUT will just say "INPUT cancelled".
> 
> With respect to your "applied operation" comment, the difference between original and applied is just variable substitution. So I think it's correct to post this in any event, since the computation of the applied operation is necessary to even invoke the INPUT statement.

image
I guess what you did actually makes the most sense.  It probably should be green because it is doing what it is supposed to do.

Also, I agree regarding applied operation.  I kind of think what it is telling us is how variables have been changed, and this does not change that at all, whereas the INPUT canceled tells us that the function was canceled.

**Review by bjalder26 — APPROVED** [review]
Call seems to be working fine still.
Approved based on testing.

**Pull request merged**
