### PR TITLE
changed file extension from vtt to 🎲

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Probably not the best idea I ever had, but I wanted to at least try it. For me it works in Chromium/Linux but not Firefox/Linux. In case we actually want to do this, I would spend a bit more time trying to figure out why.

In the process, I noticed that downloading Chinese Chess is broken. A fix in this PR but we can merge that separately.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1847/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1847-pr-test`.

**Comment by 96LawDawg** [comment]
Are you high?  Is this some kind of Oktoberfest prank I'm too uncultured to understand?  What is the point of this?

**Comment by RaphaelAlvez** [comment]
Ok it's official.. you are insane

**Comment by 96LawDawg** [comment]
@ArnoldSmith86, you seem serious about this.  But I really don't understand why or what this would do.  Explain it to me like I'm 7 years old.

**Comment by ArnoldSmith86** [comment]
"Serious" is a strong word. I listened to an interview about a programming language. They talked about how they used emoji as a file extension. I kinda liked the idea and wanted to test it.

If the reaction to this PR would have been "oh, that's so cool", we could have looked into it.

Since nobody seems to care (and I don't really care either), let's just forget about it. 😄

**Comment by mousewax** [comment]
I actually quite like it. I just didn't feel qualified to comment on it from a technical point of view.

**Pull request closed without merging**
