### PR TITLE
introduced a button that moves a room to a beta server

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The concept is simple: you click a `Beta` button in your room (currently at the bottom of the About overlay), the play continues on another server. You press a `Return` button and the play continues on the initial server.

The idea is to make it easier to test upcoming changes. Right now there are the PR test servers but it gets old fast to tell your friends on game night to go to a cryptic numeric server instead of the normal one.

The other use will be to load older games in older compatibility servers. The feature itself is more or less the same. Just the user experience needs to be a bit different.

Right now I have the basic concept working but it still needs some polish here and there. Player names and colors have to be transfered, the UI needs stuff, etc.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3898/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
OK, I started a second server with these changes at http://212.47.248.129:100001/. It uses red instead of blue so it is recognizable but otherwise it doesn't have any changes.

Clicking the `Beta` button at the bottom of the About overlay should now move the current room to that server and there you should have the `Return` button instead of the games list.

**Comment by ArnoldSmith86** [comment]
Now it redirects to `https://beta.virtualtabletop.io/` (which is the same as `http://212.47.248.129:100001/` for now).

**Comment by bjalder26** [comment]
The playerName and playerColor don't seem to transport between servers, even though I can see it being passed in the URL.
image

**Comment by ArnoldSmith86** [comment]
Yeah, sorry, I didn't update the second server yet.

**Comment by ArnoldSmith86** [comment]
Alright. News.

This actually uses `https://beta.virtualtabletop.io/` as its beta server now which is actually a real beta server (running on the same hardware though).

Whenever a pull request or `main` gets updated, the server is marked as "dirty" and once per hour - if it is dirty - it updates itself by starting with the most recent PR and automatically merging everything that doesn't cause conflicts.

The plan is to have some more beta servers but the others won't be fully automatic so they won't update as often (probably like once a day at first, when I get bored of updating it maybe once a week and when I lose interest once a month :smile:). Since I want to play my weekly game night on a test server, I hopefully do it once a week for quite a while. We'll see.

**Comment by bjalder26** [comment]
playerName and playerColor do transport now, but if you refresh your browser on the test server, then you get a new playerColor and sometimes a new playerName.  There is also some way to 'lose' the return button.  I haven't been able to repeat that though.  There have also been some disconnects, though I'm not sure why.
image

**Comment by ArnoldSmith86** [comment]
> but if you refresh your browser on the test server, then you get a new playerColor and sometimes a new playerName

For guests or for real names?

> There is also some way to 'lose' the return button.

Probably when the room is completely empty because then it gets destroyed.

**Comment by bjalder26** [comment]
> > but if you refresh your browser on the test server, then you get a new playerColor and sometimes a new playerName
> 
> For guests or for real names?

I believe earlier it was for both.  Now it seems like only Guest names have any change, and it is only the color that changes.  To me that doesn't seem like it is an issue.

> > There is also some way to 'lose' the return button.
> 
> Probably when the room is completely empty because then it gets destroyed.

I can't recreate it.  Maybe the issue is gone.  I did 'break' this room though if you want to look at that. 
http://212.47.248.129:3898/Test
https://beta.virtualtabletop.io/Test

**Comment by ArnoldSmith86** [comment]
This is getting closer and closer to what I imagined.

Would be nice to here some feedback from @robartsd, @96LawDawg, @RaphaelAlvez, @rogerl50...

**Comment by bjalder26** [comment]
I saw a button, so I clicked on it. 

Are the editor and futureproof buttons supposed to work?  The editor button did not work for me.  It gave me an internal server error.  I didn't click on the futureproof button.
image

**Comment by 96LawDawg** [comment]
When I created a new room on the standard test server, I loaded a game from my personal files.  I took 2 seats in it.  I then clicked on the automatic server button.  It dumped me into the beta server with nothing loaded up and a public library screen.  I then tried it with a game from the public library that had seats.  Same problem.  I tried it with a public library game without seats and it worked fine.  So something about seats is messing with it.  I think.

**Comment by bjalder26** [comment]
Okay, I think maybe I replicated the issue.  I moved to the 'automatic' server, then did a hard refresh (shift-F5).  Then I couldn't get the reset button until I backspaced to the test server and 'reentered' by pressing the 'automatic button again.

**Comment by ArnoldSmith86** [comment]
OK, thanks for testing! Might be a few days before I can look at it. Might not.

**Comment by 96LawDawg** [comment]
Another thing I noticed.  If I transferred to the beta server and there was no return button for whatever reason, it seems I can NEVER get back to the original room.  Try http://212.47.248.129:3898/LawDawg.  It automatically swaps to the beta server and there seems to be no way to load the original room.

**Comment by ArnoldSmith86** [comment]
> If I transferred to the beta server and there was no return button for whatever reason, it seems I can NEVER get back to the original room.

True. I'd rather focus on making sure that never happens though. The latest commits should take care of many cases where this could happen.

Please report if it happens again (after the beta server was updated again at 19:25 UTC). This won't fix rooms that are already broken though.

**Comment by ArnoldSmith86** [comment]
In case you somebody didn't find it: the beta servers have a modified about overlay that shows the time of server generation and a list of all contained PRs:

image

**Comment by ArnoldSmith86** [comment]
> Okay, I think maybe I replicated the issue. I moved to the 'automatic' server, then did a hard refresh (shift-F5). Then I couldn't get the reset button until I backspaced to the test server and 'reentered' by pressing the 'automatic button again.

This should be fixed now. Please try if you can replicate it again.

**Comment by ArnoldSmith86** [comment]
> Are the editor and futureproof buttons supposed to work? The editor button did not work for me. It gave me an internal server error. I didn't click on the futureproof button.

They are supposed to work, yes. Your test triggered a `Error: File version 5 is newer than the supported version 4.` I'm not sure how that can happen because the source server (`http://212.47.248.129:3898/`) doesn't support version 5 either.

If you can reproduce it, I would be very interested in the procedure.

**Comment by bjalder26** [comment]
> > Okay, I think maybe I replicated the issue. I moved to the 'automatic' server, then did a hard refresh (shift-F5). Then I couldn't get the reset button until I backspaced to the test server and 'reentered' by pressing the 'automatic button again.
> 
> This should be fixed now. Please try if you can replicate it again.

It no longer occurs.

**Comment by bjalder26** [comment]
> > Are the editor and futureproof buttons supposed to work? The editor button did not work for me. It gave me an internal server error. I didn't click on the futureproof button.
> 
> They are supposed to work, yes. Your test triggered a `Error: File version 5 is newer than the supported version 4.` I'm not sure how that can happen because the source server (`http://212.47.248.129:3898/`) doesn't support version 5 either.
> 
> If you can reproduce it, I would be very interested in the procedure.

I had Flora open, and moved back and forth from the beta (automatic) server, then tried the editor button. Not sure why it happened then.

However, I did have another internal server error when I was using flora with the browser debugger open.  I used the back button, then everything seemed fine.

Then I went back to the beta server again and tried to replicate that.  However, Instead this is happening when I try to return to the test server.
image

https://beta.virtualtabletop.io/test5

**Comment by bjalder26** [comment]
That commit 'fixed' the room I broke.

**Comment by ArnoldSmith86** [comment]
I loaded Flora and could do a roundtrip to each beta server.

I think I addressed everything you guys reported. Can you find more problems?

**Comment by rogerl50** [comment]
The blue stripe for the various beta servers is no longer red. (FF/MacOS)

**Comment by rogerl50** [comment]
I've tried loading multiple games back and forth to the various beta servers and making edits on the beta servers. Didn't encounter any issues.

**Comment by ArnoldSmith86** [comment]
> The blue stripe for the various beta servers is no longer red. (FF/MacOS)

Yeah, I don't think I want the red. I basically don't want my peers to even notice that we're playing on a beta server. I did it initially because there was no other way to tell. Now you can just look at the about screen.


Also: any suggestions for the texts?

**Comment by rogerl50** [comment]
What do you mean by "texts" If you mean the text at the bottom describing each server, it took me a couple of minutes to realize what the "Yeah" column meant, but in the end I think it's all clear.

Also, the second two servers (editor and futureproof) should probably have names, not ip addresses.

Finally, I just tried to go to the editor server from the PR server (which is http://212.47.248.129:3898/pr-test) and received the attached message. Note that the ip address is the same
Screen Shot 2021-11-28 at 11 05 34 AM
.

**Comment by ArnoldSmith86** [comment]
> Also, the second two servers (editor and futureproof) should probably have names, not ip addresses.

Yes. That's not part of the PR though. All of that is in `config.json`.

**Comment by ArnoldSmith86** [comment]
> Finally, I just tried to go to the editor server from the PR server (which is http://212.47.248.129:3898/pr-test) and received the attached message. Note that the ip address is the same

Hmm, I just checked. Somehow `pr-test` on the editor server was v5. So it couldn't even load it before even trying to copy the state over. I don't know how it got to v5 though.

I nuked all rooms on the three beta servers. Let's see if it happens again after all the recent fixes.

**Comment by rogerl50** [comment]
Is it possible to modify this so that you can move a room from a PR server to production? There are times when I see something odd and want to see if it happens in production, but often I don't have a loaded room - just put widget in an empty room - and AFAIK it's still not that easy to get those into another room.

**Comment by ArnoldSmith86** [comment]
Yeah, we can do that. Would just be a matter of putting it into `config.json` for the PR test servers.

**Review by rogerl50 — APPROVED** [review]
Approved through test.

**Comment by robartsd** [comment]
It is a bit confusing to me that switching servers is done through the About overlay, but returning is done through the Games List overlay. I think a return return path should also be provided on the About overlay.

**Comment by ArnoldSmith86** [comment]
Yeah, that's a good point.

**Comment by robartsd** [comment]
Could also use a download state button (probably on the Games Library overlay) on the Beta server. Currently the only way to get the state is to use the JSON editor in a room on another server to copy the state.

**Comment by ArnoldSmith86** [comment]
Well, you should know exactly what you're doing because the automatic beta server can contain PRs that do a file version update. And there is no guarantee that the file version number of that PR won't change.

So if you download your game there, it might never work anywhere ever again without manually undoing a fileupdater.

**Pull request merged**
