### PR TITLE
hide inactive guests from player list

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
I am not sure if I want this or not but I thought I would throw it into a PR.

Rooms used for a longer time tend to accumulate guest players in the player list. This PR hides them if they are inactive (not currently connected).

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3790/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
I'd rather they get removed from the room state altogether rather than just hidden. All players in the room state affect the new player color selection.

**Comment by ArnoldSmith86** [comment]
Hmm, good point. Gotta think about if there are any downsides to that.

**Comment by robartsd** [comment]
> Hmm, good point. Gotta think about if there are any downsides to that.

The current code for a new player color looks at the hue of all players (ignoring very low saturation colors), finds the largest gap in hue and picks a random color within the middle third of that gap. It would be nice if this code could determine if the players are active or not, then it could always choose a color in the largest gap in hues among the active players (perhaps still attempting to distance from colors of inactive players within that gap).

**Comment by mousewax** [comment]
I actually thought I might include a checkbox "Show Inactive Players" that then just shows them, but didn't want to introduce too much at once on my first contribution. I know it wouldn't necessarily fix the choosing colors problem, but I could add that back in.

**Comment by bjalder26** [comment]
This appears to work.  I guess this depends on whether you prefer removing the inactive players or hiding them.

**Comment by ArnoldSmith86** [comment]
We could still have a checkbox to show/hide inactive players but I feel like it's fine either way to completely forget about inactive guests that don't own any widgets.

**Comment by bjalder26** [comment]
> We could still have a checkbox to show/hide inactive players but I feel like it's fine either way to completely forget about inactive guests that don't own any widgets.

I didn't realize you and robartsd reached an agreement on removing them, and thought they were still being hidden.

**Review by bjalder26 — APPROVED** [review]
I believe I tested every scenario (ownership/no ownership, Guest name/non-Guest name, array/not array), and everything appears to work correctly.  I also looked at the code, and it appears to work as designed.

I think this will be a nice feature in preventing rooms from filling with Guest player names, but retaining other names when they go inactive.

**Comment by 96LawDawg** [comment]
Not sure if this isn't working right, or if it only works on rooms created after the merge.  I know it tested okay, but on the production server, inactive names still appear.

**Comment by ArnoldSmith86** [comment]
Yeah, I was really excited to check /Tutorials after it got merged but then I realized it won't remove anything retroactively.

It triggers when a player leaves and then only removed _that_ player if it was an inactive guest. So I guess it's one more manual cleanup...

**Comment by 96LawDawg** [comment]
But I love the tutorial list.  It is awesome.  Not so much in my personal game room.

**Pull request merged**
