### PR TITLE
don't hide card child widgets

### LINKED ISSUE #225: Cards do not accept children
When trying to attach widgets to a card, the widget simply disappears from the board.  See demo room at [https://virtualtabletop.io/09of](https://virtualtabletop.io/09of).  The single card at the top, King of Spades, has the ID of "cardtest."  Try setting the parent of a holder, card, or another widget type to that card and the widget simply disappears.

### PR DESCRIPTION
**Pull request by robartsd**
This should fix #225

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3226/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Unfortunately, this does not work.  Testing in the test room results in the same behavior as before with the child widget disappearing when the parent is set to a card.

**Comment by robartsd** [comment]
I'm guessing that the child widget is also hidden beneath the active face in addition to the issues ArnoldSmith86 pointed out in the issue. Try setting a z value?

**Comment by robartsd** [comment]
Child widgets are now appearing on the card.

**Review by ArnoldSmith86 — APPROVED** [review]
Code looks good, thanks. I didn't test it but I'm sure @96LawDawg will give it another go.

The removed `overflow: hidden` changes cards that have bigger face objects than the card itself, I think. Bug? Feature? I don't know.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Works as it is supposed to.  However, I would not that ArnoldSmith86 mentioned that the "overflow:hidden" property was supposed to be moved to "faces."  That was not done and I don't see how it could be done because there is "face" property anywhere in the css.

Update--I posted this right after ArnoldSmith did, so I didn't see his revised comment about overflow:hidden until now.  I certainly don't know the answer to the question either.

**Comment by robartsd** [comment]
> Code looks good, thanks. I didn't test it but I'm sure @96LawDawg will give it another go.
> 
> The removed `overflow: hidden` changes cards that have bigger face objects than the card itself, I think. Bug? Feature? I don't know.

Yes, this did remove `overflow:hidden` from the card (it was already present on the face) as suggested by ArnoldSmith86 in the issue. Child widgets are still getting some face styles here including `overflow hidden`. Perhaps I should have changed `.card > div` selector to `.card > div:not(.widget)` instead of overwriting `display:none` with `.card > div.widget`. I think `.card > div.active` would still be higher specificity.

**Comment by robartsd** [comment]
Or even simpler, move all styles for the active face to `.card > div.active` leaving only `display:none` applying to `.card > div`; then `.card > div.widget` only has the one property to override.

**Review by RaphaelAlvez — APPROVED** [review]
Everything looks good. Tested and code reviewed

**Pull request merged**
