### PR TITLE
Return null for undefined properties

### PR DESCRIPTION
**Pull request by robartsd**
We delete properties when they are set to null, so we should return null for undefined properties.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3417/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
This does work for the test example I gave, but it breaks some other things.  I have no idea why or what.  But the "rules" button in Mancala is broken.  On this test server, pressing the rules button freezes up the room.

**Comment by robartsd** [comment]
Somehow it looks like GET is broken by this.

**Comment by ArnoldSmith86** [comment]
> This does work for the test example I gave, but it breaks some other things. I have no idea why or what. But the "rules" button in Mancala is broken. On this test server, pressing the rules button freezes up the room.

Sounds like a new TestCafé test candidate.

**Comment by robartsd** [comment]
Crash happens when `IF` starts the evaluation of a embedded routine. Error is message in Chrome `Uncaught (in promise) TypeError: routine is not iterable`. I can't find any reason the code changing properties returned would be involved here. Should probably test to see if `CALL` is also affected.

**Comment by ArnoldSmith86** [comment]
`const routine = this.p(property) !== undefined ? this.p(property) : property;`

When changing the return value of `p` we need to make sure that nothing like this breaks.

If this only manifests in `SELECT`, maybe we should just change it there. Not sure though because in the end your approach might be cleaner.

**Comment by robartsd** [comment]
> `const routine = this.p(property) !== undefined ? this.p(property) : property;`

Where is this line?


> If this only manifests in `SELECT`, maybe we should just change it there. Not sure though because in the end your approach might be cleaner.

I don't object to changing undefined to null in routine code; however, when I realized that we were silently deleting properties with null values, I thought that we should return null values where the properties don't exist. Certainly I don't expect game designers to deal with the subtleties of the difference between null and undefined.

**Comment by robartsd** [comment]
I've searched all the client side JS for `.p(` and only find one other instance where a the result is directly compared to `undefined`. In `applyVariables` undefined properties are replaced with `null` (line 141 of widget.js):

`field[v.parameter] = (w.p(v.property) === undefined) ? null : w.p(v.property);`

**Comment by robartsd** [comment]
Looks like the issue is fixed now.

**Review by 96LawDawg — APPROVED** [review]
Approved through test, but we might want @ArnoldSmith86 input again.

**Comment by ArnoldSmith86** [comment]
I like this change but I feel like it has a pretty high probability to break stuff. So it should probably be tested pretty thoroughly.

**Comment by robartsd** [comment]
I've reviewed all the client JS code looking for instances where the modified code might be called. The only places I've found are:
- `StateManaged.applyDelta` assigns the return value to an element in `deltaForDOM`
- `BasicWidget` overrides `StateMangaged.getDefaultValue` to check for the active face properties, then returns value from `StateManaged.getDefaultValue` if property is not defined by the active face.
- `Card` overrides `StateManaged.getDefaultValue` to check for the presence of the property in the card type, then returns the value from `StateManaged.getDefaultValue` if the property is not defined by the card type.

Not yet sure what the impact of changing `undefined` values in deltaForDOM` to `null` is, but this seems to be the only remaining area of concern for this PR.

**Comment by robartsd** [comment]
`deltaForDOM` gets sent to `applyDeltaToDOM` which most widgets have some test comparing properties to undefined. I think I'll move the code that replaces `undefined` with `null` from `getDefaultValue` to `propertyGet` to avoid changing the values that occur in `deltaForDOM`.

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
Although I approved it earlier, looks like there have been some more changes that I haven't had the chance to test, so just putting this here as a reminder to me or anybody to test.

**Comment by robartsd** [comment]
> Although I approved it earlier, looks like there have been some more changes that I haven't had the chance to test, so just putting this here as a reminder to me or anybody to test.

Thank you.

Modified code should change less than before (replaces `undefined` with `null` where `propertyGet` handles the result of `getDefaultValue` rather than making the change in `getDefaultValue`). Passed red checker test case you provided and does not break processing of `IF` functions in routines; but a bit more testing would be good. I'm pretty confident that I've looked at all the client code that this might affect and that it is ready to go.

**Comment by robartsd** [comment]
OK, now I'm confused, something merged in from main seems to have broken this. The error listed sounds like a test is getting to a point running the widget code where `this` does not refer to a valid widget and therefore has no `.p()` method. I guess `this.p()` returns undefined if `this.p` is not defined.

**Comment by robartsd** [comment]
> There is no `p` anymore. It's `get` and `set` now.

That should have been obvious to me, but it wasn't today.

**Comment by ArnoldSmith86** [comment]
Technically this is a breaking change because it changes `SELECT` behaviour. It could include a fileupdater that changes `SELECT`s that have a `value` of `null` and a `property` that is not `parent` (or the other properties that have a default of `null`).

I'm fine with doing it without an updater. I'm just saying we should be pretty sensitive about this stuff. It wouldn't be the first time that someone's game is breaking because of totally reasonable changes.

**Comment by robartsd** [comment]
> Technically this is a breaking change because it changes `SELECT` behaviour. It could include a fileupdater that changes `SELECT`s that have a `value` of `null` and a `property` that is not `parent` (or the other properties that have a default of `null`).
> 
> I'm fine with doing it without an updater. I'm just saying we should be pretty sensitive about this stuff. It wouldn't be the first time that someone's game is breaking because of totally reasonable changes.

For tests against a literal `null` the only way I see this breaking something is if there are properties that default to `null` for some widget types but simply do not exist by default for other widget types. For tests where the value being compared is dynamic this could be more complicated.

**Review by ArnoldSmith86 — APPROVED** [review]
Code looks fine to me.

I didn't test this but it sounds like you spent enough time checking that nothing else depends on `undefined`.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Pull request merged**
