### PR TITLE
fixed disappearing children of cards, basicwidgets and buttons

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This PR fixes some cases where children would break:

- If properties of a card or spinner changed that triggered a rebuild of their DOM, all their children would disappear.
- If the text of a BasicWidget or button would change, all its children would disappear.
- If a spinner was a child of another spinner it would have the spinning part as another background (because of a CSS rule `.spinner > .spinner` (the spinning part of a spinner also had class `spinner`).

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3438/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Compare https://virtualtabletop.io/4bwh with http://212.47.248.129:3438/pr-test.

**Comment by RaphaelAlvez** [comment]
Do you think this solves the problem in timers?

**Comment by ArnoldSmith86** [comment]
It does but the new function `setText` has to be used in the timer.

**Review by RaphaelAlvez — APPROVED** [review]
Tested your test room and tested the spinner tutorial. nothing changed there and you test from does fix the problem.

**Pull request merged**
