### PR TITLE
fixed some edge cases with default values

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
There were a few places in the code that directly accessed `widget.defaults` instead of `widget.getDefaultValue()`. For the most part that is not a problem but for cards default values can be changed in the deck.

The problem that came up is #337: Setting a `x: 100` in `cardDefaults` would not change the behaviour that moving the card to `x: 0` would remove `x` from the card. The system assumed that the default would be `x: 0` but as soon as it is removed it would use the `x: 100` from `cardDefaults`.

### CODE REVIEW

**Comment by bjalder26** [comment]
I put some cards in there that show x/y, and that is no longer an issue, even if nothing is entered on the cardDefault screen.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Review by robartsd — APPROVED** [review]
Didn't test, but the code looks good to me.

**Comment by bjalder26** [comment]
I am still seeing some weird stacking behavior in newly created cards that have x and y dynamic properties.  This is what happens.
- I create new cards
- I stack two of them into a pile
- I remove one of the from the pile
- That card immediately gets offset from the other card an equal distance as they were from the origin
- The stationary card still has a 2 as if it is part of a pile
- Stationary card still shows 0,0, while the card that was moved shows the actual offset from the origin that the stationary card had
- Moving either card makes them go "back to normal" making both of their displayed x/y increase to the actual number


With that being said, I am not using cards for this purpose anymore, now we use a basic widget and changeRoutine.  Also the behavior disappears if I go in and delete this
{
      "x": "",
      "y": ""
 }"

 http://212.47.248.129:3436/pr-test

**Comment by robartsd** [comment]
> I am still seeing some weird stacking behavior in newly created cards that have x and y dynamic properties. This is what happens.
>
> http://212.47.248.129:3436/pr-test

If any card in the deck has no parent and x and y deleted (inheriting "", "" from cardTypes), then any pile with cards from the deck exhibits this behavior. Draging a card from the pile fails to remove it from the pile for some reason. If you drop the card then pick it up again, it finally actually leaves the pile. If the pile only had two cards, dragging the second card from the pile location destroys the pile, but if there are more than two cards in the pile, then dragging the last card from the pile location behaves just as all the other cards.

**Comment by ArnoldSmith86** [comment]
This doesn't seem to be related to dynamic `x` and `y` at all. If I add a normal deck of cards to an empty room and put one its cards to 0,0, I get the same (on production slighlty different) buggy behaviour.

When removing a card from a pile, it seems to put it to `parent: null, x: 0, y: 0` first before actually moving it to the mouse position. And when it finds another card there, it forms a pile with it and completely messes up the piling stuff.

I feel like it's still related to the fix in this PR so I'll try to update it here.

**Comment by bjalder26** [comment]
I am not seeing that behavior anymore with my cards.

**Comment by robartsd** [comment]
> When removing a card from a pile, it seems to put it to `parent: null, x: 0, y: 0` first before actually moving it to the mouse position. And when it finds another card there, it forms a pile with it and completely messes up the piling stuff.

That makes some sense. Moving cards again after they've been moved from the pile works because they are offset from 0,0 when parent is set to `null`. Sounds like if there happened to be a card at exactly the location in the room that they were offset from the origin of the pile they would exhibit the same behavior.

**Pull request merged**
