### PR TITLE
Update library (Add Stratagem and Assets-Spinners).

### PR DESCRIPTION
**Pull request by 96LawDawg**
Rummy Tiles updated to fix problem with last tile moving moved when pile was destroyed.  Downtown updated to improve automation and claim player routines.

Stratagem by LawDawg and Spinners assets by RaphaelAlvez.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3149/pr-test (or any other room on that server)

**Review by RaphaelAlvez — APPROVED** [review]
Approved by test

**Review by ArnoldSmith86 — DISMISSED** [review]
Rummy Tiles no longer has a year. Did you want to change that?

**Comment by 96LawDawg** [comment]
Messed up somewhere.  Going to do it again.

**Comment by robartsd** [comment]
> Rummy Tiles no longer has a year. Did you want to change that?

Rummikub is from 1977. I didn't think I had included it in my original submission (though I year set to 1977 in my development room at some point prior to submission). It does look like most games do have the year of the "similar to" game, I thought library maintainers may have added it back in. I'll update my development room with the year so that future updates will include year if year of "similar to" game is desired for public library submission.

**Comment by ArnoldSmith86** [comment]
It might be a good habit to always add the game from the public library before adding improvements. You never know if someone else improved it in the meantime (unless you follow every commit)..

**Comment by 96LawDawg** [comment]
I agree with ArnoldSmith86 that pulling from the public library before adding improvements is a good idea.  However, even though it is a public library, so far people are generally taking ownership of their own games.  I don't think I would approve a change to a public library game from a new person without checking with the original developer first.

**Comment by ArnoldSmith86** [comment]
Sure, if he's available. It's public domain (or similar) for a reason though. :)

**Comment by 96LawDawg** [comment]
I agree, but at least while we are a small community, this is manageable.  But I wouldn't NOT approve it; I would just do a courtesy check.

**Pull request closed without merging**
