### PR TITLE
add font symbols to timers and counter

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
adds our font icons to timers and counters.

does not apply to old widgets

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1266/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
I linked #1018 because it included this.  But I think that is actually broader than this, so you may want to unlink it.

**Comment by RaphaelAlvez** [comment]
> I linked #1018 because it included this. But I think that is actually broader than this, so you may want to unlink it.

thanks. no that's exactly what the issue was. I just forgot to link it

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

Before:

Before

After:

After

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
In general I think this is a good change.

But the timer icon doesn't make sense to me. It was a play/pause icon (which is exactly what the button does), now it is a skip/next icon (which it doesn't do).

**Comment by RaphaelAlvez** [comment]
> In general I think this is a good change.
> 
> But the timer icon doesn't make sense to me. It was a play/pause icon (which is exactly what the button does), now it is a skip/next icon (which it doesn't do).

I didn't even notice that it was not the same.
I'll talk to @mousewax because I don't know how to add it.

**Comment by ArnoldSmith86** [comment]
Is there no matching icon in the material icons?

**Comment by 96LawDawg** [comment]
> I'm still very worried about the fact that you made the font 46% smaller:
>  
> If everything still works, that's awesome of course. But maybe we should ask @mousewax about it...

Fine with me.  But you can see in https://test.virtualtabletop.io/PR-1266/lawdawg that all the fonts are still there.  I just loaded the asset that lists all the symbols.  Everything works.  My best guess as for the size decrease has to do with the save options in the program I'm using (see screenshot).  I just accepted all the defaults.  If I added in some of those option settings, my guess is the fill would be bigger.  I don't know which ones I would use, but I do know everything still works on VTT.

Screenshot 2022-07-13 143350

**Comment by 96LawDawg** [comment]
@ArnoldSmith86, straight from @mousewax:  "I used a lot of automated tools and those tend to leave a bunch of cruft. If it's working, I wouldn't worry."

**Comment by mousewax** [comment]
Specifically I authored the font as a TTF in one tool and then used another online tool to create the WOFF from that. Double automated tools built for a bunch of different use cases. BAM... fat font. I didn't think the bloat would be that bad so I didn't push it through another step to shrink it.

**Review by ArnoldSmith86 — APPROVED** [review]
The icon looks correct now. Better than the old version even.

Code changes also look fine.

**Pull request merged**
