### PR TITLE
Add Don't Blow Up, Nine Men's Morris, Quad Line, many other updates

### PR DESCRIPTION
**Pull request by 96LawDawg**
Many of these edits were prompted by recent changes allowing for additional customization on buttons for colors and images.

Assets:
  - Add example of text and image on same button in universal game symbols; add library image
  - Add a new variant of Dice with BicycleIndividual’s completed jumping dice deck

Tutorials:
  - Add example of text and image on same button in Button Appearance tutorial 2nd variant
  - Fixed an outdated comment in Functions – ROTATE and update appearance of rotate buttons
  - Fixed text that did not fit in the button space in Functions – COMPUTE in the 1st variant
  - Fixed colors in buttons in SKIP in the 2nd variant

Public Library New:
  - Added Don’t Blow Up (similar to Exploding Kittens), Nine Men’s Morris, Quad Line (similar to Connect Four), and Quad Line 3D (similar to Connect Four 3D) all by ArnoldSmith86

Public Library Updated:
  - Alleys: created reset button
  - Blue:  updated universal symbols; increased size of player name labels
  - Diced: updated universal symbols and on hover properties for buttons
  - Dominoes: updated universal symbols and on hover properties for buttons; changed variant name to blank
  - Stratagem: update universal symbol (reset)
  - Tantrums: updated universal symbols and on hover properties for buttons; made starting cards flip face up on boards 2,3 and 4
  - Tittle: changed variant name to blank; updated universal symbols and on hover properties for buttons
  - Whisky Cat: updated colors on buttons

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3394/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
All games successfully loaded from library, but I need to find the problem(s) that are taking place in TestCafe.

**Comment by ArnoldSmith86** [comment]
It is expected that the tests for updated games break. I'll have a look.

**Comment by 96LawDawg** [comment]
The problems are in the ROTATE tutorial and Blue.  Nothing in the code changed, just appearances, so probably just need a new checksum.  I'll read the TestCafe wiki and see what I can figure out.  Would be good for me to know.

**Review by ArnoldSmith86 — APPROVED** [review]
Nice update.

**Comment by ArnoldSmith86** [comment]
I found a _huge_ problem: the universal icon for "deal 1 up" has a "2" that doesn't use `currentColor`. It just stays black!

**Comment by 96LawDawg** [comment]
I fixed the deal 1 up icon color.  I also cleaned up all of the css on the button images, to include changing the border-raduis.  That had gotten a little bloated and included a lot of things it didn't need and left out the one thing it did.  Thanks.  Going to merge now.

**Pull request merged**
