### PR TITLE
style section titles in library list so they stand out

### PR DESCRIPTION
**Pull request by tsankuanglee**
small improvement for now. as discussed in Discord

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3736/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
The header line "Game Similar to ..." that formerly appeared at the top of the list now appears only after the Tutorials and Assets headers. It should appear at the top as it used to (possibly with its own header), and if we are going to implement this change, we may as well change the header line for the other two sections to be more appropriate for the contents.

**Comment by tsankuanglee** [comment]
> It should appear at the top as it used to (possibly with its own header), 

I modified my `library.json` so it has its own section title, "Official Repository", but you are right, I should have it displayed even if there's no section title. Will fix it tonight.

> and if we are going to implement this change, we may as well change the header line for the other two sections to be more appropriate for the contents.

Agreed. However, this PR is only intended to be an intermediate solution until a proper redesign is ready (I heard somebody is working on that but might take a while). Besides slightly improving the looks, it also solves the problem of user pressing non-working Add buttons (and generating errors).

To support more sophisticated categories, the  structure of `library.json` should be objects of arrays, instead of just an array. We can address this in the redesign phase.

**Review by RaphaelAlvez — APPROVED** [review]
Code review and tested. aprroved. @96LawDawg is "Tutorial Follow" a good title?

**Comment by 96LawDawg** [comment]
> Code review and tested. aprroved. @96LawDawg is "Tutorials Follow" a good title?

Yes, I think so.  Acceptable English way of saying the tutorials are below this line.

**Pull request merged**
