### PR TITLE
return black for invalid color on server

### LINKED ISSUE #1476: undefined color
It's possible that colors are undefined and then this happens:

```
ERROR - GENERIC player Guest123 connected to room example - TypeError: Cannot read properties of undefined (reading 'slice')
    at Room.newPlayerColor (file:///root/virtualtabletop/server/room.mjs:609:30)
    at Room.addPlayer (file:///root/virtualtabletop/server/room.mjs:34:52)
    at file:///root/virtualtabletop/server.mjs:321:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### PR DESCRIPTION
**Pull request by robartsd**
fixes #1476

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1502/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1502-pr-test`.

**Comment by 96LawDawg** [comment]
I have no idea how to test this by creating an undefined color on the server.  But the code looks right.

**Comment by ArnoldSmith86** [comment]
I replaced `server.mjs` by this:

```Javascript
import { toHex } from './client/js/color.js';

console.log(toHex(undefined));
```

Leads to this:

```
file:///mnt/stick/stuff/playingcards.io/Clone/virtualtabletop/client/js/color.js:9
  if (document == undefined) {
  ^

ReferenceError: document is not defined
    at toHex (client/js/color.js:9:3)
    at server.mjs:3:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

Commiting fix...

**Review by ArnoldSmith86 — APPROVED** [review]
Fixed, tested and code-reviewed.

**Review by 96LawDawg — APPROVED** [review]
Approved.  Merging bug fix now.

**Pull request merged**
