### PR TITLE
Stop enlarged from flickering

### PR DESCRIPTION
**Pull request by bjalder26**
- Stops enlarged view from flickering if mouse moves faster than the widget and the mouse moves off of the widget while moving.
- Stops enlarged view from ending if mouse temporarily moves off the screen while a widget is being moved.
- Makes the enlarged view end when mouseleave happens rather than when mouseup happens.  

This addresses issues #31 and #715.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3716/pr-test (or any other room on that server)

**Review by RaphaelAlvez — APPROVED** [review]
Tested and approved.

I had the impression the problem would be in the code and chooses the side for the enlarged version. The flickering only happens on the right side of the board wich is when this code is triggered. Anyway, your code fixes it.

**Review by rogerl50 — CHANGES_REQUESTED** [review]
When I drag a card around and then release the mouse button, the card (unenlarged) under the mouse moves.

**Comment by bjalder26** [comment]
> When I drag a card around and then release the mouse button, the card (unenlarged) under the mouse moves.

I'm having trouble recreating that.  Is the card jumping to a new spot when you release the mouse button?  Also, which browser, and does it always move in the same direction?

**Comment by rogerl50** [comment]
> > When I drag a card around and then release the mouse button, the card (unenlarged) under the mouse moves.
> 
> I'm having trouble recreating that. Is the card jumping to a new spot when you release the mouse button? Also, which browser, and does it always move in the same direction?

Firefox on MacOS. Maybe it's working as intended; I don't know the game. If the drop location is anywhere close to one of the gray circles denoting (I assume) the center of a territory, it jumps so that the upper left corner of the card is on the upper left edge of the circle. But if you drop the card (say) in the center of an ocean, it stays where you dropped it.

**Comment by bjalder26** [comment]
> Firefox on MacOS. Maybe it's working as intended; I don't know the game. If the drop location is anywhere close to one of the gray circles denoting (I assume) the center of a territory, it jumps so that the upper left corner of the card is on the upper left edge of the circle. But if you drop the card (say) in the center of an ocean, it stays where you dropped it.

Oh yeah, those grey spots are all holders.

**Pull request merged**
