### PR TITLE
Fix widget sort ordering in JSON editor tree view

### PR DESCRIPTION
**Pull request by rogerl50**
Modified widget tree display to alphabetize widgets both at the top level and within a parent. This is related to issue #382.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3443/pr-test (or any other room on that server)

**Review by RaphaelAlvez — APPROVED** [review]
Looks way better this way. Code also looks good

**Review by ArnoldSmith86 — APPROVED** [review]
First parentheses aren't necessary but fine.

I'll replace it by z order soonish.

**Comment by RaphaelAlvez** [comment]
> First parentheses aren't necessary but fine.
> 
> I'll replace it by z order soonish.

Why Z? this is way easier to find stuff

**Comment by ArnoldSmith86** [comment]
Oh. Tree view. I thought about the F1 keys.

**Comment by rogerl50** [comment]
> First parentheses aren't necessary but fine.
> 
Thanks. I could have sworn I tried it without and it failed; I must have had another error as well.

**Pull request merged**
