### PR TITLE
enhanced widget duplication in JSON editor

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The duplication command in the JSON editor now triggers a form with several options before executing:

- Recursive: also create clones of the children?
- Increment IDs: instead of creating a new random ID for every new widget, it looks at the old ID and increments the last number it finds (otherwise it appends a number)
- X/Y offset: create the top level clone at offset coordinates
- \# Copies X/Y: create multiple copies at once - forms a grid by using X/Y offset

This also replaces the copy state URL prompt by the new command options form.

It also changes the automation in the composite widgets in the add widget overlay. Their buttons no longer operate on a fixed ID but instead operate on their parent widgets. That makes it possible to use the duplication command on timers, counters and holders with recall buttons without having to manually fix their `clickRoutine`.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3522/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
So is this working for children? (First item on your list)
Can you extend this to the default duplicate?

**Comment by ArnoldSmith86** [comment]
Yeah, gotta shuffle some code around but I think "recursive" and "increment IDs" should just be default for the "normal" duplicate button.

**Review by RaphaelAlvez — APPROVED** [review]
tested

**Comment by ArnoldSmith86** [comment]
I'm a bit hesitant to just merging this because it:

- changed the widgets in the add widgets overlay (fixed deck position, removed duplicate code for empty vs full deck and changed clickRoutines to work with the parent instead of fixed IDs)
- reuses the form generation code from the `INPUT` function and I changed the code for the _checkbox_ value (from `field.value || false` to `!!field.value` - "use the value but if it's false use false" seemed weird to me) and _number_ value (it was `input.value = field.value || 1` before which meant you couldn't set the default value of a number input to `0`)

It would ease my mind if someone could do some tests in that regard.

**Comment by robartsd** [comment]
> * reuses the form generation code from the `INPUT` function and I changed the code for the _checkbox_ value (from `field.value || false` to `!!field.value` - "use the value but if it's false use false" seemed weird to me) and _number_ value (it was `input.value = field.value || 1` before which meant you couldn't set the default value of a number input to `0`)

I agree that `!!value` is a better way to ensure Boolean result. Should we use `imput.value = field.value || 0` instead?

**Comment by ArnoldSmith86** [comment]
> Should we use `imput.value = field.value || 0` instead?

Not sure. It's cleaner and I don't really mind just changing the default but in that case we also would need to change the `min` and I wouldn't want to do that without a fileupdater.

**Comment by robartsd** [comment]
I see no problems with the changes to add widget overlay. Have not tested changes to INPUT.

**Comment by minotalen** [comment]
Hi just dropping in to say this proved very useful! One thing I'd like would be for the input fields to retain their values after duplication, currently they reset.

**Comment by robartsd** [comment]
Love the duplicate widget feature. It was great for copying my compound tangram widgets.

**Review by robartsd — APPROVED** [review]

**Pull request merged**
