### PR TITLE
added favicon

### PR DESCRIPTION
**Pull request by robartsd**
Adds the favicon created based on discussion on the discord server in SVG format with PNG fallback. Will not work for IE <= 8 (requires non-standard `rel="shortcut icon"` or file served at `/favicon.ico`, does not support SVG).

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3527/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
I like the way it looks.  You might want to run it through this website's generator to get all the different types (if you haven't done so already). 
https://realfavicongenerator.net/

**Review by RaphaelAlvez — APPROVED** [review]
Looks good on my phone and ok chrome.

**Review by ArnoldSmith86 — APPROVED** [review]
It doesn't seem to work on my mobile browser (PrivacyBrowser) but other than that I like it.

**Comment by robartsd** [comment]
> It doesn't seem to work on my mobile browser (PrivacyBrowser) but other than that I like it.

I messed up the path for the fallback png. Try again.

**Review by 96LawDawg — APPROVED** [review]
Looks good.  Thanks to you and the others who helped put this together.  We should not forget the original thing that spurred this request, though:  minotalen's request to change the html document title element to something context sensitive in #517.

**Comment by ArnoldSmith86** [comment]
Works now.

**Pull request merged**
