### PR TITLE
Add The Team, Downtown, Bug Chess, Ninety-Nine.  Make other updates.

### PR DESCRIPTION
**Pull request by 96LawDawg**
**_Games:_**

- Add The Team (similar to The Crew Quest for Planet 9) by SeenD and RaphaelAlvez.

- Add Downtown (similar to Chinatown) by casbuild.

- Add Bug Chess (similar to Hive), by RaphaelAlvez.

- Add Ninety-Nine by figamir, who did not want attribution and asked that VTT take authorship credit.

- Update Wordy to move board to left and widen the hand in all 3 language variants.

- Update Spin_5 to add icons on the game pieces to increase accessibility.

**_Tutorials:_**

- Add new Offset: Advanced tutorial as one of the variants in the Holders tutorial.  Prepared by RogerLipsett.

- Fix typo in Tutorials Readme file.

**_Assets:_**

- Add the card deck used in Ninety-Nine (also by figamir who did not want attribution) to the Asset.vtt file.

library.json also updated with additions.

Tested new library.json and vtt files on local machine with no issues.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3102/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
All new VTT files have been preloaded for the approvers in the pr-test room.

**Review by RaphaelAlvez — APPROVED** [review]
Tested and approved. All games working

**Comment by RaphaelAlvez** [comment]
@96LawDawg I guess you forgot to add Diplomacy. I approved it anyway just keep in mind that there is an update pending to the next batch.

**Review by Casbuild — APPROVED** [review]

**Pull request merged**
