### PR TITLE
trigger `idGlobalUpdateRoutine` for any newly added widget

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Whenever a new widget is added to the room, any defined `idGlobalUpdateRoutine` will now be called with the new widget.

Completely untested. As in: I did not even check if the site still loads.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3917/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
This still has problems with `async`/`await` and batching. But the feature might work enough for testing. :smile:

**Comment by bjalder26** [comment]
It appears that it is triggering whenever a change is made in the JSON editor (including selecting a widget), and that the `value` variable is always the `id` of the widget with the idGlobalUpdateRoutine rather than the id of the widget with a changed id.  It also triggers a whole bunch of times.

**Comment by ArnoldSmith86** [comment]
Does this fix things?

**Comment by bjalder26** [comment]
> Does this fix things?

Unfortunately it did not.  Selecting the widget in the JSON editor still triggers the Routine.

image

**Comment by ArnoldSmith86** [comment]
Now? :smile:

**Comment by bjalder26** [comment]
> Now? 😄

Now it works much better.  However, it seems to trigger like 70 times rather than just once.  Maybe an await issue (I really don't know, but will pretend I did if I am right)?

**Comment by ArnoldSmith86** [comment]
Alright. Guess it's time to actually look at what's going on instead of pushing blindly. 😄

**Comment by ArnoldSmith86** [comment]
Hmm, I added logging here and it seems to be called once per new widget:

```Javascript
  if(isNewWidget) {
    console.log('triggering for', widget.id);
    for(const [ w, routine ] of StateManaged.globalUpdateListeners['id'] || [])
      w.evaluateRoutine(routine, { widgetID: widget.id, oldValue: null, value: widget.id }, { widget: [ widgets.get(widget.id) ] });
  }
```

What exactly did you test that triggered 70 times?

**Comment by bjalder26** [comment]
> Hmm, I added logging here and it seems to be called once per new widget:
> 
> ```js
>   if(isNewWidget) {
>     console.log('triggering for', widget.id);
>     for(const [ w, routine ] of StateManaged.globalUpdateListeners['id'] || [])
>       w.evaluateRoutine(routine, { widgetID: widget.id, oldValue: null, value: widget.id }, { widget: [ widgets.get(widget.id) ] });
>   }
> ```
> 
> What exactly did you test that triggered 70 times?

I added an idGlobalUpdateRoutine that incremented a property, and it was incrementing it about 70 times.  Now it is doing it about 15-22 times.  In the pr-test room there is a checker and a label.  If you click on the checker it will clone itself, and the label will track how many times the idGlobalUpdateRoutine was triggered.  Duplicating the checker does the same.

**Comment by ArnoldSmith86** [comment]
I had a look at your pr-test room. If I just open the room and clone a checkers piece, it works fine.

If I edit the label using the JSON editor, it starts to count more than once per widget creation.

I think it's a completely unrelated issue. The problem is that the `idGlobalUpdateRoutine` gets registered multiple times (every time the widget is being updated). That should totally be fixed but should also affect other routines.

**Comment by ArnoldSmith86** [comment]
Oops. Didn't mean to push that commit here. Should have been its own PR. But now it is the way it is.

When editing widgets in the JSON editor, `*GlobalUpdateRoutine`s would be registered again and again for every button press resulting in multiple calls when the event occured.

That should be fixed.

**Review by bjalder26 — APPROVED** [review]
This appears to work well.  I tried triggering other routines to see if they would cause any issues with the new changes, but couldn't find any issues.  Cloning widgets, duplicating widgets, adding widgets through any means, or changing the id all appear to trigger the routine (as expected).  Decks and piles also trigger the routine (also as I would expect, though maybe it should be noted considering not everyone thinks about those widgets).

Approving through testing.

**Pull request merged**
