### PR TITLE
fix crash when `CALL`ing invalid widget

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
It was already checking for a valid widget ID but `isValidID` requires a second parameter now. Probably a merge error at the time this was added.

### CODE REVIEW

**Review by robartsd — APPROVED** [review]

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1162/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
This works fine through testing, but the code also includes some changes to the PCIO importer for timers, I think.  What is that about?

**Comment by robartsd** [comment]
> This works fine through testing, but the code also includes some changes to the PCIO importer for timers, I think. What is that about?

Just changing from double quotes `"` to single quotes `'`. Not sure why that minor style change is associated with this PR, but single quotes is more consistent with the rest of the code.

**Comment by ArnoldSmith86** [comment]
GitHub had another hiccup. It didn't trigger the PR test server script or the automated tests after the first commit so I just changed something to re-trigger it.

**Pull request merged**
