### PR TITLE
Move parent widget if not movable

### LINKED ISSUE #184: widget with movable false should pass drag event to movable parent widget
We have movableInEdit:false to make compound widgets, but compound widgets can be difficult to move in play because non-movalble child widgets capture and prevent the dragging motion.

### PR DESCRIPTION
**Pull request by robartsd**
Adds moveTarget. moveTarget is the mouse target if the widget is movable in current context, Otherwise it is the nearest ancestor widget that is movable. If no movable ancestor is found moveTarget is null. Fixes #184

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3234/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
I've loaded my jumping dice (basic widgets with buttons as children) as a test case in the pr-test room. The button can be clicked. Dragging the button moves the basic widget.

**Comment by 96LawDawg** [comment]
I was trying to test the various conditions under which this would work.  I'm not sure I completely understand it.  It does work with buttons attached as children to basic widgets (and other types such as pin pieces).

**Review by RaphaelAlvez — APPROVED** [review]
Tested and approved. Waiting 24h since post for owner to merge it.

**Pull request merged**
