### PR TITLE
Add new operations to set

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
Adds *, /, random and floor as relations to SET.

SET makes operations for each object in a collection. This is not the same as COMPUTE.

/ divides by "value"

random and floor ignore "value"

Those operation now allow you to create something equivalent to Math.floor(Math.random()*25)+1

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3268/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
@larkob I'll create another issue for more operation. Can you take a look at my second commit? (or @ArnoldSmith86 )

**Comment by rogerl50** [comment]
How is this different from doing the computation using `COMPUTE`, placing the result into a variable, and then `SET`ting using that variable?

**Comment by RaphaelAlvez** [comment]
> How is this different from doing the computation using `COMPUTE`, placing the result into a variable, and then `SET`ting using that variable?

COMPUTE results in a variable and just one. So if you want to operate in multiple widgets you a way to select each one individually, get the value, compute, set and repeat for each widget. Since there is no for each loop this is not possible.
SET on the other hand operates for each widget applying one operation to one property. + and - were already in place.

Me and larkob discussed even expanding to all operation in compute. This PR was just a 5 mins work and it already open doors to some cool stuff. 

see issue #269

**Comment by larkob** [comment]
@RaphaelAlvez I've assigned myself to #269 and as I don't plan to recreate all COMPUTE functions, but to refactor it in a way that these mathematical functions can be used in other operations, it may possibly make this PR obsolete, so it's probably a good idea to wait a bit and see what I can come up with.

**Comment by RaphaelAlvez** [comment]
I don't mind if this PR gets obsolete.

I, in fact used, the strings used in COMPUTE so you don't need to make any kind of version bump.

I believe those functions I added are by far the most important and powerful besides the ones related to strings.
So if you agree with the functions strings i added and things are working then I think this PR still should be accepted.

We never know how long it will take until the next PR.

Btw when I looked ate the code it seemed that:
1) Not all compute functions make sense in set but I'm not against adding all for consistency.

2) It shouldn't be hard or much time consuming to add all functions manually. Probably the only advantage of making it in a smart way would be a clean code.

**Comment by RaphaelAlvez** [comment]
SEE #279

**Pull request closed without merging**
