### PR TITLE
adds css variable to hide pile handle

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
use --pileDisplay: none in the HOLDER css to hide a pile that is inside of it

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3493/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
That's cool.  This might also be an opportunity to further tweak the drag handle, like:

--pileDisplay: big
--pileDisplay: small
--pileDisplay: topleft
--pileDisplay: topright
--pileDisplay: bottomleft
--pileDisplay: bottomright

But that may not be easily possible to tweak.  I don't know.  Just a thought.  And if you wanted to go really crazy, you could allow full customization to include color and shape of the circle and color and style of text.  I know a big pile rewrite is eventually going to happen (maybe???), but there will always be a need to drag multiple cards like this.

**Comment by ArnoldSmith86** [comment]
Honestly, don't worry about the rewrite right now if you want to add features.

The main problem is that those customizations have to be in a widget and the piles themselves get destroyed all the time. Setting the handle style only inside a holder is pretty weird.

IMO that customization belongs into the cards (or `cardDefaults`).

And I already PM'd Raphael this on Discord:

Feels like it should be a real property of the holder, shouldn't it?
I kinda like the CSS route though. I would put a property on the holder that in turn adds a class to it and then make a CSS rule something like `.holder.hiddenPileHandles > .pile > .handle { display: none }`.

**Comment by robartsd** [comment]
> That's cool. This might also be an opportunity to further tweak the drag handle, like:
> 
> --pileDisplay: big
> --pileDisplay: small
> --pileDisplay: topleft
> --pileDisplay: topright
> --pileDisplay: bottomleft
> --pileDisplay: bottomright

We could add a --pileScale variable to adjust the size. Code choosing handle placement would not adjust for the scale. Positioning would be difficult to do using inherited css variables.

Code looks like pile handle will be hidden for piles within the holder, but not for piles within a child holder of the holder (would have to set for each holder separately if you have nested holders).

Overall the project could really use #147 and #154 , this is just a somewhat hacky workaround.

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 
> Feels like it should be a real property of the holder, shouldn't it?
Sure

> I kinda like the CSS route though. I would put a property on the holder that in turn adds a class to it and then make a CSS rule something like `.holder.hiddenPileHandles > .pile > .handle { display: none }`.
This wud be somewhat limiting if we choose to include more properties. one class for each property?

@96LawDawg 
> That's cool. This might also be an opportunity to further tweak the drag handle
yeah more flexibility is always good but it would need to be in other variables. This approach only requires one variable for each css property

**Comment by ArnoldSmith86** [comment]
TBH I would only make it possoble to hide pile handles in a holder with this PR. And like I said, it should be its own property (not just CSS).

We gotta tackle pile customization but IMHO not inside a holder but everywhere. If it's holder specific you can then just use enterRoutine.

Wait. Now that I think about it: you can't get the pile out of the holder without the handle. Why then have it in the first part?

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
See previous comment.

It should instead be a property of the holder that prevents pile creation in the first place.

**Comment by ArnoldSmith86** [comment]
So you don't agree that there shouldn't be a pile in the first place? Or are we having a misunderstanding?

**Comment by RaphaelAlvez** [comment]
> So you don't agree that there shouldn't be a pile in the first place? Or are we having a misunderstanding?

I agree with you, but I know you will prioritize other things before adding this without a pile. This PR is ready and I made it so you can just change the handling of the hidePile property in code without changing any JSON.

**Comment by ArnoldSmith86** [comment]
I see. Should be very easy to add though. Basically just pretend there is `stackoffsetX` but the value is 0.

I can take a look tomorrow at the latest.

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 Don't you think we can merge this PR and then change the pile situation if needed?

**Comment by ArnoldSmith86** [comment]
Please check if #646 does what you wanted to achieve.

**Comment by RaphaelAlvez** [comment]
should be added by #646

**Pull request closed without merging**
