### PR TITLE
Minor fixes to new tree display functionality in JSON editor

### LINKED ISSUE #1260: Button a few pixels too high
After #1257, the new swap_vert button (first row, right) is a couple of pixels too high. Likely a result of using the icon rather than the item from the font file. Didn't notice this until 1257 had already been merged.
Screen Shot 2022-07-11 at 1 52 08 PM

### PR DESCRIPTION
**Pull request by rogerl50**
- [x] Do not redisplay tree within execution of a macro (performance issue).
- [x] Adjust tree pane size when macro is being defined.
- [x] Force display of options for Copy State button if pressed when `mode == 'empty'`.
- [x] Fix #1260

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1262/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
To fix the misaligned button:

```CSS
[id="jeTopButtons"] button {
  vertical-align: top;
}
```

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  The context specific up/down buttons work nicely.  The 2 changes to the macro are good.  In one room with a lot of holders, the changes improved performance by several seconds.

**Review by RaphaelAlvez — APPROVED** [review]
slightly test reviewed but everything looks good

**Pull request merged**
