### PR TITLE
Allow customizing a cursor's active duration.

### PR DESCRIPTION
**Pull request by flackr**
In case a particular game wants to make it easier for players to point to things they may want to increase the cursor active duration so that the cursor stays visible longer before fading away.

The https://test.virtualtabletop.io/PR-1358/pr-test has a test of setting the active duration to 2000 (milliseconds). Note we could parse units to make it accept the same as an animation time (e.g. 2s or 2000ms) but I don't know if this complexity is necessary.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1358/pr-test (or any other room on that server)

After merging, a backup will be available at https://beta.virtualtabletop.io/editor/PR1358-pr-test.

**Comment by robartsd** [comment]
I don't have a problem with this approach, but I will point out that players can always keep their cursor active by moving it just a little bit and game designers already can adjust the transition effects with css.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Needs a code review.

**Review by robartsd — APPROVED** [review]
I was concerned that non numeric delay values might error this out, but setTimeout handles them gracefully.

**Comment by 96LawDawg** [comment]
> Badge in the PR header says that you are a contributor (but I think that is automatic because you have a PR that has already been merged). Perhaps commit permissions need to be manually added by @ArnoldSmith86 (I don't know much about GitHub repository admin).
> 
> In addition to the required tests/approval; we usually let PRs wait for at least a day before merging. I usually don't merge a PR unless @ArnoldSmith86 has weighed in on it in some way regardless of other approvals.

@ArnoldSmith86 ArnoldSmith has to invite people to be a full member (and they have to accept the invite) in order to have "write access" and be able to merge PRs.

I was going to merge this one tomorrow after the 24 hours, but glad you brought the issue up.

**Comment by 96LawDawg** [comment]
One final comment @flackr.  Our workflow generally works as @robartsd said.  We used to have a policy that PRs required 2 approvals.  We even had sections of the code that individuals were responsible for ("code owners", which is still in the code but isn't used).  But that policy became a problem if we needed to revert a change that broke something of if we were in a lull period that didn't see our usual contributors being active.  So we made it so one approval is enough.  However, the practice is to wait until we have 2 reviews:  somebody who did appropriate testing and somebody who did a code review.  And usually we want @ArnoldSmith86's comments as well.

**Comment by robartsd** [comment]
> We don't have an official list of things you can do with the comma hack. It wouldn't hurt to put together a list of variables that could be used. Or maybe just an additional tutorial under CSS for cursors (although there are variables outside of cursors that could be implemented and documented).

Perhaps we need a list of officially supported selectors that use the comma hack. We can warn that using unsupported selectors works, but there is no guarantee that they won't break in the future. The list of official selectors would be mitigated in a file updater if we change the DOM such that the selectors need changing.

**Pull request merged**
