### PR TITLE
JSON editor commands for copying widgets from one state to another

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Tentative remaining to-do list:
- [ ] Investigate last comment
- [ ] Add warning message
- [ ] Retest

I spend most of my time building `The Team II` right now and that game has four variants for different player counts. It is currently a big pain to add new stuff to all of those variants.

With these new commands you can use the multi-selection to select a few widgets, the command `widgets out` then saves those widgets and all their children recursively into an internal array and when you use `widgets in` in another state, it simply drops those widgets in. It does not change anything about the widget states at any point and is not smart about decks. Meaning: if a widget with the same `id` already exists, it will be overridden (probably actually useful for updating widgets); if you copy over a card and the deck does not exist in the target, the widget will be broken.

This PR should be functional and hopefully saves someone some pain but it is not exactly merge worhty:

- The names are terrible.
- The icons are only placeholders.
- You guys will probably find edge cases that should be addressed.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3694/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
I think I'm missing a step.  This is what I have tried.

- Pressing ctrl-j to open JSON editor
- Ctrl-shift-click to select multiple widgets
- Clicking widgets-out
- Pressing ctrl-j to exit JSON editor
- Choosing a new game or variant
- Pressing ctrl-j to open the JSON editor
- Clicking widgets-in

**Comment by ArnoldSmith86** [comment]
Doesn't work? Hmm. I only did one test..

**Comment by bjalder26** [comment]
> Doesn't work? Hmm. I only did one test..

I've now tried it in Edge, and it **works** in Edge.  I think my problem may have been a browser setting, but I haven't figured that out yet.

**Comment by bjalder26** [comment]
I can't think of any perfect icons, but maybe you will like something like one of these.
image

**Comment by bjalder26** [comment]
Brave (thus possibly Chrome as well) blocks the clipboard for unsecure websites (i.e. the test servers).  However, I found a way around that, and got it to work in Brave on the test server.
image

If someone has a problem on the production server with chrome or brave then they probably need to go to:
chrome://settings/content/all
Click this arrow:
image
Then set clipboard to allow:
image

**Comment by bjalder26** [comment]
The only thing unexpected I could find was with one version of checkers that I must have somehow broken.  I could not 'copy' widgets from that game.  However, when I downloaded and reuploaded the game to another room it fixed the problem.

I have no idea what the issue with that one game was, but I think it is an issue with the game and not the PR. http://212.47.248.129:3694/Interitus

As expected you cannot copy widgets with a parent without copying their parent at the same time.  If you copy 5 widgets and 1 one them has a parent that is not being copied, then the other 4 will be transferred over, but not the 1 with a parent.

It might be nice for an error message to be produced in the JSON editor so that people understand what they did wrong when they try to copy widgets without transferring over their parent as well.

**Pull request closed without merging**
