### PR TITLE
New game Flight, similar to Wingspan

### PR DESCRIPTION
**Pull request by 96LawDawg**
Ready for review and approval.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1497/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1497-pr-test`.

**Review by RaphaelAlvez — APPROVED** [review]
Blind approval

**Comment by ArnoldSmith86** [comment]
You added the solo play, right? The metadata says it's for 2-5 players. It also doesn't have a description (not that my games do...).

**Comment by 96LawDawg** [comment]
> You added the solo play, right? The metadata says it's for 2-5 players. It also doesn't have a description (not that my games do...).

Changed to 1-5 players.  Added description (I forgot it because when I made the game under the old UI, we didn't include it in the metadata).  Good catches.  Thanks.

**Pull request merged**
