### PR TITLE
fixed a few problems with CLONE and DELETE

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
I changed that x/yOffset now "stack". So if you set `count: 10` they are not all on top of each other but each one spaced out with the offset. Technically this is a breaking change but I don't think many people use that combination already.

I tried to make `CLONE` behave as expected for holders, hands, piles, the table, with and without alignChildren. For cards and non-cards. The combinations are endless; please test as many as you can.

`DELETE` pointed out a few flaws with `removeWidgetLocal`. I hope my fixes didn't break anything else but it's all waaay too complicated.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3286/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
I haven't tested extensively yet, but for sure the `DELETE` code needs similar changes.

I tried cloning several cards in the pr-test room; it looks like `xOffset` and `yOffset` are ignored if `alignChildren` is set; is that correct?

Also, what was the code removal in serverstate.js?

**Comment by rogerl50** [comment]
If `xOffset` and `yOffset` are going to stack when `alignChildren` is false, why not use the existing names `stackOffsetX` and `stackOffsetY`? (And, should we include the `dropOffsetX/Y` options as well in that case)?

**Comment by rogerl50** [comment]
I have been trying to implement `DELETE` properly, but I cannot figure out the proper call to actually remove the widgets. The existing `removeWidgetLocal` works unless the widget is in a pile. Someone who knows the code better than I needs to implement this.

**Comment by ArnoldSmith86** [comment]
> Also, what was the code removal in serverstate.js?

That's where I started to look for solutions and I noticed that the variable `parent` isn't used anymore.

**Comment by ArnoldSmith86** [comment]
> I tried cloning several cards in the pr-test room; it looks like `xOffset` and `yOffset` are ignored if `alignChildren` is set; is that correct?

Yes, I think anyone using `CLONE` wouldn't expect it to lead to inconsistent results. So I updated piles and I decided to prioritize `alignChildren` over `x/yOffset`.

**Comment by rogerl50** [comment]
In the test room, using the left-hand holder (which has AlignChildren set), doing a clone and then a delete removes the original card as well.

**Comment by rogerl50** [comment]
Is this ready to be reviewed and merged?

**Comment by ArnoldSmith86** [comment]
I hope so but it needs to be thoroughly tested!

**Comment by ArnoldSmith86** [comment]
Hmm. I found something I didn't expect. I'm building a version of Catan that builds the board by cloning a tile template. Looks like this:

```
    {
      "func": "SELECT",
      "property": "id",
      "value": "Card Template"
    },
    {
      "func": "CLONE",
      "source": "DEFAULT"
    },
    {
      "func": "SET",
      "property": "cardType",
      "applyVariables": [
        {
          "parameter": "value",
          "property": "paramType"
        }
      ]
    },
    {
      "func": "SET",
      "property": "x",
      "applyVariables": [
        {
          "parameter": "value",
          "property": "paramX"
        }
      ]
    },
    {
      "func": "SET",
      "property": "y",
      "applyVariables": [
        {
          "parameter": "value",
          "property": "paramY"
        }
      ]
    }
```

This PR changes the behavior because the clone immediately forms a pile with the template and then the `x` and `y` changes are not taking it out of the pile.

It's really hard to judge what the behavior of `CLONE` should be. In general it feels correct, that the clones form piles. Setting `x`/`y` of a card in a pile should probably remove it from a pile. But then again that will happen anyway with the pile rewrite.

**Comment by robartsd** [comment]
> Setting `x`/`y` of a card in a pile should probably remove it from a pile. But then again that will happen anyway with the pile rewrite.

Currently Rummy Tiles is taking advantage of the fact that setting the `x`/`y` does not remove a card from a pile. I was unable to create the desired effect of a random pile of tiles without allocating more space than I wanted to or having many small piles form until I realized I could leave the tiles in a pile in an off screen holder and position the tiles on screen by setting `x` and `y`. The only visible side effect is that when the second to last card leaves the draw area, the pile is destroyed. This triggers the `onLeave` property change which removes the random rotation before the card is returned to the holder.

Proper control over piling would be better, but changes to this behavior before actually fixing piles could be problematic.

**Review by rogerl50 — APPROVED** [review]
Approved based on testing. I did not carefully review the code.

**Comment by rogerl50** [comment]
I modified my poker room to use Clone/Delete to distribute chips; it seems to work fine. I've tried various combinations of betting, dealing, and resetting the table (which [now] deletes all the clones). You can play with it at http://212.47.248.129:3286/pokertest. Note that only the upper left player and the one below it have been modified to use the new setup; buying chips for the other players will likely break things.

**Comment by rogerl50** [comment]
Multiple cards cloned out of a deck with the new parent set to null do not form a pile. See the pr-test room.

**Comment by rogerl50** [comment]
The pr-test room shows a couple of bugs with CLONE/DELETE.

First, if no x/y coordinates are specified in the `properties` property, and the cards are not being moved into a holder, they do not form a pile. I'm pretty sure that's because in `button.js`, `newX` and `newY` are NaN, and that screws things up down the line. If they are undefined, they should be set to null.

Second, it appears that twice the required number of cards are being cloned. The first three buttons in that room show this problem, so it doesn't matter if they are being cloned into a holder or not. vtt file attached as well.
[clonetest.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/6217882/clonetest.zip)

**Comment by rogerl50** [comment]
I modified the computation of `newX` and `newY` in the `CLONE` code since if `x` and `y` were unspecified in `properties`, those two values were `NaN`, which caused issues downstream.

**Comment by ArnoldSmith86** [comment]
That code assumes that default for x and y is 0. That's not the case for all widgets. It should use p('x') instead and only set x and y in the clone if the offsets are not zero.

**Comment by rogerl50** [comment]
> That code assumes that default for x and y is 0. That's not the case for all widgets. It should use p('x') instead and only set x and y in the clone if the offsets are not zero.

Sorry, don't quite understand. This x and y are the ones specified in the `properties` attribute of the `CLONE` command. What other default values should they have? (These are different from xOffset and yOffset). Also, since this is happening prior to the `addWidgetLocal` call, p('x') will fail, won't it?

**Review by RaphaelAlvez — CHANGES_REQUESTED** [review]
you can test the room http://212.47.248.129:3286/hand

after closing the zoomed hand you get an error when moving a card
image

if this is not related go ahead an close the PR

**Review by RaphaelAlvez — APPROVED** [review]
checked and my problems are not related to this PR

**Comment by rogerl50** [comment]
Take a look at the pr-test room. If the target holder has alignChildren set to false but the source holder has more than one card (so has a pile), the pile is cloned into the target, which then has multiple copies of the pile. I guess I would expect multiple single cards, like you get if there is no pile in the source, but I'm not certain...

**Comment by ArnoldSmith86** [comment]
> Take a look at the pr-test room. If the target holder has alignChildren set to false but the source holder has more than one card (so has a pile), the pile is cloned into the target, which then has multiple copies of the pile. I guess I would expect multiple single cards, like you get if there is no pile in the source, but I'm not certain...

Works as I would expect. It doesn't clone the pile. It clones every single card in the pile but because the clones end up in the same location, they form piles again (just like if you would put them there manually).

**Review by rogerl50 — APPROVED** [review]

**Pull request merged**
