### PR TITLE
fix debug representation of `return`ed collection for `CALL`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The fix was already in the code but the variable just was not used.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4058/pr-test (or any other room on that server)

**Review by bjalder26 — APPROVED** [review]
Looks fixed (same room as from the issue).
image

**Review by 96LawDawg — APPROVED** [review]
Concur.  Approved through test.

**Review by rogerl50 — APPROVED** [review]
An embarrassing error on my part. Approved.

**Comment by bjalder26** [comment]
> An embarrassing error on my part. Approved.

Alternatively, a tiny error in something awesome that took forever to discover, didn't affect game play, and was fixed quickly.

**Pull request merged**
