### PR TITLE
autosave rooms once per minute

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Issue #157 shows that server crashes can happen that don't trigger the error handler that takes care of saving rooms to the filesystem.

While the goal is obviously that the server never crashes, this PR adds a failsafe that saves any active rooms once per minute.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3161/pr-test (or any other room on that server)

**Review by robartsd — APPROVED** [review]
I don't have a way to test this functionality, but I don't see anything I'm worried about in the code.

**Review by rogerl50 — COMMENTED** [review]
The code looks fine as far as I can see. Just so I'm clear: if the server crashes, and you refresh the room state, you will get the most recent backup, right?

**Comment by ArnoldSmith86** [comment]
> The code looks fine as far as I can see. Just so I'm clear: if the server crashes, and you refresh the room state, you will get the most recent backup, right?

Yes. But these aren't backups. When a room is unloaded (last player closes the tab), its state gets saved into the save directory and when it is loaded again (a player opens the URL), its state is read from that file.

This PR only adds a periodic function that **in addition** writes the state to that same file once per minute.

**Pull request merged**
