### PR TITLE
Update library images for multiple games by LawDawg

### PR DESCRIPTION
**Pull request by 96LawDawg**
The ONLY changes are to the library images (all generated by Midjourney) and the attribution reflecting that. No changes to game code.  Hint: you don't need to test anything. But, if you have strong negative feelings about the library image, chime in. Otherwise, just approve.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1777/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1777-pr-test`.

**Comment by 96LawDawg** [comment]
All the games I changed are starred in the test room so they appear together at the top.

**Comment by RaphaelAlvez** [comment]
before
image

after
image

**Review by RaphaelAlvez — APPROVED** [review]
looks good to me.

**Comment by ArnoldSmith86** [comment]
We should probably leave the update timestamp alone, right? I can automate that..

**Comment by 96LawDawg** [comment]
> We should probably leave the update timestamp alone, right? I can automate that..

Sure, but I don't think it really matters.  Either way.

**Comment by 96LawDawg** [comment]
@ArnoldSmith86, is the date/time stamp worth holding off on merging this for you? Like I said, doesn't matter to me.

**Comment by RaphaelAlvez** [comment]
I just want to point out that for some games, although the images look way nicer, we are using images that make the original game less obvious. Reward, capture the flag,  going nuts and tutti Frutti are some examples.

**Comment by 96LawDawg** [comment]
> I just want to point out that for some games, although the images look way nicer, we are using images that make the original game less obvious. Reward, capture the flag, going nuts and tutti Frutti are some examples.

I agree.  But I think it is worth it to have the better library images.  Also in a couple of cases, the library images no longer directly match the clipart/icons that are in the actual game.  For example, in Agra and Alpaca, the library images were the same as the card back icons.  Eventually, I may update that as well, but that is more work.  I still think it is worth the changes.

**Comment by RaphaelAlvez** [comment]
>  I still think it is worth the changes.

Me too. I just wanted to point it out

**Comment by 96LawDawg** [comment]
Oops by Raphael.

**Pull request merged**
