### PR TITLE
Convert coordinates recursively

### PR DESCRIPTION
**Pull request by robartsd**

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3882/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
image
I put two checkerPieces in two 2x scaled holders (at 400,400) and compared the _absoluteX and _absoluteY values.

The one on the production server calculates the absolute locations by taking the holder's x and y, then adding the offset from the holder.  Thus when scaled it does not give the actual location on the screen.
400+4 = 404

In this PR it is corrected to the actual absolute x and y.

400 - 50 (because the holder is 100px in width normally) + 8 (because the holder has a 4 pixel offset normally) = 358

So it appears this works as planned.

**Comment by robartsd** [comment]
> image I put two checkerPieces in two 2x scaled holders (at 400,400) and compared the _absoluteX and _absoluteY values.
> 
> The one on the production server calculates the absolute locations by taking the holder's x and y, then adding the offset from the holder. Thus when scaled it does not give the actual location on the screen. 400+4 = 404
> 
> In this PR it is corrected to the actual absolute x and y.
> 
> 400 - 50 (because the holder is 100px in width normally) + 8 (because the holder has a 4 pixel offset normally) = 358
> 
> So it appears this works as planned.

404 is actually the correct value here. I failed to account for recursive scaling.

**Comment by robartsd** [comment]
> > image I put two checkerPieces in two 2x scaled holders (at 400,400) and compared the _absoluteX and _absoluteY values.
> > The one on the production server calculates the absolute locations by taking the holder's x and y, then adding the offset from the holder. Thus when scaled it does not give the actual location on the screen. 400+4 = 404
> > In this PR it is corrected to the actual absolute x and y.
> > 400 - 50 (because the holder is 100px in width normally) + 8 (because the holder has a 4 pixel offset normally) = 358
> > So it appears this works as planned.
> 
> 404 is actually the correct value here. I failed to account for scaling correctly.



> > image I put two checkerPieces in two 2x scaled holders (at 400,400) and compared the _absoluteX and _absoluteY values.
> > The one on the production server calculates the absolute locations by taking the holder's x and y, then adding the offset from the holder. Thus when scaled it does not give the actual location on the screen. 400+4 = 404
> > In this PR it is corrected to the actual absolute x and y.
> > 400 - 50 (because the holder is 100px in width normally) + 8 (because the holder has a 4 pixel offset normally) = 358
> > So it appears this works as planned.
> 
> 404 is actually the correct value here. I failed to account for scaling correctly: the width and height need to be multiplied by the scale.

**Comment by robartsd** [comment]
> > image I put two checkerPieces in two 2x scaled holders (at 400,400) and compared the _absoluteX and _absoluteY values.
> > The one on the production server calculates the absolute locations by taking the holder's x and y, then adding the offset from the holder. Thus when scaled it does not give the actual location on the screen. 400+4 = 404
> > In this PR it is corrected to the actual absolute x and y.
> > 400 - 50 (because the holder is 100px in width normally) + 8 (because the holder has a 4 pixel offset normally) = 358
> > So it appears this works as planned.
> 
> 404 is actually the correct value here. I failed to account for scaling correctly - the width and height of the holder should have been multiplied by the scale.

Actually, you're right it is working. I forgot that the top left of the holder is actually at 350,350 after scaling. Holder before scaling is at 400,400 (centered at 450,450). The 200x200 holder centered at 450,450 puts the holder's local origin at 350,350.

**Comment by robartsd** [comment]
Rotation conversion not yet working properly.

**Comment by robartsd** [comment]
> Rotation conversion not yet working properly.
> 
> I think didn't account for the coordinate system correctly in the rotation: positive y values in the math functions are UP, but in CSS are down.

Nope, just used the wrong syntax for exponents when calculating the polar coordinates from the center of the widget.

**Comment by robartsd** [comment]
> Rotation conversion not yet working properly.
> 
> I think didn't account for the coordinate system correctly in the rotation: positive y values in the math functions are UP, but in CSS are down.

That and I used the wrong syntax for exponents in the distance calculation.

**Comment by robartsd** [comment]
Looks like the FromCoordLocal functions are working correctly. Now I need to devise a way to test the conversion back.

**Comment by robartsd** [comment]
Now when you drag a widget, the cursor should be anchored to the point on the widget you started the drag from regardless of scale and rotation of the holder that previously contained the widget. Adjusting for dropping into scaled/rotated holder not yet implemented.

**Comment by robartsd** [comment]
To fix #877, I am planning to add adjustments to the widget position in `moveEnd()` to correct for any shifts needed when dropping the widget required by rotation and or scale applied by `hoverTarget` or its ancestors. I'll also be changing `onChildAlign()` to make adjustments. `onChildAlign()` will adjust so that the coordGlobal origin of the widget does not change; `moveEnd()` will adjust the origin so that the point under the cursor when the user drops the widget (assuming the widget's own scale and rotation are the same as they were when the move started) will end up in the same location after `onChildAlign()`.

**Comment by ArnoldSmith86** [comment]
Sounds good. One thing I noticed when I was trying to address the issue was that it felt better if the widget kept its initial scale and rotation when starting a move (instead of resetting to the default) but I'm not sure if that's easy to incorporate. I think it was kinda easy in my approach because it wasn't recursive.

**Comment by robartsd** [comment]
Moved to #903

**Pull request closed without merging**
