### PR TITLE
fixed external properties `cardDefaults` and `cardType`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
There were problems when editing `cardDefaults` and `cardTypes` of a deck from inside a card (the red properties). This PR hides those properties if they were inherited from another deck and also fixes long-standing issues that would not save changes you made there.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3920/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
I tried to edit cardDefaults and cardType without any problems.  I also tried to `get` properties from cardDefaults and cardTypes from a card that with a deck that was inheriting cardDefault and cardType from another deck.  The changes appear to be applied, so as far as I can tell everything is working.

**Comment by bjalder26** [comment]
The one thing I could find (which could be part of another PR) is that if you change a cardType (the actual cardType, not one of the properties) in a deck, and another deck is inheriting cardTypes, then in the first deck the cardType will update on the cards, but in the inheriting deck they will not, and those cards will disappear when the browser is refreshed.  The reason being that the cardType in the card no longer exists in the inherited cardTypes.

**Comment by ArnoldSmith86** [comment]
> The one thing I could find (which could be part of another PR) is that if you change a cardType (the actual cardType, not one of the properties) in a deck, and another deck is inheriting cardTypes, then in the first deck the cardType will update on the cards, but in the inheriting deck they will not, and those cards will disappear when the browser is refreshed. The reason being that the cardType in the card no longer exists in the inherited cardTypes.

That should be an unrelated issue though (also happens in production, right?). I'm also not sure if I want to fix that. Should be reported as an issue though.

**Comment by bjalder26** [comment]
> That should be an unrelated issue though (also happens in production, right?). I'm also not sure if I want to fix that. Should be reported as an issue though.

Yes, it is the same as production.  I'm not 100% sure it should be fixed either.  I would think it is an issue for gamemaking, not so much gameplay.  I opened an issue, so people can have their say.

**Review by bjalder26 — APPROVED** [review]
Fixes known issues.  Approving through testing.

**Pull request merged**
