### PR TITLE
Update Blue

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
- adds patterns to tiles
- adds toggle buttons to should patterns on board
- added seats
- seats request player name if user is a guest
- deal buttons now check for seated players
- removed some (not all) of the UUID ids

### CODE REVIEW

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 I can't find the metadata in the JSON

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1494/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1494-pr-test`.

**Comment by 96LawDawg** [comment]
You need to update the attribution to add you.  I would say: "Artwork and initial game layout released as CC BY-NC by https://www.reddit.com/user/jaojins/.

Layout adapted for VTT by ArnoldSmith86, RaphaelAlves, LawDawg and jade-alarm, also CC BY-NC."

Everything else looks good.

**Comment by RaphaelAlvez** [comment]
> You need to update the attribution to add you. I would say: "Artwork and initial game layout released as CC BY-NC by https://www.reddit.com/user/jaojins/.
> 
> Layout adapted for VTT by ArnoldSmith86, RaphaelAlves, LawDawg and jade-alarm, also CC BY-NC."
> 
> Everything else looks good.

@96LawDawg done

**Review by 96LawDawg — APPROVED** [review]
Approved through test and JSON review.

**Pull request merged**
