### PR TITLE
added mode to ROTATE (fixes #66)

### LINKED ISSUE #66: ROTATE should allow to set wigets to specific rotation
ROTATE should have a mode with "set" or "add" (defaults to "add" for backwards compatibility)

Example for setting the rotation of widgets within holder to 90 degrees (irrespective of their current rotation):
```
{
    func: “ROTATE”,
    holder: "<holderId>",
    angle: 90,
    mode: "set"
}
```

Reason: Currently, ROTATE only allow to change the current rotation by adding a value. It would be even more useful if ROTATE could also set the rotation of widgets to a particular value, for instance to align cards that may have been various individual rotation property values.

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
ROTATE can now be set to add to (default) or set the rotation of a widget.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3074/pr-test (or any other room on that server)

**Review by UltimateGeek — APPROVED** [review]
code changes look good.

**Review by robartsd — APPROVED** [review]
Code looks good. Tested with Dominoes.

**Review by RaphaelAlvez — APPROVED** [review]
approved by test and code review

**Pull request merged**
