### PR TITLE
adds cursors

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
I'm making a new PR because:
- classes are useful in many ways
- the PR adds assets and not really any new feature

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1556/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1556-pr-test`.

**Review by 96LawDawg — APPROVED** [review]
Remove the unnecessary ones we discussed at the meeting and this is good to go.

**Comment by ArnoldSmith86** [comment]
How do you define the "cursor pixel" in the SVG? Because the paintbrush paints more to the right than expected.

**Comment by RaphaelAlvez** [comment]
> How do you define the "cursor pixel" in the SVG? Because the paintbrush paints more to the right than expected.

It is not defined. Maybe I need to enforce a value.

For other widgets I did set them and they look like this in the css
`url('/i/cursors/grabbing.svg') 9 3, auto`

Also keep in mind that this is a assets PR but I can update the tutorial

**Comment by ArnoldSmith86** [comment]
Ah, I see. If they are not defined in the asset, it's fine.

**Pull request merged**
