### PR TITLE
Fix star number location

### LINKED ISSUE #2355: The number of stars in starred games is out of position
For example, see this image.  The number 15 should be near the star.

Screenshot 2024-11-02 110650

### PR DESCRIPTION
**Pull request by 96LawDawg**
Fixes #2355

---

PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2359/pr-test (or any other room on that server)

### CODE REVIEW

**Comment by 96LawDawg** [comment]
Interestingly, this also fixes another thing that had been happening.  I thought it was just me.  But the behavior now changes.  Currently on production, if you click on the name of a game, it expands to fill the whole screen.  Like this:

Production

But previously, it opened the game in a side panel.  Not sure when that changed, but this tiny css change seems to fix that problem.  Like this:

PR

**Comment by ArnoldSmith86** [comment]
I would guess that you zoomed in on the production server (maybe by accident). The screenshots show the menu on the left in different sizes.

**Comment by 96LawDawg** [comment]
Oh.  Well.  Yes.  The zoom level on my browser had gotten to 110% instead of 100.  Thanks for that tip!

**Review by bjalder26 — APPROVED** [review]
I tried sizing the screen a bunch of different sizes, and zooming in and out, and it acted as expected.  This seems like it could only be an improvement.

**Pull request merged**
