### PR TITLE
Fix editing label does not update JSON editor

### PR DESCRIPTION
**Pull request by bjalder26**
I believe this will fix issue #662 "Typing in a label doesn't update text in the JSON editor".

- Typing in label updates the JSON editor again

- Timer stops immediately in JSON editor as soon as any character is pressed - same as production server

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3683/pr-test (or any other room on that server)

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
The `height: inherit` seems very unrelated.

The other change should cause a regression. I think it should be visible when editing a fast changing timer.

The `jeKeyIsDown` gives me an idea though: that variable should only be set in the event handlers if `#jeText` currently has the focus. Is that the case? If not, does it fix the issue?

**Comment by bjalder26** [comment]
> The `height: inherit` seems very unrelated.

I think that should fix the issue described in #607.  I don't understand the entire twoRowBottomAlign debate, but I assume that the textarea shouldn't extend past the label widget area.  The only relation is that they both affect labels.

> The other change should cause a regression. I think it should be visible when editing a fast changing timer.

You're right, the faster it goes, the more likely it is for the cursor to jump back to the beginning.  I didn't notice that earlier testing at 1000 ms. 

> The `jeKeyIsDown` gives me an idea though: that variable should only be set in the event handlers if `#jeText` currently has the focus. Is that the case? If not, does it fix the issue?

You lost me a little there.  I made a change.  It seems to fix that issue.  Maybe it is what you meant, or maybe you have a better idea.

**Comment by bjalder26** [comment]
One thing I noticed with this PR is that with a textGlobalUpdateRoutine, if you set it to capture text and write it to a text property again, then it will update in-real-time in the JSON editor (which it won't on the production server right now).  However, if you set it to capture text, then write it to a different property (e.g. textxxx), then it will not update in the JSON editor in-real-time.  However, it does still capture the text and write it to the property on both servers.

Other properties appear to update in the JSON editor in-real-time using that method on both servers.

**Comment by bjalder26** [comment]
> The `height: inherit` seems very unrelated.
> 
> The other change should cause a regression. I think it should be visible when editing a fast changing timer.
> 
> The `jeKeyIsDown` gives me an idea though: that variable should only be set in the event handlers if `#jeText` currently has the focus. Is that the case? If not, does it fix the issue?

I couldn't figure out the method you were suggesting.  However, now it appears to work exactly like on the production server except typing in labels updates the JSON editor again.  Are there still or other changes you are requesting?

**Comment by 96LawDawg** [comment]
I tested the fix to #723 and it works.  I have not tested the other aspects of this PR yet.

**Comment by RaphaelAlvez** [comment]
Tested almost everything in your test room but I don't really understand what is the first image. It really feels like something that would be a breaking change and if so maybe you could move it to another PR to make this one free to merge

**Comment by bjalder26** [comment]
> Tested almost everything in your test room but I don't really understand what is the first image. It really feels like something that would be a breaking change and if so maybe you could move it to another PR to make this one free to merge

I've been thinking about breaking this up, I've just been so busy lately.  What that is though is just setting the textarea to inherit its height from the label widget (div) `height: inherit;`.  Right now the textarea will extend beyond the size of the label widget (I think based on the line height).  So what you're seeing in that image is the selection area for the textarea extending beyond the widget border on the production server in the first image, then not doing so in this PR in the second image. 

I can break this up, but I probably won't get around to it until this weekend (I'm not at home now).

**Comment by bjalder26** [comment]
The JSON editor works differently now.  This no longer addresses the current issue.

**Pull request closed without merging**
