### PR TITLE
Enter in label no longer registered in JSON editor

### PR DESCRIPTION
**Pull request by bjalder26**
This is a fix for #660.  It moves the event listener for enter from being applied to the entire window to only being applied to the JSON editor.

Added in fix for #659.  Apparently, the white space (enter) didn't register as different enough to be evaluated as different by !=.

I do believe these two very minor fixes are both working as expected.  I also suspect these are desired changes.  However, this needs a code review to make sure I put the eventListener in the right place, and to make sure the getElementById is required <s>(which I believe it is in this case)</s>.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3661/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
image

Weird.

**Review by ArnoldSmith86 — APPROVED** [review]
Code looks good and seems to fix the issues.

**Comment by bjalder26** [comment]
> Code looks good and seems to fix the issues.

Thanks for fixing the getElementById.  I thought that MIGHT be the wrong way to do it.  Also, my guess is that the \n is added AFTER the evaluation takes place, so it 'sees' 8(whitespace) != 8 and evaluates that as false.  However, that is just a guess.

**Comment by ArnoldSmith86** [comment]
I looked in the debugger. The label has `8` as `text` because `setText` converts numeric strings to numbers. When you then press enter, the highlighted code checks `"8\n" != 8` which is actually `false`.

**Comment by bjalder26** [comment]
> I looked in the debugger. The label has `8` as `text` because `setText` converts numeric strings to numbers. When you then press enter, the highlighted code checks `"8\n" != 8` which is actually `false`.

In that case, I have no idea why it wasn't triggering the textChangeRoutine before, and why it appears to be doing so now.

**Comment by ArnoldSmith86** [comment]
You probably read that the wrong way. `"8\n" != 8` is `false` - so `"8\n" == 8` is `true`.

**Comment by bjalder26** [comment]
> You probably read that the wrong way. `"8\n" != 8` is `false` - so `"8\n" == 8` is `true`.

Yep, that's what I did.  So then it does make sense.

**Pull request merged**
