### PR TITLE
fixed pile alignment after RECALL

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The fix of onEnter/onLeave broke the alignement of cards inside piles. This happens pretty much every time a reset button is pressed.

I only did very basic tests where the problem seems to be fixed. Please test some more stuff in tutorials and games.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3092/pr-test (or any other room on that server)

**Review by ThePropagandaPanda — APPROVED** [review]

**Review by rogerl50 — APPROVED** [review]
Didn't review the code, but it fixed the problem I was seeing in my room.

**Comment by Casbuild** [comment]
It is not fixed for any room I try.

**Comment by Casbuild** [comment]
Works now!

**Pull request merged**
