### PR TITLE
Added loop to ensure unique new widget id

### LINKED ISSUE #289: New random ID is not checked to see if ID is already in use
In meeting today we mentioned that the ID generator does not check for for existing use of the ID which could potentially cause collisions.

### PR DESCRIPTION
**Pull request by rogerl50**
Fixes #289

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3299/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
I was thinking about trying to write something just like this, but hadn't been able to confirm that the locally created widget was not in `widgets` yet as I wasn't sure where it gets added. Did this not work?

**Comment by rogerl50** [comment]
> I was thinking about trying to write something just like this, but hadn't been able to confirm that the locally created widget was not in `widgets` yet as I wasn't sure where it gets added. Did this not work?

I withdrew it because it wasn't complete. There are two other places where a unique ID is created: in the JSON editor, and in the state overlay (the chess pieces). I'm not sure yet how either one works, so I withdrew the pull request. If you think it's worthwhile merging just this piece, I'm fine with it.

I tested it by manually changing the generated ID to one that was already in existence, using the FF debugger. Seemed to work just fine.

**Comment by robartsd** [comment]
> > I was thinking about trying to write something just like this, but hadn't been able to confirm that the locally created widget was not in `widgets` yet as I wasn't sure where it gets added. Did this not work?
> 
> I withdrew it because it wasn't complete. There are two other places where a unique ID is created: in the JSON editor, and in the state overlay (the chess pieces). I'm not sure yet how either one works, so I withdrew the pull request. If you think it's worthwhile merging just this piece, I'm fine with it.

I'm not familiar with these other places in the code. Are these also creating new widgets? A collision with another widget's ID here would cause the old widget to be replaced with the new widget, which could be devastating to the room. I am concerned about using a random ID anywhere that it could overwrite something else unless we first check that it is not in use. I'm also slightly concerned about the possibility of a collision dropping users into a random room that is already occupied.

I'm very concerned about a collision in shuffling; it just means that sometimes the relative position of a few cards is determined by something other than the results from the pseudo random number generator. I'm actually pretty certain that collisions in shuffling happen regularly and no one notices. About one in every eight shuffles of a standard deck of 52 cards should result in two cards with the same z-index; for a deck of 118 cards this would happen for about half of all shuffles.

**Comment by rogerl50** [comment]
I'll be posting a pull request in the AM to fix a number of these places, and I'll give a list of all places where a call to random for a purpose like this occurs, together with my belief about whether it's important or not.

For the specific case of shuffling, I actually don't think it matters either; JS has an algorithm for deciding which appears on top in the case of equal z-values.

**Pull request closed without merging**
