### PR TITLE
fixed typo in Expeditions rules

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
it's => its

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1911/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1911-pr-test`.

**Comment by 96LawDawg** [comment]
I've read it several times.  I don't see the change.  There are studies that show when reading English, our eyes skip over little words like "it."  What paragraph was it in?

**Review by 96LawDawg — APPROVED** [review]
But also have an approval because this does not really matter.

**Comment by ArnoldSmith86** [comment]
image

"and its 12 matching cards"

**Comment by 96LawDawg** [comment]
I seriously read that 4 times.  Stupid brain.

**Pull request merged**
