### PR TITLE
Editor QoL improvements

### PR DESCRIPTION
**Pull request by mousewax**
Changes `<script type="text/template">` to `<template type="text/template">` and makes the `CS`, `JS`, and `CONFIG` replaces look like comments in their elements.

This change stops the replaces from being reported as errors as well as allows proper code folding of templates in some editors including Nova on macOS and Visual Studio on Windows.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4004/pr-test (or any other room on that server)

**Review by robartsd — APPROVED** [review]

**Comment by rogerl50** [comment]
For those of us who have no idea what this is about...will it affect us in any way?

**Comment by RaphaelAlvez** [comment]
> For those of us who have no idea what this is about...will it affect us in any way?

That is just so our editors stop pop error messages for some parts of code. Helps to focus in real mistakes

**Comment by robartsd** [comment]
> For those of us who have no idea what this is about...will it affect us in any way?

No, this is just changing some of the syntax used by the tools that build the site. Code editors that don't understand what is going on are incorrectly flagging these as problems. The end result should be the same. ArnoldSmith86 did ask a question somewhere on discord about how `<template>` might be handled by different browsers.

**Pull request merged**
