### PR TITLE
PCIO import improvements

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The PCIO file [sushi.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/10804993/sushi.zip) had a few problems when importing in VTT:

1. It used spread holders. I added basic support and also added support for freeform holders.
2. The holders only allowed dropping cards of a single deck into them _but_ they were not the deck that was in them. In PCIO you can not drop the cards back into the holders but automation interacts with them just fine. I added the deck to the allowed dropTargets now. This makes the automation work in VTT but also allows dropping the cards. Staying closer to PCIO behavior would make this a lot more complicated.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1647/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1647-pr-test`.

**Comment by robartsd** [comment]
> The PCIO file [sushi.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/10804993/sushi.zip) had a few problems when importing in VTT:
> 
> 1. It used spread holders. I added basic support and also added support for freeform holders.
> 2. The holders only allowed dropping cards of a single deck into them _but_ they were not the deck that was in them. In PCIO you can not drop the cards back into the holders but automation interacts with them just fine. I added the deck to the allowed dropTargets now. This makes the automation work in VTT but also allows dropping the cards. Staying closer to PCIO behavior would make this a lot more complicated.

Can't we just set dropLimit to 0 to get similar behavior? IIRC routines aren't subject to dropLimit, but do benefit from dropTarget indicating the child widgets that count as being in the holder.

**Comment by ArnoldSmith86** [comment]
> > The PCIO file [sushi.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/10804993/sushi.zip) had a few problems when importing in VTT:
> > 
> > 1. It used spread holders. I added basic support and also added support for freeform holders.
> > 2. The holders only allowed dropping cards of a single deck into them _but_ they were not the deck that was in them. In PCIO you can not drop the cards back into the holders but automation interacts with them just fine. I added the deck to the allowed dropTargets now. This makes the automation work in VTT but also allows dropping the cards. Staying closer to PCIO behavior would make this a lot more complicated.
> 
> Can't we just set dropLimit to 0 to get similar behavior (would be able to start dragging the card, then change mind and drop it back in, but would not be able to drag from somewhere else and drop back in)? IIRC routines aren't subject to dropLimit, but do benefit from dropTarget indicating the child widgets that count as being in the holder.

It did have a deck set though that was valid to be dropped there.

**Comment by robartsd** [comment]
Oh, I see, some cards should be valid children of the holder for routines, but not for dropping by players while the holder needs to accept other cards dropped by the player. I would probably use an extra holder for this behavior in VTT (accept the card dropped by the player, then use a routine to immediately move it to the holder with dropLimit 0), not sure that PCIO importer should add that though.

**Review by RaphaelAlvez — APPROVED** [review]
code looks good

**Pull request merged**
