### PR TITLE
remove widget stylesheet when removing widget

### LINKED ISSUE #1090: Widget stylesheets are not removed when widget is removed
Widget stylesheets are currently only removed (and replaced if needed) when the widget's css is changed. The widget stylesheet remains if the widget gets deleted (or even if a new state gets loaded). If the stylesheet uses the `,` hack to address other elements, those styles continue to be applied after a new game is loaded (but only for clients that have stayed connected to the room since the widget with the stylesheet was present).

### PR DESCRIPTION
**Pull request by robartsd**
fixes #1090

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:1091/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Review by ArnoldSmith86 — APPROVED** [review]
Oops.

**Comment by robartsd** [comment]
I noticed extra stylesheets remaining when a widget with a stylesheet's id was changed (in JSON editor), but had not realized until this came up in Discord that widget stylesheets remained when switching games. This fix also fixes stylesheets remaining after the widget id is changed (tested both JSON editor and edit mode JSON text).

**Pull request merged**
