### PR TITLE
fixed `IF` and `GET` debug output

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
When providing `operand1` but not a `relation`, `IF` would show `undefined` in the debug output. Now it shows the `relation` it acutally used.

`GET` always showed the variable name instead of its content as its result. Now it shows both.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3889/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
> When providing `operand1` but not a `relation`, `IF` would show `undefined` in the debug output. Roger, was there any reason that you used `original` instead of `a` in the output?

There was, but I'll be damned if I can remember what it was. I have no problem with this change.

> 
> `GET` always showed the variable name instead of its content as its result. Was this done on purpose?

I could make a case for either. It'd probably be best to print something like `<variable> <- <value>`. But I agree that this change is better than the way it is currently.

**Comment by ArnoldSmith86** [comment]
> There was, but I'll be damned if I can remember what it was. I have no problem with this change.

I just looked at a random debug output and at least the `condition` should be from the `original` because otherwise it would just show `"true"` or `"false"` instead of the variable name. For the `operand`s it should maybe show both? The `relation` should be changed though.

**Comment by ArnoldSmith86** [comment]
OK, I reverted the changes to `IF` except for the `relation`. You want to see the variable names instead of their contents. Looks pretty weird otherwise.

**Review by rogerl50 — APPROVED** [review]

**Pull request merged**
