### PR TITLE
Move retrieval of widget type in jeGetContext

### LINKED ISSUE #584: wrong context in JSON editor
Changing `"value1": 1,` to `"value1": 1,,` and then removing the comma changes the JSON editor context to `basic`.

```JSON
{
  "type": "deck",
  "id": "taskDeck",

  "x": 0,
  "y": 0,
  "width": 86,
  "height": 86,

  "movable": true,
  "movableInEdit": true,

  "cardDefaults": {
    "width": 76,
    "height": 120
  },
  "cardTypes": {
    "green6": {
      "difficulty3": 1,
      "difficulty4": 1,
      "difficulty5": 1,
      "text1": "win",
      "value1": 6,
      "css": "--color1:green; --x1:120px; --y1:40px; --scale1:1.5"
    },
    "yellow1": {
      "difficulty3": 1,
      "difficulty4": 1,
      "difficulty5": 1,
      "text1": "win",
      "value1": 1,
      "css": "--color1:yellow; --x1:120px; --y1:40px; --scale1:1.5"
    },
    "firstTrick": {
      "difficulty3": 1,
      "difficulty4": 1,
      "difficulty5": 1,
      "text1": "win the first trick"
    }
  },
  "faceTemplates": [
    {
      "objects": [
        {
          "type": "image",
          "x": 0,
          "y": 0,
          "color": "darkblue",
          "valueType": "dynamic",
          "value": "image",
          "width": 76,
          "height": 120
        },
        {
          "type": "text",
          "x": 0,
          "y": 10,
          "fontSize": 30,
          "valueType": "dynamic",
          "value": "difficulty3",
          "textAlign": "center",
          "width": 76
        },
        {
          "type": "text",
          "x": 0,
          "y": 45,
          "fontSize": 30,
          "valueType": "dynamic",
          "value": "difficulty4",
          "textAlign": "center",
          "width": 76
        },
        {
          "type": "text",
          "x": 0,
          "y": 80,
          "fontSize": 30,
          "valueType": "dynamic",
          "value": "difficulty5",
          "textAlign": "center",
          "width": 76
        }
      ],
      "css": "color: white; font-weight: bold"
    },
    {
      "objects": [
        {
          "type": "image",
          "x": 0,
          "y": 0,
          "color": "lightblue",
          "valueType": "static",
          "value": "",
          "width": 76,
          "height": 120
        },
        {
          "type": "text",
          "x": 0,
          "y": 0,
          "color": "black",
          "valueType": "dynamic",
          "value": "text1",
          "textAlign": "center",
          "width": 76,
          "height": 120
        },
        {
          "type": "text",
          "x": -100,
          "y": 0,
          "fontSize": 50,
          "color": "white",
          "valueType": "dynamic",
          "value": "value1",
          "textAlign": "center",
          "width": 38,
          "height": 60,
          "css": "background-image: linear-gradient(90deg, var(--color1) 1%, var(--color1) 1%); transform: translate(var(--x1), var(--y1)) scale(var(--scale1)); border: 1px solid white; border-radius: 5px"
        }
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by rogerl50**
The widget type, `t`, was being assigned prior to the retrieval of the JSON into jeStateNow. This caused #584, and also (for example) a mismatch between the type in the `type: ...` field and the type shown in the context commands panel (to see this, try editing the type of any widget in production. The type name shown in the context panel is always one character different from what you've typed.).

I've done a small amount of testing here, and it didn't seem to break anything, but this needs more testing and review.

Fixes #584

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1282/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  No way to test everything, but this fixed the described problem and other things in the JSON Editor seemed to work as expected.  But I've learned my lesson.  I won't really know until I start making another game and figure out what else broke.  No ding on you @rogerl50, it's just everything is so complicated now.  (End rant).

**Review by ArnoldSmith86 — APPROVED** [review]
The change looks sensible to me.

It looks to me like the variable is only used in line `let keys = [ t ];`. Maybe just remove the variable completely and move its contents to that line? It's not like the name `t` adds any value.

**Comment by rogerl50** [comment]
> It looks to me like the variable is only used in line `let keys = [ t ];`. Maybe just remove the variable completely and move its contents to that line? It's not like the name `t` adds any value.

`t` is indeed used only there, but I think it needs to exist, since the `catch` for the `try` block sets `jeStateNow` to `null`. (I'm not sure why there is a `try`/`catch` there in the first place, but that's another issue.)

**Comment by rogerl50** [comment]
> But I've learned my lesson. I won't really know until I start making another game and figure out what else broke. No ding on you @rogerl50, it's just everything is so complicated now. (End rant).

I agree. I've learned my lesson on the recent tree modification in the editor. We are just now finding all the edge conditions.

**Comment by ArnoldSmith86** [comment]
The `try/catch` triggers for example if the text is invalid JSON and `JSON.parse` throws an exception.

It shouldn't matter if `jeStateNow === null` though.

**Comment by rogerl50** [comment]
> The `try/catch` triggers for example if the text is invalid JSON and `JSON.parse` throws an exception.
> 
> It shouldn't matter if `jeStateNow === null` though.

Perhaps I'm misunderstanding you. But if i manually set `t` to `null` after changing `button` to `butto`, I get the screenshot below
Screen Shot 2022-08-04 at 11 09 16 AM
:

**Comment by ArnoldSmith86** [comment]
What I meant was to turn this:

```Javascript
  const t = jeStateNow && jeStateNow.type || 'basic';

  // ...

  let keys = [ t ];
```

into this:

```Javascript
  let keys = [ jeStateNow && jeStateNow.type || 'basic' ];
```

Which makes it happen after parsing the JSON.

**Comment by rogerl50** [comment]
> What I meant was to turn this:
> 
> ```js
>   const t = jeStateNow && jeStateNow.type || 'basic';
> 
>   // ...
> 
>   let keys = [ t ];
> ```
> 
> into this:
> 
> ```js
>   let keys = [ jeStateNow && jeStateNow.type || 'basic' ];
> ```
> 
> Which makes it happen after parsing the JSON.

Right, I understood that, but if I force `jeStateNow` to `null` in the debugger before executing that statement, I get the screenshot above. So `jeStateNow==null` does seem to produce undesired results.

**Pull request merged**
