### PR TITLE
PL Safari Scramble: Cover image, license, help text

### PR DESCRIPTION
**Pull request by andypymont**
Updates for public library game Safari Scramble:
- With this PR I waive any copyright and release the game definition/JSON source into the public domain, as per CC0.
- Update the cover image
- Add rules help text to the metadata/game shelf page

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1890/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1890-pr-test`.

**Comment by 96LawDawg** [comment]
More issues with symbols in the instructions:

 "unless there are no animals remaining.If, after a player's turn,"

I get blank spaces before the "If".  Doesn't seem like you intended to put anything there.  Probably just a copy and paste issue.

And this is the smallest nitpicky thing possible.  You say the cards will be "fanned."  To me, fanning indicates spreading them in a hand where they have a curved shaped.  (I actually made a routine that does that in VTT). I guess I would just say "spread" or "stacked," but I don't really care.  I wouldn't have said anything except that you need to fix the graphics glitch.

**Comment by andypymont** [comment]
I've fixed the character issue which was a typo.

The other point raised (re: "fanning") is with respect to the usage instructions, which are not added in this PR, however I've corrected these anyway to say "stacked such that all players can see the values".

**Review by 96LawDawg — APPROVED** [review]
Approved.

**Pull request merged**
