### PR TITLE
New input overlays

### PR DESCRIPTION
**Pull request by mousewax**
All the inputs you used to have and a few more. 
image

- `switch` works just like `checkbox`, but provides a different context.
- If no icon or text is provided for either the confirm or cancel buttons, the old defaults of "Go" and "Cancel" are used.
- The icons use the VTT-Icons class so only those icons are available for now.
- `subtitle`s are available to split things up if needed.
- `title`, `subtitle`, and `text` can be styled with `css`. The default styling is show above.

Input overlay items:
```
{
  "func": "INPUT",
  "fields": [
    {
      "type": "title",
      "text": "Title"
    },
    {
      "type": "text",
      "text": "A simple text block."
    },
    {
      "type": "checkbox",
      "label": "Checkbox",
      "variable": "checkboxInput",
      "value": true
    },
    {
      "type": "color",
      "label": "Color picker",
      "variable": "colorPicker",
      "value": "${playerColor}"
    },
    {
      "type": "subtitle",
      "text": "Subtitles "
    },
    {
      "type": "number",
      "label": "Number Input",
      "variable": "numberInput",
      "value": 10,
      "min": 1,
      "max": 100
    },
    {
      "type": "string",
      "label": "Text Input",
      "variable": "textInput"
    },
    {
      "type": "select",
      "label": "Select box",
      "variable": "selectBox",
      "options": [
        {
          "value": "option1",
          "text": "Option 1"
        },
        {
          "value": "option2",
          "text": "Option 2"
        },
        {
          "value": "option3",
          "text": "As many options as you'd like."
        }
      ]
    },
    {
      "type": "switch",
      "label": "Switch",
      "variable": "switchInput",
      "value": true
    }
  ],
  "confirmButtonText": "Go",
  "cancelButtonText": "Cancel",
  "confirmButtonIcon": "check",
  "cancelButtonIcon": "cancel"
}
```

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3976/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
In the pr-test room, the DEAL button contains a `css` string for the `string` element. The color works but the font size doesn't seem to.

**Comment by mousewax** [comment]
> In the pr-test room, the DEAL button contains a `css` string for the `string` element. The color works but the font size doesn't seem to.

Because there is both a label and an input, I intentionally did not make those styleable. I think when we get the new css styling, that should be easier as we can style `"[space]label"` and `"[space]input`.

**Comment by rogerl50** [comment]
There is also something odd going on with game loading, but I can't yet figure out exactly what it is that works differently. Try some load/remove/load cycles.

**Comment by mousewax** [comment]
> 
All fixed.

image

**Comment by bjalder26** [comment]
I know reward uses an input overlay to recall cards.  Something might be going wrong when it tries to recall the cards.  You might want to check if that recall works by hand, and if so, then maybe it is somehow "missing' the button in the input overlay.

**Comment by mousewax** [comment]
> I know reward uses an input overlay to recall cards. Something might be going wrong when it tries to recall the cards. You might want to check if that recall works by hand, and if so, then maybe it is somehow "missing' the button in the input overlay.

Recalling by hand works fine. But when I load the game, I get this in the console.
image

**Comment by rogerl50** [comment]
I think the issue with Reward is that one of the buttons clicked is `buttonInputGo`, which is the "OK" button in the (old) state overlay. I haven't looked at any of the code to confirm, though.

**Comment by mousewax** [comment]
> 

That is the same button in the new one.

**Comment by rogerl50** [comment]
> > 
> 
> That is the same button in the new one.

Is it related to the fact that the new window is modal?

**Comment by mousewax** [comment]
> 

It's not ACTUALLY a modal. I just labeled it as such as it serves the same functions.

**Comment by bjalder26** [comment]
image

I suspect changing buttonInputGo to buttonInputGo.positiveInput in tests/testCafe/tests.js would fix the issue for Reward.
image

**Comment by mousewax** [comment]
It looks for the ID and then it fails.
```  > 74 |      await t.click(`[id="${b}"]`);```

**Comment by bjalder26** [comment]
> It looks for the ID and then it fails. `` > 74 | await t.click(`[id="${b}"]`); ``

Dang, then it was 'finding' something before, and not finding it with what I suggested.  I am not sure what is going on, though I don't think it is likely a coincidence that it's the two games that use that button.

I suppose these would be my wild guesses.
1) It is 'finding' the wrong button currently.
2) It is 'clicking' on the wrong portion of the button somehow, and that doesn't register in the game.

**Comment by 96LawDawg** [comment]
The fails are not just happening in TestCafe.  There is something wrong with the continue or go or whatever button.  For example, in the test room demo in this pr test room, I added a SET to the "restart" button that is supposed to change the text to all caps when you click the green restart game button.  But that doesn't happen.

**Comment by bjalder26** [comment]
> The fails are not just happening in TestCafe. There is something wrong with the continue or go or whatever button. For example, in the test room demo in this pr test room, I added a SET to the "restart" button that is supposed to change the text to all caps when you click the green restart game button. But that doesn't happen.

It happened when I clicked it.  Is that something you can duplicate?

**Comment by 96LawDawg** [comment]
> > The fails are not just happening in TestCafe. There is something wrong with the continue or go or whatever button. For example, in the test room demo in this pr test room, I added a SET to the "restart" button that is supposed to change the text to all caps when you click the green restart game button. But that doesn't happen.
> 
> It happened when I clicked it. Is that something you can duplicate?

No.  It works for me now.  But the switch output still says 'on' no matter which option is selected.  That was the same issue I had in the original PR for this.

**Comment by mousewax** [comment]
I have updated the code. All of it works. I have no idea why the tests still fail and, at this point, is beyond my abilities to troubleshoot.

There are six buttons here http://212.47.248.129:3976/pr-test 
All of them submit and re-display what they should. The submit and cancel buttons act appropriately. 

Send help.

**Comment by 96LawDawg** [comment]
Proposed new wiki entry (completely replace existing entry with what follows):

This function shows an overlay with input controls so you can ask the user for input and store the responses in variables.

Parameters:

* fields: _array of field definitions_ - specifies what type of input field to display and where to store the returned input
* cancelButtonIcon: _name of VTT-Symbol_ - specifies an icon to be displayed on cancel button (defaults to null).  Must match name of a [VTT-Symbol](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Fonts#vtt-symbols). Can be used with text.
* cancelButtonText:  _text_ - text shown in cancel button (defaults to "Cancel"). Can be used with icon.
* confirmButtonIcon: _name of VTT-Symbol_ - specifies an icon to be displayed on confirm button (defaults to null).  Must match name of a [VTT-Symbol](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Fonts#vtt-symbols). Can be used with text.
* confirmButtonText: _text_ - text shown in cancel button (defaults to "Go"). Can be used with icon.

Field Definition Parameters:
* type: 
  * text: _displays text_ - stores nothing
  * checkbox: _displays a checkbox_ - stores true or false
  * color: _displays a color picker_ - stores a hex color code (e.g. for coloring gaming pieces)
  * number: _displays a number input field_ - stores integer value
  * string: _displays a text input field_ - stores a string
  * select: _displays a dropdown_ - stores a string
  * switch: _displays a slider switch_ - stores off or on
* label: _text_ - to be displayed next to the input field
* value: _various_ the initial value for the input field (for checkbox: true = checked, false = not-checked; defaults to false; for slider: left = off, right = on; defaults to off)
* min: _number_ - the lowest allowed value for a number input field
* max: _number_ - the highest allowed value for a number input field
* options: _array_ - the selectable options for a `select` dropdown:
  * value: _string_ - the value that will be set to the variable when this option was selected by the player
  * text: _string_ - the text that will be shown to the player for this option (the entry in the dropdown) - if omitted the `value` will be displayed instead
* variable: _variable name_ - specifies the variable to store the value/result in

```JS
{
  "func": "INPUT",
  "title": "A title text for the overlay.",
  "fields": [
    {
      "type": "text",
      "text": "Stay a while and listen!"
    },
    {
      "type": "checkbox",
      "label": "Do you want to shuffle?",
      "variable": "shuffle",
      "value": true
    },
    {
      "type": "color",
      "label": "Which color would you like?",
      "variable": "myColor",
      "value": "${playerColor}"
    },
    {
      "type": "number",
      "label": "Which number do you like?",
      "variable": "myNumber",
      "value": 10,
      "min": 1,
      "max": 100
    },
    {
      "type": "string",
      "label": "Credit card?",
      "variable": "myCard",
      "value": "555-2483 63"
    },
    {
      "type": "select",
      "label": "Best Crypto",
      "variable": "crypto",
      "options": [
        {
          "value": "DOGE",
          "text": "Dogecoin"
        },
        {
          "value": "BTC",
          "text": "Bitcoin"
        }
      ]
    },
   {
     "type": "subtitle",
     "text": "Include Expansions:",
     "css": "background-color: purple;color:white;"
    },
    {
     "type": "switch",
     "label": "Rise of Khan",
     "variable": "includedeck",
     "value": true
    }
  ]
}
```

**Review by 96LawDawg — APPROVED** [review]
Reviewed and approved through test.  The only thing I noticed, and this happens in production and should not be changed, is that the min and max values for a number entry do not constrain the entry.  They create a scrollbar with that range, but a user can enter anything.  Will just adjust the wiki to reflect that.

**Comment by 96LawDawg** [comment]
> This looks great. Two things: 1) the wiki should say that if Cancel is pressed, the routine is terminated (at least, I think that's what happens). And 2) does the switch really store off/on rather than false/true? If so, does it return a string "off" or "on"?

1) I agree and I will make the change above
2) Yes.  Returns text value of "on" or "off".  Probably should be/could be true/false, but it doesn't really matter.

**Comment by mousewax** [comment]
The min-max thing is an oversight on my part. I will fix it.

If you want the switch to be true/false we can make it so.

**Comment by 96LawDawg** [comment]
> The min-max thing is an oversight on my part. I will fix it.
> 
> If you want the switch to be true/false we can make it so.

Min/max is working that way on production so you didn't do anything wrong.  I don't care either way.  Just so long as people know what happens.

True/false is a little easier to work with in JSON than "on" and "off," but again I don't really care either way.

**Comment by mousewax** [comment]
The number input works as designed by the web browser people. 

MDN:
> You can use the min and max attributes to specify a minimum and maximum value that the field can have. For example, let's give our example a minimum of 0, and a maximum of 100:
> ...
> In this updated version, you should find that the up and down step buttons will not allow you to go below 0 or above 100. You can still manually enter a number outside these bounds, but it will be considered invalid.

We could add checking and display an error, but I don't think that's needed. Updating the wiki to reflect this is the right thing to do.

I think this PR is good to go.

**Comment by rogerl50** [comment]
> The number input works as designed by the web browser people.
> 
> MDN:
> 
> > You can use the min and max attributes to specify a minimum and maximum value that the field can have. For example, let's give our example a minimum of 0, and a maximum of 100:
> > ...
> > In this updated version, you should find that the up and down step buttons will not allow you to go below 0 or above 100. You can still manually enter a number outside these bounds, but it will be considered invalid.
> 
> We could add checking and display an error, but I don't think that's needed. Updating the wiki to reflect this is the right thing to do.
> 
> I think this PR is good to go.

From the quote above, it sounds as though you should silently constrain to the given bounds. That is, if the user enters 110, you use 100 and so forth. Is that what currently happens?

Also, what did you decide about off/on vs false/true?

**Comment by mousewax** [comment]
I landed on `on` and `off` as the interface greatly implies those contexts. While I think that's the way it should go, I am not married to it so if there's a strong preference for `true`/`false`, I'll update it.

The number things is weird and if we want to address it, there's some possible choices:

1. Mark the field with an error if it's not a number or outside the range and POSSIBLY disable the submit button. 
2. In the UI detect if it's a number AND outside the range and then adjust it to either the min or max  before submitting.
3. On the back-end detect if it's a number AND outside the range and then adjust it to either the min or max after submitting.

I just added this for when the field is empty but there is always at least `1` if no value is specified:
image

**Comment by robartsd** [comment]
> But I think the ability to override the min/max can be important and helpful.

I'm sure it can at times, but I think most of the time a game designer would appreciate built in validation according to the provided parameters. Could add a key to the field definition disabling the range validation.

**Pull request merged**
