### PR TITLE
added `globalUpdateRoutine`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This PR adds the property `globalUpdateRoutine`. It is very similar to the `changeRoutine` but it gets triggered for property changes of other widgets as well.

The main intention behind this is the display of player owned cards for the PCIO seat compatibility (see examples in the test room).

Just like with `changeRoutine`s you can also specify an `ownerGlobalUpdateRoutine` (or any other property) to filter for which property changes the routine will be called. **This is highly recommended to avoid all those `x` and `y` changes you don't care about.**

Contrary to `changeRoutine`s these `globalUpdateRoutine`s do _not_ trigger recursively. So if you change a property inside of the routine, it will not trigger any `globalUpdateRoutine`s. This can be changed easily but I feel like it is not necessary and this way it is a lot harder to build infinite recursion.

I'm not married to the name but it can't end with `ChangeRoutine`.

# Draft Wiki entry (Global properties for every widget)

| Property  | Default value       | Description           | Tutorial              |
| --------  | ------------------- | --------------------- | --------------------- |
| globalUpdateRoutine |  []  | When any property of any widget changes, this [routine](../Functions#Routines) is called. If you want to restrict execution to changes in a particular property, use `<propertyName>GlobalUpdateRoutine` (for example, `ownerGlobalUpdateRoutine` will fire only when the `owner` value of any widget changes so you could update a label with the count of player owned cards).   |

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3605/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
> this way it is ~a lot harder~_not quite as easy_ to build infinite recursion.

**Comment by bjalder26** [comment]
For the sake of consistency with changeRoutines, shouldn't xGlobalUpdateRoutine be the correct format instead of xglobalUpdateRoutine?

I noticed that when it is set to a specific property, the property isn't returned.  That seems appropriate to me.
I noticed that it is not triggered by changes in the editors.  That also seems appropriate to me.
I didn't find any bugs.

**Comment by ArnoldSmith86** [comment]
> For the sake of consistency with changeRoutines, shouldn't xGlobalUpdateRoutine be the correct format instead of xglobalUpdateRoutine?

Yes. It's actually an oversight that currently both of them should be working.

**Review by rogerl50 — DISMISSED** [review]
Can you please add a draft Wiki page update for this PR?

**Comment by ArnoldSmith86** [comment]
> Can you please add a draft Wiki page update for this PR?

I added it to the PR description.

**Comment by RaphaelAlvez** [comment]
is the debug not working? I wanted to check the variables available

**Review by RaphaelAlvez — CHANGES_REQUESTED** [review]
There is no Debug. 
everything else is approved by test

**Comment by ArnoldSmith86** [comment]
With the `debug` property this will be very tricky. That's one of the main reasons why I wanted to introduce the better debug stuff.

**Review by RaphaelAlvez — APPROVED** [review]
approved since there is going to be a new PR for debug

**Pull request merged**
