### PR TITLE
adds new game pieces

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
totally just a draft

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3997/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Not sure how you ultimately plan on implementing this.  Would it make sense to give them names so you don't have to know the image location.  For example, the current code structure could probably handle additional "classes" like we do for checkers.  Or you could create a new one called "gamePiece" or whatever.

**Comment by mousewax** [comment]
There are classes as well as images in `i/game-pieces`. The classes (among other things) use some crafty `border-radius` wizardry to make better hit boxes for pieces.

The idea is that when pieces get updated and improved (without changing the style), even older games on that server would get the updated changes.

**Comment by robartsd** [comment]
> The classes (among other things) use some crafty `border-radius` wizardry to make better hit boxes for pieces.

The classes are made entirely in classes.css (with the help of a Unicode character for the crown). Pseudo elements allow for some pretty crafty styling there.

No reason not to add additional SVG assets served under `/i/`

**Comment by mousewax** [comment]
What's the difference where they're served from?

For me it was providing a base set of pieces that have human-readable names and that can be used to keep legacy games up to date. When images get improved, there's no reason why we should be going back through every tutorial or selector screen to update them. They always have the latest resources. Provided the general style doesn't change, this is quite the boon for us and the users.

**Comment by robartsd** [comment]
> Not sure how you ultimately plan on implementing this. Would it make sense to give them names so you don't have to know the image location.

Just like the current pieces, have users select them from the UI. No need to change the JSON for this.

**Comment by mousewax** [comment]
I'm chugging along, editing my game and I am confronted with this list of objects.
image

So I click on one to investigate.

image

What. the. hell. am I looking at?

But with an update, I get at least a LITTLE context.

image

**Comment by RaphaelAlvez** [comment]
> Not sure how you ultimately plan on implementing this. Would it make sense to give them names so you don't have to know the image location. For example, the current code structure could probably handle additional "classes" like we do for checkers. Or you could create a new one called "gamePiece" or whatever.

well they are just in i/game-pieces/2D/ or i/game-pieces/3D/ users will not have to deal with this. They are just going to click in on game piece and it will be added to their room. 

this is going to be added to the add widget overlay

this pr had 4 stages:
[x] create assets compatible with svgReplace
[x] add assets to /assets
[ ] create JSON and CSS for each game piece (working on it)
[ ] add game pieces to "add widget overlay" with a color picker and dropdown for selecting groups of game pieces.

**Comment by robartsd** [comment]
If you implement as a game pieces deck, `card-type` should be descriptive.

If they are just basic widgets, I think `"image":"i/game-pieces/..."` in the widget should be fine for most users.

**Comment by RaphaelAlvez** [comment]
> If you implement as a game pieces deck, `card-type` should be descriptive.
> 
> If they are just basic widgets, I think `"image":"i/game-pieces/..."` in the widget should be fine for most users.

I don't intend to support deck of game pieces for now. those would only be added in the pcio importer

**Pull request closed without merging**
