### PR TITLE
Change Iago to Reversi, other edits

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public library changes:
 - Iago renamed Reversi.  Added automation and alternative rule selection
 - Moving Walls 3D.  Added rune cards; fixed dropLimit issue.  There is still an automation error if 2 tokens are on the same space when the arrow buttons are selected to push in the new tile.  Only 1 of the token moves.
 - Ninety-Nine. Changes by jade-alarm allow playing of cards from hand just by clicking on them.  Also automation buttons for declaring bid or revealing hand.  Seats and instructions also added.
 - Tittle. Increased size of cards.  Made the blue color cards lighter so easier to see on mobile. Moved hand to right side of board and scores to bottom left.  Added +4 and +1 cards to move cards to hand. Made the pile drag handle for the deck of cards not movable to prevent accidental dragging.  Changed view arrows from unicode to SVG.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3776/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Changed files successfully loaded from library.

**Comment by bjalder26** [comment]
Reversi looks like it is good to go.

**Comment by bjalder26** [comment]
Moving Walls 3D: "There is still an automation error if 2 tokens are on the same space when the arrow buttons are selected to push in the new tile. Only 1 of the token moves."

That is because all the MOVE  functions are set to a `count` of 1 by default.  If you change all of them to 99 (or whatever) then that problem should go away.

**Comment by pounamu** [comment]
You could also set the MOVE to `"count": 0` for unlimited.

**Comment by 96LawDawg** [comment]
> Also, just curious, what do the dice images on the cards mean?

They are for moving "up" and "down."  In the original moving walls, the game pieces are all on the same level.  This version is 3D so you can only move your piece if the levels are +- 1.  So 4 can move to 3 or 5.  The dice are what they came up with to show that.

I made the changes (to count:0, which I hate as showing infinity, but that is what we have).  Seems to have fixed the problem.  But the test room file doesn't seem to be working right.  I'll give it a few hours then try again.

**Comment by bjalder26** [comment]
> They are for moving "up" and "down." In the original moving walls, the game pieces are all on the same level. This version is 3D so you can only move your piece if the levels are +- 1. So 4 can move to 3 or 5. The dice are what they came up with to show that.

Oh, that's a good idea.

> I made the changes (to count:0, which I hate as showing infinity, but that is what we have). Seems to have fixed the problem. But the test room file doesn't seem to be working right. I'll give it a few hours then try again.

Seems to be working now.

In Tittle, shouldn't the x and y changes from the shift buttons be 60 to match the grid in cardDefaults?  Also, it might be nice to shift either the holders on the right side or the grid a bit so they match up better.  It seems like an offsetX of -2 in the grid would do it, but then you'd have to shift every starting piece as well (which would probably be less centered.  I also noticed the dead ends aren't cards and don't form piles.  They will also always wind up on top of a card due to their default layer.  Perhaps that is desired or doesn't matter... I don't really know.

**Comment by bjalder26** [comment]
I don't really know how to play Ninety-Nine, but it looks like everything works.

I might consider making the Reveal Hand button a toggle button that sends the cards back to the hand if that helps with play.
The button furthest to the right in this room works that way. http://212.47.248.129:3373/showcards

**Comment by 96LawDawg** [comment]
> Seems to be working now.

Yeah, sometimes it takes an hour or two for the changes to take effect (server restart time delay on the test servers)

> In Tittle, shouldn't the x and y changes from the shift buttons be 60 to match the grid in cardDefaults? Also, it might be nice to shift either the holders on the right side or the grid a bit so they match up better. It seems like an offsetX of -2 in the grid would do it, but then you'd have to shift every starting piece as well (which would probably be less centered. I also noticed the dead ends aren't cards and don't form piles. They will also always wind up on top of a card due to their default layer. Perhaps that is desired or doesn't matter... I don't really know.

So the shift buttons could move 60 (started at 50 because the cards were 50px until this update), but it doesn't really matter because the all move the same amount.  For the holders on the right, it would be a better look, but I just don't care that much.  As for the dead ends, they are not actually part of game play.  If it were totally up to me I would remove them, but I added them at the request of ArnoldSmith86 and his wife who liked them.  When I play, we don't use them.  /end rant/ As for positioning, they either have to go on top or under a card; either place is bad as they should be treated like their own card and never stacked.


> I might consider making the Reveal Hand button a toggle button that sends the cards back to the hand if that helps with play.

Doesn't work that way.  Once you reveal your hand (to increase points you can earn), you play from the displayed hand so all players can see.

**Comment by pounamu** [comment]
I've edited the room so that click to play works from your hand or from the revealedHand holder. https://virtualtabletop.io/itqq

**Comment by 96LawDawg** [comment]
> I've edited the room so that click to play works from your hand or from the revealedHand holder. https://virtualtabletop.io/itqq

Doesn't work.  Click to play in that room is a mess right now.  Cards go everywhere but not where you want them to.

**Comment by bjalder26** [comment]
> So the shift buttons could move 60 (started at 50 because the cards were 50px until this update), but it doesn't really matter because the all move the same amount. 

They all move the same amount, but the grid doesn't change, which means new cards won't line up anymore once the view is shifted.
image

>For the holders on the right, it would be a better look, but I just don't care that much. 
Yeah, it's a small thing and doesn't affect function.

>As for the dead ends... never stacked.
Probably not an issue then.
 
> Doesn't work that way. Once you reveal your hand (to increase points you can earn), you play from the displayed hand so all players can see.
Then there's no need.

**Comment by pounamu** [comment]
> > I've edited the room so that click to play works from your hand or from the revealedHand holder. https://virtualtabletop.io/itqq
> 
> Doesn't work. Click to play in that room is a mess right now. Cards go everywhere but not where you want them to.

Did you sit down? Click to play only works if you take a seat, otherwise it can't know which holder is yours.

**Comment by 96LawDawg** [comment]
> They all move the same amount, but the grid doesn't change, which means newly placed cards won't line up anymore once the view is shifted.

Good point.  I should have caught that.  I fixed it.  May take a couple of hours to actually show up correct in the library.

**Comment by 96LawDawg** [comment]
> Did you sit down? Click to play only works if you take a seat, otherwise it can't know which holder is yours.

Oops.  Forgot that.  Works great now.  Good addition.  I'll get that uploaded later.

**Comment by 96LawDawg** [comment]
Not going to be able to get that last change to 99 in for this update.  I'm having problems with git and my local copy.  Only way I know to fix it is to start over and I don't want to do that.  So if anyone wants to approve this update, I'll get it merged and then add the last small change to 99 in the next update.

**Pull request merged**
