### PR TITLE
composite widget dynamic parent id

### LINKED ISSUE #549: Update recall, timer, and counter button clickRoutine defaults in editmode to use a dynamic expression
If the default clickRoutine in recall buttons used ${PROPERTY parent}, then changing the holder's ID would not affect the function.
   ` {
      "func": "RECALL",
      "holder": "${PROPERTY parent}"
    },
    {
      "func": "FLIP",
      "holder": "${PROPERTY parent}",
      "face": 0
    },
    {
      "func": "SHUFFLE",
      "holder": "${PROPERTY parent}"
    }
  ],`

image

Likewise, the default label for counter buttons could be changed to "${PROPERTY parent}"
  `"clickRoutine": [
    {
      "func": "LABEL",
      "label": "7rdx",
      "mode": "inc",
      "value": 1
    }
  ]`

image

And the default timer for timer buttons could be changed to  "${PROPERTY parent}".

 `"clickRoutine": [
    {
      "func": "TIMER",
      "timer": "ky04",
      "mode": "reset"
    }
  ],`
image

### PR DESCRIPTION
**Pull request by robartsd**
fixes #549

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3550/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
I tested them, and they appear to work as expected.  I do not know what the TestCafe issue is though.

**Comment by robartsd** [comment]
> I tested them, and they appear to work as expected. I do not know what the TestCafe issue is though.

TestCafe creates a new game as one of the tests. The composite widgets in that new game are now different.

**Comment by bjalder26** [comment]
> > I tested them, and they appear to work as expected. I do not know what the TestCafe issue is though.
> 
> TestCafe creates a new game as one of the tests. The composite widgets in that new game are now different.

Oh, so it is doing what it is supposed to do.  I probably shouldn't be the one to approve of this since I asked for it, but I do believe it tests perfectly and has no chance of causing unexpected issues.  I did test changing the name of the holder, timer, and label, and the buttons still work.  This is really just leveraging the work done on dynamic expressions, and I also like the idea that it makes things easier while also introducing a nice feature to beginners. 

Thanks for doing this PR.

**Comment by robartsd** [comment]
TestCafe results from GitPod:

```
gitpod /workspace/virtualtabletop $ REFERENCE=542 npm run testcafe-firefox-headless -- --test-grep '.*Create.*'

> virtualtabletop@0.1.0 testcafe-firefox-headless /workspace/virtualtabletop
> testcafe firefox:headless tests/testcafe/tests.js "--test-grep" ".*Create.*"

 Running tests in:
 - Firefox 89.0 / Linux 0.0

 virtualtabletop.io
 ✓ Create game using edit mode


 1 passed (12s)
gitpod /workspace/virtualtabletop $ npm run testcafe-firefox-headless -- --test-grep '.*Create.*'
> virtualtabletop@0.1.0 testcafe-firefox-headless /workspace/virtualtabletop
> testcafe firefox:headless tests/testcafe/tests.js "--test-grep" ".*Create.*"

 Running tests in:
 - Firefox 89.0 / Linux 0.0

 virtualtabletop.io
 {
   9eevB: {
     clickRoutine: [
       {
-        holder: "9eev"
+        holder: "${PROPERTY parent}"
       }
       {
-        holder: "9eev"
+        holder: "${PROPERTY parent}"
       }
       {
-        holder: "9eev"
+        holder: "${PROPERTY parent}"
       }
     ]
   }
 }

 ✖ Create game using edit mode

   1) AssertionError: expected '015d09b8df069f29befe88ff93f1494c' to deeply equal
      '2e7611649b3b5339558e3f32df4e774d'
      
      + expected - actual
      
      -015d09b8df069f29befe88ff93f1494c
      +2e7611649b3b5339558e3f32df4e774d
      

      Browser: Firefox 89.0 / Linux 0.0

         85 |    fs.writeFileSync(refFile, state);
         86 |
         87 |  if(!process.env.REFERENCE && hash != md5 && fs.existsSync(refFile))
         88 |    console.log(diffString(JSON.parse(fs.readFileSync(refFile)), JSON.parse(state)));
         89 |
       > 90 |  await t.expect(hash).eql(md5);
         91 |}
         92 |
         93 |async function getState() {
         94 |  // wait for 500ms
         95 |  await new Promise(resolve => setTimeout(resolve, 500));

         at <anonymous> (/workspace/virtualtabletop/tests/testcafe/tests.js:90:24)
         at asyncGeneratorStep (/workspace/virtualtabletop/tests/testcafe/tests.js:6:231)
         at _next (/workspace/virtualtabletop/tests/testcafe/tests.js:6:569)



 1/1 failed (11s)
```
All changes are as expected.

**Comment by ArnoldSmith86** [comment]
This change is also in #522.

**Comment by bjalder26** [comment]
> want this change but I would prefer to merge #522 instead if it doesn't get vetoed. I also de-duplicated some code in that area and merging this might lead to unnecessary (but probably very easy to solve) conflicts.

So you beat me to the idea.  I will link that PR to my issue.

**Comment by robartsd** [comment]
> I do want this change but I would prefer to merge #522 instead if it doesn't get vetoed. I also de-duplicated some code in that area and merging this might lead to unnecessary (but probably very easy to solve) conflicts.

#522 is listed as approved, but needing a conflict resolution.

**Comment by ArnoldSmith86** [comment]
> #522 is listed as approved

Please read my latest comment though. Raphael approved it during the meeting because he wants the feature.

**Comment by robartsd** [comment]
Superseded by #522

**Pull request closed without merging**
