### PR TITLE
Extend image and svg replace to buttons

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
Again I'm moving the PR to the original repo as I can't make changes from mine. I'll be closing the last PR #261

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3267/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
@96LawDawg I found the mistake and now png is working. There is one in the pr-test room.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Allows jpg, png, svg images on buttons (did not test other file types but don't see any reason they wouldn't work).  SVG images allow svgreplaces function.  This is a great enhancement to buttons.  Thanks.

**Comment by RaphaelAlvez** [comment]
3 days old and approved

**Pull request merged**
