### PR TITLE
modify default player colors

### PR DESCRIPTION
**Pull request by robartsd**
I've never really been thrilled with the default player colors. This PR changes the default colors selected for new players (somewhat reducing the value component of the color).

The value is reduced the most for the primary colors (pure red, green, blue: value reduced from 255/255 to 140/255) and the least for the secondary colors (yellow, cyan, magenta: value reduced from 255/255 to 220/255). This [CodePen demo](https://codepen.io/robartsd/pen/LYOEZrX?editors=1100) shows the existing spectrum of colors chosen, an approximation of the new spectrum chosen (gradient points at 15 degree hue angles are accurate, but colors between those points may be slightly different), and sample spectrums of colors that are desaturated enough to be ignored when choosing the hue for a new player color (this is not a change from what is currently in main). While technically this reduces the color space used by the default player colors, I think colors in this range are more distinquishable (particularly the colors containing green components). I very much prefer the darker green (and didn't want to darken the yellow any more than I did). I might prefer the reds and blues a bit brighter.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1189/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
I joined the test room as a new player repeatedly by opening in a private window, changing the player name, taking a seat, then closing the private window. I repeated in a [second test room](https://test.virtualtabletop.io/PR-1189/pr-test2) and on the [main server](https://virtualtabletop.io/itfc).

**Comment by 96LawDawg** [comment]
> I think colors in this range are more distinquishable (particularly the colors containing green components). I very much prefer the darker green (and didn't want to darken the yellow any more than I did). I might prefer the reds and blues a bit brighter.

I agree the greens are more distinguishable, but I think the reds are less so.  Not sure if it is possible to tweak that part of the spectrum, but unless you can do that, I'm not sure it is worth the change.  I like the new slightly more muted look, but am a little concerned about the red end based on your tests.

**Comment by robartsd** [comment]
> I agree the greens are more distinguishable, but I think the reds are less so. Not sure if it is possible to tweak that part of the spectrum, but unless you can do that, I'm not sure it is worth the change. I like the new slightly more muted look, but am a little concerned about the red end based on your tests.

It just depends on how complex a function I want to use to compute the value to use from the hue. The function I currently have in the PR is a sinusoidal with peaks at the secondary colors (hue angle 60, 180, 300) and troughs at primary colors (hue angle 0, 120, 240).

**Comment by robartsd** [comment]
I modified the value function.

Now it has specified values for hues 0 (red), 60, (yellow), 120 (green), 180 (cyan), 240 (blue), and 300 (magenta). Red, blue, and magenta are set to 240/255; green is set to 120/255; yellow is set to 220/255; cyan is set to 200/255. Intermediate hues have a linearly interpolated value.

The main test room was reset and new player colors generated again.

**Review by 96LawDawg — APPROVED** [review]
I think that looks better.  You get my approval.  This isn't that big of a change and it will be really subjective, I think, as to whether people like it.  But in my opinion, it is an improvement.  Most importantly, everything seems to still work as before.

**Comment by robartsd** [comment]
> This isn't that big of a change and it will be really subjective, I think, as to whether people like it.

Definitely subjective. When I first thought of making a change, I thought about just setting the value lower (fixed value for all hues), but I couldn't find anything that I liked for both green (must be somewhat low) and yellow (must be pretty high). Values I like for cyan vary quite a bit depending on the value of the background. From blue to red I generally like a wide range of values.

**Comment by robartsd** [comment]
I think the hue selection works well up to about 6-8 players. It would be nice to have other color dimensions vary when there are too many hues in use already, but I don't have any thoughts on how to do that.

I have thought about using only the active players when choosing a hue if a room has a lot of inactive players.

**Comment by RaphaelAlvez** [comment]
How about we try to always give the hue most spaced from the current hue values?

Or maybe we can curate a list of valid colors. 10-15 colors is more then enough and being curated gives us the ability to use also change the brightness. Brown for example is basically just dark orange and it is a normal enought color to be on the list.

**Comment by robartsd** [comment]
> How about we try to always give the hue most spaced from the current hue values?

The current system calculates the hue of each player then chooses the new player color from the middle third of the largest gap in the hues. Of course the gaps are simply measured as hue angle in RGB space, so the largest perceived gap may not be the same gap as the largest calculated gap and the calculated middle third of the gap may not be the perceived middle third of the gap.

**Pull request merged**
