### PR TITLE
piles are no longer widgets but simply UI elements

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
I already posted an issue about this earlier. Having piles as widgets seemed like a good idea at the time but leads to a lot of headaches.

This PR removes piles from the widget hierarchy and instead puts a property `pile` with the same value to each widget within a pile. The client then simply displays a UI element on top of the pile that looks and feels like the old pile handle.

This introduces these new widget properties (and the default values):

```
      allowPiles: true, // set to false on a holder would prevent piles inside the holder
      pile: null,       // the reference to the pile
      pilesWith: null,  // cards have this set to { type: 'card' } and it can be used to make other things pileable
      pileOptions: {    // also "css" to customize the handle
        xOffset: 10,
        yOffset: 10
      }
```

I didn't really test those properties yet though because the main code still needs work.

I'll add my generic test room to the PR test server. It's fun to play around with and might be a good tutorial/demo somewhere?

Stuff I'm still aware of:
- [x] Dropping a pile onto a pile doesn't move all widgets to the other pile's location.
- [x] The _add widgets_ overlay is disabled because its pile handle messes things up.
- [x] Pile handles don't move if its widgets (or their parents) move for any reason.
- [x] The handle is currently _always_ at the top left.
- [x] The handle doesn't scale down yet for very small widgets.
- [ ] Changing `pileOptions` (or anything else affecting the creation of piles) doesn't take effect immediately.
- [ ] Dropping a pile into a hand doesn't remove the pile handle when the cards get spread out.
- [ ] Adding a new card deck makes the shuffle button (and deck) go to 0,0 in the holder (counters are also broken).
- [ ] Cards with different `pileOptions` in one holder form multiple piles. Probably only direct neighbors (on the Z axis) should form a pile?

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3147/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
I've linked the various pile issues that we're hoping to solve with this change.

**Comment by robartsd** [comment]
current bugs I'm noticiing
- pile handle is 0 while it is being moved
- piles aren't getting destroyed properly: move the second to last card off a pile and everything looks fine, move it back and it becomes part of a 1 card pile, move the one card pile and the card is removed from the pile, but an empty pile moves with the card.

**Comment by rogerl50** [comment]
This seems like an opportunity to consider #106, since you are in all of that code.

**Comment by robartsd** [comment]
> This seems like an opportunity to consider #106, since you are in all of that code.

That appears to be the plan though setting options in the widget(s) that form the pile; not sure how conflicts between the widgets would be worked out. I think the handle is getting inline styles from _widget_.pileOptions.css

**Comment by ArnoldSmith86** [comment]
I think I will eliminate `pilesWith` because `pileOptions` needs to be the same for all widgets in a pile. So you can control `pilesWith` by just changing `pileOptions`.

The problem is that I wouldn't expect `pilesWith` **and** `pileOptions` having to be the same. So I would be wondering why two widgets don't pile if they have the same `pilesWith`.

Any other ideas?

**Comment by robartsd** [comment]
Perhaps there should be elements in the JSON explicitly defining pile types and widgets simply have a list of pile types that they can join or create. Pile options would be set for the pile type, not the widget. Widgets might have the ability to join multiple pile types. Defaults would provide a "card" pile type and cards would have .pileTypes default to ["card"]. Other widgets would have .pileTypes default to [].

**Comment by ArnoldSmith86** [comment]
I added a list of ToDos to the PR description. Please tell me if you find anything else.

**Comment by shaunhillier** [comment]
I was going to offer to help with this one but I copied the branch over to my personal instance and looks like most of the issues have been resolved (not sure why the test server is out of date?). Is there anything you've not got a chance to look at, or anything you would appreciate a second pair of eyes on?

**Comment by ArnoldSmith86** [comment]
What makes you think the test server is out of date?

The ToDos are in the PR description.

**Comment by shaunhillier** [comment]
> What makes you think the test server is out of date?
> 
> The ToDos are in the PR description.

On the test server I was getting odd result where piles were showing wrong size count as I moved cards around, but couldn't recreate on my server with branch.

**Comment by ArnoldSmith86** [comment]
We decided in the meeting of 2021-06-21 that piles will stay as widgets. So I'm closing this PR.

This PR is still a good reference for implemented features and linked issues.

**Pull request closed without merging**
