### PR TITLE
added `highlightBackground` and `highlightBorder` to holder

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This is my proposed alternative to #923.

I am not exactly excited about extracting a background property from `css` but so far I could not come up with a better solution.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3940/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
> > I think this isn't good enough. I thought `background` wouldn't override `background-position` etc. but I think it does.
> 
> You'd need to do separate `background-image` and `background-color` to override those without overriding `background-position` etc.
> 
> > At this point I would rather implement game stylesheets. Would be a lot less work and a lot more flexible. It would just be more complicated to use for the game designer.
> 
> I'm just about sold on the idea of widget stylesheets providing enough flexibility while keeping the style code in the widget; but a game style sheet could do even more (styles changed based on parents for instance).

I am missing something important here, but I don't know what. Is a stylesheet something that I as a game designer would write, or is it the thing that is created automatically (as in this PR) from properties given in the widgets? Can you give me a simple example of how this would work?

**Comment by ArnoldSmith86** [comment]
> styles changed based on parents for instance

And style the UI around the game.

**Comment by robartsd** [comment]
> I am missing something important here, but I don't know what. Is a stylesheet something that I as a game designer would write, or is it the thing that is created automatically (as in this PR) from properties given in the widgets? Can you give me a simple example of how this would work?

This PR is continuing to writie inline styles (style attribute of the element) from widget properties as all previous game designer css in VTT has been. #941 and #942 create widget stylesheets (style element in the html head element) from widget properties. A game stylesheet would be separate from widget properties. Inline styles cannot apply dynamically based on classes and pseudo classes, but is more specific than any stylesheet rule (overrides any rule that does not use `!important`). Within stylesheets, more specific rules override less specific rules; ties in specificity are broken by applying the last rule in source order.

**Comment by ArnoldSmith86** [comment]
If it doesn't cause major issues, I'd prefer to use #951 instead of this. If it does, we can always reopen this.

**Pull request closed without merging**
