### PR TITLE
added `preventPiles` to disable pile formation in holders

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This supersedes #493 because the pile does not need to be there if the handle is hidden. Propose a better name if you have any good ideas.

I only tested `preventPiles: true` on a very simple holder and on one with `alignChildren: false`. Please do some more tests with the various holder properties and button routines.

# Wiki prototype: Holder

| Property  | Default value       | Description           |
| --------  | ------------------- | --------------------- |
| preventPiles | false            | If set to true, cards in this holder will not form a pile - so they won't have a handle to move all of them at once. |

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3646/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Haven't tested this yet, but just had a crazy idea.  Would it be possible to put the `formPile` property into a deck also.  That way you could control whether piles form on the "floor" of the room?

**Comment by robartsd** [comment]
> Haven't tested this yet, but just had a crazy idea. Would it be possible to put the `formPile` property into a deck also. That way you could control whether piles form on the "floor" of the room?

Would be better to implement pilesWith for that.

**Comment by ArnoldSmith86** [comment]
Note to self: when `formPile` is updated, it has to form or destroy a pile.

**Comment by bjalder26** [comment]
How are various mixtures of alignChildren, dropOffset, and stackOffset supposed to affect whether they form piles or not when formPile is set to true?

Also, should a pile that is dropped in an `formPiles: false` holder remain as a pile?

**Comment by robartsd** [comment]
> How are various mixtures of alignChildren, dropOffset, and stackOffset supposed to affect whether they form piles or not when formPile is set to true?

> Also, should a pile that is dropped in an formPiles: false holder remain as a pile?

I realy only picture using formPile: false with alignChildren: true and stackOffset: 0 (unless we add a spread out pile feature like PCIO now has). If alignChildren is true, I would certainly expect any pile dropped in the holder to be destroyed and cards aligned as dictated by the holder. I can't really picture using alignChildren: false and formPile: false together; I don't know what I would expect.

**Comment by bjalder26** [comment]
> > How are various mixtures of alignChildren, dropOffset, and stackOffset supposed to affect whether they form piles or not when formPile is set to true?
> 
> > Also, should a pile that is dropped in an formPiles: false holder remain as a pile?
> 
> I realy only picture using formPile: false with alignChildren: true and stackOffset: 0 (unless we add a spread out pile feature like PCIO now has). If alignChildren is true, I would certainly expect any pile dropped in the holder to be destroyed and cards aligned as dictated by the holder. I can't really picture using alignChildren: false and formPile: false together; I don't know what I would expect.

This is what I found from testing.

formsPiles: true
| alignChildren: true  | alignChildren: false | 
| ------------- | ------------- | 
| +form piles  | +form piles  |  
| +retain piles  | +retain piles  |  

formsPiles: false
| alignChildren: true  | alignChildren: false | 
| ------------- | ------------- | 
| -form piles  | -form piles  |  
| +retain piles  | +retain piles  |  

formsPiles: true, alignChildren: true
| dropOffset  | stackOffset | dropOffset & stackOffset |
| ------------- | ------------- | ------------- |
| +form piles  | -form piles  | -form piles  | 
| +retain piles  | -retain piles  | -retain piles  | 

formsPiles: true, alignChildren: false
| dropOffset  | stackOffset | dropOffset & stackOffset |
| ------------- | ------------- | ------------- |
| +form piles  | +form piles  | +form piles  | 
| +retain piles  | +retain piles  | +retain piles  | 

formsPiles: false, alignChildren: true
| dropOffset  | stackOffset | dropOffset & stackOffset |
| ------------- | ------------- | ------------- |
| -form piles  | -form piles  | -form piles  | 
| +retain piles  | -retain piles  | -retain piles  | 

formsPiles: false, alignChildren: false
| dropOffset  | stackOffset | dropOffset & stackOffset |
| ------------- | ------------- | ------------- |
| -form piles  | -form piles  | -form piles  | 
| +retain piles  | +retain piles  | +retain piles  | 

Essentially formsPiles and alignChildren have no effect on whether piles that were already formed before dropping them in a holder are retained or not.  They are retained unless there is a stackOffset.  stackOffset also prevents piles from forming (this is something we already knew).

Since this is named 'formsPiles' rather than 'allowsPiles', I am inclined to believe that it is working properly.  I also did not find any effects from putting formsPiles on other widgets (as expected).

**Comment by ArnoldSmith86** [comment]
The intention was to never have piles inside a holder with `formPile: false`. It was only intended for `alignChildren: true, stackOffsetX/Y: 0` though. Not sure what should happen for `alignChildren: false`.

**Comment by bjalder26** [comment]
> The intention was to never have piles inside a holder with `formPile: false`. It was only intended for `alignChildren: true, stackOffsetX/Y: 0` though. Not sure what should happen for `alignChildren: false`.

Sorry, I'm not trying to cause problems.  Just doing testing and reporting back.  I try to think of everything people might 'do wrong'.  Personally I'm happy with the way it is.  If everyone is happy with the behavior, then we can just say in the wiki that formPile prevents new piles from forming in the holder, and stackOffset separates all piles.

If you're not happy with it, then I suppose formPile would need work like stackOffset, but with no actual offset.

**Comment by ArnoldSmith86** [comment]
The feature I want would break up piles when putting them into the holder. Unless anyone wants a different feature, I would change `formPile` to do that.

**Comment by bjalder26** [comment]
> The feature I want would break up piles when putting them into the holder. Unless anyone wants a different feature, I would change `formPile` to do that.

Honestly, I think the only real difference is what happens if someone tries to use formPile 'wrong', and what we would say in the wiki.  So I doubt anyone would object.  I don't see any advantage to not breaking up old piles while preventing new ones.

**Comment by bjalder26** [comment]
Another nice thing we learned about this PR is it prevents placing cards under other cards which can happen when stackOffset is used to prevent piles.

**Comment by bjalder26** [comment]
> Did some stuff. Holders with `preventPiles:true` should never have piles in them (except for manual automation or nested holders).
> 
> I think it behaves the way it should now for all the different combinations of properties and I think it results in the expected order of cards.
> 
> Please do some testing...

I retested for every situation mentioned above by dropping two cards and dropping a pile in holders.  None of the ones with preventPiles: true formed piles.
http://212.47.248.129:3646/Interitus2

Was there anything else?

**Review by 96LawDawg — APPROVED** [review]
I can't say I tested everything, but I tested the most common situations and it works as described.  Might be nice to get this one merged around the same time as PR #905 just because.

**Comment by RaphaelAlvez** [comment]
Just looked at the code. I suggest meeting this into #905 before going into main. Looks like won't interfere

**Comment by 96LawDawg** [comment]
While I'm the only one who has officially approved it, looks like there is agreement from @RaphaelAlvez and @bjalder26.  Ready to merge it?

**Pull request merged**
