### PR TITLE
Apply offset to cloned widget even if no parent exists.

### PR DESCRIPTION
**Pull request by flackr**
Fixes a bug I discovered in #1636 that we aren't applying the clone offset if there is no parent.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1637/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1637-pr-test`.

**Comment by 96LawDawg** [comment]
Also fixes #1612.

**Review by RaphaelAlvez — APPROVED** [review]
tested. this is a 2 week bug. I suggest we merge it asap.
it was broken by the dropShadow PR. confirmed in https://test.virtualtabletop.io/PR-1579/pr-test

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Pull request merged**
