### PR TITLE
Adds save room state button to empty room overlay

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
This should help a lot of new users and also direct them into using "save room state" later,
Pretty sure this will help every one in general

For testing you need to have an empty room

image

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3422/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Should we only show this if there are actually widgets in the room?

**Comment by RaphaelAlvez** [comment]
hard to tell. what would be the advantage of not showing this option for an actually empty room?

maybe we can change the first line to: "There is no saved game in this room. You can save your progress or add games to it ....."

**Review by 96LawDawg — APPROVED** [review]
I get the point of the discussion about whether the option should even appear if there are no widgets in the room, but I think we should implement this right away.  This fixes a problem that newcomers frequently encounter.  Good solution, in my opinion.

**Comment by RaphaelAlvez** [comment]
> I get the point of the discussion about whether the option should even appear if there are no widgets in the room, but I think we should implement this right away. This fixes a problem that newcomers frequently encounter. Good solution, in my opinion.

that was the conclusion we came up in the meeting but there was no approval

**Pull request merged**
