### PR TITLE
added a JSON editor command that copies the state from another room/server

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
You press the button (or `Ctrl+Shift+c`) and it asks you for a normal room URL. It then downloads the state of that room into the current room.

It needs CORS headers on the server so you can't copy the state from the main server (virtualtabletop.io) to the test server until this PR is merged.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3311/pr-test (or any other room on that server)

**Comment by larkob** [comment]
Ctrl+Shift+c doesn't work for me on Windows (Firefox/Chrome). It always opens the developers tools (like F12).

**Comment by ArnoldSmith86** [comment]
It doesn't work for me either but since I updated my browser, many hotkeys don't work anymore for me. So IMHO it's fine for this PR and we need to find a general solution.

And thank you very much for your buttons. ;)

**Comment by larkob** [comment]
When canceling the "Enter room url" dialog, it crashes with an "Uncaught TypeError: prompt(...) is null" error.

**Comment by ArnoldSmith86** [comment]
> When canceling the "Enter room url" dialog, it crashes with an "Uncaught TypeError: prompt(...) is null" error.

Oops.

**Review by larkob — APPROVED** [review]
Tested and approved.

**Pull request merged**
