### PR TITLE
Fixes click off bug

### LINKED ISSUE #148: Clicking on room floor does not remove focus from label
This is just a minor annoyance, but I'm accustomed to clicking somewhere on the background to remove focus from an element after I am finished editing. Currently this does not work, only clicks on widgets, UI buttons, or outside the window seems to remove focus.

### PR DESCRIPTION
**Pull request by robartsd**
closes #148

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3232/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Works as described.  Did not review code.

**Review by UltimateGeek — APPROVED** [review]

**Review by ArnoldSmith86 — APPROVED** [review]
I didn't test it but the code looks fine.

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3232/pr-test (or any other room on that server)

**Pull request merged**
