### PR TITLE
Rich Text

### PR DESCRIPTION
**Pull request by bjalder26**
Current markup:
(bold)b 
(italics)i
(centered)center
(red text)cred
(green text)c#00ff00
(subscript)sub
(superscript)sup
(30 font text)30px 

Ordered lists and unordered lists need a tag indicating their beginning and end.  I tried a few other ways, and none of them worked very well.

(ol)(1st item)li 
(2nd item)li 
(3rd item)li(/ol)

(ul)(1st item)li 
(2nd item)li 
(3rd item)li(/ul)

Blacklisted: <, >

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3619/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
hey I have taken a look at this earlier. so here are my questions and things to consider: 

1.  are we no longer going to accept < > = in labels? that might be problematic for some tutorials? @ArnoldSmith86 is there a better solution? the only thing I could image would be blacklisting "</" so most HTML would works or blacklisting each < > in HTML
2.  I did look for markdown/ markup syntaxes and I did not find anything good for colors as @larkob asked for. It looks like to me that the normal approach to markdown is (text){function} or [text](function) and avoids using / for closing code.
3.  would it be hard to use  \n - for bullet points and \n 1- for numbered?
4.  is there any reason to add center? not a problem with me but never saw anyone use it.

**Comment by bjalder26** [comment]
> hey I have taken a look at this earlier. so here are my questions and things to consider:
> 
> 1. are we no longer going to accept < > = in labels? that might be problematic for some tutorials? @ArnoldSmith86 is there a better solution? the only thing I could image would be blacklisting "</" so most HTML would works or blacklisting each < > in HTML

I don't know of a better solution, but maybe someone else can come up with one.  I'm not even sure if blacklisting greaterthan and lessthan does anything.  There are a lot of variations, and I don't know if HTML will accept them or not.  I read that it only accepts one equal sign though, and that appears to be true, because I tested about 30 different related symbols and none of them worked.  Right now the equal symbol is being replaced with another sign that looks like an equal sign, but doesn't work with html.  That might be possible with the <> signs too because other versions aren't blocked, but they might also 'work'.

> 2. I did look for markdown/ markup syntaxes and I did not find anything good for colors as @larkob asked for. It looks like to me that the normal approach to markdown is (text){function} or [text](function) and avoids using / for closing code.
> 3. would it be hard to use  \n - for bullet points and \n 1- for numbered?

Whatever is easy to type, remember, and capture without errors, I guess.  `**bold**` and `*italics*` are pretty common though.  It is what this DIV uses.  Whatever is used it should be easy to remember and/or something they are already familiar with otherwise it won't get much use.  For unordered lists (bullet points) we could wrap them in <ul><li>text</li></ul> or <menu><li>text</li></menu>to not have to indicate a start and finish, but for ordered lists, they will need something indicating their start and ending.

> 4. is there any reason to add center? not a problem with me but never saw anyone use it.
Originally I added it to prevent people from using the <center> tag, which is apparently not universally supported (it is actually a <span> tag.  However, unordered lists and ordered lists also look horrible if centered, so if someone wanted centered text and a list in the same label, then I suppose that would be the way to do it. Menu appears to look fine (at least on my browser) when centered, so it would mostly be about ordered lists and if anyone had another reason to have centered and non-centered text in the same textbox.

**Comment by ArnoldSmith86** [comment]
There's already a `html` function in the code:

```Javascript
function html(string) {
  return string.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
```

That should be enough to make the input safe to be put into HTML code. You just apply that first and then do your markdown replaces.

**Comment by bjalder26** [comment]
I'm pretty sure this portion already happens regardless either from SET or innerHTML.

`.replace(/</g, '&lt;').replace(/>/g, '&gt;'`

Which is why when I was writing back from the div I had to do this.

`		.replace(/&lt;/gimu,'<') 
		.replace(/&gt;/gimu, '>') `

**Comment by bjalder26** [comment]
> 1. I did look for markdown/ markup syntaxes and I did not find anything good for colors as @larkob asked for. It looks like to me that the normal approach to markdown is (text){function} or text and avoids using / for closing code.

As one option, maybe it could be something like this.
(bolded text)b
(italicized text)i
(20 font text)20
(centered text)center
(subscript text)sub
(superscript text)sup
(strikeout text)s
1(first ordered list item) <= 1 indicates start
2(last ordered list item)x <= x indicates end
-(unordered list item) <= no start or end indicated, but wrapped in `ul><li>text</li></ul>` or `<menu><li>text</li>`
(red text)c#ff0000
(red text)cred

(just text in parenthesis... nothing happens)

It seems like that would be easy to type, easy to remember, easy to expand, and easy to capture without errors.

**Comment by bjalder26** [comment]
During a long drive I think I figured out how to make this editable again, but it will be closer (in code) to the other PR, so I might close this one and rename the other one.  However, I am on vacation, so I don't know when I will get to it.

**Comment by RaphaelAlvez** [comment]
Nice!
Take your time no worries

Just don't close this PR until you merge one of them

**Comment by bjalder26** [comment]
> Nice!
> Take your time no worries
> 
> Just don't close this PR until you merge one of them

I decided to do it here after all.  I think it is working but haven't had time to test it much.  I tried to use a simple markup, but lists are a bit more complicated.  They also don't look great, which I assume can be fixed in the CSS somehow (I haven't looked into it yet).

**Comment by ArnoldSmith86** [comment]
I would really prefer to stick to markdown wherever possible. Since there's no real standard, I would suggest using GitHub's syntax:

```Markdown
**bold**
_italic_
~~strikethrough~~
- unordered
- list
1. ordered
2. list
```

**bold**
_italic_
~~strikethrough~~
- unordered
- list
1. ordered
2. list


Detecting where ordered and unordered lists begin and end shouldn't be a big problem. I can help if needed. If it turns into more than a few dozen lines of code, we should probably use a library instead though. But I don't think it should.

The only other thing I would add for now would be colors. But I don't have a good idea for their syntax.

**Comment by bjalder26** [comment]
> I would really prefer to stick to markdown wherever possible. Since there's no real standard, I would suggest using GitHub's syntax:
> 
> ```gfm
> **bold**
> _italic_
> ~~strikethrough~~
> - unordered
> - list
> 1. ordered
> 2. list
> ```
> 
> **bold**
> _italic_
> ~strikethrough~
> 
> * unordered
> * list
> 
> 1. ordered
> 2. list
> 
> Detecting where ordered and unordered lists begin and end shouldn't be a big problem. I can help if needed. If it turns into more than a few dozen lines of code, we should probably use a library instead though. But I don't think it should.
> 
> The only other thing I would add for now would be colors. But I don't have a good idea for their syntax.

I don't really have much of a preference in how it is done.  From looking at other examples 2 asterisks bold is common, 1 for italics is common and underline before and after for underlining is common (but also considered not best practice due to URLs - probably not an issue for us).   

I am not sure what is the best way to do lists.  HTML requires tags surrounding the beginning and end of the list, and a tag surrounding each element.  So either the first and last element of the list need to be captured individually, or the entire list needs to be captured, have tags placed, then each element needs to be captured and have tags placed around them.  I was trying to avoid a complicated solution that is simple, effective, and won't create problems when people make mistakes, but so far it hasn't come to me.

**Comment by bjalder26** [comment]
This method didn't work out.  Too many problems and unexpected behavior.

**Pull request closed without merging**
