### PR TITLE
added importer support for game pieces

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Internally they are pretty much the same as cards so only minimal importer changes are needed.

So far I only tested it with https://boardgamegeek.com/geeklist/272690/item/8176781#item8176781.

For now it links to the game piece images of PCIO but for most of them we should already have alternatives. I will work on replacing the ones we already have in this PR.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3642/pr-test (or any other room on that server)

**Review by RaphaelAlvez — APPROVED** [review]

**Comment by RaphaelAlvez** [comment]
tested and approved. You shoudl just consider adding the pileWith property in this PR since the pieces should not stack with the ones from another deck.
btw here's a test room: https://playingcards.io/5zpv3j

**Comment by ArnoldSmith86** [comment]
We never turn URLs into bundled assets (outside of Ghetto Editor). We should however replace the URLs by our own. That can happen in future PRs though. Hotlinking to PCIO images isn't exactly good but that's how their data format works and at least this makes the pieces work.

`pilesWith` isn't implemented anyway. It would be consistent with importing cards though. I'll take another look.

**Comment by RaphaelAlvez** [comment]
> `pilesWith` isn't implemented anyway. It would be consistent with importing cards though. I'll take another look.

Yeah but now would be a good time to implement it.
This PR could use the pileWith:{deck:"deckID"} we already discussed about

**Comment by ArnoldSmith86** [comment]
Sure but not in this PR.

**Comment by RaphaelAlvez** [comment]
Ok so this is approved.

**Pull request merged**
