### PR TITLE
Add Designer to Several PL Games

### PR DESCRIPTION
**Pull request by 96LawDawg**
Knizia:
  Maki Roll
  King of Dice
  Into The Castle

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1920/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1920-pr-test`.

**Comment by andypymont** [comment]
It seems as well as the two games in this PR so far, the below are also missing. This should be everything as I've now manually checked every game on the shelf for a missing `similarDesigner`.

- Ambagibus: P.D. Magnus
- Hexagonal Chess: Władyslaw Gliński
- Ich mag keine Karten: Thorsten Gimmler
- Liar's Dice: Richard Borg
- Magician: Ken Fisher
- Moving Walls: Max J. Kobbert
- No Cheese, No Coin: Stephen Rafferty
- Peak Performance: Scott Almes
- Quad Line 3D: H. Heller, A. P. Nienstaedt
- Reward: Albert Lamorisse, Michael I. Levin
- Roar: Stefan Dorra
- Scrappet Kaiser Princess: Zoql
- Shattered Dominion: Bruno Cathala
- Stacker:  Hazel "Skip" Bowman 
- Stardust Butterfly: Zoql

**Comment by 96LawDawg** [comment]
I'll get those added now.  Thanks!

**Review by ArnoldSmith86 — APPROVED** [review]
Didn't check if the designers are correct but the "code" looks fine.

**Pull request merged**
