### PR TITLE
Change user cursor circle to outline

### PR DESCRIPTION
**Pull request by 96LawDawg**
Resolves part of #249.  Does not address what happens over the hand.  That will take some more sophisticated coding that I may or may not be able to do.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1289/pr-test (or any other room on that server)

**Review by ArnoldSmith86 — APPROVED** [review]
Looks nice.

Maybe try to use `box-sizing: border-box` so you don't have to change the size?

**Review by RaphaelAlvez — APPROVED** [review]
looks nice

**Comment by 96LawDawg** [comment]
> Maybe try to use `box-sizing: border-box` so you don't have to change the size?

Great idea.  That made things easier to implement and less likely to mess up.  I tested it on an iPad and iPhone.  It looks best on a desktop, but still looks fine on smaller devices.

**Comment by 96LawDawg** [comment]
After looking at some more history on this subject, especially #808, I realized that part of the reason for the opacity difference between pressed and unpressed cursors was to show when that change happened.  But now the change is indicated by switching from a hollow circle to a filled one.  So I reduced the opacity when pressed from 0.5 down to 0.3 which is where I set the hollow circle outline at.  This way it will be less distracting when a bunch of people are working in the same holder/hand.

**Comment by ArnoldSmith86** [comment]
Any reason why you removed `--cursorShowName`?

**Comment by 96LawDawg** [comment]
> Any reason why you removed `--cursorShowName`?

I included an explanation in the commit notes, but didn't post in the discussion.  I removed it because it doesn't do anything.  @robartsd added in #808 at one point when he had the `playerName` as part of the cursor.  But we voted that feature down and he removed it.  But he left 2 useless code lines behind.  You're welcome :-).  You good with the new code changes since you last reviewed?

**Comment by robartsd** [comment]
> 

The css variable was left behind in case someone wanted to use it in a stylesheet.

**Pull request merged**
