### PR TITLE
fix crash with empty piles

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Apparently real-world games crash now because of empty piles. This introduces a sanity check.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3954/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
Added an empty pile in pr-test 2 and I can play with it as if it was any other widget

**Review by RaphaelAlvez — APPROVED** [review]
this seems to fix the problem

**Comment by robartsd** [comment]
Should this have closed #952?

**Pull request merged**
