### PR TITLE
Prevent owner change when childrenPerOwner false

### PR DESCRIPTION
**Pull request by bjalder26**
Addresses issue descripted in #820.  Prevents an automatic owner change when a widget is being removed from a holder if childrenPerOwner is not set to true.

Proposed wiki changes:
| childrenPerOwner | false        | If set to true, a new child will have its _owner_ set to the player that drags the child into the holder.  It will also remove the owner when the card is dragged out of the holder. <br />This is set to true when you add a new hand. |

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3821/pr-test (or any other room on that server)

**Review by ArnoldSmith86 — COMMENTED** [review]
No need for `== true` but doesn't hurt of course.

Any reason why you changed the order of the two lines? Because I have no idea if that breaks stuff...

**Comment by bjalder26** [comment]
> No need for `== true` but doesn't hurt of course.
> 
> Any reason why you changed the order of the two lines? Because I have no idea if that breaks stuff...

I thought it might be better to check for `== true` to exclude anything else someone might put in childrenPerOwner like 'true', 'false', 1, 0.  However, I have no particular reason to think "mistakes" should default to false vs true.  So I can change that if "mistakes" should default to true rather than false.

I changed the order because I originally thought I would GET the parent.  Then I realized I didn't have to an forgot to switch them back.  I switched them back now, because there was no reason to switch them in the first place.

**Comment by ArnoldSmith86** [comment]
> I thought it might be better to check for `== true` to exclude anything else someone might put in childrenPerOwner like 'true', 'false', 1, 0. However, I have no particular reason to think "mistakes" should default to false vs true. So I can change that if "mistakes" should default to true rather than false.

I'm pretty sure that `if(a == true)` is exactly the same as `if(a)`. If you really _only_ want `true` you need `if(a === true)` (which compares value _and_ type).

I would just use the same comparison as the one _setting_ the owner when `childrenPerOwner` is being used.

**Pull request merged**
