### PR TITLE
apply styles in widget stylesheet to `#enlarged`

### PR DESCRIPTION
**Pull request by robartsd**
Copies `#STYLES_widgetID` stylesheet to `#enlargeStyle` stylesheet with all instances of `#w_widgetID` replaced with `#enlarged` so that styles for the widget in the stylesheet will also be applied to the enlarged widget. As a side benefit, styles specific to the enlarged widget can be created with stylesheets:

```json
"css": {
  "#enlarged": {
    styles placed here will only be applied to the enlarged widget
    #w_widgetID#enlarged will not match anything
    but #enlarged#enlarged will match the enlarged widget.
  }
}
```

CSS variables `--roomTop` and `--roomLeft` have been added to assist in positioning the enlarged widget at a fixed point relative to the room area. Offsets from the top left will need to be adjusted with `--scale` and the `transform-origin` should be set to `top left` to override `#enlardged.right`.

The enlarged widget is now a child of a fixed position div that follows the client pointer. Because the enlarged widget is also `position: fixed`, it still is positioned relative to the window, but change the `position` property of the enlarged widget to `absolute` will make the enlarged widget follow the mouse instead. In addition to the `.right` class added to move the enlarged widget to the right side of the screen when the cursor is on the left side of the screen, a `.bottom` class has been added when the cursor is on the top half of the screen (not used by the default styles, but may be useful for game designers styling the enlarged widget).

## Suggested edit to Widget wiki page

| Property  | Default value       | Description           | Tutorial              |
| --------  | ------------------- | --------------------- | --------------------- |
| enlarge   | false               | This can be false or a number. If it's a number, a version of the widget will be displayed as an overlay.  Enlarge is activated when a player mouses-over a widget or when they touch a widget on a touchscreen for half a second or longer. The number is the scale applied to the enlarged widget (the scale property of the widget is ignored in the enlarged widget). So a 3 says that the enlarged version is 3x the size of the widget. A 0.5 would actually show a version that's half as big as the original.<br><br> The enlarged widget gets styles from the widget's stylesheet by making a copy of the stylesheet with the id of the widget replaced with the id of the enlarged widget. Styles targeting only the enlarged widget can be created in a widget stylesheet by starting a selector with `#enlarged`. The enlarged widget uses css `position: fixed` to be positioned near the edge of the viewport; defaulting to the top corner on the opposite side of the viewport as the pointer. The css variables `--roomTop`, `--roomLeft`, and `--scale` can be used in styles for the enlarged widget to calculate a position at specific coordinates in the room and css variables `--originalLeft`,  `--originalTop`,  `--originalRight`,  and `--originalBottom` provide the location of the original widget's bounding box for calculating a position relative to the original widget. The enlarged widget can be positioned relative to the pointer by styling with `position: relative`. | _add link to LawDawg's Tutorial_ |

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1180/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
We could add a cursor div for the current player (always fully hidden by transparent color) and make div#enlarged a child of the player's cursor.  div#enlarged could maintain a default fixed position with position fixed by game designer styles would be able to override the position attribute in a widget stylesheet to make div#enlarged follow the cursor. I think that should be adequate to fully close #244.

**Comment by robartsd** [comment]
Test room now has a demo of using `css` property to customize the enlarged view.

**Comment by 96LawDawg** [comment]
> Test room now has a demo of using `css` property to customize the enlarged view.

That looks ... complicated.

**Comment by robartsd** [comment]
> > Test room now has a demo of using `css` property to customize the enlarged view.
> 
> That looks ... complicated.

It only needs to be as complex as you want to style it.

The first block overrides the card's default overflow property so that the generated content can be seen. It also tests using position:fixed (see my earlier comment as to why I wanted to test position:fixed), and overrides the default %5 from top of window to 2% from top of window.

The next two blocks are used to move the enlarged widget to the bottom if the widget being enlarged is on the top of the screen.

The fourth block creates the pseudo element displaying the cardType and coordinates.

The last block moves the pseudo element to above the enlarged widget if the enlargement is on the bottom.

**Comment by robartsd** [comment]
> That looks ... complicated.

Your comment about the dice face colors not showing on the enlarged widget was what prompted this PR in the first place. In my view this fixes a bug created by #951. The enlarged widget should now get all the styles of the original widget without any changes to existing games (widget stylesheet styles were not being applied at all). Of course pointer event based styles like :hover still won't be seen on the enlarged widget (you can't hover the enlarged widget and the original widget at the same time, and even if you could the enlarged widget has pointer events disabled).

Adding the ability to specifically style the enlarged widget is just bonus.

**Comment by 96LawDawg** [comment]
I played with it some.  No idea what I'm doing.  Purple checker is just default (so I could compare).  Green checker was experimental.  Just trying to create an example of what is in #327 (making the enlarge appear near the original widget/mouse location).

**Comment by robartsd** [comment]
> I played with it some. No idea what I'm doing. Purple checker is just default (so I could compare). Green checker was experimental. Just trying to create an example of what is in #327 (making the enlarge appear near the original widget/mouse location). No success. If you can do that, great. If not, no worries for now.

There is currently no way to have the enlarged respond to the mouse position (though you can place it at any fixed position in the window)...that is an extension that I am thinking about adding.

**Comment by robartsd** [comment]
I don't want to take on the scope needed to allow the enlarged widget to follow the cursor at this time.

**Comment by robartsd** [comment]
I added variables `--roomTop` and `--roomLeft` for convenience in positioning the enlarged widget in a specific location relative to the room instead of the screen.

**Comment by robartsd** [comment]
The red checker demonstrates positioning the enlarged widget in a specific spot in the room. The green checker demonstrates the enlarged widget following the pointer.

**Comment by robartsd** [comment]
> I added variables `--roomTop` and `--roomLeft` for convenience in positioning the enlarged widget in a specific location relative to the room instead of the screen. Any offsets from the top left corner of the room must be calculated using scale, since the position reference is still the viewport, not the scaled room. The `transform-origin` must also be set to `top left` to override the rule for `#enlarged.right`

See destination cards in (css in destinationDeck): https://test.virtualtabletop.io/PR-1180/FunWithTransit

**Comment by 96LawDawg** [comment]
> See destination cards in (css in destinationDeck): https://test.virtualtabletop.io/PR-1180/FunWithTransit

That is an AMAZING effect.  Definitely worth the effort you've put into this.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

We'll need a wiki update for this.

**Comment by robartsd** [comment]
> > See destination cards in (css in destinationDeck): https://test.virtualtabletop.io/PR-1180/FunWithTransit
> 
> That is an AMAZING effect. Definitely worth the effort you've put into this.

Technically that doesn't even require this PR because nothing else uses enlarge in that room; enlarged widget styles don't need to change with the widget that is being enlarged. This PR does make it easier (to get it to work on production I needed a bunch more rules to calculate the position of the room area).

**Comment by robartsd** [comment]
> We'll need a wiki update for this.

A tutorials more than a wiki update. This does not actually change any widget properties - just how they get applied to the enlarged widget.

**Review by RaphaelAlvez — APPROVED** [review]
looks good to me.

Only thing I don't fully like is the need to use position: absolute for the moving enlarge. It is just a bit odd but the blame is on CSS and not on your code.

Also I just realised that we might want to add our own unit that automatically applies "calc(var(--scale)* **VALUE** px)"  but probably in another PR. I'll make an issue for that

also is there any reason so that the div for the enlarged moves arround with the mouse? I find it a bit odd that the enlarged keeps moving. maybe it would be better if it was fixed in relation to the widget. I did find a way to do so using some of your code. I added an exampl in the room

also I managed to make a widget that reveals another image on hover. that is something I always seen being requested.

tested and code reviewed (css)

**Comment by robartsd** [comment]
> Also I just realised that we might want to add our own unit that automatically applies "calc(var(--scale)* **VALUE** px)" but probably in another PR. I'll make an issue for that

Not sure how that could work (in css). I didn't want to go to the extent of adding widget properties.

> also is there any reason so that the div for the enlarged moves arround with the mouse? I find it a bit odd that the enlarged keeps moving. maybe it would be better if it was fixed in relation to the widget. I did find a way to do so using some of your code. I added an exampl in the room

Might be nice to put the widget position into variables in the enlarged to make that more convenient.

> also I managed to make a widget that reveals another image on hover. that is something I always seen being requested.

Should be able to display a different face of the card being enlarged. Something like `#enlarged > .active { display:none } #enlarged > .cardFace:nth-child() {display : block}`

**Comment by robartsd** [comment]
> Only thing I don't fully like is the need to use position: absolute for the moving enlarge. It is just a bit odd but the blame is on CSS and not on your code.

`position:relative` should work just as well as `position:absolute` in this case if that sounds better to you.

**Comment by 96LawDawg** [comment]
> Should also be able to display a different face of the card being enlarged. Something like `#enlarged > .active { display:none } #enlarged > .cardFace:nth-child() {display : block}`

That would be amazing.  My idea based on this was to create a 3 faced card.  First 2 faces as usual.  Third face would be an explanation of its powers or whatever, but it would only show when face up (activeFace: 1).  And it would use a clickRoutine to prevent showing the 3rd face when flipping over.  I have it all set up in the test room in the upper right, but can't get the enlarge to work as described.  Help?  I would then add this to the tutorial.

**Comment by robartsd** [comment]
> > Should also be able to display a different face of the card being enlarged. Something like `#enlarged > .active { display:none } #enlarged > .cardFace:nth-child() {display : block}`
> 
> That would be amazing. My idea based on this was to create a 3 faced card. First 2 faces as usual. Third face would be an explanation of its powers or whatever, but it would only show when face up (activeFace: 1). And it would use a clickRoutine to prevent showing the 3rd face when flipping over. I have it all set up in the test room in the upper right, but can't get the enlarge to work as described. Help? I would then add this to the tutorial.

You were attempting to use a compound object to build css selectors (also attempted to select nth-child as a class selector `.` instead of a pseudo class selector `:` and used zero based face index (as javascript does) rather than one based face index).

```json
"css": {
  "#enlarged" : {
    ">.active": {
      "display": "none"
    },
    ">.cardFace:nth-child(3)": {
      "display": "none"
    }
  }
}
```
generates (not valid css):
```css
#enlarged {
  >.active {
    display: none;
  }
  >.cardFace:nth-child(3) {
    display: block;
  }
}
```
I changed it:
```json
"css": {
  "#enlarged > .active": {
    "display": "none"
  },
  "#enlarged > .cardFace:nth-child(3)": {
    "display": "block"
  }
}
```
which generates:
```css
#enlarged>.active {
  display: none;
}
#enlarged>.cardFace:nth-child(3) {
  display: block;
}
```

**Comment by 96LawDawg** [comment]
Thank you for the help.  You are a wizard with CSS and it is making us and our games better.  To me, this finally seems like an ideal solution for a built-in help system, at least for cards.  For individual widgets, you could do something like Raphael did with background-image.

Just an observation on one other thing.  The new #enlarged CSS property looks like it only pulls from the face "object" in the card.  I had put

```JS
{
      "border": false,
      "radius": 8,
      "objects": [
        {
          "type": "text",
          "x": 0,
          "y": 0,
          "width": 103,
          "height": 160,
          "css": "background-color:red; color:white",
          "dynamicProperties": {
            "value": "power"
          }
        }
      ]
    } 
```
as the 3rd face.  The border-radius was not showing up, presumably because it wasn't in the object but was just part of the overall face setup.  Easy to fix by adding `border-radius:8` to the css line.  Not suggesting anything should be changed; just pointing that out.

**Comment by robartsd** [comment]
> Thank you for the help. You are a wizard with CSS and it is making us and our games better. To me, this finally seems like an ideal solution for a built-in help system, at least for cards. For individual widgets, you could do something like Raphael did with background-image.

Or text directly in the css using content property of ::before and/or ::after pseudo elements. 

> 
> Just an observation on one other thing. The new #enlarged CSS property looks like it only pulls from the face "object" in the card. I had put
> 
> ```js
> {
>       "border": false,
>       "radius": 8,
>       "objects": [
>         {
>           "type": "text",
>           "x": 0,
>           "y": 0,
>           "width": 103,
>           "height": 160,
>           "css": "background-color:red; color:white",
>           "dynamicProperties": {
>             "value": "power"
>           }
>         }
>       ]
>     } 
> ```
> 
> as the 3rd face. The border-radius was not showing up, presumably because it wasn't in the object but was just part of the overall face setup. Easy to fix by adding `border-radius:8` to the css line. Not suggesting anything should be changed; just pointing that out.

The border radius is still applied to the .cardFace, but the overflow property isn't set in the standard css unless the face is active, so the object on the .cardFace was not clipped by the .cardFace border radius.

**Comment by robartsd** [comment]
> Might be nice to put the widget position into css variables in `#enlarged` as part of Widget.showEnlarged() to make that more convenient (rather than requiring the stylesheet rebuild every time the widget moves). Could go so far as to just provide the client rectangle coordinates directly so that the stylesheet doesn't need to calculate as an offset from the room variables.

Bounding box (client coordrinate system) of the original widget provided to enlarged widget as css variables `--originalLeft`, `--originalTop`, `--originalRight`, `--originalBottom`.

**Comment by 96LawDawg** [comment]
> Bounding box (client coordrinate system) of the original widget provided to enlarged widget as css variables `--originalLeft`, `--originalTop`, `--originalRight`, `--originalBottom`.

Couldn't figure out how to use that.  Could you update the draft wiki entry above?

And I've updated the draft tutorial to include the 3rd face enlarge technique for cards you helped me with above.

**Comment by robartsd** [comment]
> > Bounding box (client coordrinate system) of the original widget provided to enlarged widget as css variables `--originalLeft`, `--originalTop`, `--originalRight`, `--originalBottom`.
> 
> Couldn't figure out how to use that. Could you update the draft wiki entry above?

I've modified @RaphaelAlvez 's example to use `--originalTop` instead of `${PROPERTY y}`

**Pull request merged**
