### PR TITLE
Add Moving Walls 3D, other updates

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:

- Moving Walls 3d. New game by Casbuild and ArnoldSmith86.  Similar to 3d Labyrinth.
- Fireworks.  Markers no longer movable, removed pile handle from stacking holders, increased stackOffsetY on discard holders.
- Moving Walls.  New visual elements by Casbuild and fixed game pieces getting lost.
- Undercover. Fixed layer of two cards.
- Undercover Duo. Removed pile handles on top of words.
- Blue. Add automation buttons to empty holders, discard dropped tiles, and improved reset button.

Public Tutorials:
- Arrays.  Activated features enabled by PR 469: in, remove, numericSort.
- Math.  Activated features enabled by PR 469: acos, atan, atan2, asin.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3636/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Changed files loaded from public library

**Comment by 96LawDawg** [comment]
Can't figure out why TestCafe isn't working for Blue.  The error is:
1) The specified selector does not match any element in the DOM tree.

       > | Selector('[id="fdc25f83-ed33-4845-a97c-ff35fa8a...)

That is the old name for the holder that has all the tiles at the start of the game.  The new name is "tileBag."  That old name is not one of the buttons being pressed in TestCafe.  I checked and they are all still the same name.  That old fdc25f83.... holder doesn't appear anywhere in the new version of Blue even as a reference for some other button.  So I just can't figure out the reason for the failure.

**Comment by ArnoldSmith86** [comment]
I'll look into it.

**Comment by ArnoldSmith86** [comment]
The button `fdc25f83-ed33-4845-a97c-ff35fa8a094f_shuffleButton` is clicked in the test. It was renamed to `reset_button` so that change has to be reflected in the test. After that it gives you the new hash. Should look like this:

```Javascript
publicLibraryButtons('Blue',               0, '6681bcf652fe87f58945797e2f909036', [
  'fcc3fa2c-c091-41bc-8737-54d8b9d3a929', 'd3ab9f5f-daa4-4d81-8004-50a9c90af88e_incrementButton',
  'd3ab9f5f-daa4-4d81-8004-50a9c90af88e_incrementButton', 'd3ab9f5f-daa4-4d81-8004-50a9c90af88e_decrementButton',
  'reset_button', 'buttonInputGo', 'fcc3fa2c-c091-41bc-8737-54d8b9d3a929', '9n2q'
]);
```

The test could be expanded to click the new buttons but that can happen another time.

I also noticed that `Blue` contains a BGG link.

**Comment by 96LawDawg** [comment]
Thanks for the help.  (Should have added that as a label).  I swear at looked at that, but I obviously missed that button name change.  The BGG link is in the current public library version.  Might have been there from the start.  But I fixed that and the new TestCafe is working.

**Review by RaphaelAlvez — APPROVED** [review]
Changes are as discribed

**Pull request merged**
