### PR TITLE
Split up tests into categories with common helper functions.

### PR DESCRIPTION
**Pull request by flackr**
In preparation for adding more different types of tests, split up the existing tests into three main categories. The npm run scripts now accept as an argument which test file you want to run.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1362/pr-test (or any other room on that server)

After merging, a backup will be available at https://beta.virtualtabletop.io/editor/PR1362-pr-test.

**Review by ArnoldSmith86 — APPROVED** [review]
The split looks good. I didn't check if you did major code changes but I assume you didn't.

This would be a perfect opportunity to split the GitHub action into multiple ones so they can run in parallel. Since the compute test takes about as long as all the public library tests combined, it would make the tests a lot faster in total. We can also do this in a new PR though.

**Comment by ArnoldSmith86** [comment]
Kinda related but not really: it would also be nice if the tests run a second time in case of a problem. They fail for no apparent reason quite a lot.

**Comment by flackr** [comment]
> The split looks good. I didn't check if you did major code changes but I assume you didn't.

That's correct, there are no functional changes, just splitting up the code and moving common functions to `test-util.js`

**Comment by robartsd** [comment]
Needs updated wiki instructions for how to run tests.

**Review by 96LawDawg — APPROVED** [review]
Nothing to test.  All Cafe Tests run as expected.  Approved.  @flackr can you suggest some wiki edits to explain how to run Test Cafe under this new split procedure?  @ArnoldSmith86's suggestions for simultaneous tests and automatically rerunning tests can be a new PR someday.

**Comment by robartsd** [comment]
> Nothing to test. 

I plan to test the instructions. Should have instructions for running all tests, instructions for running a single section of tests, and instructions for running a specific test.

`npm run testcafe-gitpod` fails with:
```
ERROR Cannot prepare tests due to the following error:

ReferenceError: window is not defined
    at Object.<anonymous> (/workspace/virtualtabletop/client/js/connection.js:80:1)
    at Object.<anonymous> (/workspace/virtualtabletop/client/js/main.js:2:1)
    at Object.<anonymous> (/workspace/virtualtabletop/tests/client/client-util.js:1:1)

Type "testcafe -h" for help.
```

**Comment by ArnoldSmith86** [comment]
> Not sure if this is just a problem with the tests on gitpod or not.

It does still work on `main`.

**Comment by robartsd** [comment]
Perhaps we need 2 npm scripts per browser scenario, one that runs all tests and another that requires test paths be specified.

**Comment by robartsd** [comment]
Old scripts names require passing of the path(s) to tests, new script names with `-all` added to the end uses the path `tests/testcafe`. 

`npm run testcafe-all` runs all tests in Chrome.
`npm run testcafe tests/testcafe/publiclibrary.js` runs Public Library tests in chrome.

`npm run testcafe-firefox-all` runs all tests in Firefox.

Note `npm testcafe-gitpod` now requires two sets of double hyphens `--` to get a `--test-grep` argument passed to the testcafe process, all other scripts only require one set of double hyphens before the `--test-grep` argument as before.

`npm run testcafe-gitpod-all -- --test-grep pattern` runs any test that matches pattern.

`npm run testcafe-gitpod tests/testcafe/publiclibray.js -- -- --test-grep pattern` runs any test in publiclibrary.js that matches pattern.

**Comment by robartsd** [comment]
There might be a way `gitpod.sh` such that it be called with the path to the scripts as well as `--test-grep` argument without the need for the variation on how it is called.

**Comment by robartsd** [comment]
> Do we just change the way you call TestCafé or can we make `tests/testcafe/` the default while still being able to specify single files?

I think we could write a script that reads the command line arguments. If a path to tests is given as the first command line argument, then just use the given arguments, otherwise use `tests/testcafe/` followed by the given arguments.

**Comment by flackr** [comment]
Just getting back to this. As far as I can tell is this ready to go with the added `-all` targets you added @robartsd ?

@96LawDawg Currently https://github.com/ArnoldSmith86/virtualtabletop/wiki/TestCafé says to run the tests with:
`npm run testcafe-firefox-headless`

This would need to be changed to:
`npm run testcafe-firefox-headless-all`

It would also be worth adding a mention that you can run an individual test with:
`npm run testcafe-firefox-headless tests/testcafe/testfile.js`

**Comment by robartsd** [comment]
> Just getting back to this. As far as I can tell is this ready to go with the added `-all` targets you added @robartsd ?
> 
> @96LawDawg Currently [https://github.com/ArnoldSmith86/virtualtabletop/wiki/TestCafé](https://github.com/ArnoldSmith86/virtualtabletop/wiki/TestCaf%C3%A9) says to run the tests with: `npm run testcafe-firefox-headless`
> 
> This would need to be changed to: `npm run testcafe-firefox-headless-all`
> 
> It would also be worth adding a mention that you can run an individual test with: `npm run testcafe-firefox-headless tests/testcafe/testfile.js`

`-- --test-grep` works to select tests from within the test files by name from either (of course if you specify a test file then the search is limited to that file).

**Comment by flackr** [comment]
@robartsd are you good with landing this? Or would you like me to add a script to insert `tests/testcafe/` if there are no arguments or the first argument does not look like a path / test file?

**Comment by robartsd** [comment]
I'm absolutely okay with this as is.

**Pull request merged**
