### PR TITLE
new game: Dreamcatcher (similar to Dixit)

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Powered by AI. I think this one is really cool. :smile:

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1769/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1769-pr-test`.

**Comment by 96LawDawg** [comment]
The art is amazing @ArnoldSmith86 and @RaphaelAlvez.  I know that Midjourney did the heavy lifting, but wow!  It was just a few months ago that some of you started playing with Dixit art.  Those first images were good enough.  But with the latest updates to Midjourney, just wow!

I had to see the cards, so I used the Deck Display code from the Demo Library.  You can see them all laid out here https://test.virtualtabletop.io/PR-1769/cards.

So on to the review.  One persistent problem.  I was testing with 4 seats.  Every time, one of the players did not have check marks to vote.  Not sure what the pattern was.  But I couldn't test the voting because one player never could vote.

**Comment by 96LawDawg** [comment]
BTW, recommend you add BGG list of awards to the metadata.

(And thanks for your work in making Midjourney more usable for mass production of images).

**Comment by ArnoldSmith86** [comment]
The storyteller can't vote. Because they know the answer.

**Review by 96LawDawg — APPROVED** [review]
I was expecting the storyteller not to be able to vote, but it still seemed strange.  Then I looked at the seat turn indicator and finally my slow brain put it together.  Works great when not operated by an idiot.  Approved through test.

**Comment by 96LawDawg** [comment]
Not a big deal, but when I add awards, I remove the duplicates.  There are several in the list.  For example

```
2010 Vuoden Peli Family Game of the Year Winner
2010 Vuoden Peli Family Game of the Year Nominee
```

Get rid of Nominee because it won.  Just a suggestion; I don't really care.

**Pull request merged**
