### PR TITLE
improved debug output

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The current debug output is from a time before `IF`, `FOREACH` and `CALL`. It even pre-dates `COMPUTE` I think and back then everything was simpler. For current routines, the output is way too long and not really readable.

This PR replaces the `debug` property by commands in the JSON editor. There are no commands yet though. For now the new debugging is simply enabled while having the JSON editor enabled. This will change though.

There are still many things that need improvements but it is now at a state where it might be more useful than the status quo so I opened the PR to get some early feedback.

- I want subroutines to be collapsible.
- IFs look horrible.
- Subroutine triggers are still displayed below the contents.
- ~~The top widget selection (`F1`...) now overlaps the room.~~
- ...

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3548/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
I know there is limited real estate, but *please* use 10 point type at least. If that won't work, at least try to use it in the detail overlay on the left-hand side.

**Comment by ArnoldSmith86** [comment]
Yeah, I know. I'm not exactly happy with that yet. :smile: 

The problem is that you want to edit the widget, use commands and get IDs from the room while editing routines. I didn't have a good idea yet where to put the debug output.

**Comment by rogerl50** [comment]
> Yeah, I know. I'm not exactly happy with that yet. 😄
> 
> The problem is that you want to edit the widget, use commands and get IDs from the room while editing routines. I didn't have a good idea yet where to put the debug output.

Can you create a browser tab from JS? If you can, then after tearing it off, at least users could reposition the output in a way that made sense in context.

**Comment by ArnoldSmith86** [comment]
There has to be a better solution than a separate tab..

**Comment by RaphaelAlvez** [comment]
> There has to be a better solution than a separate tab..

I have to agree with him that this would be a good OPTION. Making it mandatory would be horrible.

**Comment by rogerl50** [comment]
A couple of thoughts:
1. Can you put the detail along the bottom? Generally (if you're not in expanded view) the area below the image of the table is empty. That would make the table visible during debugging. You could even think about moving the tabletop display up towards the top of the window to create more space at the bottom. Of course, if in expanded view, this wouldn't work as well. Also, I'd consider not showing the Problems section if it's empty.
2. Would a canned treeview widget help with the collapsing? If not, building collapsing CSS doesn't seem hard (for someone who knows CSS :) )
3. I think this is worth deploying to production once you have the control structures (IF, CALL/CLICK, FOREACH?) displaying reasonably. It's unlikely to interfere with game operation and is already easier to work with than the existing `debug` mechanism.

**Comment by ArnoldSmith86** [comment]
My "building games" environment usually looks like this:

Screenshot from 2021-06-10 17-27-41

So there's not a lot of space above and below the room. It could always shrink of course.

**Comment by rogerl50** [comment]
How do you make the tabletop larger in the editor? (And get the visual divider between the code and the selectors?)

**Comment by ArnoldSmith86** [comment]
You use a 1440p screen and the divider is a scrollbar.

You can in theory use the browser zoom to change the room area.

**Comment by bjalder26** [comment]
> And get the visual divider between the code and the selectors?

Are you not seeing a visual divider on the live server, or not seeing it in a PR?  Because if you are not seeing it on the live server, then a long enough code that runs past the bottom of the screen should cause the divider to appear.

**Comment by rogerl50** [comment]
My screen (2880x1800) looks like this:
Screen Shot 2021-06-10 at 12 27 39 PM

**Comment by ArnoldSmith86** [comment]
So, it's probably a retina screen? Which gives you a smaller image with more pixels. You should be able to just zoom out with your browser features and the room should get bigger.

We might want to provide some feature ourselves to adjust the ratio?

**Comment by rogerl50** [comment]
Yes, that's right - if I zoom out the text gets smaller and the area for the room gets bigger.

**Comment by bjalder26** [comment]
I uploaded the FOREACH tutorial so I could see how that would look, and the JSON editor still displays the widgets of the previous game.  However, the debug seems to work anyway.

**Comment by bjalder26** [comment]
> There has to be a better solution than a separate tab..

What if there was a way to toggle debug view in the same area as the board?  We're not using Ctrl for anything, are we?  That bit about Ctrl was a joke, but maybe one of the function keys since you don't need to be pressing anything else at the same time.

**Comment by rogerl50** [comment]
> > There has to be a better solution than a separate tab..
> 
> What if there was a way to toggle debug view in the same area as the board? We're not using Ctrl for anything, are we? That bit about Ctrl was a joke, but maybe one of the function keys since you don't need to be pressing anything else at the same time.

That would probably work. You probably don't need to be seeing the board while you're looking at the debug details, as long as they don't hide the code.

I'd prefer to get away from keystrokes and would rather see a toggle switch or button.

**Comment by bjalder26** [comment]
> I'd prefer to get away from keystrokes and would rather see a toggle switch or button.

You mean something you click right?

**Comment by rogerl50** [comment]
> > I'd prefer to get away from keystrokes and would rather see a toggle switch or button.
> 
> You mean something you click right?

Yes.

**Comment by bjalder26** [comment]
Is 'applied operation' supposed to show the variables replaced by their stored values? I don't see any difference between 'original operation' and 'applied operation'.

**Comment by ArnoldSmith86** [comment]
It doesn't work for expressions yet. But other operations should show variables applied and all the default values.

**Comment by bjalder26** [comment]
After using this a bit, I find it is really helpful, but I would say that it needs more screen area.  In my opinion, the one thing it should not cover is the JSON.  I figure that is what you want to look at while you are looking at the debug data.  Also, some of the data that is shown on the left side of the screen can be really long sometimes, and many times the most important information is at the bottom.  You can zoom out to see it, but it can get really tiny.

Also, even though I mentioned a possible toggle key, I could not care less if it was a key or an on-screen button.

**Comment by ArnoldSmith86** [comment]
Yeah, it should probably use the room space..

**Comment by ArnoldSmith86** [comment]
This is still far from finished but I changed where, how and how big the debug output is being displayed. Everything should be accessible now by scrolling.

Please tell me what you think about the changes...

**Comment by 96LawDawg** [comment]
I played around with this some while working on the poker sort room.  I thought this was great.  The only problem was when I tried to see the detail on a particular line, you have to highlight that line with the cursor and then very CAREFULLY move the mouse over to the right side of the screen in the red area while staying on the same line.  Maybe either make the lines a little bit bigger (slightly bigger font) or allow to click on a line of output on the left side of the screen and "lock" it in to place while moving the mouse over to the right/red side of the screen.

**Comment by rogerl50** [comment]
Can you merge at least PR #528 into this one? I need this for debugging but don't have `inheritFrom` here.

**Comment by RaphaelAlvez** [comment]
> Can you merge at least PR #528 into this one? I need this for debugging but don't have `inheritFrom` here.

You can use the current staging server. Both PRs are there

**Comment by rogerl50** [comment]
To improve the presentation of nested constructs (`CALL`, `CLICK`, `IF`, `FOREACH`, and `enter/leave/changeRoutine`s), I think the code should not call `jeLoggingRoutineStart` and `jeLoggingRoutineEnd` if `depth>0`, and instead the nesting constructs should call a new and different routine before and after they execute so as to present more context-dependent information.

**Comment by rogerl50** [comment]
After the latest push, the arrows on the left property expand and collapse all subtrees. There are also arrows on the right of each operation that contains details; clicking on the arrow shows the detail (and hovering no longer does). Issues that I know about:
1. If you click on multiple detail arrows, they are all active, but the last one clicked on covers up the others. This is likely not the desired behavior.
2. The color scheme is still hideous :)
3. It might be desirable to have the details displayed in the main tree rather than on the side. This would also simplify dealing with item 1, as it would be entirely reasonable to have two sets of details open at once.
4. There is still no solution for CALL/IF/FOREACH displaying something reasonable at the start, and again at the end.

**Comment by rogerl50** [comment]
@ArnoldSmith86  Please take a look. I'm pretty happy with this. There is a merge issue that I have no idea how to deal with, and the styling still probably needs some work, in addition to whatever bugs remain.

**Comment by ArnoldSmith86** [comment]
Very nice. I added some stuff but it still needs some work.

**Comment by bjalder26** [comment]
I think it looks really great, but unless you are zoomed out, or have a large screen, if there is no current debug, then mousing over "Show Routine Debug Output" appears to just make the screen go black, which may confuse some people. 

image

**Comment by bjalder26** [comment]
I think that maybe this PR server needs to be reset.

**Comment by rogerl50** [comment]
> I think that maybe this PR server needs to be reset.

The room I'm working in seems OK. What are you having a problem with?

**Comment by bjalder26** [comment]
> > I think that maybe this PR server needs to be reset.
> 
> The room I'm working in seems OK. What are you having a problem with?

Updating and downloading variants is very slow for me, and if I go to the address without putting in a room id (http://212.47.248.129:3548/), then it seems to take forever.

**Comment by bjalder26** [comment]
I know this is still a draft, but FYI I'm getting an error message when I press ctrl-J.  To me it looks like "CTRL-click a widget..." is 
image

I compared to another PR server, and jeSet wasn't called upon pressing ctrl-J, and when it was the text did not include "CTRL-click a widget...". 
image

**Comment by rogerl50** [comment]
> I know this is still a draft, but FYI I'm getting an error message when I press ctrl-J. To me it looks like "CTRL-click a widget..." is getting captured as part of the text because jeSet is getting called when it shouldn't and causing an error.
> image
> 
> I compared to another PR server, and jeSet wasn't called upon pressing ctrl-J (only upon clicking on a widget in the JSON editor), and when it was the text did not include "CTRL-click a widget...".
> image
> 
> It only seems to happen the first time ctrl-J is pressed.

When I do this on a new (empty) room, ctrl-J seems to work fine. I also tried in a new room and loaded up a vtt file, and it worked fine. Can you give any more details?

**Comment by ArnoldSmith86** [comment]
Just to avoid confusion: the error should be a caught exception so you normally shouldn't notice it at all. The code does some post-processing to valid JSON but if it can't parse the JSON, it just uses the text as is.

It doesn't seem to be correct though that @bjalder26 says that `jeSet` is not called on other servers. The tree view function looks like this (in production - [no changes in 4 months](https://github.com/ArnoldSmith86/virtualtabletop/blame/main/client/js/jsonedit.js#L1090)):

```Javascript
function jeDisplayTree() {
  const allWidgets = Array.from(widgets.values());
  let result = 'CTRL-click a widget on the left to edit it.\n\nRoom\n';
  result += jeDisplayTreeAddWidgets(allWidgets, null, '  ');
  jeMode = 'tree';
  jeWidget = null;
  jeStateNow = null;
  jeSet(jeStateBefore = result);
  jeGetContext();
  jeShowCommands();
}
```

**Comment by bjalder26** [comment]
> When I do this on a new (empty) room, ctrl-J seems to work fine. I also tried in a new room and loaded up a vtt file, and it worked fine. Can you give any more details? Also, `jeSet` is called from several places; what does the call stack look like when you get this error?

image

I tried a different browser and got the same results.  I also tried it in the pr-test room and got the same error (below).
image

I have also noticed issues with downloading SOME variants and games.

In the pr-test room I couldn't download Reward or Undercover, but others I could (I didn't try them all).
This is what happened when I tried certain downloads:
Trying to download Reward game: http://212.47.248.129:3548/dl/pr-test/2iq2
Trying to download Reward variant: http://212.47.248.129:3548/dl/pr-test/2iq2/2iq2

Trying to download Undercover game: http://212.47.248.129:3548/dl/pr-test/stst
Trying to download first variant: http://212.47.248.129:3548/dl/pr-test/stst/stst
Second variant: http://212.47.248.129:3548/dl/pr-test/stst/r01k
Third variant: http://212.47.248.129:3548/dl/pr-test/stst/6ke3

It gives me an internal server error.
image

I'm not sure if that is related or not.

**Comment by rogerl50** [comment]
> 
> I'm not sure if that is related or not.
> 
> On edit: Now I'm getting the exact same error on every server I try. Only on the first time I open the JSON editor after refreshing though. Perhaps that hasn't been causing any problems.

All the links you posted work fine for me. You might try resetting your cache or trying a different browser.

**Comment by bjalder26** [comment]
> All the links you posted work fine for me. You might try resetting your cache or trying a different browser.

I'm still getting the same Internal Server Error message in both Brave (chrome) and Edge.  I don't know why.  If nobody else has the same issue though, then I probably wouldn't worry about that.  Comcast service here is horrible, so it could always be that.
image

**Comment by ArnoldSmith86** [comment]
Can confirm that there's a problem:

`2021-07-24T15:25:21.831Z ERROR - URL /dl/pr-test/2iq2 - TypeError: Cannot read property '_meta' of undefined\n    at Room.download (server/room.mjs:175:38)\n    at async downloadState (server.mjs:45:15)`

**Comment by rogerl50** [comment]
Update: As of the 7/29 push, I've completed improved messaging for all functions. Things remaining to be done:
1. A thorough code review. There are many areas where I've simply tried to copy other code, but someone needs to read the changes to make sure I've done things reasonably.
2. The punctuation (single vs double quotes) in the function messages in the debug output could probably use some improvement.
3. Both the Node.js tests and the TestCafe tests fail, and I don't know how to fix them.
4. Any other review comments.

**Comment by bjalder26** [comment]
I'm not noticing any problems.  I think the problems I noticed before were unrelated, and probably fixed when the server was reset.  This PR is pretty amazing, and I would have been happy to have the first draft.  The only suggestions I would make is considering making `IF` and `call` different colors because they can have a bunch of stuff under them.  Also, considering making it so that if something comes up 'red' (null result or some error) that the red color go up the 'tree' so it can be seen at a glance.  However, I wouldn't postpone merging this to wait for that (if you decided you want to do either of those things)

One of the TestCafe errors is almost identical to the one that showed up here: (https://github.com/ArnoldSmith86/virtualtabletop/pull/693/checks?check_run_id=3164175264) - don't know if that helps though.

**Comment by bjalder26** [comment]
image
Seems like jeRoutineLogging is defined in jsonedit.js, but then used extensively in widget.js.  Is there a missing import or get?

**Comment by rogerl50** [comment]
> image
> Seems like jeRoutineLogging is defined in jsonedit.js, but then used extensively in widget.js. Is there a missing import or get?

Right. I tried importing it from jsonedit.js, but then `onLoad` ends up being undefined. I think what is needed is a local overriding definition in the test files, but I was unable to make that work either.

**Comment by bjalder26** [comment]
> Right. I tried importing it from jsonedit.js, but then `onLoad` ends up being undefined. I think what is needed is a local overriding definition in the test files, but I was unable to make that work either.
I don't know what you tried, and you know this stuff better than I do, but did you try `require()`?

https://fjolt.com/article/javascript-export-import-node-js

**Comment by rogerl50** [comment]
> > Right. I tried importing it from jsonedit.js, but then `onLoad` ends up being undefined. I think what is needed is a local overriding definition in the test files, but I was unable to make that work either.
> 
> I don't know what you tried, and you know this stuff better than I do, but did you try `require()`?
> 
> https://fjolt.com/article/javascript-export-import-node-js

Based on https://nodejs.org/en/knowledge/getting-started/what-is-require/, I don't think require will do what's needed. It seems to apply only to modules, not individual variables or objects. In any case, I can't get it to work either.

**Comment by rogerl50** [comment]
The TestCafe tests use the old debug mode console output to see if the tests worked properly. This fails with the new debugger, as no debug info is output to the console. Simply writing the widget id and original text to the console and querying that also fails, but I'm not sure why. There are other errors emitted by the tests as well, which never get to the point of comparing checksums.

**Review by bjalder26 — APPROVED** [review]
Approving based on testing.  I think this is unlikely to cause issues, and is a heavily anticipated feature.  It could probably use a code review, but I think people will be happy to have this feature as soon as possible.

**Pull request merged**
