### PR TITLE
Public Library - Tweaks for Sashimi Dice

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
We played a few games and I made a few tweaks. Will probably make a few more. See commit messages for the actual changes.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2067/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR2067-pr-test`.

**Comment by 96LawDawg** [comment]
This breaks dice rolling.

**Comment by ArnoldSmith86** [comment]
🤣

**Review by 96LawDawg — APPROVED** [review]
Everything seems to work okay.  Approved.

**Pull request merged**
