### PR TITLE
removed "will-change: transform"

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This PR removes the CSS property `will-change` from widgets. I added it initially because it improves performance while dragging widgets in certain situations but it is not meant to be applied to hundreds of widgets. It causes a lot of other problems and I want to use this PR to test a few things and see if it improves overall.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3400/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
how should this be tested

**Comment by ArnoldSmith86** [comment]
Basically whenever you have rendering issues in a game (pile handle below cards for example), test it with this PR and report your findings here.

**Comment by bjalder26** [comment]
This appears to be the cause of the zoom problem in issue #71, so I linked it to this PR.

**Review by bjalder26 — APPROVED** [review]
This addresses a known issue, and I believe it also fixes the issue with rendering too many cards with a font that is too large.

It also fixes the rendering issue while zooming in this room: https://virtualtabletop.io/test

The same Apples to Apples file that 'breaks' this room (try clicking on the game list), doesn't appear to have the same problems on this test server.
https://virtualtabletop.io/jtsr

Test server: http://212.47.248.129:3400/Interitus

Since it fixes known bugs I'm approving of this PR.

**Review by robartsd — APPROVED** [review]
I see no issues with the code. May slightly degrade performance in some circumstances, but on the balance performance should be fine and applying this fixes known bugs.

**Pull request merged**
