### PR TITLE
add support for floats with `LABEL`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This is a bit more complicated because of float rounding issues. You do not want `0.100000001` to show on your labels. So this looks at how many decimal places your `LABEL` `value` has and then rounds the result to that many decimal places.

Please test and give feedback.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3919/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
I would need one example for this...

**Comment by ArnoldSmith86** [comment]
Compare the upper counter between http://212.47.248.129:3919/pr-test and https://virtualtabletop.io/xtvl.

**Review by RaphaelAlvez — APPROVED** [review]
Not really sure what is happening but this definitely fixes that bug

**Comment by ArnoldSmith86** [comment]
It was using `parseInt` before so it threw away decimal places of the given `value`.

Now it uses `parseFloat` and to get around rounding errors, it turns the `0.1` into a string, matches it against `/\..*$/` which gives the dot and all decimal places. So it counts the decimal places, turns it into a factor (so `10` for `0.1` or `1000` for `0.123`) for multiplying, then rounding and then dividing again.

Does that help?

**Comment by RaphaelAlvez** [comment]
> It was using `parseInt` before so it threw away decimal places of the given `value`.
> 
> Now it uses `parseFloat` and to get around rounding errors, it turns the `0.1` into a string, matches it against `/\..*$/` which gives the dot and all decimal places. So it counts the decimal places, turns it into a factor (so `10` for `0.1` or `1000` for `0.123`) for multiplying, then rounding and then dividing again.
> 
> Does that help?

It does. I did not see the parseInt. the rest of the code also became more clear

**Comment by ArnoldSmith86** [comment]
I think this will lead to rounding errors when _not_ using decimals. Maybe.

**Review by 96LawDawg — APPROVED** [review]
Tested a variety of values, decimals and integers, large and small numbers, negative and positive.  I did not notice any problems or rounding errors.

**Comment by bjalder26** [comment]
I think it would be slightly better if it looked at the number of decimal places in the label and rounded to that many decimal places instead so that you could "increment" 1.05 by 0.1 and get 1.15 (rather than 1.2), but that would require dealing with issue #399 as well, because otherwise the number of decimal places would change whenever you hit a zero in the last decimal place.

**Comment by 96LawDawg** [comment]
Interitus comment made me think of one other thing I didn't test.  If I type in the label 1.02, the label will not accept the zero.  Has nothing to do with this PR though.  Same behavior on production.  However, if I type 1.2 and then go back in between the decimal and the 2 and insert a 0, that works.

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
And nevermind on my approval.  Somehow I missed another obvious test.  Starting with a value of 7.3 and increases and decreases of 1.  Go up a couple of places and you get 8.3, 9.3, etc.  Then go back down and you get 7.3000000001.  Start with 7.2 go up and down and you get 7.199999999.  Not ideal.

**Comment by bjalder26** [comment]
> And nevermind on my approval. Somehow I missed another obvious test. Starting with a value of 7.3 and increases and decreases of 1. Go up a couple of places and you get 8.3, 9.3, etc. Then go back down and you get 7.3000000001. Start with 7.2 go up and down and you get 7.199999999. Not ideal.

I believe that actually brings us back to the issue I mentioned.  If we round based on the number of decimal places in the inc/dec, then it would go from 7.3 to 8 when the inc/dec is set to 1.  If we round based on the number of decimal places in the label, then when we go from 1.9 to 2 (inc/dec set to 0.1) it will then start rounding to the ones place instead of the tenths place.  In the PR right now it does not round when there is no decimal place in the inc/dec, which is why we are getting what you're seeing.

I THINK, we will need to pick one of those unless someone else has a clever solution.

**Comment by ArnoldSmith86** [comment]
I want to try to round to whatever of the two has more decimal places. And also round when there are no decimal places. Will update tomorrow.

**Comment by ArnoldSmith86** [comment]
Please test if the issues are fixed now.

**Review by 96LawDawg — APPROVED** [review]
This fixes all the rounding errors I was able to create yesterday.  I cannot seem to make it have any rounding errors no matter what I try.  Still an issue with trying to type 5.0 something in a label, but that is not related to this PR.  Approved through test.

**Review by rogerl50 — APPROVED** [review]
Code looks right (though unexpectedly complicated for a seeming simple problem!)

**Pull request merged**
