### PR TITLE
Update Several Tutorials

### PR DESCRIPTION
**Pull request by 96LawDawg**
Update to reflect changes from #1432 in FOREACH with range.

Added new example to Enlarge.

Added new Dragging tutorial to reflect changes from #1145.

Added new Color tutorial to reflect changes from #1443.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1496/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1496-pr-test`.

**Comment by 96LawDawg** [comment]
The Comparisons tutorial didn't make it through the UI update somehow.  The latest commit fixes that and adds it to this small group of tutorial updates.

**Review by RaphaelAlvez — APPROVED** [review]
approved

suggestion: enlarge card needs the basic. enlarge in cardDefaults vs in cardType

**Comment by 96LawDawg** [comment]
> approved
> 
> suggestion: enlarge card needs the basic. enlarge in cardDefaults vs in cardType

I agree.  But I don't see where the problem is.  Which deck?

**Comment by RaphaelAlvez** [comment]
> > approved
> > suggestion: enlarge card needs the basic. enlarge in cardDefaults vs in cardType
> 
> I agree. But I don't see where the problem is. Which deck?

I mean in general. there is no basic example of enlarge

**Pull request merged**
