### PR TITLE
new players get unique color

### PR DESCRIPTION
**Pull request by robartsd**
Ensures that new players get a color that is a different hue from the hues of existing player colors.

Easiest way to see new feature is to open an empty test room in a browser and look at the player list. Add additional players by repeatedly opening the room in a Incognito/In Private window then closing the window (in Chrome/Edge all Incognito/In Private windows share local storage, so all must be closed before reopening - did not test in Firefox).

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3558/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
Inspired by #555

**Comment by robartsd** [comment]
All TestCafe tests pass on my local server.

**Comment by robartsd** [comment]
Now TestCafe passed on GitHub but is still failing on my local server.

**Comment by robartsd** [comment]
I think I must have messed up my GitPod and local server environments somehow. Tests failed in GitPod, but passed when I opened a new GitPod workspace.

**Comment by ArnoldSmith86** [comment]
TestCafé tests also sometimes just fail.

**Review by ArnoldSmith86 — APPROVED** [review]
I won't try to understand the code but the result is a whole lot nicer than the status quo.

**Comment by robartsd** [comment]
> TestCafé tests also sometimes just fail.

The failures in those environments were consistent.

**Comment by robartsd** [comment]
Sorry @RaphaelAlvez , if all hues have been taken new players all get red again.

**Comment by 96LawDawg** [comment]
This also has the side effect of erasing the history of players that have been in a room.  Bug?  Feature?  Is this something we want?  I'm okay with that, but just pointing it out.

**Comment by ArnoldSmith86** [comment]
Not intended but something is weird. Are you sure it doesn't happen in production?

**Comment by 96LawDawg** [comment]
Well, one of my rooms on production server has a scroll bar with 50+ "guest" names.  Every time I go into the one on this test server, the names of others are gone and it's like the first time going into the room.  I don't know if that will mess anything else up (like your plan for timers).

**Comment by robartsd** [comment]
Empty rooms get deleted when everyone leaves. I don't think the player list gets removed on non-empty rooms.

If you want the algorithm to ignore a player entry because they will not come back to the room, make their color grey.

**Comment by robartsd** [comment]
Would be nice if there was a way to remove inactive players from rooms.

**Comment by 96LawDawg** [comment]
> Empty rooms get deleted when everyone leaves. I don't think the player list gets removed on non-empty rooms. 

Yeah.  I didn't even think about the room being empty.  That was the difference.  Same thing on the production server.  My bad.

**Comment by robartsd** [comment]
> I won't try to understand the code but the result is a whole lot nicer than the status quo.

Color conversion functions mostly shamelessly copied from StackOverflow (I did take enough time understanding them to throw away the parts I didn't care about). Here's a [Wikipedia article on calculating hue](https://en.wikipedia.org/wiki/Hue#Computing_hue_from_RGB).

**Comment by robartsd** [comment]
> > Empty rooms get deleted when everyone leaves. I don't think the player list gets removed on non-empty rooms.
> 
> Yeah. I didn't even think about the room being empty. That was the difference. Same thing on the production server. My bad.

If you want to clear the list for a room, backup the room to a VTT file, delete all games and widgets from the room, close all connections to the room. After confirming that the player list was cleared, restore the VTT file.

**Comment by bjalder26** [comment]
> Would be nice if there was a way to remove inactive players from rooms.

I don't know if this is exactly the same thing, but If you change your playerName to every inactive name in the room one by one, then they'll all go away.  I don't know if this has any unwanted side effects though, because I've only ever done it with Guest names from my own devices.

**Comment by robartsd** [comment]
> > Would be nice if there was a way to remove inactive players from rooms.
> 
> I don't know if this is exactly the same thing, but If you change your playerName to every inactive name in the room one by one, then they'll all go away. I don't know if this has any unwanted side effects though, because I've only ever done it with Guest names from my own devices.

Oh, yeah, there is that selective method.

**Comment by bjalder26** [comment]
I don't really understand why RGB is involved in this.  It seems to me that it would be easiest to designate regions of the hue in HSL then convert to hexcode.  However, maybe there is something I am missing.

https://stackoverflow.com/questions/36721830/convert-hsl-to-rgb-and-hex

**Comment by robartsd** [comment]
Hex is just and encoding of RGB. I calculate the hue for each existing player from the hex RGB, then find the largest gap in hue angles and choose a color for the new player in that gap (always using 100% saturation and 50% lightness), returning the color as hex RGB.

**Comment by robartsd** [comment]
> https://stackoverflow.com/questions/36721830/convert-hsl-to-rgb-and-hex

The HSL to hex part started with this answer, but I threw out the parts needed to output colors that are not 100% saturation and 50% lightness.

**Pull request merged**
