### PR TITLE
Update Piles Tutorial with Rank Pile Handle

### PR DESCRIPTION
**Pull request by Ingegneus**

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1652/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1652-pr-test`.

**Comment by 96LawDawg** [comment]
Cool example.  But (and I used to have this problem some), you brought other changed from your Fantasy Wars update into this.  You need to create a new branch on your local machine for each PR.  It seems you did create a new branch, but it wasn't clean; it wasn't based on the main branch.  It was based on an existing branch.  I don't know how to do any of that stuff in command lines.  I just use the Windows GUI with VSCode and it works.

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
You need to delete the Fantasy Wars commits or better yet, start over with a new branch based on main.

**Comment by 96LawDawg** [comment]
Also, whatever you did wrecked the existing card backs in the variant so the room looks broken because you can't see the card backs.

**Pull request closed without merging**
