### PR TITLE
Add A Simple Life to Public Library

### PR DESCRIPTION
**Pull request by 96LawDawg**
New game from @LexJudex (based on an original game from, and used with permission by, Clint Ghosn).

Ghosn

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1766/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1766-pr-test`.

**Comment by ArnoldSmith86** [comment]
"Carrot : Coin" - That is not a semicolon.

**Comment by 96LawDawg** [comment]
> "Carrot : Coin" - That is not a semicolon.

Fixed.

**Comment by ArnoldSmith86** [comment]
I'm learning and playing a game. I'll update this comment with my notes.

- upgraded tools aren't very clear without the PDF
- the first day is already crossed when starting - not there yet but I wonder if it ends with a cross on day 10 or if you have another (which would be my guess)
- spaces around dice emoji are not very consistent in the rules
- also 6🎲 sometimes represents "six dice" and sometimes "rolling a 6" - I'm pretty sure it's understandable though

**Comment by lexjudex** [comment]
> * upgraded tools aren't very clear without the PDF

I definitely agree. I'll look into adding tooltips to clarify those.

> * the first day is already crossed when starting - not there yet but I wonder if it ends with a cross on day 10 or if you have another (which would be my guess)

Your guess is correct, you get 10 full days, and you mark off day 1 to start the game. Maybe changing it so that the button says "Start Game" at first and changed to "New Day" after it's been pressed once could make it clearer.

> * spaces around dice emoji are not very consistent in the rules

Yeah I copy and pasted the rules from the PDF and tried to clean it up but it needs work, I can fix that.

**Comment by ArnoldSmith86** [comment]
BTW, this is total nitpicking. It works great.

**Comment by ArnoldSmith86** [comment]
> > * the first day is already crossed when starting - not there yet but I wonder if it ends with a cross on day 10 or if you have another (which would be my guess)
> 
> Your guess is correct, you get 10 full days, and you mark off day 1 to start the game. Maybe changing it so that the button says "Start Game" at first and changed to "New Day" after it's been pressed once could make it clearer.

I'd say it's clear enough. Why would there be ten days if you only get nine?

**Comment by 96LawDawg** [comment]
> * any reason why the dice don't do a full roll animation when starting a new day?

Yes, that's on me.  I will fix that after Lex is done making changes.

**Comment by 96LawDawg** [comment]
> I didn't read all the additions to the rules but it looks way better. I noticed a typo: "To do so, repeated process from Step 1".

Fixed this and a few other minor typos.

**Pull request merged**
