### PR TITLE
added COMPUTE

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Any thoughts?

Here's an example:

```JSON
{
  "func": "COMPUTE",
  "operation": "+",
  "operand1": 2,
  "operand2": 3,
  "variable": "result"
}
```

The valid operations can be seen in the diff. Pretty much any operator and quite a lot of [Math](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math), [String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String) and [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) functions.

### CODE REVIEW

**Comment by larkob** [comment]
Looks good to me. How about we call it CALCULATE? Unless we plan to eventually also support string-related functions - then we might as well call it TRANSFORM as a catch-all term.

**Comment by ArnoldSmith86** [comment]
CALCULATE might be better but for example doesn't cover the constants. But I guess that's fine.

I'm not really planning to add string functions to it but it can already be used to concatenate strings because that's what `"a" + "b"` does. It can also compare strings (`<`, `>`, `==` etc.).

**Comment by ArnoldSmith86** [comment]
You can play around with it here: http://212.47.248.129:8889/ukl9 (or any other room on that server)

**Comment by pwinckles** [comment]
> Looks good to me. How about we call it CALCULATE? Unless we plan to eventually also support string-related functions - then we might as well call it TRANSFORM as a catch-all term.

It already does support strings due to the nature of javascript. I added an example to the demo table.

**Review by UltimateGeek — COMMENTED** [review]
Feels like a companion change we need is some way to adjust the resulting value produced by MATH when putting it into a label. Maybe at least support `maximumSignificantDigits` from `Intl.NumberFormat()`?

```json
{
  "func": "MATH",
  "operation": "/",
  "operand1": 2,
  "operand2": 3,
  "variable": "result"
},
{
  "func": "LABEL",
  "label": "myLabel",
  "significantDigits": 3,
  "applyVariables": [
    {
      "parameter": "value",
      "variable": "result"
     }
  ]
}
```

**Comment by rogerl50** [comment]
Perhaps `COMPUTE` would be a good choice for a name, particularly since it can be used with strings.

**Comment by ArnoldSmith86** [comment]
I think I'll rename it to `TRANSFORM` or `COMPUTE` (go vote!) and just add some string handling to it.

**Comment by rogerl50** [comment]
Between those two I definitely vote for `COMPUTE`. It's shorter, and `TRANSFORM` seems too general.

**Comment by larkob** [comment]
I second `COMPUTE`. This operation can also be used for setting a variable to a value (like x=1) without any mathematical transformations, so "compute" sounds right.

**Comment by ArnoldSmith86** [comment]
API Test

**Comment by ArnoldSmith86** [comment]
You can play around with it here: http://212.47.248.129:3026/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
You can play around with it here: http://212.47.248.129:3026/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3009/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3010/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3028/pr-test (or any other room on that server)

**Review by UltimateGeek — APPROVED** [review]
Thank you for adding the check for finite :-)

**Comment by 96LawDawg** [comment]
I put together a prototype tutorial for this.  See http://212.47.248.129:3026/DraftTutorial.  It uses labels for user input on 2 values and the operand.  * / and - all work as expected.  + acts strange when using decimal values.  It looks like it is concatenating the values rather than adding them.  I have not checked out any more advanced functions yet.

**Comment by 96LawDawg** [comment]
So an update to my math tutorial.  The higher functions (exponents, tangent, square root, etc. seem to work fine.  However, addition still seems to be a problem. Even using an INPUT function and setting the type to number still treats it as a string.  So "3+3=33."  I think addition (or figuring out how to treat a string as a number) needs work.

**Comment by ArnoldSmith86** [comment]
Damn, that's an awesome idea! And you're completely right; I'll make it treat number strings as numbers. At first for everything and then it'll need some more testing.

**Comment by 96LawDawg** [comment]
That fixed the addition for number "strings."  Still need to work on some tests for arrays and actual string concatenation.

**Comment by 96LawDawg** [comment]
Okay, this is just damn strange.  Testing addition of decimals.  0.7 + 0.2 = 0.89999999999.  But 0.8 + 0.1 = 0.9.  If we have to test every possible math value, we'll never get this finished.  I don't remember much from math classes decades ago, but I think there might be an infinite number of numbers.

**Comment by ArnoldSmith86** [comment]
Yeah, that's normal for computers. We need a way to display those numbers better. UltimateGeek suggested `maximumSignificantDigits` from `Intl.NumberFormat()` but I think much of that construct is pretty new so maybe not supported well enough.

You can fiddle with `round` but doing `round(x*100)/100` for two decimal places is already pretty complicated with buttons...

**Review by RaphaelAlvez — APPROVED** [review]
This looks pretty good. LawDawg Made a test room and everything looks ok

**Pull request merged**
