### PR TITLE
Add Capture the Flag, Interrogation; other updates

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:
- Capture the Flag. New game by LawDawg. Similar to Stratego
- Interrogation. New game by Ingegneus. Similar to Guess Who?
- Bulls. Fixed movable “Get” buttons

Public Tutorials:
- Functions – INPUT: New tutorial with 1 variant.
- Functions – MOVEXY: New tutorial with 1 variant.
- Functions – SELECT: Substantially revised. Now has 3 variants: basic, relation, and mode and rank.
- Routines. Fixed a couple of typos.
- Piles. Added comment about z-index:-1 in first variant. Addd mousewax cube example in last variant.

Public Assets:
- Symbols: New asset with 2 variants.
- Universal Game Symbols. Asset removed.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4052/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Changed files successfully loaded from new library.json file.

**Comment by bjalder26** [comment]
Suggestions:
INPUT: 
set movable to false for label that begins 'INPUT is used to prompt a user...', and all labels under buttons
Maybe even just set everything to movable: false, movableInEdit: false.

MOVEXY:

- "Cards moved using MOVEXY will form piles."
        Maybe that be "Cards moved to the same location using MOVEXY will form piles."?  Or maybe that is obvious.
- Get rid of the move button under the second MOVEXY button.
- Maybe set the recall & shuffle face to 1 for each recall button.
- For the 3rd MOVEXY button, you could also use 0 instead of 999.  I suppose either is fine though.
- For the 4th button it might be useful to note that the widgets must match the dropTarget, otherwise they won't be moved (though maybe this is already in the MOVE tutorial).
- Maybe set everything to movableInEdit: false.

**Comment by 96LawDawg** [comment]
> Suggestions: INPUT: set movable to false for label that begins 'INPUT is used to prompt a user...', and all labels under buttons Maybe even just set everything to movable: false, movableInEdit: false.
> 

Done

> MOVEXY:
> 
> * "Cards moved using MOVEXY will form piles."
>   Maybe that be "Cards moved to the same location using MOVEXY will form piles."?  Or maybe that is obvious.

Changed

> * Get rid of the move button under the second MOVEXY button.

I don't know what you are talking about here.  I don't see a second move button.

> * Maybe set the recall & shuffle face to 1 for each recall button.

Done

> * For the 3rd MOVEXY button, you could also use 0 instead of 999.  I suppose either is fine though.

Changed to 0; mentioned using 999.

> * For the 4th button it might be useful to note that the widgets must match the dropTarget, otherwise they won't be moved (though maybe this is already in the MOVE tutorial).

That only applies to MOVE.  MOVEXY does not put anything in a holder so dropTarget is not relevant.

> * Maybe set everything to movableInEdit: false.

Done.

**Comment by 96LawDawg** [comment]
The SELECT tutorial was substantially revised.  The TestCafe use of this is largely insignificant.  Because of the way the new variants are set up, we can't really test multiple buttons.  So I changed it to test only one that is less commonly used (add mode).  I know some of the other TestCafe tests already cover normal set mode SELECTS in various places.  No harm to leave SELECT tutorial in the cafe, but it doesn't add much.

**Comment by bjalder26** [comment]
> > * Get rid of the move button under the second MOVEXY button.
> 
> I don't know what you are talking about here. I don't see a second move button.

image

There's a MOVE button under the second MOVXY button (counting from the left).  The widget id is `jkmt1`.

**Comment by 96LawDawg** [comment]
> There's a MOVE button **under** the second MOVXY button (counting from the left). The widget id is `jkmt1`.

Thanks.  Done.

**Comment by bjalder26** [comment]
Suggestions:
SELECT Basic:
'name(s) of the widgets' to "name(s) of the widget(s) => I know, really nit picking
Why the offscreen holder?
image

SELECT Relation: 
has the same offscreen holder

SELECT Mode & Sort: 
has the same offscreen holder

**Comment by 96LawDawg** [comment]
> Suggestions: SELECT Basic: 'name(s) of the widgets' to "name(s) of the widget(s) => I know, really nit picking

Done

Offscreen holders were just a leftover from something else.  Deleted them.

**Comment by bjalder26** [comment]
No notes on functions, piles, symbols or universal game symbols.  They look good to me.  Capture the flag looks good to me.  I noticed that SOME of the tiles on the sideline can be flipped by the opposing player, but in an actual game they would captured and it would be obvious what their number is from their position, so I don't think that's an issue.

**Comment by 96LawDawg** [comment]
> No notes on functions, piles, symbols or universal game symbols. They look good to me. Capture the flag looks good to me. I noticed that SOME of the tiles on the sideline can be flipped by the opposing player, but in an actual game they would captured and it would be obvious what their number is from their position, so I don't think that's an issue.

I'm not sure what you mean.  Before the game starts, the opposing players can't see the other sideline tiles.  After the game starts and a piece is captured, it is visible to everybody.  When and where did you encounter a problem?

**Comment by bjalder26** [comment]
> I'm not sure what you mean. Before the game starts, the opposing players can't see the other sideline tiles. After the game starts and a piece is captured, it is visible to everybody. When and where did you encounter a problem?

I wouldn't say it was a problem.  After the game starts it seems like some of the captured pieces can be flipped, and others can't.  I didn't see it as a problem, but didn't know if it was intentional.

**Comment by 96LawDawg** [comment]
Okay.  I think I know what you mean.  None of the pieces can be "flipped" but if you move them slightly when they are upside down in the side holders, they will turn face up.  But not the bombs and flags, because they can't be moved by opponents.  But none of that will happen in a real game.  If you set up all the pieces for both sides (in separate browsers when seated), then none of that will ever happen because pieces are auto-captured, moved to the side, and flipped face up.

**Comment by bjalder26** [comment]
At this point I've played with everything to some degree.  I think this just needs a hash update for select.

**Review by bjalder26 — APPROVED** [review]
I believe everything is good to go in this PR.  Approving through testing.

**Pull request merged**
