### PR TITLE
added link to game

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This PR enables the `Share Link` entry of the game menu for public library games as well. Pressing it (for any game) now produces a URL like https://test.virtualtabletop.io/PR-1908/game/agra for public library games or https://test.virtualtabletop.io/PR-1908/game/mykke926/red-rising for custom games.

The URL then looks like this and allows players to easily add the game to a new room:

image

- [x] The overlay disappears immediately sometimes. Reloading usually helps. **Apparently this happens every time on the PR test server and reloading doesn't help.**
- [x] Re-sharing a shared game returns the raw VTT file URL (`.../s/...` instead of `.../game/...`).
- [x] Make it work with public library games.
- [x] Make it work with tutorials and assets. Should just need changing the filter box.
- [x] Improve the "Loading room" thingy.
- [x] Layout fixes for viewport sizes of the welcome overlay.
- [x] Replace hard-coded room ID `s91j` by a randomly generated but unused room ID.
- [x] Replace hard-coded `Animal Race` in the text by the actual game name.
- [x] Using the Back button of the browser restores the `/game/` URL but doesn't show the overlay again.
- [x] Fix TestCafé. (Fixed in #2010.)
- [x] `ensureRoomIsLoaded(req.params.room || req.params.id)` loads the share ID as a room. This needs refactoring.
- [x] Remove "user-generated content" warning for public library games.
- [x] Show game name in `<title>`.
- [x] Add Open Graph support for game URLs.
- [x] The Close button doesn't work yet.
- [x] Text on the Share Link overlay doesn't make a lot of sense for public library games.
- [x] `COPY TO CLIPBOARD` should probably be called `SHARE` now.
- [x] Handle non-existent games.
- [x] Empty rooms should show the Game Shelf again.
- [x] Share button breaks layout when clicking.
- [x] Enable ENTER when entering name and room.
- [x] Changing your name from the overlay does not work.
- [x] A way to get away from "Game not found".
- [x] Fix `/game/crafty2`.
- [x] Make `/tutorial` only load tutorials. Same for games.
- [x] Fix code test error.
- [ ] Sometimes the newly entered room reloads immediately.
- [x] Looks like I broke adding the game to the new room.
- [x] Custom games with no metadata break the layout a bit.
- [x] The message about "user-generated content" breaks has broken layout.
- [x] Sharing a TTS import shows the workshop URL instead.
- [x] Loading a room doesn't highlight "Active Game" in the toolbar anymore.
- [x] Game details are not always displayed after "Create Room".
- [x] https://test.virtualtabletop.io/PR-1908/tutorial/css shows wrong (generic) link preview in Discord.
- [x] https://test.virtualtabletop.io/PR-1908/qvka also doesn't show its image in the Discord link preview (might be unrelated to this PR). -> Looks like Open Graph doesn't like SVG images.
- [ ] Linking to a variant would be useful for tutorials. Should probably be a separate PR though.
- [x] Sharing a TTS import now doesn't create a link to the original (VTT) game. Probably the same for PCIO imports.
- [x] Tutorial overlay should probably say "tutorial" instead of "game".
- [x] The star number is broken for the smallest viewport.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1908/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1908-pr-test`.

**Comment by 96LawDawg** [comment]
When you get the "Game not found!" text, you are stuck there since the sidebar is disabled.  Recommend adding a button under the notification that takes you to a random room.  Maybe say: "Click here to see games in the public library" or something like that.

If I enter a link like /game/crafty it works.  If I enter a link like /game/crafty2, I get the loading screen instead of the game not found screen.  But if I completely make up something like /game/foobar/ I get the game not found.  So something about adding characters after a legit game messes it up.

Entering /game/css loads the css tutorial.  So does /tutorial/css.  Entering /game/checkers or /tutorial/checkers loads the checkers game.  Probably not a problem until a tutorial has the same name as a PL game, but should probably be fixed.

Changing your name from the overlay does not work. It lags one entry behind.  I started as LawDawg on the server.  Tried to change my name to Mike.  Didn't work.  Tried to change my name to TestMe.  Then it was Mike. Changed my name to something else, and then it was TestMe.  Also, while it was lagging behind on changing name, it did some weird stuff with the cursor in the room like I was actually playing for 2 players.

Everything else seems fine.

**Comment by 96LawDawg** [comment]
You fixed the player name, but it doesn't load the selected game.  After pressing Play on the overlay, you just get dumped into a generic room without the PL game pre-selected.

**Comment by ArnoldSmith86** [comment]
You use Share Link from the menu of the game.

**Comment by 96LawDawg** [comment]
> You use Share Link from the menu of the game.

Got it.  So just a hyphen.  I was testing by typing in names directly into the URL.  Faster and easier to break for testing purposes.  Forgot to go back and click on Share.  Thanks.

**Comment by 96LawDawg** [comment]
> Still think that they should be case insensitive? I think I would prefer if everybody uses the same URL for the same game.

Doesn't really matter to me.  Leave it as is.

**Comment by ArnoldSmith86** [comment]
The layout isn't done yet but it's pretty close to what I imagined on most viewport sizes.

**Comment by ArnoldSmith86** [comment]
Alright. I'm done. Please review.

If you know how to reproduce the last remaining task, I would be thankful. Otherwise we'll have to see if it's an issue in production. :grin:

**Comment by 96LawDawg** [comment]
For custom games, if you copy and paste a link into a new browser tab everything works.  But if you paste into the same browser tab again, you get the new overlay to show the option to set the room name and player name, but after clicking CREATE ROOM, when you go to the new room, the room details sidebar with the play button is not opened.

**Comment by 96LawDawg** [comment]
Everything else works as expected.  I have never seen (and cannot duplicate) the problem of the room reloading.  I assume that is what you were asking about as the "last" undone item.  But the last one is actually TTS imports.  That one happens every time.  Not sure that is a really big deal because it would be strange for a user to share a raw TTS import that had not been tweaked and saved as a game.

**Comment by ArnoldSmith86** [comment]
Yeah, I found and added the TTS thing later. Fix is already on the way. Will look at the other issue you found soon.

Thanks for testing!

**Comment by ArnoldSmith86** [comment]
> But if you paste into the same browser tab again, you get the new overlay to show the option to set the room name and player name, but after clicking CREATE ROOM, when you go to the new room, the room details sidebar with the play button is not opened.

Please re-test. I hope it's fixed now.

**Comment by 96LawDawg** [comment]
> Please re-test. I hope it's fixed now.

Works.

**Review by 96LawDawg — APPROVED** [review]
Approved through lots of testing.  Everything except for the last couple of unchecked items on the to-do list have been tested as best as I can.  Anything else at this point is just a nice to have incremental improvement.  Merge when you are ready.

**Pull request merged**
