### PR TITLE
adds css variables to holders

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
As requested in #597

DT stands for dropTarget

 --wcBackground: #ffffff;
  --wcBackgroundDT: var(--wcBackground);
  --wcBorderLight: #d8d8d8 #ccc #ccc #d8d8d8;
  --wcBorder: var(--wcBorderLight);
  --wcBorderDT: #333;

--wcBorderLight is there because of a future style sheet PR

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3923/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
Looks like it works.

**Comment by 96LawDawg** [comment]
Everything works except for one thing, which changes behavior from the production server.  Whenever I defined the border thickness, onhover broke.  That doesn't happen on production and should be fixed.

**Comment by bjalder26** [comment]
> Everything works except for one thing, which changes behavior from the production server. Whenever I defined the border thickness, onhover broke. That doesn't happen on production and should be fixed.

I'm thinking that this:
```js
.widget.droppable.droptarget {
  background-color: var(--wcBackgroundDT);
  border-color: var(--wcBorderDT);
}
```
Should be changed to this:
```js
.widget.droppable.droptarget {
  background-color: var(--wcBackgroundDT);
  border-color: var(--wcBorderDT) !important;
}
```

**Comment by RaphaelAlvez** [comment]
> > Everything works except for one thing, which changes behavior from the production server. Whenever I defined the border thickness, onhover broke. That doesn't happen on production and should be fixed.
> 
> I'm thinking that this:
> 
> ```js
> .widget.droppable.droptarget {
>   background-color: var(--wcBackgroundDT);
>   border-color: var(--wcBorderDT);
> }
> ```
> 
> Should be changed to this:
> 
> ```js
> .widget.droppable.droptarget {
>   background-color: var(--wcBackgroundDT);
>   border-color: var(--wcBorderDT) !important;
> }
> ```

Thanks for pointing this out. Always good to receive problems already solved

**Comment by RaphaelAlvez** [comment]
> Everything works except for one thing, which changes behavior from the production server. Whenever I defined the border thickness, onhover broke. That doesn't happen on production and should be fixed.

added interitus suggestion. works for me now.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Comment by bjalder26** [comment]
I thought I would make a rough draft for the wiki.  Of course, feel free to change anything.

| Property  | Default value       | Description           |
| --------  | ------------------- | --------------------- |
| css | null                | Same property as in [the global properties](#global-properties-for-every-widget) but with different css variables. `--wcBackground` controls the background color of the holder, and defaults to `#ffffff`. `--wcBackgroundDT` controls the background color when a droppable widget is hovering over the holder, and it defaults to `var(--wcBackground)`. `--wcBorder` controls the color of the border and defaults to `#d8d8d8 #ccc #ccc #d8d8d8`. `--wcBorderDT` controls the color of the border when a droppable widget is hovering over the holder, and defaults to `#333`. An example is `"css": "--wcBorder: green; --wcBorderDT: red; --wcBackground: lightgrey; --wcBackgroundDT: grey;"`|

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
This changes border colors for buttons inside holders (for example the default shuffle button).

**Comment by bjalder26** [comment]
> This changes border colors for buttons inside holders (for example the default shuffle button).

I believe children always inherit the css of their parents.  We ran into this issue before appending a button to a label (or maybe it was a holder).

If the button has their css explicitly set, then this won't happen.
image
I'm not sure what the proper solution to this issue is though.

**Comment by bjalder26** [comment]
In Flora the background goes white when you move cards.
image

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
I figured out what is going on in Flora (and Dominos).  The entire room is a transparent widget.  This PR is messing with `"classes":"transparent"` in a disruptive way.  Smaller demo in the pr-test room in the Unnamed variant.  There is a transparent holder on the small Chinese Chess board.

**Comment by ArnoldSmith86** [comment]
If it doesn't cause major issues, I'd prefer to use #951 instead of this. If it does, we can always reopen this.

**Pull request closed without merging**
