### PR TITLE
PL Tutorial JSON Operations - Add 2 new variants

### PR DESCRIPTION
**Pull request by 96LawDawg**
This adds two examples of how to `fetch` and `parseJSON` within VTT.  The first example shows how to retrieve scores from another room and keep them in a master scoreboard.  The second example is a spectator room that allows observers to view the hand cards of the participants of the game.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1897/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1897-pr-test`.

**Comment by ArnoldSmith86** [comment]
Are you using a different font or something?

image

**Review by ArnoldSmith86 — APPROVED** [review]

**Comment by 96LawDawg** [comment]
I guess I forgot to check a box on Photopea.  I think I fixed it.  Look at the new html tutorial as well.  It looks right on my screen but maybe I messed that one up also.

**Comment by 96LawDawg** [comment]
The HTML library image was also messed up.  Fixed.

**Pull request merged**
