### PR TITLE
Update holder after children sorted in collection

### PR DESCRIPTION
**Pull request by robartsd**

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3576/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
This works as intended.  I tested it using the game that I was having the problem with and it works now.  But David also suggested I test it with owner arrays.  I did that it it doesn't work.  SORT on holders (on production server) does work with owner arrays.  But this solution for SORT on collections does not work with owner arrays.

**Comment by robartsd** [comment]
Primary use case seems to be SORT for one player's hand only. Would be nice to support that by adding an "owner" property to "SORT" that is used with holder to limit the sort to a particular player.

```json
"...Routine": [
  {
    "func":"SORT",
    "holder":"hand",
    "owner":"${playerName}"
  }
]
```

**Comment by robartsd** [comment]
> This works as intended. I tested it using the game that I was having the problem with and it works now. But David also suggested I test it with owner arrays. I did that it it doesn't work. SORT on holders (on production server) does work with owner arrays. But this solution for SORT on collections does not work with owner arrays.

Can you be more specific about the differences between production and this PR?

This PR currently should update the holder after a collection sort in the exact same way that the holder is updated after sorting the entire holder. The only difference should be that cards outside the collection did not get an update to their 'z' values.

**Comment by 96LawDawg** [comment]
> Can you be more specific about the differences between production and this PR?
> 
> This PR currently should update the holder after a collection sort in the exact same way that the holder is updated after sorting the entire holder. The only difference should be that cards outside the collection did not get an update to their 'z' values.

This PR fixes the problem for collection sorting.  On the production server, sorting does not work on collections, as described in the issue.  Now it does.  The behavior for holders on production and this PR are the same (they both work).

What I was talking about with my last comment was specifically owner arrays in collections.  On this PR, sorting a collection with an owner array does not change the z values.  You don't get the visual shift I showed in the images before.  I also checked the actual z values and they don't change.  On production, there is a change in z values (with a collection involving an owner array).

**Review by ArnoldSmith86 — APPROVED** [review]
I didn't test it but the code looks fine to me.

It's probably a good idea to only look at unique parents though. No need to call updateAfterShuffle 100x on the same holder.

**Comment by robartsd** [comment]
> It's probably a good idea to only look at unique parents though. No need to call updateAfterShuffle 100x on the same holder.

I did think about this, but I realized that the w function was already taking care of it:
```js
    async function w(ids, callback) {
      for(const a of widgetFilter(w=&gt;toA(ids).indexOf(w.get('id')) != -1))
        await callback(a);
    }
```
Receives an array of ids then loops through the widgets collection triggering callback for each widget with an id found in the list. Should only fire once per widget regardless of number of times the id is in the array.

**Comment by ArnoldSmith86** [comment]
Ah, nice. Didn't look at the function.

**Comment by robartsd** [comment]
> > Can you be more specific about the differences between production and this PR?
> What I was talking about with my last comment was specifically owner arrays in collections. On this PR, sorting a collection with an owner array does not change the z values. You don't get the visual shift I showed in the images before. I also checked the actual z values and they don't change. On production, there is a change in z values (with a collection involving an owner array).

This is perplexing. I can't see a reason for this difference in behavior.

**Comment by robartsd** [comment]
> > > Can you be more specific about the differences between production and this PR?
> 
> > What I was talking about with my last comment was specifically owner arrays in collections. On this PR, sorting a collection with an owner array does not change the z values. You don't get the visual shift I showed in the images before. I also checked the actual z values and they don't change. On production, there is a change in z values (with a collection involving an owner array).
> 
> This is perplexing. I can't see a reason for this difference in behavior.

The routine in the test room is failing to SELECT the cards that have owner set to an array. Would be useful to have a `contains` relationship for SELECT. As I suspected, when rearrange children files, the cards with owner arrays are arranged separately from the cards with individual ownership.

**Pull request merged**
