### PR TITLE
Revert "sanitize room, state and variant IDs to prevent file system breaches"

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Reverts ArnoldSmith86/virtualtabletop#145

I don't understand the problem yet but this is the most likely culprit for #157.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3159/pr-test (or any other room on that server)

**Review by RaphaelAlvez — APPROVED** [review]
I'm approving this based on the feedback received after the merging.
If the bugs continues then we can maybe discard these PR as the reason.

**Comment by ArnoldSmith86** [comment]
I think it's actually unrelated.

**Comment by ArnoldSmith86** [comment]
I'm >90% sure that #145 was not responsible for the crashes. So I'm closing this.

**Pull request closed without merging**
