### PR TITLE
fixed that removing an update link from a variant would lead to room resets (fixes #169)

### LINKED ISSUE #169: Lost everything in my main room
I wanted to get an empty board so I got the Unicode assets as a starting point. I then went into the metadata and erased everything. I guess the file was then totally empty and when I pressed play everything was erased. Even other games. 

I guess that not such a big problem in my case but that a big bug

image

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
When removing the update link, it will now download the current state of that link to a static file like any other variant.

This also _finally_ introduced a `variantFilename` to `room.mjs` so the structure and character checking isn't duplicated five times.

So please test adding/loading/removing variants/states a bunch.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3172/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Whoops, I meant to merge those two commits. Oh well...

**Comment by 96LawDawg** [comment]
So I wanted to test this.  I didn't know if the behavior on the PR test servers would be the same as on the live server, so I started with an older PR test server (#170 for updating the library).  When I did what Raphael and I did last night (removing update link from a room), the test server broke.  I wasn't even in the same room that everybody uses by default; I had created a new room.  Now nobody can test that PR on that test server.  I never even got around to testing it on this PR test server.

**Comment by ArnoldSmith86** [comment]
I restarted the server. The PR test servers don't restart themselves when they crash.

**Review by 96LawDawg — APPROVED** [review]
Verified through test.  Did not evaluate the code.  This works to prevent room reset when the update link is removed.

**Review by RaphaelAlvez — APPROVED** [review]
Tested and approved

**Pull request merged**
