### PR TITLE
added activePlayers as a preset variable to buttons (fixes #91)

### LINKED ISSUE #91: Expose an array of all active player names as button variables
Now that `COMPUTE` is merged, this could be used to iterate through all players.

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This adds the variable `activePlayers` to all buttons. Please play around with it to see if you can actually turn this into something useful already or if we're missing some array features for it.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3093/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
I tested this using a VPN to get a different player ID.  I don't know if it was that or if there is a problem with the code, but in the debug screen, there are multiple instances of me (Guest125 was how I entered; Guest 469 was through the VPN; Guest74 was through an iPad).  Pic1.  The player list menu button showed the correct information. Pic2.  The repeats increased after I closed the VPN connection.  Pic3.

Debug List

Player List

Debug List 2

**Comment by robartsd** [comment]
> I tested this using a VPN to get a different player ID. I don't know if it was that or if there is a problem with the code, but in the debug screen, there are multiple instances of me (Guest125 was how I entered; Guest 469 was through the VPN; Guest74 was through an iPad). Pic1. The player list menu button showed the correct information. Pic2. The repeats increased after I closed the VPN connection. Pic3.
> 
I don't think the problem is with the code in this pull request. I think this code is exposing the values that are being repeated in the meta message from the server. The player overlay lists players received in a meta message as args.meta.players, then checks against activePlayers; the activePlayers variable lists players received in a mete message as args.activePlayers.

**Comment by robartsd** [comment]
room.mjs keeps a list of player objects (connect, name, room) that gets added to every time a player connects. Different connections with the same player name are possible. When the player object is added, the room's meta.players list is checked for an entry under that player name and one is added if needed. The player name is build using this list received in the meta message. The activePlayers variable is repeating player names if there is more than one connection for that player that has not been closed.

**Comment by ArnoldSmith86** [comment]
Yeah, names can occur more than once if they connected from multiple devices/tabs. I didn't think about that when implementing this pull request. For the intents of this button variable it's probably better to filter the duplicates.

**Comment by robartsd** [comment]
> Yeah, names can occur more than once if they connected from multiple devices/tabs. I didn't think about that when implementing this pull request. For the intents of this button variable it's probably better to filter the duplicates.

Any reason not to filter at sendMetaUpdate in room.mjs?

**Comment by ArnoldSmith86** [comment]
Well, the player overlay probably has to know about it. Right now if you rename yourself to another active player (and you might want to in order to switch devices) your entries in the player overlay get merged into one.

The information about multiple devices for one player could then be used to perform some kind of split operation to turn two players with the same name into two players with different names again.

I use this pretty often when playing on the PC and then I have to switch to the phone. I can enter the same name and have my hand cards waiting for me.

**Comment by robartsd** [comment]
> Well, the player overlay probably has to know about it. Right now if you rename yourself to another active player (and you might want to in order to switch devices) your entries in the player overlay get merged into one.
> 
> The information about multiple devices for one player could then be used to perform some kind of split operation to turn two players with the same name into two players with different names again.
> 
> I use this pretty often when playing on the PC and then I have to switch to the phone. I can enter the same name and have my hand cards waiting for me.

sendMetaUpdate is only providing a list of player names:

`  sendMetaUpdate() {
    this.broadcast('meta', { meta: this.state._meta, activePlayers: this.players.map(p=>p.name) });
  }
`

a player rename is sent to the server without checking for multiple entries in activePlayers:

`    $('.playerName', entry).addEventListener('change', function(e) {
      toServer('rename', { oldName: player, newName: e.target.value });
    });
`

I don't think the client is doing anything with repeated values in activePlayers.

**Comment by ArnoldSmith86** [comment]
Not yet. I'm saying the player list overlay **should** do something with it in the future because right now it's very hard to rename a player without renaming another one with the same name.

**Comment by robartsd** [comment]
> Not yet. I'm saying the player list overlay **should** do something with it in the future because right now it's very hard to rename a player without renaming another one with the same name.

I have noticed this. I think currently one would need to disconnect, clear cookies and reconnect as a new guest. It also seems impossible to play from the same device under different player names in different rooms.

**Review by UltimateGeek — APPROVED** [review]

**Review by robartsd — APPROVED** [review]
Looks good to me.

**Pull request merged**
