### PR TITLE
ignore trailing commas in JSON editor

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This PR makes the JSON editor automatically remove (ignore) trailing commas. Something like this:

```JSON
{
  "id": "resetGame",

  "x": 6,
  "y": 6.5,
  "width": 60,
  "height": 60,
}
```

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:1121/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
Code looks okay to me. If I'm reading the regex correctly, the trailing comma to ignore must be at the end of a line and the following line must contain only a `}` or `]` (optionally preceded by spaces and/or followed by a comma) for the comma to be ignored. I'm assuming that this is primarily intended to make copy and paste a bit more forgiving.

**Comment by ArnoldSmith86** [comment]
Yeah, I'm not sure if this will be very useful. It might be better if it also inserts the comma you mentioned:

```
  }
  {
```

@mousewax What do you think? (He mentioned this when I asked him about feature requests.)

**Review by RaphaelAlvez — APPROVED** [review]
tested in multiple places an extra comma could cause a problem. Approved. please merge this because I hate this.

If you can think of more regex to about other mistakes I would like to see them implemented. (example: missing commas, missing " " in variable in routines' functions (I think I have an issue for that))

**Pull request merged**
