### PR TITLE
PL Update Carnival with Automatic Scoring

### PR DESCRIPTION
**Pull request by 96LawDawg**
Adds a button (and updates the instructions) for automatic scoring.

You can test this by just dragging cards into the seat areas and pressing the button.  No need to actually sit in seats or play the game.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1991/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1991-pr-test`.

**Comment by 96LawDawg** [comment]
2 player scoring fixed

**Comment by ArnoldSmith86** [comment]
Scoring seems to work fine.

Some notes (not necessarily requests):
- Sorting of the second row is still weird. Top row goes left to right and then it continues right to left in the second row.
- Would be nice if it sorts the rows when dropping the final cards in there.
- Some kind of indication of the last round would be nice.

**Review by ArnoldSmith86 — APPROVED** [review]

**Comment by 96LawDawg** [comment]
> Some notes (not necessarily requests):
> 
> * Sorting of the second row is still weird. Top row goes left to right and then it continues right to left in the second row.

Done

> * Would be nice if it sorts the rows when dropping the final cards in there.

Mostly done. If you drop the card into the correct top or bottom row it works.  It was more complicated than it was worth to try to move a card between rows.

> * Some kind of indication of the last round would be nice.

Done.  The scoreboard button is hidden by default.  It now appears in the room to indicate the last round (updated instructions to reflect that).

**Pull request merged**
