### PR TITLE
updated ws to 8.2.0

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Supercedes #732. It needed minor code changes to make the update work.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3733/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
I did a quick test on the test server and the websocket synchronization seems to still work.

Could use some testing on mobile and browsers other than Firefox but I think this is pretty safe to merge.

**Review by 96LawDawg — APPROVED** [review]
I have no idea what this does or how to test it.  But I'll approve it based on your say-so.

**Review by 96LawDawg — APPROVED** [review]
Looks like I have to approve it again after merging??  Done.

**Pull request merged**
