### PR TITLE
added `fetch` compute function

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Downloads a URL, returns a string. This required compute stuff to be async so I added a bunch of `async` and `await`. Might have broken everything everywhere.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1852/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1852-pr-test`.

**Comment by 96LawDawg** [comment]
Just a quick test shows that all the old stuff seems to be working.  TestCafe passing is also a good sign.

I took Tavo's test from: https://virtualtabletop.io/nrd4 and changed it so it `fetch`ed the external URL at https://arkhamdb.com/api/public/deck/3241635.json.  Worked fine.

**Comment by ArnoldSmith86** [comment]
Added the most basic example to the test room.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Pull request merged**
