### PR TITLE
Replace "ghetto" by "legacy" in UI

### PR DESCRIPTION
**Pull request by rogerl50**
Change #ghetto-link to #legacy-link in three places; changed the phrase "in an advanced" editor to "in the legacy editor".

Change link in room.html to legacy-editor.htm.

### CODE REVIEW

**Comment by rogerl50** [comment]
It's hard to test this before it is merged, since the legacy editor receives just the room id and assumes (I think) virtualtabletop.com as the URL.

**Review by 96LawDawg — APPROVED** [review]
This looks right to me, but would appreciate another review.  Cannot text in a PR server (this has always been a limitation of the legacy editor and PR test rooms.

**Comment by 96LawDawg** [comment]
Now line 150 just needs to be changed to [https://virtualtabletop.io/legacy-editor.htm](https://virtualtabletop.io/legacy-editor.htm) and I think all references to Ghetto will be replaced.

**Review by ArnoldSmith86 — APPROVED** [review]
Looks fine to me.

**Pull request merged**
