### PR TITLE
updates holder alignment on property change

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
@96LawDawg see if that's what you wanted in #1198

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1261/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
No.  This does not fix the situation where `dropTarget` changes after cards are already in the holder.  Look at the change I made to your demo room.  Add a card with the right suit.  Click the button to cycle to another suit.  Add a card with that suit and you will see the problem.

**Comment by 96LawDawg** [comment]
I agree it is an improvement on the base code.  I tested it in the room you made and I also tested it with a hand.  That worked fine.  I tested it on a couple of games with complex hand structures like Yoink and Tutti Frutti.  Worked fine there.  The only issue, and this probably won't surprise you, is with piles.  If you have a holder with a pile (stackOffsetX:0) then spread it out, the pile handle is still there.  Not sure what behavior I would expect, but it seems strange.

**Comment by RaphaelAlvez** [comment]
> The only issue, and this probably won't surprise you, is with piles. If you have a holder with a pile (stackOffsetX:0) then spread it out, the pile handle is still there. Not sure what behavior I would expect, but it seems strange.

I know it is weird but it doesn't break anything and @ArnoldSmith86 wanted to work on pile with hands so maybe he can improve that behavior later.

**Review by 96LawDawg — APPROVED** [review]
Okay.  I'm convinced.  Approved based on testing.

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
Why is this in `widget.js` and then it checks `this.get('type') == 'holder'`?

And please fix the formatting. I can tolerate missing semicolons but curly braces with wrong indentation are pretty deadly.

**Comment by RaphaelAlvez** [comment]
> Why is this in `widget.js` and then it checks `this.get('type') == 'holder'`?

yeah you are right

> And please fix the formatting. I can tolerate missing semicolons but curly braces with wrong indentation are pretty deadly.

😂

**Pull request merged**
