### PR TITLE
fixed that arrow buttons in state details did not honor `showName`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
See title.

Before:
image

After:
image

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1523/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1523-pr-test`.

**Comment by 96LawDawg** [comment]
Where was the arrow button?  What field?  I'm trying to test by duplicating on production and in here.

**Comment by ArnoldSmith86** [comment]
The game details overlay. The browser window has to be big enough to show them and small enough to not use the sidebar.

**Comment by RaphaelAlvez** [comment]
I also cannot replicate on both server I see not title

**Review by RaphaelAlvez — APPROVED** [review]
Ignore my previous comment

tested in tutorials.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Pull request merged**
