### PR TITLE
prevent crashes in asset downloader

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
If downloading an asset URL failed on the server, the entire server would crash. This improves the URL detection a bit and catches errors if the download failed.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1875/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1875-pr-test`.

**Review by 96LawDawg — APPROVED** [review]
Downloading assets still works.  No idea how to test if the error catching stuff works.

**Comment by ArnoldSmith86** [comment]
Add an asset `http://invalid` and try to use the downloader (the one that turns URLs into assets).

**Comment by 96LawDawg** [comment]
> Add an asset `http://invalid` and try to use the downloader (the one that turns URLs into assets).

Okay.  I did that without problem.

**Pull request merged**
