### PR TITLE
Separate widget box from widget appearance

### PR DESCRIPTION
**Pull request by robartsd**
This creates a separate div element `div.widget-content` to contain all the appearance attributes of the widget. `div.widget-content` is the first child of `div.#id.widget`. Child widgets are appended as siblings of `div.widget-content`. Positioning styles set by the game engine go to the inline style attribute of `div.#id.widget` all other styles go to the inline style attribute of `div.widget-content`. For convenience in using this with widget stylesheets, all classes except `typeClasses` are added to both `div#id.widget` and `div.widget-content`. This structure allows a lot more freedom in styling the widget without impacting the child widgets, it also removes the need to take the child widgets out of the DOM when rebuilding the widget as was done in card.js and spinner.js previously.

In the code I've replaced `domElement` with `domBox` if the target should be `div#id.widget` and `domInner` if the target should be `div.widget-content`.

Open to suggestions for changing the names of the widget object properties, the class names or both. In particular I've thought about using `div#id.widget-box` for the outer div and simply `div.widget` for the inner div.

#### default selector
The default selector will target the widget content div, not the widget box. Inline CSS will be applied to the widget content div. 

#### inheritance
Because child widgets will not be children of the widget content div, they will not be able to inherit CSS variables or [other inheritable properties](https://www.sitepoint.com/css-inheritance-introduction/#list-css-properties-inherit) set in default selectors.

#### child selectors
Selectors targeting child widgets will not reach the child widget if they are prefixed with the default selectors.

#### transform
Because engine generated transform rules will be applied to the widget box, game transform rules applied to the default selector which formerly overrode engine generated transform rules will cause transformations to be duplicated.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3984/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
I know this is still a draft, but it appears to resolve issue #664.

**Comment by robartsd** [comment]
> I know this is still a draft, but it appears to resolve issue #664.

Yes, that kind of problem was the original motivation, but as I worked with the idea it quickly became apparent that there were additional advantages to this approach.

**Comment by robartsd** [comment]
I think widget stylesheets in #951 should have "default" and "inline" go to `#id>.widget-content`. Perahaps a keyword "container" could be added at the beginning of the key if the target should be `#id` instead. 

I'm considering making a PR that merges this with #951.

**Comment by ArnoldSmith86** [comment]
> Perahaps a keyword "container" could be added at the beginning of the key if the target should be `#id` instead.

Do they need to ever touch the outer div?

**Comment by robartsd** [comment]
> > Perahaps a keyword "container" could be added at the beginning of the key if the target should be `#id` instead.
> 
> Do they need to ever touch the outer div?

The outer div itself, probably not, but they might want to reach descendant widgets. Since the inline style will be inaccessible, the only way to overwrite game engine dynamic styles would be `!important`

**Comment by 96LawDawg** [comment]
I generally like the new edit mode styling.  But in some instances it can be overwhelming.  Take a look at Go (built before cloning and inheritFrom, so cut me some slack).  Or Chinese Checkers.  Or Reward.  There, the value is diminished.  Most games benefit, but some are worse.  Can there be a toggle switch to turn that on and off?

**Comment by robartsd** [comment]
I think I will dial back the edit styles in this PR. Edit mode style options can come separately. I initially started reworking edit styles because my plan to implement all edit styles on `#id.widget::before` failed due to `--color` variable not being defended there. I think I need to work through the code in widget.js distinguishing between properties that are needed for the box and properties that are only needed for the inner div.

**Comment by robartsd** [comment]
> I think widget stylesheets in #951 should have "default" and "inline" go to `#id>.widget-content`. Perahaps a keyword "container" could be added at the beginning of the key if the target should be `#id` instead.
> 
> I'm considering making a PR that merges this with #951.
> 
> I intend it to be impossible for game designers to set inline styles on `div#id.widget`.

I've merged in the css improvements from main. I still need to create a way to address the container.

**Comment by robartsd** [comment]
> 1. Why are the properties in div.#w_id.widget set using `::before` and `::after` instead of being attributes of the div?

That is using pseudo elements to display the attributes in edit mode.

> 2. Can you give an example of where the game designer might need to use `container` (i.e. to have access to div.#w_id)?

If they want to style child widgets (like I did to simulate [bags](https://virtualtabletop.io/Bags)).

**Comment by robartsd** [comment]
VTT is now using elementsFromPoint() for identifying holders and widgets for JSON edit F-key shortcuts. This only returns elements that can accept pointer events, so setting `pointer-events: none` on the widget box div means that the element with the widget id is no longer returned. Rather than walking up the DOM tree from returned elements to find out which widget the element belongs to, it would might be better to generate an id for the widget content div as well as the widget box div (also the hit-test element proposed by @flackr). What form should these ids take?

I'm thinking the DOM structure of a widget might look something like:
```html
<div id="w_{widget id}_BOX" class="widget-box {type classes} {classes}" style="{engine generated styles}">
    <div id="w_{widget id}_HITTEST" style="{engine generated styles}" />
    <div id="w_{widget id}" class="widget {type classes} {classes}" style="{widget css property styles}">
        {widget contents}
    </div>
    <div id="w_{child widget id}_BOX" ...>
        <div id="w_{child widget id}" ...>
            {child widget contents}
        </div>
    </div>
    ...
</div>
```

In widget stylesheet selectors `${THIS}` could be replaced with `w_{widget id}` so selecting the widget container by id could be done with `${THIS}_BOX`.

Game authors should be discouraged from styling `${THIS}_BOX`, but may want to use it to select child widgets with a selector like `${THIS}_BOX > .widget-box > .widget`

**Comment by flackr** [comment]
I generally like this proposed structure, but, there are a few things that we may want to apply to children:
- Scrollable overflow
- Transforms, e.g. https://virtualtabletop.io/perspective
I guess these would just be the cases in which you'd add them to the `_BOX` element right?

Would the engine translation transform also be applied to the `_BOX` element? Would there be any value in adding an element to wrap the children so game authors may never need to style the `_BOX`?

For compat we may have to detect descendent combinator selectors in the `css` and use the BOX or child container element instead of the presentation element, e.g.:
```
  "css": {
    ">.childClass": { /* styles */ },
    " .descendantClass": { /* styles */ },
  }
```

I think it would be nicer if instead of `${THIS}_BOX` we define variables for the things we want devs to target, e.g. `${THIS_BOX}`

**Comment by robartsd** [comment]
> I generally like this proposed structure, but, there are a few things that we may want to apply to children:
> 
> * Scrollable overflow
> * Transforms, e.g. https://virtualtabletop.io/perspective
> 
> I guess these would just be the cases in which you'd add them to the `_BOX` element right?
> 
> Would the engine translation transform also be applied to the `_BOX` element?

Yes, engine translation transform is applied applied to `_BOX`. Box also gets the width, height, and border-radius. Box does not get borders (content-box and border-box must never be different for box; that's a big motivator to changing the structure).

> Would there be any value in adding an element to wrap the children so game authors may never need to style the `_BOX`?

Transforms involving the child widgets seems the most likely here.

> For compat we may have to detect descendent combinator selectors in the `css` and use the BOX or child container element instead of the presentation element, e.g.:
> 
> ```
>   "css": {
>     ">.childClass": { /* styles */ },
>     " .descendantClass": { /* styles */ },
>   }
> ```

The problem here is distinguishing between descendent selectors targeting the widget's own content elements vs. child widget elements. We can make an attempt in a fileupdater process, but there is no way that this PR will be able to adjust for everything possibility. For backward compatibility sake, we will not merge this to production until there is a public way to play games in an old version of the engine.

> I think it would be nicer if instead of `${THIS}_BOX` we define variables for the things we want devs to target, e.g. `${THIS_BOX}`

We probably would do something like this (but with the id scheme I proposed it wouldn't be strictly needed).

**Comment by flackr** [comment]
> Rather than walking up the DOM tree from returned elements to find out which widget the element belongs to, it might be better to generate an id for the widget content div as well as the widget box div (also the hit-test element proposed by @flackr). What form should these ids take?

In the proposed structure the widget div is only one parent away - a walk of one based on the presence of some class would be fine. If however we end up with more complex structures I agree it would be better to have individual ids. Of course if we didn't have unique ID's for the components it would mean selecting anything but the root would require a child combinator.

**Comment by robartsd** [comment]
> > Rather than walking up the DOM tree from returned elements to find out which widget the element belongs to, it might be better to generate an id for the widget content div as well as the widget box div (also the hit-test element proposed by @flackr). What form should these ids take?
> 
> In the proposed structure the widget div is only one parent away - a walk of one based on the presence of some class would be fine.

Might do that for a hit test element. Most widget stylesheet rules will target the inner div so, giving it an id probabaly makes sense.

**Pull request closed without merging**
