### PR TITLE
Adds fixed parent to composed widgets

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
Just a small PR since the feature was not added to the composed widget in the add widget overlay

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3685/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
Great idea.  Approved through test and code review.

**Comment by robartsd** [comment]
Just need to update the testcafe hash for game creation and this should be ready to go.

**Review by robartsd — APPROVED** [review]

**Review by bjalder26 — APPROVED** [review]
I took the liberty of updating the hash.  IMHO this is ready to merge.

**Comment by RaphaelAlvez** [comment]
> I took the liberty of updating the hash. IMHO this is ready to merge.

I just spent 1h trying to figure it out. Thanks!

**Pull request merged**
