### PR TITLE
adds highlight class and uses filter to indicate dropable and target holder

### LINKED ISSUE #1248: holder should have highlightb option for droptarget
similar to Agar or in the CSS tutorial

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
similar to Agra

There is an example in the test room

closes #1248

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1265/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
This works as expected.  It conflicts with (meaning it provides the darkening filter for) the existing css technique if dropTargetHighlight is true, but that is to be expected.  I added a couple of colored demo holders in the room that show that.  But there is no conflict if dropTargetHighlight is false.

The only thing I wanted to open up for discussion is whether you should also provide easier access to changing the colors.  You've done that for a variety of css things like button hover, etc.  I don't think we need more properties like dropTargetHighlightDroppable or whatever.  But maybe dropTargetHighlight could be an array like this:

```JSON
"dropTargetHightlight": [
  {
     "droppable":"pink"
  },
  {
     "dropTarget":"red"
   }
]
```

If dropTargetHighlight is empty or null, then nothing happens.  If either value is filled in, then it gets that color.  If one value is filled in and the other is blank, it gets a default color equivalent to your filter.  Something like I did in Agra with #00000050 for droptarget and #000000aa for droppable or whatever.  That has the same effect as a filter.

To be clear, we don't have to do that.  All of that can be done through css.  Was just wondering if people thought it was worth making it that easy to modify.

**Comment by RaphaelAlvez** [comment]
As I said to you I wasn't sure of what I was doing either.

The css to add this is so simple that it is probably irrelevant to have this property but it is such a nice feature that I felt like adding it.
the way you proposed seems even more complicated than just adding it to the css. 

code wise I feel this is the simplest solution and for games I feel that the filter is good as it also displays over the cards

**so my main point:** it is very simple to do it the proper way but this is more user friendly, even simpler and very basic

**Review by 96LawDawg — APPROVED** [review]
Works for me.  And you are right that just using the css is probably less complicated than what I came up with.  You have a simple property that works for people who want it done.  Good enough.  Approved through test.

**Review by ArnoldSmith86 — COMMENTED** [review]
The code looks fine. In a PCIO style game (no custom CSS etc), this is pretty nice. I wonder how useful it'll be for us though. As soon as you want to customize the highlight even a little bit, it basically doesn't add any value; it even kinda makes it harder because you'd have to undo the filter. And like you said, anything more customizable is probably worse than just adding the CSS.

So, I'm not against merging it. I'm just also not very excited about it. :man_shrugging:

**Pull request closed without merging**
