### PR TITLE
Add Fantasy Wars, Hangman, other updates

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:
- Blue: Fixed layers on a couple of labels.
- Connex: Updated with css rotation animation for game pieces.
- Fantasy Wars. New game by RaphaelAlvez.  Similar to War Chest.
- Hangman. New game by LawDawg.  Portuguese word list by RaphaelAlvez.
- Medieval VNO. Added variant with automation following play on Dev Game Night.
- Reward. Updated with lower z values.
- Tantrums. Updated with css rotation animation for game pieces and replaced Unicode symbols with svg images.

Public Tutorials:
- Button Appearance.  Added on buton on CSS Shapes Variant
- changeRoutine. Optimized all the JSON for dynamic expressions.
- Functions – GET. Added a comment about using dynamic expressions.
- Hexagonal Cards. Fixed typo on button in The Basics variant for calculator of height and width.  Optimized some JSON for dynamic expressions.
- Holders. Optimized some JSON for dynamic expressions on Offset: Advanced and Moving: Basic variants.

Public Assets:
- Other Widgets.  Renamed the Coordinate Helper variant to Misc Tools and added a new widget by Interitus that provides a list of widgets in a room sorted by layer, type, and then alphabetical.

Updated library.json and tests.js (with new Blue checksum).

For some reason, the tests.js file replaced the existing one completely without showing just the change, but the only change is the Blue checksum.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3526/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Loaded files from library.json.

**Comment by ArnoldSmith86** [comment]
You left the recall menu expanded in Reward. The TestCafé test tries to press the button to expand it but it isn't visible.

Is it supposed to be expanded by default now? In that case I'll change the test.

**Comment by 96LawDawg** [comment]
No.  I screwed that up.  I'll fix it.  I mean, it doesn't really matter for the game, but I originally intended for it to start closed so I'll put it back.  Thank you.

**Comment by 96LawDawg** [comment]
So I did all the usual things and somehow this PR got polluted with other recent merges.  Do I need to close it and start over?

**Comment by ArnoldSmith86** [comment]
It's probably fine.

**Review by ArnoldSmith86 — APPROVED** [review]
Some notes:
- You added tests.js to the library repo. Please delete it next time.
- You also have two holder tutorial files now. One with `t` and one with `T`. Only one of them is used.
- When selecting troops in Fantasy Wars, the cards are below the overlay when dragging.
- And the instructions say there should be 7 tokens in my bag. There's just a coin.
- In the automated VNO the Next button goes in reverse. Is that a feature? If it is, you should change the name.
- We should probably revisit Reward eventually. It's pretty sluggish with all those cards.

**Comment by robartsd** [comment]
> * We should probably revisit Reward eventually. It's pretty sluggish with all those cards.

PR #537 should help in some cases where recalling a lot of cards is slow.

**Comment by ArnoldSmith86** [comment]
It probably helps but even loading Reward takes quite a while. And while VTT should probably support that many cards, it feels like it is totally unnecessary for Reward considering all the automation features we added in the meantime. It could just auto-clone them..

**Comment by robartsd** [comment]
> It probably helps but even loading Reward takes quite a while. And while VTT should probably support that many cards, it feels like it is totally unnecessary for Reward considering all the automation features we added in the meantime. It could just auto-clone them..

I agree. Auto clone was pretty easy to implement in the developer game night scheduling room we built a couple of weeks ago.

**Comment by bjalder26** [comment]
> > It probably helps but even loading Reward takes quite a while. And while VTT should probably support that many cards, it feels like it is totally unnecessary for Reward considering all the automation features we added in the meantime. It could just auto-clone them..
> 
> I agree. Auto clone was pretty easy to implement in the developer game night scheduling room we built a couple of weeks ago. Could still use card widgets, they can be cloned just like basic widgets can. In play we want them to still support piles.

If you're thinking of using a leaveRoutine, then I would probably wait until leaveRoutine gets updated, or make sure the leaveRoutine does not clone if there is already a widget in the holder.  Right now leaveRoutine will trigger twice for every widget you remove, so the number of widgets in the holder will increase as you remove widgets.

**Comment by robartsd** [comment]
> > > It probably helps but even loading Reward takes quite a while. And while VTT should probably support that many cards, it feels like it is totally unnecessary for Reward considering all the automation features we added in the meantime. It could just auto-clone them..
> > 
> > 
> > I agree. Auto clone was pretty easy to implement in the developer game night scheduling room we built a couple of weeks ago. Could still use card widgets, they can be cloned just like basic widgets can. In play we want them to still support piles.
> 
> If you're thinking of using a leaveRoutine, then I would probably wait until leaveRoutine gets updated, or make sure the leaveRoutine does not clone if there is already a widget in the holder. Right now leaveRoutine will trigger twice for every widget you remove, so the number of widgets in the holder will increase as you remove widgets.

Yes, the leaveRoutine would check the number of widgets:
```json
  "leaveRoutine": [
    {
      "func": "SELECT",
      "property": "parent",
      "value": "${thisID}",
      "type": "card",
    },
    {
      "func": "COUNT"
    },
    {
      "func": "IF",
      "operand1": 0,
      "relation": "==",
      "operand2": "${COUNT}",
      "thenRoutine": [
        {
          "func": "CLONE",
          "source": "child"
        },
        {
          "func": "SET",
          "property": "parent",
          "value": "${thisID}"
        },
        {
          "func": "MOVE",
          "from": "${thisID}",
          "to": "${thisID}"
        }
      ]
    }
  ]
```

**Pull request merged**
