### PR TITLE
Many new tutorials plus library image updates

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Tutorials:
- Canvas. New tutorial explaining the CANVAS function and composed widget. 1 Variant
- Routines. Substantially revised the changeRoutines tutorial.  Now 4 variants covering all aspects of routines.
- Functions – AUDIO. New tutorial. 1 variant for AUDIO and clickSound
- Functions - CLONE and DELETE. New tutorial. 1 variant
- Functions – COUNT. New tutorial. 1 variant
- Functions – FLIP. New tutorial. 1 variant
- Functions – LABEL. New tutorial. 1 variant
- Functions – MOVE. New tutorial. 1 variant
- Functions - RECALL and SHUFFLE. New tutorial. 1 variant
- Dice. Added ArnoldSmith86’s version of the dice

Changed library image using new VTT icons for the following tutorials:
- faceTemplates, Grid, Hands, Holders, inheritFrom, JSON Editor User Guide (just adjusted text position), Master Button, Menus, Piles, Seats, State Dependent Routines, Timer

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3994/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
All files successfully loaded from new library.json file.

Substantive changes (can copy and paste this for approval):
- [ ] Canvas. New tutorial explaining the CANVAS function and composed widget. 1 Variant
- [ ] Routines. Substantially revised the changeRoutines tutorial. Now 4 variants covering all aspects of routines.
- [ ] Functions – AUDIO. New tutorial. 1 variant for AUDIO and clickSound
- [ ] Functions - CLONE and DELETE. New tutorial. 1 variant
- [ ] Functions – COUNT. New tutorial. 1 variant
- [ ] Functions – FLIP. New tutorial. 1 variant
- [ ] Functions – LABEL. New tutorial. 1 variant
- [ ] Functions – MOVE. New tutorial. 1 variant
- [ ] Functions - RECALL and SHUFFLE. New tutorial. 1 variant
- [ ] Dice. Added ArnoldSmith86’s version of the dice

Library image changes (can copy and paste this for approval):
- [ ] faceTemplates
- [ ] Grid
- [ ] Hands
- [ ] Holders
- [ ] inheritFrom
- [ ] JSON Editor User Guide
- [ ] Master Button
- [ ] Menus
- [ ] Piles
- [ ] Seats
- [ ] State Dependent Routines
- [ ] Timer

**Review by RaphaelAlvez — CHANGES_REQUESTED** [review]
> All files successfully loaded from new library.json file.
> 
> Substantive changes (can copy and paste this for approval):
> 
> * [ ]  Canvas. New tutorial explaining the CANVAS function and composed widget. 1 Variant

suggestion: Canvas are not locked
Change request: Artist can be an array

> * [X]  Routines. Substantially revised the changeRoutines tutorial. Now 4 variants covering all aspects of routines.

Suggestion: maybe this should be Routines and Automations and include info about other sources of automation like onEnter, onLeave, faces and nomarl click for all widget and their relation to between the routines(as I'm already working on). (suggestion for futures updates not for this PR)

last line in enterRoutines: "calculation"

> * [x]  Functions – AUDIO. New tutorial. 1 variant for AUDIO and clickSound
> * [x]  Functions - CLONE and DELETE. New tutorial. 1 variant
> * [x]  Functions – COUNT. New tutorial. 1 variant
> * [x]  Functions – FLIP. New tutorial. 1 variant

suggestion: maybe add a note that says that random is really random and sometimes you will get the same face multiple times in a row. the lack of animation does not make this clear

suggestion related to routines: a variant that gives the equivalent clickRoutines to each widget click

> * [ ]  Functions – LABEL. New tutorial. 1 variant

change request: no example of using LABEL in basicWidget or buttons (and holders in the future)

> * [ ]  Functions – MOVE. New tutorial. 1 variant

change request: "used"
change request: I feel MOVE should state that moving directly to hand only works for the player clicking. and direct the reader to the seat tutorial if they want to move cards to other players hand
change request: inform that move select widgets based on the dropTarget of the origin parent and that parent can be any type of widget. 

> * [ ]  Functions - RECALL and SHUFFLE. New tutorial. 1 variant

change request: "Shuffling the widgets in a holder randomizes their stacking order ('z' position) but does not move them within the holder" not true for stackOffset
suggestion: "intermingle" does not seem to be a very common word. maybe use "mix" or "shuffle them together"

> * [x]  Dice. Added ArnoldSmith86’s version of the dice
> 
> Library image changes (can copy and paste this for approval):
> 
> * [x]  faceTemplates
> * [x]  Grid
> * [x]  Hands
> * [x]  Holders
> * [x]  inheritFrom
> * [x]  JSON Editor User Guide
> * [x]  Master Button
> * [x]  Menus
> * [x]  Piles
> * [x]  Seats
> * [x]  State Dependent Routines
> * [x]  Timer

I only unchecked tutorials that have change requests. suggestions are up to you.

**Comment by 96LawDawg** [comment]
> > * [ ]   Canvas. New tutorial explaining the CANVAS function and composed widget. 1 Variant
> 
> suggestion: Canvas are not locked Change request: Artist can be an array

Accepted.  Changes made.

> > * [ ]   Routines. Substantially revised the changeRoutines tutorial. Now 4 variants covering all aspects of routines.
> 
> Suggestion: maybe this should be Routines and Automations and include info about other sources of automation like onEnter, onLeave, faces and nomarl click for all widget and their relation to between the routines(as I'm already working on). (suggestion for futures updates not for this PR)
> 
> last line in enterRoutines: "calculation"

Suggestion noted, but nothing changed.  Corrected spelling error.


> > * [x]   Functions – FLIP. New tutorial. 1 variant
> 
> suggestion: maybe add a note that says that random is really random and sometimes you will get the same face multiple times in a row. the lack of animation does not make this clear

Accepted.  Change made.

> suggestion related to routines: a variant that gives the equivalent clickRoutines to each widget click

I don't understand what you mean so I didn't do anything with this.

> > * [ ]   Functions – LABEL. New tutorial. 1 variant

> change request: no example of using LABEL in basicWidget or buttons (and holders in the future)

The example on the left already used a basic widget.  I clarified that in the note.  I changed the example on the right to change the button text.  I can add a holder example once #921 is merged.

> > * [ ]   Functions – MOVE. New tutorial. 1 variant
> 
> change request: "used" change request: I feel MOVE should state that moving directly to hand only works for the player clicking. and direct the reader to the seat tutorial if they want to move cards to other players hand change request: inform that move select widgets based on the dropTarget of the origin parent and that parent can be any type of widget.

Accepted.  Changes made.

> > * [ ]   Functions - RECALL and SHUFFLE. New tutorial. 1 variant
> 
> change request: "Shuffling the widgets in a holder randomizes their stacking order ('z' position) but does not move them within the holder" not true for stackOffset suggestion: "intermingle" does not seem to be a very common word. maybe use "mix" or "shuffle them together"

Accepted.  Changes made.  I deleted the part of the sentence after z position.  No need to cause confusion or go into too much detail.  Changed intermingle to mix.

**Review by RaphaelAlvez — APPROVED** [review]
Approved. lat review but leave that for next week's PR

in MOVE you used ) instead of ( in the first example

**Comment by 96LawDawg** [comment]
> Approved. lat review but leave that for next week's PR
> 
> in MOVE you used ) instead of ( in the first example

Fixed it while I was adding the new Routine variant you made.

**Pull request merged**
