### PR TITLE
Implement anonymous collections.

### PR DESCRIPTION
**Pull request by rogerl50**
This is a replacement for #879, which was closed. Suggestions/review comments from that PR have been implemented.

Needs:
1) Good code review
2) Thorough testing of new array functionality for source collections.
3) Is there a way to add [] to the list of possible values for the `"collection"` property (or, for SELECT or TURN, the `source` property? I don't see how it can be done.

Addresses #875. With this PR, functions that accept an input collection can now accept an array
```
  "collection": ["id1", "id2", "id3"]
```
The result is that the function will operate on an anonymously-named collection that consists of all the id's that actually are the id's of widgets.

Replaces `isValidCollection` by a new routine, `getCollection`, that returns either the key of the collection passed in, or the key of a new collection created from the array that is passed in, or `null` in case of error. The resulting collection key is used in subsequent function processing.

Passes the TestCafe tests, so this may not have broken anything. Tested only in very simple cases for the actual use of anonymous collections.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3881/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
I'm thinking that `[]` should be added to the JSON editor under `collection`.
It does not appear to double add to a collection, which I think is a good thing.

**Comment by ArnoldSmith86** [comment]
> I'm thinking that `[]` should be added to the JSON editor under `collection`.

We have `CTRL-F1` to add the widget `id` to the editor. We could enhance that a bit to work differently when you highlight the `collection` parameter of a routine operation. So there it would change it to `collection: [ "<id>" ]`.

It's still a good idea to add `[]` as a preset.

**Comment by rogerl50** [comment]
Adding `[]` as a preset *should* be simple, but I can't figure out how to add `[]` to the `collectionNames` in jsonedit.js. Adding just `[]` gives a little blue dot in the editor. Adding `'[]'` and then using the replacement in the editor results in a property value of `"[]"`.

**Comment by bjalder26** [comment]
I think I have tested this used with every function that uses collection and source, and haven't found any issues.

**Comment by rogerl50** [comment]
> I think I have tested this used with every function that uses collection and source, and haven't found any issues.

You tested with an array in place of a collection name, right?

**Comment by bjalder26** [comment]
> > I think I have tested this used with every function that uses collection and source, and haven't found any issues.
> 
> You tested with an array in place of a collection name, right?

Yes.  Both for source and collection (when applicable).

**Review by ArnoldSmith86 — APPROVED** [review]
The general code changes look fine to me. I didn't test anything but if @bjalder26 did extensive tests, I don't see a problem.

**Pull request merged**
