### PR TITLE
fixed undefined collection after CALL and thisID+thisButton now point to the callee

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Last minute changes _always_ screw everything up. :(

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3353/pr-test (or any other room on that server)

**Review by rogerl50 — APPROVED** [review]
Seems to work correctly in the example in the pr-test room.

However, `thisButton` and `thisID` are not set in a `CALL` to the id of the called widget. That fix may be out of scope for this PR.

**Comment by rogerl50** [comment]
Can you just educate me as to why this fixes the problem? It doesn't really seem like you changed the assignment.

**Comment by ArnoldSmith86** [comment]
> Can you just educate me as to why this fixes the thisButton/thisID problem? It doesn't really seem like you changed the assignment.

Does reading https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign help you understand?

It's basically just the order of parameters that determine which object overrides which.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Debug did not work with the simplest of CALL routines (only one and in the same button) before.  It does with this change.

**Comment by 96LawDawg** [comment]
This is ready to be merged to fix a bug.  But it seems to be stuck waiting on the new TestCafe process.  I restarted the checks, but that didn't trigger it to work.

**Comment by ArnoldSmith86** [comment]
Yeah, I think we need to merge the new test PR first. Unless someone has objections.

**Pull request merged**
