### PR TITLE
changing the widgets in the multi-selection mode now retrieves their values

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Multi-selection mode in the JSON editor shows a property `widgets` that lists all selected widget IDs. With this PR you can edit that list directly in the text editor to add or remove widgets. It also supports regular expressions so you can add something like `/Player [0-9]+ Holder/` and it will display the values of all matching widgets.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3647/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Quick little demo (of course it would have been faster to click the four holders in this case):

https://user-images.githubusercontent.com/73538315/124929635-f3cf4100-e000-11eb-8c1d-8e524bb39fbf.mp4

**Review by 96LawDawg — APPROVED** [review]
This is great!  I don't understand much about regular expressions, but I was able to make it work and find things in a room.  It is very powerful.  Accidentally pressing the delete widget key while you have a bunch of widgets selected is too easy to do.  Maybe a confirmation prompt would be good if deleting multiple widgets.  But even without that, this is an improvement.  Approved through test.

One other recommendation.  We need a wiki entry for the JSON editor.  The tutorial I made is already badly out of date.  All these new features being added all the time need to be documented somewhere.

**Comment by ArnoldSmith86** [comment]
> Accidentally pressing the delete widget key while you have a bunch of widgets selected is too easy to do.

True. But I would prefer a more general undo functionality to adding a delete confirmation.

**Comment by robartsd** [comment]
> True. But I would prefer a more general undo functionality to adding a delete confirmation.

I think a delete confirmation is a useful stopgap until a general undo is implemented.

**Pull request merged**
