### PR TITLE
dynamic expression string literal whitelist

### LINKED ISSUE #471: Cannot use colon symbol with dynamic expressions
I am trying to use the new dynamic expressions to update css.  I want to say something like "var newCSS = 'background: white'".  However, the colon causes the output to be 1.  I tried do something like "var newCSS = 'background'" and then "var newCSS = ${newCSS} +':'" but that causes the same problem.

### PR DESCRIPTION
**Pull request by robartsd**
Allows most ASCII printable characters in dynamic expression string literal. fixes #471

Dynamic Expresions wiki page:

~Finally, valid characters for strings are alphanumerics, , (comma), . (period), ( (left parenthesis), ) (right parenthesis), space, _ (underscore), and - (hyphen).~

String literals in dynamic expressions can contain any [printable ASCII character](https://en.wikipedia.org/wiki/ASCII#Printable_characters) (\u0020 to \u007e) except single quote `'` (\u0027), double quote `"` (\u0022), and backslash `\` (\u005c).

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3645/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
Does this R.E. allow lowercase letters? (They aren't in either of the ranges specified.)

**Comment by robartsd** [comment]
> Does this R.E. allow lowercase letters? (They aren't in either of the ranges specified.)

Yes, it should lowercase letters are between `]` and `~`.

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
Code looks good to me. Please also update the fileupdater so it doesn't add unnecessary escapes.

**Comment by robartsd** [comment]
> Code looks good to me. Please also update the fileupdater so it doesn't add unnecessary escapes.

I did think about not needing fileupdater because unnecessary escapes don't cause problems, but had not thought about removing escapes put in by the updater that are no longer needed.

**Comment by robartsd** [comment]
I think I got the fileupdater change correct here.

**Review by ArnoldSmith86 — APPROVED** [review]
I tested the fileupdater with [Unnamed.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/6784678/Unnamed.zip). It needed one fewer backslash because the regex is not in a string. Now it seems to work as advertised.

**Comment by robartsd** [comment]
> I tested the fileupdater with [Unnamed.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/6784678/Unnamed.zip). It needed one fewer backslash because the regex is not in a string. Now it seems to work as advertised.

Thanks.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Did not test any fileupdater operations.

**Pull request merged**
