### PR TITLE
Increase JSON Editor Pane Width

### LINKED ISSUE #1283: JSON Editor Bug in Wide View
There is a problem when using the Wide View version of the JSON Editor.  I have 2 videos below that show how this happens.  It only seems to be a problem in deeply nested routines.  I have not been able to duplicate it other than in my poker room, but I have not tried many other rooms.  I have uploaded my current poker room file to https://virtualtabletop.io/elmq.  Here is what happens.

In video 1, inside of a deeply nested routine, I copy a snippet and paste it somewhere inside the middle of a routine.  It turns into white text because I have not reselected the widget.  But I should still be able to work with the widget the way it is, and until recently I could.  But as you can see in the video, when I try to select JSON text to edit, the highlighter does not work property.  When in narrow view, it works as it should.

In video 2, I paste the same snippet at the end of an area.  Again it turns white.  I try to position the cursor to delete the extra trailing comma.  That used to work.  Now it doesn't.  Once I position the cursor in the video, I press the delete key and you can see it moving strangely.  In the narrow view, it works fine.

Please help.  This caused significant frustration for me recently.  I switched to the narrow view to fix the problem, but I don't like working in the narrow view, especially with deeply nested JSON.  This definitely came about as a result of some of the recent changes to the JSON editor from @rogerl50.  I went back to PR 1222 (before the full-time JSON tree was made available).  Things worked as expected in that PR.

https://user-images.githubusercontent.com/76912527/181935603-9c4248a8-77cb-49dd-9590-ec6d677d6b9f.mp4

https://user-images.githubusercontent.com/76912527/181935610-0961dfce-da06-4ef3-ad0d-b061879677ea.mp4

### PR DESCRIPTION
**Pull request by 96LawDawg**
Fixes #1283

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1285/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
I guess the other little change in the file is from Windows line endings?  Not sure.  I don't really do this sort of thing.

**Comment by 96LawDawg** [comment]
I tested it and it works.  I may be the only one able to test it since I seem to be the only one having the problem.

**Comment by RaphaelAlvez** [comment]
> I guess the other little change in the file is from Windows line endings?  Not sure.  I don't really do this sort of thing.

When you use GitHub ok desktop you can choose which lines you want to add to the commit. Just deselect anything that you didn't use

**Comment by ArnoldSmith86** [comment]
> I may be the only one able to test it since I seem to be the only one having the problem.

It's always way more important to test that nothing else breaks.

**Comment by 96LawDawg** [comment]
> It's always way more important to test that nothing else breaks.

I agree with that!

I tested as many JSON Editor functions as I could think of.  Everything still works.

**Review by ArnoldSmith86 — APPROVED** [review]
The change should be fine because the inner width should be the same as before now.

**Pull request merged**
