### PR TITLE
JSON editor tree view no longer steals focus

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Please test if this fixes the same stuff that #1031 fixes.

This would be a less hacky solution but if the other PR fixes more stuff, I have no problem merging it instead.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4035/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
I love that both are attempting to fix the same issue, but both make it into the automatic beta without conflicts.

**Comment by bjalder26** [comment]
> I love that both are attempting to fix the same issue, but both make it into the automatic beta without conflicts.

I think this is a cleaner solution.

**Review by bjalder26 — APPROVED** [review]
Approving based on testing and code review.

**Review by rogerl50 — APPROVED** [review]

**Pull request merged**
