### PR TITLE
GET with sum returns 0 for an empty collection (fixes #112)

### LINKED ISSUE #112: GET with "sum" on an empty collection should return zero.
`COUNT` on an empty collection properly returns zero, but `GET` with "sum" on some property seems to return nothing. I'm using that result in a `COMPUTE` operation, and that operand gets turned into 1. The following `clickRoutine` in a button in an otherwise empty room shows the problem (with "debug": true):
```JSON
    {
      "func": "SELECT",
      "property": "id",
      "value": "foo",
      "collection": "bar"
    },
    {
      "func": "COUNT",
      "collection": "bar",
      "variable": "count"
    },
    {
      "func": "GET",
      "collection": "bar",
      "property": "foo",
      "aggregation": "sum",
      "variable": "sum"
    }
```

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
I think it's reasonable to assume that anyone would expect the sum of a property of an empty collection to be 0.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3116/pr-test (or any other room on that server)

**Review by rogerl50 — DISMISSED** [review]
Looks good. Do you want to register an empty collection problem even when you return zero? Might be useful for debugging, but I don't know what side effects that has.

**Comment by ArnoldSmith86** [comment]
I don't think it warrants a "problem". Sounds like expected behaviour. The debug output already shows the collection contents so you could already see that it's empty.

**Review by UltimateGeek — DISMISSED** [review]

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 the PR is approved. You need to resolve the conflicts

**Review by rogerl50 — APPROVED** [review]

**Review by UltimateGeek — APPROVED** [review]

**Pull request merged**
