### PR TITLE
fixed `grid` in conjunction with `fixedParent`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The `grid` was only applied if the widget did not have a parent to avoid snapping to the grid after snapping to a holder.

This PR moves the `grid` code from `setPosition` to `move` and removes the check for a `parent`. Now it is only called when the widget is moved manually.

This PR also adds a parameter to `MOVEXY`: `snapToGrid` (default `true`) - If the widget being moved has a `grid` property and this parameter is `true`, the widget will snap to the nearest valid grid position just like when the user moves it manually. If set to `false`, the widget will ignore its own `grid` and end up exactly where `x` and `y` specify.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3890/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
As I understand this, it will cause the widget to snap to the grid while being dragged. If it is dropped into an aligned holder, the holder will still override the grid location.

> I was too lazy to test this special condition but if you moved a widget with a `grid` using `MOVEXY` it should have snapped to the grid while now it will not. Does anybody think that is a problem anywhere?

It's possible that someone wrote a routine that calculated the position for `MOVEXY` that used a grid for final alignment, but that seems like a far reach.

I'm currently working with movement in #882.

**Comment by ArnoldSmith86** [comment]
> As I understand this, it will cause the widget to snap to the grid while being dragged. If it is dropped into an aligned holder, the holder will still override the grid location.

Yes.

> It's possible that someone wrote a routine that calculated the position for `MOVEXY` that used a grid for final alignment, but that seems like a far reach.

That sounds backwards to me. I was saying that `MOVEXY` to `x:5, y:5` would instead move to `x:10, y:10` (if there was a grid like that) before this PR because it used `setPosition` and set the `parent` to `null` before that (so it applied the `grid`).

**Comment by ArnoldSmith86** [comment]
You know what, it should just be an option of `MOVEXY`. No problem to call `snapToGrid` in there.

**Comment by robartsd** [comment]
> You know what, it should just be an option of `MOVEXY`. No problem to call `snapToGrid` in there.

And the option can default to call `snapToGrid` or a file update can add the option to any existing `MOVEXY` functions. Easy fix to avoid a breaking change.

**Review by robartsd — APPROVED** [review]
Code looks good to me. I have not done testing.

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 this is approved please consider merging (I didn't look at it)

**Comment by ArnoldSmith86** [comment]
> I have not done testing.

I was hoping @96LawDawg would do some testing because he reported the bug.

**Comment by 96LawDawg** [comment]
I forgot this one was mine.  I'll test in the next day or so.

**Review by 96LawDawg — APPROVED** [review]
Approved by testing.

**Comment by ArnoldSmith86** [comment]
@96LawDawg Can you do another quick test? I messed up the merge a little.

**Comment by 96LawDawg** [comment]
I don't know if I missed this the first time or if something changed.  For the green checker in the test room, `snapToGrid` does not work if the parent is fixed.  Seems like it should.

**Comment by ArnoldSmith86** [comment]
The green one doesn't have a `grid` or am I missing something?

**Comment by 96LawDawg** [comment]
Making a draft of what the wiki for MOVEXY should look like after merge:
----------------------------------

This function moves widgets to a specific position on the surface (i.e. outside any holders). In case the widgets are currently contained in a another widget (e.g. pile or holder), they will be moved out before being moved to the given coordinates.

Parameters:
* from: _holderID_ (or an array) - specifies the holder that contains the widgets to move
* ~~collection: _collection_~~ - _not yet supported_
* count: _number_ - limits the amount of moved widgets (defaults to 1 if omitted; use 0 to indicate no limit)
* x: _number_ - the x position on the surface (defaults to 0)
* y: _number_ - the y position on the surface (defaults to 0)
* snapToGrid: _true/false_ - If the widget being moved has a grid property and this parameter is true, the widget will snap to the nearest valid grid position just like when the user moves it manually. If set to false, the widget will ignore its own grid and end up exactly where x and y specify (defaults to true)

The parameter _z_ can optionally set the z-order of the widget. If omitted, the z-order will be determined automatically.

The parameter _face_ can optionally set the face of the moved widgets to the given value (see FLIP). If omitted, the widgets will be left as they are.

Please note that the moved widgets can form _piles_ as if they were moved by players. They will NOT be placed into any _holders_ though, even if the coordinates match perfectly. Use _MOVE_ for that.

```JS
{
  "func": "MOVEXY",
  "from": "<holderID>",
  "count": 2,
  "face": 0,
  "x": 100,
  "y": 100,
  "z": 100
}
```

**Pull request merged**
