### PR TITLE
Update Investors

### PR DESCRIPTION
**Pull request by 96LawDawg**
Add gameStartRoutine and turn cards face down when leaving hand.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1710/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1710-pr-test`.

**Comment by ArnoldSmith86** [comment]
Hmm.

image

The holder exists. So something with `gameStartRoutine` seems to be broken.

**Comment by 96LawDawg** [comment]
> The holder exists. So something with `gameStartRoutine` seems to be broken.

Nope.  Typoe: holer instead of holder.  Fixed.

**Comment by ArnoldSmith86** [comment]
...

**Review by ArnoldSmith86 — APPROVED** [review]
Code looks fine. Changes seem to work. I'm not really familiar with the game though.

**Pull request merged**
