### PR TITLE
loop through all widgets

### PR DESCRIPTION
**Pull request by robartsd**

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3572/pr-test (or any other room on that server)

**Review by rogerl50 — CHANGES_REQUESTED** [review]
The only change left in this PR is the ability to loop over multiple widgets in a collection. The other two changes have been made in #569

**Comment by rogerl50** [comment]
It seems like this addition could potentially be useful, although it obviously requires the use of `+` and a variable being modified in a `FOREACH` loop or the like. We probably want specifics in the Wiki regarding id changes regardless of whether this PR makes it in or not.

**Comment by robartsd** [comment]
> It seems like this addition could potentially be useful, although it obviously requires the use of `+` and a variable being modified in a `FOREACH` loop or the like. We probably want specifics in the Wiki regarding id changes regardless of whether this PR makes it in or not.

While looping in a FOREACH would provide more options, without a FOREACH this could be useful using mode:"+". You could select a set of widgets and clone them all with some tag added to all the original ids.

**Comment by robartsd** [comment]
```json
  "clickRoutine": [
    {
      "func": "SELECT",
      "property": "id",
      "relation": "!=",
      "value": "${thisID}"
    },
    {
      "func": "SET",
      "property": "id",
      "relation": "+",
      "value": "-idChanged"
    }
  ]
```

**Comment by bjalder26** [comment]
> ```json
>   "clickRoutine": [
>     {
>       "func": "SELECT",
>       "property": "id",
>       "relation": "!=",
>       "value": "${thisID}"
>     },
>     {
>       "func": "SET",
>       "property": "id",
>       "relation": "+",
>       "value": "-idChanged"
>     }
>   ]
> ```
> 
> Loaded in pr-test. Open JSON editor to tree view before clicking button to easily see results.

Even if it selects the button it appears to apply the -idChanged tag to everything just fine.

**Comment by robartsd** [comment]
> > ```json
> >   "clickRoutine": [
> >     {
> >       "func": "SELECT",
> >       "property": "id",
> >       "relation": "!=",
> >       "value": "${thisID}"
> >     },
> >     {
> >       "func": "SET",
> >       "property": "id",
> >       "relation": "+",
> >       "value": "-idChanged"
> >     }
> >   ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Loaded in pr-test. Open JSON editor to tree view before clicking button to easily see results.
> 
> Even if it selects the button it appears to apply the -idChanged tag to everything just fine.

I'm guessing that the routine gets interrupted when the delta changing the routine's id gets processed. This succeeds here because the change is in the last step.

**Pull request merged**
