### PR TITLE
group custom and routine properties in JSON editor

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This PR does not change the fixed order at the top of the JSON (type, id, ...). All other properties were just shown in alphabetic order. With this PR this bottom block will be split into three parts: all other known widget properties (the yellow ones), then a block with all custom properties (the orange ones) and then another block with all the routine properties.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:1120/pr-test (or any other room on that server)

**Review by rogerl50 — APPROVED** [review]
Seems to work, code looks good.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Comment by robartsd** [comment]
Can we get the canvas data properties moved to after the routines?

**Pull request merged**
