### PR TITLE
fixed crash after renaming a widget

### LINKED ISSUE #1974: renaming a widget in the JSON makes the editor lose connection to the widget
This causes a client crash when using the dragToolbar unless you click on the widget again first.

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Fixes #1974. When changing the `id` of a widget using the JSON editor, the editor selection will now be updated to the new id.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2216/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
No idea why a random TestCafé test fails... :grin:

**Comment by 96LawDawg** [comment]
This does not work. It lets you type one letter, then the `id` value loses focus and you have to click on the `id` value again and again for each letter.  But it does fix the problem of the drag handle.

**Comment by ArnoldSmith86** [comment]
> It lets you type one letter, then the `id` value loses focus and you have to click on the `id` value again and again for each letter.

I never tested more than typing one letter. :grimacing:

Now it should be working.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

There is still one minor thing, but may be difficult to figure out and does not really matter.  If you change the type and then change the id, it loses focus after the first letter but is fine for other letters.  Strange, so just reporting but also approving.

**Pull request merged**
