### PR TITLE
Now capital letters are incremented using Excel style.

### LINKED ISSUE #1322: Incrementing letters in duplicate command runs out of letters
[cinnamon-2022-09-09T094617+0200.webm](https://user-images.githubusercontent.com/73538315/189299222-1bf2e9fb-c637-448d-bfcb-a5fcc6a1cbcf.webm)

We should change it to "Excel style" where after `Z` comes `AA` etc. But this issue is not severe enough to further delay #837.

I started to write this but it doesn't quite work yet:

```Javascript
function increment(letters, amount=1) {
  const a = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split('');
  let number = letters.split('').map(l=>a.indexOf(l)).reverse().map((l,i)=>l*26**i).reduce((a,b)=>a+b) + amount;
  const result = [];
  while(number > 0) {
    result.push(a[number%26]);
    number = Math.floor(number/26);
  }
  return result.reverse().join('');
}

console.log(increment("A"));
console.log(increment("J"));
console.log(increment("Z"));
console.log(increment("AT"));
console.log(increment("VZ"));
console.log(increment("ZZ"));
console.log(increment("ZZZ"));
```

It might also be easier and shorter to through each letter and if it is `Z`, increment the previous one or add another `A` in front of it.

---

Second attempt. Even more broken. This is when I realized (again) that it just doesn't work like normal counting because going from `Z` to `AA` is like going from `9` to `11` (or `00`)...

```Javascript
function increment(letters, amount=1) {
  let number = parseInt(letters.split('').map(l=>l.charCodeAt(0)).map(c=>c<75?c-17:c+22).map(c=>String.fromCharCode(c)).join(''), 36);
  number += amount;
  return (""+number).split('').map(l=>l.charCodeAt(0)).map(c=>c<75?c+17:c-22).map(c=>String.fromCharCode(c)).join('');
}
```

---

Third attempt. Seems to be working.

```Javascript
function increment(letters, amount=1) {
  let result = [];
  for(const letter of letters.split('').reverse()) {
    const next = letter.charCodeAt(0)-64+amount;
    amount = Math.floor(next/26);
    result.push(next%26);
  }
  if(amount)
    result.push(amount);
  return result.reverse().map(i=>String.fromCharCode(64+i)).join('');
}
```

Nope. `console.log(increment("Y"));` is broken.

---

Fourth attempt. Seems to be working.

```Javascript
function increment(l) {
  const m = l.match(/Z+$/);
  const zs = m ? m[0].length : 0;
  if(m && zs == l.length)
    return 'A'+[...Array(zs)].map(l=>'A').join('');
  else
    return l.substr(0, l.length-zs-1) + String.fromCharCode(l.charCodeAt(l.length-zs-1)+1) + [...Array(zs)].map(l=>'A').join('');
}
```

### PR DESCRIPTION
**Pull request by rogerl50**
Fixes #1322 

Note that this increments the *last* set of capital letters. Is that what's desired? (For example, 'AxxxY' -> 'AxxxZ', not 'BxxxY'.) If not, I think the RE needs to be changed to `/^(.*?)([A-Z]+)([^A-Z].*)?$/`.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1323/pr-test (or any other room on that server)

After merging, a backup will be available at https://beta.virtualtabletop.io/editor/PR1323-pr-test.

**Comment by ArnoldSmith86** [comment]
I tried to make 100 copies and it didn't finish in minutes.

**Comment by rogerl50** [comment]
> I tried to make 100 copies and it didn't finish in minutes.

One of these days I will stop being in a hurry and careless. One of these days.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Works as expected.  But now it makes me not like the widget tree so much.  The widget tree lists in true alphabetical order so A, AA, AB, AC, B, C, D although the widgets were created in order A, B, C, D, AA, AB, AC.  Not a complaint and no need to fix.  Just an observation.

**Comment by rogerl50** [comment]
> Approved through test. Works as expected. But now it makes me not like the widget tree so much. The widget tree lists in true alphabetical order so A, AA, AB, AC, B, C, D although the widgets were created in order A, B, C, D, AA, AB, AC. Not a complaint and no need to fix. Just an observation.

Agreed. But I'm not sure what else you would do....

**Comment by rogerl50** [comment]
@ArnoldSmith86 OK to merge as is?

**Review by RaphaelAlvez — APPROVED** [review]
I like the concept very much

**Review by ArnoldSmith86 — APPROVED** [review]
I don't see a problem merging this. I didn't test it a lot but others did and it would only break duplicating widgets..

**Pull request merged**
