### PR TITLE
fixed background position in Blue

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The usual...

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1694/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1694-pr-test`.

**Review by 96LawDawg — APPROVED** [review]
Here's a Jan-like approval:  Code looks fine.

**Review by RaphaelAlvez — APPROVED** [review]
Code reviewed

**Review by RaphaelAlvez — CHANGES_REQUESTED** [review]
Actually you only updated one variant

**Comment by ArnoldSmith86** [comment]
True. The error is only in one variant but I totally didn't update the metadata.

**Comment by ArnoldSmith86** [comment]
> Actually you only updated one variant

Fixed. And fixed TestCafé.

**Comment by 96LawDawg** [comment]
Tested and reviewed and approved again.

**Pull request merged**
