### PR TITLE
Recolor widgets

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
Recolor to fit the style. All changes were discussed in a meeting.

You can compare the CSS I implemented with the original from this link: https://virtualtabletop.io/color

On top of that, all colors are in variables now and users can recolor by setting variables. This include on hover colors.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3262/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
for some reason some comits from @96LawDawg that I didn't touch were included in this PR.

**Comment by 96LawDawg** [comment]
The spinners change does not work.  It looks fine in the colors room you provided.  But it doesn't work in the test room.  Spinners should not look like this:
Screenshot 2021-03-10 180820

**Comment by RaphaelAlvez** [comment]
Thanks I'll check that later. I must have accidentally deleted one line

**Comment by RaphaelAlvez** [comment]
New PR created from local branch

**Pull request closed without merging**
