### PR TITLE
added simple JSON editor command to add a dynamic expression

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Sooner or later I will expand this but for now it just adds two simple buttons: one adds `"var increment = ${variableName} + 1"` and one adds `"var random = randInt 1 10"`.

I also removed `RANDOM` from the JSON editor commands.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3488/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
That's a good start.  If nothing else, it is a placeholder that will add the right indentation and format.  Approved through test.

**Comment by bjalder26** [comment]
I tried it out in a clickRoutine, changeRoutine, and an xChangeRoutine.  No issues.  I'm not sure what else could be tested.

With this, maybe consideration should be given to replacing the RANDOM function altogether with the dynamic expression.  My thought is that it is something that is very easy to do in the JSON editor, and a very easy dynamic expression to understand.  At the same time, it is very useful for a lot of games.  So it MIGHT encourage people to use the JSON editor and dynamic expressions.  We could possibly have a tutorial just showing people how to get a random number as a way to push the JSON editor and dynamic expressions.

**Comment by ArnoldSmith86** [comment]
> With this, maybe consideration should be given to replacing the RANDOM function altogether with the dynamic expression.

There is no `RANDOM` anymore.

**Comment by bjalder26** [comment]
> > With this, maybe consideration should be given to replacing the RANDOM function altogether with the dynamic expression.
> 
> There is no `RANDOM` anymore.

Given the changes made in my JSON, I should have realized that, but I guess I didn't notice with all the other changes.  Maybe this PR should be expedited to get RANDOM out of the JSON editor.

**Pull request merged**
