### PR TITLE
Edit Mode converts width and height to float value

### PR DESCRIPTION
**Pull request by bjalder26**
This is to address issue #708

Changes:
- Width and height are converted to float values instead of strings
- Value is taken from the text input rather than the range (slider), so that it will not round values to nearest range (slider) step (currently every 10 px)
- Width and height will not update if a valid number is not entered (numbers and possibly a decimal point)

This only affects tokens, boards, and labels as they are the only widgets that have a width and height in Edit Mode.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3709/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
Thanks I'll review it as soon as possible. It was an oversight from myself. Just from code review this looks ready to go.

**Comment by bjalder26** [comment]
> Thanks I'll review it as soon as possible. It was an oversight from myself. Just from code review this looks ready to go.

I just realized that editMode will round the height and width to multiples of 10 anyway.  So I figure that either I should change this to parseInt() (and consider changing the step value to 1 if we don't want it to round), or if we want it to allow decimals, then the range should be given a smaller step value (e.g. step="0.1").

Unfortunately, a smaller step value would also mean that it will be harder to get the exact number you want (assuming it coincides with the steps).

**Comment by RaphaelAlvez** [comment]
> I just realized that editMode will round the height and width to multiples of 10 anyway.  So I figure that either I should change this to parseInt() (and consider changing the step value to 1 if we don't want it to round), or if we want it to allow decimals, then the range should be given a smaller step value (e.g. step="0.1").
> 
> Unfortunately, a smaller step value would also mean that it will be harder to get the exact number you want (assuming it coincides with the steps).

Unless I did something worth, text input should at least already allow any unit value. Having it allow any decimal value is reasonable.
The scroll bar needed to have this rounding to be useful and enjoyable.

**Comment by bjalder26** [comment]
> Unless I did something worth, text input should at least already allow any unit value. Having it allow any decimal value is reasonable.
> The scroll bar needed to have this rounding to be useful and enjoyable.

I think I figured it out.  It was getting the value from the range (slider) instead of getting it from the text input.  I think now it SHOULD work as intended.

**Review by RaphaelAlvez — APPROVED** [review]
sted both version. #710 is indded better

**Pull request merged**
