### PR TITLE
fixed that SELECT type would not work for cards in piles

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
SELECTing children of a holder with type:card did not work properly if they were inside a pile because the pile would be discarded before it would be resolved.

I also added that if you specify type:pile, the piles would not be resolved.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3171/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Tested using [http://212.47.248.129:3171/mike](url) and a modified version of the move view routine in Bug Chess.  Still strange behavior with moving piles programmatically because the drag handle gets left behind.  Also, debug does not show the id of the pile.

**Comment by ArnoldSmith86** [comment]
```
  "property": "type",
  "value": "pile",
```

That will resolve the pile. `"type": "pile"` won't.

**Comment by 96LawDawg** [comment]
Thanks for the clarification.  That works now for piles outside a holder.  Piles inside a holder still get resolved if using "type":"pile."  Is that the intended behavior or did I screw something else up?

**Comment by ArnoldSmith86** [comment]
> Thanks for the clarification. That works now for piles outside a holder. Piles inside a holder still get resolved if using "type":"pile." Is that the intended behavior or did I screw something else up?

The button in the top left of http://212.47.248.129:3171/pr-test selects the pile inside the holder. Do you have a specific example that doesn't work for you (>2 months later :D )?

**Comment by 96LawDawg** [comment]
> The button in the top left of http://212.47.248.129:3171/pr-test selects the pile inside the holder. Do you have a specific example that doesn't work for you (>2 months later :D )?

Yes and no.  I think I was probably still not doing it right when I posted that.
```    
      "func": "SELECT",
      "type": "pile",
      "property": "type",
      "value": "pile"
```

The above works, but it seems like an extra step.  It seems counter-intuitive to need type, property, and value to get that result.  This PR was created to solve a problem identified by my screen shift routine that stopped working after #87 was merged.  Bug chess still uses that old routine, so I tested on it.  It works, except for not moving the pile drag handle, which I pointed out before.  You can see that in the test room.

**Comment by ArnoldSmith86** [comment]
> It works, except for not moving the pile drag handle, which I pointed out before.

If the pile handle isn't moving, you're not moving the pile but the cards inside it.

The `type: pile` is always _in addition_ to the usual `property` and `value`. So it doesn't have to be `property: type, value: pile` but if you just do `type: pile`, it will use the default `property: parent, value: null`.

I'm pretty sure it works as intended but I agree that it's not exactly the easiest to use. I would say it's good enough for now because piles will go away soon™.

I updated the example in the test room to work as expected. I left out all defaults which probably doesn't help. :D

**Comment by 96LawDawg** [comment]
This shouldn't be so hard, but it is.  I don't understand why what I did doesn't work and why what you did does.  Don't explain it to me.  I'll just have to relearn it soon (TM).

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  I tested it at the same time as my last comment, I just didn't put in the "approve" section.

**Pull request merged**
