### PR TITLE
fixed that leaveRoutine would be called twice and that enterRoutine and leaveRoutine are called for a pile and not its children

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This PR fixes basically a typo that caused leaveRoutine to be triggered twice.

It also fixes that when you drag a pile into a holder, the enterRoutine would be called once for the pile and not once per child of the pile.

I also noticed that enterRoutine would be called again if you drag a card inside a holder without ever leaving it.

Please test if there are related issues. For example I did not test if MOVEing and SETing cards into the holder (still) works as expected.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3495/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
Setting parent to null does not trigger leaveRoutine.

**Comment by robartsd** [comment]
MOVE XY does not trigger leaveRoutine

**Comment by ArnoldSmith86** [comment]
>  Set parent (card): triggers enterRoutine once per each card. However, **if I SELECT for a SINGLE CARD, then SET its parent, then the WHOLE PILE is moved** in and each card triggers enterRoutine.

This is probably unrelated issue #496. Please test it using a second `SELECT` that re-applies `max` to the collection (or use another way to select one card - by ID or whatever).

**Comment by bjalder26** [comment]
> > Set parent (card): triggers enterRoutine once per each card. However, **if I SELECT for a SINGLE CARD, then SET its parent, then the WHOLE PILE is moved** in and each card triggers enterRoutine.
> 
> This is probably unrelated issue #496. Please test it using a second `SELECT` that re-applies `max` to the collection (or use another way to select one card - by ID or whatever).

This is a bit confusing, but I had parent == null as part of the default of that selection.  So I THINK what was happening is that none of the cards were directly selected because they all had the pile as a parent.  However, I THINK the pile was passing the parent == null test, then passing on ALL of the cards in the pile into the selection, which then passed the card type test, or maybe piles pass the card type test.  So all the cards were getting selected and moved.

I set it to parent != null, and it moves 1 card (as expected).

**Comment by ArnoldSmith86** [comment]
The mentioned problems are pretty much the biggest problems we still have that are pile-related. I will look at this again and try to solve them. If I can, I vote for keeping piles as widgets like they are now and continue fixing the problems they still have.

**Comment by ArnoldSmith86** [comment]
Test cases also need to include `CLONE` and the split feature of piles (which was mentioned somewhere already).

**Comment by ArnoldSmith86** [comment]
Bigger fixes to these problems will need to wait for the planned change where games can be loaded on older server versions.

**Pull request closed without merging**
