### PR TITLE
Formalize use of dropTarget and dropLimit on non-holder widgets

### PR DESCRIPTION
**Pull request by 96LawDawg**
As recently mentioned in Discord, it is possible to allow cards or any other widget to become a parent just by including dropLimit and dropTarget properties on the widgets that will be the parents. This just adds the default null value in widget.js so the JSON Editor recognizes that and recolors the properties yellow.

The wiki has also already been updated. This has been a hidden feature that we just did not realize existed until today.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2253/pr-test (or any other room on that server)

**Review by ArnoldSmith86 — APPROVED** [review]
It ended up being a nightmare to simply fix the need to reload the room to apply `dropTarget`. Oh well, it should work now. The code change is pretty simple but the automated tests and the code minifier didn't like it.

I also made all widgets default to `dropLimit: -1`. I don't see this breaking anything and it'll prevent hours of frustration...

Feel free to merge if you agree. Or start a discussion if you don't. :grinning:

**Comment by 96LawDawg** [comment]
Those do look like substantial changes to the minifier.  I wonder if that is what is causing my problem.  I opened this PR up, with your changes, on my local machine, but all I get is "Loading room..."  I deleted all the room and state and tried again and nothing.  But no problem opening other PRs or main.  I was going to update a tutorial showing how to do this (with the css overflow), but I can't get my local setup working.  Any idea?

**Comment by RaphaelAlvez** [comment]
Is this PR going two things at once? I see some code that I wouldn't expect needed and the branch name also indicates it has other goals.

**Comment by 96LawDawg** [comment]
I don't think so.  The branch name was what I thought the basic fix should be.  But it needs to work without forcing a refresh.  All the other code does that.

**Comment by ArnoldSmith86** [comment]
> I opened this PR up, with your changes, on my local machine, but all I get is "Loading room..." I deleted all the room and state and tried again and nothing.

Anything in the console?

**Comment by 96LawDawg** [comment]
> Anything in the console?

Uncaught SyntaxError: Identifier 'toServer' has already been declared

**Comment by ArnoldSmith86** [comment]
Does it work on the PR test server?

**Comment by ArnoldSmith86** [comment]
Does this help?

**Comment by ArnoldSmith86** [comment]
Does it work with either `"minifyJavascript": false` or `"minifyJavascript": true` in `config.json`? Can you send me the broken source code (CTRL+U in browser)?

**Comment by 96LawDawg** [comment]
Based on discussion in Discord at https://discord.com/channels/770758631146782780/770758631146782783/1276544777860546713, I reverted @RaphaelAlvez's  changes.  I think this should be ready to merge.  Any final comments from any body?

**Comment by RaphaelAlvez** [comment]
> Based on discussion in Discord at https://discord.com/channels/770758631146782780/770758631146782783/1276544777860546713, I reverted @RaphaelAlvez's  changes.  I think this should be ready to merge.  Any final comments from any body?

Was the property name the only problem?

I think it's least good to incorporate the features where we expect them to be used

**Review by RaphaelAlvez — APPROVED** [review]
Tested.

Feel free to ignore my previous comment if you disagree with it.

**Pull request merged**
