### PR TITLE
Fix visibility of basic widgets in edit mode, #248.

### PR DESCRIPTION
**Pull request by rogerl50**
Sorry about three commits...

### CODE REVIEW

**Comment by robartsd** [comment]
I think 65% opacity is too much (but I don't care that much about it either).

**Comment by RaphaelAlvez** [comment]
I tried adding a border. What do you guys think? @rogerl50 hope you don't mind. Thanks for taking the task.

**Comment by rogerl50** [comment]
> This still doesn't fix the basic problem that Raphael brought up. See http://212.47.248.129:3256/Mike where many of the basic widgets are still invisible. I also think 65% is too much. Maybe 35%?

Which widgets are invisible? (The notes at the bottom don't appear to me to be widgets, at least they are not clickable in edit mode).

**Comment by rogerl50** [comment]
> I tried adding a border. What do you guys think? @rogerl50 hope you don't mind. Thanks for taking the task.

I don't mind, but I didn't think it looked very good, particularly since some of the widgets are much smaller than the bounding box.

**Comment by RaphaelAlvez** [comment]
> > I tried adding a border. What do you guys think? @rogerl50 hope you don't mind. Thanks for taking the task.
> 
> I don't mind, but I didn't think it looked very good, particularly since some of the widgets are much smaller than the bounding box.

The one that is just a blue background.

I don't like it either but I don't know any other solution

**Comment by RaphaelAlvez** [comment]
You are totally right. Labels border is really a problem

**Comment by rogerl50** [comment]
Closed until we are clear on what should actually be done.

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3256/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Borders are ugly.  BUT, it does show the size of the object and at least makes all invisible objects visible in edit.  On the other hand, in really complicated setups, it makes things even worse.  Compare the current version of Reward in edit mode:

Current

With the proposed version:

Proposed

On balance, I think we should NOT include labels.

**Comment by rogerl50** [comment]
Closing, will reopen when I fix my Git config.

**Comment by robartsd** [comment]
> The discussion at https://www.geeksforgeeks.org/how-to-apply-colored-shadow-and-border-properties-to-a-grayscale-image/ indicates that it is possible to create a blue border rather than a gray one for widgets with images, but it requires CSS such as
> 
> ```css
> <div class="widget basic"> 
>         
> </div> 
> ```
> 
> instead of the current approach using the `background-image` CSS tag. I have no idea what doing this would break, and it doesn't seem trivial to do in any case.

It should be feasible to change the DOM structure. Would need to be aware of how this will change the image behavior relative to other children of the widget's DOM element might change (anonymous text elements if the widget also has a text property, child widgets). If the image is a DOM element, we could also better support accessibility properties for the image.

**Comment by RaphaelAlvez** [comment]
Yeah I'm long term that would be great. We already have to think about including symbols when making games

**Pull request closed without merging**
