### PR TITLE
COMPUTE with toFixed, parseFloat, randint and randrange

### LINKED ISSUE #345: Decimals without leading zeros are not treated as numbers
The COMPUTE function treats ".2" as a text string and treats "0.2" (or any other number like 17.2) as a number.  So adding ".2" and ".2" gives you a concatenated value of ".2.2" rather than ".4."  I guess it is possible that some people would want a string to start with a decimal, but it seems like this should be treated as a number.

### PR DESCRIPTION
**Pull request by larkob**
Resolves #345 which needed the addition of COMPUTE operations dealing with decimal numbers. I also added two functions to generate random whole numbers based on the Python equivalent.

The new functions are:
* toFixed: converts a number into a string, rounding the number to keep only the specified amount of decimals
* parseFloat: parses a string and returns a floating point number. It determines if the first character in the specified string is a number. If it is, it parses the string until it reaches the end of the number, and returns the number as a number, not as a string.
* randInt: generates a random integer in a min-max range, including the end points (identical to RANDOM button operation)
* randRange: generates a random integer in a min-max range, excluding the max point. Allows to set a step interval (defaults to 1).

Note that COMPUTE currently applies default values of 1 for operands - which is going to be changed eventually, so it is strongly recommended to specify each operand and not rely on the default value.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3357/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
I accidentally deleted the small test room you built while I was working on my own.  But I think I duplicated the functionality in a way that will be easy to add to the existing tutorial.  Tested all functions.  All work as designed.  Approved.

**Review by rogerl50 — APPROVED** [review]
Tested toFixed and parseFloat. Both seem to work. It is sad that parseFloat returns the expected 0.75 when fed 0.2 and 0.55, but returns 0.35000000003 when fed -0.2 and 0.55. Floating point arithmetic sucks.

**Review by ArnoldSmith86 — APPROVED** [review]
Code looks good to me.

**Pull request merged**
