### PR TITLE
crash fixes for JSON editor + "go to error" command

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Error checking in the JSON editor commands was all over the place and it crashed pretty often while editing the text.

I refactored the error checking to be global (not in each command) so hopefully there are less problems now.

I also added the "go to error" command again after @larkob unintentionally removed it because it was part of the superfluous "apply changes" command.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3284/pr-test (or any other room on that server)

**Comment by larkob** [comment]
There's a Firefox-only issue with adding a newline (Enter/Return key) at the end of the last property within an object or array. It adds a newline, but the blinking cursor stays at the end of the line. Only when you start typing, you see the blinking cursor in the new line.

Otherwise I've found no issues and no more crashes.

**Comment by ArnoldSmith86** [comment]
True but I don't think this was introduced in this PR.

**Comment by larkob** [comment]
Right.

**Review by larkob — APPROVED** [review]
Tested and seems to be working fine.

**Pull request merged**
