### PR TITLE
Fantasy Wars Update

### PR DESCRIPTION
**Pull request by Ingegneus**
Fantasy  Wars update, plus my first PR! Lets see how much I can mess up.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1643/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1643-pr-test`.

**Comment by Ingegneus** [comment]
ok I feel like a wizard now. 
I am using vs code with the "GitHub Repositories", "Remote Repositories" and "GitHub Pull Requests and Issues" extensions. I can't figure out how to edit the assets from the game...

**Comment by 96LawDawg** [comment]
If you are running a copy of the engine on your local machine, you can edit the game (and the assets) there just like if you were on VTT. You first need to changed the setting in config.json to allowPublicLibraryEdits (or something like that—away from my computer so can’t check) to true. That will enable an “Add to Public Library” button when adding games and will allow you to edit existing PL games.

**Comment by 96LawDawg** [comment]
I don't have any comments about the game itself.  Obviously @Ingegneus and @RaphaelAlvez know way more about that than I do.  I would just clean up the instructions a bit (no space between some sentences, no space between some paragraphs currently).  Add @Ingegneus to the attribution.  And specify the license for each asset (Unsplash is Unsplash License, game-icons.net is CC BY 3.0, and Vecteezy is the Vecteezy License).

**Comment by Ingegneus** [comment]
I've made my changes in #1644, so this pr is obsolete

**Pull request closed without merging**
