### PR TITLE
added empty click method to widget.js

### PR DESCRIPTION
**Pull request by robartsd**
Widgets without a click method can trigger an error in click routines.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3143/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Sorry, should have checked PRs first.

I might prefer your solution but then we should remove all the `if(widget.click)` conditions throughout the codebase. An example is in `mousehandling.js`.

**Review by rogerl50 — COMMENTED** [review]
Solves the problem in my (buggy) button routine reported in #141.

**Comment by robartsd** [comment]
> Sorry, should have checked PRs first.
> 
> I might prefer your solution but then we should remove all the `if(widget.click)` conditions throughout the codebase. An example is in `mousehandling.js`.

I also should have assigned the issue to myself when I decided to code for it.

**Review by rogerl50 — APPROVED** [review]

**Comment by ArnoldSmith86** [comment]
Well. Now there's one more. I forgot to remove my pull request. :D

**Comment by robartsd** [comment]
Issue fixed in another pull request.

**Pull request closed without merging**
