### PR TITLE
STAGING 2021-06-12: contains multiple PRs for testing

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This includes #95, #400, #435, #444, #457, #466, #469, #493, #495, #521, #522, #528, #531, #537, #539, #540, #547, #548, #552, #557, #558, #559, #560.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3561/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
In case anyone wants to poke around in today's trace file:

[pr-test-1623506888891.trace.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/6642952/pr-test-1623506888891.trace.zip)

(extract the zip, press `CTRL`+`F9` on the test server of this PR and select the trace file)

So far it's more of a replay viewer than an analytics tool though. There's a lot of stuff in the trace file though and I will use it to build better tools around it (and hopefully fix the bugs we encountered).

**Comment by ArnoldSmith86** [comment]
Changing `"value1": 1,` to `"value1": 1,,` and then removing the comma changes the JSON editor context to `basic`.

```JSON
{
  "type": "deck",
  "id": "taskDeck",

  "x": 0,
  "y": 0,
  "width": 86,
  "height": 86,

  "movable": true,
  "movableInEdit": true,

  "cardDefaults": {
    "width": 76,
    "height": 120
  },
  "cardTypes": {
    "green6": {
      "difficulty3": 1,
      "difficulty4": 1,
      "difficulty5": 1,
      "text1": "win",
      "value1": 6,
      "css": "--color1:green; --x1:120px; --y1:40px; --scale1:1.5"
    },
    "yellow1": {
      "difficulty3": 1,
      "difficulty4": 1,
      "difficulty5": 1,
      "text1": "win",
      "value1": 1,
      "css": "--color1:yellow; --x1:120px; --y1:40px; --scale1:1.5"
    },
    "firstTrick": {
      "difficulty3": 1,
      "difficulty4": 1,
      "difficulty5": 1,
      "text1": "win the first trick"
    }
  },
  "faceTemplates": [
    {
      "objects": [
        {
          "type": "image",
          "x": 0,
          "y": 0,
          "color": "darkblue",
          "valueType": "dynamic",
          "value": "image",
          "width": 76,
          "height": 120
        },
        {
          "type": "text",
          "x": 0,
          "y": 10,
          "fontSize": 30,
          "valueType": "dynamic",
          "value": "difficulty3",
          "textAlign": "center",
          "width": 76
        },
        {
          "type": "text",
          "x": 0,
          "y": 45,
          "fontSize": 30,
          "valueType": "dynamic",
          "value": "difficulty4",
          "textAlign": "center",
          "width": 76
        },
        {
          "type": "text",
          "x": 0,
          "y": 80,
          "fontSize": 30,
          "valueType": "dynamic",
          "value": "difficulty5",
          "textAlign": "center",
          "width": 76
        }
      ],
      "css": "color: white; font-weight: bold"
    },
    {
      "objects": [
        {
          "type": "image",
          "x": 0,
          "y": 0,
          "color": "lightblue",
          "valueType": "static",
          "value": "",
          "width": 76,
          "height": 120
        },
        {
          "type": "text",
          "x": 0,
          "y": 0,
          "color": "black",
          "valueType": "dynamic",
          "value": "text1",
          "textAlign": "center",
          "width": 76,
          "height": 120
        },
        {
          "type": "text",
          "x": -100,
          "y": 0,
          "fontSize": 50,
          "color": "white",
          "valueType": "dynamic",
          "value": "value1",
          "textAlign": "center",
          "width": 38,
          "height": 60,
          "css": "background-image: linear-gradient(90deg, var(--color1) 1%, var(--color1) 1%); transform: translate(var(--x1), var(--y1)) scale(var(--scale1)); border: 1px solid white; border-radius: 5px"
        }
      ]
    }
  ]
}
```

**Comment by robartsd** [comment]
> Changing `"value1": 1,` to `"value1": 1,,` and then removing the comma changes the JSON editor context to `basic`.

Same on production.

**Comment by ArnoldSmith86** [comment]
OK. Didn't want to interrupt my deck creation. Guess I'll open an issue later then.

**Pull request closed without merging**
