### PR TITLE
parallelize testcafe tests on GitHub

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This PR splits Firefox and Chrome TestCafé tests in separate workflows. That should hopefully make it run in parallel.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1159/pr-test (or any other room on that server)

**Review by robartsd — APPROVED** [review]
Nice to have Testcafe tests completing faster.

**Comment by ArnoldSmith86** [comment]
We could also split the Compute test into its own workflow. That one probably doesn't need to be run on both browsers?

**Comment by robartsd** [comment]
I agree on splitting Compute out from the rest of TestCafe, but I think I'd still run in both browsers.

Even if both TestCafe tests don't complete faster, the first to complete is sooner than when they were combined. Also I have yet to see both experience timeout failures on the same commit, so it is easier to identify failures that should just be re-run vs. failures that mean the code needs to change.

**Pull request merged**
