### PR TITLE
added multi-selection commands for setting a parent

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Select multiple widgets, click into the JSON editor until #2259 is fixed, click `make child`. It will set the `parent` for all widgets to the biggest selected widget and set `x` and `y` to compensate for the parent coordinates.

Should probably get a better name and be smarter - right now it only works if all widgets had the same `parent` before and are not scaled.

---

Todo:
- [x] Rename the button. :grin: 
- [x] Provide a way for the user to select the new parent.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2260/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Probably this works most of the time.  Would it make more sense (and not be too much trouble) to select the widgets you want to re-parent and then after pressing "make child" you select the new parent (either by clicking in the room, or entering an id)?  I guess most of the time the largest widget would be the norm, but not always.  And that is not intuitive.  For example, if I have a seat, a holder, and some tokens I could select them all thinking the seat is going to be the parent.  But it would be the holder.

And instead of "make child," which sounds vaguely like a reproductive act, if you make my suggested change, then maybe the button is "select parent."

**Comment by ArnoldSmith86** [comment]
I renamed the existing command to `set biggest as parent` and added a new `enter new parent ID` command that spawns a text input option.

Ideally you would instead either select the new parent by clicking on it or offer the selected widgets in a dropdown but both of those need changes to the way JSON commands work.

**Review by 96LawDawg — APPROVED** [review]
Approved through test

**Pull request merged**
