### PR TITLE
preserve white space in widget text

### LINKED ISSUE #177: newline character should be supported in all widgets
Currently `\n` works to create a new line in a label but not in other widgets. This is because the label is implemented as a `textarea` element which defaults to presenting white space (`wihte-space: pre-wrap`). Other places where text is presented use `div` elements which default to collapsing white space (`white-space: normal`). I propose that we change the default styling to preserve white space for all widgets presenting text.

### PR DESCRIPTION
**Pull request by robartsd**
closes #177 

This defaults all widgets to `white-space: pre-wrap`. `white-space: pre-line` would also preserve newline characters but collapse horizontal white space characters. Since all widget DOM elements are generated by the js code there shouldn't be any extra whitespace in any of them so `white-space: pre-wrap` should be fine.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3178/pr-test (or any other room on that server)

**Review by ArnoldSmith86 — APPROVED** [review]
Looks fine.

**Comment by RaphaelAlvez** [comment]
Yeah looks good

**Review by RaphaelAlvez — APPROVED** [review]
Tested and approved

**Comment by robartsd** [comment]
As I understand the 24 hour policy, I should merge this tomorrow.

**Pull request merged**
