### PR TITLE
UI Overhaul

### PR DESCRIPTION
**Pull request by mousewax**
This is a work in progress.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4022/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Want to keep this open? Or work in #791 instead?

**Comment by mousewax** [comment]
I think I am going to merge all of these changes into #791. I just need to save some of the markup from 791.

**Comment by mousewax** [comment]
So I think what I would like to do is undo my changes on #791, get that one up to date with current features, and then merge this one into that one. I can move my files over manually and check them in. I have what I need from 791.

**Comment by ArnoldSmith86** [comment]
Same as #791. I'm closing this. #1223 will be merged first and afterwards we can pick commits from this one.

**Pull request closed without merging**
