### PR TITLE
added FOREACH

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This PR adds a new button function called `FOREACH`.

It has a parameter `loopRoutine` which gets called for every element of a collection, array, object or string.

If it gets a parameter `in`, it will call the `loopRoutine` for each element with variables `key` and `value` available inside the routine.

If it gets a parameter `collection`, it will call the `loopRoutine` for each widget of that collection. The routine will receive a variable `widgetID` and a `DEFAULT` collection that contains the one widget of the current iteration.

If `in` and `collection` are not supplied, it will operate on collection `DEFAULT`.

A very simple example:

```
  "clickRoutine": [
    {
      "func": "SELECT",
      "property": "type",
      "value": "button"
    },
    "var increment = 1",
    {
      "func": "FOREACH",
      "loopRoutine": [
        {
          "func": "SET",
          "property": "text",
          "value": "${increment}"
        },
        "var increment = ${increment} + 1"
      ]
    }
  ]
```

Oh, and this fixes JSON editor commands in subroutines.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3525/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
So in the case of an array, only `value` will be passed to the routine, while for an object you get both `key` and `value, I assume? What gets passed in the case of a string?

**Comment by ArnoldSmith86** [comment]
You always get both. `key` is then the index. At least it should be. I never tested if `key` actually works.

**Comment by bjalder26** [comment]
I'm getting some unexpected JSON editor behavior.  If I try and place a `SELECT` between the `FOREACH` and a `SET` it either places it inside the `FOREACH` or after the `SET`.
image

**Comment by bjalder26** [comment]
> So in the case of an array, only `value` will be passed to the routine, while for an object you get both `key` and `value`, I assume? What gets passed in the case of a string?

It appears each letter gets passed in turn as the value during the iteration of a string.

Also, I threw some examples in there.  So far everything appears to work as expected except what I mentioned about the JSON editor.

**Comment by ArnoldSmith86** [comment]
Yeah, the JSON editor isn't exactly perfect in those regards. I'm looking at it right now though. You can insert an operation after the `FOREACH` by placing the cursor on the `FOREACH` but before the `iterationRoutine`.

**Comment by ArnoldSmith86** [comment]
Does that commit help?

**Comment by bjalder26** [comment]
> Does that commit help?

Yes, that appears to have fixed the issue I mentioned with the JSON editor.

**Review by bjalder26 — APPROVED** [review]
I added a button that tests for the key and the value of an object, and another one that has two consecutive forEach that makes an array from an object, then a string from an array.

I even nested forEach functions and that appears to have worked, so I'm approving through testing and suggesting that someone review the code.

**Comment by ArnoldSmith86** [comment]
The longest part of the code is actually backing up the variables `key` and `value` and restoring them after the `FOREACH`...

Would be cool if you could make one or two tests to check if that works as expected..

My idea was basically that all the changes you make inside the `FOREACH` are permanent to the parent routine but everything the `FOREACH` adds by itself (`key`, `value`, `widgetID` and collection `DEFAULT`) is only available inside of it and doesn't override the existing variables/collections for the parent routine.

**Comment by robartsd** [comment]
> My idea was basically that all the changes you make inside the `FOREACH` are permanent to the parent routine but everything the `FOREACH` adds by itself (`key`, `value`, `widgetID` and collection `DEFAULT`) is only available inside of it and doesn't override the existing variables/collections for the parent routine.

Would it be better for all defined variables and collections from the parent routine to be available and update-able in the 'FOREACH' but anything newly defined withn the 'FOREACH' would not be passed back to the parent routine?

**Comment by bjalder26** [comment]
> The longest part of the code is actually backing up the variables `key` and `value` and restoring them after the `FOREACH`...
> 
> Would be cool if you could make one or two tests to check if that works as expected..
> 
> My idea was basically that all the changes you make inside the `FOREACH` are permanent to the parent routine but everything the `FOREACH` adds by itself (`key`, `value`, `widgetID` and collection `DEFAULT`) is only available inside of it and doesn't override the existing variables/collections for the parent routine.

I set up a button in the lower right, which I think tests for "leaky variables" for `key` and `value` (null result).  However, I'm going to have to think about how `DEFAULT` and `widgetID` can be tested. 

Also, I just noticed my nested forEach doesn't work like I expected.  However, maybe it works like it is supposed to, and I just haven't completely wrapped my mind around how this works yet.  I thought it would take each array from a nested array, then take each value from that array, double them, then put everything back as a nested array, but with everything doubled.

It makes a doubled nested array, but each 'small array' has all the values doubled instead of just the 'large array'.

Maybe that illustrates an issue, or maybe I am doing something wrong.  I need to take a break, but I will look at it again later.

**Comment by ArnoldSmith86** [comment]
> It makes a doubled nested array, but each 'small array' has all the values doubled instead of just the 'large array'.

You didn't put `"var newArray = []"` into the outer `FOREACH` so it was not reset between iterations.

**Comment by bjalder26** [comment]
> > It makes a doubled nested array, but each 'small array' has all the values doubled instead of just the 'large array'.
> 
> You didn't put `"var newArray = []"` into the outer `FOREACH` so it was not reset between iterations.

Thanks for figuring that out and fixing it.  I think I've tested for `key`, `value`, `widgetID` and collection `DEFAULT` in such a way to make sure they aren't accessible outside of the `forEach`, and did not find any unexpected behavior (a DEFAULT collection narrowed inside the `forEach` did not have the same `COUNT` as the one outside).  The buttons are in the lower right corner.  The `DEFAULT` collection counts only show up in the debug though.

**Comment by ArnoldSmith86** [comment]
The tests suggest that this can be merged pretty soon.

Any recommendations for better parameter names? (Note that the routine has to end with `Routine`.)

**Comment by robartsd** [comment]
> The tests suggest that this can be merged pretty soon.
> 
> Any recommendations for better parameter names? (Note that the routine has to end with `Routine`.)

Why not just "routine" as there is just the one routine parameter?

Looks like if both `of` and `collection` parameters are provided, `of` is the one that is used and `collection` is ignored. It might be nice to pass `collection` as `DEFAULT` when `of` is used.

**Comment by rogerl50** [comment]
> Why not just "routine" as there is just the one routine parameter?
> 
I think we should keep `iterationRoutine` for clarity, just as we have `clickRoutine` in widgets rather than `Routine`.

**Review by larkob — APPROVED** [review]
Code looks fine to me. I suggest to name the routine `loopRoutine`

**Comment by bjalder26** [comment]
eachRoutine?
foreachRoutine?

**Comment by bjalder26** [comment]
I updated my buttons to use `loopRoutine` and `in`, and they work again.

**Pull request merged**
