### PR TITLE
JSON representation and copy in set()

### PR DESCRIPTION
**Pull request by robartsd**

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3516/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
I uploaded by deal buttons to this server because it creates and shifts an array using a timer.  If you open the JSON editor and select the timer in the upper right, then click on the "Deal 5 to each" button then you will get to see it in action.  Previously using a changeRoutine crashed my client.  It does not do that now, and it is `SET`ting 40 objects in a property array `GET`ting them, shifting them out and `SET`ting the property array again while it is adding more, and doing so in about 5 seconds. 


This one uses changeRoutine and the changes made in this PR: http://212.47.248.129:3516/Interitus
This one uses millisecondsChangeRoutine on the public server:  https://virtualtabletop.io/j1ej

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Recommend code review by Jan, Raphael, or Lars.

**Comment by ArnoldSmith86** [comment]
Gotta think about this a bit. When the title said `get` I was very skeptical but in `set` this might be a good idea.

The array issue that spawned this pretty much works as intended though. That intention can be augmented of course.

**Review by ArnoldSmith86 — APPROVED** [review]
It's probably fine.

**Pull request merged**
