### PR TITLE
Change names of `absolutex` and `absolutey` to `absoluteX` and `absoluteY`

### PR DESCRIPTION
**Pull request by rogerl50**
What it says...

If approved, I'll update the Wiki as well.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3823/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
Approved through code review.  I don't actually know what the code does, but I can see the that changes are only to capitalize the X and Y.

**Comment by bjalder26** [comment]
Honestly it seems the sooner this is merged the better before anyone starts using the pseudo-properties.

**Comment by 96LawDawg** [comment]
> Honestly it seems the sooner this is merged the better before anyone starts using the pseudo-properties.

I agree.  Not a bug, but merging now might help prevent any breaking changes (unlikely since this is brand new, but still).  Merging now.

**Pull request merged**
