### PR TITLE
Adds Timer widget and related features

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The way it currently works is that the client that changes the `paused` property of the timer starts an interval that updates the `seconds` interval every second.

This might not be good enough but I want to play around with it a bit.

(hijacking this space)

To-Do:
- [x] timer widget
- [x] countdown mode
- [X] alert when timer reaches "end"
- [x] "start" property used to reset timer
- [x] TIMER functions for simple automations
- [x] Improve alert
- [x] ~~Running mode (css class)~~ paused mode (css class)
- [x] Editor mode
- [x] test with PR #438  
- [x] weird space in the bottom of the timer when added background (about 5px)
- [x] "clickable": false not working (@ArnoldSmith86 look at please)
- [x] importer: set correct mode properties
- [x] importer: Add timer widget

### see all properties added in the [wiki page](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Widget-Properties#timer)

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3408/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
This will be fun with changeRoutine.  When the timer hits a certain mark, use an IF function to make something happen.  I played around with it.  Nothing but the obvious to point out; when I briefly lost my internet connection, the timer stopped.  I added a couple of buttons to increase and decrease the time by 30 seconds.

One thing it might be nice to show in the JSON is something like: `"paused":false`. Then that status could be changed programmatically rather than by just clicking on it.

**Comment by 96LawDawg** [comment]
This will be fun with changeRoutine. When the timer hits a certain mark, use an IF function to make something happen. I played around with it. No much other than the obvious to point out; when I briefly lost my internet connection, the timer stopped.  When I closed the room on my browser, the timer stopped.  However, when I came back in, I had to press it several times to restart it.  If there were a way to keep the timer going even if I left the room, I think this would be about perfect.  (I did think of a hacky workaround way to do that, but it also requires changeRoutine, which isn't on this branch).

I added some buttons to try to do things programmatically (increase and decrease the time by 30 seconds, start/stop, switch from counting up to counting down).

I recommend you add the greyed out defaults of `paused` and `countdown` so you can see it in the JSON editor all the time (like width and height are greyed out until the default is changed).  Also, you should change the css in the add widget/interactive area to something more readable than the current white.

**Comment by bjalder26** [comment]
The paused property does not show in the JSON when the button attempt to set it to true.  The timer still pauses, but if you look inside the timer in edit, there will not be a paused property.  I am not sure if this causes any real issues or not.

**Comment by 96LawDawg** [comment]
If the timer is running, then the JSON editor is unusable because every second, the cursor moves back to the top of the JSON.  Easy workaround; just stop the timer.  No need to fix (may not even be possible).  Just reporting the behavior.

**Comment by RaphaelAlvez** [comment]
on add widgets overlay the timer is white while it's black on room

timers' children disappear when you change a property of the timer. I added a timer similar to PCIO's timer in /pr-test with children buttons

**Comment by 96LawDawg** [comment]
Some things I've been thinking about lately might benefit from finer time units than seconds (I'm talking about tenths of seconds, not milliseconds.  I know this isn't a high precision instrument, and we wouldn't even have to display the tenths by default.  Just would be cool if it was available in the calculations.

**Comment by Ingegneus** [comment]
I agree with LawDawg. fractions of a second could be used to make some sort of animation where the frames are faces of a basic widget and every 20ms a click happens.

**Comment by larkob** [comment]
What we're trying to accomplish here is just a timer widget for compatibility with PCIO. I'm sure we'll eventually add extra functionality like being able to trigger a routine when it reaches the end, perhaps even a trigger when it is started/paused.

However, I'm not a fan of the timer widget being used to control other things every x ms. That sounds more like a workaround for a standalone feature that should be properly discussed independent of the timer widget.

**Comment by 96LawDawg** [comment]
> However, I'm not a fan of the timer widget being used to control other things every x ms. That sounds more like a workaround for a standalone feature that should be properly discussed independent of the timer widget.

You may be right, BUT with the combination of `changeRoutine` and this, we will be able to trigger things happening at least every second when the widget gets updated.  JavaScript already counts time in ms, so I don't see why another timing thing is needed.  Although if the widget doesn't recognize the state change of ms going by that are not reflected on the screen then `changeRoutine` would not work and a separate timer would be needed.

**Comment by larkob** [comment]
I agree that have such a feature would be great (and I also want it), I just don't think it needs to be tied to the timer. From my point of view, this could be something that runs constantly and is not effected by users temporarily pausing or resetting timer widgets. Also, you could have multiple timer widgets in the room, but for something like a persistent loop every x ms, you only need a single instance. Also, I'm not sure you'd actually want a specific pause between the checks, but rather something that just runs fast and smoothly.

I fear I am digressing, but the use case I have in mind is a label that regularly reads some widget properties, does some calculation and updates its value accordingly, so for instance, it could aggregate the score of cards in a specific holder. This would be perfect for something like a Score Board, but the main point is that this functionality should not require an active timer widget. (And I know it could theoretically be realized with changeRoutines, but I don't want to start a discussion here).

So, what I'm basically asking for is that we collect our ideas in a separate issue and discuss how they could best be realized.

**Comment by RaphaelAlvez** [comment]
Ok lot of stuff to tackle. Everything here is my opinion.

- Should timers be used to trigger routines?

Yes and this was already discussed in a meeting with approval. Change routine was the chosen way to implement it. Especially routines that are executed after x time has passed.


- Is 1 second update to much?

Probably that will be a problem. In some situations one second will feel like a delay. I agree that ms may cause problems or simply be to much. Maybe we can always round up to the next 100 ms? Or just display it in seconds with one decimal?


- Should we have a way to trigger automations without a timer?

Yes and again already agreed on meetings. Some sort of dynamic automation can be used to make labels, tables, counters and other widgets that respond to other interactions on the board.

**Comment by 96LawDawg** [comment]
And what Raphael said about one decimal (tenths of a second) is all I was asking for originally.

**Comment by ArnoldSmith86** [comment]
I don't think the current approach is good enough. I'll revisit this after a few more pressing issues.

**Comment by RaphaelAlvez** [comment]
Ok so I looked at the automation on PCIO and I think that the timer should be added in it's lain current mode and the buttons that come with it should be added with the automations used in PCIO. I also suggest dropping the ▶ and ⏸ button that keeps flipping and go with a ⏯ button.

Also I propose that we include an end to timers and a start for easy reset, a property that says that said timer has ended, a property that stops the timer when it has reached the end time, an startRoutine and an endRoutine

**Comment by ArnoldSmith86** [comment]
You can now play around with a timer and `changeRoutine`. Pretty much everything about the timer will change but it will always trigger its `changeRoutine` in an interval.

**Comment by 96LawDawg** [comment]
And VTT's first animation routine is complete.  Not much more advanced than Bell saying "Mr. Watson, come here. I want to see you."  But it's something.  http://212.47.248.129:3408/LawDawg

**Comment by bjalder26** [comment]
Timer should probably be added as a type in the JSON editor.

**Comment by RaphaelAlvez** [comment]
Added "precision" property that defaults to 1 (line 15)

precision gets applied to the interval (line 51) and to the seconds (line 56)

The precision will be corrected to 0.1 if user tries to set a lower value

There is still a problem that I treied to solve on line 56 where every so often the seconds are set to something like 52.000000002

@ArnoldSmith86 please take a look at the rounding problem maybe you can find a solution.
Also maybe there is a more correct way to do what I did on line 51

**Comment by robartsd** [comment]
To avoid rounding errors, it might be better to set the precision in milliseconds.

**Comment by RaphaelAlvez** [comment]
> To avoid rounding errors, it might be better to set the precision in milliseconds.

This wouldn't solve the problem.
The error is on a much smaller scale.
I'm getting values like 170.20000000000002 (seconds) (expected 170.2)
in milliseconds that would be 170200.00000000002

the problem is that 170.20000000000002 != 170.2

**Comment by ArnoldSmith86** [comment]
@RaphaelAlvez I made a few changes. I changed everything "second" to "millisecond". Like @robartsd says, this solves everything about rounding and comparing because they will always be integers. I believe it's the right move if we allow fractions of seconds.

I changed the alarm logic to use a property `alarm` so you can easily react to it using an `alarmChangeRoutine`.

In general _every_ `widget.set` needs to be preset with an `await`.

**Comment by 96LawDawg** [comment]
A strange thing is happening with the checker in http://212.47.248.129:3408/LawDawg.  It really lags behind the cursor.  Not sure why.  Even if both timers are paused, you still get the effect.  The same thing does not happen to the spinning cards.

**Comment by ArnoldSmith86** [comment]
It's the `"css": "transition: transform 0.15s"`. It causes all changes to rotation and position to take 0.15s.

**Comment by RaphaelAlvez** [comment]
I added buttons to the default timer (mostly for compatibility and the reset button)
We are reaching the end of this PR content-wise. Maybe it's time for feedback

**Comment by 96LawDawg** [comment]
svgReplaces (using #ffffff) works fine.  The only thing I thought was strange was that the buttons disappear completely after use.  I'm not sure that is the most intuitive behavior that users would expect.

**Comment by ArnoldSmith86** [comment]
That needs #438 merged.

**Comment by RaphaelAlvez** [comment]
That bug will be fixed once PR #438 gets merged

**Comment by larkob** [comment]
I know PCIO uses two routines, but there's actually no reason to follow that approach. Here's my proposal:

```
{
  "func": "TIMER",
  "collection": "timerID",
  "change": "reset"
},
{
  "func": "TIMER",
  "collection": "timerID",
  "change": "set",
  "value": 30
},
{
  "func": "TIMER",
  "collection": "timerID",
  "change": "pause"
}
```

**Comment by RaphaelAlvez** [comment]
> I know PCIO uses two routines, but there's actually no reason to follow that approach. Here's my proposal:
> 
> ```
> {
>   "func": "TIMER",
>   "collection": "timerID",
>   "change": "reset"
> },
> {
>   "func": "TIMER",
>   "collection": "timerID",
>   "change": "set",
>   "value": 30
> },
> {
>   "func": "TIMER",
>   "collection": "timerID",
>   "change": "pause"
> }
> ```

That was one approach I really needed feedback on.

I'm not a big fan of the functions' names and I code wise that would be ok to do.

The counterarguments I can see is that it does make the code cleaner if you just want to reset a timer since there are 2 defaults, keeps consistency accros Platforms and this might make duplicates in the code relating to the paused func

**Comment by ArnoldSmith86** [comment]
I prefer Lars' solution. Compared to other functions it seems like overkill to have two explicitly for timers.

**Comment by larkob** [comment]
I've added the importer functions that would be compatible with my proposal.

**Comment by RaphaelAlvez** [comment]
Value can be a property of the timer (string)
Added "seconds" as alias to value input that is multiplied by 1000 (converted to milliseconds)
There is only one TIMER func now with all the previous modes
Reset now also pauses the timer as in PCIO

**Review by 96LawDawg — APPROVED** [review]
Approved through extensive testing.

**Review by RaphaelAlvez — APPROVED** [review]
@ArnoldSmith86  This is ready for merging in my opinion

**Pull request merged**
