### PR TITLE
`CANVAS` mode `setPixel` coordinate validation

### LINKED ISSUE #964: CANVAS function, mode: setPixel needs error checking
The values of x and y in the setPixel mode are scaled percentages from 0 to 99.9.  If a user puts a value that is negative or 100 or more, the room freezes.  I'm working on a canvas tutorial and I thought the values were absolute coordinates, which is how I discovered this.  the wiki entry was unclear, so I changed that.  But still need to catch this error in the JSON.

### PR DESCRIPTION
**Pull request by robartsd**
Fixes #964

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3966/pr-test (or any other room on that server)

**Review by ArnoldSmith86 — APPROVED** [review]
Didn't test but the code looks good.

**Comment by robartsd** [comment]
I did very basic testing (tested that I got problems at both ends of the range with both x & y).

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Pull request merged**
