### PR TITLE
add collection to ROTATE, SHUFFLE and SORT

### PR DESCRIPTION
**Pull request by larkob**
This PR adds the collection property to ROTATE, SHUFFLE and SORT

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3294/pr-test (or any other room on that server)

**Comment by larkob** [comment]
I noticed that the `count` property in FLIP and ROTATE defaults to 1, which is non-intuitive when using collections, because you would obviously expect the default to be unlimited when you perform a FLIP or ROTATE on a collection of widgets.

**Review by ArnoldSmith86 — COMMENTED** [review]
Feels like there is way too much code duplication going on here. Don't you think it's better to have a helper function that returns either holder children or a collection?

Also: the `reverse` calls are probably damaging for collections in `SORT`. Needs to be tested at least if you didn't do it already. The purpose is that widgets with the same value remain in the initial order.

**Comment by larkob** [comment]
The reverse sort seems to be working fine in the pr test room.

@ArnoldSmith86 I've tried to refactor with helper functions but I can't do it. That's beyond my coding skills, unfortunately.

**Comment by larkob** [comment]
I will re-do this PR based on new main branch.

**Pull request closed without merging**
