### PR TITLE
fixed editing public library games without assets

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Looks like git does not add empty directories to the repository. Either way, this PR makes sure that a public library game has an assets directory before updating its assets.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1848/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1848-pr-test`.

**Comment by 96LawDawg** [comment]
Did not work.  I created and added an "Unnamed" PL file that only has a pin in it.  No asset directory was created.  I left it uploaded for now so you can see, but that commit obviously needs to be reverted before this is merged.

**Comment by ArnoldSmith86** [comment]
But does it crash if you now add assets to it? That was the problem. I wanted to fix that Nexus still uses links to its assets and it caused a crash.

**Comment by 96LawDawg** [comment]
> But does it crash if you now add assets to it? That was the problem. I wanted to fix that Nexus still uses links to its assets and it caused a crash.

It does not crash.  Works to add assets after the fact.

**Review by 96LawDawg — APPROVED** [review]
Approved through test

**Pull request merged**
