### PR TITLE
label textarea styles and bottom align

### PR DESCRIPTION
**Pull request by robartsd**
refactors label applyDeltaToDOM to explicitly set the height of the text area to fit the content to avoid scroll bars. Min-height prevents text area collapsing smaller than the widget. Padding added to bottom align if twoRowBottomAlign

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3595/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
The textarea size looks like it's fixed for me now. Didn't test anything else.

**Comment by 96LawDawg** [comment]
I was referred here regarding #607.  This PR actually makes it worse.  Again, just using the tutorial Arrays (Evaluating variant), twoRowBottomAlign has no effect and the overflow doesn't create a scroll bar.

In production:

Production

In PR 595:

PR 595

**Comment by bjalder26** [comment]
> I was referred here regarding #607. This PR actually makes it worse. Again, just using the tutorial Arrays (Evaluating variant), twoRowBottomAlign has no effect and the overflow doesn't create a scroll bar.

I was fiddling around in inspect element, and I think in the CSS textareas need to be set to height: inherit.

**Comment by bjalder26** [comment]
The textarea also seems to need to be nudged upwards `transform: translate(0px, -4px);` for whatever reason.  I do not know why.

**Review by RaphaelAlvez — COMMENTED** [review]
Tested some Tutorials and couldn't find any problem.

@96LawDawg I couldn't understand your problem with this PR if there any please approve this

**Review by 96LawDawg — APPROVED** [review]
I misunderstood.  The reason that the example I used went below the area without a scrollbar is because that is what this PR does.  But labels are so messed up right now I don't know what to approve or not.  This does what it is supposed to do.  It also fixes the problem Raphael found on Tittle.  So going to approved based on that.

**Comment by ArnoldSmith86** [comment]
So, wait. Aren't scrollbars a feature? All those one-pixel scrollbars should be fixed somehow but in general I feel like the text should never go outside of the widget dimensions and if it's more than a few pixels, it should show a scrollbar, shouldn't it?

**Comment by 96LawDawg** [comment]
>I feel like the text should never go outside of the widget dimensions and if it's more than a few pixels, it should show a scrollbar, shouldn't it?

I guess that makes sense.  For labels.  Don't want to change the behavior of all widgets, but I think you are right that a label should have a limit on width and height.  If somebody wants more flexibility, they can use a basic widget whose text does not follow height limits (but does follow width limits).

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
Like I said in my last comment: I think we have different ideas about how label widgets should work.

In my mind it should never show any text outside of the defined widget rectangle (`x`, `y`, `width` and `height`). Keep in mind that child widgets still need to work.

If the text is more than a few pixels higher than the widget, it should show a scrollbar. If it's just - let's say - 5px too big, it should just be cut off.

Does anyone have different ideas about how labels should work?

**Comment by 96LawDawg** [comment]
I think we are in violent agreement about labels.

Do you have a different idea about basic widgets and text leaving those defined width/height areas?  Because that would be a seriously breaking change.

**Comment by ArnoldSmith86** [comment]
> Do you have a different idea about basic widgets and text leaving those defined width/height areas? Because that would be a seriously breaking change.

I'm not sure. On the one hand I think no widget should have content (apart from children) outside its area but on the other hand I feel like basic widgets should just show what you throw at them. It doesn't really matter though because - like you said - it's basically impossible to change that now without breaking all kinds of stuff.

**Comment by robartsd** [comment]
> Like I said in my last comment: I think we have different ideas about how label widgets should work.
> 
> In my mind it should never show any text outside of the defined widget rectangle (`x`, `y`, `width` and `height`). Keep in mind that child widgets still need to work.
> 
> If the text is more than a few pixels higher than the widget, it should show a scrollbar. If it's just - let's say - 5px too big, it should just be cut off.
> 
> Does anyone have different ideas about how labels should work?

I don't have strong opinions on how labels should work, but can certainly look into implementing this idea. I would use JS to test the scroll height and set the overflow for the textarea appropriately. Could change DOM representation if needed to wrap the textarea in an element between the widget's primary DIV and the textarea if needed for styling without impact how child widgets would behave.

**Comment by bjalder26** [comment]
I added `height: inherit;` to `.label > textarea {}` on my laptop server, and it appears to get rid of the last issue (the text area extending beyond the label widget).

.label > textarea {
  border: none;
  background: none;
  padding: 0;
  margin: 0;
  color: inherit;
  text-align: inherit;
  font: inherit;
  width: 100%;
  min-height: 100%;
  resize: none;
  **height: inherit;**
}

Left side: production server label without and with text.
Right side: after `height:inherit;` without and with text.
(This label has a lot of padding)
image

**Comment by robartsd** [comment]
I'll consider revisiting this after #951 and #984.

**Pull request closed without merging**
