### PR TITLE
convert `property` in `SET` to string before setting

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Setting `property` in `SET` to `null` leads to removal of all widgets in the collection because `null` is used for deletion in the server-client-communication.

This PR converts `property` to a string before setting it so `null` would lead to property `"null"` now.

I feel like we should extent `setDefaults` to enforce types of parameters but I would do that in another PR because this seems like a pretty big issue.

I did not test this at all so please do so.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3599/pr-test (or any other room on that server)

**Review by bjalder26 — APPROVED** [review]
I tested this and it seems to work fine.  I also checked to see if this would change how numbers and true/false are treated when set as properties, and there is no change there.  They were already converted to strings.

Approve through testing.

**Comment by robartsd** [comment]
> I tested this and it seems to work fine. I also checked to see if this would change how numbers and true/false are treated when set as properties, and there is no change there. They were already converted to strings.

Javascript object keys are always converted to strings, so `object.1 === object['1']`; however `null` is the absence of a value it only becomes `'null'` if you explicitly say you want it represented as a string.

**Comment by robartsd** [comment]
> This PR converts `property` to a string before setting it so `null` would lead to property `"null"` now.

Should we parallel this change in 'GET'. (I'm OK either way, but think it is worth asking the question before we merge this.)

**Comment by ArnoldSmith86** [comment]
> Should we parallel this change in 'GET'.

Sounds reasonable. I added it to `GET` as well.

**Pull request merged**
