### PR TITLE
New players get a random color instead of red

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
reasons: Red is my go-to color in board games and the current setup makes red an unusable color

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3555/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
of course the 2 first player that joint the room would get hues 133 and 131....

image

**Comment by robartsd** [comment]
Better HSL to hex function found on [StackOverflow](https://stackoverflow.com/questions/36721830/convert-hsl-to-rgb-and-hex):
```js
function hslToHex(h, s, l) {
  l /= 100;
  const a = s * Math.min(l, 1 - l) / 100;
  const f = n => {
    const k = (n + h / 30) % 12;
    const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
    return Math.round(255 * color).toString(16).padStart(2, '0');   // convert to Hex and prefix "0" if needed
  };
  return `#${f(0)}${f(8)}${f(4)}`;
}
```

**Comment by robartsd** [comment]
What if we find the hue angle for all existing player colors, find the widest gap in hue colors, then choose a new color in that gap avoiding near hues?

**Comment by robartsd** [comment]
I wasn't sure where the actual color was set (you have a random function in both the server `server/room.mjs` and the client `client/js/overlays/players.js`). So I change the color setting in the server only and that is the one that took. I'm going to try to implement this without changes to the client.

**Comment by RaphaelAlvez** [comment]
> I wasn't sure where the actual color was set (you have a random function in both the server `server/room.mjs` and the client `client/js/overlays/players.js`). So I change the color setting in the server only and that is the one that took. I'm going to try to implement this without changes to the client.

It is in room.mjs but there was a fallback color there so I decided to include a fallback random color.

The toHex function was based on what Arnold did on canvas. I don't really see the problem with it. It works and is 2 lines long.

The hue angles stuff you talked about seems great but is maybe overkill. We can reduce the complexity by using something like this:
'toHex('+Math.floor(Math.random()*15)*24+',100%, 50%)'

This should return a random color between 15 options but now at least the difference between player can be more noticeable

**Comment by robartsd** [comment]
Superseded by #558

**Pull request closed without merging**
