### PR TITLE
significantly improved error handling and logging

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This should prevent almost all server crashes and log useful stack traces.

A major change is that rooms are no longer reset to empty rooms when there's a problem with them. I feel like that really doesn't help us find out what's wrong.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3347/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
I don't see how any of us are going to be able to test this.  Not sure anyone else knows the code well enough.  I recommend someone semi-qualified give it a glance and approve.  Maybe just separate merging this by a day or so from anything else so that if there are errors, we might be able to isolate them better.

**Comment by ArnoldSmith86** [comment]
As for every PR, it's way more important that everything else still works. So it's always extremely helpful if you can test as many games and tutorials as possible.

**Comment by 96LawDawg** [comment]
I tested quite a variety of complex games and tutorials (the ones currently loaded into the test room).  They all seemed to work fine.

**Comment by ArnoldSmith86** [comment]
Thanks for testing! Please approve the PR if you didn't find any problems.

**Comment by larkob** [comment]
The browser crashes when CTRL+clicking any widget in the JSON editor with "Cannot read property 'click' of null". See http://212.47.248.129:3347/larkob

**Review by bowiz2 — APPROVED** [review]
Looks good!

**Comment by ArnoldSmith86** [comment]
> The browser crashes when CTRL+clicking any widget in the JSON editor with "Cannot read property 'click' of null". See http://212.47.248.129:3347/larkob

That was actually just an old bug. After merging the latest changes from `main` it's gone.

**Pull request merged**
