### PR TITLE
clients can now detect a server restart and will reload after a few seconds

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Whenever clients lose the websocket connection, they will automatically try to reconnect after a few seconds.

Especially when we start with version bumps, old client code should not interact with new server code.

This PR sends a timestamp of the server start to the client. If the client detects that the timestamp changed, it will reload itself.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3375/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
I guess this works.  I was sort of able to test it.  I don't know how to cause a server to restart.  I tried freezing up a room in the pr-test room.  I used debug with call.  I waited a bit and nothing happened.  Then I hit refresh.  A few seconds later that warning you put in the code appeared.  I waited about 10-15 seconds and then that screen went away and returned me to the room.  But I think that was a coincidence that locking up the room and a server restart happened at around the same time because I could not repeat the experiment.  But at least I did see the warning text and it did go away.

**Comment by rogerl50** [comment]
> I guess this works. I was sort of able to test it. I don't know how to cause a server to restart. 

I think if you can cause a server restart on demand, that's a reportable bug :)

**Comment by robartsd** [comment]
I think a PR test serve is stopped when the PR is closed and restarted if the PR is reopened.

**Review by 96LawDawg — APPROVED** [review]
Approved based on trust in ArnoldSmith and luck that I saw it happen once.

**Review by RaphaelAlvez — APPROVED** [review]

**Pull request merged**
