### PR TITLE
Change R.E. for non-string non-numeric expressions to exclude `$`

### LINKED ISSUE #643: variable highlight on JSON editor
the regular expresion should try to detect if the `${}` is inside of a string and if not make the `${ }` red
I've made this mistake so many time and I think it is because the color kinds of indicates that you used the right syntax when in fact you did not

### PR DESCRIPTION
**Pull request by rogerl50**
Hopefully fixes #643.

Simple change to the R.E., but I'm not sure what else in colorization might be affected.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1287/pr-test (or any other room on that server)

**Review by RaphaelAlvez — APPROVED** [review]
tested and the problem is fixed

**Review by ArnoldSmith86 — APPROVED** [review]
Like I said: have a look at the "more correct" version. If it's too much effort, this solution is fine.

**Review by ArnoldSmith86 — APPROVED** [review]
New code looks fine to me and it seems to be working.

**Pull request merged**
