### PR TITLE
log and clear widgets that could not be added

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Tentative remaining to-do list:
- [x] Fix messages to be more understandable.
- [ ] Retest

When a new room state is loaded, widgets will be added according to the order in the JSON file. That means that a widget might be added to the room before its parent (or deck). Because that is not possible, they are added to the variables `deferredCards` and `deferredChildren` instead and when adding any widget, those variables will be queried for children that were not added yet.

If the parent of a widget no longer exists, it will just enter a limbo state where it never leaves `deferredChildren` and there will not be any message to the player.

This PR adds a little check after a new state was loaded: if those variables still contain widgets, it prints an error message in the browser console and resets the variables to an empty state so that the widgets will not be added to an unrelated state when another one is loaded that _does_ contain a matching parent widget.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1141/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
This works to create an error message which does not appear on production.  However, the message is confusing.  I created a test room that had holder1 with child widget checker1 and checker1 had child widget pawn1.  I also created button1 with child pin1.  Offline in a text editor, I deleted checker1 and button1 then uploaded the file.  The message said "could not add these widgets because their parent does not exist: button1, checker1."  There was also something about not adding "[[Prototype]]: Object" and I have no idea what that was about.  But the message implied that button1 and checker1 had parents that were missing.  That's not true.  Those were the widgets that were missing.

So maybe the message should say "could not add some widgets because these parent widget(s) were missing:"

Same thing for a missing deck, which I also tested.  It should say "could not upload some cards because these deck(s) were missing:"

**Comment by ArnoldSmith86** [comment]
The messages should be better now.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Tested with piles, decks, and basic widgets.  Console worked as advertised and the messages are exactly what is needed.

**Pull request merged**
