### PR TITLE
Update Bhukhar and Diced

### PR DESCRIPTION
**Pull request by 96LawDawg**
Bhukhar added improved layout, automation, and rules enforcement.  Diced added improved rules enforcement and restart button. 

Added Grim Pixel Art deck to Deck Assets.

Copied hexagonal grids tutorial from Hexagons to Grid.  Copied part of Spinner tutorial counting spinners to Functions - GET.

Updated library.json to reflect those changes and to remove the Chinese language name of Chinese Checkers per discussion at the meeting today.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3266/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
All changed files successfully loaded from updated library.json file onto test server.

**Comment by RaphaelAlvez** [comment]
There is a problem with Bhukar the pick up button is broken

**Review by RaphaelAlvez — CHANGES_REQUESTED** [review]
Please remove Bhukar until we find out what's wrong

**Comment by GroggyLion** [comment]
The Take One and Pick Up buttons are designed to be used as this or that options. When the player has taken a card from the main pile (Take One), the Pick Up button is disabled until Next Player is clicked. And similarly if the player clicks Pick Up to take the card(s) from the Discard holder, Take One is disabled. The player is not allowed to both take one and pick up in the same turn.

**Comment by 96LawDawg** [comment]
> Please remove Bhukar until we find out what's wrong

So GroggyLion says it is working as designed.  What he explained is what my play testing showed as well. Any reason this cannot be approved?

**Comment by GroggyLion** [comment]
> There is a problem with Bhukar the pick up button is broken

Please explain how the Pick Up button is not working so that it can be fixed and this PR can be merged. Thanks.

**Comment by ArnoldSmith86** [comment]
The problems should be fixed by #282. Please test and approve that PR; then this one should be fine.

**Comment by GroggyLion** [comment]
So sorry @96LawDawg, but as part of the pick up button error debugging, I came across a couple of other errors in our click routines that are now fixed. Not sure if it is possible to update this PR but I'm adding the latest version 1.1 file to the public library channel on Discord. Thanks.

**Comment by 96LawDawg** [comment]
This PR has become a mess with unrelated commits.  Closing and starting over.

**Pull request closed without merging**
