### PR TITLE
updated testcafe on github

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This _might_ fix things.

---

PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2353/pr-test (or any other room on that server)

### CODE REVIEW

**Comment by bjalder26** [comment]
This just needs a review right?  I've read how this is what is suggested as a solution to the error message we are getting, and it's just an update to testcafe, so I don't see any reason to not approve it.

**Review by bjalder26 — APPROVED** [review]
I've read that this update is supposed to address the error message we are getting from testcafe.

**Comment by 96LawDawg** [comment]
Yeah, I didn't approve this one because it didn't work.  I wonder if the player name thing has anything to do with #2351?

**Comment by bjalder26** [comment]
> As you can see, the TestCafe Chrome test still fails on this one though. It is a different problem though and possibly because resizing the window doesn't work which makes editor stuff open in an overlay instead of the sidebar, obscuring the game content the tests want to click on.
> 
> Hmm, I just looked at the output again and it seems to not find the color picker for the player color. I'll do some tests soon.

Could that be the same as this issue?
https://github.com/DevExpress/testcafe/issues/8237

It looks like they resolved that issue with 3.7.0 (3.7.0-rc.4).
https://github.com/DevExpress/testcafe/commit/716aa9194a2b9113f10dd398a4c303664ea8758f#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR32

**Pull request merged**
