### PR TITLE
add #playerCursors overlay

### PR DESCRIPTION
**Pull request by robartsd**
- groups player cursors into separate div within #roomArea
- adds --playerName and --playerColor css variables to cursors

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3972/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
Grouping cursors into a div will make it easier to separate the tabletop from the UI viewport for games that enable rotate and/or pan & zoom of the view. Also now that they are anchored to a dedicated element instead of the master parent element, other changes to the DOM structure / layout outside the actual game div should be easier.

**Comment by robartsd** [comment]
Looks like TestCafe is running wrong version of CodeNames now.

**Review by ArnoldSmith86 — APPROVED** [review]
Sounds like a good idea. The code looks fine and the cursors seem to still work.

**Pull request merged**
