### PR TITLE
removed highlighting of the hotkey from JSON editor

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The hotkeys were disabled anyway for now.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3988/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
This looks much better.  I tested it by playing around with it a bit and it works.  However, twice the room flashed and I got dumped out of the editor.  I didn't think to look at console (I'm really an amateur).  I did the exact same steps again and could not replicate it.  Just reporting what happened.

**Comment by bjalder26** [comment]
Reproducible client crash:

- open JSON editor
- ctrl-click card
- click duplicate widget (options don't open)
- ctrl-click card again
- room flashes

**Comment by ArnoldSmith86** [comment]
Better?

**Comment by bjalder26** [comment]
> Better?

Yeah, I'm not sure if that was also what LawDawg found.  I was trying to see if I could replicate what he found, and the first thing I decided to do was duplicate a card.  I clicked a bunch of other stuff and didn't find anything else, so maybe that was it.

**Review by 96LawDawg — APPROVED** [review]
I was never able to get the room to flash again at the time of my initial report.  I tested the way to force an error and it is fixed now.  I played around in the JSON Editor some and didn't have any other problems, but this was not a comprehensive test.  Approved.

**Review by rogerl50 — APPROVED** [review]

**Pull request merged**
