### PR TITLE
Improve testcafe-gitpod

### PR DESCRIPTION
**Pull request by robartsd**
Allows arguments to be passed to testcafe-gitpod similar to other testcafe scripts.

Also adds files for setting up a VNC environment needed to run testcafe in graphical mode with gitpod. This can be set up using this branch then another branch can be checked out for testing (the script installs the tools needed outside the container's /workspace directory - changes do not persist when the container is stopped, but they are also not removed when switching branches).

To run graphical tests in gitpod using VNC, simply use `source tests/testcafe/gitpod-vnc/install.sh` to install and start VNC (also installs firefox). Open a browser to the suggested port 6080 to see the graphical desktop. Then use `npm run testcafe-firefox` to run tests.

### CODE REVIEW

**Comment by robartsd** [comment]
run `./test/testcafe/gitpod-vnc/install.sh` to install VNC based x11 server, noVNC web based vnc client, and firefox.

x11 server will be started automatically next time you open a new terminal. Open the suggested port 6080 to see the graphical desktop. Then run `npm npm testcafe-firefox` to watch testcafe tests. Create game test is not working in vnc because Fullscreen fails.

**Comment by robartsd** [comment]
I'd like to figure out how to change firefox settings so that the fullscreen permissions error does not come up.

I'm also not sure how to make a script that would set up the environment for launching a GUI in the same terminal rather than needing to open a new terminal. (VNC implementation borrows heavily from [gitpod workspace images](https://github.com/gitpod-io/workspace-images/tree/master/chunks/tool-vnc).)

**Comment by robartsd** [comment]
Hand drag was happening to end on a toolbar button in the default window size for firefox in gitpod vnc. I changed the drag direction to upward to avoid potential for drag ending over the toolbar.

**Review by ArnoldSmith86 — APPROVED** [review]
It's crazy what's possible nowadays... I love it.

**Pull request merged**
