### PR TITLE
new `.pinPiece` and `.classicPiece` css

### PR DESCRIPTION
**Pull request by robartsd**
Re-sizable replacements for pin and pawn.

Pin scales only according to the width of the widget. Pin also has `--borderColor`, `--borderWidth` (3), `--pinWidth` (40), `--pinLength` (80 - values less that 50 do not extend beyond the pin head), & `--pinAngle` (-30) css variables allowing customization. Old pin available as 'legacyPinPiece' and border variables have been added to it.

Pawn stretches to fill widget (designed aspect ratio is 2:3). Old pawn available as 'legacyClasicPiece'

### CODE REVIEW

**Comment by robartsd** [comment]
View design work on CodePen: [Pin Piece](https://codepen.io/robartsd/pen/RwLpLMa?editors=0100), [Classic Piece](https://codepen.io/robartsd/pen/NWapQox?editors=0100)

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4036/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
Looks like 3 public library TestCafe tests used these widget types. I've loaded these into the PR-test room. All look fine at first glance. Reward and SELECT use pins. CALL has a pawn.

**Comment by robartsd** [comment]
File updater not applying legacy versions..

**Comment by robartsd** [comment]
Compare 'CSS piece test' in https://virtualtabletop.io/lxfb to the results in PR test room.

**Comment by ArnoldSmith86** [comment]
image

That's http://212.47.248.129:4036/pr-test. Firefox on the left. Chrome on the right. Both on Linux.

**Comment by rogerl50** [comment]
Screen Shot 2021-12-18 at 2 00 04 PM
And this is Firefox/MacOS

**Comment by robartsd** [comment]
> That's http://212.47.248.129:4036/pr-test. Firefox on the left. Chrome on the right. Both on Linux.

Bummer. Explicitly setting height of the generated content fixes part of the problem, but Firefox is also treating the top-margin differently.

**Comment by robartsd** [comment]
Looks like Firefox on Linux is setting defaulting some of the values to non-zero. Explicitly setting to zero appears to fix.

**Comment by robartsd** [comment]
Fixed for Firefox on Linux:
image

**Comment by ArnoldSmith86** [comment]
Looks the same for me now.

**Comment by robartsd** [comment]
Anything more needed to get this approved? No comments from css codeowner @RaphaelAlvez yet.

**Comment by RaphaelAlvez** [comment]
> Anything more needed to get this approved? No comments from css codeowner @RaphaelAlvez yet.

Sorry been busy last days. I'll review it today

**Review by RaphaelAlvez — APPROVED** [review]
Looks good to me

**Pull request merged**
