### PR TITLE
add `clickable` support and `artist` to canvas

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Since canvas uses a raw mouse mode, it did not respect its `clickable` property. Now it does. Also added:

`artist`- default `null` - If set to a player name or array of player names only those players can draw on the canvas.

Please suggest better names than `artist`. @bjalder26 suggested `writable` but that feels like a boolean property to me.

Completely untested.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3913/pr-test (or any other room on that server)

**Review by RaphaelAlvez — APPROVED** [review]
Artist is perfect!!!😆 

Tested and code reviewed

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Artist is a good name.

**Comment by bjalder26** [comment]
`but that feels like a boolean`

Agreed, and 'artist' matches canvas.

**Comment by bjalder26** [comment]
Thought I would provide a rough draft for the wiki.  Of course, feel free to change anything.

| Property  | Default value       | Description           |
| --------  | ------------------- | --------------------- |
| artist | null                 | Indicates the player or players that can use the canvas by `playerName`.  It can accept a single `playerName` (`e.g. "artist": "guest1234"`) or an array of playerNames (`e.g. "artist": ["guest1234", "guest2222"]`).  The default value `null` allows anyone to use the canvas. |
| clickable | true                | Same property as in [the global properties](#global-properties-for-every-widget) but with a different default value.|

**Review by robartsd — APPROVED** [review]

**Pull request merged**
