### PR TITLE
Add Lost Temples, Tutti Frutti, Solitaire

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public library:
 - Lost Temples.  New game similar to Karuba.  By LawDawg.
 - Solitaire.  New collection of solitaire card games.  Includes FreeCell (by ArnoldSmith86) which is being replaced by this collection. Other games in collection by LawDawg.
 - Tutti Frutti.  New game similar to Sushi Go!  By LawDawg.
 - Whisky Cat.  Minor updates.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4078/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
New and changed files successfully loaded from new library.json.

**Review by ArnoldSmith86 — APPROVED** [review]
I never played Sushi Go! and Karuba. I tried to learn the rules and both seem to be perfectly playable. I'm looking forward to actually playing them in one of our game nights.

I played a game of Klondike (I much prefer FreeCell myself). Several things happened that aren't perfect but not really _bad_ either:
- I clicked too low on a card and it didn't flip.
- I moved a card to the holders on the left and it ended up on the other card instead of the holder.
- The holders on the top should probably have `dropLimit: 1`?
- In the Windows version you can see the "skipped" cards when drawing three cards. That's a difference. I have no idea which version is "correct" though.

I tried to learn and play Agnes Sorel but the internet doesn't seem to agree on the rules. The only thing you enforce is +7 doesn't work if one column is empty. I would probably just remove that enforcement because someone said you can't move cards from one column into empty columns. :man_shrugging:

What is the `Recall` button for in Simple Simon?

**Comment by 96LawDawg** [comment]
> I played a game of Klondike (I much prefer FreeCell myself). Several things happened that aren't perfect but not really _bad_ either:
> 
> * I clicked too low on a card and it didn't flip.
> * I moved a card to the holders on the left and it ended up on the other card instead of the holder.
> * The holders on the top should probably have `dropLimit: 1`?

All of those issues also existed in the other solitaire games I added because of the way I used holders on a card.  All those issues are fixed (with a minor exception that I will make an issue for soon).  But I'm having trouble getting the revised file into this PR.  So I'll add it to the next one.

> * In the Windows version you can see the "skipped" cards when drawing three cards. That's a difference. I have no idea which version is "correct" though.

Since this is the first time you've ever suggested doing something the "Windows" way, I'm just going to ignore that comment.  Besides, I don't think it really matters and doing it the Windows way is more trouble than it is worth.


> I tried to learn and play Agnes Sorel but the internet doesn't seem to agree on the rules. The only thing you enforce is +7 doesn't work if one column is empty. I would probably just remove that enforcement because someone said you can't move cards from one column into empty columns. 🤷‍♂️

Change accepted (removed +7 enforcement) for next version.

> 
> What is the `Recall` button for in Simple Simon?

Nothing.  Leftover from debugging.  Removed for next time.

**Comment by ArnoldSmith86** [comment]
> Since this is the first time you've ever suggested doing something the "Windows" way, I'm just going to ignore that comment.

:rofl: Where else would you know Klondike from? :smile:

**Comment by 96LawDawg** [comment]
> 🤣 Where else would you know Klondike from? 😄

It was the one solitaire game I knew as a kid.  Parents taught it to us to keep us busy on long trips.

**Pull request merged**
