### PR TITLE
npm run debug across environments

### PR DESCRIPTION
**Pull request by larkob**
This adds the ability to run a local VTT in debug mode (uncompressed JS) across environments. Without this, you have to run it with "SET NOCOMPRESS=1" on Windows, but even then I only got it to work with Chrome. I hope this change doesn't affect environments other than Windows.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3281/pr-test (or any other room on that server)

**Comment by larkob** [comment]
@ArnoldSmith86 And while we're talking about uncompressed JS - is there a way we could have the PR-test sandboxes run without JS compression?

**Comment by ArnoldSmith86** [comment]
> @ArnoldSmith86 And while we're talking about uncompressed JS - is there a way we could have the PR-test sandboxes run without JS compression?

Should be the case already. Do you have an example where it doesn't work?

**Comment by larkob** [comment]
You're right. Must have mistaken my local environment with a PR-sandbox, then

**Comment by ArnoldSmith86** [comment]
BTW, you can check Linux yourself by going to https://gitpod.io/#https://github.com/ArnoldSmith86/virtualtabletop/pull/281..

**Review by ArnoldSmith86 — APPROVED** [review]
Tested on gitpod (Linux) and seems to work fine.

**Pull request merged**
