### PR TITLE
Fix `twoRowBottomAlign`

### LINKED ISSUE #589: `twoRowBottomAlign` does not work
This was broken by #563. Code to check label height overrides the `textarea` `height` property, but this is failing to resize the textarea due to the new `min-height` property.

### PR DESCRIPTION
**Pull request by robartsd**
fixes #589 

Also changes twoRowBottomAlign so that it is not dependent on label height - should bottom align any size label.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3591/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
I imported a game and it appears to be working for both 40px height (which I assume is default) and random heights.
image

**Comment by bjalder26** [comment]
I'm not sure if I understand what this is doing.  If the old 'height' property was overriding the min-height in the CSS, and if setting a min-height of 100% in twoRowBottomAlign works, then can't we just delete the `this.input.style.height` lines because the min-height will already be set to 100% by the CSS?

**Comment by robartsd** [comment]
The idea here is that the height is temporarily reduced, then the scroll area is checked to see how tall the actual content is.

**Comment by robartsd** [comment]
Bottom align is now working (should work with any number of lines). Need feedback from people who have had text area scrollbar issues in the past.

**Comment by 96LawDawg** [comment]
I have not fully tested this, but it fixes one of the most annoying label problems: unnecessary scroll bars.  See before and after images from 2 sample rooms.

VNO Original
VNO Revised
Poker Original
Poker Revised

There is a slight change to how the typing works when editing, but that isn't a problem (just a feature) and the fix is totally worth it.  Thank you.

**Comment by robartsd** [comment]
> I have not fully tested this, but it fixes one of the most annoying label problems: unnecessary scroll bars. See before and after images from 2 sample rooms.

I thought #563 fixed the scroll bars but broke bottom align. This PR attempts to fix the bottom align without reverting the scroll bar issue (I personally have not experienced the scroll bar issue).

**Comment by 96LawDawg** [comment]
> I thought #563 fixed the scroll bars but broke bottom align. This PR attempts to fix the bottom align without reverting the scroll bar issue (I personally have not experienced the scroll bar issue).

I think #563 fixed a smaller range of issues.  But it was merged and those scrollbars in the pictures I sent are from the production server.  This PR fixes the scroll bar issue I've had since the beginning.  I have NO idea what it might do for bottom align because I never used that and never understood it.  As far as I know, it was just created to allow PCIO imports to work.  If it had a use other than that, I never understood.

**Comment by bjalder26** [comment]
> > I thought #563 fixed the scroll bars but broke bottom align. This PR attempts to fix the bottom align without reverting the scroll bar issue (I personally have not experienced the scroll bar issue).
> 
> I think #563 fixed a smaller range of issues. But it was merged and those scrollbars in the pictures I sent are from the production server. This PR fixes the scroll bar issue I've had since the beginning. I have NO idea what it might do for bottom align because I never used that and never understood it. As far as I know, it was just created to allow PCIO imports to work. If it had a use other than that, I never understood.

I think #563 fixed one issue, but created others, and your labels were affected by both, but robartsd has a better understanding of this issue.  If someone can tell me how to test this, then I would be happy to test it.  My guess is that I would have to import a PCIO file with various labels, but then I am not sure exactly what confirms that it works.

**Comment by ArnoldSmith86** [comment]
Holders in PCIO have a "label" attached to them. It's not an extra widget but just a property of the holder. It's above the label and has a width that is a little wider than the holder.

When the text is too long for one line, it is wrapped to a second line but it is bottom-aligned (so the label grows to the top).

That is something that textareas (which VTT puts into all labels) cannot do (bottom-align). So I created this property that basically moves the textarea down a line if the text fits on one line.

When creating a game in VTT, you would just move your label manually to where you want it. So this property doesn't have much use outside of the import process.

**Comment by robartsd** [comment]
> When creating a game in VTT, you would just move your label manually to where you want it. So this property doesn't have much use outside of the import process.

Except that labels can be player editable, so the designer might want to provide space for multiple lines, not know how many lines will be used, and want it bottom aligned. This provides that to VTT designers as well as PICO import. I've expanded the concept to work bottom align any number of lines (up to the height the designer gives the widget).

**Comment by ArnoldSmith86** [comment]
Yeah, that's nice. Maybe we should rename it then? But we can do that later of course.

**Comment by robartsd** [comment]
> Yeah, that's nice. Maybe we should rename it then? But we can do that later of course.

Yeah, renaming it to simply be bottomAlign would be good.

**Review by 96LawDawg — COMMENTED** [review]
Based on the discussion and my review, this works as intended and improves playability and readability of the rooms.  Also tested on my iPad which had some problems before as well. Approved.

**Review by 96LawDawg — APPROVED** [review]
Guess I didn't hit the approve button.  Trying again.

**Review by ArnoldSmith86 — APPROVED** [review]
I don't see potential for problems in the code that wouldn't have come up already.

**Comment by ArnoldSmith86** [comment]
Hmm. The textareas are actually way too big now. That's why the scrollbars are gone. Look at public library game `Magician`, open the score card and try to fill in the first row (below the player names).

Maybe just adding `overflow: hidden` on the label helps? But that would probably break counters and other stuff.

**Comment by 96LawDawg** [comment]
That's what I was talking about when I said "There is a slight change to how the label looks when typing an entry, but that isn't a problem (just a feature) and the fix is totally worth it."

**Comment by ArnoldSmith86** [comment]
But it's not just when typing in. The label is now way bigger than what is defined in the JSON and it overlaps other widgets.

**Comment by ArnoldSmith86** [comment]
You pretty much can't even edit PCIO imported counters anymore: https://virtualtabletop.io/vunm

**Comment by robartsd** [comment]
> You pretty much can't even edit PCIO imported counters anymore: https://virtualtabletop.io/vunm

I'm not having any trouble (Edge/Windows)

**Comment by ArnoldSmith86** [comment]
Firefox on Linux. Used dev tools to make textarea background red and added a blue border around the label widget:

image

Less bad in Chrome for Linux but still:

**Comment by 96LawDawg** [comment]
> > You pretty much can't even edit PCIO imported counters anymore: https://virtualtabletop.io/vunm
> 
> I'm not having any trouble (Edge/Windows)

No problems on my end either.  Edge, Chrome, Firefox (Windows).

**Comment by bjalder26** [comment]
It seems to be the font-size driving the size of the textbox area.

**Comment by robartsd** [comment]
> It seems to be the font-size driving the size of the textbox area.

That seems likely. Setting min-height instead of height eliminated scrollbars, but the problem really might have been that we were not setting font size.

**Comment by robartsd** [comment]
> https://virtualtabletop.io/vunm

Should be improved in #595

**Pull request merged**
