### PR TITLE
Update Rummy Tiles

### PR DESCRIPTION
**Pull request by 96LawDawg**
Temporary workaround to a problem caused by recent update involving location of piles in holders.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3352/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Successfully uploaded file from library.  Revised version seems to work.

**Review by robartsd — APPROVED** [review]
Looks like it's working for me.

**Comment by 96LawDawg** [comment]
Going to merge this now without waiting. Risk is low (only 1 file/game) and it fixes a bug. Tested by 2 people.

**Pull request merged**
