### PR TITLE
Add Iago, other updates

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:
- Iago.  New game by RogerLipsett.  Similar to Othello or Reversi.
- Go. Updated counter function based on dev-game-night feedback.
- Speedy Fruits. Added automation to move cards when bell rung at right time and wrong time.  Changed seat behavior.  Added deal button.  Added timer to eliminate conflict displays.
- The Team. Updates to layout and improved automation.

Public Tutorials:
- Functions – SORT (Poker).  New variant for sorting poker hands by rank.
- inheritFrom. New tutorial by Interitus for new property.
- Timer (Appearance).  New variant adds timer bar, hourglass, clock, and stopwatch.

Library.json:  Change Moving Walls to Moving Walls 3D

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3663/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
New and changed files successfully added from library.

**Comment by rogerl50** [comment]
I noticed that the `resetGame` button is no longer  a child of the `reset` holder. I probably broke it at some point. I fixed it in the demo room, but someone should fix it before the game is posted. I can, or you can.

**Comment by 96LawDawg** [comment]
Okay.  I tried fixing it several times.  Doesn't seem to want to work, but maybe because it takes a bit for the file to update.  I'll give it a few hours and try again.

**Comment by bjalder26** [comment]
inheritFrom has an unmatched parenthesis. 
image

The color-changing timer wasn't working for me.  It needed background-color instead of background, and the colon wasn't needed.  This should work:
{
  "type": "timer",
  "id": "xen9",

  "x": 98,
  "y": 650,
  "width": 74,
  "height": 30,

  "z": 15,

  "movable": false,
  "movableInEdit": true,

  "changeRoutine": [
    "var Red = randInt 0 255",
    "var Green = randInt 0 255",
    "var Blue = randInt 0 255",
    "var newCSS = 'background-color\\u003a rgb(' + ${Red}",
    "var newCSS = ${newCSS} + ','",
    "var newCSS = ${newCSS} + ${Green}",
    "var newCSS = ${newCSS} + ','",
    "var newCSS = ${newCSS} + ${Blue}",
    "var newCSS = ${newCSS} + ')'",
    {
      "func": "SELECT",
      "property": "id",
      "value": "myHolder"
    },
    {
      "func": "SET",
      "property": "css",
      "value": "${newCSS}"
    }
  ],
  "precision": 500
}

In the timer appearance tutorial, you might want to put some clickRoutines in the widgets in front of the widget that turns the timer on and off so that clicking on them passes on the click.
e.g.
  "clickRoutine": [
    {
      "func": "SELECT",
      "property": "id",
      "value": "theTimer4"
    },
    {
      "func": "CLICK"
    }
  ],
or
  "clickRoutine": [
    {
      "func": "SELECT",
      "property": "id",
      "value": "${PROPERTY parent}"
    },
    {
      "func": "CLICK"
    }
  ],

**Comment by robartsd** [comment]
> "var newCSS = 'background-color\u003a rgb(' + ${Red}",

since PR #645 was merged the escape for the colon is no longer needed.

**Comment by 96LawDawg** [comment]
I made all the requested changes with one exception.  I already had clickRoutines in front of the widgets for most of the timer appearance clock faces and whatnot.  I added a couple more.  The ones in front of the hourglass just don't seem to work.

Closing this PR because I botched it through github.

**Pull request closed without merging**
