### PR TITLE
Use separate tags for widget defaults per-type.

### LINKED ISSUE #459: default layer of buttons is wrong
When adding `layer` to a button in JSON editor, it changes the layer of the button. It should instead have the default value initially.

Probably caused by the fact that `layer` has a different default in class `widget`.

### PR DESCRIPTION
**Pull request by rogerl50**
Fixes #459.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1288/pr-test (or any other room on that server)

**Review by RaphaelAlvez — APPROVED** [review]
tested and it works

**Review by ArnoldSmith86 — APPROVED** [review]
Code looks fine. Didn't test it.

**Comment by rogerl50** [comment]
For future reference: the bug here was that for each widget type, for each default property of that widget type, an entry was made in `jeCommands` with `id: widget_<property>`. When a widget is displayed, all actions with the proper context were displayed, and the action routine for property <property> was the one with id `widget_<property>`. This meant that when the button for that property was clicked in the UI, the *first* entry in `jeCommands` that matched that id was used, which results in the property associated with the first widget containing a default for that property being used. This fix simply adds the widget type to the identifier, so that that unique action routine is associated to the button for properties of widgets of that type.

**Pull request merged**
