### PR TITLE
grids can now set any property on widgets

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Until now `grid`s could only define a custom `rotation` which could be used to make something like roads in Catan.

While actually using it, I actually wanted to replace the `image` depending on the rotation because of a 3D perspective effect.

The example on the right of the test room now sets `rotation` and `scale` as an example.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3396/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Interesting.  I tried replacing the image with that from a different card depending on the rotation.  That worked, but I got a result I didn't expect (maybe because I don't fully understand how decks work).  I tried it on the 10 of diamonds, with the face switching to the queen of spades.  Fine.  But it also affected all the other cards.  Is there a way to make it happen per card rather than per deck?

**Comment by ArnoldSmith86** [comment]
Huh.

**Comment by ArnoldSmith86** [comment]
OK, now I see what you mean. The `grid` is defined in `cardDefaults` so it is in all the cards. If you want it to apply to only one card type, put the `grid` into the `cardTypes` entry instead (or in addition). If it should be exactly for one card, put it into the card widget.

**Comment by 96LawDawg** [comment]
I figured it was just me not paying attention (or knowing) the difference between ```cardDefaults``` and ```cardTypes```.

**Review by RaphaelAlvez — APPROVED** [review]
approved by code and testing

**Pull request merged**
