### PR TITLE
Add user control of widget highlighting in JSON editor.

### PR DESCRIPTION
**Pull request by rogerl50**
Addresses #1273. I think this is the solution we agreed on; highlighting will never really work properly on pieces like the pawns.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1328/pr-test (or any other room on that server)

After merging, a backup will be available at https://beta.virtualtabletop.io/editor/PR1328-pr-test.

**Review by ArnoldSmith86 — APPROVED** [review]
Looks good.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Comment by rogerl50** [comment]
Changing from button to holder works, but doesn't get updated in other open editors, and the icon doesn't update until a refresh is done.

**Pull request merged**
