### PR TITLE
Add button to reverse the assignment order of widgets to Fkeys.

### LINKED ISSUE #1230: Reverse z-order for function key displays
This is a possible add-on to #1228 that wasn't implemented there but could be implemented separately.  My idea is to have a switch that will toggle the z-order display in the function keys.  After #1228 the highest z value widget under the cursor gets F1, the next highest z value gets F2 and so on.  This proposed change would reverse that so the widget with the lowest z value gets F1.\

The UI for that switch could be a couple of things.  Put a button at the top of the JSON Editor that acts as a toggle (right up there with the other permanent buttons). Or make a hot key for it, maybe F12 as that never shows up on my screen as a widget function key?  The key would then immediately toggle the z order.  Personally, I think I like a visual switch better, but as I won't be coding it, I'll take whatever.

### PR DESCRIPTION
**Pull request by rogerl50**
Fixes #1230. If you click the "height" button in the command pane, the order in which widgets are assigned to Fkeys changes as described in the linked issue.

I would prefer that the icon assigned to the button would change depending on the order. We could use the up and down arrows for that. Alternatively, if swap_vert is added to the icon list, we could use that and not have the icon change. I'm open to either (or to something else), but I don't particularly like the "height" icon for this purpose.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1257/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
This works fine.  I tried to add in the requested icon.  Everything looks identical to what was done before and what it should be, but it doesn't work.  But now I can't revert commit [b291c19](https://github.com/ArnoldSmith86/virtualtabletop/pull/1257/commits/b291c19fb9b3f0825b0a1f8ff871a03844259d86) because I don't know how to use GitHub.  I guess it could just be changed back to [height].

**Review by 96LawDawg — APPROVED** [review]
Changes work as expected and the swap_vert image has been added.

**Comment by rogerl50** [comment]
This appears to work, and the other icons, which use the font file, appear to still work as well. Not sure what other testing needs to be done; this change will not affect anything outside of the JSON editor.

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
Works.  But shouldn't this also fix "zoggle zoom"?  I would do it, but I'm like a bull in a china shop at this point.

**Review by 96LawDawg — APPROVED** [review]
Approved through testing.  zoggle zoom is being fixed elsewhere.

**Review by ArnoldSmith86 — APPROVED** [review]
Code looks fine. Didn't test.

**Comment by rogerl50** [comment]
Removed swap_vert.svg. Still works. I'll commit tomorrow if nobody complains before then.

**Pull request merged**
