### PR TITLE
On hover for seats

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
addresses #906

Turns out that the approach used in seats is not reliable for multiple colors.
I tested adding a brightness(90%) filter and it worked very well for dark and bright player colors.

I did want to give compatibility between buttons and seats so I added on hover --wcFilterOH for buttons and all the other OH CSS variables to seats.

I don't know how I feel about adding them as properties in this PR

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3909/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
See the first button in the pr-test room. I'm trying to make the default background blue and the on-hover background a different color. The code currently in there does not work, and neither does specifying `--wcMain:blue`.

I'd rather this solution than the `--wcFilter=90%` solution, since as you point out that really only works well for some combinations.

**Comment by RaphaelAlvez** [comment]
> See the first button in the pr-test room. I'm trying to make the default background blue and the on-hover background a different color. The code currently in there does not work, and neither does specifying `--wcMain:blue`.
> 
> I'd rather this solution than the `--wcFilter=90%` solution, since as you point out that really only works well for some combinations.

I indeed forgot to test that. It is working now and I added some examples with different player colors

**Review by rogerl50 — APPROVED** [review]

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Comment by 96LawDawg** [comment]
I prefer the button + font approach.  When I custom make buttons, I usually do something along those lines.  It just looks better visually.  Also, since the colors are automated, I think doing it that way reduces the possibility that the colors will conflict in such a way that they are not readable, like in Guest709 in the button approach row.

**Comment by ArnoldSmith86** [comment]
If it doesn't cause major issues, I'd prefer to use #951 instead of this. If it does, we can always reopen this.

We might consider putting a default to `:hover` of a seat but I'm not sure if that's a good idea.

**Pull request closed without merging**
