### PR TITLE
Add Find the Word, Oasis, Spades

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:

- Find the Word. New game by RogerLipsett. Similar to Jotto.
- Oasis. New game by LawDawg. Similar to Skull.
- Spades. Classic card game by ArnoldSmith86 and LawDawg.
- Tutti Frutti. Autoscore now calculates before cards are moved off the board.

Public Tutorials:

- CSS. New tutorial with 4 variants: basic, advanced, caution, cards.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:1136/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
Updated version of Reward seems to be in this PR as well. Testcafe needs updating for it.

**Comment by 96LawDawg** [comment]
I reverted all the files that shouldn't be changed in this PR (those from #1100 that aren't included in the list above) back to the current public library versions.

**Review by robartsd — APPROVED** [review]
Tested Find the Word and CSS Tutorial

**Comment by 96LawDawg** [comment]
Thanks.  Roger fixed the issue you previously identified in Find the Word in the other PR (backspace not working on right side player).

**Pull request merged**
