### PR TITLE
added multi-selection mode to JSON editor

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Probably not like you expect though. You can CTRL-SHIFT-click on multiple widgets and it will start a new mode where you can see all the coordinates of the selected widgets. If they differ, they are shown as an object. If they are the same, it just says `x: 10`.

The idea is to add commands to this mode that can align the widgets like Ghetto can but there are also other possibilities.

In its current form it is already useful to set the same `y` to a couple of widgets or just manually align multiple widgets by setting their `x`s with the same difference to each other.

You can also add any property to the object and it will be added to all the selected widgets. Unless it is an object in which case each widget receives the value at the key corresponding to its `id`.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3523/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
In MacOS, Ctrl-Shift-click produces a right menu click.

**Comment by ArnoldSmith86** [comment]
You can also use SHIFT with the F-keys but we should find a solution.

**Comment by rogerl50** [comment]
I'm a little confused about this...normally Ctrl-click causes a right click in MacOS (and cannot AFAIK be overridden), but Ctrl-click works in the JSON editor to select the widget under the click (and does not cause the context menu to appear). Shift-Ctrl-click also does a right click in MacOS (I suspect the OS ignores the Shift key), but in the JSON editor *also* causes a right click, and the context menu appears.

Command (Apple key) click and option click might both be available. In Firefox, Command click opens the link under the pointer in a new tab when a link is clicked, but right now does nothing in a JSON edit session. I assume Firefox lets each page deal with keystrokes before it applies its methods?

**Comment by ArnoldSmith86** [comment]
> I assume Firefox lets each page deal with keystrokes before it applies its methods?

Well, it depends. It got a lot worse (depending on your perspective) the last years. That's why many of the JSON editor shortcuts don't work anymore.

Is this the only place where you have problems with `CTRL`? I'll try to add `e.metaKey` (should be the command key) later.

Does `SHIFT`+`F1` work for you?

**Comment by rogerl50** [comment]
In Emacs, meta maps to my option key, but that may simply be an Emacs setting. But command should work.

I'm not sure what you are asking regarding Shift-F1. Right now, Shift-F1 does the same thing as F1. (It's also quite a pain because of the crappy Apple keyboard; requires holding down Shift and Fn and pressing F1.)

**Comment by ArnoldSmith86** [comment]
> I'm not sure what you are asking regarding Shift-F1. Right now, Shift-F1 does the same thing as F1.

It should only do the same if it's the same widget you're currently editing (or if you're not editing any widget).

While the cursor is on a pile of cards you should be able to hold `SHIFT` and then press a few function keys to "select" multiple of the cards.

**Review by RaphaelAlvez — APPROVED** [review]
tested slyly

**Comment by larkob** [comment]
The regular actions to add properties in the JSON editor no longer work, there's an error about an "insideString" not being defined.

**Comment by ArnoldSmith86** [comment]
Thanks. Should be fixed.

**Pull request merged**
