### PR TITLE
fix crash when applying delta

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
#1051 stumbled onto a constellation where the order of applying delta changes leads to a crash. This PR makes sure to apply all other changes first before removing widgets.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1164/pr-test (or any other room on that server)

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
I don't understand the code changes.  But I did load the problem demo into this room and it still crashes the client when doing the recall.  So this didn't fix that problem yet.

**Comment by ArnoldSmith86** [comment]
Well, the first click doesn't crash anymore. I didn't realize that a second click now crashes. I'll have a look.

**Comment by ArnoldSmith86** [comment]
It doesn't crash for me anymore. I hope I didn't break anything else.

**Comment by 96LawDawg** [comment]
I don't really understand that `delete` any more.  I mean I have a note to myself, but I don't remember why.  Anyway, that isn't important because I was just using the room as a test for some solitaire stuff.

However, something does seem broken.  Do the recall and then manually drag some cards out and drop the on the board.  Some of them "snap back" to the deck.  Something is still screwy with the deltas.

**Comment by ArnoldSmith86** [comment]
> Some of them "snap back" to the deck.

I don't think I can reproduce it. Can you make a quick video? They do of course snap to the holders on the cards.

**Comment by 96LawDawg** [comment]
Getting a certificate authority not valid error trying to go into pr-test rooms.  Hopefully that will clear itself up.  My browser said it was probably temporary.

**Comment by ArnoldSmith86** [comment]
According to https://www.ssllabs.com/ssltest/analyze.html?d=test.virtualtabletop.io everything should be fine. :disappointed:

**Comment by 96LawDawg** [comment]
> > Some of them "snap back" to the deck.
> 
> I don't think I can reproduce it. Can you make a quick video? They do of course snap to the holders on the cards.

Never mind.  I think it was an issue with the laptop I was using at the time.  I also found that happening in some games on production with that laptop after I checked.  Doesn't seem to be an issue now with my regular devices.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  I tested the solitaire game which developed out of this problem demo room.  Everything was fine.  I also tested the most important game (and one of the most complex) on VTT -- my poker room.  Everything seems fine.  I have no way of figuring out what or how else to test this.

**Pull request merged**
