### PR TITLE
Add Expeditions, Foreign Affairs, Imagination, Shattered Dominion

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:
- Expeditions.  New game by Marxos.  Similar to Lost Cities.
- Foreign Affairs.  New game by ArnoldSmith86.  Similar to Café International.
- Imagination.  New game by LawDawg96.  Similar to Pictures.
- Shattered Dominion.  New game by ArnoldSmith86.  Similar to Kingdomino.

Public Tutorials:
- JSON Editor. Corrected a few minor details.
 
Public Assets:
- Dice. Fixed a typo on the Dice Animation variant. 

library.json:  Changed similar name for Telepathy from “Mind” to “The Mind”

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3887/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
New/changed files successfully loaded from public library.

**Comment by ArnoldSmith86** [comment]
According to the changes you added a new `Dice.vtt` and didn't reference it anywhere. Isn't that supposed to update an existing file?

**Comment by 96LawDawg** [comment]
> According to the changes you added a new `Dice.vtt` and didn't reference it anywhere. Isn't that supposed to update an existing file?

It's listed under public assets changes above.  Just fixes a minor typo that you pointed out during the last library update.

**Comment by ArnoldSmith86** [comment]
But shouldn't it be `Assets - Dice.vtt` or something like that? If it is a change to an existing file, it shouldn't be listed as a new one.

Did the change load from the library in the test server?

**Comment by 96LawDawg** [comment]
You are right.  Good catch.  I add "tutorial" or "assets" in front of those files to distinguish them.  Except when I forget like this time.  This PR library loaded the old uncorrected file.  I'll fix it.

**Comment by 96LawDawg** [comment]
Fixed the Assets - Dice file name.  Unable to figure out how to delete the old plain "Dice" filename.  I know I can do it later when starting a new PR but I always have trouble while the PR is in review.  Will delete the old one next time (unless someone else figures out how).

**Review by ArnoldSmith86 — APPROVED** [review]
My games seem to be the latest version.

Expeditions seems to be the latest version but I think I only playtested older versions.

Imagination seems to work as well.

No idea how you managed to get the changes of the latest commit to show up in `Files changed` but that's probably not a problem.

**Comment by 96LawDawg** [comment]
Going to try something I found on stackoverflow.  Close and reopen.  Fingers crossed.

**Pull request merged**
