### PR TITLE
Set currentParent to grandparent if immediate parent is a pile.

### PR DESCRIPTION
**Pull request by flackr**
Fixes an issue @96LawDawg found with owner not being reset if you move widgets out of a pile within a `childrenPerOwner` holder.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1526/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1526-pr-test`.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  I tested the specific behavior that this was supposed to fix.  But since this code is in the routine for most moving, I tested different types of piles in different games.  All works as expected (with no change in behavior for existing games).

**Comment by ArnoldSmith86** [comment]
Shouldn't it be enough to change `parent` to `_ancestor` in the line above your insertion?

**Comment by 96LawDawg** [comment]
> Shouldn't it be enough to change `parent` to `_ancestor` in the line above your insertion?

Tested. That works.  Made the change.

**Review by flackr — COMMENTED** [review]
Yup, didn't know about ancestor but that looks like it does exactly what we want. I would self approve the updated change but github won't allow me :-).

**Comment by ArnoldSmith86** [comment]
I'll approve it after looking at what this might influence.

**Comment by flackr** [comment]
> I'll approve it after looking at what this might influence.

My justification for it being okay to change currentParent is that both the check for `childrenPerOwner` and the call to `dispenseCard` should be called on the holder. The use of `currentParent` in `moveToHolder` also seems to be making an assumption that the parent is the holder and not a pile.

**Comment by 96LawDawg** [comment]
This also fixes #1202.  But I can't seem to link that in the development in Git. Lately, it seems like older issues will not link like there is some limit on how far back that filter in Git lets you go.

**Comment by ArnoldSmith86** [comment]
I can usually link it from the issue side because the PR is still new.

**Comment by 96LawDawg** [comment]
That is what I just figured out and did.

**Review by ArnoldSmith86 — APPROVED** [review]
Yeah, this looks OK to me.

**Pull request merged**
