### PR TITLE
adds new classes

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
adds clickable, editable, and movable classes based on the properties of the same name.

basically, I wanted to add more cursor triggers. let me know if you can think of something else

demo will be loaded to test room

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1544/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1544-pr-test`.

**Comment by ArnoldSmith86** [comment]
The pig doesn't show a different cursor for me (Firefox, Linux).

**Comment by RaphaelAlvez** [comment]
> The pig doesn't show a different cursor for me (Firefox, Linux).

it's supposed to be "zoom-in" got it from Mozilla's documentation

**Review by ArnoldSmith86 — APPROVED** [review]
Looks fine to me.

**Pull request merged**
