### PR TITLE
Add Crossed, Flatten the Curve, +4 other new games

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:

- Crossed.  New game by ArnoldSmith86. Similar to Encore!
- Flatten the Curve. New game by LawDawg.  Similar to Pandemic.
- Going Nuts. New game by LawDawg. Similar to Bananagrams.
- Hearts. New game by LawDawg. Classic trick taking game.
- Impostor. New game by ArnoldSmith86. Similar to Spyfall.
- Ultra. New game by LawDawg. Similar to Decrypto.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1157/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
All new games successfully loaded from revised library.json file.

**Comment by robartsd** [comment]
Passing cards in Hearts is confusing. There is no obvious way to pass cards to another player. I guess you can just put them on the table near the player's seat.

I think there should be a holder to put the passed cards into (perhaps the tricks taken holders could do double duty). Would be nice if the holder you are supposed to pass to is somehow highlighted (or the other holders hidden while passing).

**Comment by 96LawDawg** [comment]
> Passing cards in Hearts is confusing. There is no obvious way to pass cards to another player. I guess you can just put them on the table near the player's seat.
> 
> I think there should be a holder to put the passed cards into (perhaps the tricks taken holders could do double duty). Would be nice if the holder you are supposed to pass to is somehow highlighted (or the other holders hidden while passing).

Passing system in Hearts updated.

**Comment by robartsd** [comment]
Hearts issue:
- In my testing piles formed in all the trick holders except the bottom one, but I don't see preventPiles set in the holder. Not sure what was going on there.

Hearts enhancements that would be nice to have (I would approve without them):
- Wait to display done passing until all passing holders have received 3 cards (perhaps even wait to turn off the "pass here" until all three cards have been passed. Could configure number of cards to pass in settings.
- Reset button.
- Display Take Trick button only for player who "won" the trick (or have automation track who should take the trick and act as if the correct player pressed the button). Probably not a problem when really playing, but it was easy for me to click from the wrong player when playing 4 hands in separate browsers.

**Review by robartsd — APPROVED** [review]
I've only really tested hearts. There is still a minor issue there, but it is playable. We seem to have issues with adequately testing public library games, but adding games won't break anything else.

**Comment by rogerl50** [comment]
Is there a reason why Yahtzee hasn't made it in yet?

**Comment by robartsd** [comment]
> Is there a reason why Yahtzee hasn't made it in yet?

I think because this was opened so long ago. Not merged due to lack of approvals. LawDawg has a bunch of new games to add to the public library as well, but we don't have people testing. I think when get the public library overhaul done this might get easier, but right now the public library workflow has issues if we don't have enough people providing quick feedback/approval for public library PRs.

**Comment by robartsd** [comment]
> Is there a reason why Yahtzee hasn't made it in yet?

Besides, Yahtzee will be so much better after #1167 .

**Comment by 96LawDawg** [comment]
> I've only really tested hearts. There is still a minor issue there, but it is playable. We seem to have issues with adequately testing public library games, but adding games won't break anything else.

I'll take the approval and put the changes to Hearts on my to do list.  Won't take me that long to do the changes, but at the current pace, the update won't be merged until summer.  Thanks for the approval.

**Comment by 96LawDawg** [comment]
> > Is there a reason why Yahtzee hasn't made it in yet?
> 
> I think because this was opened so long ago. Not merged due to lack of approvals. LawDawg has a bunch of new games to add to the public library as well, but we don't have people testing. I think when get the public library overhaul done this might get easier, but right now the public library workflow has issues if we don't have enough people providing quick feedback/approval for public library PRs.

What Dave said.  I do one library PR at a time.  This one adds 6 new games.  Next up, 8 or 9 new games.  Still pending are 14-15 games that I have updated with seats and other improvements.  But at the current pace of reviews, I've decided to prioritize new games for now so it may be a while before those updates get in the cycle.  Yahtzee is in the next group of new games.  If you want to get it merged, give it a review and approval.  Should have it ready in a couple of days.

**Comment by rogerl50** [comment]
No, it's fine. I just wanted to make sure it hadn't been forgotten.

**Pull request merged**
