### PR TITLE
improved game file uploads significantly

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Uploading VTT files failed randomly in the past and using WebSockets there was no way to get information about the current progress.

I now changed it to use XMLHttpRequest which allows for a progress indicator and I think it used base64 before so this already saves some bandwidth.

I used the opportunity to also implement a check that actually opens the vtt file clientside, checks if the assets are already on the server and if more than half of them are, it deletes them from the archive and uploads a newly created file. This should make >90% of all uploads near instant.

# To do
- [x] Uploading multiple files doesn't reset the button text correctly.
- [x] Uploading a zip file without states in it doesn't trigger the appropriate error message.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3405/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
Reviewed through test.  File upload is much faster for very large files.  I saw a "loading ..." indicator when it too slightly longer.  On some files, it was so fast that didn't even have time to appear.

**Comment by rogerl50** [comment]
That worked for me. I think just not doing card image uploads in my case accounts for about 90% of the bandwidth.

**Comment by ArnoldSmith86** [comment]
Please test this a bit. I'd like to merge it tomorrow because it's already 20 days old.

**Comment by rogerl50** [comment]
Still works for me. I tried multiple uploads of different versions of several games. There was one time where the background rendered significantly (~1/4 sec or so) after the rest of the room on initial upload, but I doubt it was related to the PR.

**Pull request merged**
