### PR TITLE
added public library game Cheer Up! (similar to Skyjo)

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Will probably do another 2 player playtest tomorrow.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1932/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1932-pr-test`.

**Comment by ArnoldSmith86** [comment]
Did some more tweaks after playtest. The main things that could be improved:

1. At the start you flip two cards and the player with the highest cards begins. The highlighted seat doesn't reflect that.
2. When a round ends, the player that ended it gets twice the penalty points if they don't have the lowest score. This could be automated but I just added a "double score of player X" option to the `INPUT`.
3. When a round ends, the player that ended it begins the next round. The highlighted seat doesn't reflect that.

It's not really an issue if you know the game though. I might improve this at some point but probably not any time soon.

**Comment by 96LawDawg** [comment]
I added a few lines of code to fix issue 3.  I also added a few words to the instructions to clarify that the player that finishes/ends the round should press the play next button.  That person then has the turn indicator.

I considered fixing issue 1 for you, but your seat and holder names were too random.

**Review by 96LawDawg — APPROVED** [review]
Approved through test

**Comment by ArnoldSmith86** [comment]
> I considered fixing issue 1 for you, but your seat and holder names were too random.

:laughing:

**Pull request merged**
