### PR TITLE
implemented automated game testing using TestCafe

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This introduces new tests that get executed by GitHub after every commit.

It basically opens a browser somewhere in the cloud, loads some games (and tutorials) from the public library, clicks a few buttons in those games and then checks if the resulting room state is the same as when I wrote the tests.

We'll see if we want to keep these game tests or replace them by dedicated test rooms. I feel like it's a good idea to check the actual games.

This can be expanded quite a lot and can potentially also drag cards around (or play entire games) but for now I would like to gather some experience.

These tests will break every time one of the tested games/tutorials receive an update. For now I will update them manually but we can also automate the process in the future.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3372/pr-test (or any other room on that server)

**Comment by bowiz2** [comment]
I really like the implementation, and this is a great way to catch regressions in playability.

I'm definitely for having dedicated test rooms in the future, as you'd like to have your tests input-output be controlled as much as possible, without external unrelated activity breaking them needlessly (they'll break enough as is 😉).

**Comment by ArnoldSmith86** [comment]
This doesn't change the client and server code at all.

Can we get this approved and merged (because it blocks the other PRs) or is anyone against this or has questions?

**Review by 96LawDawg — APPROVED** [review]
I don't understand the code, but I do see that this creates 2 new files that shouldn't interfere with any existing code (as ArnoldSmith86 said).  Approved.

**Pull request merged**
