### PR TITLE
fixedParent under parent

### PR DESCRIPTION
**Pull request by bjalder26**
moves fixedParent under parent in the JSON editor.

image

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3679/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
Approved through test and code review.  Even I can review that code.

**Review by ArnoldSmith86 — APPROVED** [review]
:+1:

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 @bjalder26 what does # and * mean in this list?
I imagine # is a space line but can't figure *

**Comment by bjalder26** [comment]
> @ArnoldSmith86 @bjalder26 what does # and * mean in this list?
> I imagine # is a space line but can't figure *

I believe * means it is shown when the value is default (in other words, always shown).  I don't know what # does.

**Comment by ArnoldSmith86** [comment]
> I believe * means it is shown when the value is default (in other words, always shown). I don't know what # does.

Correct. And # does mean empty line afterwards.

**Pull request merged**
