### PR TITLE
Limit textarea size to size of label widget

### PR DESCRIPTION
**Pull request by bjalder26**
Addresses https://github.com/ArnoldSmith86/virtualtabletop/issues/607.

image

http://212.47.248.129:4032/pr-test
vs
https://virtualtabletop.io/y2lc

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4032/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
Works in the one room I was having an issue with.

**Comment by bjalder26** [comment]
> Code looks ok. Do you have any examples that I can compare?
> 
> I'm somewhat out of the loop in this one

http://212.47.248.129:4032/pr-test
vs
https://virtualtabletop.io/y2lc

Click in the labels.

**Comment by ArnoldSmith86** [comment]
But doesn't this reintroduce scrollbars when the textarea is one or two pixels too small? We had a lot of those depending on the system and browser. Probably a line-height issue?

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
At least this doesn't work for `"twoRowBottomAlign": true`. Because the textarea is shifted down (see pr-test top left).

I'm pretty sure we need a more complicated approach.

**Comment by bjalder26** [comment]
> But doesn't this reintroduce scrollbars when the textarea is one or two pixels too small? We had a lot of those depending on the system and browser. Probably a line-height issue?

I believe right now the textarea tends to be oversized for the label widget (the div).  So we are getting fewer scrollbars because even if the text goes beyond the label height it might not go beyond the textarea height.  As soon as it goes beyond the textarea height there will be a scrollbar though (in both cases).  In the pr-test room I made the textsize intentionally too large.  I recall there was some discussion on scrollbars in the past, but I can't recall the conclusion.

> At least this doesn't work for `"twoRowBottomAlign": true`. Because the textarea is shifted down (see pr-test top left).
> 
> I'm pretty sure we need a more complicated approach.
> 
> The other example in the test room was already there and looks like this for me:
> 
> image

That is because twoRowBottomAlign overrides this by setting element.style height to auto and it also puts in a top padding of 20px.  Its the same as on the production server.  To me that seems like a separate twoRowBottomAlign issue.  It seems like the additional padding will need to be subtracted from the textarea height (compared to the label widget height).

**Comment by ArnoldSmith86** [comment]
I tried to fix this stuff in #1033. Please see how the behavior compares to your `height: inherit` approach.

**Comment by RaphaelAlvez** [comment]
look at #1033

**Pull request closed without merging**
