### PR TITLE
Adds clickRoutine to Piles

### LINKED ISSUE #856: Pile clickRoutine customization
This would complement #852 by allowing further customization of piles.  The idea is to allow a user to override the default click behavior for piles.  So instead of getting the standard menu of shuffle, flip, and split, a user could make a pile do other things.  For example, if piles only ever need to be flipped, the user could just add a `clickRoutine` to flip, saving players time and button presses.  Or more advanced options could be included such as spreading piles out, or gathering them back up, or bringing up a custom menu screen.

If this is developed, I recommend creating a new property such as `pileClick` which would default to false and enabling the existing behavior.  But if set to true, it would allow piles to use `clickRoutines.`  I also recommend putting the property into a deck and allowing the deck to hold the pile specific `clickRoutine` JSON.  The property and the code needs to be somewhere permanent since piles are not.

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
fixes #856

Adds same structure used in other widgets

As a side effect piles can now have clickable: false

You will need automation to use this so this as piles are constantly being created and deleted.  This should be viewed as an advanced feature for now.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3896/pr-test (or any other room on that server)

**Review by ArnoldSmith86 — APPROVED** [review]
Code looks fine. Someone please make sure this doesn't break piles for everyone. :smile:

**Comment by RaphaelAlvez** [comment]
@96LawDawg I belive you should be the one to test it as you were the one requesting this change

**Comment by 96LawDawg** [comment]
Testing piles is a real pain in the ass.  However, I believe I have thoroughly tested these changes.  I loaded several games that use pile routines, including Flora with its move view routine, that has had pile issues before.  I did not find anything unusual.

I also developed something for piles based on the new capabilities.  See http://212.47.248.129:3896/LawDawg.  I was trying to figure out a way to get new piles to have custom `clickRoutine` automatically added.  I thought I would play with my newfound `globalUpdateRoutine` skills.  I tried basing it on `id` but that didn't work.  The creation of a new pile with a new `id` does not trigger a `globalUpdateRoutine`.  I don't know if it should.  Maybe?  Anyway, I decided to go with `xGlobalUpdateRoutine` because something is almost always moving.  This isn't perfect, but close enough.

In the room, there are 2 decks.  Piles made with the one on the left always behave normally.  Piles made with the one on the right and that are outside the holder will have a custom `clickRoutine` created.  I wanted to make this as complicated as possible to test.  It is very easy to have every pile in the room get a custom `clickRoutine` for a global x change.  But I have been able to limit it to just a subset of piles that I want.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Comment by RaphaelAlvez** [comment]
@96LawDawg So does this serves your needs?

**Comment by 96LawDawg** [comment]
Yes.  Slightly more complicated to implement what I was envisioning, but doable.  And this is a whole lot easier on the code.  This is more than good enough.  Thanks.

**Comment by RaphaelAlvez** [comment]
> Yes. Slightly more complicated to implement what I was envisioning, but doable. And this is a whole lot easier on the code. This is more than good enough. Thanks.

Let's see if my approach of #852 is accepted. I can add a pileClickRoutine that is treated in the same way as pileCSS

**Pull request merged**
