### PR TITLE
Change hoverTarget selection priority

### PR DESCRIPTION
**Pull request by robartsd**
When multiple holders are valid for a drop target select which one to use based on:
1. holders with cursor over them
2. holders with best overlap (area of client bounding box overlap / maximum possible client bounding box overlap)
3. closest holder (client bounding box center to center distance)

This change (with an error in comparing distance) was initially introduced in #903 in response to [@ArnoldSmith86 's comment](https://github.com/ArnoldSmith86/virtualtabletop/pull/903#issuecomment-986076658). This PR fixes the error. #1013 has been merged reverting selection criteria to only use distance (but retaining #903's refinements for what selecting which holders are valid targets).

> Not even saying that the behavior in production is better. There it's problematic if you have a small holder at the end of your hand. If you move a card to the hand, it can't touch the small holder at all anymore or it'll snap back because the hand center is further away than the small one.

In discord it was also proposed that the topmost holder could be selected when multiple qualify.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4012/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
I would vote for #1013.  It fixes the problems in Calico, Bus Driver, and Pairs.

Also, #1012 still has what some may consider counter-intuitive behavior.  See the screenshot below from PL Chinese Checkers. I could not capture where the mouse was, so I drew a black x in the upper left corner of the red marble on the board.  The draggable area on the marbles is square so it extends a bit beyond the circle.  In the situation in the screenshot, the marble would still be dropped into the upper left holder because the cursor was right at its boundary.  But if you are just looking at where the marble is and not the cursor (not an unreasonable expectation), you would think the marble would go into the lower right holder.

Screenshot 2021-12-11 131106

**Comment by robartsd** [comment]
hoverTarget behavior change was intended to address @ArnoldSmith86 's [comment in PR 903
](https://github.com/ArnoldSmith86/virtualtabletop/pull/903#issuecomment-986076658)

> Not even saying that the behavior in production is better. There it's problematic if you have a small holder at the end of your hand. If you move a card to the hand, it can't touch the small holder at all anymore or it'll snap back because the hand center is further away than the small one.

I'll merge #1013 but leave this open for further discussion / evaluation.

**Comment by ArnoldSmith86** [comment]
> We might want to implement this, but wait until legacy servers are functional.

What's your current intention with this PR? Wait for legacy servers?

**Comment by robartsd** [comment]
> > We might want to implement this, but wait until legacy servers are functional.
> 
> What's your current intention with this PR? Wait for legacy servers?

Yes, (or an explicit rejection of the idea). This was originally added as feature creep when I worked on #903 but removed due to issues with some games. It is not much of a priority for me.

**Comment by 96LawDawg** [comment]
This PR fixes an issue I was having in a version of Blue (Azul) I was working on.  I loaded the game into the test server room.  I have rhombus shaped pieces and holders.  I was having a problem on production figuring out why the tall vertical holder between the board and the "Empty" button was not getting selected as a hoverTarget.  Part of my problem was due to the fact that I was using a clip-path holder and was only thinking about the visual element and not the actual footprint of the holder.  So in the top left, I have one holder that keeps its rhombus shape and another one where I removed the clip-path.  In production, it is almost impossible to get the tall vertical holder to accept pieces when dropping near one of the smaller holders.  In this PR, it works great.

**Comment by robartsd** [comment]
Closing in favor of new approach introduced in #1354

**Pull request closed without merging**
