### PR TITLE
Fix visibility of label and basic widgets

### PR DESCRIPTION
**Pull request by rogerl50**
by adding the editmode-colored 3 pixel border in edit mode. Requires adding a drop shadow and changing box-sizing in edit mode as well to avoid apparent widget movement.

Replaces https://github.com/ArnoldSmith86/virtualtabletop/pull/264

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3324/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
I like the box-shadow solution for providing the edit mode outline. I'm not sure why box-sizing is needed.

**Review by ArnoldSmith86 — APPROVED** [review]
Way better. Some existing stuff should probably converted to box-shadow as well but that can happen later.

**Comment by rogerl50** [comment]
> I like the box-shadow solution for providing the edit mode outline. I'm not sure why box-sizing is needed.

I'm guessing, pretty much, but I think that with `box-sizing: border-box`, the size of the additional border is included in the size of the box overall, so the contents shrink. Depending on how rounding of the new contents size happens, this can result in an apparent shift in the position of the contents.

**Comment by rogerl50** [comment]
> > > I like the box-shadow solution for providing the edit mode outline. I'm not sure why box-sizing is needed.
> > 
> > 
> > I'm guessing, pretty much, but I think that with `box-sizing: border-box`, the size of the additional border is included in the size of the box overall, so the contents shrink. Depending on how rounding of the new contents size happens, this can result in an apparent shift in the position of the contents.
> 
> Yes, that is how it works, but there no longer is an additional border as the outline is not a border, it is a box shadow. The box shadow goes outside the border box. If the sizing in game mode is border box and the game designer adds a border, the content box will be smaller enlarged when entering edit mode.
> 
> This doesn't solve the problem of image basic widgets having the border converted to grayscale.

But in http://212.47.248.129:3324/border, there is a large border around the label, and sizes don't change between edit and game mode. Perhaps I don't understand what you're saying.

And no, this doesn't address the problem of a grayed border around basic widgets. You linked to a post (in the other PR) giving a way to solve that problem, but it requires more involved CSS work that is beyond my skill level.

**Review by RaphaelAlvez — APPROVED** [review]
I'm happy with the changes. @robartsd you seen to be pretty involved in the discussion but I'm not sure if you are approving it or not. Please make a review whenever you feel like this PR is ready to be merged.

**Comment by robartsd** [comment]
Looks like we've applied `box-sizing: border-box` to widgets wherever we have applied borders. We probably should have applied `box-sizing: border-box` to all widgets (where there is no border the computed size is the same as the default box sizing of `content-box`). I think we should change the default box-sizing of all widgets to `border-box` even though this has the potential to cause problems for existing games that use custom css and writing file updater code to mitigate might be too difficult. I might put together a PR for discussion in our meeting next week.

**Review by robartsd — APPROVED** [review]
I'm OK with the changes this PR is making.

I'd like to look into broader changes to `box-sizing` globally and using `box-shadow` for all edit mode outlines, but that should be a new PR.

**Pull request merged**
