### PR TITLE
fixed unwanted HTML render in JSON editor

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
HTML tags were not escaped for the white parts of the text. So when adding HTML to a text property and then removing one of the enclosing quotes, the HTML was actually rendered inside the editor.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3628/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Anything else you can find? :smile:

**Comment by bjalder26** [comment]
> Anything else you can find? 😄
Not in this PR, but I went and checked the improved debug PR as well.
image

**Review by RaphaelAlvez — COMMENTED** [review]
@bjalder26 since you reviewed this I think your should approve it. the debug problem should be solved there if this PR really doesn't fix it

**Comment by ArnoldSmith86** [comment]
I feel like this PR should be pretty straightforward to review...

**Review by bjalder26 — APPROVED** [review]
Fixes HTML rendering in JSON editor.  Approved through testing.

**Pull request merged**
