### PR TITLE
Move to seat sets `owner` before moving to `hand`

### LINKED ISSUE #1116: Interaction of childrenPerOwner and MOVE to seat/hand
When working on a room, I ran into something that seems to be a bug.  If you use MOVE to seat (which then moves to hand), everything ultimately works out the way it is supposed to, but some intermediate step along the way is off.  In my room, I was trying to capture in a custom property the first player to have a card moved to his hand.  I tried doing this by having an enterRoutine that applied a custom property of the owner.  That didn't work so I tried putting a changeRoutine on the card so the first time owner was changed from null, it set a property onto the card.  That didn't work either.

What happened was the owner property got set correctly, but the custom property was set to whichever player pressed the button, so there was a mismatch.  I eventually got it to work by having everything happen in the same button that did the MOVE.  @robartsd summarized what he thinks is happening this way: "I think move to seat is moving to that hand (and childrenPerOwner in the hand is setting the owner to the player running the automation) then the seat is changing the owner to the player in the seat."  That's better than any summary I could come up with.  

There is a sort of demo at https://virtualtabletop.io/m9it.

### PR DESCRIPTION
**Pull request by robartsd**
Fixes #1116 

This could change the behavior of some games that make use of owner arrays. Currently a player in an owner array can move a card into the hand to become the sole owner of the card, but this PR changes that behavior. All players in the owner array would continue to see the card.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1139/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  This does fix the behavior identified in the issue I opened.  I tested the game I was working on then as well as a couple of other games and tutorials.  Nothing was broken.

I guess I also don't understand the concern you raise about some games may change behavior.   I'm not aware of a game that does what you said (but I don't know the full details of many of them).  An owner array basically has to be set programmatically, right?  Because if you drag a card into a hand (`"childrenPerOwner":true`) it will always set owner of that card to the player dragging it (or pressing the button to move it).  So I don't see how an array of owners could see that card by your change.  What am I missing?

**Comment by robartsd** [comment]
> An owner array basically has to be set programmatically, right? 

Correct.

> Because if you drag a card into a hand (`"childrenPerOwner":true`) it will always set owner of that card to the player dragging it (or pressing the button to move it). So I don't see how an array of owners could see that card by your change. What am I missing?

If a widget with an owner array is moved by a player to a holder with `"childrenPerOwner":true`, the holder currently changes `owner` to the player who moves the widget. With this PR, the holder will no longer change `owner` when the widget is moved.

Actually this could break any game where widgets that are not owned by the player get moved to holders with `"childrenPerOwner":true` (either moved by a player who is a member of the owner array or widgets owned by other players moved by automation). I don't know of any games that make use of this behavior, but it is possible.

**Comment by 96LawDawg** [comment]
> If a widget with an owner array is moved by a player to a holder with `"childrenPerOwner":true`, the holder currently changes `owner` to the player who moves the widget. With this PR, the holder will no longer change `owner` when the widget is moved.
> 

Well, you may think that is what happens, but testing does not show that to be the case.  In https://test.virtualtabletop.io/PR-1139/pr-test I manually added an array of 2 owner names to a card.  I did 3 things to the card: I manually dragged it to the hand, I moved it with a button from a holder to the hand, and I moved it with a button from a holder to seat (and through the seat, to the hand).  In each case, the owner array was changed to the playerName of the player doing the moving.  Same thing that happens on production.

This would seem to me to be a good thing as it means hypothetical games won't break.

**Pull request merged**
