### PR TITLE
Adds cardType & deck to mouse over in JSON editor

### PR DESCRIPTION
**Pull request by bjalder26**
- Adds cardType and deck to mouseover in JSON editor.
- Adds cardType to where cardType properties are shown.

image

I think these changes are convenient, for when someone is editing their cards, and they want to quickly identify the cardType or deck of a card.  However, if they aren't desired parts can be eliminated, or this can be closed.
Test Server: http://212.47.248.129:3737/pr-test

### CODE REVIEW

**Comment by rogerl50** [comment]
If we're going to do this, why not add similar pointers for `cardDefaults`?

**Comment by bjalder26** [comment]
> If we're going to do this, why not add similar pointers for `cardDefaults`?

I removed the one in red because I discovered it was somehow breaking the Deck Editor and causing errors in the JSON editor and I haven't figured out why yet.  However, if you'd like me to add it to the remaining one, then that seems easy enough.

**Comment by rogerl50** [comment]
I don't see any reason not to do this. But someone who understands the JSON editor code (like @larkob) should really be the one to approve it.

**Comment by robartsd** [comment]
> I don't see any reason not to do this. But someone who understands the JSON editor code (like @larkob) should really be the one to approve it.

I agree. I've done very little with the editor code.

**Review by ArnoldSmith86 — APPROVED** [review]
I only looked at the code and it looks fine to me. I can't think of anything that would break because of the change.

Please test if editing the contents of the `cardType` still works as intended though.

But the good thing about fiddling with the editor is that we can just fix stuff without worrying about breaking games. :smile:

**Comment by bjalder26** [comment]
> I only looked at the code and it looks fine to me. I can't think of anything that would break because of the change.
> 
> Please test if editing the contents of the `cardType` still works as intended though.
> 
> But the good thing about fiddling with the editor is that we can just fix stuff without worrying about breaking games. 😄

Editing the cardType (id) in the deck editor successfully updates the card.
Updating the cardType (id) in the JSON editor makes the card disappear because it doesn't update the card. (same as production server)
Updating the cardType properties successfully updates the properties on the card.

**Pull request merged**
