### PR TITLE
RECALL now works with multiple decks in a holder

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Previously only the first found deck would be recalled.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3354/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
That was quick.  I uploaded a VTT file to the test server, and it now appears to recall cards from multiple decks without any issues that I could find.

**Review by larkob — APPROVED** [review]
I've reviewed the code and it looks fine.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Pull request merged**
