### PR TITLE
IF using variable for default condition

### PR DESCRIPTION
**Pull request by larkob**
This PR allows to omit the `condition` parameter in IF operations. If omitted, it evaluates the 'condition' variable for true or false. 

```
  "clickRoutine": [
    {
      "func": "COMPUTE",
      "operand1": 1,
      "operand2": 1,
      "operation": "==",
      "variable": "condition"
    },
    {
      "func": "IF",
      "thenRoutine": [
        {
          "func": "LABEL",
          "label": "hpyx",
          "value": "success"
        }
      ],
      "elseRoutine": [
        {
          "func": "LABEL",
          "label": "hpyx",
          "value": "failure"
        }
      ]
    }
  ]
```

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3431/pr-test (or any other room on that server)

**Comment by larkob** [comment]
I've fixed it so it should behave identical if the condition variable is undefined.

**Comment by RaphaelAlvez** [comment]
Please remember me to talk about this in the meeting.
The idea is good I just want to talk about the variables

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
This now changes behavior if a variable `condition` is set. Obviously since that's the intention.

I think it's entirely reasonable though that currently used button code sets a `condition`, checks it in an `IF` and later in the routine has a second `IF` that uses `operand1` instead. This PR would break that routine because now the second `IF` would instead check the same condition as the first one.

My best idea so far would be a fileupdater that renames existing variables wit the name `condition` but I'm not sure if that's straightforward with things like `CALL`.

Inheriting the variable `condition` to other routines will also cause havoc even if they are written with this PR in mind.

The more I think about it, the more I fear that this isn't worth it.

**Comment by robartsd** [comment]
> The more I think about it, the more I fear that this isn't worth it.

Particularly now that it is so easy to apply a variable to a parameter. Leaving it explicit should be easier to understand and maintain. I vote we close without merging.

**Comment by ArnoldSmith86** [comment]
I'll close this. Feel free to reopen it if you have a good idea about how to address the issues I pointed out in my review. My gut tells me there's no good solution.

**Pull request closed without merging**
