### PR TITLE
Stop JSON editor from stealing focus from label

### PR DESCRIPTION
**Pull request by bjalder26**
Addresses issue in https://github.com/ArnoldSmith86/virtualtabletop/issues/1028.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4031/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
Approved through test

**Comment by ArnoldSmith86** [comment]
It only steals the focus if the tree view is currently active, right? I don't think the tree view should ever steal the focus because you don't type there.

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
Please test if #1035 works the same.

**Comment by bjalder26** [comment]
#1035 looks to be a cleaner solution.

**Pull request closed without merging**
