### PR TITLE
Update library.  Add Rummy Tiles.  Other minor game updates.

### PR DESCRIPTION
**Pull request by 96LawDawg**
Fixed error in hexagonal cards tutorial.  Diced now calculates scores automatically.  Dominoes, Flora, Tittle, and Assets - UN Unicode updated with new move view code and holder.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3123/pr-test (or any other room on that server)

**Review by ArnoldSmith86 — APPROVED** [review]
I only checked Rummy Tiles but it's looking good.

**Comment by robartsd** [comment]
Move view works in the opposite direction from what I expected. I expected it to move the viewport in the direction of the arrow (as I am accustomed to scrollbars behaving), it moved the objects (as I am accustomed to two finger drag behaving).

**Comment by 96LawDawg** [comment]
> Move view works in the opposite direction from what I expected. I expected it to move the viewport in the direction of the arrow (as I am accustomed to scrollbars behaving), it moved the objects (as I am accustomed to two finger drag behaving).

That's true.  Perhaps the eye icon is a little bit misleading because you aren't moving the eye but the pieces, but I couldn't find a better alternative. I did think about reversing the direction, but decided to keep it as is.  Just a design choice.  Anyone is free to make a different choice.  I mean, if you click on the arrow thinking it will go one way and it doesn't, just click the other arrow.  You get used to it either way.

**Comment by RaphaelAlvez** [comment]
I created a suggestion to the flora buttons as a new game file in the server

**Review by robartsd — APPROVED** [review]
Opened all games listed. Tested move buttons in Dominoes. Tested scoring in Diced.

**Pull request merged**
