### PR TITLE
added back mouse coordinates to editor

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Now on the overlay that shows the widgets under the cursor.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1907/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1907-pr-test`.

**Review by RaphaelAlvez — APPROVED** [review]
is this code commig from the old editor? Why was there some code for this already if it was not being displayed?

Approved by test. Code looks alright

**Comment by ArnoldSmith86** [comment]
Yeah, the JSON editor code is very separate from the new editor. There are just small wrapper classes to display it inside the new stuff.

**Review by 96LawDawg — APPROVED** [review]
Fantastic.  Approved through test.  I was somehow worried there would be a problem with this that happened when I rescaled the size of the room manually be dragging the divider between the room and the edit area.  But I should have trusted in the magic of the browser and javascript.

**Pull request merged**
