### PR TITLE
added dropdown arrow to `INPUT.select`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
I will tweak this a bit but ran out of time.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1917/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1917-pr-test`.

**Comment by 96LawDawg** [comment]
This solution does not allow you to click on the arrow itself to open the menu.

**Comment by ArnoldSmith86** [comment]
Needs `z-index: -1`.

**Comment by RaphaelAlvez** [comment]
What does this do???

**Comment by ArnoldSmith86** [comment]
Same as #1917 but hopefully with less side effects.

**Comment by mousewax** [comment]
I made a very minor modification to vertically align the symbol. and to make it so that when the option is very long it does not trample over the down arrow.

**Review by RaphaelAlvez — APPROVED** [review]
looks good to me

**Comment by RaphaelAlvez** [comment]
image

**Review by 96LawDawg — APPROVED** [review]
Changes look good to me.  I tested with and without labels.  All look better than before and work just as before.  Approved.

**Pull request merged**
