### PR TITLE
adds properties to change color of options svg

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
This PR is being created as draft as it will be discussed at the meeting tomorrow

This PR adds two new properties to style spinners.

styleOptionsLines changes the color of the lines in options svg
styleOptionsColor changes the font color of options in options svg

more properties can be easily added like font size and font but I need to know the designer's needs.

I also plan on extend replace SVG to spinners arrow

### CODE REVIEW

**Comment by robartsd** [comment]
I'd really like to be able to set the color for each option independently. I'm OK with one color for all the dividing lines.

**Comment by RaphaelAlvez** [comment]
> I'd really like to be able to set the color for each option independently. I'm OK with one color for all the dividing lines.

after a quick look that seems possible just not sure how the property itself would look like and be called.

**Comment by robartsd** [comment]
My preferred solution for providing options would be to have the options array contain an object for each option which would provide all of the option's properties.
```
"options":[
  {"value":"1","color":"red"},
  {"value":"2","color":"blue"}
]
```

Later, we might extend this to allow for options that are not just colored text. Of course if the options is an object, there should be a way to get all of the current value properties (not just the text). I think we'd want to leave the value property of the spinner alone, so we'd probably want to add a "valueColor" property to the widget as well.

**Comment by RaphaelAlvez** [comment]
Updated property names to lineColor and textColor acording to today's meeting. Working in test room. @ArnoldSmith86 @robartsd or @larkob please approve it

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 @robartsd or @larkob
 
 Sorry, it was still set as a draft. It should now be ready for review.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Pull request merged**
