### PR TITLE
support `MOVE` from a seat

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
That was kinda a oversight when adding seats. PCIO supports this.

I am not quite sure if this really works well already.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3933/pr-test (or any other room on that server)

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  It does not work on production but does work on this PR.

Should other functions be extended to seats?  I tested MOVEXY, FLIP, COUNT, and SORT.  None of them currently work.  I could see a use for both COUNT and SORT as I already do that in rooms that were built before seats.  Open a new issue?

**Comment by RaphaelAlvez** [comment]
Yeah i would prefer if we took a look to see if there can be a function that deal with all of this

**Comment by ArnoldSmith86** [comment]
With the new concept of anonymous collections, I would like to rework all that stuff so all operations support the same stuff with proper functions.

I have a feeling that it won't be 100% compatible though so we should wait for compatibility servers to be a thing.

**Comment by 96LawDawg** [comment]
So this fixes an important omission.  I know there is more work to be done.  But are there any objections to merging this and opening a new issue that can be worked over time for the other seat-related anonymous collection stuff?

**Review by robartsd — APPROVED** [review]
This code looks good to me.

**Comment by rogerl50** [comment]
Draft wiki update, please!

**Comment by 96LawDawg** [comment]
Wiki update.  Change the "from" and "to" entrries in the MOVE function to the following:

* from: _widgetID_ (or an array) - specifies the widget(s) that contains the widgets to move. In the typical case, this would be a holder, but could be any widget with child widgets. If the widget is a [seat](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Widgets#seat) and the seat is linked to the hand, then using MOVE from a seat will move widgets only if the seat is occupied.

* to: _widgetID_ (or an array) - specifies the widget(s) that widgets should be moved into. In the typical case, this would be a holder, but could be any widget. If the widget is a [seat](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Widgets#seat) and the seat is linked to the hand, then using MOVE to a seat will move widgets only if the seat is occupied.

I think this is ready to be merged and should be merged.

**Comment by robartsd** [comment]
> * from: _widgetID_ (or an array) - specifies the widget(s) that contains the widgets to move. In the typical case, this would be a holder, but could be any widget with child widgets. If the widget is an [seat](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Widgets#seat) and the seat is linked to the hand, then using MOVE from a seat will move widgets ~only if the seat is occupied~ _from the hand of the player in the seat (no widgets will be moved if the seat is unoccupied)_.
> * to: _widgetID_ (or an array) - specifies the widget(s) that widgets should be moved into. In the typical case, this would be a holder, but could be any widget. If the widget is a [seat](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Widgets#seat) and the seat is linked to the hand, then using MOVE to a seat will move widgets ~only if the seat is occupied~ _to the hand of the player in the seat (no widgets will be moved if the seat is unoccupied)_.

**Comment by 96LawDawg** [comment]
> > * from: _widgetID_ (or an array) - specifies the widget(s) that contains the widgets to move. In the typical case, this would be a holder, but could be any widget with child widgets. If the widget is an [seat](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Widgets#seat) and the seat is linked to the hand, then using MOVE from a seat will move widgets ~only if the seat is occupied~ _from the hand of the player in the seat (no widgets will be moved if the seat is unoccupied)_.
> > * to: _widgetID_ (or an array) - specifies the widget(s) that widgets should be moved into. In the typical case, this would be a holder, but could be any widget. If the widget is a [seat](https://github.com/ArnoldSmith86/virtualtabletop/wiki/Widgets#seat) and the seat is linked to the hand, then using MOVE to a seat will move widgets ~only if the seat is occupied~ _to the hand of the player in the seat (no widgets will be moved if the seat is unoccupied)_.

**Comment by 96LawDawg** [comment]
I have no idea what happened there.  Oops.

**Comment by ArnoldSmith86** [comment]
Just FYI: I didn't merge this yet because I want to make some tests if this behaves like it does in PCIO. If anyone else wants to do that, that would be fabulous.

**Comment by 96LawDawg** [comment]
> Just FYI: I didn't merge this yet because I want to make some tests if this behaves like it does in PCIO. If anyone else wants to do that, that would be fabulous.

I created a spades room at https://playingcards.io/g5hx32.  I first tested the deal with sitting in seats and not.  It works as expected.  It deals x cards to the hand of occupied seats and only to those hand/seats.  Then I changed the button to move from the hand back to the deck.  It worked as expected moving only cards from occupied hand/seats.  If there were cards in the hand but no player seating in that seat, then those cards stayed.

Same behavior in VTT and PCIO as far as I can tell.

**Comment by 96LawDawg** [comment]
I also tested the import of the same game in http://212.47.248.129:3933/pr-test.  Worked as expected.

**Comment by ArnoldSmith86** [comment]
And it also took the same cards from the hands?

**Comment by 96LawDawg** [comment]
I'm glad you made me go back and check.  I don't know exactly what happened the first time, but now I see a difference.  I sat in 3 seats at the same time.  I had 5 cards in each seat/hand.  I clicked the button to return 1 at a time.  In PCIO, it takes 1 card from one of the hands.  Click again it takes another card from another hand.  Click again it takes another card from the 3rd hand.  Then the cycle repeats, but not always in the same order.  In VTT, that operation takes 1 card from every hand and returns it.

**Comment by robartsd** [comment]
> Then the cycle repeats, but not always in the same order. In VTT, that operation takes 1 card from every hand and returns it.

I wonder if # of cards in the hand influences it.

**Comment by 96LawDawg** [comment]
> I wonder if # of cards in each hand influences which card it takes. And how does this relate to how PCIO handles moves from multiple holders?

Good question.  I haven't made anything in PCIO in 12 months until this.  I had an equal number of cards in both hands.  I just went back and tested with more cards in one hand than the other.  PCIO removes from the hand with more cards until they are equal, and then sort of back and forth.  As for how it handles moves from multiple holders, I think that is exactly what this is.  In the PCIO interface, you can pick multiple holders/seats/hands to move to or from.  It looks a bit like an array.  But it moves through the array sequentially whereas VTT does it all at once.  The VTT way seems more like what I would expect, but I guess it just depends.

**Comment by robartsd** [comment]
> Good question. I haven't made anything in PCIO in 12 months until this. I had an equal number of cards in both hands. I just went back and tested with more cards in one hand than the other. PCIO removes from the hand with more cards until they are equal, and then sort of back and forth. As for how it handles moves from multiple holders, I think that is exactly what this is. In the PCIO interface, you can pick multiple holders/seats/hands to move to or from. It looks a bit like an array. But it moves through the array sequentially whereas VTT does it all at once. The VTT way seems more like what I would expect, but I guess it just depends.

My guess is that it randomly selects from among all the hands with the most cards if there is a tie for the most. I can't remember how it handles multiple destinations either. The only time I've used PCIO's move to / from hand was between holders designated for each seat and the hand, so the details of which card moves where were not important (I was moving all the cards to one holder or hand in each routine step then repeating the steps for each player).

**Comment by robartsd** [comment]
It appears that PCIO's move in one at a time mode moves a card from the holder or hand that has the most cards (picking which holder or hand to move from randomly if there is a tie for the most). The top card is always taken from the selected holder or hand.

**Comment by robartsd** [comment]
Player does not have to be connected for move to / from a seat to work; there just needs to be a player assigned to the seat.

**Comment by robartsd** [comment]
The move source is a bit more complex than I thought. I get different results depending on if the last action was an automation button or a drag to a potential source holder. I'm not sure how important it is to precisely emulate ambiguous routine steps such as move from multiple sources.

**Comment by 96LawDawg** [comment]
Strange that the last action has an impact.

I think that if you wanted to emulate PCIO most closely, then MOVE from multiple sources would need another parameter.  If there are multiple from holders, then you need to decide whether to do what PCIO does or do what VTT does.  You could add a "mode" parameter with options for 'sequential' that would work like PCIO, 'simultaneous' that would work like VTT, and 'random' which would create a new option to take from a random holder.

All of that could get pretty complicated though if there are multiple destination holders I think.  Which cards would go where? 
 So "mode" should only be activated if there are multiple from widgets and a single to widget.  Then to have as close as possible compatibility with PCIO, the default mode is sequential.

**Comment by RaphaelAlvez** [comment]
Is it a problem related to move from seats or a problem related to move from multiple holders?

**Comment by 96LawDawg** [comment]
> Is it a problem related to move from seats or a problem related to move from multiple holders?

If you move from holders that are not seats, the behavior is different.  It picks one holder and moves all the cards from there x at a time.  Then it moves to the next holder until all are gone, etc.  I don't know how it picks the holders but it seems the first one is the one that last had widgets dropped into it, but there may be more to it than that.  It may also depend on whether the widget was dragged or automated (based on what @robartsd said above).

**Comment by ArnoldSmith86** [comment]
Thanks for all this research. You just know that there are games that break if we don't emulate this as closely as possible.

It would be very helpful if you can provide pcio files with tests for all the cases.

**Comment by robartsd** [comment]
> You just know that there are games that break if we don't emulate this as closely as possible.

Of course I agree we should attempt to maximize compatibility, but I'm not sure how hard we should work at documenting exactly what PCIO does when the declarations are ambiguous. We should at least be able to document what VTT does and match PCIO as far as we are aware. If all the sources are hands, the hand with the most cards (or random among a tie for most cards) is selected on a per card basis. The confusion seems to come in if sources are both holders and hands. I haven't explored how multiple holders (without any hands) behave. The one at a time or as a pile options certainly control what happens if there are multiple destinations selected.

**Comment by 96LawDawg** [comment]
> Thanks for all this research. You just know that there are games that break if we don't emulate this as closely as possible.
> 
> It would be very helpful if you can provide pcio files with tests for all the cases.

I started to give this some thought, but there are so many possible permutations based on what Dave and I discovered.  Here are some of them:

- Previous drop to a holder automated vs manual
- Moving to combination of hand and regular holder
- Moving to another hand vs regular holder
- Simultaneous move from combination of hand and regular holder
- Equal or different number of cards in old holder(s) (hands and regular holders)
- Equal or different number of cards in new holder(s) (hands and regular holders)


Setting that up would take hours and hours.  Any particular thing that would be most helpful?  I mean, the most common use cases would be moving from multiple hands to a single holder (like a discard pile) or to multiple holders.  But again, different number of cards, automated or not all adds to the complexity.

Ultimately, I guess I'm with Dave that we don't need to emulate it perfectly because we can't perfectly understand it because we don't have access to the source code.

**Comment by ArnoldSmith86** [comment]
Do you have a PCIO file with some tests you could provide?

**Comment by 96LawDawg** [comment]
> Do you have a PCIO file with some tests you could provide?

https://playingcards.io/agw6fz and https://virtualtabletop.io/fozh (imported version of the same file).

To use, the upper left hand buttons will reset the room, will deal 6 cards to all (occupied) seats and holders 1-4 or will deal different cards to each seat and matched in each holder 1-4.

Then on the right are 2 columns of buttons arranged by whether the PCIO option is to move one-by-one or as a pile.  Within each column are several buttons that move 1, 3, or combination of 3 and 2 cards from seats and/or holders to other holders.

Hope that helps.

**Comment by ArnoldSmith86** [comment]
Unfortunately the PCIO room timed out in the meantime. Do you still have the pcio file?

**Comment by 96LawDawg** [comment]
> Unfortunately the PCIO room timed out in the meantime. Do you still have the pcio file?

Yes.  Tried to attached, but not a supported file type.  Sent via PM in Discord.

**Comment by ArnoldSmith86** [comment]
[Move_FROM_Seat_Demos_for_PR933.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/8253567/Move_FROM_Seat_Demos_for_PR933.zip)

Thanks!

**Comment by ArnoldSmith86** [comment]
Hmm, I think I want to merge this as-is. When we worry about getting closer to PCIO behavior, we can always just add options to the operations. And I'm pretty sure that moving _to_ seats is just as different from PCIO as this PR is.

**Review by RaphaelAlvez — APPROVED** [review]
code reviewed and tested.
that filter covers hands with stackOffset: 0 (creating piles)

this should be merged as soon as possible.

**Comment by 96LawDawg** [comment]
> > Thanks for all this research. You just know that there are games that break if we don't emulate this as closely as possible.
 
> Ultimately, I guess I'm with Dave that we don't need to emulate it perfectly because we can't perfectly understand it because we don't have access to the source code.

I still feel the same way.  This is ready to be merged.  I don't think anything existing will break because the functionality currently does not exist at all.  PCIO imports _might_ not work perfectly depending on what they do, but that is already the case.

**Review by RaphaelAlvez — CHANGES_REQUESTED** [review]
Sorry after some tests I see that this does not resolve piles. I initially tested with a count: 0

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 I tried adding the code for resolving piles and it just broke more stuff. I'm ou of time now so this is in your hands now

**Comment by 96LawDawg** [comment]
I have no idea how this was missed.  But Raphael is right in that MOVE from seat does not work well with piles in this PR.

But on production, MOVE from hand when there are multiple piles in the hand with different owners also does not work.  I will open an issue.

And MOVE to hand (through seats) does not work on production when the hand will form piles.  But that will be fixed by #1256 .

**Comment by RaphaelAlvez** [comment]
I see why you think that but I think this is a pile problem. The filter must be getting the pile anyway and moving the whole pile.

Btw I didn't have time to take a deep look. Almost all my time was looking if I could make one function to solve all the seat problems

**Comment by RaphaelAlvez** [comment]
My last commit still doesn't solve it, there is still this bug

https://drive.google.com/file/d/1GQmpkFeeZti9oRgxaVh2MenGHjCWiw0E/view?usp=sharing

**Comment by RaphaelAlvez** [comment]
the problem was destroying the pile added the card back to the holder and we were not taking the measures we need to take when dealing to another player

This solves it:
image

**Review by RaphaelAlvez — APPROVED** [review]
should work now

**Comment by RaphaelAlvez** [comment]
> My last commit still doesn't solve it, there is still this bug
> 
> https://user-images.githubusercontent.com/73476656/178159607-e8e5929a-2dae-4254-b46d-a6c0c76af4cd.mp4

Just to be clear. My latest commit fixes this bug

**Comment by 96LawDawg** [comment]
I may be confused, but I don't think this fixes the bug.  In the video, I have 2 browsers open to the same room.  The hand is alignChildren: true and stackOffset: 0.  The move button sometimes works correctly, but not reliably.  In the first series of clicks, it moves from the hand of the player pressing the button.  In the second series of click, it moves from the hand of the other player.  This does fix the problem of moving the entire pile (from #1259).  But it still is not a good solution for MOVE.  I haven't tested anything related to seats yet.

https://user-images.githubusercontent.com/76912527/222611385-0e5cead9-0499-4c3c-a55b-076dda89b4af.mp4

**Comment by 96LawDawg** [comment]
I agree the issue with MOVE from a seat is solved (including seats with piles) and is ready to be merged.

My earlier comments about this and #1259 relate to MOVE from a hand.  Which is sort of similar, but is still broken.  But this PR can be merged through test.

**Comment by ArnoldSmith86** [comment]
With the recent changes `MOVE` from a seat works in production. Can somebody check the comments from this PR against production so we can see what still needs to be done?

**Comment by 96LawDawg** [comment]
> With the recent changes `MOVE` from a seat works in production. Can somebody check the comments from this PR against production so we can see what still needs to be done?

Here is some feedback.  I have not finished testing, but I will need to start over after all these updates are made, so I'm stopping for now:

1) Needs `updateAfterShuffle()` applied to the hand after cards are moved from a seat.
2) This does not work as expected with piles.  If cards in the hand are in piles, a request to move from the seat moves the entire pile, even if only 1 card is supposed to be moved.
3) Moving more than 1 card from a seat (like count=3) selects opposite cards to move if just moving from a holder.  Moving from a holder takes cards that are the highest z level (on top).  Moving cards from a seat takes the lowest z (on bottom).

**Comment by 96LawDawg** [comment]
I forgot to add that despite the limitations mentioned in the previous post, this generally works.  For a simple use case of moving _n_ cards from a seat to another holder (or holders), this works as expected.

**Comment by ArnoldSmith86** [comment]
It doesn't make sense to use this for fixing the mentioned issues because the implementation in production is fundamentally different. I opened #2307 and will fix it in a new PR.

**Pull request closed without merging**
