### PR TITLE
Add Tic-Tac-Toe-Tye, many tutorials

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:
- Tic-Tac-Toe-Tye. New game by LawDawg.  Similar to Otrio
- Alleys. Updated with css rotation animation for game pieces.
- Stratagem. Updated with css rotation animation for game pieces (and improved again after Dev Game Night).
- Backgammon. Improved the doubling die and score keeping and tweaked the offsets in the holders on the right (after Dev Game Night).

Public Tutorials:
- Array.  Modified library image and name.  This is no longer a function under COMPUTE, but a separate explanation of how arrays work.  Also, when switching to dynamic expressions, some of the code on all 3 variants was not optimized.  Fixed all of that. Created new variants consistent with the Strings tutorial.
- Strings. Added new tutorial based on dynamic expressions.
- Comparisons. Added new tutorial based on dynamic expressions.
- Math. Added new tutorial based on dynamic expressions. Loosely based on the original COMPUTE tutorial.
- State Dependent Routines. New tutorial demonstrating a variety of techniques for using clickRoutines.
- IF. Added new variant for Used Buttons (compare to Skip Used Buttons tutorial variant)
- CALL. Fixed border color of library image (was black, now dark blue).
- COMPUTE. Delete obsolete tutorial.
- COMPUTE – Array. Delete obsolete tutorial.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3498/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
All changes files successfully loaded through revised library.json file.

**Comment by ArnoldSmith86** [comment]
Liar's Dice is also new, right?

**Comment by 96LawDawg** [comment]
Sort of.  It got added after your review last time at the last second.  But it is already in the public library on the production server.

**Comment by 96LawDawg** [comment]
Anybody want to review this one?  I've got several more things staged and ready to go but I'm not going to pile them all on here.

**Comment by rogerl50** [comment]
For the alphanumeric comparisons, why not simply
```
   "var str1 = ${PROPERTY text OF compare1}",
   "var str2 = ${PROPERTY text OF compare2}",
    "var output = ${str1} < ${str2} //Returns true if the first value is less than the second value",
    {
      "func": "LABEL",
      "label": "outputbox",
      "value": "${output}"
    }
```

**Comment by rogerl50** [comment]
Similarly, the `GET` button in creating arrays could start `"var myArray = ${PROPERTY arrayValues}"`

**Comment by 96LawDawg** [comment]
> For the alphanumeric comparisons (and similarly for the logical comparisons), why not simply
> 
> ```
>    "var str1 = ${PROPERTY text OF compare1}",
>    "var str2 = ${PROPERTY text OF compare2}",
>     "var output = ${str1} < ${str2} //Returns true if the first value is less than the second value",
>     {
>       "func": "LABEL",
>       "label": "outputbox",
>       "value": "${output}"
>     }
> ```

Because I'm still learning how awesome the new structure is (and I didn't even think about it).  Making those changes now.

**Comment by 96LawDawg** [comment]
> Similarly, the `GET` button in creating arrays could start `"var myArray = ${PROPERTY arrayValues}"`. There are many instances of this simplification waiting to happen in other parts of the tutorials :)

And now I'm working on these.  I might not get them all, but I'll try.  Just a new way of thinking, but we definitely want to show the easiest way, not necessarily the old way that works.

**Comment by 96LawDawg** [comment]
And clarification.  It isn't that the room freezes.  Other buttons work.  Just the sort and reverse button don't work as expected.

**Comment by rogerl50** [comment]
I had a discussion with ArnoldSmit86 on the #help discord channel on 5/29 (There's probably a way to link to that, but I don't know it) regarding the fact that array operations may not actually make a copy of the array. This could be related to that issue, but someone who knows the code will have to look at it.

**Comment by robartsd** [comment]
> > For the alphanumeric comparisons (and similarly for the logical comparisons), why not simply
> > ```
> >    "var str1 = ${PROPERTY text OF compare1}",
> >    "var str2 = ${PROPERTY text OF compare2}",
> >     "var output = ${str1} < ${str2} //Returns true if the first value is less than the second value",
> >     {
> >       "func": "LABEL",
> >       "label": "outputbox",
> >       "value": "${output}"
> >     }
> > ```

This should yield the same result:
```
    "var output = ${PROPERTY text OF compare1} < ${PROPERTY text OF compare2} //Returns true if the first value is less than the second value",
    {
      "func": "LABEL",
      "label": "outputbox",
      "value": "${output}"
    }
```

**Comment by 96LawDawg** [comment]
> This should yield the same result:
> 
> ```
>     "var output = ${PROPERTY text OF compare1} < ${PROPERTY text OF compare2} //Returns true if the first value is less than the second value",
>     {
>       "func": "LABEL",
>       "label": "outputbox",
>       "value": "${output}"
>     }
> ```

True.  And that is the most perfect version of the code.  But we also want it understandable to newcomers.  That is pretty compact.  Do you think that is best?

**Comment by bjalder26** [comment]
It appears the reverse is just flipping the 

> And clarification. It isn't that the room freezes. Other buttons work. Just the sort and reverse button don't work as expected.

The buttons will work IF the label is changed by any means between pressing one of the buttons the first and second time.  Also, the reverse button alters the original property.  I think some sort of check is being done to see if the final property (the text of the label) has changed and if it hasn't then it does not perform the SET for some reason (or it applies the last SET).  

I do not know what that has to do with dynamic variables essentially doing a GET, but to me that seems like it is the behavior.

**Comment by 96LawDawg** [comment]
#510 will fix the issue I noted.

**Comment by 96LawDawg** [comment]
The tutorials for Arrays, Comparisons, Math, and Strings (all variants) have been updated to reflect the changes that Roger requested.

**Comment by rogerl50** [comment]
For `&&` and `||` in the logical comparisons tutorial, did you mean for the first compare to compare `str1` to 7?

**Comment by rogerl50** [comment]
In the Rotate example in the `CALL` tutorial, the last statement in the subroutine adds 1 to the result. I think it should be adding `${min}` to the result to ensure that the answer is between `min` and `max`. (The only reason I noticed this is that the example in the `random` section of the computations Wiki had the same error.)

**Comment by rogerl50** [comment]
The first `Note` in the `clickRoutine` for `MoveCards` in the `CALL` tutorial refers to the wrong routine.

**Comment by rogerl50** [comment]
The `SELECT` and `GET` at the start of the `clickRoutine` for Flip Either Chip in the `IF` tutorial can be replaced by `var aValue = ${PROPERTY text OF nmo0}`. In fact, if desired, `aValue` could be dispensed with altogether, and the reference to it at the end of the `IF` just replaced with `${PROPERTY text OF nmo0}`. (BTW, the condition for that `IF` should be moved up to precede the `thenRoutine`, just for readability.)

**Comment by 96LawDawg** [comment]
> For `&&` and `||` in the logical comparisons tutorial, did you mean for the first compare to compare `str1` to 7?

No.  I have no idea how that happened.  Fixed.  I had to put that series of statements in there to turn the strings "true" and "false" into boolean values.  But that was weird.

**Comment by 96LawDawg** [comment]
> In the Rotate example in the `CALL` tutorial, the last statement in the subroutine adds 1 to the result. I think it should be adding `${min}` to the result to ensure that the answer is between `min` and `max`. (The only reason I noticed this is that the example in the `random` section of the computations Wiki had the same error.)

This example is from Lars, so I'm not sure exactly what he was trying to do.  But there is no need to add 1 or to add ${min} to the result.  In fact, the last statement is completely unnecessary and I deleted it.  The point of the example is to show how to use CALL (using random number as an example).  The routine works without the last statement (even better because the way it was structured, it was ignoring the ROUND function).

**Comment by 96LawDawg** [comment]
> The first `Note` in the `clickRoutine` for `MoveCards` in the `CALL` tutorial refers to the wrong routine.

Fixed.  Thank you.

**Comment by rogerl50** [comment]
> > In the Rotate example in the `CALL` tutorial, the last statement in the subroutine adds 1 to the result. I think it should be adding `${min}` to the result to ensure that the answer is between `min` and `max`. (The only reason I noticed this is that the example in the `random` section of the computations Wiki had the same error.)
> 
> This example is from Lars, so I'm not sure exactly what he was trying to do. But there is no need to add 1 or to add ${min} to the result. In fact, the last statement is completely unnecessary and I deleted it. The point of the example is to show how to use CALL (using random number as an example). The routine works without the last statement (even better because the way it was structured, it was ignoring the ROUND function).

I don't think I agree. The point of the example is to return a rotation between `min` and `max`. As things are now, since `random` returns a value between 0 and 1, the computed rotation, `${r} * ${range}`, will return a rotation between `0` and `max-min`.

**Comment by 96LawDawg** [comment]
> I don't think I agree. The point of the example is to return a rotation between `min` and `max`. As things are now, since `random` returns a value between 0 and 1, the computed rotation, `${r} * ${range}`, will return a rotation between `0` and `max-min`.

I see what you are saying.  But I'm not sure how adding `min` back in to that fixes it.  How about this.  I change the min and max values to 0 and 359.  Then the called function is simply what follows:

``` "randomValueRoutine": [
    "var result = randInt ${min} ${max} // This takes the 'min' and 'max' variables passed from the CALL function, creates a random integer between those values, stores the outcome in the variable 'result' which is passed back to the function following the CALL."
  ],
```
This is much simpler and easier to follow.

**Comment by 96LawDawg** [comment]
> The `SELECT` and `GET` at the start of the `clickRoutine` for Flip Either Chip in the `IF` tutorial can be replaced by `var aValue = ${PROPERTY text OF nmo0}`. In fact, if desired, `aValue` could be dispensed with altogether, and the reference to it at the end of the `IF` just replaced with `${PROPERTY text OF nmo0}`. (BTW, the condition for that `IF` should be moved up to precede the `thenRoutine`, just for readability.)
> 
> Similar comments apply for the other buttons on that screen.

All those changes made.  All the tutorials were made before dynamic functions, so many of them could benefit from this type of clean up.  I'll be on the watch for that as future tutorials are updated.  Thanks.

**Comment by rogerl50** [comment]
> > I don't think I agree. The point of the example is to return a rotation between `min` and `max`. As things are now, since `random` returns a value between 0 and 1, the computed rotation, `${r} * ${range}`, will return a rotation between `0` and `max-min`.
> 
> I see what you are saying. But I'm not sure how adding `min` back in to that fixes it. How about this. I change the min and max values to 0 and 359. Then the called function is simply what follows:
> 
> ```
>     "var result = randInt ${min} ${max} // This takes the 'min' and 'max' variables passed from the CALL function, creates a random integer between those values, stores the outcome in the variable 'result' which is passed back to the function following the CALL."
>   ],
> ```
> 
> This is much simpler and easier to follow.

No need to change min and max, though. You can leave them as they are at -90 and 90.

**Comment by bjalder26** [comment]
> In the Rotate example in the `CALL` tutorial, the last statement in the subroutine adds 1 to the result. I think it should be adding `${min}` to the result to ensure that the answer is between `min` and `max`. (The only reason I noticed this is that the example in the `random` section of the computations Wiki had the same error.)

I'm guessing because I didn't see the original, but if the point was to create a random rotation between a min and max that was virtually continuous, then yeah I would expect it would need to be done something like this.

"var a = rand // gives decimal between 0 and 1, which is essentially the same as zero percent to one hundred percent",
"var range = ${max} - ${min} // calculates the range in values",
"var rotationRange = ${a} * ${range} // essentially a random percent of the range",
"var randRotation = ${min} + ${rotationRange} // a random rotation with a minimum of min when the random number is zero and a maximum of max when the random is 1 and the full range is added back to the minimum"

**Comment by rogerl50** [comment]
> > In the Rotate example in the `CALL` tutorial, the last statement in the subroutine adds 1 to the result. I think it should be adding `${min}` to the result to ensure that the answer is between `min` and `max`. (The only reason I noticed this is that the example in the `random` section of the computations Wiki had the same error.)
> 
> I'm guessing because I didn't see the original, but if the point was to create a random rotation between a min and max that was virtually continuous, then yeah I would expect it would need to be done something like this.
> 
> "var a = rand // gives decimal between 0 and 1, which is essentially the same as zero percent to one hundred percent",
> "var range = ${max} - ${min} // calculates the range in values",
> "var rotationRange = ${a} * ${range} // essentially a random percent of the range",
> "var randRotation = ${min} + ${rotationRange} // a random rotation with a minimum of min when the random number is zero and a maximum of max when the random is 1 and the full range is added back to the minimum"

Yes, that's exactly what the example in the `CALL` section in the Wiki does now.

**Comment by 96LawDawg** [comment]
It won't hurt to have a slightly different example in the tutorial.  The purpose is to demo CALL, so I think this is fine.

**Review by rogerl50 — APPROVED** [review]
Tutorials approved through test and code review. New/revised games not reviewed.

**Review by ArnoldSmith86 — APPROVED** [review]
I briefly looked at the games and couldn't find any problems.

**Pull request merged**
