### PR TITLE
fixed label textarea height and scrollbars

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This is my take in a long row of PRs.

Labels now work like this:
1. Measure how high the label would need to be to fit all text.
2. If it is smaller than the label widget or only 5px taller, the scrollbar will be hidden.
3. If `twoRowBottomAlign` is set, the height and top padding of the textarea will be set in a way that the text is aligned to the bottom and that the textarea does not go outside of the widget.

Please find labels where this does not work as intended.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4033/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
For some reason the scrollbars don't show up on fireFox.

**Comment by ArnoldSmith86** [comment]
True. It's the same for me in #1032 though. Didn't check production yet.

**Comment by bjalder26** [comment]
> True. It's the same for me in #1032 though. Didn't check production yet.

I'm not having any success figuring out why the scrollbars don't show up, but maybe this will be a clue.  On production they don't show up if twoBottomRowsAlign is set to true, but do show up if it is set to false AND the text goes outside of the height of the textarea.
https://virtualtabletop.io/y2lc

**Comment by ArnoldSmith86** [comment]
> The difference appears to be that on production if there is a height set on the textarea, then it won't show a scrollbar, but if it is not set, then it will.

It looks like this is just what Firefox does. If the height of the textarea is less than 40px, it won't show a scrollbar. And let's face it, a scrollbar that small is useless except that it shows you that there is an overflow. For bigger labels the scrollbar works just fine.

We could change the `'auto'` in `this.input.style.overflowY = contentHeight-this.get('height') < 5 ? 'hidden' : 'auto';` to `'scroll'` because the condition pretty much already knows that a scrollbar is necessary. It would make the label more consistent between browsers.

**Comment by ArnoldSmith86** [comment]
I'm not 100% sure about any of the last 3 commits. What do all of you think?

**Comment by ArnoldSmith86** [comment]
In case anyone is wondering: the fileupdater "broke" (fixed rather) my pr-test setup which had multiple labels with 1px height increments.

**Comment by bjalder26** [comment]
> It looks like this is just what Firefox does. If the height of the textarea is less than 40px, it won't show a scrollbar. And let's face it, a scrollbar that small is useless except that it shows you that there is an overflow. For bigger labels the scrollbar works just fine.
> 
> We could change the `'auto'` in `this.input.style.overflowY = contentHeight-this.get('height') < 5 ? 'hidden' : 'auto';` to `'scroll'` because the condition pretty much already knows that a scrollbar is necessary. It would make the label more consistent between browsers.

Yeah, it seemed to me there was a choice between a textarea smaller than 40px with no scrollbar or one 40px with a scrollbar (I'm guessing to accommodate the size of the scrollbar).  Maybe we could reduce that size by changing the scrollbar in Firefox, but maybe below a certain size (e.g. <= 20px) there shouldn't be a scrollbar in any browser (I don't really know).

I don't really have strong feelings on this.

**Comment by bjalder26** [comment]
Maybe using `scrollbar-width: thin;` for FireFox would make the scrollbars more consistent.  It seems to get rid of the up and down arrows in FireFox.
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width

**Comment by ArnoldSmith86** [comment]
> Maybe using `scrollbar-width: thin;` for FireFox would make the scrollbars more consistent.

Can you test that? Sounds like a good solution but for me they are already thin.

**Comment by bjalder26** [comment]
> > Maybe using `scrollbar-width: thin;` for FireFox would make the scrollbars more consistent.
> 
> Can you test that? Sounds like a good solution but for me they are already thin.

I think adding that is a descent solution.  It seems more, but not perfectly consistent.  It DOES make the arrows go away, and it only appears to affect FireFox (as desired).

Firefox before and after:
image

Chrome:
image
Edge:
image

**Comment by ArnoldSmith86** [comment]
I added `scrollbar-width: thin` and tweaked the fileupdater a bit (it enlarges a few more labels now).

I think this won't get much better. What do you think?

**Comment by 96LawDawg** [comment]
I reviewed in Chrome, Firefox, Edge and Safari.  No issues in Chrome or Edge.

For Safari, the top label in the row of closely spaced labels (the first one under Liz in the text room), usually worked, but sometimes it was a little tricky to get it to work.  Safari does NOT show a scrollbar until you click in the label.  It would be better if Safari could indicate that there is a scrollbar, but not sure if that is possible.

For Firefox, the same label as the one in Safari (directly under Liz) almost never worked.  I couldn't just left click and drag on the scrollbar directly and get it to work like with all the other labels.  I could get it to work by hovering and using my mouse scrollwheel or by clicking into the box and using keyboard down arrow.  I have no idea why that label would behave differently that the ones on either side of it that are the same height and width.  Must have something to do with it be so close above another one??

**Comment by ArnoldSmith86** [comment]
> For Safari, the top label in the row of closely spaced labels (the first one under Liz in the text room), usually worked, but sometimes it was a little tricky to get it to work. Safari does NOT show a scrollbar until you click in the label. It would be better if Safari could indicate that there is a scrollbar, but not sure if that is possible.
> 
> For Firefox, the same label as the one in Safari (directly under Liz) almost never worked. I couldn't just left click and drag on the scrollbar directly and get it to work like with all the other labels. I could get it to work by hovering and using my mouse scrollwheel or by clicking into the box and using keyboard down arrow. I have no idea why that label would behave differently that the ones on either side of it that are the same height and width. Must have something to do with it be so close above another one??

I'll try to have a look at that.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  It fixes problems on Chome and Firefox.  Safari (mobile) is equally as broken in this PR as it is on production.  But this is a vast improvement.

Right now on Safari, scrollbars do not work at all in either this PR or production.  If you can fix that great.  If not, this is still worth merging.

**Comment by ArnoldSmith86** [comment]
I'll just merge this in the next days. So speak up if you have any reservations.

**Pull request merged**
