### PR TITLE
Remove width/height equal to cardDefault/cardType

### PR DESCRIPTION
**Pull request by bjalder26**
This PR should address issue #680 and remove the width and height if those values are already being inherited from either cardDefault or cardType.  So, if it is a value that is overriding the cardDefault or cardType it will remain on the card, but if it is not, then it will be removed.

This is just 1/2 line of code.  All it does it make it so that if they widget is a card and the property is height or width, then it will be treated the same way inherited properties are treated in the JSON editor (not shown if they are not set to a different value).

else if(match[2] == '*' && !o.inheritFrom **&& (o.type != 'card' || (key != 'width\*' && key != 'height\*'))**)

Examples:
image
http://212.47.248.129:3711/pr-test

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3711/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
Shouldn't it be `(o.type != 'card' || (key != 'width' && key != 'height'))` (changing the first `&&` to `||`)? The way it's written it looks to me as though the default values will not be printed whenever the object is a card, independent of the width and height.

**Comment by bjalder26** [comment]
> Shouldn't it be `(o.type != 'card' || (key != 'width' && key != 'height'))` (changing the first `&&` to `||`)? The way it's written it looks to me as though the default values will not be printed whenever the object is a card, independent of the width and height.

Thanks, yes, but there was another problem too.  It should have been 'height\*' and 'width\*'.  I was missing the *.

The movable and movableInEdit were not being shown on cards when there were defaults, which they should have been.  That is now fixed.

**Review by rogerl50 — APPROVED** [review]
Code looks good to me. If someone else wants to take a look, *please* have at it, but I'm approving this one.

**Pull request merged**
