### PR TITLE
Select max widgets *after* pile resolution, not before.

### LINKED ISSUE #752: `max` and `type` do not interact properly in `SELECT`
The code
```
  "clickRoutine": [
    {
      "func": "SELECT",
      "property": "parent",
      "type": "card",
      "max": 1,
      "value": "stock"
    }
  ]
```
when run on a deck in the `stock` holder returns all the cards. This is because pile resolution happens *after* the selection of `max` children. (This code would be useful in selecting the top card of a pile.)

### PR DESCRIPTION
**Pull request by rogerl50**
Fixes #752 .

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3782/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
I noticed 2 things.  They are probably both 'worse' on the PR server.
1) SELECTing than SETting more than one cards produces a weirdly placed pile holder because although the cards will form a pile, and will be in the spot signified in the JSON, the pile will be at 0,0 and the cards will have the specified x/y values, so they are offset from the pile, which is at 0,0.  **This is exactly the same on the production server**.
2) In the off-chance the holder is set to alignChildren: false, and there is both a pile, and a card, it will always select the individual cards BEFORE selecting cards in a pile.  On the PR server it will do the same EXCEPT that it will move the entire pile when it is finally moved instead of just a single card (which I view as worse).

Otherwise it seems to work great, allowing a much simpler way to select the top card.  So I am inclined to think of the issues I mentioned as separate issues and approve this PR unless rogerl50 decides to add those issues to this PR.

**Comment by rogerl50** [comment]
> I noticed 2 things. They are probably both 'worse' on the PR server.
> 
>     1. SELECTing than SETting more than one cards produces a weirdly placed pile holder because although the cards will form a pile, and will be in the spot signified in the JSON, the pile will be at 0,0 and the cards will have the specified x/y values, so they are offset from the pile, which is at 0,0.  **This is exactly the same on the production server**.
> 
>     2. In the off-chance the holder is set to alignChildren: false, and there is both a pile, and a card, it will always select the individual cards BEFORE selecting cards in a pile.  On the PR server it will do the same EXCEPT that it will move the entire pile when it is finally moved instead of just a single card (which I view as worse).
> 
> 
> Otherwise it seems to work great, allowing a much simpler way to select the top card. So I am inclined to think of the issues I mentioned as separate issues and approve this PR unless rogerl50 decides to add those issues to this PR.

Can you put up a room that exhibits these behaviors?

**Comment by bjalder26** [comment]
> Can you put up a room that exhibits these behaviors?

There are 2 sets of buttons, holders and decks in the pr-test room.  Clicking the top one will show the fist thing I mentioned:

>SELECTing than SETting more than one cards produces a weirdly placed pile holder because although the cards will form a pile, and will be in the spot signified in the JSON, the pile will be at 0,0 and the cards will have the specified x/y values, so they are offset from the pile, which is at 0,0. This is exactly the same on the production server.

Clicking the bottom button will show the second thing I mentoned.
>In the off-chance the holder is set to alignChildren: false, and there is both a pile, and a card, it will always select the individual cards BEFORE selecting cards in a pile. On the PR server it will do the same EXCEPT that it will move the entire pile when it is finally moved instead of just a single card (which I view as worse).

These are both pre-existing issues, so I'm not saying they are a reason to hold up this PR.  It's really only if you felt like they were related enough and wanted to fix them in this PR.  They are probably issues in a different part of the code.

**Comment by rogerl50** [comment]
The first of these has to do, I believe, with the fact that the `SET`s are still in the delta update queue, which is not processed until the routine finishes, so that `updatePiles` retrieves incorrect information. As you say, that exists in production. It's beyond my ken to fix, so we should open a new issue for that.

The second issue is potentially more serious. When I click the bottom button, no cards appear to move, and yet if I look in the debugger, the cards are in fact moved to (100,100). The display can be updated by pressing the top button. This is different behavior from that in the production version. I'll try to look at this, but I'm sure it's again code that I really do not understand. It'd be great to get input from @ArnoldSmith86 or @larkob on these issues as well.

**Comment by bjalder26** [comment]
> The first of these has to do, I believe, with the fact that the `SET`s are still in the delta update queue, which is not processed until the routine finishes, so that `updatePiles` retrieves incorrect information. As you say, that exists in production. It's beyond my ken to fix, so we should open a new issue for that.

Sounds good to me.

> The second issue is potentially more serious. When I click the bottom button, **no cards appear to move**, and yet if I look in the debugger, the cards are in fact moved to (100,100). The display can be updated by pressing the top button. This is different behavior from that in the production version. I'll try to look at this, but I'm sure it's again code that I really do not understand. It'd be great to get input from @ArnoldSmith86 or @larkob on these issues as well.

Are you sure there wasn't just some unrelated browser crash or an exception if you have your browser debugger open?  When I click the bottom button I see them move.

**Comment by rogerl50** [comment]
> Are you sure there wasn't just some unrelated browser crash or an exception if you have your browser debugger open? When I click the bottom button I see them move.

When I reload the room from scratch and press the bottom button, the behavior is identical to what it is in production. So it doesn't appear that I broke anything further. But both behaviors are odd to say the least. Also note that Recall/Shuffle on the bottom holder does not appear to have the desired effect. This is probably another issue waiting to be opened.

**Comment by bjalder26** [comment]
> When I reload the room from scratch and press the bottom button, the behavior is identical to what it is in production. So it doesn't appear that I broke anything further. 

Well that's good.

> But both behaviors are odd to say the least. Also note that Recall/Shuffle on the bottom holder does not appear to have the desired effect. This is probably another issue waiting to be opened.

I know, there was already a PR for that #676.  I've started looking at that, but haven't figured it out yet.  I opened new issues for the other two.

**Review by bjalder26 — APPROVED** [review]
Code reviewed (mostly just moves code) and tested.  Some unrelated issues became apparent.  This PR fixes a known issue, and makes selecting the top card significantly more simple.

**Comment by ArnoldSmith86** [comment]
Is it possible to emulate the old `SELECT` behavior by splitting it into two `SELECT`s or something like that? Then we could add a fileupdater that detects affected `SELECT`s and migrates them.

If not, :man_shrugging:.

**Comment by rogerl50** [comment]
> Is it possible to emulate the old `SELECT` behavior by splitting it into two `SELECT`s or something like that? Then we could add a fileupdater that detects affected `SELECT`s and migrates them.
> 
> If not, 🤷‍♂️.

Feeling particularly dim today...what old SELECT behavior needs to be emulated? The current behavior is just wrong IMO, and the simplest fix will just resolve piles before picking cards. It's hard to believe that any games rely on the current behavior.

**Comment by bjalder26** [comment]
Is the behavior we'd emulate selecting a certain number of piles instead of selecting a certain number of cards?

If so, can we just do a search to see if anyone is currently using select max widgets?

**Review by ArnoldSmith86 — APPROVED** [review]
I had a quick look at the code and I think a fileupdater would be _way_ too complicated for something that probably nothing relies on anyway.

**Comment by rogerl50** [comment]
> for something that probably nothing relies on anyway.

That's what they always say 😃

**Pull request merged**
