### PR TITLE
SHIFT+F<X> now deselects the widget if it was already selected

### LINKED ISSUE #2247: deselecting using SHIFT+F1 does not work

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Fixes #2247. Looks like this was never a thing...

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2254/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Just making sure this works as expected.  Shift-F1 does not always deselect the current widget.  It only does so if the cursor is also over the widget (not sure about mobile; did not test).  I'm okay with that.  Is that what you intended?  If not, I'm not sure how it would work with multiple widgets selected.

**Comment by RaphaelAlvez** [comment]
> Just making sure this works as expected. Shift-F1 does not always deselect the current widget. It only does so if the cursor is also over the widget (not sure about mobile; did not test). I'm okay with that. Is that what you intended? If not, I'm not sure how it would work with multiple widgets selected.

I think it is as intended. this bothered me many times. if you are selecting with shift+Fx you cannot deselected and need to restart the selection if you mess up.

**Review by RaphaelAlvez — APPROVED** [review]
code looks ok and tested.

I didn't even know it was a bug but this bothered me so much in the past

**Pull request merged**
