### PR TITLE
Add Dix Dice, Dix Cards, Tangrams, other updates

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:
- Dix Dice. New game by LawDawg. Similar to Phase 10 Dice.
- Dix Cards. New game by LawDawg. Similar to Phase 10.
- Tangrams. New game by BicycleIndividual and LawDawg.
- Dominoes. Minor changes after dev game night.  Dominoes don’t change face when leaving hand; add 5 and 7 to hand buttons added; counter values default to +1 and -1; removed 5th player and shifted the room move button down; changed Unicode buttons to VTT images
- Diced. Replaced Unicode symbols with VTT images. Fixed text in restart button.
- The Team. Fixed how rocket cards are handled in 2-player variant.
- Magician.  Fixed label with parent and stackOffsetX of the hand.  Removed recall button and added holder for active trick and a trick-taking button.

Public Tutorials:
- Functions: CLICK (Modes).  Added new tutorial for mode paramater of CLICK function.
- faceTemplates.  Updated attribution regarding blue card back.  No change to code.
- Timer (Card Deal Animation). RogerLipsett simplified and shortened the code
- Arrays (Creating).  Added missing heading of “Dynamic Expressions.”  No change to code.

Library.json:
- Added brief descriptions of all public library games.
- Corrected number of players infor Ninety-Nine to 3 (instead of 2-4).

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3603/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Files loaded from revised library.json into test server room.

**Review by ArnoldSmith86 — APPROVED** [review]
Only looked at the games.

Dix Dice has a misaligned label (first one for player 2). Not that that's a bad problem.

And The Team 2 player variant can deal the rocket 4 to the AI. I don't think that should be possible, right?

image

**Comment by ArnoldSmith86** [comment]
This should fix the rocket: [The_Team.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/6712550/The_Team.zip)

**Comment by robartsd** [comment]
Sorry about the rocket. I noticed during play that the AI got no rockets. The rules say the AI should be able to get any card except rocket 4. I noticed the click routine sorted, then removed 4 cards. I changed it to remove only one, but I didn't realize that the key that was being sorted did not put the rockets in a particular order. ArnoldSmith86's file fixes the key to put the rockets in order so that rocket 4 is removed before dealing the AI instead of removing any random rocket.

**Pull request merged**
