### PR TITLE
Added pretty buttons

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
All in blue now

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3044/pr-test (or any other room on that server)

**Comment by UltimateGeek** [comment]
I'd prefer to review this after PR #42 has been promoted.

One initial question I have is: why are the icons all in an "icons-white" folder, if they are now blue? If the default color is white, but css modifies it to a different color, then I think the folder name doesn't need to have the color in it because it's not important.

**Review by UltimateGeek — COMMENTED** [review]
I think these buttons in the Add widget dialog be updated for consistency

image

**Review by UltimateGeek — COMMENTED** [review]
Should this greyed-out icon be updated for consistency?

image

**Comment by RaphaelAlvez** [comment]
Sorry I did a very bad description. 

I meant that all the interface is blue.

The buttons are in a folder called white because I downloaded them black and at some point I expect to have grey icons.

I replaced all emojis with related icons

**Comment by larkob** [comment]
Could the player list perhaps be center-aligned as well, perhaps against some neutral background and with more padding between the elements? Also, it's still difficult to identify who is yourself as the bold isn't that obvious.

**Comment by RaphaelAlvez** [comment]
> Could the player list perhaps be center-aligned as well, perhaps against some neutral background and with more padding between the elements? Also, it's still difficult to identify who is yourself as the bold isn't that obvious.

Good input. This pull request was not meant to cover overlays but I added it to my notes. My plan is to use a small person just like the one on the toolbar (but only on person). If you have any ideas on how to make a better highlight let me know

**Comment by RaphaelAlvez** [comment]
Comments from reviewers were adressed and this PR reviewed in the meeting today.

**Pull request merged**
