### PR TITLE
added commands to add or remove all cards of a deck

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
I wanted to copy a deck of cards with 96 different cardTypes to a different game. Using the normal edit mode to add every card did not work because it screws up the variables for more complicated decks. So I added a JSON editor command to do it and while I was at it, I added one to remove all cards and I updated the existing ones that only handle a single cardType to show the number of cards on the command button

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3656/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Not sure what problem you had, but this seems to simply duplicate what already exists in the All -1 and All +1 buttons on the deck edit mode.

Screenshot 2

I don't have a problem with the duplication.  Just another way to do the same thing.  The only thing I found after testing that is worth commenting on is what happens when you load an empty deck from the add widget menu.  Then you get this:

Screenshot 1

And clicking that button doesn't do anything because there are no card types defined.  Maybe hide the button if there are 0 card types?

**Comment by ArnoldSmith86** [comment]
> Not sure what problem you had, but this seems to simply duplicate what already exists in the All -1 and All +1 buttons on the deck edit mode.

Yes. But that only works when pressing `Update widget` at the bottom and for my deck in generated the text fields for the parameters wrong and then put wrong data into the deck.

That should be fixed there of course but I was too lazy.

> Maybe hide the button if there are 0 card types?

I thought I did. I'll check.

**Comment by ArnoldSmith86** [comment]
> Maybe hide the button if there are 0 card types?

Done. And all those commands have better context detection now.

Also the `card type template` command no longer crashes if the deck doesn't have `faceTemplates`.

**Review by 96LawDawg — APPROVED** [review]
Thanks for the changes.  And the improved context detection is nice.  Approved through test.

**Pull request merged**
