### PR TITLE
PL Update - Flatten the Curve

### LINKED ISSUE #1731: Flatten the Curve
Feedback from Maxio68:

Flatten the Curve needs a 0 indicator for the Outbreak counter.

### PR DESCRIPTION
**Pull request by 96LawDawg**
Fixes #1731.

Fix error in Outbreak button missing 0 option.  Also rename and one routine and tweak the css of one button.  Minor stuff.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1732/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1732-pr-test`.

**Comment by ArnoldSmith86** [comment]
Probably unrelated to this PR but the enlarge for the Event List is cut off if it is on the left for me:
image

**Comment by 96LawDawg** [comment]
> Probably unrelated to this PR but the enlarge for the Event List is cut off if it is on the left for me:

Fixed

**Review by RaphaelAlvez — APPROVED** [review]
it solves the original problem

I think there is still improovemente to be made in these cards:

image
image
image

but I don't intend to hold this pr for this

**Comment by 96LawDawg** [comment]
Those cards should be better now.

**Pull request merged**
