### PR TITLE
fixed weird numbers when spam-clicking star

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This allows only one click until the client received the server response.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1535/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1535-pr-test`.

**Comment by RaphaelAlvez** [comment]
There is still a temporary number under the start but it only goes from 0 to 1

**Review by RaphaelAlvez — APPROVED** [review]
already a better version

There is still a temporary number that appears but that not a big deal

**Comment by ArnoldSmith86** [comment]
Might be the fact that the faked number doesn't remove a zero? I'll change that.

**Comment by ArnoldSmith86** [comment]
Fixed that it would show 0. Can you trigger any more issues?

**Pull request merged**
