### PR TITLE
fixed cursor in JSON editor jumping to the start

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Whenever the JSON editor updates its text editor because of external changes to the widget, the cursor position would be reset to the beginning.

This PR saves the cursor position before external changes and tries to restore it afterwards. It tries to find the same line and restore the position inside that line because a lot about the widget structure might have changed in the update.

In practice this means it should be possible - after #540 - to edit running timers and - in combination with #539 - it should even be possible for multiple people to edit the same widget (just not the same line) at the same time.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3557/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
It will still delete 'hidden' variables that are at their default value, so in the timer you have to be a little quick placing a non-default value in there IF the timer is running.

I suspect this will also fix some of the copy/past issues, because I think sometimes this is what it was doing - jumping to the beginning.

**Comment by 96LawDawg** [comment]
So I only briefly tested this and found that it largely did not work.  As best I could tell, it seemed to work with properties that (not sure of the right word - don't have default values).  So things like grid and changeRoutine, the cursor would keep its location.  But for things like debug, css, and even precision (that show up in JSON editor as grey), the property would briefly flash an appearance, disappear, and the cursor went to the very top.

**Comment by 96LawDawg** [comment]
I forgot to clarify, as @bjalder26 said, that was with a running clock.  That's the only time I've had real issues with cursor relocation.

**Comment by ArnoldSmith86** [comment]
True. This still has the problem of disappearing grey properties. Let me see if I can find a solution for that.

**Comment by ArnoldSmith86** [comment]
> But for things like debug, css, and even precision (that show up in JSON editor as grey), the property would briefly flash an appearance, disappear, and the cursor went to the very top.

This should be fixed now. Please do some testing...

**Comment by 96LawDawg** [comment]
So I tested this and it works in most of the situations with a running timer.  But I have a room that it still doesn't work in.  Not sure what is different.  Look in http://212.47.248.129:3557/lawdawg.

**Comment by ArnoldSmith86** [comment]
>  But I have a room that it still doesn't work in.

Just to be sure: are you talking about the fact that you basically can't scroll in the editor unless you use the keyboard or is something else broken?

**Comment by 96LawDawg** [comment]
> Just to be sure: are you talking about the fact that you basically can't scroll in the editor unless you use the keyboard or is something else broken?

Yeah, that's it.  Scrolling with my mouse wheel doesn't work in that room, but if I use the cursor arrow down key, it does work.  I didn't notice that difference before.  But the mouse wheel does work in other timers (that have code long enough to need scrolling).  I was just pointing it out.  I think what you've done is a huge improvement and 98% better.  If you can't easily figure out this one strange issue, that's okay.

**Comment by ArnoldSmith86** [comment]
> Scrolling with my mouse wheel doesn't work in that room

That should be fixed now. Please put this PR through its paces again. :smile:

**Comment by 96LawDawg** [comment]
Ummm.  No.  I just tried adding a timer, adding a changeRoutine that moved the x to x+1 with every second.  The test server crashed and is so broken I think it needs a reset.  Also, before that happened, when I pressed ENTER inside of the changeRoutine to add a new blank line, the cursor when back to the beginning.

**Comment by bjalder26** [comment]
I noticed that typing on the millisecond line the cursor will jump to the end, which I think is expected.  Also, like LawDawg mentions if you press enter, then it will jump to the beginning unless you quickly hit a space.  I assume this is because the JSON doesn't really update when an Enter is pressed.

**Comment by ArnoldSmith86** [comment]
>  I just tried adding a timer, adding a changeRoutine that moved the x to x+1 with every second. The test server crashed and is so broken I think it needs a reset.

Well, you used `changeRoutine` instead of `millisecondsChangeRoutine` which triggers for your `x` change recursively.

>  Also, before that happened, when I pressed ENTER inside of the changeRoutine to add a new blank line, the cursor when back to the beginning.

I'll check this out.

**Comment by ArnoldSmith86** [comment]
> Also, before that happened, when I pressed ENTER inside of the changeRoutine to add a new blank line, the cursor when back to the beginning.

I think that's too complicated for me at the moment. It's an issue but now you can at least use commands and edit values that are already there. For some stuff, you'll have to pause your timer or whatever. Or cause the text to not be valid JSON.

**Review by 96LawDawg — APPROVED** [review]
Okay except for my stupidity in creating a recursive problem and the enter key behavior while the timer is running, I think this is good enough.  Approved through test.

**Pull request merged**
