### PR TITLE
Update library images for multiple games by ArnoldSmith86, RaphaelAlvez

### PR DESCRIPTION
**Pull request by 96LawDawg**
This commit has images only for review and comment. None of the attribution was changed until a final image is selected. All the new games will be starred in the test room so they appear at the top.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1778/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1778-pr-test`.

**Comment by 96LawDawg** [comment]
Most of these are awesome.  Some are maybe just meh or don't differ that much from what was there before.  Some games are really tough to implement.  Most important: we have to get The Team and The Team II right.

**Comment by 96LawDawg** [comment]
Just added a few new images for @RaphaelAlvez.  Also noticed that Fantasy Wars did not have similar to information, so added that and awards.

**Review by ArnoldSmith86 — APPROVED** [review]
I reverted the `lastUpdate` in both PRs using https://chat.openai.com/share/99a644ea-3390-4578-8012-7fa34a61f3d4.

**Comment by 96LawDawg** [comment]
That's pretty sweet.  So are you okay with the images for the games as well?  This set in particular.  I'm going to go ahead and merge the other one.

**Comment by ArnoldSmith86** [comment]
We can always replace one or two later. It looks like a nice improvement.

**Pull request merged**
