### PR TITLE
Add Find the Word, Oasis, CSS tutorial

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:
- Find the Word. New game by RogerLipsett. Similar to Jotto.
- Oasis. New game by LawDawg. Similar to Skull.
- Alleys.  Added seats.  Changed pawns so they inherit seat color. Updated restart button code.
- Chinese Checkers.  Added seats. Combined all variants into one using an option button to pick style of marble.
- Dix Dice.  Added seats and restart button.
- Dominoes. Changed rotation method. Changed cards to SVGs. Add 7,8,9 pip dominoes. Added seats. Expanded number of players. Added options for scoring increments of 1 or 5.  Imrpoved shift view feature.
- Flora. Changed card images to SVGs.  Combined all variants into one using an option button to pick types of cards.  Added seats.  Improved shift view feature.  Added detail to the attributions.  Updated the library image with the new cards.
- Reward.  Added seats.  Changed cards to css. Updated menu system code. Updated attribution and changed library image.
- Solitaire. Fixed a few dragging and stacking issues in some of the variants.
- Stratagem.  Added seats.
- Tantrums.  Added seats and revised layout slightly.
- Tittle.  Added seats and revised layout slightly.  Improved shift view feature.
- Tutti Frutti. Autoscore now calculates before cards are moved off the board.

Public Tutorials:
- CSS. New tutorial with 4 variants: basic, advanced, caution, cards
- Button Appearance. Revised CSS shapes variant to include clip-path examples and changed borderRadius from css string to stand-alone property.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:1100/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Revised games/tutorials successfully loaded from new library.json file.

**Comment by ArnoldSmith86** [comment]
I'll have a look at the test in the next days.

**Comment by 96LawDawg** [comment]
Help with TestCafe, please.  I changed a lot of things in Reward, so I redid the buttons in TestCafe.  Got all of that working, but the checksum changes every time.  I update the checksum to what it tells me it should be and then it gives me a new checksum.  I update that, same thing.  I haven't seen this before and don't know what is going on.

But after writing this, I think there may be one thing new: seats.  I sat in a seat in the room.  I vaguely remember that seats may not be supported in TestCafe.  I will try changing that.

**Comment by ArnoldSmith86** [comment]
> I vaguely remember that seats may not be supported in TestCafe.

I don't see why they shouldn't be. If they are the problem, I'll see if I can fix that.

**Comment by 96LawDawg** [comment]
The problem seems to be seats.  I removed the TestCafe step to click on a seat (and that was the only change I made) and everything worked fine.  Somehow, clicking on a seat appears to give a different checksum every time.  I'll open an issue.

Aside from all that, the new and changed games in this PR are ready for review.

**Comment by 96LawDawg** [comment]
So based on #1106 I thought it was safe (and a good test) to add seats back in.  But the checksum keeps shifting again.  Am I doing something wrong?

**Comment by robartsd** [comment]
> So based on #1106 I thought it was safe (and a good test) to add seats back in. But the checksum keeps shifting again. Am I doing something wrong?

I don't think so. I'll see if I can figure this out.

**Comment by robartsd** [comment]
I got '069236b7f9c1a1efe20b0e02c0d850ba' as the checksum in Gitpod. This matches the checksum for Reward in [cfdb8e5](https://github.com/ArnoldSmith86/virtualtabletop/pull/1100/commits/cfdb8e5804653c7c58a4c664b477ee3c4d2a3694) and [6c2ed87](https://github.com/ArnoldSmith86/virtualtabletop/pull/1100/commits/6c2ed87c89f44a08b5fbf218141d75633bef1fe7).

Undercover failed for some reason in [7df0a48](https://github.com/ArnoldSmith86/virtualtabletop/pull/1100/commits/7df0a48142b8a926a6f2eaa9437286f491fb1bef) and you copied that checksum to reward in 6c2ed87.

**Comment by 96LawDawg** [comment]
Copy and paste error.  Well, thanks for figuring that out.  Was driving me nuts.

Games and tutorials in this PR are ready for review by whoever.

**Comment by robartsd** [comment]
I found issues with a few games (have not tried all the games):

- [ ]  Find the Word: Right side player backspace does not work when guessing.
- [ ]  Chinese Checkers: marbles shift when changing styles.
- [ ]  Dix Dice: top left score box associated with wrong seat.

**Comment by 96LawDawg** [comment]
> I found issues with a few games (have not tried all the games):
> 
> * [ ]   Find the Word: Right side player backspace does not work when guessing.
> * [ ]   Chinese Checkers: marbles shift when changing styles.
> * [ ]   Dix Dice: top left score box associated with wrong seat.

Find the Word and Dix Dice are "fixed" outside the PR, but I am battling github to try and make it take my changes.

Chinese Checkers isn't fixable without a ton of work that isn't worth it.  They shift because they use different image sizes for their source, so the offsets and scales needed to match up with the board are different.  As long as you don't change marbles during the middle of a game, you are fine.  And if you do change and the offsets get screwed up, you can change back with no problem.

**Comment by 96LawDawg** [comment]
I've been having trouble getting a couple of revised files to upload.  Also, this change may be so big that people are afraid to take it on.  Going to close it and make a library update that takes the new games out of this plus one the updates to one game I know has been played some.  After that is merged, I'll do an update with other new games.  When there is a lull, I'll circle back around and do the games that just have minor updates to seats or whatever.

**Pull request closed without merging**
