### PR TITLE
PL: Spin 5, Fix CSS Transitions

### PR DESCRIPTION
**Pull request by 96LawDawg**
An earlier PR changed the behavior of transitions when changing parents.  That modified the behavior in Spin 5.  This PR fixes that game.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1606/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1606-pr-test`.

**Comment by ArnoldSmith86** [comment]
Hmm, dropping into an already rotated holder results in rotated pieces. They fix themselves when rotating the holder but it's still pretty weird.

**Comment by 96LawDawg** [comment]
> Hmm, dropping into an already rotated holder results in rotated pieces. They fix themselves when rotating the holder but it's still pretty weird.

Good catch.  Fixed.

**Review by RaphaelAlvez — APPROVED** [review]
this seems to fix all the problems we found

**Pull request merged**
