### PR TITLE
Add Naval Warfare to PL

### PR DESCRIPTION
**Pull request by 96LawDawg**
Similar to Battleship (by LawDawg)

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1930/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1930-pr-test`.

**Comment by 96LawDawg** [comment]
That's not good.  Doesn't take me as long, but still a bit.  I may have to make the boards just an image and forget about holders.

**Comment by ArnoldSmith86** [comment]
I think you just forgot to remove the recursive inheritance from the column labels at the top.

Feel free to open an issue and append this game. Looks like a nice test case. :grinning:

**Review by ArnoldSmith86 — APPROVED** [review]
Performance issues seem to be fixed.

**Pull request merged**
