### PR TITLE
Round y coordinates of checkers and classic pieces.

### LINKED ISSUE #1307: y coordinates of pieces are not integers
This is in the add widget overlay. Is there a reason why they shouldn't be?

### PR DESCRIPTION
**Pull request by rogerl50**
The y-coordinates are computed by centering them around the pins. This PR just rounds the result to avoid random decimals. Fixes #1307

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1308/pr-test (or any other room on that server)

After merging, a backup will be available at https://beta.virtualtabletop.io/editor/PR1308-pr-test.

**Review by RaphaelAlvez — APPROVED** [review]
Code reviewed. This is mainly useless but I guess this was bothering you.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Review by ArnoldSmith86 — APPROVED** [review]
I did a thorough code review and I _really_ like your coding style! :rofl:

**Comment by rogerl50** [comment]
You can all make fun of me as you wish :smiley:

I noticed this while I was making an incorrect update to the grid CSS stuff. If I had been smarter about that, I would never have noticed this horrible problem.

**Pull request merged**
