### PR TITLE
TTS importer

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Very early stages.

I wanted to do something different so I started to write a TTS importer similar to the one in my PCIO editor.

So far it only creates `deck` widgets for decks that are not in any container.

~Usage is similar to the editor:~

1. Go to [the Steam workshop](https://steamcommunity.com/app/286160/workshop/).
~2. Use [the steam workshop downloader](https://steamworkshopdownloader.io/) to download.~
~3. Upload ZIP file like a VTT/PCIO file.~
2. Add workshop link to VTT room with the `Enter link` button.

This will probably never be "upload & play" but we might be able to import quite a lot of stuff...

Gonna leave this here for later:

`curl -s 'https://steamcommunity.com/workshop/browse/?appid=286160&searchtext=sprawlopolis&childpublishedfileid=0&browsesort=textsearch&section=home' | grep -Po 'SharedFileBindMouseHover[^{]+\K.*286160.'`

`curl -s $(curl -s 'http://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1' -d itemcount=1 -d 'publishedfileids[0]=2116072828' | grep -Po '"file_url":"\K[^"]+') | bsondump --quiet --pretty > WorkshopUpload.json ; zip out.zip WorkshopUpload.json ; rm WorkshopUpload.json ; mv out.zip ~/Downloads/`

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3955/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Is anyone interested in this? Because I pretty much only started because I can...

**Comment by robartsd** [comment]
I'm a bit interested, but have not tried it out yet. I expect that I will be more interested after #878 is solved as I imagine that many layouts from TTS might work better with players being able to adjust their view.

**Comment by 96LawDawg** [comment]
If this were not in draft form, I would approve it.  I have used it extensively to bring in assets from TTS.  I did suggest some additional wording in the overlay so that people don't misunderstand what this can do.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  The latest commit that makes sure all of the widgets are in the visible room is a nice touch and it works.

**Pull request merged**
