### PR TITLE
no longer send deltas when creating widgets

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This is one of the biggest remaining problems and I hope this fixes it.

Whenever a new widget is created (for example a pile), the client immediately sends a delta to the server. Without sending the delta, the new widget would not have been added to the `widgets` map of the client who created it. So any code after the widget creation (for example `card.set("parent", newID)`) would fail because the pile (`newID`) does not really exist yet. It is just inside the delta that has not been applied yet.

Normally this is not a problem but it makes the changes of a client interaction non-atomic. Meaning that another client can cause conflicts in the middle of the changes of a button click.

For example: one client clicks a fairly complex reset button. It recalls cards to a holder so it has to create a new pile. Everything else the button does does not send a delta until the button is completely done. In the meantime another client receives the delta to create a new pile (which it does - a pile with a zero) but then the user starts to drag a card that was supposed to be recalled. The server does not know that the first client locally already recalled that card so it accepts the second user dragging the card. When the first client finishes its button routine sending a big delta, the server notices that it is invalid because the second client already changed the card position to something else. The big reset delta is discarded and the triggering client gets sent the server state to resolve the conflict. So now both clients have a new pile with zero cards and nothing will fix it (unless the users do it).

This PR changes the core behavior. When a new widget is added, it does not send an intermediate delta. It instead calls `addWidget` so the local client adds the widget without sending the delta. The function `receiveDelta` also needs an update because it can no longer assume that new widgets have been created already (so now it first applies all widget creations and then any other updates).

**This touches the very core of VTT so please test this vigorously.** Make sure that changes are properly applied to the initiating client _and_ receiving clients.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3892/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
In a new room, add a 52-card deck. You get a pile that say 104, but the tree view in the editor shows one holder with 52 cards. Delete that holder, and you get an empty tree view, but a holder still in the room. 

And a question: how (where) does a delta actually get added when a widget is added? I can't see where `addWidget` causes that to happen.

**Comment by rogerl50** [comment]
The TestCafe tests appear to be hanging.

**Comment by ArnoldSmith86** [comment]
> And a question: how (where) does a delta actually get added when a widget is added? I can't see where `addWidget` causes that to happen.

`addWidget` is the function that adds widgets from a received delta. So it doesn't send a delta.

`addWidgetLocal` is the function that creates a new widget locally and then uses `sendPropertyUpdate` and `sendDelta` to send it to the server.

**Comment by rogerl50** [comment]
> > And a question: how (where) does a delta actually get added when a widget is added? I can't see where `addWidget` causes that to happen.
> 
> `addWidget` is the function that adds widgets from a received delta. So it doesn't send a delta.
> 
> `addWidgetLocal` is the function that creates a new widget locally and then uses `sendPropertyUpdate` and `sendDelta` to send it to the server.

I see. I misread what the code was doing. Too late, of course, but aren't these routines named backwards? addWidgetLocal should add locally and addWidget should add it to all clients, just from the names...

**Comment by ArnoldSmith86** [comment]
> Too late, of course, but aren't these routines named backwards?

I don't know. You can look at it either way. They should probably have completely different names. `addWidget` adds a widget coming from the server; `addWidgetLocal` locally creates a new widget. :man_shrugging:

> In a new room, add a 52-card deck. You get a pile that say 104, but the tree view in the editor shows one holder with 52 cards. Delete that holder, and you get an empty tree view, but a holder still in the room.

This should be fixed now. The order of function calls caused any new widget to be added twice if it was not created inside a `batchStart`/`batchEnd` block.

**Comment by ArnoldSmith86** [comment]
Please also test if `SET`ting a widget's `id` still works. Because that also creates a new widget. Also `CLONE` and stuff.

**Comment by RaphaelAlvez** [comment]
That's description seemed almost apocalyptic. Going to try to review that as soon as possible

**Comment by robartsd** [comment]
The failed test for "Create game using edit mode"  has the original spinner (`jyo2`) in the state (it should have been removed), but not the duplicated spinner (`jyo3`).

Reward is failing simply because two widgets (`3nsj` and `srda` - probably cloned reinforcements) have their properties listed in a different order in the tests than in the reference (both are `y`, `id`, `parent` instead of `id`, `parent`, `y`). It wouldn't be a bad idea to have a canonical format for JSON state to use in TestCafe testing.

**Comment by rogerl50** [comment]
We need a cooperative effort to try to test this with multiple clients, I think.

**Comment by bjalder26** [comment]
> We need a cooperative effort to try to test this with multiple clients, I think.

image

**Comment by ArnoldSmith86** [comment]
Yes. But I gotta check those TestCafé errors first. The ones with property order are obviously inconsequential but I have no idea why the first test removes the wrong widget (didn't look yet).

**Comment by ArnoldSmith86** [comment]
Splitting a pile in production produces these two deltas (it sends the first intermediate one as soon as the new pile is created):

```Javascript
{
  s: {
    jyo2_K_H: { parent: null, x: 522, y: 393, z: 104 },
    jyo2_Q_H: { parent: null, x: 522, y: 393 },
    rry0: {
      type: 'pile',
      parent: null,
      x: 522,
      y: 393,
      width: 103,
      height: 160,
      id: 'rry0'
    }
  },
  id: 13
}
{
  s: {
    jyo2_K_H: { parent: 'rry0', x: null, y: null },
    jyo2_Q_H: { z: 106, parent: 'rry0', x: null, y: null },
    jyo2_J_H: { parent: 'rry0', x: null, y: null, z: 108 },
    jyo2_T_H: { parent: 'rry0', x: null, y: null, z: 110 },
    jyo2_9_H: { parent: 'rry0', x: null, y: null, z: 112 },
    jyo2_8_H: { parent: 'rry0', x: null, y: null, z: 114 },
    jyo2_7_H: { parent: 'rry0', x: null, y: null, z: 116 },
    jyo2_6_H: { parent: 'rry0', x: null, y: null, z: 118 },
    jyo2_5_H: { parent: 'rry0', x: null, y: null, z: 120 },
    jyo2_4_H: { parent: 'rry0', x: null, y: null, z: 122 },
    jyo2_3_H: { parent: 'rry0', x: null, y: null, z: 124 },
    jyo2_2_H: { parent: 'rry0', x: null, y: null, z: 126 },
    jyo2_A_H: { parent: 'rry0', x: null, y: null, z: 128 }
  },
  id: 14
}
```

Splitting a pile with this PR produces this one delta:
```Javascript
{
  s: {
    jyo2_K_C: { parent: '2njb', x: null, y: null, z: 52 },
    jyo2_Q_C: { parent: '2njb', x: null, y: null, z: 54 },
    '2njb': {
      type: 'pile',
      parent: null,
      x: 108.5,
      y: 434,
      width: 103,
      height: 160,
      id: '2njb'
    },
    jyo2_J_C: { parent: '2njb', x: null, y: null, z: 56 },
    jyo2_T_C: { parent: '2njb', x: null, y: null, z: 58 },
    jyo2_9_C: { parent: '2njb', x: null, y: null, z: 60 },
    jyo2_8_C: { parent: '2njb', x: null, y: null, z: 62 },
    jyo2_7_C: { parent: '2njb', x: null, y: null, z: 64 },
    jyo2_6_C: { parent: '2njb', x: null, y: null, z: 66 },
    jyo2_5_C: { parent: '2njb', x: null, y: null, z: 68 },
    jyo2_4_C: { parent: '2njb', x: null, y: null, z: 70 },
    jyo2_3_C: { parent: '2njb', x: null, y: null, z: 72 },
    jyo2_2_C: { parent: '2njb', x: null, y: null, z: 74 },
    jyo2_A_C: { parent: '2njb', x: null, y: null, z: 76 }
  },
  id: 1
}
```

So in production the `parent` of two cards is set to `null` and the next delta sets it to the ID of the newly generated pile.

This PR does not change the fact that `parent` is first set to `null` _but_ the delta is not sent at that point so setting the `parent` to the ID afterwards, updates that parent _in the delta_ so the update to `null` is never seen by the server.

Setting it to `null` removes the property entirely from the room state and resetting it to the ID adds the property back to the end of the widget JSON. This PR doesn't send the `null`, the property is not removed so it is updated in-place without moving to the end.

So now that I know why the order of properties is changing, I'm fine with it and I'll check and update the TestCafé hashes. The failure with the spinner in the first test is unrelated. I fixed that; I just didn't push the update yet.

**Comment by ArnoldSmith86** [comment]
There's still a problem with Bhukhar. Two cards are swapped. I don't know why yet. Thanks for adding that test.

**Comment by robartsd** [comment]
> So now that I know why the order of properties is changing, I'm fine with it and I'll check and update the TestCafé hashes. The failure with the spinner in the first test is unrelated. I fixed that; I just didn't push the update yet.

I still think it would be good if we had a representation of state that always sorted object keys (at all levels) to use for TestCafe hashes.

https://github.com/ShivrajRath/jsonabc
https://github.com/zgrossbart/jdd
https://github.com/circlecell/jsoncompare.com

**Comment by ArnoldSmith86** [comment]
I'm not saying that's a bad idea but I was actually glad the tests failed. Something obviously changed and I'm glad that I looked into why.

**Comment by ArnoldSmith86** [comment]
I looked into the TestCafé test for Bhukhar where dealing cards now leads to two cards ending up in different piles (players).

When shuffling, the two cards get identical `z` values. And they end up in different piles if the result of the shuffle is sent as its own delta or if shuffling and dealing are in the same delta.

The problem is `this.childArray.sort` in function `Widget.children` which changes `this.childArray` in place and I'm pretty sure that the order of widgets with the same `z` gets inverted every time you call `sort`. I'm not sure why but the function apparently gets called a different count of times now.

While this is a potentially game breaking change, I think it's worth it. There's probably a way to add complexity so it gets called the same count of times but I don't want to do that.

It's technically not related to this PR but it would probably be better if that sort is deterministic going forward. My proposal would be adding a secondary sort by `id` because that has to be unique. I'll probably add a commit for that shortly but if you have reasons to remove it, please present them.

**Comment by ArnoldSmith86** [comment]
I tried the secondary sort by `id`. I didn't expect any changes but the tests for FreeCell and Reversi changed _a lot_. No need to make the impact even bigger.

At this point I feel pretty confident about this PR and we should start testing it thoroughly.

**Comment by rogerl50** [comment]
So if I understand correctly, you'll just change the hash for the Bhukhar test?

**Comment by robartsd** [comment]
> The problem is `this.childArray.sort` in function `Widget.children` which changes `this.childArray` in place and I'm pretty sure that the order of widgets with the same `z` gets inverted every time you call `sort`. I'm not sure why but the function apparently gets called a different count of times now.

> It's technically not related to this PR but it would probably be better if that sort is deterministic going forward. My proposal would be adding a secondary sort by `id` because that has to be unique. I'll probably add a commit for that shortly but if you have reasons to remove it, please present them.

> I tried the secondary sort by `id`. I didn't expect any changes but the tests for FreeCell and Reversi changed _a lot_. No need to make the impact even bigger.

Still not technically related to this PR, but rather than a secondary sort on `id` I would prefer to solve the sort issue by not inverting order of widgets with the same `z`. Such a change may or may not have an impact on other current tests.

**Comment by ArnoldSmith86** [comment]
> I would prefer to solve the sort issue by not inverting order of widgets with the same `z`.

Any suggestions on how to do that?

**Comment by robartsd** [comment]
> > I would prefer to solve the sort issue by not inverting order of widgets with the same `z`.
> 
> Any suggestions on how to do that?

Sort should not be reversing the array when 'z' is equal. I don't think `this.childArray.sort` in `Widget.children` is causing the reversal, but it is returning a reference to the array. Anywhere that reference is used could call `.reverse` causing the order of elements in `Widget.childArray` to change. Perhaps a shallow copy should be returned instead.

I have not yet identified anywhere in the code where this reference is reversing the order. 'SORT' calls `sortWidgets` with `holder.children` but `Holder.children` applies a filter to `Widget.children` thus creating a new array.

**Comment by ArnoldSmith86** [comment]
> I don't think `this.childArray.sort` in `Widget.children` is causing the reversal, but it is returning a reference to the array. Anywhere that reference is used could call `.reverse` causing the order of elements in `Widget.childArray` to change. Perhaps a shallow copy should be returned instead.

While I was playing around with this, I stumbled upon #1111. So the solution should probably be to avoid duplicate z values in the first place unless explicitly set through automation. And I think shuffling cards is the only place they occur.

**Comment by ArnoldSmith86** [comment]
With #1111 and #1112 I think we shouldn't touch the problem in this PR.

**Comment by robartsd** [comment]
> There's still a problem with Bhukhar. Two cards are swapped. I don't know why yet. Thanks for adding that test.

#1112 also swapped two cards in Bhukhar. I'm guessing that two cards got the same 'z' value in a shuffle.

**Comment by robartsd** [comment]
With PR #1112, the changes here no longer cause additional changes in Bhukhar.

**Review by robartsd — APPROVED** [review]

**Pull request merged**
