### PR TITLE
game library overhaul

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Things I want to accomplish in this PR:

- [x] Get rid of the git submodule for the library. IMHO it's just an unnecessary complication.
- [x] Extract the vtt files in the repo for better version control.
- [x] Properly split the library into games, tutorials and assets.
- [x] Redo the way public library games are loaded and stored. One goal is to fix the problem that existing public library games in a room library frequently break when they receive updates.
- [ ] Implement the new game library design and functionality we discussed on Figma (see screenshots below).
  - [x] Split games into categories.
  - [x] Add star buttons to move public library games into your own game list at the top.
  - [x] Add quick filters for language and player count.
  - [x] Add search bar.
  - [ ] Keep track of the currently active game.
  - [ ] Implement the popup variant selection when clicking a game.
  - [ ] Implement the save game feature. This might slip into a separate PR; depends on what I have to touch along the way.
- [ ] Move assets, tutorials, saving the game state and editing game metadata somehow to the edit mode.

This is the current version of our mock-up. That's basically the current goal (the wide sidebar will be its own PR):
Screenshot from 2021-09-30 21-12-03
Screenshot from 2021-09-30 21-13-03

Notes:

- [ ] `urlProperties.load` needs to be fixed.
- [x] The order of variants is pretty random now. That should be fixed.
- [ ] `REMOVE BEFORE MERGE` needs to be removed. :scream: 

In case I need it again: `for i in *.vtt; do mkdir "${i:0:-4}"; cd "${i:0:-4}"; unzip ../"$i"; cd ..; done`

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3791/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
The test server should work now in case anyone was waiting...

**Comment by RaphaelAlvez** [comment]
> I'm not quite sure if I understand what you're saying. :smile:
> 
> My plan would be to hide everything behind the "Edit mode" toggle that a player doesn't need. And I think it's nice to have the tutorials features pretty prominently in the edit mode.

I was reviewing it right now. I had the impression that the add game from public library was still and option but now it would rather add a copy of the game (no ⭐ option).

Then the tutorials would be there to.

But now I'm the one not sure of what you mean.  Where in edit mode do you want to put them?

**Comment by ArnoldSmith86** [comment]
Comparing The Team to production shows quite a lot of subtle changes:

image

image

Is that intentional? Are you aware? @mousewax

**Comment by mousewax** [comment]
I am aware there may be subtle but not game-breaking changes to the games themselves in `room`. If there are, I need to know about them to fix them. All of those changes SHOULD be purely cosmetic.

**Comment by RaphaelAlvez** [comment]
> I am aware there may be subtle but not game-breaking changes to the games themselves in `room`. If there are, I need to know about them to fix them. All of those changes SHOULD be purely cosmetic. 

Ideally there should be no changes at all.
Hard to know when those changes would break a game design

That being said I had a hard time trying to find the difference between both images

**Comment by mousewax** [comment]
Some of the subtle changes will be in things like font smoothing that may make sizing and line heights appear to be  adjusted by about a pixel when really no adjustment is happening. Nothing should actually change in size or appearance beyond that.

**Comment by mousewax** [comment]
I was able to shore up some of the changes, but there is still one that's puzzling.
Somewhere the inline styles are being set differently in these two rooms. Since they're inline styles in the room, I don't think Framework7 is causing it (since it does not set any inline styles by itself).

image

It's not a massive change, but it's noticeable.

**Comment by mousewax** [comment]
image
image

and 

image
image

**Comment by robartsd** [comment]
> Some of the subtle changes will be in things like font smoothing that may make sizing and line heights appear to be adjusted by about a pixel when really no adjustment is happening. Nothing should actually change in size or appearance beyond that.

These types of changes probably already vary between different devices/browsers in games now. One of the reasons pro designers using frameworks is to reduce how much the particulars of the rendering engine used affect the rendered result.

**Comment by mousewax** [comment]
> These types of changes probably already vary between different devices/browsers in games now. One of the reasons pro designers using frameworks is to reduce how much the particulars of the rendering engine used affect the rendered result.

Yep. Which is where Framework7 shines, but I don't want it bleeding over into the game engine. There's a lot of overlapping css selectors that I'm still rummaging through to keep apart.

**Comment by robartsd** [comment]
> I was able to shore up some of the changes, but there is still one that's puzzling. Somewhere the inline styles are being set differently in these two rooms. Since they're inline styles in the room, I don't think Framework7 is causing it (since it does not set any inline styles by itself).
> 
> image
> 
> It's not a massive change, but it's noticeable.

IIRC the twoRowBottomAlign code in label reads in the height used and adjusts the top padding.

**Comment by 96LawDawg** [comment]
I had a thought about how to incorporate tutorials (and assets if we keep them).  We are already planning to have drop-down filters.  Have a selection for games, tutorials (and assets).  The default is games so people will only see games unless they specifically want tutorials.  And don't have an option for "all."  Doing it this way, we could also add some rooms that are "tests" for TestCafe that will be in the library but will never show to the public because they won't be on a drop down list.  I'm not against putting the tutorials on the edit button.  But this also seems like a reasonable solution with the added TestCafe advantage.

**Comment by ArnoldSmith86** [comment]
I'm closing this. #1223 will be merged first and afterwards we can pick commits from this one.

**Pull request closed without merging**
