### PR TITLE
Spinner customization

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
- Fixes a bug where spinner's lineText and colorText would not update until you refreshed the room and made them available to customization on css
- Finally added the background tutorial for spinners

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1815/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1815-pr-test`.

**Review by 96LawDawg — APPROVED** [review]
Tutorial looks fine.  Basic spinners still look and work normally.  A brief look at the code changes seems harmless enough; just some coloring and css tweaks.  Approved through test and limited code review.

**Comment by RaphaelAlvez** [comment]
> Tutorial looks fine.

Some sort of English review is also appreciated

**Comment by 96LawDawg** [comment]
> Some sort of English review is also appreciated

That was already included at no extra charge.

**Comment by RaphaelAlvez** [comment]
> That was already included at no extra charge.

Thanks 😁

**Pull request merged**
