### PR TITLE
Correctly process 'return: false' in debugging. Fixes #767

### LINKED ISSUE #767: "return":false causes "Show Routine Debug Output" to drop some levels of output
While in the Ctrl-J editor, when you `CALL` another routine and specify `"return":false`,  the output "Show Routine Debug Output" is missing a lot of stuff.

### To reproduce:

1. Load the attached vtt file [return_false_bug_demonstration.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/7229124/return_false_bug_demonstration.zip) (I changed the extension to .zip so GitHub would accept it.) A full copy of the JSON file from the VTT is inline below as well.
2. "Play"
3. Ctrl-J to enter the editor
4. Click the `"return": true` button.
5. Hover over "Show Routine Debug Output"
6. Observe output that looks something like this (which is expected):

```
      ▼ bug-trigger1: clickRoutine
        ▼ CALL anotherRoutine and return result => 1
          ▶ Original and applied operation
          ▶ var result = 1 => 1
          ▶ Variables and collections afterwards
```

7. Click the `"return": false` button.
8. Hover over "Show Routine Debug Output"

### Observed behavior:

Show Routine Debug Output looks like this:

```
      ▶ var result = 1 => 1
```

### Expected behavior:

Show Routine Debug Output looks something like this:

```
      ▼ bug-trigger: clickRoutine
        ▼ CALL anotherRoutine and no return
          ▶ Original and applied operation
          ▶ var result = 1 => 1
          ▶ Variables and collections afterwards
```

In more complicated examples, the incorrect output is more complex and different, but there are definitely problems.

### Reproduction script

```
{
  "_meta": {
    "version": 3,
    "info": {
      "name": "return false bug demonstration",
      "image": "",
      "rules": "",
      "bgg": "",
      "year": "0",
      "mode": "vs",
      "time": "30",
      "players": "2-4",
      "language": "US",
      "variant": "",
      "attribution": ""
    }
  },
  "bug-trigger": {
    "type": "button",
    "text": "\"return\": false",
    "clickRoutine": [
      {
        "func": "CALL",
        "routine": "anotherRoutine",
        "return": false
      }
    ],
    "anotherRoutine": [
      "var result = 1"
    ],
    "x": 0,
    "y": 0,
    "id": "bug-trigger"
  },
  "bug-trigger1": {
    "type": "button",
    "text": "\"return\": true",
    "clickRoutine": [
      {
        "func": "CALL",
        "routine": "anotherRoutine",
        "return": true
      }
    ],
    "anotherRoutine": [
      "var result = 1"
    ],
    "x": 0,
    "id": "bug-trigger1",
    "y": 100
  }
}
```

### PR DESCRIPTION
**Pull request by rogerl50**
<strike>1. Fix 'return: false' debug information, and make several related changes in CALL processing. The problem was an unnecessary and harmful 'break' after CALL processing. In addition, the return variable and collection were being set even if 'return: false' was specified. </strike>

1. Fix 'return: false' debug information.

2. Fix a minor problem in 'SELECT' debug information reporting.

Test room at http://212.47.248.129:3771/pr-test

### CODE REVIEW

**Review by bjalder26 — APPROVED** [review]
I'm going to approve based on testing.  I don't think there is a chance of breaking games, and if it is not perfect, then it is certainly an improvement.

**Comment by ArnoldSmith86** [comment]
If you remove the `break`, this doesn't terminate the code execution after the `CALL` anymore or did I miss anything?

**Comment by rogerl50** [comment]
> If you remove the `break`, this doesn't terminate the code execution after the `CALL` anymore or did I miss anything?
> 
> To clarify: `"return": false` does not mean that the called function won't return any variables. It means that the code execution will not return to the calling function - so anything after the `CALL` would not be executed at all. This is only useful if the `CALL` is conditional (if it has a `skip` or is inside an `IF`).

Well, that's not what the Wiki says. But based on the original CALL PR, you are correct and the Wiki is wrong. I'll change this PR and resubmit for review. I'll also fix the Wiki.

**Comment by AlanDeSmet** [comment]
Ouch. My intention, based on the wiki, was to not receive a return value at all. I suppose easily enough worked around (`"variable":"unused"`).

**Comment by rogerl50** [comment]
@ArnoldSmith86 Is "return: false" useful as specified? It will terminate the execution of the CALLing routine only - not of any routines that might call that routine. So for example:
```
 "clickRoutine": [
    {
      "func": "CALL",
      "routine": "firstRoutine"
    },
    "var click = true"
  ],
  "firstRoutine": [
    {
      "func": "CALL",
      "routine": "nestedRoutine",
      "return": false
    },
    "var first = true"
  ],
 "nestedRoutine": [
    "var nested = true"
  ]
```
Here the execution of the `clickRoutine` completes even though return:false is specified in the call to `nestedRoutine`. What is the use case for using "return: false"?

**Comment by ArnoldSmith86** [comment]
> What is the use case for using "return: false"?

:man_shrugging:

I never used it. It's basically a side effect of the way `CALL` came into existence. I'm not sure if @larkob had a use case for it in mind.

**Review by ArnoldSmith86 — APPROVED** [review]
I didn't test anything (should probably be done again before merging) but the code looks like it would still work now.

**Comment by bjalder26** [comment]
This appears to behave like explained by ArnoldSmith86 now, but I'm pretty sure this could now break games without a fileupdater.

It seems to me like a fileupdater would need to change all the `"return": "false"` to `"return": "true"`.  Hopefully we can safely assume that nobody was using `"return": "false"` to actively prevent the result variable from being "returned", because if you didn't want it returned, then presumably you wouldn't use it later in the JSON anyway (I think there are probably convoluted JSON that could utilize that, but I don't see why anyone would do that).

For all the `"return": "true"` it seems like the behavior would be the same.  I'm doing something similar in #722, but for some odd reason I can't get it to work on the PR server.

I thinking to make that update you'd need to use these two parts in the right spots.
```js
  for(const operation of routine) {
    if(operation.func == 'CALL') {
      updateProperties(operation.properties, v);
    }
```
```js
 if(property == 'return' && properties[property] == false)
      properties[property] = true;
```

**Comment by rogerl50** [comment]
> This appears to behave like explained by ArnoldSmith86 now, but I'm pretty sure this could now break games without a fileupdater.
> 
Perhaps I'm confused, but I don't see how this PR changes the behavior of the caller or callee at all; all it changes now is the debugging information. Moving the `if (a.return)` to the end of the large `for` loop really has no effect except for allowing the intermediate calls to logging routines to execute.

**Comment by bjalder26** [comment]
> > This appears to behave like explained by ArnoldSmith86 now, but I'm pretty sure this could now break games without a fileupdater.
> 
> Perhaps I'm confused, but I don't see how this PR changes the behavior of the caller or callee at all; all it changes now is the debugging information. Moving the `if (a.return)` to the end of the large `for` loop really has no effect except for allowing the intermediate calls to logging routines to execute.

You are right.  I thought it used to work differently.

**Comment by rogerl50** [comment]
> You are right. I thought it used to work differently.

It did. Then I changed it :smiley:

**Review by bjalder26 — APPROVED** [review]
Appears to be working as expected & now catches the information required.
image

**Pull request merged**
