### PR TITLE
optimize default card back

### LINKED ISSUE #702: Default deck card back slow to load
The XML file for the default deck card back looks really complicated with a bunch of transform/translate instructions.  It seems to cause a minor lag when cards are pulled from a deck.  Below shows about 1/5th of the xml.  I suggest we create a less-complicated svg for the default deck, and possibly even replace the current file with it.

image

### PR DESCRIPTION
**Pull request by robartsd**
Closes #702 : Optimized default card back using https://jakearchibald.github.io/svgomg/

### CODE REVIEW

**Comment by bjalder26** [comment]
That is a MUCH better result than I got trying to optimize it using a different tool.  Edge still struggles with the image on the production server where will-change: transform is off.  You can notice that when you move a card over a deck, or try to pull a card off of a deck there is a lag.

You can see that here (new image used on right): https://virtualtabletop.io/Issues
Room: # 702 Default Card Back

However, I also tested it on the server for PR #698 where the top two cards and the pile have will-change: transform turned on.  On the left is the current image, and on the right is the new image.
http://212.47.248.129:3698/pr-test

To me it seems like the little bit of lag pulling a card off the deck that remained in the left deck is gone in the right deck.

**Review by bjalder26 — APPROVED** [review]
Approving based on testing.  Appears to be a slight performance improvement in Edge (really all that was needed).  Even at 10x the normal size the images appear crisp.  Highly unlikely this PR could cause problems.

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 no bot server?

**Comment by bjalder26** [comment]
> @ArnoldSmith86 no bot server?
Looks like this is it (same card back).
http://212.47.248.129:3703/pr-test

**Review by RaphaelAlvez — APPROVED** [review]
Going to merge this PR since we have a lot of PRs open and this is approved. I also tested and works fine for me.

**Pull request merged**
