### PR TITLE
Exclude audio property from inheritFrom

### PR DESCRIPTION
**Pull request by bjalder26**
Addresses issue https://github.com/ArnoldSmith86/virtualtabletop/issues/1026 . I do not think there is ever an appropriate time for the audio property to be inherited.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4038/pr-test (or any other room on that server)

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
The array with properties is supposed to be the list of excluded properties. Your change to line 75 makes it obvious that the two if checks are in the wrong order. Please swap them so you don't need to change the `== '*'` and see if stuff breaks.

**Comment by bjalder26** [comment]
> The array with properties is supposed to be the list of excluded properties. Your change to line 75 makes it obvious that the two if checks are in the wrong order. Please swap them so you don't need to change the `== '*'` and see if stuff breaks.

That was really confusing me.  For my purposes it appears to work.  My fear though is that someone might have been counting on the way it was (deck & cardType being inheritable).

**Comment by ArnoldSmith86** [comment]
I'm 90% sure that all of the listed properties are listed because they will not work in `inheritFrom`. So allowing them in `*` doesn't make sense.

The reason is that they are used before `inheritFrom` can do anything. A card won't be added to the room at all without a `deck` property for example (90% sure).

**Comment by bjalder26** [comment]
> I'm 90% sure that all of the listed properties are listed because they will not work in `inheritFrom`. So allowing them in `*` doesn't make sense.
> 
> The reason is that they are used before `inheritFrom` can do anything. A card won't be added to the room at all without a `deck` property for example (90% sure).

Are there some things I should test, or is THIS just how things should be regardless?

**Comment by ArnoldSmith86** [comment]
I'm pretty sure this is the correct way. We should still do some tests.

**Comment by bjalder26** [comment]
> I'm pretty sure this is the correct way. We should still do some tests.

Well... now none of those thing are being inherited, but the bad news (which I'm sure you already knew) is they are being inherited on the production server (if everything is being inherited).  I cannot imagine someone trying to inherit cardType or deck, but type has me a little worried.  Do we need a fileupdater for basic widgets with that are inheriting everything from another type widget? 

image

**Comment by ArnoldSmith86** [comment]
`GET` will return an inherited type but the widget won't _be_ that type.

The `type` is only used when creating an instance of the appropriate class. There are special cases when editing the JSON that create a completely new instance of another class when changing _type_ but that process will not be triggered if the inherited type changes.

I didn't exclude those properties because I don't _want_ them to work. I excluded them because it would be significant work to _make_ them work.

It could still "break" games to change this but I don't think we should care. As long as the stuff that should work, still does.

**Comment by bjalder26** [comment]
> `GET` will return an inherited type but the widget won't _be_ that type.
> 
> The `type` is only used when creating an instance of the appropriate class. There are special cases when editing the JSON that create a completely new instance of another class when changing _type_ but that process will not be triggered if the inherited type changes.
> 
> I didn't exclude those properties because I don't _want_ them to work. I excluded them because it would be significant work to _make_ them work.
> 
> It could still "break" games to change this but I don't think we should care. As long as the stuff that should work, still does.

Oh, then that's good news.

**Review by ArnoldSmith86 — APPROVED** [review]
The code looks fine to me. I did _not_ test it at all and like I mentioned: somebody should. Just to make sure this doesn't break `inheritFrom` completely.

**Comment by rogerl50** [comment]
> The code looks fine to me. I did _not_ test it at all and like I mentioned: somebody should. Just to make sure this doesn't break `inheritFrom` completely.

I did some (not extensive) testing with a public game room of mine that uses `inheritFrom` and it worked fine.

**Review by rogerl50 — APPROVED** [review]

**Comment by ArnoldSmith86** [comment]
Sounds good to me.

**Pull request merged**
