### PR TITLE
SELECT now resolves piles

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
After each `SELECT` operation every pile in the resulting collection will be replaced by all its children.

This will probably break a few rooms out there but I'm pretty sure everyone affected will love the change.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3087/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Please test a few tutorials and games with this change. It should only break counting cards in a holder but depending on the implementation even that should be fine.

**Comment by rogerl50** [comment]
It doesn't appear to break pot counting in my poker room, and when I have a couple of minutes I'll try to replace the SELECT code with new SELECTS to test out this feature.

**Review by rogerl50 — APPROVED** [review]
Big fan. First, this works properly in my poker room without any code changes. Second, when I make the changes in the code that this fix enables, it solves a previously difficult issue, and reduces the amount of code needed by a factor of about three.

**Comment by 96LawDawg** [comment]
I agree with Roger.  With the revised code, I have also fixed the 'blue card' issue UltimateGeek pointed out in my skip deal to holders tutorial.  See button 3 at http://212.47.248.129:3087/LawDawg.  Works now, no matter if there is a pile or where in the pile the blue card is.  That is what I always wanted to happen.

**Review by UltimateGeek — APPROVED** [review]

**Pull request merged**
