### PR TITLE
css @rule selectors

### PR DESCRIPTION
**Pull request by robartsd**
Provides basic support for widget stylesheets to css `@`rules. Intended use is `@font-face` and `@keyframes`. Multiple `@font-face` rules can be added to a widget if they differ in trailing whitespace. Should work with other `@`rules that typically take blocks (though I can't think of any that would be useful currently - `@property` might be nice when supported in Firefox and Safari).

Support for nested css blocks added.

### CODE REVIEW

**Comment by 96LawDawg** [comment]
Tried two ways of making this work in the test room.  No joy.  Look at the 2 haikus on the right.  Need help with the syntax.

**Comment by ArnoldSmith86** [comment]
I think I fixed the top right one.

**Comment by robartsd** [comment]
`format(woff2)`  was incorrect. `format('woff2')` fixed the Haiku factory widget.

**Comment by 96LawDawg** [comment]
@font-face and @keyframes seem to work as they should.

**Review by 96LawDawg — APPROVED** [review]
I sort of feel like this is music on MySpace.  Flashy but ultimately too distracting.  But that is for each game designer to figure out on their own.  Approved through testing.

**Comment by robartsd** [comment]
> I sort of feel like this is music on MySpace. Flashy but ultimately too distracting. But that is for each game designer to figure out on their own. Approved through testing.

Lots of different fonts and gratuitous animations like we put into the test room certainly can be too distracting. Well chosen fonts and animations can be great enhancements when used sparingly.

**Comment by 96LawDawg** [comment]
Proposed wiki changes to the font page. This basically will replace the first section and add a new last section to what is currently there.  Note, I do not intend to address @keyframes at all.  We don't have a separate css wiki entry and I am not qualified to write one.  We should just document that it is possible in the widget attributes page somewhere and then maybe have a tutorial.  Or someone with competent knowledge can write a new wiki entry covering multiple css topics.

------------

There are several different fonts supported directly in VTT. The default font is Roboto. Each widget may only use one font of this type. Several fonts are included for display of regular alphabetic characters.  All of the following are from the Google family of fonts, except for Handwriting.

* [Roboto](#roboto)
* [Handwriting](#handwriting)
* [Condensed](#condensed)
* [Serif](#serif)
* [Fantasy](#fantasy)
* [Gothic](#gothic)
* [Horror](#horror)
* [Tech](#tech)

This second group of fonts are symbols designed specifically for use in VTT as well as the Google Material Icon font set.  It is not possible to combine regular text with a VTT-Symbol or Material Icon.

* [VTT-Symbols](#vtt-symbols)
* [Material Icon](#material-icon)

The third group of fonts are web-based fonts implemented through a css style-sheet using `@font-face`.

* [@font-face](#@font-face)

If a user declares an unlisted font, for example Arial, in the css of a widget, that font will display for a user if it is available for use in that user's browser. The only way to be sure to provide a consistent experience across a multitude of devices is to use one of the fonts listed above. Even then, room designers should keep in mind that smaller displays such as tablets and phones may have a different appearance depending on how the css on a widget is structured.

----------

## @font-face

Google has over 1,000 fonts available under a free-to-use license.  Other fonts are also widely available.  To use those, you only need to use the following css techniques as well either have access to the font file or know the URL address where the font is available.  For public library games, all fonts must be incorporated as assets on the server and external URL links are not allowed.

To put a font in your room, use the following css syntax:

```JS
"css": {
    "default": {
      "font-family": "hurricane"   
    },
    "@font-face": {
      "font-family": "hurricane",
      "src": "url(https://fonts.gstatic.com/s/hurricane/v3/pe0sMIuULZxTolZ5YldCBfe_.woff2) format('woff2')"
    }
  },
```
Alternatively, you can use `"src": "url(/assets/-2087183141_373892)"`. To get the 'asset' URL, upload the font file using the "Upload Token" link from the Add Widget menu or upload it as an `image` to any widget type that supports images.  That will upload the file and give you the link.

To find and use a Google font, go to https://fonts.google.com.  Browse for the font you want and click on it.  When looking at the various styles offered, you can download the entire font family by clicking the "Download family" button at the top right of the page.  That is a compressed version of the file you would upload as described in the previous paragraph.  Or to just use the web-based version of the font, press the "+ Select this style button".  Then click on the button in the far0right upper portion of your screen that is 3 squares and a plus sign. Once that side window opens, copy the link the appears after the following: <link href=.  Copy the complete URL that appears between the quotation marks (it will likely start with "http:.//fonts" and end with "swap".  For example, if you were looking for the hurricane font, you would find and copy "https://fonts.googleapis.com/css2?family=Hurricane&display=swap".  Paste that link into a new browser window.  Then look around to find the appropriate "src" link to use in VTT.  Note, you will probably need to use the "latin" variation and not "latin-ext".

**Comment by robartsd** [comment]
> Code looks fine to me. I only moved `document.createElement('style')` down so it isn't used in nested calls.
> 
> It probably doesn't even make a difference in modern browsers but it just didn't feel right. 😄

Definitely better. It also fixes an issue that I encountered when hacking the widget stylesheet in chromium dev tools - the editied text node became the only text node; now there is only the one text node containing all the rules.

**Pull request merged**
