### PR TITLE
Public Library - Add Runway Roll

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
I have been working on this on and off for weeks now. This is the first time where the base game should be complete. The How To Play section took quite some time.

I will probably still improve it because I am actively playing this daily. It is awesome.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2227/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
I've said it before and I'll say it again.  I love it when you are full into making a game because you find and fix major and minor annoyances as well as add new features.  Thanks!

**Comment by ArnoldSmith86** [comment]
> I've said it before and I'll say it again. I love it when you are full into making a game because you find and fix major and minor annoyances as well as add new features. Thanks!

The only feature was #2215 though, right? I didn't need that. :grinning: And maybe #2223 if that's considered a feature..

**Comment by 96LawDawg** [comment]
Yes.  INPUT.choose.

I just spent 10 minutes playing around with it.  This looks awesome and fun.  The only critique is that when in an advanced scenario, it took me a while to figure out how to close the box holding the scenarios.  Maybe something in the instructions or in the room to make it more clear that the icons at the top of the screen are actually buttons.  Maybe a hover effect?

**Review by 96LawDawg — APPROVED** [review]
Approved.

**Comment by ArnoldSmith86** [comment]
> Maybe something in the instructions or in the room to make it more clear that the icons at the top of the screen are actually buttons. Maybe a hover effect?

Will do. But I'll merge it for now.

**Pull request merged**
