### PR TITLE
Major Tutorial Reorganization (plus add COMPUTE and SORT)

### PR DESCRIPTION
**Pull request by 96LawDawg**
(This is a second attempt.  I will delete PR#78 that deals with the same thing).

Created consistency in the library image. Unlike games, creative images don’t help. I think just seeing the names is best.

Created consistency at the top of most tutorial variants with the name of the tutorial and the variant in large letters.

Eliminated copyright notices. Tutorials use generic assets. Have updated the README.md file to indicate CC0 for all tutorials and to link to the new https://virtualtabletop.io/Tutorials room.

Reorganized some of the existing tutorial structure. Buttons as a category really doesn’t make sense. Broke all of those out into Functions – xyz tutorials. Combined some other tutorials that were spread out into the Holders one.

File naming structure is mostly intact. Only a couple of wiki entries directly reference the existing files and those should work. This new structure should make wiki linkage easier. But I have deleted all tutorial files and added them back with this PR.

New content includes a basic tutorial on Hands before the more advanced tutorial on custom visibility. First version of COMPUTE tutorial is on here. First version of SORT tutorial is as well. Other tutorials which have been on hold in the #tutorials channel have mostly been added as well. A few are still missing and I will get to those soon (text bearer and sorting spinners by value).

Future needs: additional Skip examples. COMPUTE string and array examples. Other functions that could use a little attention: COUNT and SET). UltimateGeek has a draft tutorial for MOVE and MOVEXY that should be publishable after the PR dealing with those changes is committed.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3080/pr-test (or any other room on that server)

**Comment by UltimateGeek** [comment]
COMPUTE tutorials:
1. Missing string & array operations. Is this intentional?
2. A clarification could be made that static constant names (e.g. LN2) need to be placed in the Operation input box (not Operand1 or 2)

**Comment by UltimateGeek** [comment]
SORT sequential

1. I don't understand what is meant by "Using the setup on the left"
2. I don't understand what is meant by "other keys"

image

**Comment by UltimateGeek** [comment]
Skip: Occupied Holders

Unable to click to close the pop-up explanation box due to #20.

image

**Comment by UltimateGeek** [comment]
Skip: Occupied Holders:

The third button "Skip Selected Card" does not work as advertised in this scenario:
1. Deal two or more cards to piles
2. Move a pile off the holder.
3. Put a blue card into the holder
4. Move the pile back onto the holder over the blue card.

At this point, when you click "Skip Selected Card", it still deals to the pile even though the blue card was on the button.

**Comment by 96LawDawg** [comment]
> COMPUTE tutorials:
> 
> 1. Missing string & array operations. Is this intentional?
> 2. A clarification could be made that static constant names (e.g. LN2) need to be placed in the Operation input box (not Operand1 or 2)

1) This is intentional due to tutorial fatigue.  My doctor said it is incurable.  I (or someone??) will provide tutorials for strings and arrays.  I wanted to go ahead and get what we have out there.
2) Agree.  Change made and will update the files once other comments received.

**Comment by 96LawDawg** [comment]
Fixed blocked pop-up box on Skip tutorial.  Will investigate the blue card issue.

**Comment by 96LawDawg** [comment]
The blue card issue is a result of piles.  If there is more than one card in the holder (even 2 blue) a pile is created and that busts the code.  Rather than write lengthy pile checking code, I have further clarified in the tutorial that the blue card works if it is the only card in the holder.  Revised version to be uploaded after any other comments.

**Comment by 96LawDawg** [comment]
Regarding the confusion about SORT sequential (variant 3), I have changed the wording to: "Using the various different buttons (which reflect default keys) on the left, try to recreate the cardType and rankFixed sorting using two other sort keys."

**Comment by 96LawDawg** [comment]
All changes listed above have been incorporated into the pr-test server.  I'm not really sure of the workflow but I know I need to update the files in the PR.  But I'm also not really sure how to do that on git without breaking stuff.

**Review by UltimateGeek — APPROVED** [review]
I’ll need to merge these changes into my library tutorial updates PR

**Review by ArnoldSmith86 — APPROVED** [review]
The readme has a `the the` somewhere. That can be fixed whenever.

**Pull request merged**
