### PR TITLE
place value compression of repeating color values

### PR DESCRIPTION
**Pull request by robartsd**
This uses `#$%&'()` to encode the repeat length for most colors. The color character is encoded first, then the code for how many times it is repeated if the color occurs for at least 3 pixels in a row (a color occurring only twice in a row the color code simply gets repeated). The characters `*+,-./0` encode the repeat length of the color `0`; but `0` is not always in the encoding. To make `0` mean one `0` the values of the characters used are 1-7 with the highest code point representing the lowest value (no zero is needed, 14 is encoded as 7 ones + 1 seven, 56 is 7 ones + 7 sevens). For the maximum supported canvas size (500x500 - 2500 pixels per region) the maximum possible length of a repeat encoding is 4 characters (7 + 7 x 7 + 7 x 7^2 + 7 x 7^3 = 2800). For a 200x200 canvas (400 pixels per region) 3 character repeat codes are always sufficient (7 + 7 x 7 + 7 x 7^2 = 399).

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3499/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
Lots of escaped `"` characters in the JSON. I think I'll reduce the character set used.

**Comment by ArnoldSmith86** [comment]
That's a nice idea. If we also use this for the background color, I'm pretty sure my simpler version would be shorter most of the time though.

Maybe support 8-16 colors directly and use the same base16 idea for further (unlimited) colors?

And then use some bytes for short repetitions of 0 (and maybe 1 and 2) and use base16 for all other repetitions?


At some point it's probably easier to use existing compression schemes but this is kinda fun. 😄

**Comment by robartsd** [comment]
I think I'm starting to agree that special treatment of background color might be worthwhile.

**Comment by robartsd** [comment]
I think this may be ready now.

**Comment by robartsd** [comment]
This uses `#$%&'()` to encode the repeat length for most colors. The color character is encoded first, then the code for how many times it is repeated if the color occurs for at least 3 pixels in a row. The characters `*+,-./0` encode the repeat length of the color `0`; but the `0` character is not always in the encoding. To make `0` mean one `0` the values of the characters used are 1-7 with the highest code point representing the lowest value (no zero is needed, 14 is encoded as 7 ones + 1 seven, 56 is 7 ones + 7 sevens). For the maximum supported canvas size (500x500 - 2500 pixels per region) the maximum possible length of a repeat encoding is 4 characters (7+7*7+7*7*7+7*7*7*7 = 2800). For a 200x200 canvas (400 pixels per region) 3 character repeat codes are always sufficient (7+7*7+7*7*7= 399).

**Comment by ArnoldSmith86** [comment]
Now I actually want to build an exporter and importer so we can compare which method produces shorter results for actual images.

**Comment by robartsd** [comment]
> Now I actually want to build an exporter and importer so we can compare which method produces shorter results for actual images.

I believe that by using place value, on average my scheme will be smaller. There will always be some special cases where your scheme happens to be optimal, but I doubt they would prevail in actual images.

**Review by ArnoldSmith86 — APPROVED** [review]
I didn't take the time to understand the entire code but it seems to be fine.

**Pull request merged**
