### PR TITLE
fixed phantom widgets after removal

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
There are multiple situations where widgets were not completely removed when they should have been. This PR aims to fix those instances.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3559/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Please test if you can still reproduce the problem.

**Comment by bjalder26** [comment]
This likely relates to issues #477, #380, & #554 and the issues discovered testing PR #521.

**Comment by bjalder26** [comment]
I uploaded a room I was using to create these errors, and cards with deleted decks no longer remain until a refresh.  I had a timer repeat this action over and over for like 1/2 an hour, and the length of the JSON in the room didn't change.  Deleted widgets that have a parent do not 'reappear' anymore when another widget is renamed to their parent's name.

What is still remaining is that pile counts for widgets deleted before being removed from their parent do not update.  The workaround is to set their parent to null before deleting them.

**Review by bjalder26 — APPROVED** [review]
This seems like a definite improvement on a known bug.

**Comment by ArnoldSmith86** [comment]
> What is still remaining is that pile counts for widgets deleted before being removed from their parent do not update. The workaround is to set their parent to null before deleting them.

Please provide a way to reproduce.

**Comment by robartsd** [comment]
> > What is still remaining is that pile counts for widgets deleted before being removed from their parent do not update. The workaround is to set their parent to null before deleting them.
> 
> Please provide a way to reproduce.

Using my original modification to Reward, add cards from multiple colors to the reinforcements holder then recall one of the colors.

**Comment by bjalder26** [comment]
> > What is still remaining is that pile counts for widgets deleted before being removed from their parent do not update. The workaround is to set their parent to null before deleting them.
> 
> Please provide a way to reproduce.

Reward (clone wars) is on the test server right now.  If you make a pile of two different colors then recall one of the colors using the buttons in the lower right, then the pile number won't update even though some of the cards have been deleted.  Below was the 'workaround' I put in before deletion that got rid of the problem in another copy of the game..

{
      "func": "SELECT",
      "property": "label",
      "value": "Red"
    },
    {
      "func": "SET",
      "property": "parent",
      "value": null
    },

**Comment by ArnoldSmith86** [comment]
Please check if this fixes the issue with pile counts but please also check other ways to remove widgets.

**Review by bjalder26 — APPROVED** [review]
Rechecked issue involving pile counts, and that has been resolved.  Also tried deleting directly using a button press, and deleting using both editors.  No pile count issues.  Retested other tests I did, and found no problems there and tested for the issue of 'returning widget' after a parent is deleted, then another widget is created with the same ID as the parent.  Children of deleted widget do not return even if parent is deleted through the editors.

Approve based on testing.

**Pull request merged**
