### PR TITLE
Add Piles tutorial, fix minor game errors

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:
- Imagination. Fixed simultaneous button clicks and missing preview picture. Added results screen after voting.
- Diced. Fixed seats and inheritFrom problem.
- Undercover. Fixed wrong border on extra cards and spy master no longer has to decide when a word is final because other players can click on words to cover them.

Public Tutorials: 
- Piles. New tutorial to explain pile handle customization. 3 variants: Basic, Advanced, and Decoration.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3957/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Changed files loaded from library.json.

**Comment by 96LawDawg** [comment]
Can I get a review on this?  I'm going to be pushing a bunch of new tutorials soon and I would like to get this one out of the way.

**Review by RaphaelAlvez — APPROVED** [review]
Looks good

**Pull request merged**
