### PR TITLE
added `regex` to `INPUT.string`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Now you can define a regular expression to match an `INPUT` string against and use `regexHint` to tell the player about it if the input does not match it.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1882/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1882-pr-test`.

**Comment by 96LawDawg** [comment]
Will add this to the wiki entry for INPUT under string:

* `string`: _displays a text input field_ - stores a string. Optionally may add a Javascript regular expression
    * `regex`: _regex_ - will limit the user to the characters in the regular expression. For example, `^[0-9]$` forces an entry consisting only of numbers.
     * `regexHint`: _text_ - this is the prompt that players see if the response does not meet the regex criteria

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  Updated tutorial and drafted wiki entry.

**Comment by ArnoldSmith86** [comment]
This was very easy to add after #1871. Any other ideas what INPUT could check when confirming the overlay?

**Pull request merged**
