### PR TITLE
increment more properties when duplicating widgets

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The current JSON editor duplication command is really amazing and saves a ton of work. But I always have _some_ stuff that I need to post-process manually. A custom `player` property, the references in `inheritFrom` or `dropTarget` (and the new `linkedToSeat` and `onlyVisibleForSeat`). The `text` `"Player 1"`. Or now the `index` of the seat.

This PR adds a new option to the duplication command: `Increment In`. It is a comma separated list of property names. For now it just does `JSON.parse(JSON.stringify(widget[property]).replaceAll(sourceNumber, targetNumber))`.

I am pretty sure this is already all I need but please tell me where this does not fit your use-cases.

Also keep in mind that `id` and `parent` are not needed. They work just like they did before.

I also added another option called `Increment Letters`. For my player areas I want to keep all IDs in a form that can be recursively duplicated. So if there are 2 identical game pieces I call them `Player 1 - Piece A` and `Player 1 - Piece B` so that duplicating them turns into `Player 2 - Piece A` and `Player 2 - Piece B` instead of `Player 1 - Piece 3` if they used numbers.

With the new option I can now also use automatic duplication to create 15 game pieces A-O that in turn can be duplicated for each player.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
For me this change is pretty huge BTW. I recommend taking a look and approving. 😄

**Comment by 96LawDawg** [comment]
What should it do when it runs out of letters?  I tested a widget with ID widgetA and text property "A."  I incremented letters in small batches and it worked fine, meaning that it picked up where it left off as it should.  After Z, the ID went to A1, A2, etc.  The text property stayed at A.  I don't know what it should do, but leaving the text at A is probably not the right answer.  It should probably go to A1.

At first, I was curious about your choice for default for `increment in` (dropTarget,hand,index,inheritFrom,linkedToSeat,onlyVisibleForSeat,text).  But after looking at all the available properties, I think that makes sense.  It isn't the easy box to use or see, especially in the new narrow view, but it is functional.  I don't know that I have a better solution.  Maybe wraparound onto a 2nd line so you can see it all at once?  A list of properties with checkboxes prechecked and an "other" place to type in your own?

It does not work consistently with custom properties.  If the property has just a letter `"foo":"A"` it is fine.  If there is a number in the custom property, it does not increment it.

When working with letters, I got some unexpected results.  For example, testing `"foo":"A"` by using `increment letters` also caused letters to be added to the id.  So the id became "seat1A" instead of 2.  But of course, that works fine if I don't select `increment letters`.

**Comment by ArnoldSmith86** [comment]
For initial clarification: the incrementing is always based on the `id` of the widget. So if the `id` is `"Foo 1"` and you increment numbers (not letters), it will turn the `"1"` into the next free number (let's say `"4"`). It will _then_ replace `"1"` by `"4"` in all the given properties. Nothing else.

If you incremented letters instead, it would turn `"Foo 1"` into `"Goo 1"` (only the last capital letter is incremented) and replace `"F"` by `"G"` in the additional properties.

`parent` is a special case. It gets set to whatever the copy of the old parent becomes.

Do you have actual use cases where you would want to increment something unrelated to the `id` in the other properties?

**Comment by ArnoldSmith86** [comment]
>  After Z, the ID went to A1, A2, etc.

That sounds like you didn't activate `increment letters`:

image

There's currently no logic for when you run out of letters. It just ascends the ASCII chart which is probably problematic at some point.


While I agree the behavior isn't exactly perfect yet, in general I don't know if it's worth the effort to make this foolproof before someone actually runs into problems. And in the meantime this makes duplicating complicated widget setups way easier...

**Comment by 96LawDawg** [comment]
> That sounds like you didn't activate `increment letters`:

You are right.  I did forget.  But I tested again.  Widget id of colA, colB, etc.  After Z it went col[ and then stopped.  I asked for 60 copies and got 26 or so.  But you are also right that we shouldn't worry too much about this because I shouldn't expect a computer to alphabetize something after Z.

> Do you have actual use cases where you would want to increment something unrelated to the id in the other properties?

Yes.  No.  Maybe.  I know I've used custom properties before, but that was probably before I could auto-increment ids.  The only thing that I can think of is I might want something like token1, token2, token3 as an id.  But I might create a custom property tokenNum: 1, tokenNum: 2, etc.  That way I could do math without having to get a substring.  But I guess that isn't required.  Just need to document in the new wiki @rogerl50 is working on the boundaries of this new capability.

**Comment by ArnoldSmith86** [comment]
> I might want something like token1, token2, token3 as an id. But I might create a custom property tokenNum: 1, tokenNum: 2, etc.

That should work with the current version just fine. Just add `tokenNum` to the `Increment In` option.

> I shouldn't expect a computer to alphabetize something after Z.

I mean, the expectation would be Excel-style: after Z comes AA. But that's significantly more work, I think.

**Comment by 96LawDawg** [comment]
> That should work with the current version just fine. Just add `tokenNum` to the `Increment In` option.

It does.  I kept trying to get that to work with `increment letters`.  Somehow I thought it would do both and I was expecting too much.

**Review by 96LawDawg — APPROVED** [review]
Approved through testing.  Recommend adding to the draft wiki on JSON editor capabilities.

**Comment by rogerl50** [comment]
In http://212.47.248.129:3837/poker, I got the following JS error when trying to duplicate one of the widgets.

Screen Shot 2021-11-07 at 10 50 25 AM

**Comment by 96LawDawg** [comment]
> In http://212.47.248.129:3837/poker, I got the following JS error when trying to duplicate one of the widgets.

I wonder if that was because you specified `parent` and `id`.  As Arnold says above, they are 'special' and you don't have to specify them, so I didn't test that.  That might be the problem and if it is, a code change to catch that would be nice.

**Comment by rogerl50** [comment]
> > In http://212.47.248.129:3837/poker, I got the following JS error when trying to duplicate one of the widgets.
> 
> I wonder if that was because you specified `parent` and `id`. As Arnold says above, they are 'special' and you don't have to specify them, so I didn't test that. That might be the problem and if it is, a code change to catch that would be nice.

If I don't specify either (leave that field empty, for example), the widget gets duplicated, but the id of the parent is not updated. I get a widget named "P7 Stack", as expected, with parent "holderP3" rather than "holderP7". Even if I create a holder named "holderP7", the parent doesn't get updated.

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
We need to figure out what is going on with @rogerl50's parent issue before continuing.

**Comment by bjalder26** [comment]
> If I don't specify either (leave that field empty, for example), the widget gets duplicated, but the id of the parent is not updated. I get a widget named "P7 Stack", as expected, with parent "holderP3" rather than "holderP7". Even if I create a holder named "holderP7", the parent doesn't get updated.

My understanding is that this PR doesn't increment the parent UNLESS it is the parent you are duplicating.  In that case when it duplicates the children, it increments the parent's ID and updates the parent's ID in all the children.  I do not know what is causing the JS errors though.

**Comment by ArnoldSmith86** [comment]
What @bjalder26 says. But @rogerl50's use case is something I would want as well. I'll see how easy it is to make that work.

**Comment by ArnoldSmith86** [comment]
Yeah, this wasn't supposed to be the final solution. I just ran out of time.

**Comment by rogerl50** [comment]
This is almost ready to go, I think; all that's needed is a better resolution of the error above. It would be really useful in game development.

**Comment by 96LawDawg** [comment]
I know this didn't make the recent list of PRs that we should take a look at, but this would be SO VERY useful.  I keep forgetting to come here and work on a game in this room, but I have tested it and if we can resolve @rogerl50's concern, then I think this could be merged.

**Comment by ArnoldSmith86** [comment]
Yeah. Are you aware that you can use the `Editor` beta server through the "about" overlay? With that you can use this feature pretty seamlessly from a production room.

**Comment by 96LawDawg** [comment]
I haven't really messed with the beta servers at all.  But that is a great idea, at least for game development.  Thanks.

**Comment by ArnoldSmith86** [comment]
Not perfect but now there's feedback if it's not possible to add generated widgets.

**Comment by rogerl50** [comment]
This is ready for re-review. The error message thing was already fixed by @ArnoldSmith86. The latest commit does two things:
1. Integrates the 'Increment IDs' and 'Increment Letters' into a single dropdown.
2. Fixes a bug in the R.E. for letter incrementing whereby e.g. '8AXY' was duplicated to '8B'. Now letter incrementing acts on the last capital letter in the ID, or if there are none, appends an 'A'.

**Review by rogerl50 — APPROVED** [review]

**Comment by 96LawDawg** [comment]
I can't get letter incrementing to work at all.  I've got `"text":"A"` set on a widget.  I selected "Letters" in the dropdown.  Nothing.

**Comment by ArnoldSmith86** [comment]
It will only increment an `A` in `text` if it also incremented an `A` in `id`. Did it do that?

**Comment by 96LawDawg** [comment]
> It will only increment an `A` in `text` if it also incremented an `A` in `id`. Did it do that?

Yes.  But I guess that I didn't fully understand this then.  I thought I could increment "fooBar":1 no matter the id.  But "fooBar":1 only increments if the widget id has a 1 (and only a 1 - not 11, 21, etc) in it.  And for letters, it as you said but in that case it looks for the last capital.

So you can't independently increment properties without considering the id?

**Comment by 96LawDawg** [comment]
> > Do you have actual use cases where you would want to increment something unrelated to the id in the other properties?
> 
> Yes. No. Maybe. I know I've used custom properties before, but that was probably before I could auto-increment ids. The only thing that I can think of is I might want something like token1, token2, token3 as an id. But I might create a custom property tokenNum: 1, tokenNum: 2, etc. That way I could do math without having to get a substring. But I guess that isn't required. Just need to document in the new wiki @rogerl50 is working on the boundaries of this new capability.

I guess I could have read the thread. I get it now.

**Comment by ArnoldSmith86** [comment]
> So you can't independently increment properties without considering the id?

At least not the way it is now. The idea was for a `id=Player 1 - Seat` widget to increment `index=1` as well.

But maybe it wouldn't cause problems (and cause less confusion) if we also increment `index=2` in there.

**Review by 96LawDawg — APPROVED** [review]
Approved through testing

**Review by RaphaelAlvez — APPROVED** [review]
I did not test MOST of this PR but it does fix a weird behavior I found today.

duplicating a widget with ID "960x" was incrementing in 10s (970x, 980x, 990x...)

**Pull request merged**
