### PR TITLE
improved timer behavior

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Timers react a lot better to changes done by other players or through the JSON editor.

I also added that the first player to enter a room automatically starts all the timers that are not paused.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3540/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
> I also added that the first player to enter a room automatically starts all the timers that are not paused.

I don't understand.  If the timers are not paused, then aren't they already running?  I'm concerned about how this behavior might impact some things where I have changeRoutines tied to a timer that shouldn't be running all the time and certainly not upon entering a room.

**Comment by ArnoldSmith86** [comment]
The player who causes a timer to run (by pressing a button for example) starts a browser feature that makes the timer _tick_.

As soon as that player leaves the room (for example closes the browser), the timer will immediately stop running because their browser "kept it alive".

That part is still true. I would like to improve that sooner or later but I don't think it's a big problem in practice where players usually leave when they're done playing.


But now after everyone left the room and then one player comes back, the browser of that first player looks at the room state and for every timer that is `paused: false`, it starts that background process to effectively start the timer again.

In practice this basically means: **if you are in a room alone and you `F5` while a timer is running, it will continue to run after the reload**.

This does not mean that actually paused timers (so `paused: true`) will suddenly start to run.

**Comment by robartsd** [comment]
What happens if the player currently running a timer leaves the room while other players remain active?

> I don't understand. If the timers are not paused, then aren't they already running?

The timers only run if there is a player in the room to run them. This effectively pauses a running timer on disconnect then resumes it as soon as a player reconnects. A carefully crafted saved state could even have a timer that starts from zero as soon as the timer widget loads.

> I'm concerned about how this behavior might impact some things where I have changeRoutines tied to a timer that shouldn't be running all the time and certainly not upon entering a room.

What should happen if all players disconnect while timers are running then someone reconnects?

**Comment by bjalder26** [comment]
> > I also added that the first player to enter a room automatically starts all the timers that are not paused.
> 
> I don't understand. If the timers are not paused, then aren't they already running? I'm concerned about how this behavior might impact some things where I have changeRoutines tied to a timer that shouldn't be running all the time and certainly not upon entering a room.

As I understand it the timer 'runs' on the client and so if nobody is in the room, then the timer stops.  So this would make it so an unpaused timer would start when someone enters the room.  From a game standpoint, this would allow people to get the automatic shuffles they've wanted.

**Comment by robartsd** [comment]
> ```js
> if(delta.paused === false && activePlayers.length == 1)
>   this.startTimer();
> ```
> 
> I guess it could be changed to "if I'm `activePlayers[0]`" though. Hmm. Maybe it should always be run by `activePlayers[0]` and when they leave, the new `activePlayers[0]` takes over.

Yes, I think having `activePlayers[0]` run timers that are not paused that no other player is already running might be a good solution. I do think that timers should usually continue to be run by the player that starts them.

**Comment by ArnoldSmith86** [comment]
> that no other player is already running

That's not that easy to determine. I was thinking just always let `activePlayers[0]` run the timer. The only problem is that multiple clients might be `activePlayers[0]` if they have the same `playerName` (I think).

**Comment by robartsd** [comment]
> > that no other player is already running
> 
> That's not that easy to determine. I was thinking just always let `activePlayers[0]` run the timer. The only problem is that multiple clients might be `activePlayers[0]` if they have the same `playerName` (I think).

Yeah, I was thinking about that too. Really should be first active connection.

**Comment by ArnoldSmith86** [comment]
Yeah, but the clients don't know that. Maybe we should change that. The server could just tell one player that they are responsible for timers.

**Comment by robartsd** [comment]
> Yeah, but the clients don't know that. Maybe we should change that. The server could just tell one player that they are responsible for timers.

I wasn't sure what all the server included in the _meta object. I thought there was somewhere where we were having players repeated if they had multiple simultaneous connections.

**Comment by ArnoldSmith86** [comment]
You're right. It's the client that removes duplicates. But still, if all players have more than one connection there would be no candidate. I think it's cleaner if the server just picks a "master" player.

**Comment by robartsd** [comment]
What if all clients run the timer locally and somehow flag the deltas the timer creates so that the server knows that they are duplicates when it receives them from multiple clients?

**Comment by ArnoldSmith86** [comment]
The deltas can contain anything because of `changeRoutine` and the ticks will not be synchronized and will be based on different room states.

**Comment by robartsd** [comment]
> The deltas can contain anything because of `changeRoutine` and the ticks will not be synchronized and will be based on different room states.

If each tick happened based on the same state, then they should result in the same state. Of course that assumes on routine makes use of some variant of random.

I just think the latency of starting a timer from a client that is not the delegate to run the timer could be a problem, so timers should be run by the client that starts them and only fall back to a designated delegate if that client gets disconnected. I think the longest continuously connected client is the most reasonable choice to designate to run timers that are somehow abandoned while running.

**Comment by ArnoldSmith86** [comment]
> I just think the latency of starting a timer from a client that is not the delegate to run the timer could be a problem, so timers should be run by the client that starts them and only fall back to a designated delegate if that client gets disconnected.

Hmm, true.

**Comment by ArnoldSmith86** [comment]
I don't plan to further improve the timer handling with this PR unless problems arise. Especially that timers stop when the player, who started it, leaves.

We should improve that eventually but I'm pretty sure that it won't be straightforward and I think it's more of a theoretical problem. In general players don't leave mid-game. And if they do, any timers will have to be reset anyway because the game was disrupted.

**Comment by 96LawDawg** [comment]
> I don't plan to further improve the timer handling with this PR unless problems arise. Especially that timers stop when the player, who started it, leaves.
> 
> We should improve that eventually but I'm pretty sure that it won't be straightforward and I think it's more of a theoretical problem. In general players don't leave mid-game. And if they do, any timers will have to be reset anyway because the game was disrupted.

Since this is as far as this one goes, I'm going to approve it.  But the other problem is more than theoretical, at least for me.  If a timer is running (that I started), and I have an internet glitch, then the timer stops for everybody.  I mean, it is easy enough to restart, but noticing that it stopped and making the effort to restart may be significant.  So I do hope that gets addressed someday.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  It works as described and does not negatively impact the few actual implementations of timer that exist and I tested.

**Comment by ArnoldSmith86** [comment]
> I have an internet glitch, then the timer stops for everybody

That's a valid point. Unless this PR causes problems, I'd like to tackle this separately though.

Thanks for testing!

**Pull request merged**
