### PR TITLE
Pile customization

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
Add css variables that should allow a very wide customization to the handle. 

### Update (not a draft anymore)

- added pileCSS that can be added to holder and cards
- pileCSS is only passed to the pile's "css" property on creation. it doesn't matter if you change it in the holder. if you want to do that, use automation. you can select a pile and set the css using routines
- the priority is set as such:
    - CSS from the previous pile taken on splitting a pile
    - pileCSS from the holder
    - pileCSS from the bottom card on creation. it does not update when you drop a pile into card
- You need to use the css variables stated bellow if you want to edit the handle. normal css would only change the pile itself (transparent stuff that parents the cards)

I'm not sure yet how to pass the CSS to the pile. from my testings it feels weird if the CSS changes way to often

My proposal would be to not update the CSS unless forced.
Something like inheritedCSS that would only be set on creation. CSS would still be available for change using automation.

at the moment you can use those properties in the holder CSS and it will pass to children. 

CSS being used:
  left/right: var(--phX);
  top/botton: var(--phY);
  width (changed by classes small): var(--phWidth);
  height (changed by classes small): var(--phHeight);
  font-size: var(--phFontSize);
  background: var(--phBackground);
  color: var(--phColor);
  border: var(--phBorder);
  border-radius: var(--phBorderRadius);
  display: var(--phDisplay);

here are the defaults:
'--phX: -15px'
'--phY: -15px'
'--phWidth: 40px'
'--phHeight: 40px'
'--phFontSize: 20px'
'--phBackground: #e4e4e4'
'--phColor: #6d6d6d'
'--phBorder: none'
'--phBorderRadius: 50%'
'--phDisplay: flex'

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3852/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
This would be harder and likely require coffee change, but I'd like to be able to select large or small handles.

**Comment by RaphaelAlvez** [comment]
> This would be harder and likely require coffee change, but I'd like to be able to select large or small handles.

I'm creating some examples in the test room and you can change the size if you want

**Comment by rogerl50** [comment]
In this model, the pile handle styling is an attribute of the *holder*, not of the *pile*. For example, moving a pile in the test room from one holder to another changes its styling. I'm not sure if this is the desired behavior or not. It does result in some weird effects; dragging a pile out onto the desktop reverts its styling to the default.

One approach would be to retain the custom styling from a holder until the pile is dropped into another holder, when it acquires the styling (default or not) from the new holder. (Note that you will then have to deal with making the pile handle move around as the pile gets close to the edge of the table.) So in this approach (where you would actually copy the CSS from the holder to the pile), the styling is an attribute of the pile, but need not be set directly (although it could be).

**Comment by RaphaelAlvez** [comment]
> In this model, the pile handle styling is an attribute of the _holder_, not of the _pile_. For example, moving a pile in the test room from one holder to another changes its styling. I'm not sure if this is the desired behavior or not. It does result in some weird effects; dragging a pile out onto the desktop reverts its styling to the default.
> 
> One approach would be to retain the custom styling from a holder until the pile is dropped into another holder, when it acquires the styling (default or not) from the new holder. (Note that you will then have to deal with making the pile handle move around as the pile gets close to the edge of the table.) So in this approach (where you would actually copy the CSS from the holder to the pile), the styling is an attribute of the pile, but need not be set directly (although it could be).

I agree that this is not the ideal set-up and for sure not the final one. I just think that there might be already a lot of value in this initial approach.

I added two holders in the right to show a simple automation that handles this problem. 

Anyways I understand that this is very simple PR so far so I understand if you think this should be worked on but I will not be able to improve this in a near future (1-2 weeks).

**Pull request closed without merging**
