### PR TITLE
Upgrade to buttons customization

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
### This is part of the basic UI upgrade
see PR #457 

- Adds css variables as properties
- Better use of the variables. You can now just set the --wcMain and --wcBorder
- Divided the border property because that was messing up with the variables

There is one thing **I couldn't do.** I want to take the "color" property, find out its HUE, use it to generate the border and main colors in RGB and apply them to the widget

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3461/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
example added to test room

**Comment by 96LawDawg** [comment]
I like this.  It will clean up the css and make it easier to identify what colors are being changed.  However, do you think there is any problem with the inconsistency in the labelling? Your original shortcut words (main and font) now turn into background and text.  I think the newer words are better descriptors.  Should they all be the same?  Of course, making a change like that would be a breaking change and would require a fileupdate.  Just something to think about.

**Comment by RaphaelAlvez** [comment]
> I like this. It will clean up the css and make it easier to identify what colors are being changed. However, do you think there is any problem with the inconsistency in the labelling? Your original shortcut words (main and font) now turn into background and text. I think the newer words are better descriptors. Should they all be the same? Of course, making a change like that would be a breaking change and would require a fileupdate. Just something to think about.

I am not going to make such a change. I do not understand enough about the file updater and there is very little examples.

Also, I used text because that's the name of the property it is related to but in CSS those properties are names font-something (with the exception of color)

**Review by 96LawDawg — APPROVED** [review]
Approved through test and code review.

**Pull request merged**
