### PR TITLE
presets for online IDE Gitpod

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
I want to be able to develop on my Android tablet and a web IDE seems like a good way to do that.

[Gitpod.io](https://gitpod.io) looks like it works just fine and this PR adds a few config files for it so that pretty much everything should just work.

An interesting feature is live collaborative coding. I'm looking forward to testing that with someone.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3227/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
How should this pr be reviewed? Looks like a good idea

**Comment by ArnoldSmith86** [comment]
You can test this PR in Gitpod: https://gitpod.io/#https://github.com/ArnoldSmith86/virtualtabletop/pull/227

But of course the more important thing is that the generated PR test server is still working as expected. It would be very weird if it's broken though.

**Review by RaphaelAlvez — APPROVED** [review]
tested and approved

**Pull request merged**
