### PR TITLE
Basic UI redesign

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
Started adding basic editor UI and this got me into also changing the CSS for the edit overlay.

CSS changes:
- corrected deck editor upload button
- changed general button style
- changed scroll bar to WebKit browsers
- changed style of basic widget editor UI

UI changes:
- started creating individual basic editors for each widget
   - buttons
   - labels
   - timers

to-do:
- [ ]  add widgets' CSS properties as normal properties to easily implement new elements to the basic UI
    - [ ]  label: font size; color
    - [x]  button: all colors variables
- [x]  add UI for basic widgets (enlarge, upload image) and spinners (dropdown for options)
- [x]  I just realized that the general button also affects the advanced JSON editor so I need to fix that
- [ ]  Maybe change the basic JSON editor to

This PR is based in the Timer PR because I wanted to already work on that UI and I have no expectation to finish before the emerging of that one

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3457/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 take a look into the last commit please

**Comment by ArnoldSmith86** [comment]
I added an upload button to the button UI. And I added this `FIXME` for you:

`// FIXME: if widget.text is not set AND widget.image is not set, this doesn't set the correct styles`

Re-add `help needed` if you need more assistance.

**Comment by RaphaelAlvez** [comment]
This PR is feature complete and ready for review.
I made the changes requested in the meeting and the FIXME.
@ArnoldSmith86 I'm requesting help because I don't know what to do to the test cafe. Other than that whenever this is fixed and approved please go ahead and merge this PR for me

**Comment by 96LawDawg** [comment]
Comments:

On the spinner, I'm sure you have a reason for the presets that you do.  Some of them even make sense, but not 0-9.  I don't really care, but is that too many presents or not enough.  I have no idea.

For buttons, you have the option to set debug, but that looks like it is going away soon.  Maybe want to remove that?  People good enough to understand the debug won't need the help.

On the Add widget page, there is no canvas widget (I know this was before the canvas, but that is close to being merged, so probably should include it).

On the game list, we should probably get rid of "save in progress game."  It's never been implemented, so until it is, this seems like a good place to do it.

On the basic widget editor, you can swap between token and board, which seems to only affect the layer.  Seems like if you set the property to board, it should also change the size to 1600x1000 by default.

Visually, I like the way the colors, buttons, scrollbars, etc. look.  We are definitely improving the look of our "brand" overall.

**Comment by RaphaelAlvez** [comment]
> Comments:
Answers

> On the spinner, I'm sure you have a reason for the presets that you do.  Some of them even make sense, but not 0-9.  I don't really care, but is that too many presents or not enough.  I have no idea.

Only reason is compabillity

> For buttons, you have the option to set debug, but that looks like it is going away soon.  Maybe want to remove that?  People good enough to understand the debug won't need the help.

Yeah maybe but I actually want to lobby that we don't remove it because the JSON editor can't be accessed on mobile and I do a lot of debug on my phone

> On the Add widget page, there is no canvas widget (I know this was before the canvas, but that is close to being merged, so probably should include it).

No this PR is compatible. I did actually make a merged version on my local host already. Looks good. 

> On the game list, we should probably get rid of "save in progress game."  It's never been implemented, so until it is, this seems like a good place to do it.

I'm not doing that. This has to stay until it is added 😅. But seriously not sure if this is still planned or not. @ArnoldSmith86 since this is auto generated if you want to remove please do it yourself.

> On the basic widget editor, you can swap between token and board, which seems to only affect the layer.  Seems like if you set the property to board, it should also change the size to 1600x1000 by default.

This is as intended. What if someone wants to have a resized board?

> On the label edit screen, I think you should have a bigger text box.  Probably most people will just use it for a few words, but there is so much screen space, it wouldn't hurt to have a bigger display for those times when someone needs a lot of text.

There is going to be a next PR that only make this kind of changes. I just don't want to mix fine tunning of looks with features. 

> Visually, I like the way the colors, buttons, scrollbars, etc. look.  We are definitely improving the look of our "brand" overall.

Yeah this is a first step. I definitely want to go way beyond this. It just to much work to put into only one PR and I wanted to have the minimal good looking UI to merge it as soon as possible.

**Comment by 96LawDawg** [comment]
> > On the basic widget editor, you can swap between token and board, which seems to only affect the layer.  Seems like if you set the property to board, it should also change the size to 1600x1000 by default.
> 
> This is as intended. What if someone wants to have a resized board?

Then they use the sliders to resize it.  If the only difference is layers, then call it layers.  I don't feel strongly about anything else in my comments, but I definitely think a board should default to full screen.

**Comment by bjalder26** [comment]
> Then they use the sliders to resize it. If the only difference is layers, then call it layers. I don't feel strongly about anything else in my comments, but I definitely think a board should default to full screen.

I think it would be nice if uploading a board also gave the option of automatically scaling the image to 1600x1000 as well.  It could do so by calculating the pixel ratio then updating the scale property (e.g. "scale": [2.4, 1]).  I suspect there are a lot of people who aren't great about resizing images.  However, what I am talking about would be outside this PR.

**Comment by 96LawDawg** [comment]
> I think it would be nice if uploading a board also gave the option of automatically scaling the image to 1600x1000 as well. It could do so by calculating the pixel ratio then updating the scale property (e.g. "scale": [2.4, 1]). I suspect there are a lot of people who aren't great about resizing images. However, what I am talking about would be outside this PR.

No math required.  The "upload board" button already sets the size (scale may be off, but that is up to the user).  The default behavior for a "board" is already full-screen.  This PR moves away from that.

**Comment by RaphaelAlvez** [comment]
> Then they use the sliders to resize it. If the only difference is layers, then call it layers. I don't feel strongly about anything else in my comments, but I definitely think a board should default to full screen.

Personally I prefer not to touch people's stuff.
I also think this would be kinda buggy to code since it would only be applied when changing from a token to a board. Maybe I could include a fullscreen checkbox.

> I think it would be nice if uploading a board also gave the option of automatically scaling the image to 1600x1000 as well.  It could do so by calculating the pixel ratio then updating the scale property (e.g. "scale": [2.4, 1]).  I suspect there are a lot of people who aren't great about resizing images.  However, what I am talking about would be outside this PR.

Yeah I really miss this feature all the time

**Comment by RaphaelAlvez** [comment]
> > I think it would be nice if uploading a board also gave the option of automatically scaling the image to 1600x1000 as well. It could do so by calculating the pixel ratio then updating the scale property (e.g. "scale": [2.4, 1]). I suspect there are a lot of people who aren't great about resizing images. However, what I am talking about would be outside this PR.
> 
> No math required.  The "upload board" button already sets the size (scale may be off, but that is up to the user).  The default behavior for a "board" is already full-screen.  This PR moves away from that.

Yeah I didn't realize that. I still think a full screen checkbox would be a good compromise

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
Approved with the condition that board widgets get a checkbox or something similar that allows them to be set to full screen.  I have reviewed the other areas impacted by the changes and they are fine, with no problems noted.

**Comment by bjalder26** [comment]
#addCustomOverlay textarea, #editJSONoverlay textarea {  height: 100%;  min-height: 100%;}

Might want to throw a resize: none; into here if you want to prevent resizing of the textarea on the editoverlay.

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
The button `Save in-progress game` doesn't look like it's disabled anymore.

**Comment by RaphaelAlvez** [comment]
> The button `Save in-progress game` doesn't look like it's disabled anymore.

Oh yeah need to fix that

**Review by ArnoldSmith86 — APPROVED** [review]
Big step in the right direction. :smile:

**Pull request merged**
