### PR TITLE
added toggle for wide/narrow sidebar to JSON editor

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The sidebars on the right of the JSON editor are pretty wide right now. When writing complicated routines that is useful but the rest of the time it is basically a giant waste of space that can make the room look tiny depending on your resolution.

This PR adds a new button to the top row of commands that toggles the width between two presets.

We might have to tweak the values a bit but I think a toggle between a narrow and a wide preset is good enough. Adding a way to set the size freely is also possible but a lot more work and then people will ask for saving their sizes etc.

This PR should work fine as is but please use it as a base for further discussion.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3849/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
In narrow mode, the "CTRL-click..." text conflicts with the placement of the mouse coordinate display. Perhaps put a blank line before that text, or move the mouse coordinates.

**Comment by 96LawDawg** [comment]
In narrow mode, the "Show Routine Debug Output" label covers too much of the bottom left of the screen.

**Comment by ArnoldSmith86** [comment]
> In narrow mode, the "Show Routine Debug Output" label covers too much of the bottom left of the screen.

I want to fix that (also the F key display) but those are unrelated. It would happen in production just the same - only at different window aspect ratios.

**Comment by ArnoldSmith86** [comment]
I initially planned to make these changes in a different PR but it might be a better idea to have them all in here.

- The F-keys and "Show Routine Debug Output" are more compact now and will actually be hidden completely when there's not enough room for them.
- The width of the F-keys is no longer fixed. More jumping around but less truncated IDs. I named a lot of overlapping stuff `Player 1 - *` lately and the truncating was not helpful.
- The F-keys skip `F4` now because `CTRL-F4` cannot be remapped from "close tab" (at least not in my Firefox).
- `F9` no longer triggers tracing when the JSON editor is active to avoid the conflict.
- The room now shrinks to fit the viewport height.

This is what it looks like for me on a 1366x768 laptop running Firefox on vanilla Linux Mint 20.2:

image

Feedback, please. :smile:

**Comment by ArnoldSmith86** [comment]
I built a game with this PR and on my laptop this is _so_ much better.

On my big screen without fullscreen I actually hit exactly the aspect ratio where the top and bottom are hidden. I'm gonna make the room shrink instead of hiding those.

**Comment by ArnoldSmith86** [comment]
> I'm gonna make the room shrink instead of hiding those.

OK, that was way easier than expected...

I would still love some feedback. :smile:

**Comment by rogerl50** [comment]
This looks like a great improvement. A couple of minor things: 
1) [unrelated] can you change the button background for the top command buttons? It's very hard to see the icons against the dark blue background. 
2) The debug window could actually be narrower, I think, perhaps to the width of the room in wide sidebar mode; that way the JSON will never be covered by the debug information. It will only be an issue when things get nested deeply enough that it has to wrap.

**Comment by ArnoldSmith86** [comment]
> 1. [unrelated] can you change the button background for the top command buttons? It's very hard to see the icons against the dark blue background.

Hasn't bothered me yet. I would prefer to not address this in this PR.

> 2. The debug window could actually be narrower, I think, perhaps to the width of the room in wide sidebar mode; that way the JSON will never be covered by the debug information. It will only be an issue when things get nested deeply enough that it has to wrap.

This I will tweak a bit..

**Review by rogerl50 — APPROVED** [review]
A great improvement, works through testing.

**Pull request merged**
