### PR TITLE
support `#tutorials` to jump directly to Tutorials

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Adding `#tutorials` after the URL will pre-select Tutorials in the game shelf filters.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1533/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1533-pr-test`.

**Comment by RaphaelAlvez** [comment]
id prefer if there was no redirect but I'm happy with it

**Review by RaphaelAlvez — APPROVED** [review]
tested

**Comment by ArnoldSmith86** [comment]
> id prefer if there was no redirect but I'm happy with it

There is no redirect. Only the URL changes. You'd prefer if it still showed "#tutorials"? Might be misleading either way because you can just switch to games.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

I like this.  I was trying to think of a way to do this to make the Tutorials room work.  After this is merged, can change the links we post in Discord and the wiki.

**Pull request merged**
