### PR TITLE
fix Go button

### PR DESCRIPTION
**Pull request by larkob**
Addresses #271

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3273/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
Not sure if there is any difference but the enter button is not working on my phone.

**Comment by larkob** [comment]
@RaphaelAlvez Can you please try again? I cannot test this on mobile.

**Comment by RaphaelAlvez** [comment]
Working.

There is another problem though it is not related to your PR. Triggering the keyboard on input mess everything. The room div get disaligned from the main div. I had to reload the page. 

I also accidentally removed you room and There is no equivalent example on the public library.

**Comment by larkob** [comment]
No problem. I've recreated the test game. So, if this is working now - can you approve the PR?

**Comment by robartsd** [comment]
> Working.
> 
> There is another problem though it is not related to your PR. Triggering the keyboard on input mess everything. The room div get disaligned from the main div. I had to reload the page.
> 
> I also accidentally removed you room and There is no equivalent example on the public library.

I'm experiencing the same issue with triggering the keyboard messing up the room requiring a refresh. I've never tried opening a VTT input on any mobile before, so I don't know what behavior this has changed. I certainly do not consider mobile input fixed by this.

**Review by RaphaelAlvez — APPROVED** [review]
This PR does not solve all the problems with input overlay and mobile but it moves in the right direction so I'm approving it. Another issue has to be open to addressing the major issue with display once the user clicks on ANY input box @robartsd .

**Review by ArnoldSmith86 — APPROVED** [review]
I feel like this is overly complicated. For me it also works just fine to not modify Javascript at all and only do this in room.html:

```html
      <form onsubmit="return false">
        <h1>Button Input</h1>
        <div id="buttonInputFields"></div>
        <button id="buttonInputGo">Go</button>
        <button id="buttonInputCancel">Cancel</button>
      </form>
```

`<button>`s submit forms by default; no need for another `<input>`. That also means that `#buttonInputGo` is clicked automatically and that leads to the function only doing a `return false`.

But maybe this is not working in all browsers? I'm also fine with merging as is.

**Comment by larkob** [comment]
I'll merge #292 instead of this one.

**Pull request closed without merging**
