### PR TITLE
greatly improved conflict detection

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The conflict detection in VTT is responsible for making sure that every client has the same room state. If two clients edit the same widget "at the same time" (so before knowing about the changes by the other client), the server tells the later client that the change was invalid and resends the entire room state.

In general this seems to be working quite well. I am not aware of any instance where two clients diverged from each other.

There have been issues with falsely detected conflicts though. So the conflict resolution was triggered seemingly unnecessarily and one player saw the room blink (state reloaded) and whatever widget they tried to drag got ripped out of their "hand".

When working on JSON editor and timer improvements yesterday, I refined the conflict detection to work on property basis (previously a conflict was triggered if the same widget was changed - no matter which properties were affected). But afterwards I still had conflicts I did not expect.

Turns out the conflict detection was looking at older deltas than it needed to.

This PR changes the conflict detection to property level and restricts it to only look at deltas that are newer than the one the conflicting delta was based on.

This should be tested thoroughly because I do not want clients to have diverging room states. I would much prefer the current state where too many conflicts are detected than too few.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3539/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
This PR need to be tested in a game night. I think that it would be pointless to do it by myself.

**Comment by ArnoldSmith86** [comment]
True. It was part of the last two staging PRs though. So it was active the last two game nights.

**Comment by RaphaelAlvez** [comment]
I took a look at the code and the changes make some sense to me but I don't feel comfortable in making a code approval (@robartsd ?). I do think this is approved through test so let me know if you want me to give such approval.

**Comment by robartsd** [comment]
> I took a look at the code and the changes make some sense to me but I don't feel comfortable in making a code approval (@robartsd ?). I do think this is approved through test so let me know if you want me to give such approval.

I'm not confident enough in my understanding of the code either. @96LawDawg has reported some concurrency testing. This has also been staged for DevGameNight sessions without causing issues.

**Comment by RaphaelAlvez** [comment]
> > I took a look at the code and the changes make some sense to me but I don't feel comfortable in making a code approval (@robartsd ?). I do think this is approved through test so let me know if you want me to give such approval.
> 
> I'm not confident enough in my understanding of the code either. @96LawDawg has reported some concurrency testing. This has also been staged for DevGameNight sessions without causing issues.

Personally I would approve this. We did not see most of the classical conflicts problems in the lasts gave nights

**Comment by 96LawDawg** [comment]
I'm not against approving it, but if you really want to put it through its paces, we should play around in the poker room for a few minutes on the next dev game night.  Don't have to play any games.  The conflicts come about pretty quickly.  I would test this out in my actual poker group, but getting them all to the same URL when it changes takes too much time out of our night.  Some of them are very computer challenged.

**Review by RaphaelAlvez — APPROVED** [review]
Tested in devs game night and approved. Not sure if this PR is the reason but we are getting fewer problems

**Pull request merged**
