### PR TITLE
fixed cloning widgets with inheritFrom

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This is my best idea so far for fixing #2192. I did not test this at all yet. @pipejakob, can you do some testing / commenting?

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2204/pr-test (or any other room on that server)

**Comment by pipejakob** [comment]
Do you need any more help/testing from me on this, or is it just waiting for official review from a core member?

**Comment by 96LawDawg** [comment]
> Do you need any more help/testing from me on this, or is it just waiting for official review from a core member?

Pretty much waiting on me.  But if there is anything else you can think of to test, that would be good.  I will get to it eventually.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  I could not find any problems that this causes and it does fix the issue.

**Pull request merged**
