### PR TITLE
fixed several issues with INPUT and ESC

### LINKED ISSUE #2000: Pressing ESC from INPUT overlay crashes client
Pretty significant bug.  I'm guessing this was introduced as part of CHOOSE, but maybe something else.

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This should fix #2000, #2001, #2002, #2003 and #2004 which were only three separate but related problems.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2005/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR2005-pr-test`.

**Comment by 96LawDawg** [comment]
Tested. This fixes everything except #2001.

**Comment by ArnoldSmith86** [comment]
> Tested. This fixes everything except #2001.

How about now?

**Review by 96LawDawg — APPROVED** [review]
Approved through test

**Pull request merged**
