### PR TITLE
Update Dix Cards

### LINKED ISSUE #1716: Dix Cards
Scoring round does not advance phase for all players who successfully completed the phase, only the player who got rid of all their cards.

### PR DESCRIPTION
**Pull request by robartsd**
fixes #1716 

To Do: (optional):

- [x] update to use seats
- [x] update to use gameStartRoutine
- [ ] update to use scoreboard

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1721/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1721-pr-test`.

**Comment by 96LawDawg** [comment]
Now uses seats.  It was a fair amount of re-coding, but worth it for knowing the card count of other players' hands.  Also added `gameStartRoutine` to shuffle the cards. I don't think a scoreboard is a bad idea, but that would require changing the layout substantially to fit it in.  So I just left it as is.  Should be ready to test and merge.

**Comment by robartsd** [comment]
Play tested last night and did not notice any issues.

**Comment by RaphaelAlvez** [comment]
I didn't review it before because there was still a checkbox unmarked

**Review by 96LawDawg — APPROVED** [review]
Approved through testing

**Comment by 96LawDawg** [comment]
There is an unchecked box, but this doesn't need a scoreboard and it won't fit on the screen without reworking the layout.

**Comment by robartsd** [comment]
I marked the whole checklist as optional improvements.

**Comment by RaphaelAlvez** [comment]
> There is an unchecked box, but this doesn't need a scoreboard and it won't fit on the screen without reworking the layout.

I totally agree. I'm just pointing out that I tested other PRs and at the time I had the impression this one was not ready. Sorry for that.

**Pull request merged**
