### PR TITLE
Fix error when no selection to colapse

### PR DESCRIPTION
**Pull request by robartsd**

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3235/pr-test (or any other room on that server)

**Review by RaphaelAlvez — APPROVED** [review]
code reviewed , tested and approved

**Review by 96LawDawg — APPROVED** [review]
This seems to fix whatever was broken.  Should be merged as soon as possible.

**Review by ArnoldSmith86 — APPROVED** [review]
No idea what the problem was (didn't check Discord) but the code change seems reasonable.

**Pull request merged**
