### PR TITLE
Add Best Guess, Seats tutorial

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:
- Telepathy. Fixed card arrangement on table when multiple players drag a card from the hand.
- Best Guess.  New game by LawDawg96, similar to Just One.
- Diced. Fixed overlapping labels.  Added seats and turns.

Public Tutorials:
- Seats and TURN.  New tutorial. 4 variants: Basic, Advanced, Turns, and Board Demo.
- changeRoutine.  New variant for globalUpdateRoutine with leaderboard demo.
- Timer.  Fix error in the Basics variant that caused the color shifting holder to not work.
- Functions – GET. Changed the virtual properties variant to look at the _ancestor of the cards rather than piles as per @ArnoldSmith86 suggestion in #838.
- Hands.  Added a third variant showing the link between hands and seats.
- JSON User Guide. Uploaded file with correct name.

-Delete improperly named “Dice.vtt” and “JSON Editor User Guide.vtt” files.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3910/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
Successfully loaded changed files from library.json.

**Review by RaphaelAlvez — CHANGES_REQUESTED** [review]
- [ ] Telepathy. Fixed card arrangement on table when multiple players drag a card from the hand.
**No idea what I should be looking in this game**


- [x] Best Guess. New game by LawDawg96, similar to Just One.

- [x] Diced. Fixed overlapping labels. Added seats and turns.

Public Tutorials:

- [ ] Seats and TURN. New tutorial. 4 variants: Basic, Advanced, Turns, and Board Demo.
**Shouldn't variant "seats" from hand tutorial be duplicated in seats tutorial.**

- [x] changeRoutine. New variant for globalUpdateRoutine with leaderboard demo.

- [x] Timer. Fix error in the Basics variant that caused the color shifting holder to not work.

- [x] Functions – GET. Changed the virtual properties variant to look at the _ancestor of the cards rather than piles as per @ArnoldSmith86 suggestion in Add Cities, Roar, Telepathy, other updates #838.

- [x] Hands. Added a third variant showing the link between hands and seats.

- [x] JSON User Guide. Uploaded file with correct name.

**Comment by ArnoldSmith86** [comment]
Telepathy: If one player is dragging a card out of the hand (but still hovering the hand) and then another player moves a card from the hand to the stack (holder above hand), then it used to leave a gap in the cards going to the right. Now it shouldn't.

**Comment by 96LawDawg** [comment]
> Public Tutorials:
> 
> * [ ]  Seats and TURN. New tutorial. 4 variants: Basic, Advanced, Turns, and Board Demo.
>   **Shouldn't variant "seats" from hand tutorial be duplicated in seats tutorial.**

It is, just in a slightly different way.  The same demo is in seat 4 on the Seats: Advanced variant.

**Comment by 96LawDawg** [comment]
@RaphaelAlvez, did my comment address your concern?  If so, can you approve?

**Review by RaphaelAlvez — APPROVED** [review]
Approved by testing

**Pull request merged**
