### PR TITLE
Add Mahjong +4 other games +2 tutorials

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public library:
 - Add Mahjong.  New game by LawDawg similar to Mahjong.
 - Add Road Race.  New game by LawDawg similar to Mille Bornes.
 - Add Starship Pyramids.  New game by nupa similar to Homeworlds.
 - Add Yoink!  New game by LawDawg and mousewax similar to Scout.
 - Add You Can't Draw. New game by LawDawg similar to Pictionary.

Public tutorials:
 - New tutorial: Decks.
 - New tutorial: Enlarge
 - Updated tutorial Functions - AUDIO to include attribution information from sounds by Interitus
 - Updated tutorial FOREACH. Fix error in first couple of buttons that post results in wrong label.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1211/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
All new and revised files successfully loaded from library.json.

**Review by ArnoldSmith86 — APPROVED** [review]
I left some comments about Mahjong and Starship Pyramids in #public-library. Road Race and Yoink look nice. You Can't Draw is probably fine but I really don't enjoy the game so I didn't take a closer look.

I'm really looking forward to playing Starship Pyramids and Yoink.

Decks:
- No typos found so far but quotes and parenthesis could use some double-checking in the introduction and example 1.
- The last paragraph of the first example should probably mention `dynamicProperties`.
- I don't quite agree with "you should set `color:transparent`". I don't mind leaving it in there but I often set a background color behind my images.
- Example 4 misses a word: "The only custom property which not used to change the appearance is `rank` which is used in that game for sorting purposes."
- Example 4 typo: "need to by dynamic"
- You could mention somewhere that all the routine stuff won't work in this tutorial "room"; only in the games the decks are from.

I didn't look at the other tutorials yet. If the PR is still open when I find some more time, I probably will.

Enlarge (Cards):
- Superfluous word: "It also makes sets 'overflow' to 'visible' to show a larger sized image."

**Comment by 96LawDawg** [comment]
I've taken notes on all these comments and will make the changes.  Going to merge now because I hate pushing changes.  Hasn't worked right for me lately so I'd rather get the 95% solution merged then come back and clean up.

**Pull request merged**
