### PR TITLE
fix alignment issues and improve droptarget selection

### PR DESCRIPTION
**Pull request by robartsd**
This adds widget methods for converting between a widget's own coordinate system, it's parent's coordinate system, and the room's coordinate system. There is also a method to convert from the client coordinate system to the widget's coordinate system.

### for wiki Widgets page:

| Property  | Default value       | Description           | Tutorial              |
| --------  | ------------------- | --------------------- | --------------------- |
| _absoluteRotation| null<br/> (read-only)| `_absoluteRotation` returns the total rotation of a widget including the rotation that occurs in parent widgets. Read-only properties do not trigger change routines - this value is the sum of `rotation` for this widget and each of its parent widgets.|
| _absoluteScale| null<br/> (read-only)| `_absoluteScale` returns the effective scale of a widget including scale that occurs in parent widgets. Read-only properties do not trigger change routines - this value is the product of `scale` for this widget and each of its parent widgets.|
| _absoluteX| null<br/> (read-only)| `_absoluteX` returns the room x coordinate of the widget's insertion point (`x`,`y` in the parent widget's coordinate system). Read-only properties do not trigger change routines - this value can be affected by `x`, `y`, `scale`, and `rotation` of any of the widget's parents in addition to the widget's own `x` and `y` value.|
| _absoluteY| null <br/> (read-only)| `_absoluteY` returns the room y coordinate of the widget's insertion point (`x`,`y` in the parent widget's coordinate system). Read-only properties do not trigger change routines - this value can be affected by `x`, `y`, `scale`, and `rotation` of any of the widget's parents in addition to the widget's own `x` and `y` value.|
|_centerAbsoluteX| null<br/>(read-only)|`_centerAbsoluteX` returns the room x coordinate of the center of the widget. Read-only properties do not trigger change routines - this value can be affected by `x`, `y`, `scale`, and `rotation` of any of the widget's parents in addition to the widget's own `x` and `y` value.|
|_centerAbsoluteY| null<br/>(read-only)|`_centerAbsoluteY` returns the room y coordinate of the center of the widget. Read-only properties do not trigger change routines - this value can be affected by `x`, `y`, `scale`, and `rotation` of any of the widget's parents in addition to the widget's own `x` and `y` value.|
|_localOriginAbsoluteX| null<br/>(read-only)|`_localOriginAbsoluteX` returns the room x coordinate of (0,0) within the widget. This value is the same as `_absoluteX` unless the widget itself is transformed with `scale` and/or `rotate`. Read-only properties do not trigger change routines - this value can be affected by `x`, `y`, `scale`, and `rotation` of this widget or any of the widget's parents.|
|_localOriginAbsoluteY| null<br/>(read-only)|`_localOriginAbsoluteY` returns the room y coordinate of (0,0) within the widget. This value is the same as `_absoluteY` unless the widget itself is transformed with `scale` and/or `rotation`. Read-only properties do not trigger change routines - this value can be affected by `x`, `y`, `scale`, and `rotation` of this widget or any of the widget's parents.|

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3903/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
What should `_absoluteX` and `_absoluteY` return if the widget is transformed with scale and/or rotation? Currently I have this returning (0,0) in the widget's own coordinate system converted to the room global coordinate system, but I could see arguments for this returning the (x, y) in the coordinate system of the widget's parent converted to the room global coordinate system.

**Comment by ArnoldSmith86** [comment]
I don't quite understand the difference. Maybe we should expose your functions in the routines?

**Comment by rogerl50** [comment]
> What should `_absoluteX` and `_absoluteY` return if the widget is transformed with scale and/or rotation? Currently I have this returning (0,0) in the widget's own coordinate system converted to the room global coordinate system, but I could see arguments for this returning the (x, y) in the coordinate system of the widget's parent converted to the room global coordinate system.

I hope we don't get involved with special relativity here, with all the coordinate systems :smiley:

**Comment by robartsd** [comment]
> I hope we don't get involved with special relativity here, with all the coordinate systems 😃

No special relativity, at least not unless we start moving timers around really quickly.

**Comment by robartsd** [comment]
I'm not sure how widget methods should be exposed to routines. In use, I'd want these as compute functions, but that seems rather complicated to accomplish since the compute module is outside widget.js. For now I think I'll add:

`_centerAbsoluteX`, `_centerAbsoluteY`, `_localOriginAbsoluteX`, and `_localOriginAbsoluteY`.

`_absoulteX` and `_absoluteY` will be the room global coordinates converted from the widget's `x` and `y` values in the widget's parent coordinate system (as is in production currently for widget without transformed ancestors).

`_centerAbsoluteX` and `_centerAbsoluteY` will be the room global coordinates of the widget's center (calculated from the parent coordinate system, but the result should be the same calculating from the local center because the transformation origin is the center).

`_localOriginAbsoluteX` and `_localOriginAbsoluteY` will be the room global coordinates of (0,0) within the widget. If the widget does not have it's own transformations, this will be itentical to `_absoluteX` and `_absoluteY` but slightly more computationally expensive.

**Comment by robartsd** [comment]
Also added `_absoluteRotation` and `_abslouteScale`.

**Comment by robartsd** [comment]
I see someone has put canvases into transformed holders. As far as I know this problem is the same on production servers, but making use of `coordLocalFromCoordLocal()` within `mouseRaw()` should make this fairly easy to fix.

**Comment by robartsd** [comment]
Determining if a rotated holder should be a drop target should also be improved, but I'm not sure if that belongs to this PR.

**Comment by robartsd** [comment]
Now a drop target's transformed rectangle must be under the cursor position to be the hover target. If multiple targets are under the cursor, the target is still the closest measured from the widget center to target center.

**Comment by robartsd** [comment]
## Changes that might need discussion

### Widgets can be placed nearly entirely off screen

The test to keep 25% of the widgets width/height on screen has been removed. This test was based on the widget's untransformed size. To simplify the code, I moved the code checking room boundaries from widget.move() to mousehandling.js eventCoords(). Now any dragable point on the widget can now be moved to the edge of the room, so if you pick up a widget near the edge, you can almost completely move it off screen. As before, zoom out mode in the advanced editor eliminates checks for room boundaries.

### hoverTarget now checks based on cursor position

Previously hoverTarget checked based on overlap of the widget and the target (actually overlap of their client bounding boxes), now the cursor position must be over the target's transformed rectangle. This fixes the hitbox issue with rotated holders, but small holders may be harder to drop things into now.

**Comment by RaphaelAlvez** [comment]
> > I hope we don't get involved with special relativity here, with all the coordinate systems 😃
> 
> No special relativity, at least not unless we start moving timers around really quickly.
> 

I suffered in all quantum mechanics classes just appreciate that joke

**Review by RaphaelAlvez — COMMENTED** [review]
It does feel better to play with pieces in rotated holders. Approved by test

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

I had created a demo based on #878.  It sort of works on production because I did a lot of the complicated math in a routine.  But mouse movement was awkward and things still clicked strangely when moving from extreme scales or rotations.  This PR fixes all that and did away with the need for individual widget calculations.

The demo is in http://212.47.248.129:3903/LawDawg and it shows how 2 players can work with the "same" widgets (really they are all just inheritFrom copies) on different scales and rotations at the same time.

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
Actually, I'm going to revoke my approval for now.  One more discussion item we need to cover I just realized.  The x,y coords in a simple room now have ridiculous decimal point precision.  Just drop a checker in an empty room and you get "x": 496.2248995983936, "y": 343.81024765729586.  Can we do something about that?

**Comment by robartsd** [comment]
I don't think I removed any rounding of widget coordinates. Rotated widgets will cause plenty of long decimal values with the conversion fuctions. I don't want to round the coordinates in the conversion functions, but I'd be happy to round the final results. Should the rounding happen in `widget.move()`, `widget.moveEnd()`, `statemangaged.setPosition()`, or create `widget.setPosition()` for this?

**Comment by robartsd** [comment]
Widget coordinates are now rounded to the nearest integer as the widget is moved. This does mean that a ridiculously scaled fixed parent could cause something similar to grid movement.

**Review by 96LawDawg — APPROVED** [review]
Widgets on the floor get normal x,y.  Transformed widgets get precision.  That seems about right.  I give back my approval.  Thank you.

**Comment by robartsd** [comment]
> Widgets on the floor get normal x,y. Transformed widgets get precision. That seems about right. I give back my approval. Thank you.

If the widget has a fixed parent, the x,y gets rounded in the parent's coordinate system as the widget moves regardless of the parent widget's transformations. If the widget is dropped into a transformed parent, the conversion to the parent coordinate system can cause x,y values that are not integers.

**Comment by robartsd** [comment]
I think my wife playing on the Beta server discovered an issue with the Rummy Tiles grid alignment while using this PR.

**Comment by ArnoldSmith86** [comment]
Does this work when overriding `transform-origin`?

Also I'm not sure about the new holder drop behavior. It's kinda weird that you can put cards onto holders now. Maybe we add special cases for non-rotated holders? And/or check if the distance between card and holder is less than the sum of their smaller sides (so kinda use inner circles)?

**Comment by robartsd** [comment]
> Does this work when overriding `transform-origin`?

No. Transform-origin is assumed to be the default.

> It's kinda weird that you can put cards onto holders now. 

Don't understand what you mean.

**Comment by ArnoldSmith86** [comment]
If the card overlaps with a holder but your cursor doesn't, the card will float above the holder when letting go. We will probably get used to that but we should probably think about whether or not we can improve that.

Not even saying that the behavior in production is better. There it's problematic if you have a small holder at the end of your hand. If you move a card to the hand, it can't touch the small holder at all anymore or it'll snap back because the hand center is further away than the small one.

**Comment by robartsd** [comment]
> If the card overlaps with a holder but your cursor doesn't, the card will float above the holder when letting go. We will probably get used to that but we should probably think about whether or not we can improve that.

We could check the holder's absolute rotation, and size relative to the widget being moved to determine which hitbox tests to apply. Cursor location works great for large holders, but can be an issue for small holders.

**Comment by robartsd** [comment]
Marked as draft, as we further consider drop target tests.

Also, I've now decided that I want to adjust for transformations of the widget that occur during the move (I have code that is working for this except the `moveEnd()` adjustments for transformed `hoverTarget`.) This might cause some weirdness with grids that transform the widget (will probably want to test with a hex grid with rotation).

**Comment by ArnoldSmith86** [comment]
Maybe something like:

If cursor is over holder, drop into that.
If widgets aren't rotated, calculate area of intersection and drop into the one with biggest overlap.

**Comment by robartsd** [comment]
Not sure why the build test is failing. I'm also having difficulty opening a new gitpod workspace (but that seems to be a gitpod issue, not an issue with this PR).

**Comment by robartsd** [comment]
In the PR-test room, start the timer then drag the spinning pawn around.

**Comment by robartsd** [comment]
Looking at the hoverTarget code in widget.move(). Not sure why hoverTargetDistance and hoverTargetChanged are saved as properties of the widget object rather than just local variables in the method.

**Comment by ArnoldSmith86** [comment]
> I'm also having difficulty opening a new gitpod workspace

You are aware that there is a 40 or 50 hour time limit per month unless you pay?

**Comment by ArnoldSmith86** [comment]
> Not sure why hoverTargetDistance and hoverTargetChanged are saved as properties of the widget object rather than just local variables in the method.

No idea: https://github.com/ArnoldSmith86/virtualtabletop/blob/de92fedf597fcdd07ef5f27a9454fe11843cad33/client/js/widgets/widget.js

Probably just because `hoverTarget` is there. The `hoverTargetDistance` should be carried over from last move call though to save a few overlap calls. No idea if that makes a significant distance.

**Comment by robartsd** [comment]
> The `hoverTargetDistance` should be carried over from last move call though to save a few overlap calls. No idea if that makes a significant distance.

No, the distance changed since the last move call because the widget has moved again. Would only be worth carrying over if it gets used in moveEnd().

I'm thinking about comparing coverage (area of overlap of bounding rectangles / area of holder bounding rectangle) as a tiebreaker between potential droptargets instead of distance.

**Comment by robartsd** [comment]
> > I'm also having difficulty opening a new gitpod workspace
> 
> You are aware that there is a 40 or 50 hour time limit per month unless you pay?
> 
> Can be seen on the account page somewhere.

Yes, I have about 20 hours left with reset on the 8th. I've promised myself that if this hobby uses up that limit, I'll take a break until my reset.

**Comment by robartsd** [comment]
> Also, I've now decided that I want to adjust for transformations of the widget that occur during the move ... This might cause some weirdness with grids that transform the widget (will probably want to test with a hex grid with rotation).

Loaded Colonies in [http://212.47.248.129:3903/grid](http://212.47.248.129:3903/grid). Move a road or ship around there; you can find points near intersections where it rapidly jumps between grids as you move.

**Comment by robartsd** [comment]
The handing of transformations during move are working as I wanted them to for my bag demp. See difference in the composite bag example [https://beta.virtualtabletop.io/Bags](https://beta.virtualtabletop.io/Bags) vs. [CSS PR-test room](http://212.47.248.129:3951/pr-test).

**Comment by ArnoldSmith86** [comment]
We test-played http://212.47.248.129:3903/g1mj today on the beta server. Pretty much a perfect example of the holder overlap problem.

You drag the "trains" from the top left to the small holders on the map. Everyone missed all the time. Way easier on production.

Just providing a real-world example.

**Comment by robartsd** [comment]
> We test-played http://212.47.248.129:3903/g1mj today on the beta server. Pretty much a perfect example of the holder overlap problem.
> 
> You drag the "trains" from the top left to the small holders on the map. Everyone missed all the time. Way easier on production.
> 
> Just providing a real-world example.

Example is very helpful.

**Comment by robartsd** [comment]
I think this is much better hoverTarget code now.

Not sure if the grid issue is worth holding this up. I think It is minor - especially if you drag the widget from a point close to the center. I did have the thought that the move code could check if the cursor position is valid for a grid - if it is skip the coordinate conversion stuff (I'd be much happier with that idea if the widget's insertion point was its center instead of top left corner).

**Comment by 96LawDawg** [comment]
I reiterate my approval.  Everything I tested again today works.  Not comprehensive because there are too many permutations.  But this is generally much better than what we have now.

**Comment by ArnoldSmith86** [comment]
Shouldn't it trigger right around there?

image

It does trigger around here:

image

**Comment by robartsd** [comment]
> Shouldn't it trigger right around there?
> 
> image

Looks like you have middle edge meeting middle edge there which should be the trigger point (assumes both objects are painted to their edges).

I probably should make the test `<=` rather than `<`. Perhaps I should also extend the target circle out a pixel or two.

> It does trigger around here:
> 
> image

Still better than when the cursor has to be directly over the target, right?

**Comment by robartsd** [comment]
Typo was causing size of object being dragged to not be included in distance test.

**Comment by robartsd** [comment]
> Shouldn't it trigger right around there?
> 
> image

Finally fixed!

**Comment by robartsd** [comment]
A large circular holder still has a lot of corner area where a widget can be droped without any actual overlap due to the cursor being within the corner, but that is definitely out of scope for this PR. Long narrow holders will still be difficult to drop things into near the ends, but should be reasonable targets near the middle.

**Review by ArnoldSmith86 — APPROVED** [review]
TBH, I don't want to spend the time to understand your code.

The improvements for transformed holders are amazing and "normal" holders work well now as well.

If somebody is bored, they could add a proper intersection of rotated rectangles when the widgets are less than the sum of their longer sides apart but we'll probably find that we don't need that.

**Comment by robartsd** [comment]
> If somebody is bored, they could add a proper intersection of rotated rectangles when the widgets are less than the sum of their longer sides apart but we'll probably find that we don't need that.

And check the `border-radius` as well. By the time they are done with that, we should have the new widget DOM allowing use of `clip-path` on widgets without causing behavior similar to `overflow:hidden` on their child widgets, so they'll need to support arbitrary polygons (and eventually any path when browsers finally implement that).

**Comment by robartsd** [comment]
> And check the `border-radius` as well. By the time they are done with that, we should have the new widget DOM allowing use of `clip-path` on widgets without causing behavior similar to `overflow:hidden` on their child widgets, so they'll need to support arbitrary polygons (and eventually any path when browsers finally implement that).

I would like to add borderRadius as a widget property (numeric values would set `border-radius` in px, "ellipse" would set `border-radius` to 50%) and extend the function that checks if a point is inside or not at some point.

**Pull request merged**
