### PR TITLE
Adding  '${}' in JSON editor

### PR DESCRIPTION
**Pull request by bjalder26**
Adding '${}' in places in the JSON editor where variables are frequently used.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3609/pr-test (or any other room on that server)

**Review by ArnoldSmith86 — COMMENTED** [review]
In general I want a more powerful solution to the problem but in the meantime this is a good idea.

The line with `applyVariables` should actually be deleted. I didn't realize it's still in there.

I never used the name of a collection in a variable. Did you?

When the `in` of `FOREACH` is `[]`, this doesn't seem to work. It just selects some stuff at the beginning of the widget for me.

**Comment by rogerl50** [comment]
Should `-> count` be treated the same as `-> value`?

**Comment by bjalder26** [comment]
> Should `-> count` be treated the same as `-> value`?
> 
> There are lots of other places where I could imagine `${}` being useful, but this seems like a good start. (Just as one example, `ROTATE -> angle`.)

Both of those default to numbers, so with this addition it should come up in both those situations.

**Review by rogerl50 — APPROVED** [review]

**Review by ArnoldSmith86 — APPROVED** [review]
`source` is also a collection. I don't think that's a frequent enough use-case to be included here but it's not like it really hurts anyone.

**Pull request merged**
