### PR TITLE
PCIO import improvements

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
@robartsd posted a PCIO file that fails to import.

One problem I found so far is `object.value: null` in card definitions.

Please report what else is broken.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3931/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
This PR only touches the importer and nothing else so it shouldn't break anything.

Without it every current PCIO file is broken if it uses a button.

It would be cool if someone could test a few old and new PCIO files and approve it.

**Comment by robartsd** [comment]
I've tested with recent PICO files. I'll try to find some old PICO files to test.

**Comment by ArnoldSmith86** [comment]
I tested a few in http://212.47.248.129:3931/arnold-test. Trip down memory lane...

**Comment by ArnoldSmith86** [comment]
@robartsd Can you just approve it? I think the two of us tested enough games and the important thing is that _nearly all_ current PCIO exports are broken in production because they changed how `clickRoutines` are stored.

**Review by robartsd — APPROVED** [review]
Approved through test.

**Pull request merged**
