### PR TITLE
fixed dropping a pile onto another pile

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Code refactoring for changeRoutine broke the code path where two piles are merged.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3440/pr-test (or any other room on that server)

**Review by RaphaelAlvez — APPROVED** [review]
This is urgent. Approved for imediate merging

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  This happened last night once in poker and I just thought it was a strange room error.

**Comment by ArnoldSmith86** [comment]
Honestly, it's _very_ unlikely that this makes it worse. Merging.

**Pull request merged**
