### PR TITLE
fixed adding games with multiple variants to the public library

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Adding the first variant already tried to save all assets from all variants but then could not read the second file.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1825/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1825-pr-test`.

**Review by 96LawDawg — COMMENTED** [review]
I don't think this worked.  I can't load, for example, the Team II (but under a different name) into this PL in this PR.

**Review by 96LawDawg — APPROVED** [review]
Now that I tested it properly, it works.  Approved through test.

**Comment by mousewax** [comment]
Yes. This seems to work on my server as well.

**Pull request merged**
