### PR TITLE
added inverted properties to `inheritFrom`

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Instead of `["x","y"]` you can now use `["!x","!y"]` to inherit everything EXCEPT `x` and `y`.

Completely untested. As in: I did not even check if the site still loads.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3916/pr-test (or any other room on that server)

**Review by RaphaelAlvez — APPROVED** [review]
Tested and code reviewed

**Comment by rogerl50** [comment]
This seems to work properly, but it took me a while to convince myself that if the user mixed `!prop` and `prop` that the results are as expected. That is, if the first property in the list does not have a `!`, then later properties with `!` are ignored (so will not be included), while if the first property does have a `!`, then later properties without `!` are ignored (so *will* be included). Probably fine to leave as is, but requires some documentation in the wiki.

**Comment by ArnoldSmith86** [comment]
Does mixing make any sense?

**Comment by RaphaelAlvez** [comment]
> Does mixing make any sense?

I don't think it does... better keep as is

**Comment by rogerl50** [comment]
No, it doesn't make sense. That was my point. It is allowed by the syntax, but the sense of the first element in the array determines whether things are included or excluded.

**Comment by rogerl50** [comment]
To try and be clearer: Currently
```
  "inheritFrom": {"widget1": ["!prop1", "prop2", "!prop3"]}
```
is accepted, and has the same effect as
```
  "inheritFrom": {"widget1": ["!prop1", "!prop3"]}
```
while
```
  "inheritFrom": {"widget1": ["prop1", "!prop2", "prop3"]}
```
is also accepted and has the same effect as
```
  "inheritFrom": {"widget1": ["prop1", "prop3"]}
```
I am not proposing a change here, just noting how it works.

**Comment by RaphaelAlvez** [comment]
> To try and be clearer: Currently
> 
> ```
>   "inheritFrom": {"widget1": ["!prop1", "prop2", "!prop3"]}
> ```
> 
> is accepted, and has the same effect as
> 
> ```
>   "inheritFrom": {"widget1": ["!prop1", "!prop3"]}
> ```
> 
> while
> 
> ```
>   "inheritFrom": {"widget1": ["prop1", "!prop2", "prop3"]}
> ```
> 
> is also accepted and has the same effect as
> 
> ```
>   "inheritFrom": {"widget1": ["prop1", "prop3"]}
> ```
> 
> I am not proposing a change here, just noting how it works.

I agree that ignoring something is weird

"inheritFrom": {"widget1": ["prop1", "!prop2", "prop3"]}

means copy prop1 and prop3 but don't copy prop2

the result is the same as in "inheritFrom": {"widget1": ["prop1", "prop3"]}.


Maybe  "inheritFrom": {"widget1": ["!prop1", "prop2", "!prop3"]}

should be interpreted as "inheritFrom": {"widget1": ["prop2"]}

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
The property works as advertised.  But there is some sort of strange error that crashes the JSON Editor.  To replicate:
 - Duplicate a simple widget using inheritFrom
 - Click on the duplicated widget in the inheritFrom property
 - Put the brackets around it as if you were going to manually create the conditions.  Should look like this: `"inheritFrom": {"2k98":[]}`
 - Then in between the straight brackets start typing as if you were going to build the conditions.  JSON Editor crashes.  Depending on the order you added the brackets, it might crash before then.

This does not happen in production.

**Comment by bjalder26** [comment]
Following LawDawg's instructions, it looks like this is the exception, and that you'll need to make sure properties isn't empty first.

image

**Comment by ArnoldSmith86** [comment]
Better?

**Comment by bjalder26** [comment]
> Better?

Yes, it looks like that problem is gone.  One of the things I'm noticing is that if something is set to inherit a property, then set to not inherit it, the old property is still applied until there is a browser refresh.  I think that is a separate issue though.

**Comment by ArnoldSmith86** [comment]
Does that also happen in production? (It probably does.)

**Comment by bjalder26** [comment]
> Does that also happen in production? (It probably does.)

Yes

**Comment by rogerl50** [comment]
The more I think about how arrays with mixed `!prop1` and `prop2` are handled, the less I like it. I think it has the potential for confusion for users. Perhaps adding a different primitive,
```
  "inheritFromExcept": {"widget1": ["prop1", "prop3"]}
```
to mean the same as the above
```
  "inheritFrom: {"widget1": ["!prop1", "!prop3"]}
```

**Comment by ArnoldSmith86** [comment]
Does that help? What happens when you add both of those?

**Comment by rogerl50** [comment]
> Does that help? What happens when you add both of those?

Yeah, you're right. It just introduces ambiguity somewhere else.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  I'm not overly worried about the concerns @rogerl50 raises.  It could be confusing, but honestly inheritFrom is already a bit confusing.  Not in the implementation, but in realizing why your widgets are doing something you didn't expect.  I think the inverted property brings a nice granularity of control that at least one user has asked for.  I also think I will start using this once merged.

**Review by rogerl50 — APPROVED** [review]
I can't think of anything that is clearer than what is here. It can all be explained in documentation. This is a very useful feature; I've already been tripped up a couple of times by using `*` when I really needed to exclude one property.

**Pull request merged**
