### PR TITLE
reset z values when above 90000

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The CSS property `z-index` is calculated `(layer+10)*100000 + z`. This means that if `z>=100000`, the widget effectively jumps into layer `layer+1`.

This PR introduces the function `resetMaxZ` which gets called if the highest z value in a layer is above 90000. It then reassigns new z values to every widget in that layer starting with 1 (without changing their relative order in the z stack - unless they use negative z values which is not supported officially).

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3509/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
I moved some things onto the server to test it out, and it appears to work perfectly.

**Comment by ArnoldSmith86** [comment]
I think the function needs to be called at a different place. I'll have another look.

It's also weird that TestCafé fails. Maybe a game uses z values higher than 90000?

**Comment by robartsd** [comment]
> I think the function needs to be called at a different place. I'll have another look.
> 
> It's also weird that TestCafé fails. Maybe a game uses z values higher than 90000?

It's failing on Reward. Reward has a lot of pieces and probably had a lot of things moved around during development.

**Comment by ArnoldSmith86** [comment]
Yeah. It has z values above 350.000...

I'll just update the checksum in this PR. I don't know if it's worth it to "fix" the game because it's not really broken.

**Comment by robartsd** [comment]
High z values haven't really been a problem in practice because for most games they are most likely to occur in the top layer used.

**Comment by ArnoldSmith86** [comment]
Hmm. Apart from thousands of z values, two cards switch their parents. Ideas? :smile: 

```diff
   ac785fc0-5463-41fe-8553-800448347c24: {
-    z: 350649
+    z: 9779
-    parent: "Yakutsk"
+    parent: "Ontario"
   }
   449a46b1-f627-4bbd-8dc3-292f339f3ca2: {
-    z: 350636
+    z: 9792
-    parent: "Ontario"
+    parent: "Yakutsk"
   }
```

**Comment by 96LawDawg** [comment]
I'll take a look.

**Comment by ArnoldSmith86** [comment]
I mean, it has to be caused by my new code (which is just a handful of lines).

**Comment by 96LawDawg** [comment]
So here is what I think.  The random distribution of tokens to starting countries in Reward is done by bringing the starting colors together (3 in the TestCafe case) and shuffling them.  Since your new code changes the z values, the standard shuffle that TestCafe forces so it is the same every time, is not the same this time because the z values all got hosed.

**Comment by 96LawDawg** [comment]
I will save a new version of the Reward game that starts with z values lowered by this code.  It won't fix this TestCafe case, and I'll have to change the checksum again when I upload it.  But I think all this is consistent with what I would expect.  I think.

**Comment by ArnoldSmith86** [comment]
I found the problem. Checking if it's fixed...

**Review by 96LawDawg — APPROVED** [review]
This works as advertised.  Approved through test.  Not sure if you found a problem with Reward after your last comment or not.  Assuming you did not, I believe this can be merged.

**Comment by ArnoldSmith86** [comment]
The problem was that the one widget that triggered the reset still received the old z value, causing the order to change. That's fixed now.

**Pull request merged**
