### PR TITLE
removed type when adding basic widget

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
The command `Add basic widget` in the JSON editor currently adds `type: basic` to the added widget implying that that is required. In fact any value for `type`, that is _not_ one of the other widget types, results in a basic widget.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2042/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR2042-pr-test`.

**Comment by 96LawDawg** [comment]
Either here or in #2041 we should add "type" into the JSON editor's list of clickable properties.

**Comment by ArnoldSmith86** [comment]
> Either here or in #2041 we should add "type" into the JSON editor's list of clickable properties.

Hmm, tricky. The editor only shows command buttons for properties that apply to the current widget type. A widget without `type` is type basic which doesn't have a `type` property. We could fake it, of course.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  I never noticed this before.  I don't use the JSON Editor to add widgets.  I've just been using the overlay from the menu at the top.  But, yeah, that is unncessary.

**Pull request merged**
