### PR TITLE
Default values in INPUT select field

### LINKED ISSUE #1123: No default value for "select" fields in INPUT
When using `select` field in an `INPUT` function, it is not possible to store a default value.  When you run the routine, the field always defaults to the first value in the list.  Other fields have that capability and it would be nice to add it to `select` as well.

### PR DESCRIPTION
**Pull request by robartsd**
Fixes #1123 

Default value for an INPUT select field can be set in two ways. Setting the field value to the value of one of the options, or setting `selected: true` within the option to select.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:1124/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Funny. I was thinking about implementing the exact same two ways. Kinda obvious ofc but still...

**Comment by 96LawDawg** [comment]
Tested.  Works.  Why still draft?

**Comment by ArnoldSmith86** [comment]
So, I just wanted to add `selected: true` to one option and then overriding that using the `value` of the field. That doesn't work. Do we want that to work?

**Comment by 96LawDawg** [comment]
> So, I just wanted to add `selected: true` to one option and then overriding that using the `value` of the field. That doesn't work. Do we want that to work?

That would make `select` very different from the other `INPUT` modes and adds a (perhaps unnecessary layer of complexity).  However, if there is a conflict between the 2 ways of accomplishing the same thing, then there needs to be some conflict resolution solution.  I guess allowing "value" to override "selected: true" would make sense.

**Comment by ArnoldSmith86** [comment]
Yeah, maybe we should remove the `selected: true` part. I liked it initially but the way it is now, if you use both, it breaks (because two are selected and the browser just uses the first selected option in the select).

We could of course ignore that it breaks and tell people to just use one of them.

We could also "repair" it so that one of them _actually_ overrides the other.

Or we just remove `selected` and make it work like all the others.

**Comment by robartsd** [comment]
I try to always open PRs as a draft.

I lean toward `field.value` taking priority over `option.selected`.

I was also thinking about expanding to support multiple selections (where `option.selected` would be very useful).

**Comment by ArnoldSmith86** [comment]
`if(option.value == field.value || field.value === undefined && option.selected)` should probably do it then?

**Comment by ArnoldSmith86** [comment]
It should probably also use `selected: true` if `value === null`. I just tried to build my language selection the way I initially intended. Having `selected: true` for English and then this:

```JSON
        {
          "type": "select",
          "options": "${languages}",
          "label": "Language",
          "variable": "language",
          "value": "${PROPERTY lastLanguage}"
        }
```

So I would save the last selected language in the property `lastLanguage`. But if I do this, it ignores `selected: true` even if the property doesn't exist because it's `null` and not `undefined`.

**Review by ArnoldSmith86 — APPROVED** [review]
Now the override seems useful to me. :+1:

**Comment by 96LawDawg** [comment]
So, for me since I can't understand the JavaScript, can you explain what is happening in non-programmer terms so I can update the wiki?  I'm guessing now you can use either `value` or `selected` as originally proposed.  And if you specify `value` it overrides `selected`?  Is that right?

**Comment by robartsd** [comment]
> So, for me since I can't understand the JavaScript, can you explain what is happening in non-programmer terms so I can update the wiki? I'm guessing now you can use either `value` or `selected` as originally proposed. And if you specify `value` it overrides `selected`? Is that right?

Yes. 

If `field.value` is provided, the first option with a `value` that matches `field.value` is selected. If `field.value` is missing (undefined or evaluates to `null`) then the first option with `selected: true` (actually any "truthy" value would work) will be selected. If neither case occurs (including providing a `field.value` that does not match any `option.value`, even if there is an option with `selected: true`) then the first option provided is selected (as currently happens in production).

**Comment by 96LawDawg** [comment]
**Suggested wiki edits (starts about 1/2 down the `INPUT` entry):**

For those field types that accept input and return a value (`checkbox`, `color`, `number`, `string`, and `switch`), the following additional parameters can be used.
  * label: _string_ - to be displayed next to the input field
  * value: _various_ the initial value for the input field (for `checkbox`: true = checked, false = not-checked; defaults to false; for `switch`: left = off, right = "on"; defaults to "off")
  * variable: _variable name_ - specifies the variable in which to store the value/result.

For the `select` field, the `label` and `variable` fields have the same application as above.  There is also an `options` field that defines the possibilities for what the user can scroll and select.  The `value` field is used in two ways: as described above to store the default choice and in the `options` field as a sub-field for the value that gets stored in the `variable`.  In the `options` field, you can indicate which option will initially be displayed by declaring `"selected": true` inside that option.  If both `"selected":true` and `value` are used to define the starting option, then the information in `value` overrides `"selected":true`. The following example helps illustrate the point except that you would normally only use either `"value": "en-US"` or `"selected":"true"` and not both unless you use a dynamic property as the `value` and programmatically override the `selected` option: 

```JS
{
  "func": "INPUT",
  "fields": [
   {
      "type": "select",
      "label": "Choose language",
      "variable": "language",
      "value": "en-US",
      "options": [
        {
          "value": "en-US",
          "text": "English",
          "selected": true
        },
        {
          "value": "de-DE",
          "text": "German"
        }
      ]
    }
  ]
}
```

For the remaining field types (`subtitle`, `title`, and `text`), the only parameter is
  * text: _string_ - the text that will be shown to the player.

The following example show how to use each of the `INPUT` fields.
```JS
{
  "func": "INPUT",
  "fields": [
   {
      "type": "title",
      "text": "A header text for the overlay.",
      "css": "background-color:var(--VTTblue);color:white;"
    },
    {
      "type": "text",
      "text": "Stay a while and listen!"
    },
    {
      "type": "checkbox",
      "label": "Do you want to shuffle?",
      "variable": "shuffle",
      "value": true
    },
    {
      "type": "color",
      "label": "Which color would you like?",
      "variable": "myColor",
      "value": "${playerColor}"
    },
    {
      "type": "number",
      "label": "Which number do you like?",
      "variable": "myNumber",
      "value": 10,
      "min": 1,
      "max": 100
    },
    {
      "type": "string",
      "label": "Credit card?",
      "variable": "myCard",
      "value": "555-2483 63"
    },
    {
      "type": "select",
      "label": "Best Crypto",
      "variable": "crypto",
      "value": "BTC",
      "options": [
        {
          "value": "DOGE",
          "text": "Dogecoin"
        },
        {
          "value": "BTC",
          "text": "Bitcoin"
        }
      ]
    },
   {
     "type": "subtitle",
     "text": "Include Expansions:",
     "css": "background-color: purple;color:white;"
    },
    {
     "type": "switch",
     "label": "Rise of Khan",
     "variable": "includedeck",
     "value": "on"
    }
  ],
  "cancelButtonIcon": "cancel",
  "cancelButtonText": "Cancel",
  "confirmButtonIcon": "restart_alt",
  "confirmButtonText": "Restart Game"
}
```

**Review by 96LawDawg — CHANGES_REQUESTED** [review]
The ability to use `"selected":true` no longer works.  If you include that, NO default is selected and the initial option appears blank.

**Comment by ArnoldSmith86** [comment]
> The ability to use `"selected":true` no longer works. If you include that, NO default is selected and the initial option appears blank.

It looks like you broke it by still having this after the options:

```JSON
            {
              "selected": 5
            }
```

**Review by 96LawDawg — APPROVED** [review]
I'm an idiot.  I have no idea how that even got there.  Must have been from some earlier experimenting.  Or my dog ate my keyboard.  Approved through testing.

**Pull request merged**
