### PR TITLE
Add Tutorials (faceTemplates, FOREACH)

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Library:
- Chinese Checkers. Fixed one holder and added clickable turn indicator following dev game night comments.
- Medieval VNO. Swapped the default rotation for Next button (in Automation variant) to clockwise.
- Reward. Removed about 1,000 cards (game tokens) and replaced with clones.

Public Tutorials:
- Arrays (Creating). Changed text of button from GET to example dynamic expression (not caught earlier when JSON was updated to move away from GET, SELECT to var x …
- Button Appearance (Introduction).  Fixed typo switching left and right.
- faceTemplates. New tutorial by Interitus that shows how to use dynamic expressions to modify faceTemplates.
- Functions - FOREACH. New tutorial by Interitus showing how to use the FOREACH function and loopRoutines.
- Slightly modified library images for (Arrays, Comparison, Dice, Grids, Hands, JSON Editor User Guide, Master Button Math, Menus, Spinners, Strings, Timer)

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3553/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
How can I find the new tutorials? (They aren't in the linked page.)

**Comment by robartsd** [comment]
Recall buttons in Reward fail if the tokens are in a mixed pile. I think this is because some items in the pile do not match the new `dropTarget` even though the recalled items do.

**Comment by 96LawDawg** [comment]
> How can I find the new tutorials? (They aren't in the linked page.)

You got there before I could upload them from the library.  They should be there now.

**Comment by rogerl50** [comment]
In the FOREACH tutorial, the lower left button has a line reading `"condition": "${bool} // if true = value is present",`. This will always evaluate to `true`, since the comment will be included in the string. Trailing comments are (apparently) treated as such only in `var` declarations. (And, the output is wrong as a result.)

**Comment by bjalder26** [comment]
> In the FOREACH tutorial, the lower left button has a line reading `"condition": "${bool} // if true = value is present",`. This will always evaluate to `true`, since the comment will be included in the string. Trailing comments are (apparently) treated as such only in `var` declarations. (And, the output is wrong as a result.)

I thought I took those mistakes out.  Thanks for noticing.

**Comment by 96LawDawg** [comment]
> Recall buttons in Reward appear to fail if the tokens are in a mixed pile (pile handle does not update to show the removed items). I think the items are being deleted by the holder's enterRoutine without updating the pile handle for some reason. If all the colors in the pile are recalled, then the pile appears to disappear.

Until issue #554 is resolved, I think we should revert back to the previous Reward game version.  I cannot think of a workaround that would fix the concern about piles an involve cloning widgets rather than having a lot of existing cards.

**Comment by 96LawDawg** [comment]
> This is how that `IF` should start. I updated the button in the room (now the button works correctly again), but I'm not sure how to update it for the PR.

I took care of it.  I wish it was as easy as just changing the room.

So the FOREACH tutorial typo is fixed and Reward has been returned to its current public library version due to the pile problem.  I assessed that to be worse than the lag from having 1,000 card widgets.

**Comment by bjalder26** [comment]
> Until issue #554 is resolved, I think we should revert back to the previous Reward game version. I cannot think of a workaround that would fix the concern about piles an involve cloning widgets rather than having a lot of existing cards.

I know you're not likely to choose to do this, but putting the JSON below on your cards would solve the zero pile issue.  However, why use cards anymore?  You don't need to be able to enter a number to get 180 of them, you really only need 1 or each right?  Why not use a non-piling basic widget?

  "lRoutine": [
    {
      "func": "COUNT",
      "collection": "child",
      "variable": "COUNT"
    },
    {
      "func": "IF",
      "operand1": "${COUNT}",
      "relation": "==",
      "operand2": 0,
      "thenRoutine": [
        {
          "func": "IF",
          "operand1": "${PROPERTY type}",
          "relation": "==",
          "operand2": "pile",
          "thenRoutine": [
            {
              "func": "DELETE",
              "collection": "thisButton"
            }
          ]
        }
      ]
    }
  ],
 "parentChangeRoutine": [
    {
      "func": "IF",
      "operand1": "${PROPERTY parent}",
      "relation": "==",
      "operand2": "pile",
      "thenRoutine": [
        {
          "func": "SELECT",
          "property": "id",
          "value": "${PROPERTY parent}"
        },
        {
          "func": "SET",
          "property": "leaveRoutine",
          "value": "${lRoutine}"
        }
      ]
    }
  ]

**Comment by 96LawDawg** [comment]
The game pieces need to pile.  Otherwise you would be individually dragging a dozen or more around with you as you conquer the board.  Moving physical game pieces isn't too hard; cup your hand and push.  But moving a lot of individual widgets from one territory to another would be a real pain.  Piling is the only way to make that tolerable.

**Comment by bjalder26** [comment]
> The game pieces need to pile. Otherwise you would be individually dragging a dozen or more around with you as you conquer the board. Moving physical game pieces isn't too hard; cup your hand and push. But moving a lot of individual widgets from one territory to another virtually using mouse clicks would be a real pain. Piling is the only way to make that tolerable.

Ah I see.  Unless they are all holders then it would be an issue.  And you wouldn't be able to split anyway.  Also, my JSON had some issue anyway.  I thought it was working.

**Comment by robartsd** [comment]
> Until issue #554 is resolved, I think we should revert back to the previous Reward game version. I cannot think of a workaround that would fix the concern about piles an involve cloning widgets rather than having a lot of existing cards.

Although in actual play, you wouldn't usually recall certain colors from mixed piles (recalling all colors appears to work as expected). I wonder if moving to an intermediary holder would help. I'll see if I have time to experiment, but it's fine if it doesn't make it in to this update.

**Comment by 96LawDawg** [comment]
> Although in actual play, you wouldn't usually recall certain colors from mixed piles (recalling all colors appears to work as expected). 

I don't know why you would ever have mixed piles in actual play.  Only one color can occupy a territory.  When the conquering phase starts, you move your pieces to the top of the board.  The winner moves back into the territory in question and any remaining pieces are returned to the stock or distributed on the board.

But I've never actually played this implementation.  So I'm sure it will benefit from dev game night.  Maybe we just wait until then and update everything at once.  And maybe, because mixed piles shouldn't happen, the issue isn't as important as I thought.  In any event, probably best to leave it at status quo until we play it.

**Comment by bjalder26** [comment]
> Recall buttons in Reward appear to fail if the tokens are in a mixed pile (pile handle does not update to show the removed items). I think the items are being deleted by the holder's enterRoutine without updating the pile handle for some reason. If all the colors in the pile are recalled, then the pile appears to disappear.

My guess is that the parent is being deleted, and the children are not 'fully deleted'.  If you refresh the browser does the pile handle count change?

**Comment by 96LawDawg** [comment]
> My guess is that the parent is being deleted, and the children are not 'fully deleted'. If you refresh the browser does the pile handle count change?

I tested that on the version @robartsd created and the pile handle count does change if you refreshed the broswer.

**Comment by bjalder26** [comment]
> > My guess is that the parent is being deleted, and the children are not 'fully deleted'. If you refresh the browser does the pile handle count change?
> 
> I tested that on the version @robartsd created and the pile handle count does change if you refreshed the browser.

Weird, maybe I am seeing the wrong issue because for me they did when I wound up with wrong counts.

I think I worked around the issue here by deparenting them first (I also think I messed up the recall button locations):
https://virtualtabletop.io/zbaa

However, maybe you're seeing a different issue, or maybe browsers are different.

**Comment by 96LawDawg** [comment]
The problem seems to be fixed in /zbaa.  It looks like all you changed was something like this in each recall button:

```
{
      "func": "SELECT",
      "property": "label",
      "value": "Red"
    },
    {
      "func": "SET",
      "property": "parent",
      "value": null
    },
```

Was that all you did?  I can get that changed version uploaded again.

**Comment by bjalder26** [comment]
> The problem seems to be fixed in /zbaa. It looks like all you changed was something like this in each recall button:
> 
> ```
> {
>       "func": "SELECT",
>       "property": "label",
>       "value": "Red"
>     },
>     {
>       "func": "SET",
>       "property": "parent",
>       "value": null
>     },
> ```
> 
> Was that all you did? I can get that changed version uploaded again.

I also looked good doing it, but yeah, that is the only change.

**Comment by 96LawDawg** [comment]
Can someone review this, please?

**Review by ArnoldSmith86 — APPROVED** [review]
- Reward looks good. Way faster now.
- VNO has some kind of holder under the direction button. It swallows cards if you don't hit the discard pile exactly.
- Timer basics: Typo "incdicate" in countdown example and what does "Be careful using small precision values with changeRoutine as doing so can have unexpected and damaging consequences to the room state." mean?
- Arrays creating: should probably mention `var a = []` now. The button that seems like it mentions it, is misleading because `var a = [1,2,3]` does **not** work.
- faceTemplates: radius should be `false` or a number. Not quite sure what `true` does (looks like 100%).
- FOREACH: all labels already show the correct result except bottom left. Not a big deal but I first thought something is broken.

**Comment by 96LawDawg** [comment]
> * Reward looks good. Way faster now.
> * VNO has some kind of holder under the direction button. It swallows cards if you don't hit the discard pile exactly.
> * Timer basics: Typo "incdicate" in countdown example and what does "Be careful using small precision values with changeRoutine as doing so can have unexpected and damaging consequences to the room state." mean?
> * Arrays creating: should probably mention `var a = []` now. The button that seems like it mentions it, is misleading because `var a = [1,2,3]` does **not** work.
> * faceTemplates: radius should be `false` or a number. Not quite sure what `true` does (looks like 100%).
> * FOREACH: all labels already show the correct result except bottom left. Not a big deal but I first thought something is broken.

- VNO updated all 3 variants to change `dropTarget` so it will not accept cards.
- Timer: Fixed typo.  Removed confusing sentence (because I no longer even know what I was talking about).
- Arrays: Created separate topic for dynamic expressions and changed button text.
- faceTemplate: Changed radius to a number.
- FOREACH: erased all the default results so something will visibly happen when pressing the buttons.

Thanks!

**Pull request merged**
