### PR TITLE
card property changes get applied to dynamic face objects now

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This fixes that a lot of properties would not trigger DOM updates when they are used as dynamic card face properties or as `svgReplaces` properties.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3291/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
I tested it in that room, and it works.  I put a button in there that brings up a label, allows you to edit the label, then applies the text to the top card in the holder.  It immediately updates.  I left those items in there (2 holders, a label, a deck, and a button) in case you would like to try it out too.

**Comment by bjalder26** [comment]
I also put a deck in there that has a card with a red box around it that is 100 x 100 and tells you the x, y of the upper left corner.  With this "fix" or new feature, I thought it could be helpful for figuring out layouts.

**Comment by 96LawDawg** [comment]
> I also put a deck in there that has a card with a red box around it that is 100 x 100 and tells you the x, y of the upper left corner. With this "fix" or new feature, I thought it could be helpful for figuring out layouts.

Wow!  That is cool.  I'm sure that has some uses.  I don't know who added the z value to the other cards, but that was an interesting idea.  I learned something about z values.  Every time I clicked on a card, it increased the z value by 1 and made it 1 larger than the largest z value in the room.  There has been some peculiar behavior with z values reported before.  Maybe this can help some expert track down the reason for the problem.

**Comment by bjalder26** [comment]
> Wow! That is cool. I'm sure that has some uses. I don't know who added the z value to the other cards, but that was an interesting idea. I learned something about z values. Every time I clicked on a card, it increased the z value by 1 and made it 1 larger than the largest z value in the room. There has been some peculiar behavior with z values reported before. Maybe this can help some expert track down the reason for the problem.

ArnoldSmith86 put those cards in there, and I just copied the idea to try and make something that might be useful for layouts.  Before I would move a widget around and then look at the x, and y coordinates.  But before, you couldn't do this.

After playing around a little, it appears what you're describing with the z values is a feature of cards.  It appears they go to the highest z value of all cards in the room (or to a z value one greater than what was the highest).  Putting a layer property on one of the decks apparently does not affect this.

**Comment by 96LawDawg** [comment]
It's not just cards.  Other widgets do this also.  I added 2 checkers pieces.  They exhibit the same behavior as the cards (I used the ctrl-J JSON editor mode to watch the values change).  They just compete between themselves for the highest z value.

**Comment by bjalder26** [comment]
> It's not just cards. Other widgets do this also. I added 2 checkers pieces. They exhibit the same behavior as the cards (I used the ctrl-J JSON editor mode to watch the values change). They just compete between themselves for the highest z value.

I tried manually changing z values during edit, and they had no effect for the widgets I tried (I think a label and a deck).  However, I think I was getting the same results as you with the checkers, but now I am not.  I put a bunch of other widgets in there, and now I find that none of them "compete" for the highest z value with the cards, except the spinner.

I could have sworn the checkers were doing it too, but now if I move a checker, the cards just increment by one when I touch them again (increasing by one over their previous number).

So I don't know exactly what is going on.

Also, now if I change the z value manually on anything but the cards or spinner, the cards don't seem to compete with that value.

**Comment by rogerl50** [comment]
> I tried manually changing z values during edit, and they had no effect for the widgets I tried (I think a label and a deck). However, I think I was getting the same results as you with the checkers, but now I am not. I put a bunch of other widgets in there, and now I find that none of them "compete" for the highest z value with the cards, except the spinner.
> 
> I could have sworn the checkers were doing it too, but now if I move a checker, the cards just increment by one when I touch them again (increasing by one over the highest of the card or spinner z values).
> 
> So I don't know exactly what is going on.
> 
> Also, now if I change the z value manually on anything but the cards or spinner, the cards don't seem to compete with that value.

The z values that you see are relative to the layer in which the object lives. So cards and spinners are both in layer 0 by default, which is why their z values affect each other. But buttons, for example, are in layer -1, so their z values have no effect on the z value assigned to a card or a spinner.

**Comment by bjalder26** [comment]
Yeah, I just changed the z value of a button to zero, and it competed with the cards for the highest z value on that layer.  Also, I now noticed that checkers do affect each other's z values.  So I guess widgets "compete" for the highest z value with anything on their same layer.

So perhaps some of the odd z behavior spoken about is really just a misunderstanding of how the z values interact with each other based on their layer.

**Review by larkob — APPROVED** [review]
I've made some tests in the pr room and also looked at the code. Not sure that I understand everything, but I could not find any issue.

**Pull request merged**
