### PR TITLE
STAGING 2021-07-03: contains multiple PRs for testing

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Multiple PRs. See commit messages.

RaphaelAlvez:

> hijacking this PR to make tests to Seats composed widgets. 
> DO NOT close this PR
> 
> work being done in http://212.47.248.129:3640/seatTest

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3640/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
We really need to focus on merging PRs. Merging all of these into staging PRs is more and more work.

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86  I'm using this PR let it open for now please

**Comment by ArnoldSmith86** [comment]
I usually leave the latest two staging PRs open. So this would be closed on 2021-07-17.

**Pull request closed without merging**
