### PR TITLE
fixed crash with invalid widgets

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Invalid widgets will not be added. Examples are widgets without `id`, with non-existant `parent` or cards without `deck` or `cardType`. They will produce error messages in the browser console (except for non-existant `parent`, I think).

When adding the widget failed, it is removed "properly" by calling `removeWidget`. _But_ if that _also_ fails, it currently crashes the client. An example are cards with their `deck` set to an existing widget that is not a deck.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:1099/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:1099/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
I was trying to test this (on production) to see what happened.  But I don't understand.  How do you add, for example, a card with its deck set to something that is not a deck?  I tried to do that and got a JSON Editor notification in red that I can't do that, so it never took effect, so I couldn't try to remove it.  Confused.

**Comment by ArnoldSmith86** [comment]
Many broken widgets resulted from earlier bugs, I think. But there's no mechanic that removes broken widgets from game states so they stick around unless you remove them manually from the JSON.

There are also probably quite a few ways to create broken widgets using routines. Of course we should try to inhibit those as well.

The easiest way to test this is probably to download a game state and hand-edit it in a text editor. Old school.

**Comment by 96LawDawg** [comment]
So I went old school.  I changed the "deck" of a card to some other widget in the room using an offline text editor.  When I uploaded that file into a room on the production server, that card just did not exist.  So far, I can't seem to be able to create the conditions needed to even test this.

**Comment by ArnoldSmith86** [comment]
Looking at the code, I think the card has be after its deck in the room JSON for this bug to occur. If that still doesn't trigger it, I'll have to look deeper.

The bug was reported via private message in a private room so I can't share the actual culprit. But if you still can't reproduce it, I'll extract a demo from the broken room.

**Comment by 96LawDawg** [comment]
> Looking at the code, I think the card has be after its deck in the room JSON for this bug to occur. If that still doesn't trigger it, I'll have to look deeper.

I moved the card to a position after its deck (a checker) in the JSON.  Changed the deck to the checker.  Loaded up the room and it melted down.  Repeated flashing with no way to reset or do anything else.  Console said could not add widget.  So I still don't know how to reliably reproduce the problem.

However, since this did create a difference, I tried uploading the tweaked .vtt into this PR.  It behaved differently.  Still some room flashing, but more intermittent and I could move things around in the room.  But I could not open the JSON Editor to see anything.

https://virtualtabletop.io/5w2f and http://212.47.248.129:1099/lawdawg in case you need it.

**Comment by 96LawDawg** [comment]
Just to see what happened, and based on Panda's Discord post, I edited my room to delete the deck offline, but left the cards.  When I loaded it up in both production and this pr test server, the same thing happened: nothing.  I got a 0 pile of cards where they used to be, but all the cards, and of course the deck, were gone.

**Comment by ArnoldSmith86** [comment]
> Repeated flashing with no way to reset or do anything else. Console said could not add widget. So I still don't know how to reliably reproduce the problem.

That _is_ how you reproduce the problem and it _is_ the problem. :smile:

> It behaved differently. Still some room flashing, but more intermittent and I could move things around in the room. But I could not open the JSON Editor to see anything.

Thanks for the hint with the JSON editor. That should be fixed now. Can you still produce "room flashing"?

**Comment by 96LawDawg** [comment]
Room still flashes, but now I know when and why.  It flashes when you drag the cursor into the upper left corner of the room (starting at exactly the coordinates that would be the outer boundary of a standard sized card if the card were at 0,0 (so right at x=103 or y=160).  Drag the mouse there and the room flashes.  The JSON Editor, which works now, shows nothing located at 0,0 in the room.  And if you are in the JSON Editor when you take the mouse into the upper left coordinates, the room flashes and you get dumped out of the editor.

Hope that helps narrow it down.  Same demo file as before, now in http://212.47.248.129:1099/lawdawg2.

**Comment by robartsd** [comment]
> Room still flashes, but now I know when and where. It flashes when you drag the cursor into the upper left corner of the room (starting at exactly the coordinates that would be the outer boundary of a standard sized card if the card were at 0,0), so right at x=103 or y=160. Drag the mouse there and the room flashes. The JSON Editor, which works now, shows nothing located at 0,0 in the room. And if you are in the JSON Editor when you take the mouse into the upper left coordinates, the room flashes and you get dumped out of the editor.
> 
> Hope that helps narrow it down. Same demo file as before, now in http://212.47.248.129:1099/lawdawg2.

DOM inspector shows that a DIV for a invalid card was added:
```
<div id="3y9g_K_S_mod" class="widget card " style="width: 103px; height: 160px; z-index: 1000000; transform: translate(0px, 0px);"></div>
```
Console shows the "Could not add widget!" and "Could not remove widget!" log entries for this widget.


Console log just before refresh that occurs on mouse over of the card:
```
Uncaught TypeError: this.deck.cardPropertyGet is not a function
    at Card.getDefaultValue (lawdawg2:7716:27)
    at Card.get (lawdawg2:4661:33)
    at Card.get (lawdawg2:6713:20)
    at Card.showEnlarged (lawdawg2:6986:13)
    at HTMLDivElement.<anonymous> (lawdawg2:5271:63)
```

**Comment by robartsd** [comment]
#1093 added `this.applyDeltaToDOM(this.defaults)` which is adding a DOM element for the invalid widget before the widget add ultimately fails due to the widget specified as the deck not being a deck (it is a basic widget) so it does not have the deck.addCard() method.

The remove operation failed because the code finds a widget with the id specified as the deck for this card, but the id does not belong to a deck. This failure occurs before removeFromDOM() is called.

The recent commit fixes the issue by recognizing the invalid deck before adding the DOM element.

**Comment by ArnoldSmith86** [comment]
Thanks for testing!

I'm not sure what's happening exactly but I think this case merits a special condition: cards with their `deck` set to a valid widget ID but not actually a deck, will no longer be added in the first place.

I hope that other cases we didn't see yet will be caught by the initial change.

**Review by robartsd — APPROVED** [review]

**Pull request merged**
