### PR TITLE
fixed JSON editor copy and paste in Edge

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
WIP

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3544/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
@96LawDawg Does this fix it?

**Comment by 96LawDawg** [comment]
This fixed it in Edge; tested it and it still works in Chrome.  Not sure how much actual testing you want.

**Comment by ArnoldSmith86** [comment]
That's good enough for me. This is not meant to be merged yet because I only removed a new "feature". I'd rather fix it.

**Comment by 96LawDawg** [comment]
No worries.  I'll switch to Chrome for now.

**Comment by ArnoldSmith86** [comment]
I added some logging to the problematic code. Can you trigger the error and tell me what the console says? And do the exact same thing in Chrome, please.

**Comment by 96LawDawg** [comment]
In Chrome, I only get an error occasionally.  Not sure what is different there.  But I can't get the log to stay despite clicking on "preserve log."  What I do seem to get is something like below, repeating multiple times:  

(2) ["      ]", "      ", index: 0, input: "      ]", groups: undefined] (4) ["button", "clickRoutine", 0, "fields"]
pr-test:1846 before (2) ["    }", "    ", index: 0, input: "    },", groups: undefined] (4) ["button", "clickRoutine", 0, "fields"]
pr-test:1848 after (2) ["    }", "    ", index: 0, input: "    },", groups: undefined] (3) ["button", "clickRoutine", 0]
pr-test:1846 before (2) ["    }", "    ", index: 0, input: "    },", groups: undefined] (4) ["button", "clickRoutine", 1, "value"]
pr-test:1848 after (2) ["    }", "    ", index: 0, input: "    },", groups: undefined] (3) ["button", "clickRoutine", 1]
pr-test:1846 before (2) ["    }", "    ", index: 0, input: "    },", groups: undefined] (4) ["button", "clickRoutine", 1, "value"]
pr-test:1848 after (2) ["    }", "    ", index: 0, input: "    },", groups: undefined] (3) ["button", "clickRoutine", 1]

**Comment by bjalder26** [comment]
I tried to paste in a grid and it is giving me an error telling me that the last curly bracket is unexpected.

image

**Comment by ArnoldSmith86** [comment]
You're missing a `]`.

**Comment by bjalder26** [comment]
> You're missing a `]`.

I assume you're talking about me.  Yeah, I caught that after posting and deleted the message.

**Comment by robartsd** [comment]
I had a paste in the JSON editor crash the client using Chrome 91 on Linux.

**Comment by ArnoldSmith86** [comment]
Superseded by #547.

**Pull request closed without merging**
