### PR TITLE
A few minor scoreboard updates/fixes

### PR DESCRIPTION
**Pull request by rogerl50**
- [X] Set text of Totals from the `totalsLabel` property, initial value `Totals`.
- [x] Move `Add scoreboard` into the interactive widgets column in the add widget overlay.
- [x] Add appropriate icon to `Add scoreboard` button.
- [x] Add scoreboard to `editor.js` testCafe test.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1505/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1505-pr-test`.

**Comment by rogerl50** [comment]
In order to make room for `Add Scoreboard` in the interactive page as well as a potentially upcoming Seat plus Counter, I removed the 20 spinner.

**Comment by 96LawDawg** [comment]
Trying to update the TestCafe I got this error:

```The action target (<button class="ui-button" id="addScoreboard">Add Sco...</button>) is invisible. 
      It descends from an element that has the 'display: none' property (<div id="addOverlay" class="overlay" style="display: none;">...</div>).```

I was expecting it to just give me a new hash.  This is the same error I got when trying to add a new seat + counter button.  Help.

**Comment by ArnoldSmith86** [comment]
Gotta do `.click('#addButton')` before your line. That's the "Add widget" toolbar button to open the overlay again.

**Comment by 96LawDawg** [comment]
I have no idea why the scoreboard tutorial library image doesn't work here.  It works on production and on my local copy of this branch.  I'm done messing with it.

**Review by 96LawDawg — APPROVED** [review]
Tested the new `totalsLabel`.  Works as expected.  Everything else is UI or TestCafe.  Approved.

**Review by flackr — APPROVED** [review]
Looks good to me.

**Comment by 96LawDawg** [comment]
A few minor things broke during the merge from main.  Fixed those.  Should be ready to go @rogerl50.

**Pull request merged**
