### PR TITLE
log multiple routine calls if they happen with the same mouse interaction

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
So you can see all your `changeRoutine`s and `globalUpdateRoutine`s fire a hundred times when you move a card around...

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3989/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
> So you can see all your `changeRoutine`s and `globalUpdateRoutine`s fire a hundred times when you move a card around...

Should we limit to click, onEnter, onLeave, onPileCreation and timers?

Also maybe not related to this PR but we should include a message in degub on changing faces that states that the properties do not trigger change routines

**Comment by ArnoldSmith86** [comment]
> Should we limit to click, onEnter, onLeave, onPileCreation and timers?

Why?

**Comment by RaphaelAlvez** [comment]
> > Should we limit to click, onEnter, onLeave, onPileCreation and timers?
> 
> Why?

Not sure. Didn't test it yet. It was only bases on your own impression

**Comment by RaphaelAlvez** [comment]
It seems to be working properly.

Do you think you could include some sort in visual identification of whether the routine came from the original "button" or not?
maybe using the icon [icon-redo]?

But keeping the correct trigger order.

just a QOL thing.

**Review by 96LawDawg — APPROVED** [review]
This works great.  I wish I had thought to do some of the debugging for Capture the Flag here.  I have multiple enter and leave routines going on but when I added a 3 second timer is when things got weird.  First image from production.  Second image from the PR.  Definitely works and definitely better than what we have.  Approved through test.
Production

PR

**Pull request merged**
