### PR TITLE
apply cardDefaults to DOM if delta contains deck property

### LINKED ISSUE #1151: `classes` in `cardDefaults` do not get applied by the initial delta
Setting `classes` in `cardDefaults` does not apply the classes to the card unless the deck gets opened in the JSON editor. I discovered this issue when attempting to build a deck in which I wanted all the card types except one to have a particular class. Setting `classes` in each card type does work.

### PR DESCRIPTION
**Pull request by robartsd**
Fixes #1151

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1194/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
It might be more efficient to use Object.assign() to merge properties from `cardDefaults` with properties from `cardTypes` then iterate over the combined object.

**Comment by robartsd** [comment]
@96LawDawg 's exampe from #1193 loaded to https://test.virtualtabletop.io/PR-1194/Crow

**Review by ArnoldSmith86 — APPROVED** [review]
Code looks fine. Fingers crossed.

**Comment by robartsd** [comment]
> Code looks fine. Fingers crossed.

I believe it has been in the automatic beta server for months.

**Comment by ArnoldSmith86** [comment]
Sure. Are you using those? :smile:

**Pull request merged**
