### PR TITLE
Update Audio Tutorial (minor fixes and player arrays)

### PR DESCRIPTION
**Pull request by bjalder26**
---

PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2375/pr-test (or any other room on that server)

### CODE REVIEW

**Comment by bjalder26** [comment]
I did something wrong.  I'll get some help.

**Comment by 96LawDawg** [comment]
Do you want to just add an updated tutorial to your audio PR?

**Comment by bjalder26** [comment]
> Do you want to just add an updated tutorial to your audio PR?

That would be fine, but somehow I botched it.

**Comment by 96LawDawg** [comment]
Wrong thread.

**Pull request closed without merging**
