### PR TITLE
fixed that setting activeFace in BasicWidgets would copy the properties of the face to the base state

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
It was never intended that the properties of the currently active BasicWidget face get copied to the widget base state. Instead they should just be _active_ like it works for card faces.

Please do some tests when the properties are actually defined in the base and the faces.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3536/pr-test (or any other room on that server)

**Review by robartsd — APPROVED** [review]
Code looks good to me.

**Review by robartsd — CHANGES_REQUESTED** [review]
Base properties are not restored to DOM when changing away from a face that overrides them.

In test room I added a checker piece that sets color on face 0 and sets classes on face 1. On reload the DOM reflects the active face properties, but once the face properties are applied they are never unapplied.

Best practice has always been to apply all face properties to all faces and this appears to behave the same as current production until state is reloaded. On reload, the active properties returned by get() are represented in the DOM which can cause DOM state in different clients to be different. If no reload occurs then this appears to work as current production regarding changing only properties that occur in the face that was just activated.

**Comment by 96LawDawg** [comment]
The latest commit broke this test server.

**Comment by 96LawDawg** [comment]
Fixed now.  Thanks.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  I created a basic widget and set bunches of different properties on a couple of different faces.  Things like css, grid, fixed coordinates, size, etc.  On face change, none of those properties got copied to the base widget properties; they were just active on the face.

**Comment by ArnoldSmith86** [comment]
I'm pretty sure this needs major changes in order to not change game behavior.

I still want this though because in combination with `inheritFrom` it would be _way_ cleaner.

**Comment by ArnoldSmith86** [comment]
I have to look at your changes more closely. At first sight I don't know what you're doing. I'll need a little time.

Keep in mind though that we can't change behavior in production.

**Comment by robartsd** [comment]
> Keep in mind though that we can't change behavior in production.

Not possible; but best practice has always been to set all face linked properties on all faces. Games that followed best practices will see no change in behavior.

**Comment by ArnoldSmith86** [comment]
Sure it's possible.

**Comment by robartsd** [comment]
> Sure it's possible.

No, current behavior always copies the property from the face. Unless we continue to copy the property to the base we will change behavior for any game that has not followed the best practice of setting all face linked properties on all faces. This cannot be solved unless we set up a "legacy" mode for handling faces.

**Comment by 96LawDawg** [comment]
> No, current behavior always copies the property from the face. Unless we continue to copy the property to the base we will change behavior for any game that has not followed the best practice of setting all face linked properties on all faces. This cannot be solved unless we set up a "legacy" mode for handling faces.

That actually makes sense to me.  That sounds right.

**Comment by ArnoldSmith86** [comment]
Yes. Some kind of legacy mode is needed. Or just the old behavior if best practices were not followed.

**Comment by ArnoldSmith86** [comment]
I'm pretty sure you're basically right though.

I couldn't come up with a solution yet that's better than basically just adding a separate feature (something like `referenceFaces`). Even when all faces have the same properties.

I'm pretty sure that's not worth it. Such a pity that I didn't fix this shortly after implementing it.

**Comment by robartsd** [comment]
Perhaps fileUpdater can add a activeFaceChangeRoutine that implements legacy mode if updating a file that does not comply with best practices. We might be able to avoid a legacy mode directly in the engine.

**Comment by robartsd** [comment]
New behavior will allow routines to SET properties that are currently presenting values from the active face. The property will be set in the base, but the value will not be represented in the DOM or returned by GET until the face changes to a face that does not have the property. Might be useful to have a mode for SET that can set the value on the active (or even a specified) face rather than the base. I think under old behavior SET would succeed in changing the current value of the property, but the value would get overwritten when the face changes.

**Comment by ArnoldSmith86** [comment]
> Perhaps fileUpdater can add an activeFaceChangeRoutine that implements legacy mode if updating a file that does not comply with best practice.

The problem is that that is not enough. Even when best practices are followed, there is the case when `activeFace` is set to something that is not a valid key in `faces`.

Currently that leads to `activeFace` being set to an "invalid" value and the widget uses the values that were copied last time.

If we don't accept invalid values for `activeFace`, it would change behavior for routines that read `activeFace`. As a solution we could save the other value we need in a new property.

I just don't think that the current behavior is bad enough to warrant such a mess. IMHO we should just close this PR and forget about it. :smile:

**Comment by robartsd** [comment]
> I just don't think that the current behavior is bad enough to warrant such a mess. IMHO we should just close this PR and forget about it.

We do need to prevent the JSON editor from creating new classes in the base as a class is being added to the active face. I think we can preserve current results of get() while mostly not copying properties to base for games that follow best practice. Continue checking face as part of getDefaultValue(); then on face change:
1. copy properties from old face to base if they don't exist in new face
2. change activeFace
3. copy properties from new face to base only if get() returns a different value for the property

**Comment by ArnoldSmith86** [comment]
I'll close this. Feel free to reopen it if you want to test an implementation you have in mind.

**Comment by robartsd** [comment]
> I'll close this. Feel free to reopen it if you want to test an implementation you have in mind.

I might start from main with the ideas above; but I agree, it is not yet time to delete the branch.

**Comment by robartsd** [comment]
I think this is causing crashes on beta.
```javascript
  applyDeltaToDOM(delta) {
    this.applyCSS(delta);
    if(delta.z !== undefined)
      this.applyZ(true);

    if(delta.movable !== undefined)
      this.isDraggable = this.get('movable');

    if(delta.parent !== undefined) {
      if(this.parent)
        this.parent.applyChildRemove(this);

      if(delta.parent === null)
        $('#topSurface').appendChild(this.domElement);
      else
        widgets.get(this.get('parent')).domElement.appendChild(this.domElement);
```
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'domElement')
    at Card.applyDeltaToDOM (BicycleIndividual:2819)
    at Card.applyDeltaToDOM (BicycleIndividual:4356)
    at Card.applyDelta (BicycleIndividual:2274)
    at receiveDelta (BicycleIndividual:277)
    at sendDelta (BicycleIndividual:298)
    at addWidgetLocal (BicycleIndividual:365)
    at Holder.evaluateRoutine (BicycleIndividual:3190)
    at Holder.evaluateRoutine (BicycleIndividual:3467)
    at Card.onPropertyChange (BicycleIndividual:3863)
    at async Card.set (BicycleIndividual:2314)
```

**Comment by ArnoldSmith86** [comment]
Superseded by #1665.

**Pull request closed without merging**
