### PR TITLE
Fix crash on SORT with empty collection. Also fix a typo.

### PR DESCRIPTION
**Pull request by rogerl50**

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3718/pr-test (or any other room on that server)

**Review by bjalder26 — APPROVED** [review]
Fixes a typo and a known bug

**Comment by bjalder26** [comment]
It appears to have fixed that issue.  Good job finding it.

**Comment by rogerl50** [comment]
> It appears to have fixed that issue. Good job finding it.

This is why I really wanted a code review...but in any case. This was leftover code that should not have been there.

**Comment by bjalder26** [comment]
> > It appears to have fixed that issue. Good job finding it.
> 
> This is why I really wanted a code review...but in any case. This was leftover code that should not have been there.

I have an automated test room (which I should be using on each of these), but funny enough sorting a collection was not part of the room, so when I tried it now it missed it anyway.  I'll add that, and start testing all these PRs with it.

**Comment by rogerl50** [comment]
> > > It appears to have fixed that issue. Good job finding it.
> > 
> > 
> > This is why I really wanted a code review...but in any case. This was leftover code that should not have been there.
> 
> I have an automated test room (which I should be using on each of these), but funny enough sorting a collection was not part of the room, so when I tried it now it missed it anyway. I'll add that, and start testing all these PRs with it.

I had the same problem. I had a test room that tested lots of functions with various parameters so that I could look at the logging information during development. Somehow I missed that branch as well.

**Comment by rogerl50** [comment]
> > > It appears to have fixed that issue. Good job finding it.
> > 
> > 
> > This is why I really wanted a code review...but in any case. This was leftover code that should not have been there.
> 
> I have an automated test room (which I should be using on each of these), but funny enough sorting a collection was not part of the room, so when I tried it now it missed it anyway. I'll add that, and start testing all these PRs with it.

You should add that test room to the standard set of node.js tests.

**Comment by bjalder26** [comment]
> > I have an automated test room (which I should be using on each of these), but funny enough sorting a collection was not part of the room, so when I tried it now it missed it anyway. I'll add that, and start testing all these PRs with it.
> 
> You should add that test room to the standard set of node.js tests.

I put in a PR for virtualtabletop-library to add the .vtt file, and a corresponding PR to add a click to tests.js.  I hope that was the right thing to do.

**Pull request merged**
