### PR TITLE
Adds thenBreak elseBreak thenEnd & elseEnd to IF

### PR DESCRIPTION
**Pull request by bjalder26**
This might be overkill, but I thought I'd rather do more and reduce it later than the other way around because this way people can see/try everything.

This PR adds `thenBreak` `elseBreak` `thenEnd` & `elseEnd` parameters to the `IF` function.  If the `IF` function evaluates for true, then if `thenBreak` is set to true, the current routine will stop, or if `thenEnd` is set to true, all routines will stop.  If the `IF` function evaluates for false, then if `elseBreak` is set to true, the current routine will stop, or if `elseEnd` is set to true, all routines will stop.

* thenBreak: _true/false_ - the current routine stops executing if the condition is evaluated as true
* elseBreak: _true/false_ - the current routine stops executing if the condition is evaluated as false
* thenEnd: _true/false_ - all routines stop executing if the condition is evaluated as true
* elseEnd: _true/false_ - all routines stop executing if the condition is evaluated as false

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3926/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
That's basically the same PR I did except you introduced `condition` as an inverted alias for `skip`.

**Comment by bjalder26** [comment]
> That's basically the same PR I did except you introduced `condition` as an inverted alias for `skip`.

Yes, which is why I said it was by the magic of copy/paste/edit.  However, as compared to skip, this terminates the routine, whereas skip just skipped a function (if I can still recall correctly).

I think it gets rid of the need to nest it in an IF/thenRoutine, which allows it to terminate the clickRoutine or changeRoutine.  However, perhaps that is not what is desired.  Perhaps, what is desired is a function that terminates all Routines.

IMHO, this acts a lot like BREAK does in JavaScript.

**Comment by rogerl50** [comment]
If we are going to go this route, why not allow `BREAK` to take parameters like `IF` does? So either a `condition` or two operands and a relation? (Also, you might consider renaming it to `BREAKIF`, which is a little more descriptive but clumsy.)

**Comment by ArnoldSmith86** [comment]
At that point we could just add a `elseBreak` parameter to `IF`.

**Comment by bjalder26** [comment]
> At that point we could just add an `elseBreak` parameter to `IF`.

That's probably a better approach if we're going to have operands.  I was also thinking it might be possible to have another parameter to completely stop all routines.  I figure it could do the same thing except also set a variable that makes it keep breaking until all the routines are 'done'.  I'm not sure if that is desired though.

Would it make sense to have a `thenBreak` as well?

**Review by ArnoldSmith86 — CHANGES_REQUESTED** [review]
As far as I can tell, you made it only work for `clickRoutine`s? Any other routines would cause all future routines to not execute until a `clickRoutine` finishes.

Also using `this.end`/`this.break` only works inside one widget. An `end` inside a `CALL`ed routine of a different widget would not do what I would expect.

**Comment by bjalder26** [comment]
> At that point we could just add an `elseBreak` parameter to `IF`.

I updated it to be parameters for IF.  However, I may have overdone it.

**Comment by bjalder26** [comment]
> As far as I can tell, you made it only work for `clickRoutine`s? Any other routines would cause all future routines to not execute until a `clickRoutine` finishes.
> 
> Also using `this.end`/`this.break` only works inside one widget. An `end` inside a `CALL`ed routine of a different widget would not do what I would expect.

Oh, that's not good.

**Comment by bjalder26** [comment]
> As far as I can tell, you made it only work for `clickRoutine`s? Any other routines would cause all future routines to not execute until a `clickRoutine` finishes.
> 
> Also using `this.end`/`this.break` only works inside one widget. An `end` inside a `CALL`ed routine of a different widget would not do what I would expect.

I think that's fixed.  This may still be overkill.  There will still be leaveRoutine issues involving double triggering.

**Review by ArnoldSmith86 — COMMENTED** [review]
I feel like the proper way to implement this would be to return `true` or `false` from `evaluateRoutine` and change the calls to `if(evaluateRoutine(...)) break`.

Unless you found something where that doesn't work.

**Comment by bjalder26** [comment]
> I feel like the proper way to implement this would be to return `true` or `false` from `evaluateRoutine` and change the calls to `if(evaluateRoutine(...)) break`.
> 
> Unless you found something where that doesn't work.

I would not be surprised if there is a better solution, it seems like you're saying I could get rid of one or both of the variables, but I don't understand the solution you're proposing.

The way I have it set up it breaks out of the  `for(const original of routine)` if told to "break", and continues to do so if told to "end".  Sounds like you're describing a different solution than that, and if I figure it out, then I'll make the changes.  However, if anyone else wants to push changes (or open another PR), then feel free.

**Comment by rogerl50** [comment]
- It also seems to me that it might be simpler to implement this almost wholly within widget.js by setting `breakRoutine` and `endRoutine` to `null` at the start of `evaluateRoutine` if the nesting depth is zero, returning a boolean from `evaluateRoutine`, and using that to break out of the loop if appropriate. At the end of the loop you can check which of the variables was set and act appropriately. I *think* you could avoid the changes in `set` and `dispenseCard`, for example, if it worked this way.
- This seems complicated to me. Would it be simpler and just as effective (at the cost of a bit more syntax) to say
```
  {"func": "IF",
   "condition": "..."
   "thenRoutine": [
       { "func": "BREAK" }
   ]
  }
```
That way we just add two new functions, `BREAK` and `END`, and avoid the confusing (in my mind) necessity to provide values for `thenBreak` and `elseBreak`. You might lose a little flexibility here in the event that you wanted to write
```
  "elseBreak": "${var}"
```
but that really seems like an edge case to me, and you could fix it with an inner `IF`.

**Comment by bjalder26** [comment]
> * It also seems to me that it might be simpler to implement this almost wholly within widget.js by setting `breakRoutine` and `endRoutine` to `null` at the start of `evaluateRoutine` if the nesting depth is zero, returning a boolean from `evaluateRoutine`, and using that to break out of the loop if appropriate. At the end of the loop you can check which of the variables was set and act appropriately. I _think_ you could avoid the changes in `set` and `dispenseCard`, for example, if it worked this way.

I don't understand.  Maybe I should just close this PR.

**Comment by bjalder26** [comment]
I think I figured it out last night.  I'll see if I can make the changes later.

**Comment by bjalder26** [comment]
> * This seems complicated to me. Would it be simpler and just as effective (at the cost of a bit more syntax) to say
> 
> ```
>   {"func": "IF",
>    "condition": "..."
>    "thenRoutine": [
>        { "func": "BREAK" }
>    ]
>   }
> ```
> 
> That way we just add two new functions, `BREAK` and `END`, and avoid the confusing (in my mind) necessity to provide values for `thenBreak` and `elseBreak`. You might lose a little flexibility here in the event that you wanted to write
> 
> ```
>   "elseBreak": "${var}"
> ```
> 
> but that really seems like an edge case to me, and you could fix it with an inner `IF`.

I think the issue there is that you would only be breaking out of the thenRoutine.

**Comment by rogerl50** [comment]
> > * This seems complicated to me. Would it be simpler and just as effective (at the cost of a bit more syntax) to say
> > 
> > ```
> >   {"func": "IF",
> >    "condition": "..."
> >    "thenRoutine": [
> >        { "func": "BREAK" }
> >    ]
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That way we just add two new functions, `BREAK` and `END`, and avoid the confusing (in my mind) necessity to provide values for `thenBreak` and `elseBreak`. You might lose a little flexibility here in the event that you wanted to write
> > ```
> >   "elseBreak": "${var}"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but that really seems like an edge case to me, and you could fix it with an inner `IF`.
> 
> I think the issue there is that you would only be breaking out of the thenRoutine.

You are right.

**Comment by bjalder26** [comment]
> I feel like the proper way to implement this would be to return `true` or `false` from `evaluateRoutine` and change the calls to `if(evaluateRoutine(...)) break`.
> 
> Unless you found something where that doesn't work.

I've tried to understand this suggestion and do not.  Can you explain it in more detail?

**Comment by rogerl50** [comment]
> > I feel like the proper way to implement this would be to return `true` or `false` from `evaluateRoutine` and change the calls to `if(evaluateRoutine(...)) break`.
> > Unless you found something where that doesn't work.
> 
> I've tried to understand this suggestion and do not. Can you explain it in more detail?

I think the idea is as follows: you are using `endRoutine` to communicate between one level of call and the previous. The proposal is essentially to replace this flag by a return value from `evaluateRoutine`. So each call to `evaluateRoutine` would be replaced by something like `if (!evaluateRoutine(args)) return false`, and the code in widget.js which processes the `elseEnd` and `thenEnd` would return the appropriate value. (`breakRoutine` is handled largely within one invocation of `evaluateRoutine` and can likely remain largely as you have it.) I'm sure there is more complexity than this to actually get it to work, but that's the overall idea as I understand it.

**Comment by bjalder26** [comment]
> I think the idea is as follows: you are using `endRoutine` to communicate between one level of call and the previous. The proposal is essentially to replace this flag by a return value from `evaluateRoutine`. So each call to `evaluateRoutine` would be replaced by something like `if (!evaluateRoutine(args)) return false`, and the code in widget.js which processes the `elseEnd` and `thenEnd` would return the appropriate value. (`breakRoutine` is handled largely within one invocation of `evaluateRoutine` and can likely remain largely as you have it.) I'm sure there is more complexity than this to actually get it to work, but that's the overall idea as I understand it.

I was thinking that this at the beginning of the evaluateRoutine:
```js
if(endRoutine){
        return false;
      }
```
And changing the calls to evaluateRoutine (that come from within evaluateRoutine) from something like 
```js
await this.evaluateRoutine(a[branch], variables, collections, (depth || 0) + 1, true)
```
to something like this:
```js
if(!await this.evaluateRoutine(a[branch], variables, collections, (depth || 0) + 1, true)) break;
```
would work, but when I try that with FOREACH and CALL it breaks everything and the server won't load.

FOREACH
```js
await this.evaluateRoutine(a.loopRoutine, variables, collections, ((depth || 0) + 1), true)
```

CALL
```js
const result = await widgets.get(a.widget).evaluateRoutine(a.routine, inheritVariables, inheritCollections, (depth || 0) + 1);
```
Maybe I am completely misunderstanding though.

**Comment by bjalder26** [comment]
> I think the idea is as follows: you are using `endRoutine` to communicate between one level of call and the previous. The proposal is essentially to replace this flag by a return value from `evaluateRoutine`. So each call to `evaluateRoutine` would be replaced by something like `if (!evaluateRoutine(args)) return false`, and the code in widget.js which processes the `elseEnd` and `thenEnd` would return the appropriate value. (`breakRoutine` is handled largely within one invocation of `evaluateRoutine` and can likely remain largely as you have it.) I'm sure there is more complexity than this to actually get it to work, but that's the overall idea as I understand it.

I couldn't make any progress on that and decided to give up after numerous tries.  Nothing I tried came anywhere near working at all.

**Comment by ArnoldSmith86** [comment]
A big question is also: if a routine does a `SET` which in turn triggers a `changeRoutine`, should a `thenEnd` cancel the initial routine or just the `changeRoutine`?

**Comment by bjalder26** [comment]
> A big question is also: if a routine does a `SET` which in turn triggers a `changeRoutine`, should a `thenEnd` cancel the initial routine or just the `changeRoutine`?

Yeah, I raised the same question regarding globalUpdateRoutines.  `"I'm also not sure how "end" should relate to globalUpdateRoutines."`.  

As is, I believe `thenBreak` ends the current routine (which could be a `thenRoutine` or an `elseRoutine`, whereas `thenEnd` ends the entire clickRoutine, changeRoutine, globalUpdateRoutine, leaveRoutine, or enterRoutine that it is inside of.  I believe `thenBreak` will end a called Routine and return to the routine that called it, whereas `thenEnd` will end all the called routines then end the clickRoutine, changeRoutine, globalUpdateRoutine, leaveRoutine, or enterRoutine of the original calling routine.

Also currently a changeRoutine, globalUpdateRoutine, leaveRoutine, or enterRoutine that contains a `thenEnd` won't end the routine that caused the change that triggered the routine.

I'm not 100% sure how it 'should work', nor am I 100% sure `thenEnd` and `elseEnd` are needed.  I suppose it would be possible to use `thenBreak` everywhere you want.

Maybe someone else has a more clear idea of how it should work when making a real game.

**Comment by rogerl50** [comment]
Is there a use case for `thenEnd`/`elseEnd`?

**Comment by bjalder26** [comment]
I suspect this would be better addressed with a CALL that doesn't return under certain circumstances.

**Comment by 96LawDawg** [comment]
> I suspect this would be better addressed with a CALL that doesn't return under certain circumstances.

That is probably as good a solution as any and will work in most cases.  But not currently if CALLing from an enterRoutine.  See bug in #2078.

**Pull request closed without merging**
