### PR TITLE
Fixes Corners on Cards

### LINKED ISSUE #240: Unexpected behavior in drawing corners on cards
Tonight in my poker game, I noticed square corners on cards that I don't think had ever been there before.  I brought it up to the other players, and we identified that different people were seeing different things.  The first screen shot is from my computer.  Notice the square corners on cards 2,4,5 (counting from the left) and rounded corners on the other cards.  The second screenshot is from another player of the SAME cards.  Notice the square corners on cards 2,3,4 and rounded corners and 1 and 5.

As I said, as best I can remember, this is new since the last time I played last week (February 23).

Version 1

Version 2

### PR DESCRIPTION
**Pull request by 96LawDawg**
Fixes card corner visibility errors caused by PR#226. Closes #240.

I acknowledge robartsd's comments about needing to understand this better and looking for a better solution. However, this band-aid solution will work in the interim. Playing with those card corners is very visually distracting.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3241/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
The test room has an example of how the cards no longer have the ugly corners.  It also demonstrates that the good change from PR#226 (not hiding card child widgets) is still in place.

**Comment by 96LawDawg** [comment]
I would also note that github automatically assigned Raphael as a reviewer.  Is the css code owner limit still in place or was this caused by something else?

**Comment by 96LawDawg** [comment]
Through testing in the meeting today, we saw that children of cards will not be displayed off the card with ```overflow:hidden``` set.  So probably some other solution is needed to allow for children to be visible at or near the edge of the card.

**Comment by 96LawDawg** [comment]
I am closing this because this PR is such a mess.  I just cannot easily handle multiple PRs open at the same time.  This fix, or something like it is still needed.  But I'm going to focus on the library.

**Pull request closed without merging**
