### PR TITLE
Update to shape sorter

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
- adds border a border to the pieces
- changes colors to palete for color blindness
- new shift widget. now supports piles

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1480/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1480-pr-test`.

**Comment by ArnoldSmith86** [comment]
How did you do the update? It didn't update `lastUpdate` successfully.

**Comment by RaphaelAlvez** [comment]
> How did you do the update? It didn't update `lastUpdate` successfully.

Update from room state

**Comment by 96LawDawg** [comment]
You need to make the reset button press "shiftCenter."  That is essential.

And you may want to add the stuff to make the seat prompt for a real name instead of Guest.  I don't usually bother with that in my games, but a lot of people do.  Up to you.

Otherwise, looks good.

**Comment by RaphaelAlvez** [comment]
> You need to make the reset button press "shiftCenter."  That is essential.

Thanks will do

> And you may want to add the stuff to make the seat prompt for a real name instead of Guest.  I don't usually bother with that in my games, but a lot of people do.  Up to you.

Where do I get this?

**Comment by RaphaelAlvez** [comment]
> How did you do the update? It didn't update `lastUpdate` successfully.

@ArnoldSmith86 is this a problem. Should I change anything or just a small bug.

**Comment by 96LawDawg** [comment]
> Where do I get this?

Just put this in the seat clickRoutine:

```
 "var playerPrefix = substr ${playerName} 0 5",
   {
      "func": "IF",
      "operand1": "${playerPrefix}",
      "operand2": "Guest",
      "thenRoutine": [
        {
          "func": "INPUT",
          "fields": [
            {
              "type": "title",
              "text": "Enter your name"
            },
            {
              "type": "string",
              "label": "Name",
              "variable": "playerName",
              "value": "${playerName}"
            }
          ]
        }
      ]
    },
    {
      "func": "CLICK",
      "collection": "thisButton",
      "mode": "ignoreClickRoutine"
    }
```

**Comment by ArnoldSmith86** [comment]
> > How did you do the update? It didn't update `lastUpdate` successfully.
> 
> @ArnoldSmith86 is this a problem. Should I change anything or just a small bug.

I'll take care of it. It's not a problem though. It just means that the game won't be at the front when sorting the library by latest change.

**Comment by 96LawDawg** [comment]
The reset button still doesn't work.  Steps to reproduce:

1. Put pieces on board.
2. Use shift buttons to move away from center.
3. Press reset
4. Place new pieces
5. Press center (eye) button.

**Review by 96LawDawg — APPROVED** [review]
Approved through test

**Pull request merged**
