### PR TITLE
Font and class additions to add personality to your games.

### PR DESCRIPTION
**Pull request by mousewax**
image

Added or updated the following classes for fonts. All current games that use fonts are unaffected. There should be no discernible difference in any games. This update merely makes fonts available to designers should they want them.

All of the fonts are from Google Fonts and have the same license as Roboto.

.standard_font, .font-standard, .font-roboto, .font-sans-serif
**.condensed_font, .font-condensed, .font-roboto-condensed
.serif_font, .font-serif
.fantasy_font, .font-fantasy
.gothic_font, .font-gothic
.horror_font, .font-horror
.tech_font, .font-tech**
.symbols, .font-vtt-symbols, .font-symbols
.handwriting_font, .font-handwriting
.handwriting_casual_font, .font-handwriting-casual

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4056/pr-test (or any other room on that server)

**Comment by rogerl50** [comment]
How would these be used in code? Would it be for example `"classes":"serif_font"`?

**Comment by mousewax** [comment]
> How would these be used in code? Would it be for example `"classes":"serif_font"`?

That is correct. Identically to the other font options already available.

**Review by 96LawDawg — APPROVED** [review]
Approved through test and code review.

**Pull request merged**
