### PR TITLE
added pre-defined variables seatIndex, seatID and collection playerSeats

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Implements #1397. It adds two variables and one collection that are available in every routine.

The new variable `seatID` contains the `id` of the first seat the active player is sitting in and the variable `seatIndex` contains the `index` of that seat. If the player does not sit in any seat, the variables are set to `null`.

The collection `playerSeats` contains all seat widgets the player is currently sitting in.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1400/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1400-pr-test`.

**Comment by 96LawDawg** [comment]
What if one of those variable names is already in use in the room for something else?  Don't you need a file updater to address that?

**Comment by 96LawDawg** [comment]
For the wiki, I recommend removing the 2 short paragraphs under the Routines section of the Functions, Automation, and Routines page.  Create a new section right before Predefined-Routines that is Predefined Variables and Collections.  Then add these new ones there.  Here is what that would look like.  

------------------------------

## Routines

A routine is a sequence of operations that is executed when a specific action happens. There are several kinds of predefined routines, and you can also define arbitrary routines (all of which must end in the string _Routine_) for use with the [CALL](#call) function. The predefined routine names are discussed in more detail [below](#predefined-routines).

An operation is either an invocation of one of the functions listed above, and detailed below, or it is a `"var"` statement. `"var"` statements and the dynamic expressions used below are employed to define and use variables inside a routine. They are described in detail in the section on [[Dynamic Expressions]].

Many routines operate on a collection of widgets (which may, of course, contain just a single widget). [Collections](#collections) are discussed further below.

Here's what flipping the top card of a holder to its back side ("face") would look like in a button:

```JS
{
  "type": "button",
  "text": "Flip holder",
  "clickRoutine": [
    {
      "func": "FLIP",
      "holder": "<holderID>",
      "count": 1,
      "face": 0
    }
  ],
  "x": 758,
  "y": 721,
  "z": 11,
  "id": "2zye"
}
```

Each operation needs to be told the specific context in which it operates, so if you wanted to flip AND rotate the top card of a holder, the _clickRoutine_ would be:

```JS
{
  "func": "FLIP",
  "holder": "<holderID>",
  "count": 1,
  "face": 0
},
{
  "func": "ROTATE",
  "holder": "<holderID>",
  "count": 1,
  "angle": 90
}
```

Oftentimes, you want to work with several items at once, like moving the entire card pile or dealing cards to multiple hands/holders. To this effect, some functions allow you to specify a _collection_ or a _holder_ parameter.

* Use the _holder_ parameter when you want to work with the _content_ of one or more holders
* Use the _collection_ parameter when you want to work with the widgets themselves, rather than their content

To illustrate the difference:

```JS
//Rotate the content of a holder, leaving the holder as-is
{
    "func": "ROTATE"
    "holder": "<holderID>"
    "angle": 90
}

//Rotate the holder itself
{
    "func": "SELECT",
    "property": "id",
    "value": "<holderID>"
},
{
    "func": "ROTATE"
    "angle": 90
}

//Note that this is not working code, but just an illustration of principles
```

When working with holders, it is important to understand the concept of `dropTarget`: By default, a holder only allows Cards to be dropped into the holder. You can set `dropTarget` to some other criterion, or to empty in order to have the holder accept any type of widget. When using button operations that operate on a holder as a source (e.g. [FLIP](#flip), [MOVE](#move), etc.), only those widgets that match the `dropTarget` are affected, leaving the other widgets inside the holder (where they could still be affected by players). You can also set `dropTarget` to a value that does not occur, thus preventing any drops into the holder.

If you'd like to better understand a routine, you can get detailed execution information as part of the JSON editor. The JSON editor is accessed by pressing Ctrl-J; an editor tutorial is available [here](https://virtualtabletop.io/#%7B%0A%20%20%22load%22%3A%20%22https%3A%2F%2Fvirtualtabletop.io%2Flibrary%2FTutorial%20-%20JSON%20User%20Guide.vtt%23VTT%22%0A%7D). At the bottom left of the window you will see the legend _Show Routine Debug Output_. Moving a pointer over this text will reveal a tree-formatted trace of all functions performed during the last routine execution (often but not always a button press). Each line marked with a triangle can be clicked to expand or compress its contents. For most functions, you can also view the original text of the JSON as well as the text after any variable substitutions (e.g. `${x}`) have been performed, as well as the contents of all variables and collections after execution completes. For functions such as _IF_, _FOREACH_, _CALL_, and _CLICK_, as well as in certain other situations (such as `enterRoutines` being invoked) the expanded text will itself include a list of functions performed by that operation (e.g., in the case of _FOREACH_, the `loopRoutine` executions).

Previously, debugging was done using the _debug_ property of each widget. The _debug_ property is no longer a predefined property and will have no effect on the execution of your game.

### Predefined-Routines

Each routine begins with a number of predefined variables:
* `activePlayers` - list of active players' names in room
* `playerName` - name of the player clicking the widget
* `playerColor` - color of player clicking the widget
* `seatID` - `id` of the first seat the active player is in. Set to `null` if the player is not in a seat
* `seatIndex` - the index number of the `seatID`. Set to `null` if the player is not in a seat
* `thisID` - _id_ of the widget that contains the routine

Each routine begins with a predefined collection:
* `thisButton` - a collection consisting of the widget that contains the routine
*  `playerSeats` - a collection consisting of all the seat `id`s that the active player is in

### Predefined-Routines
... [continue the rest of the entry as is]

**Comment by robartsd** [comment]
> What if one of those variable names is already in use in the room for something else? Don't you need a file updater to address that?

I believe that these variables are simply initialized with these values. Setting them in a routine should override the initial value, so a fileupdater would not be needed.

**Comment by robartsd** [comment]
> > What if one of those variable names is already in use in the room for something else? Don't you need a file updater to address that?
> 
> I believe that these variables are simply initialized with these values. Setting them in a routine should override the initial value, so a fileupdater would not be needed.

Okay, there could be a problem - called routines do not get the updated variables and collections, they get reinitialized versions.

**Comment by 96LawDawg** [comment]
So all this needs then is a file updater, right?  I took a stab at that.  This will conflict with #1436 as I currently have that slated as v9, but whichever one goes first doesn't really matter.  Just change a digit.

**Comment by 96LawDawg** [comment]
Well, the file updater didn't work.  It broke the test room.  I have no idea what I did wrong.  I copied what @ArnoldSmith86 and I came up with for a file updater in #1436.  Same concept here.  Oh well.  I'll leave it alone, but anyone who is competent can look at it and maybe fix it and get this PR ready to go.

**Comment by ArnoldSmith86** [comment]
> Okay, there could be a problem - called routines do not get the updated variables and collections, they get reinitialized versions.

We have this problem for every new preset variable and collection. Would it be solved by doing this instead for new ones?

```Javascript
      variables = Object.assign({
        seatIndex: playerSeats.length ? playerSeats[0].get('index') : null,
        seatID: playerSeats.length ? playerSeats[0].get('id') : null
      }, initialVariables, {
        playerName,
        playerColor,
        activePlayers,
        thisID : this.get('id')
      });
      collections = Object.assign({
        playerSeats
      }, initialCollections, {
        thisButton : [this]
      });
```

The behavior of the current variables shouldn't change, of course, so they are applied after `initialVariables` like before.

**Comment by robartsd** [comment]
> > Okay, there could be a problem - called routines do not get the updated variables and collections, they get reinitialized versions.
> 
> We have this problem for every new preset variable and collection. Would it be solved by doing this instead for new ones?
> 
> ```js
>       variables = Object.assign({
>         seatIndex: playerSeats.length ? playerSeats[0].get('index') : null,
>         seatID: playerSeats.length ? playerSeats[0].get('id') : null
>       }, initialVariables, {
>         playerName,
>         playerColor,
>         activePlayers,
>         thisID : this.get('id')
>       });
>       collections = Object.assign({
>         playerSeats
>       }, initialCollections, {
>         thisButton : [this]
>       });
> ```
> 
> The behavior of the current variables shouldn't change, of course, so they are applied after `initialVariables` like before.

This looks like a workable solution to me.

**Review by RaphaelAlvez — APPROVED** [review]
Approved by code review and testing.

I suggest adding playerSeats to collections on JSON editor

**Comment by 96LawDawg** [comment]
Updated the draft wiki entry to account for the changes since this started (adding in `activeColors` and `mouseCoords`).

**Comment by robartsd** [comment]
I changed these to be added before the initialVariables and initialColections are assigned in the merge commit when resolving the conflict.

**Comment by 96LawDawg** [comment]
I added a new variant 3 to describe the use of the new pre-defined routines and collection.  I also added a button I noticed was missing in variant 0.

**Review by 96LawDawg — APPROVED** [review]
Approved through test and code review.

**Comment by 96LawDawg** [comment]
@ArnoldSmith86, this has approvals, tutorial, and wiki all ready to go.  This technique also was already proven to work in #1443. Any reason not to merge it?

**Pull request merged**
