### PR TITLE
always send update for deleted properties

### LINKED ISSUE #1408: JSON editor fails to delete properties
I have this widget:

```JSON
{
  "type": "holder",
  "id": "B1",

  "x": 500,
  "y": 800,
  "width": 100,
  "height": 100,

  "movable": false,
  "movableInEdit": true,

  "classes": "transparent",
  "css": "background:#ccc",
  "dropOffsetX": 0,
  "dropOffsetY": 0,
  "inheritFrom": {
    "A1": [
      "width",
      "height",
      "borderRadius",
      "classes",
      "css",
      "dropOffsetX",
      "dropOffsetY",
      "dropTarget",
      "enterRoutine"
    ]
  }
}
```

I want to delete for example `"dropOffsetY": 0,` but opening the widget again shows that it's not deleted.

### PR DESCRIPTION
**Pull request by robartsd**
Fixes #1408

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1409/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1409-pr-test`.

**Comment by ArnoldSmith86** [comment]
So... Any idea what my thought process was here? https://github.com/ArnoldSmith86/virtualtabletop/pull/1314/commits/f36fabf23dca7094fd2f106e3c523ff0837361d6 :rofl:

**Comment by robartsd** [comment]
The JSON part was clearly intended to filter out cases where the updated property is an object or array that is equivalent to the previous object or array. I'm not 100% sure what the null filter was trying to accomplish. Could possibly change the filter to check only type defaults (but not inherited defaults).

**Comment by rogerl50** [comment]
This was put in as a performance improvement. I don't recall how much effect it had, but that should probably be looked at before deciding whether to improve or remove. I think the issue was from ingegneus.

**Comment by robartsd** [comment]
> This was put in as a performance improvement. I don't recall how much effect it had, but that should probably be looked at before deciding whether to improve or remove. I think the issue was from ingegneus.

You seem to be the one who did much of the profiling of the PR in question (#1314).

**Comment by rogerl50** [comment]
Now that I'm back and can look at this carefully, I'd just go ahead and merge this PR as is. The only difference is what happens when someone removes a property that already has the default value. This can't possibly make a huge difference in performance. I think removing it is lower-risk (and certainly easier) than trying to further optimize for `inheritFrom`.

**Review by ArnoldSmith86 — APPROVED** [review]
I honestly don't see how the removed code is doing something useful. If I remove a property from the widget that is set to its default value, I sure want it to be removed.

**Comment by 96LawDawg** [comment]
Any reason this bug-fixing PR isn't merged yet?

**Pull request merged**
