### PR TITLE
Update Bhukhar and Diced

### PR DESCRIPTION
**Pull request by 96LawDawg**
Bhukhar added improved layout, automation, and rules enforcement. Diced added improved rules enforcement and restart button.

Added Grim Pixel Art deck to Deck Assets.

Copied hexagonal grids tutorial from Hexagons to Grid. Copied part of Spinner tutorial counting spinners to Functions - GET.

Updated library.json to reflect those changes and to remove the Chinese language name of Chinese Checkers per discussion at recent meeting

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3288/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
All changed files updated successfully from public library.  According to @ArnoldSmith86 Bhukhar still needs #282 implemented before this in order to work.  This is a do-over on the PR because the previous one had a lot of other unrelated commits leaking in.

**Review by ArnoldSmith86 — APPROVED** [review]
Looks fine to me. Two little things that can totally wait for next time:

- Bhukhar says `4-6-8` players. At some point we want to filter on this and I wouldn't know how to interpret it. It looks like `4-8` to me but I guess it's supposed to be 4 or 6 or 8 which I would prefer to be entered as `4,6,8`.
- The tutorial for `GET` with `first` says "GET always works on the first widget of a collection." That sounds to me like there is actually no other aggregation function. I'm pretty sure that text is older than the `aggregation` parameter.

**Comment by 96LawDawg** [comment]
This one has been waiting long enough for a library update.  Merging now.  I have added @ArnoldSmith86's comments to my to do list for next time.

**Pull request merged**
