### PR TITLE
added Codespaces support

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
First test. Goal is that VTT starts automatically when opening a Codespace.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2290/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
It seems to work pretty well. It takes a while. And for some reason it takes quite a while longer until the websocket connection actually works..

**Comment by RaphaelAlvez** [comment]
Works for me. Much better then doing by myself

**Comment by ArnoldSmith86** [comment]
I think this is all I wanna do for now. I couldn't get the debugger to attach automatically but you can just press the Play arrow in "Run and Debug" and it should attach to the automatically running process. Breakpoints should then just work.

It also doesn't make the port public. Maybe it's a security feature, no idea.

**Review by 96LawDawg — APPROVED** [review]
Blind approval.  I don't even know what Codespaces is, but it doesn't look like this can do any harm.

**Pull request merged**
