### PR TITLE
hide empty `INPUT` labels

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Suggested by @mousewax. Did not test yet.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1896/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1896-pr-test`.

**Comment by 96LawDawg** [comment]
Sorry.  I don't get it.  What does this do?  What should I test?

**Comment by mousewax** [comment]
It removes the spacing left for labels on input rows where the label has been left off or is null.

Before:
image

After:
image

**Comment by 96LawDawg** [comment]
I see now what we are trying to do.  And I see the visual difference in what you posted.  I just can't create it.  I put labels, I put no labels.  The spacing all looks the same to me in my tests.  I'm sure I'm doing it wrong.

**Comment by mousewax** [comment]
I am not sure why it's not working. This is from this PR test server.
image

**Comment by ArnoldSmith86** [comment]
Looks like there's an extra colon in the rule.

**Review by 96LawDawg — APPROVED** [review]
I thought I was just being an idiot and considered approving it before because it should have worked.  Glad I held off.  Now it is approved through testing and code review.

**Pull request merged**
