### PR TITLE
Behave as if fixedParent is true if only movable in edit

### PR DESCRIPTION
**Pull request by robartsd**
It is very easy to accidentally remove the parent of a widget when in edit mode. This makes all widgets that have movable set to false behave as if fixedParent is set to true when being moved in edit mode.

### CODE REVIEW

**Comment by robartsd** [comment]
This is an alternative to #1617 that does not actually change widget properties or behavior in game mode, so no file updater should be required.

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1618/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1618-pr-test`.

**Comment by 96LawDawg** [comment]
Doesn't work.

**Comment by robartsd** [comment]
> Doesn't work.

Opps. I pushed without testing before heading to my mom's for dinner. It works now.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  This is a good solution.

**Comment by robartsd** [comment]
What is especially nice is that it works for all widget types - if you set them so that the player can't move them, they no longer deparent when moved in edit. Most of the widget types that we talked about defaulting to fixedParent: true also default to movable: false. 'deck' is a bit weird; even though it does not appear in play mode, it is 'movable', so it will not behave as if it has fixedParent true by default, but that is needed for the edit mode UI design to drag and drop a deck between holders.

**Review by flackr — APPROVED** [review]
Code looks good to me.

**Comment by flackr** [comment]
Also, I like this approach. I've accidentally moved things out of parents in edit mode so often!

**Review by ArnoldSmith86 — APPROVED** [review]
I like it. We'll see if we prefer the old way in a few months... :smile:

**Pull request merged**
