### PR TITLE
Add Agra, Dog Eat Dog, Investors +4 others

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public library:

- Agra. New game by LawDawg96. Similar to Jaipur.
- Dog Eat Dog World. New game by LawDawg96. Similar to Food Chain Island.
- Investors. New game by LawDawg96. Similar to Startups.
- No Cheese No Coin. New game by Stephen Rafferty and LawDawg96. Original game by Stephen Rafferty.
- Peak Performance. New game by ArnoldSmith86. Similar to Unsurmoutable.
- Scrappet Kaiser Princess. New game by Zoql and LawDawg96. Original game by Zoql.
- Stardust Butterfly. New game by Zoql and LawDawg96. Original game by Zoql.
- Forces of Nature. Updated font color on cards for readability and deleted an accidental holdover from testing that left an old card sum visible when first taking a seat.
- Hearts. Based on playtesting, updated the layers of a couple of widgets so that cards always pass in front.  And changed a default option setting so that points are NOT displayed during the round.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1249/pr-test (or any other room on that server)

**Comment by RaphaelAlvez** [comment]
I had the impression we were done with PL PRs for now. Should I review this?

**Comment by 96LawDawg** [comment]
@ArnoldSmith86 said it didn't make any difference.  So a review would be appreciated.

**Review by RaphaelAlvez — APPROVED** [review]
approved

minor change request. The card 6 in forces of natures does not use #000000aa
image

**Comment by 96LawDawg** [comment]
Change to 6 card in Forces of Nature made.  Staged for upload next time.

**Pull request merged**
