### PR TITLE
Grid can use widget corner instead of center for snap alignment

### PR DESCRIPTION
**Pull request by 96LawDawg**
Implements #1462 by creating new `gridCornerAlign` boolean property.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1512/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1512-pr-test`.

**Comment by flackr** [comment]
I think maybe we should have an alignment specified for each different grid definition, e.g.

```
  grid: [{ "offsetX": 200, "x": 300, "y": 173.2, "align": "center" }, { "offsetX": 350, "offsetY": 86.6, "x": 300, "y": 173.2, "align": "top left" }, … ]
```

**Comment by 96LawDawg** [comment]
> I think maybe we should have an alignment specified for each different grid definition, e.g.
> 
> ```
>   grid: [{ "offsetX": 200, "x": 300, "y": 173.2, "align": "center" }, { "offsetX": 350, "offsetY": 86.6, "x": 300, "y": 173.2, "align": "top left" }, … ]
> ```

I thought about that.  I guess that would work.  Would seem to be confusing to implement.  Do we need additional alignment parameters other than center and top left?

**Comment by flackr** [comment]
> I thought about that. I guess that would work. Would seem to be confusing to implement. Do we need additional alignment parameters other than center and top left?

It's probably interesting to think about how this would interact with dropAnchor (see https://github.com/ArnoldSmith86/virtualtabletop/pull/1388) which has a pair of percentages (but could also have keywords like top/left/bottom/right/center). Should we use dropAnchor for this instead of having a grid property? The two having different values would be weird.

**Comment by RaphaelAlvez** [comment]
I'd suggest using percentages

with values like "align": "0 0" or "align": "0.5 0.5"

then the code can just be something like:
`snapX = x + grid.x*alignX - mod(x - (grid.offsetX || 0), grid.x);`

btw I don't really understand why you need to change the whole code for snapX and snapY.

**Pull request closed without merging**
