### PR TITLE
fix mistake in sort tutorial

### PR DESCRIPTION
**Pull request by tsankuanglee**
tutorial description says reverse sort but parameter doesn't. this fixes it.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1569/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1569-pr-test`.

**Comment by 96LawDawg** [comment]
Good catch.  Can you make the TestCafe correction as well?  The hash changed since that variant was used in testing.  If you can't, I'll re-do the PR and push from main.

**Comment by tsankuanglee** [comment]
Thanks, @96LawDawg . I'll work on TestCafe.

**Comment by tsankuanglee** [comment]
This is ready to go @96LawDawg

**Review by 96LawDawg — APPROVED** [review]
Approved through test and JSON review.

**Pull request merged**
