### PR TITLE
Improve default counters for mobile devices

### PR DESCRIPTION
**Pull request by 96LawDawg**
Default counters are almost unusable on mobile devices because the plus and minus buttons sit within the overly large label text area.  This change shrinks the size of the text area box and slightly repositions the plus and minus buttons in relationship to the new box.  Values -999 to 999 still fit.  See screenshot for example of change; new default counter is on top and the original one is on the bottom.  The other change was needed to slightly reposition the default counter in the add widget menu to account for the change in size.

Counter

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3224/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
This is my first edit to the javascript. I have only done library.json and .vtt files before.  I tested this on a virtual server on my computer and on the github test server.  Not much of a change because I don't know javascript, but I really wanted the "code contributer" label on Discord!  Actually, I was play testing Crafty on a mobile device and couldn't get the scoring to work, which prompted this suggested change.

**Comment by 96LawDawg** [comment]
Well, I may have screwed this up because I tried to add library files while I had a pending code change.  This additional commit has Bus Driver and Mensch argere Dich nict by Ingegneous and also a slightly updated version of Medieval Uno by him as well.  It also contains Crafty by LawDawg.

I'm going to leave this as is for now until somebody either approves PR that contains a minor code enhancement and a library update or until somebody tells me how to unscrew this because I don't know github well enough to do it on my own.

**Comment by UltimateGeek** [comment]
> Well, I may have screwed this up because I tried to add library files while I had a pending code change. This additional commit has Bus Driver and Mensch argere Dich nict by Ingegneous and also a slightly updated version of Medieval Uno by him as well. It also contains Crafty by LawDawg.
> 
> I'm going to leave this as is for now until somebody either approves PR that contains a minor code enhancement and a library update or until somebody tells me how to unscrew this because I don't know github well enough to do it on my own.

Could you update the PR title to indicate the additional scope?

**Comment by RaphaelAlvez** [comment]
I was about to approve this PR but I couldn't find the new games on the public library

**Comment by ArnoldSmith86** [comment]
I'm pretty sure it's not fine to call it "Mensch ärgere Dich nicht": https://en.wikipedia.org/wiki/Mensch_%C3%A4rgere_Dich_nicht

**Comment by robartsd** [comment]
> I'm pretty sure it's not fine to call it "Mensch ärgere Dich nicht": https://en.wikipedia.org/wiki/Mensch_%C3%A4rgere_Dich_nicht

According to that WP article, the game was developed in 1907/1908; so I believe the original would be out of copyright by now (would be under US copyright law anyway). Unless the name is covered by trademark law, it should be fine.

**Comment by 96LawDawg** [comment]
> I was about to approve this PR but I couldn't find the new games on the public library

I think that is because this server started with the change to default counters and got the older version of the library.  Probably restarting the server would fix that, but I don't know how to do that.

**Comment by 96LawDawg** [comment]
> > I'm pretty sure it's not fine to call it "Mensch ärgere Dich nicht": https://en.wikipedia.org/wiki/Mensch_%C3%A4rgere_Dich_nicht
> 
> According to that WP article, the game was developed in 1907/1908; so I believe the original would be out of copyright by now (would be under US copyright law anyway). Unless the name is covered by trademark law, it should be fine.

Except that also says "In 1953, Schmidt Spiele introduced an official Mensch ärgere Dich nicht version as a licensed edition in East Germany."  So that would put it still under copyright.  So I'll fix that here in the PR soon and get with the developer to change the name.

**Comment by robartsd** [comment]
> > I was about to approve this PR but I couldn't find the new games on the public library
> 
> I think that is because this server started with the change to default counters and got the older version of the library. Probably restarting the server would fix that, but I don't know how to do that.

Merging main back into this branch should fix it.

**Comment by ArnoldSmith86** [comment]
Works for me.

I'll test the counter change soon.

**Comment by robartsd** [comment]
> > > I'm pretty sure it's not fine to call it "Mensch ärgere Dich nicht": https://en.wikipedia.org/wiki/Mensch_%C3%A4rgere_Dich_nicht
> > 
> > 
> > According to that WP article, the game was developed in 1907/1908; so I believe the original would be out of copyright by now (would be under US copyright law anyway). Unless the name is covered by trademark law, it should be fine.
> 
> Except that also says "In 1953, Schmidt Spiele introduced an official Mensch ärgere Dich nicht version as a licensed edition in East Germany." So that would put it still under copyright. So I'll fix that here in the PR soon and get with the developer to change the name.

Although the 1953 release would not affect the copyright status of previously released versions, it does increase the likelyhood that trademark protection does still apply to the name; so we probably should rename.

**Comment by 96LawDawg** [comment]
I agree with robartsd that we should rename.  Copyright isn't the only thing we have to worry about; trademarks are also an issue and versions of Mensch ärgere Dich nicht from Schmidt Spiele have been issued as recently as 2014: [https://www.boardgamegeek.com/boardgame/153103/mensch-argere-dich-nicht-das-kartenspiel](url).

I tried to fix this PR by deleting the game and updating the library.json.  It did not work as expected.  So I'm going to close this PR and start over.  I will upload the library stuff first for approval.  Then hopefully we can get the counter thing approved after that.  I really have a love-hate (mostly hate) relationship with github.

**Comment by 96LawDawg** [comment]
Actually, I decided to try one more time.  Stand by.

**Comment by 96LawDawg** [comment]
Of course, by closing the PR the test server room no longer works.  Hopefully that won't be a problem.  Sorry for the mess.

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3224/pr-test (or any other room on that server)

**Review by RaphaelAlvez — APPROVED** [review]
Tested again and approved. Next time try to make changes on different branches and use them to make different PRs.

**Pull request merged**
