### PR TITLE
Protect set(parent,null) in MOVEXY by disablePileUpdateAfterParentChange

### LINKED ISSUE #872: The position of the card placed in MOVEXY shifts
If you expand the cards using the code below, you'll see that only the last card in the collection is out of coordinates and overlaps with the other cards.
However, for example, "var x = 20" and "vary = 20" were fine.
```
{
  "type": "button",
  "text": "spread",
  "x": 0,
  "y": 90,
  "z": 305,
  "id": "spread",
  "debug": false,
  "movableInEdit": false,
  "parent": "length",
  "width": 40,
  "height": 40,
  "clickRoutine": [
    {
      "func": "SELECT",
      "property": "parent",
      "value": "temp",
      "type": "card",
      "collection": "spreadDeck",
      "sortBy": {
        "key": "z",
        "reverse": true
      }
    },
    "var x = 10",
    "var y = 10",
    "var offsetX = 120",
    "var offsetY = 200",
    "var count = 1",
    {
      "func": "FOREACH",
      "collection": "spreadDeck",
      "loopRoutine": [
        {
          "func": "MOVEXY",
          "from": "temp",
          "face": 0,
          "x": "${x}",
          "y": "${y}",
          "z": 100
        },
        {
          "func": "IF",
          "operand1": "${count}",
          "relation": ">=",
          "operand2": "${PROPERTY text OF length}",
          "thenRoutine": [
            "var count = 1",
            "var x = 10",
            "var y = ${y} + ${offsetY}"
          ],
          "elseRoutine": [
            "var count = ${count} + 1",
            "var x = ${x} + ${offsetX}"
          ]
        }
      ]
    }
  ]
}
```
spread

### PR DESCRIPTION
**Pull request by rogerl50**
I think this fixes #872, but this needs code review from @ArnoldSmith86 .

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3874/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
It looks good to me.  It looks like it will prevent the piles from updating from onPropertyChange before the new x and y are set in MOVEXY.

**Comment by ArnoldSmith86** [comment]
The second line could be moved after set position. It's calling updatePiles explicitly anyway afterwards. (Or that call could be deleted? Gotta have a closer look.)

**Comment by rogerl50** [comment]
> The second line could be moved after setPosition. It's calling updatePiles explicitly anyway afterwards. (Or that call could be deleted? Gotta have a closer look.)

Yeah, possibly move the `setParent` call to the end and get rid of the `updatePiles` call would work. But you'll have to decide that.

**Comment by rogerl50** [comment]
> > The second line could be moved after setPosition. It's calling updatePiles explicitly anyway afterwards. (Or that call could be deleted? Gotta have a closer look.)
> 
> Yeah, possibly move the `setParent` call to the end and get rid of the `updatePiles` call would work. But you'll have to decide that.

After looking at the code some more, I made this change and it appears to work. Still needs review, though.

**Comment by ArnoldSmith86** [comment]
Doesn't this now cause a similar problem if the the `setPosition` causes a new pile to form before the `parent` gets updated?

**Comment by rogerl50** [comment]
> Doesn't this now cause a similar problem if the the `setPosition` causes a new pile to form before the `parent` gets updated?



> Doesn't this now cause a similar problem if the the `setPosition` causes a new pile to form before the `parent` gets updated?

It doesn't appear to. Look at the pr-test room. There, I move a card to offset (105,5) from the holder (resetting its parent to be the holder), then MOVEXY a card from the deck to (105,5). It ends up in the right place.

The `updatePiles` call occurs during the `setParent(null)`, not during the `set('x')` call.

**Review by ArnoldSmith86 — APPROVED** [review]
The code change looks fine to me if it seems to improve the behavior. It's not like I can predict everything this would affect.

**Review by bjalder26 — APPROVED** [review]
I think the changes make sense in the code, and I fiddled around trying to fine problems and could not.  Approving based on code review and testing.

**Pull request merged**
