### PR TITLE
First version of editable tables

### PR DESCRIPTION
**Pull request by rogerl50**
Still needs work. What's here mostly works, but the issue I'm having is getting clicks in other parts of the room to work correctly. The behavior I'm looking for is: Enter accepts an edit, ESC or a click anywhere else aborts the edit (and a click doesn't do whatever the click would normally do). I'm getting messed up with too many click handlers. Help is definitely needed.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1446/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1446-pr-test`.

**Comment by RaphaelAlvez** [comment]
Hum. I just created a room on my phone I can say I got nowhere with eh current setup.

Probably because I would assume we need a button to start anew round. If so I assume we need to make this a composite widget

**Comment by 96LawDawg** [comment]
I guess I agree with Raphael that this version of it should work just upon adding to the room.  So need someway to advance rounds.  We could (just to make things harder for Roger - but really to keep the visual profile low) make cell 0,0 (where it says Round), a separate click area that creates a new row.

On testing, I could enter numbers okay using the enter key.  But as soon as the scoreboard moves, the scores reset to 0.

**Comment by rogerl50** [comment]
> I guess I agree with Raphael that this version of it should work just upon adding to the room.  So need someway to advance rounds.  We could (just to make things harder for Roger - but really to keep the visual profile low) make cell 0,0 (where it says Round), a separate click area that creates a new row.
> 
> On testing, I could enter numbers okay using the enter key.  But as soon as the scoreboard moves, the scores reset to 0.

Right. I should have said that I don't have this set up to update the score arrays yet. I'm just trying to get the click navigation working properly. Apologies to those of you who spent time testing something that is known not to work.

**Comment by ArnoldSmith86** [comment]
So, when I said manually editing the scoreboard would be cool, I actually just had an overlay in mind that opens on click where you would have a seat dropdown, a round dropdown (with an "add" option) and a score input field.

I'm not saying I don't think your approach is cool. I do think that it'll probably be pretty finicky on mobile though.

I can definitely try to help with clickhandler problems but I'd like to hear some thoughts about this approach vs. a simpler one (opening some sort of overlay or other UI on click) before committing further.

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 do you think your approach could include a round and reset buttons?
If so I maybe prefer yours

**Comment by ArnoldSmith86** [comment]
We can put whatever we want onto an overlay. We could also recreate the whole table in fullscreen and make it editable there.

**Comment by rogerl50** [comment]
That sounds like a reasonable approach. If the whole table is recreated in fullscreen, with some auxiliary buttons for the additional functions, it would be much more usable even on a computer.

Should we get the original scoreboard PR merged first? I personally am ready to be done with it :smiley:

**Comment by rogerl50** [comment]
Will likely be done a different way.

**Pull request closed without merging**
