### PR TITLE
Update library (Add Connex, Tutorial-Dice, Assets-Decks, Assets-Dice)

### PR DESCRIPTION
**Pull request by 96LawDawg**
Add:
 - Connex, similar to Tetris Link, by LawDawg
 - Tutorial-Dice
 - Assets-Decks and Assets-Dice

Update:
 - library.json
 - Diced (to incorporate new style dice into game)
 - Splendid (fixed undo button and automatically spend tokens)
 - Assets - Spinners (to make VTT name consistent with other asset files)
 - Assets - Widgets (to add buttons and crystals and remove decks and make its own category)

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3192/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
All changed files added to test server successfully through library.json.

**Comment by robartsd** [comment]
I did notice that the backgrounds for the player scorecards in Diced are moveable in play mode (published version has the same, so not a reason to block this PR).

**Comment by 96LawDawg** [comment]
Thanks.  I'll fix that for the next go around.  So many parts in there I forgot to lock down some of them.

**Review by RaphaelAlvez — APPROVED** [review]
Did not play test the new games but everything seems to be right according to the description

**Pull request merged**
