### PR TITLE
Enlarge for laptop touchscreens

### PR DESCRIPTION
**Pull request by bjalder26**
Adds touchscreen event listeners so that enlarge will work for touchscreens.

- Enlarge is activated by a long press (1/2 sec) on touchscreens
- Click event deactivated on long press

I used a class, because I didn't want to create a new property if a long press wasn't going to be used for anything else.  However, it would be fairly easy to make longtouch a property if it is going to be used for other things as well.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3657/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
Doesn't it work for you when you long-press? (Apart from not being hidden until you basically long-press something else.)

**Comment by bjalder26** [comment]
> Doesn't it work for you when you long-press? (Apart from not being hidden until you basically long-press something else.)

On the production server, it does not enlarge on my touchscreen at all (no matter how long I press it).  I assumed it was the same for everyone.  Maybe that was a bad assumption.

**Comment by ArnoldSmith86** [comment]
Does it work for you on mobile?

**Comment by bjalder26** [comment]
> Does it work for you on mobile?

Yes, it does.  I'll check another touchscreen laptop as well.

**Comment by RaphaelAlvez** [comment]
I don't really understand this PR.
This is from my phone in the normal server:

**Comment by ArnoldSmith86** [comment]
Yeah, it works on my phone as well. My guess is that laptops with touchscreens report different capabilities.

That's good to know.

I want to tweak that feature soon. It should work more like in PCIO: you long-press one widget until the enlarged version shows up and then you can just move the finger to different widgets to see their enlarged version.

**Comment by bjalder26** [comment]
> Yeah, it works on my phone as well. My guess is that laptops with touchscreens report different capabilities.
> 
> That's good to know.
> 
> I want to tweak that feature soon. It should work more like in PCIO: you long-press one widget until the enlarged version shows up and then you can just move the finger to different widgets to see their enlarged version.

I checked another touchscreen and it was the same.  I had a similar realization.  With the changes in this PR it will flip the widget when you remove your finger unless you move the widget a little.  Like I think you're saying, ideally a short press should probably flip the widget and a long one should enlarge (if set to do so).

**Comment by bjalder26** [comment]
Maybe something like the 2nd answer here (SLoN1ck's) would be a better solution.

https://stackoverflow.com/questions/6139225/how-to-detect-a-long-touch-pressure-with-javascript-for-android-and-iphone

**Comment by bjalder26** [comment]
> I don't really understand this PR.
> This is from my phone in the normal server:

My guess is that apps on phones and tablets will automatically change the input to mouse events as needed, but a laptop that has a mouse (or touchpad) will not automatically change touchscreen events into mouse events.

'Web applications can either directly process touch-based input by using Touch Events or the application can use interpreted mouse events for the application input.'
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Using_Touch_Events

**Review by RaphaelAlvez — APPROVED** [review]
tested and this PR does not break enlarge on my devices. If it does improve in any device then this should be merged

**Comment by bjalder26** [comment]
> tested and this PR does not break enlarge on my devices. If it does improve in any device then this should be merged

I believe it will make enlarge take 1/2 a second longer on phones than previously because it waits 1/2 a second.  The other difference you might notice is that it prevents the click event, so cards will flip if you quickly tap them, but not if you do a long press (>1/2 sec) on them.

**Pull request merged**
