### PR TITLE
new game Hnefatafl

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
A simple implementation of an abstract game. I will probably still improve it a bit.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1483/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1483-pr-test`.

**Review by RaphaelAlvez — CHANGES_REQUESTED** [review]
You forgot attributions

**Review by RaphaelAlvez — APPROVED** [review]
Quick test. Very simple game

**Comment by RaphaelAlvez** [comment]
@ArnoldSmith86 this is good to go. I'd just merge it and maybe change it in the future.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  I agree with Raphael.  Nothing wrong with this the way it is.  Fix it later if you want.  Ready to merge.

**Pull request merged**
