### PR TITLE
result of shuffle is no longer ambiguous

### LINKED ISSUE #1111: ambiguous z values
So, I found a potentially big problem:

1. Open https://virtualtabletop.io/1mxx (red is on top)
2. Press the button (orange is on top)
3. Open https://virtualtabletop.io/1mxx (red is on top)

When two widgets have the same `z`+`layer`+`parent`, the actual z order of them is determined by the order in the DOM.

When loading a room, the order in the DOM is the order in which the widgets are defined in the JSON (so usually the one added first is below the one added afterwards).

Changing a parent in the game moves the DOM element to the new parent but it puts it all the way at the end.

In practice this could happen with normal shuffling, I think.

1. Player 1 shuffles cards.
2. Player 2 joins afterwards.
3. The order of the cards is not the same for both of them (unless player 1 reloads the page).

Now, I'm not too sure if this is actually a problem. Mouse interactions and for example `MOVE`s apply a unique z value so those should not be affected. A `SHUFFLE` applies random z values to all children which can produce the same value for multiple widgets. _But_ if you shuffle, the order is obviously not important. Unless the cards are face up.

Hmm, I think `SHUFFLE` should make sure that z values are unique.

### PR DESCRIPTION
**Pull request by robartsd**
Fixes #1111: shuffle no longer creates ambiguous z values. Instead of a random z assigned to each shuffled widget, the widgets are put in a random order, then each is brought to the front of their layer in turn. Shuffled widgets will now be in front of any widgets that were not shuffled (previously widgets on the same layer could remain in front of [some] of the shuffled widgets).

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:1112/pr-test (or any other room on that server)

**Comment by ArnoldSmith86** [comment]
The shuffle button in the pile menu should also be affected.

**Comment by ArnoldSmith86** [comment]
Just as an FYI to anyone following this issue: this does not fix the example I built in https://virtualtabletop.io/1mxx for #1111.

But I feel like that example is artificial enough to be ignorable.

This does however fix the currently very real (though pretty unlikely) possibility that you `SHUFFLE` a pile of face up cards and different players see (and interact with) a different card on top.

**Comment by robartsd** [comment]
> This does however fix the currently very real (though pretty unlikely) possibility that you `SHUFFLE` a pile of face up cards and different players see (and interact with) a different card on top.

It wasn't all that unlikely. Probability that n widgets shuffled has a pair of widgets with the same z:

`P = 1 - 0.9999**(n-1)`

About 1:200 chance that two cards would get the same z value somewhere in a shuffle of 52 cards. Of course the probability the top two cards are that pair is only 1:10000, but your chance of coming across ambiguous shuffle increases as you continue through the deck. (At least 2 TestCafe tests had ambiguous shuffles, an ambiguous shuffle swapped a pair of cards in the test for Bhukhar; another was detected in the draw pile for Rummy Tiles).

**Comment by ArnoldSmith86** [comment]
And then it only occurs if the order of the pair in the DOM is different than the order in the JSON. Which is probably 1:2 but there might be bias in the code somewhere.

And one player has to reload the game state.

So it's probably not the biggest issue in the world but I think it's kinda important that we fix it.

**Review by ArnoldSmith86 — APPROVED** [review]
Feels kinda weird that `shuffleWidgets` is a class method but :man_shrugging:.

Code looks fine. Seems to work. If games are breaking because of this, it would be _really_ weird.

**Comment by robartsd** [comment]
> Feels kinda weird that `shuffleWidgets` is a class method but 🤷‍♂️.

True, I didn't put much thought into where I implemented the routine. It really has no need to belong to the Widget class.

**Comment by robartsd** [comment]
I'll merge this and open an issue for sortWidgets and shuffleWidgets to be moved out of the class.

**Pull request merged**
