### PR TITLE
Add Flower Poker to PL

### PR DESCRIPTION
**Pull request by 96LawDawg**
Similar to Los Banditos (by Shobu).

Also fixes Pumpkin Curse that was recently added; it was missing the year in the meta data.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1929/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1929-pr-test`.

**Comment by ArnoldSmith86** [comment]
At least the library images are links to Midjourney.

**Comment by 96LawDawg** [comment]
Good catch.  There's one more I need to fix.  Is there an easy way to check that other than searching for "http" in the JSON?

**Comment by ArnoldSmith86** [comment]
The assets sidebar should show them but I didn't think of a good way to include metadata assets yet:

image

**Comment by 96LawDawg** [comment]
Maybe I don't know how to use that Assets sidebar thing properly.  For me, it just is a file interface: download or upload.  It doesn't display anything.

**Comment by ArnoldSmith86** [comment]
Then it didn't find any links.

**Review by ArnoldSmith86 — APPROVED** [review]
Looking good!

**Pull request merged**
