### PR TITLE
Input overlay revamp

### PR DESCRIPTION
**Pull request by mousewax**
The PR you have requested is no longer in service. The new PR is:
https://github.com/ArnoldSmith86/virtualtabletop/pull/976

Please make a note of it.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3888/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
I know this is still a work in progress, but through some testing, I discovered that the toggle switches do not seem to work.  Whether I select them on or off, they always report as on in the debugger.

**Comment by rogerl50** [comment]
What's the status of this PR? It looks like it needs some changes because it includes almost duplicate content from #862, and there is the problem reported above by @96LawDawg . Once those are fixed we can take a look at the TestCafe failures.

**Comment by rogerl50** [comment]
In the pr-test room, the DEAL button contains code that tries to apply css to a `string`, but it fails.

**Comment by rogerl50** [comment]
Also, in the state overlay, the [sand_timer] and [book_open] do not show icons - just the text.

**Comment by rogerl50** [comment]
Finally, this is great!

**Comment by mousewax** [comment]
The PR you have requested is no longer in service. The new PR is:
https://github.com/ArnoldSmith86/virtualtabletop/pull/976

Please make a note of it.

**Pull request closed without merging**
