### PR TITLE
added `jsonParse` and `jsonStringify` compute functions

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
Please test...

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1851/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1851-pr-test`.

**Comment by gustavoberman** [comment]
Is there any example or documentation on how to use this?
Thanks!

**Comment by ArnoldSmith86** [comment]
> Is there any example or documentation on how to use this? Thanks!

I put a basic example into the PR test room (https://test.virtualtabletop.io/PR-1851/pr-test):

image

Please note that this is not usable in production yet. It is mainly meant in conjunction with #1852, so you can download JSON from somewhere on the internet and use its contents easily.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.  I added a tutorial using a cool website that provides fake data for just this sort of thing.  I added placeholder entries into the wiki already (saying that approval is pending).

**Comment by ArnoldSmith86** [comment]
Can you check what happens if you give it malformed JSON?

**Comment by 96LawDawg** [comment]
> Can you check what happens if you give it malformed JSON?

I took what I used in the tutorial (retrieved from the website) and just added 'hello' to the end.  The `parsed` function returns 0 and gives this error in the debugger: "Exception: SyntaxError: Unexpected non-whitespace character after JSON ..."  But it didn't crash the room.

**Comment by ArnoldSmith86** [comment]
Sounds like the correct solution?

**Comment by 96LawDawg** [comment]
Yes, I think so.

**Pull request merged**
