### PR TITLE
gamepiece are in hue order

### PR DESCRIPTION
**Pull request by RaphaelAlvez**
I was passing by it in the code and decided to propose the change

- This PR:

image

- Before:

image

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3484/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
This makes no changes to the actual pieces, just changes the order on the add widget screen.  The only thing worthwhile I could think to do is double check to make sure there were no typos or slight changes in the hex code.  Unless someone has an objection to changing the order of the gamepieces, I think this could be merged.

**Review by ArnoldSmith86 — APPROVED** [review]
Sure.

**Comment by robartsd** [comment]
Personally, I'd prefer Black, Red, Orange, Yellow, Green, Blue, Purple, Gray, White because black and read are the colors most often used by two player games; but I don't really care.

**Pull request merged**
