### PR TITLE
improve cacheability of assets

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
This PR tells browsers to not ask the server for changes to assets it already has in its cache. The assets have a checksum of their contents in the URL so every change to the content would lead to a new URL anyway.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3789/pr-test (or any other room on that server)

**Comment by bjalder26** [comment]
Is there a way to test this, or does someone just need to review the code?

**Comment by ArnoldSmith86** [comment]
Load a game into a room, open dev tools (F12), reload the room by pressing ENTER in the address field (pressing F5 might trigger a more aggressive reload):

image

You get an entry for every asset in the Network tab resulting in a "304 Not Modified" response. That means the browser sent a request to the server basically saying "I have this version of the image in my cache. Is this still the latest one?" and the server replies that it's the latest one so it doesn't have to send the image again.

With this PR the server tells the browser that it doesn't have to ask if it's still the latest one for the next year or something. Doing the same procedure then results in this:

image

10 instead of 23 requests. It still asks for the toolbar images and some other stuff. That can also be fixed but I think it's way more important for assets (a game could load hundreds or more) and since the URL already contains a checksum, it was really easy to add.

**Comment by bjalder26** [comment]
Yeah, I see it and it is even faster.

**Review by bjalder26 — APPROVED** [review]
Approved based on testing.  There is only minimal code (2 lines), and I can see it working in the debugger.  It improves speed, and I'm guessing it will lower the work of the server.

**Pull request merged**
