### PR TITLE
tree view shows identifying properties

### PR DESCRIPTION
**Pull request by ArnoldSmith86**
I just rediscovered these tree view improvements in #850. I do not think that #850 will be prioritized anytime soon but these changes are unrelated and probably helpful.

It shows the `cardType` of cards, `text` of buttons and `classes` of basic widgets in red.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1150/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
I don't think this helps readability.  It makes it worse in some cases.  So much worse, that I don't think this should be approved as is.  Making the cards red is fine.  But the buttons and basic widgets in red, especially in narrow view is, well ...  See for yourself.  From Best Guess.

Old way (wide)

Old Wide

Old way (narrow)

Old Narrow

New way (wide)

New Wide

New way (narrow)

New Narrow

**Comment by 96LawDawg** [comment]
I just had a thought that I should also check out cards, especially cards imported from PCIO (like the current PL dominoes room).  Also very ugly.

Old (wide)

Card old (wide)

New (wide)

Card new (wide)

**Comment by ArnoldSmith86** [comment]
This was mainly meant for widgets with randomly generated IDs. Please take another look. Note: it will only show up in the wide editor.

**Review by 96LawDawg — APPROVED** [review]
That is much better and now actually useful.  I looked at several PL games that have widgets that are improved by this.  And the games that I pointed out that were problems no longer are.

**Review by RaphaelAlvez — APPROVED** [review]
I was feeling stupid becaise I saw no difference at first.

very helpful if anyone finds this

**Pull request merged**
