### PR TITLE
New icon font specifically for VTT

### PR DESCRIPTION
**Pull request by mousewax**
New icon font VTT-Symbols. 
This update contains over 200! icons specifically tailored or chosen for VTT both as an icon font as well as SVGs. 

Many buttons have been updated to include icons from the new font. I am sure that I missed some. 
The `prettyButton` class in CSS was updated for this.
There is now a new `ui-button` class that are larger. They are on the 'Edit game' overlay. 

Adding the class 'symbols' will change the font to the VTT-Symbols font allowing you to use the names of the symbols as text.
` "classes": "symbols",
  "text": "help card",`
becomes:
image

You can also add `font-family: 'VTT-Symbols'` to the CSS.

The SVGs (contained in a new `assets/icons` directory) all have `currentColor` as their fill value so SVG replaces should work. Though some work should probably be done to make more sections have their own colors applied to them.

[You can preview the icons and see their names here.](https://www.mousewax.com/VirtualTabletop-Symbols/)

Let me know how I can make these more useful!

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3935/pr-test (or any other room on that server)

**Comment by robartsd** [comment]
I can't distinguish a difference in the shuffle icons.

**Comment by rogerl50** [comment]
Once it looks like this will be approved and merged, could you suggest a place in the Wiki for a discussion and write up a draft? (It would be great if you could actually include the icon images in the wiki.)

**Comment by mousewax** [comment]
> 

Yes. I will build a page with all of the glyphs and their names.

**Comment by 96LawDawg** [comment]
Created a room in this server with all the icons just to see them in action and with color.  I also was testing their placement on buttons.  Tried to use the image version rather than the text.  Not sure why I would want to do that because the text works so well.  But I couldn't get the image version to load.  Not sure what I did wrong.  http://212.47.248.129:3935/LawDawg

**Comment by mousewax** [comment]
> Created a room in this server with all the icons just to see them in action and with color. I also was testing their placement on buttons. Tried to use the image version rather than the text. Not sure why I would want to do that because the text works so well. But I couldn't get the image version to load. Not sure what I did wrong. http://212.47.248.129:3935/LawDawg

You were linking to `/assets/icons/die.svg` which gives an error. On a running server everything in `/assets/` is served served through `/i/` like `/i/icons/die.svg`. It's working now.

**Comment by 96LawDawg** [comment]
You want to take a shot at the JSON menu icons as well?  Don't have to custom design anything; just replace with Material glyphs.  

Speaking of which, I don't think I'm a fan of the [face] as the seat icon.  Looks strange that small and in that place.  I found some seat glyphs in Material, one of which I used in the seat's tutorial library image.  Something like that would be better, in my opinion.

**Comment by mousewax** [comment]
> 

I do think I like that seat icon. I will add it. How do you feel about the one I just added (before I read your comment)?

**Comment by 96LawDawg** [comment]
I don't think the new one is much better.  To me, when I look at the icon, I only see the dark area.  It looks like a slightly lopsided bicycle seat.  Only when I concentrate do I see the face.  It's like one of those visual tricks that if you look at it one way you see two faces, if you look at it another, you see a vase.

**Comment by mousewax** [comment]
> 

New add seat is in. I also added tutorial and help icons.
image

**Comment by rogerl50** [comment]
The font in the editing column in the JSON editor is larger, and the font in the F-key row smaller, than in production. IMO neither of those changes is desirable.

**Comment by mousewax** [comment]
> The font in the editing column in the JSON editor is larger, and the font in the F-key row smaller, than in production. IMO neither of those changes is desirable.

That was a testing implementation as I was troubleshooting why the symbols were not showing up in Safari. That has been reverted.

**Review by RaphaelAlvez — APPROVED** [review]
Tested and some code review. Looks awesome!!

**Comment by rogerl50** [comment]
Now that it looks like this will be merged soon, could you draft a set of wiki changes? It should probably cover all of the capabilities described in the original post. Happy to help if you want.

**Review by 96LawDawg — APPROVED** [review]
Approved through test.

**Comment by 96LawDawg** [comment]
There is one thing I noticed that I wanted to mention.  In the JSON editor, some of the first listed commands have a hotkey (or whatever it is called) underlined and in a different color.  We used to have that in production but did away with it when we went to all buttons.  I don't think they even work anymore.  I tried various combinations of shift, alt, and ctrl and nothing happened.  Can we get rid of that visual distraction?

**Comment by mousewax** [comment]
> There is one thing I noticed that I wanted to mention. In the JSON editor, some of the first listed commands have a hotkey (or whatever it is called) underlined and in a different color. We used to have that in production but did away with it when we went to all buttons. I don't think they even work anymore. I tried various combinations of shift, alt, and ctrl and nothing happened. Can we get rid of that visual distraction?

I think the styling should be left, but I'd those things are no longer working in the code, the code should be updated to reflect that. This way, if the functionality should make a return, the styling is already there. I will look to see if I can find where that's defined.

**Comment by 96LawDawg** [comment]
#616 should help narrow it down.

**Pull request merged**
