### PR TITLE
Update tutorials and Chinese Checkers

### PR DESCRIPTION
**Pull request by 96LawDawg**
Public Tutorials:
- Functions – GET. Completely redone to demonstrate all the aggregation modes
- Button Appearnace. Added a third variant covering css shapes
- Grid. Add a fourth variant covering the new ability to change almost any property with grids
- All button tutorials; changed the image once again. This time the border is dark blue instead of black.

Public Library:
- Chinese Checkers: added dropLimit to each holder and added name labels for each position for both variants.  Considered Raphael’s suggestion to change the shiny black marble, but decided against it because I like the way it looks as is

Changed library.json to reflect changes to tutorial variants

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3429/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment]
All changed items successfully loaded from public library.

**Comment by RaphaelAlvez** [comment]
> All button tutorials; changed the image once again. This time the border is dark blue instead of black.

Sorry for that but they do look better

**Review by RaphaelAlvez — APPROVED** [review]
Everything as described.

I would prefer having the get tutorial being divided into two variants

**Comment by 96LawDawg** [comment]
No problem on the images. I should have gotten that right the first time. As for the GET tutorial feel free to change it and I’ll upload it.

**Comment by RaphaelAlvez** [comment]
It is approved. I'll not make it anytime soon.

**Pull request merged**
